### ISSUE TITLE
Metadata variables are interpreted as markdown

### ISSUE THREAD

**Issue by mister-goo** [jgm/pandoc#10078]
**Explain the problem.**

Metadata variables are interpreted as markdown. This results in undesired HTML. Is this the intended behavior?

Markdown input:

```markdown
---
pagetitle: A `quoted`
description-meta: A `quoted`
...
```

Command: `pandoc -f markdown -t html5 -s test.md -o test.html`

HTML output:

```html
  <meta name="description" content="A <code>quoted</code>" />
  <title>A <code>quoted</code></title>
```

**Pandoc version?**
pandoc-3.1.13

**Comment by jgm** [comment]
Yes, it's intended (and documented) behavior.

There are ways to work around this if you actually just want to pass in a literal string.  The intended method for passing in a literal string to a template is to use `--variable` (or `variables` in a `--defaults` file).  Those are not interpreted as markdown.  But if you really want to use a metadata field, you can use the `raw_attribute` syntax to indicate that it is a raw string in your desired output format, e.g.

```
pagetitle: '`` A `quoted` ``{=html}'
```

In this case another option would be to use `&#96;` instead of the `` ` `` characters; this would not cause the string to be interpreted as a code element.
