### ISSUE TITLE
Markdown writer: keep HTML comment at end of file — e.g. Vim modeline.

### ISSUE THREAD

**Issue by bpj** [jgm/pandoc#10133]
**Problem**

When “converting” from markdown to markdown, which is very handy for cleaning up Markdown source, a RawBlock containing (only) an HTML comment at the end of file, which is where Vim expects to find its [modeline], doesn’t stay at the end of file if there are any reference link or note definitions[^1] thus breaking the modeline functionality in Vim.

[^1]: Either in the document as a whole, in the last section or in the last block, depending on the value of `--reference-location`.

  [modeline]: https://vimhelp.org/options.txt.html#modeline

**Proposed solution**

My proposed solution is that the markdown writer (and perhaps other writers which can preserve comments in some form) checks whether the last thing in the body of the document is a RawBlock containing (only) an HTML comment and if so places it after any link or note definitions so that it stays at the end of file.

I don’t think that it is needed or even desirable to check specifically for a Vim modeline in such a comment, since it might be useful for other things, like “hiding” note and link definitions/URLs when no reference to them has yet been placed in the document.

**Alternative solutions**

There are none which don’t involve the Vim format plugin or autocommand mechanism, which needs setting up on each machine/device you might use,[^2] or setting the relevant Vim options manually all the time, which is what modelines are meant to make unnecessary.

[^2]: FWIW keeping your dotfiles on GitHub and clone them to various machines/devices might not work. For example the way things work on a regular Linux system and when running Termux on an Android device are different enough that e.g. custom commands for invoking pandoc may not be portable.

Placing the modeline at the top of the file doesn’t solve the problem since there it is liable to be “pushed down” by metadata.

**Comment by jgm** [comment]
Relocating an HTML comment like you suggest seems too unprincipled to me.

Have you considered just adding the modeline with `--include-after-body`?

**Comment by bpj** [comment]
Nice idea but it won't work: it will create a duplicate each time I reformat because the modeline must be at the bottom of the file when the file is loaded. It might work to have a filter remove it from the bottom of the body and put it into meta.include-after but it seems fragile.

**Comment by alerque** [comment]
@bpj Keeping an [`.editorconfig`](https://editorconfig.org/) file in each project with my preferred options for editing Markdown is my solution to this problem. It stays with the project instead of the user, and also works across editors. NeoVIM uses it out of the box, and plain VIM has several plugins that add support.

**Comment by bpj** [comment]
@alerque unfortunately one of the Vim options I like to set for my Markdown files is 'colorcolumn' (unsurprisingly to the same value as 'textwidth') and editorconfig doesn't support that. If there were an editorconfig plugin for Vim which allowed me to set the equivalent of a modeline I would use that. I have tried some plugin meant to allow you to have a per-project .vimrc but haven't been able to get it to work properly.

**Comment by alerque** [comment]
I hear you, that's an option I use too. And yes, the set supported by EditorConfig is limited — but I would argue that it is limited for a good purpose. It is limited to settings that directly affect the *contents* of the files as implemented in editor settings. That is a subset of editor settings, not anything that a user could configure. For example it can set whether or not to automatically trim empty white space at the end of lines (definitely something I *disable* for Markdown but enable for almost all code) but it cannot set whether or not my editor has syntax highlighting enabled or not.

I would argue the CursorColumn setting is *not* related to the data that will get saved in a file and hence has no relevance to keeping a team on the same page as far as the content they are collaborating on. It is not project related, it is very much a user interface preference and hence *belongs* in the user's dotfiles, not the project (or file). I would set that up in my vim rc in the block of settings I enable for all prose-like file types.

As such I tend to agree with @jgm that adjusting the output writing to special-case the output format in a way that *could* break some input/outputs just so that it *can* be overloaded to mean something outside the scope of the document entirely does not seem like a good idea.

All that being said...

You know you can just put the modeline at the *top* of the file right? I would put it inside a YAML meta data block and use a YAML comment to hide it if you really must put user interface preferences in your document content.
