### ISSUE TITLE
[RFE] Font colors via filter

### ISSUE THREAD

**Issue by Hi-Angel** [jgm/pandoc#10144]
**Describe your proposed improvement and the problem it solves.**

There's a popular usecase of changing background/foreground colors. Pandoc makes it kind of possible via external means, such as CSS for HTML or some kind of templates for office formats, but there isn't anything consistent that would be applicable to all supported formats. For example, [this question](https://stackoverflow.com/q/32755607/2388257#convert-html-to-docx-using-pandoc) has 23k views at the moment and no useful answer *(the only answer that could possibly work is one that suggests using `--reference-doc`, but it's completely unclear how to e.g. combine it with a Lua filter to conditionally apply styling to Markdown `Para`s)*.

Would be great if Pandoc supported a way to set foreground and background colors on arbitrary elements, and that would then get propagated to any supported output format.

**Describe alternatives you've considered.**

Markdown + CSS is what I'm using. But it doesn't work for converting to an office format.

**Comment by jgm** [comment]
Right now we consider color a formatting detail, not part of the structure of the document pandoc is charged with preserving.

Adding support for color would require modifications to jgm/pandoc-types and a massive amount of work on all the readers and writers -- not to mention the wider pandoc ecosystem.

Apart from the work involved, I am not convinced that this is something we *should* support -- pandoc has to have limited ambitions, in order to be able to cover so many formats.

In your case (producing docx), you might look up pandoc's documentation on custom styles for docx.

**Comment by Hi-Angel** [comment]
> In your case (producing docx), you might look up pandoc's documentation on custom styles for docx.

I read that *(and even used long ago)*, but in the current context I am not clear how to communicate to the Lua filter that I want to have certain style/color from the reference docx to be applied. I have a Markdown document and I want to use Lua filter to highlight in yellow every paragraph that starts with `📝` emoji. [I have a filter](https://github.com/Hi-Angel/notes-backup/blob/4b6cd8826933e939e42218f7453abca8a850d830/pandoc.md#lua-filter) that does that, but it has no effect for DOCX output. You're saying I can use reference docx. Okay, but how do I handle that in the filter then?

**Comment by jgm** [comment]
The reference doc would define a style (say "Foo") with the highlighting.
The lua filter would add `custom-style="Foo"` attributes to each paragraph that starts with the emoji.
