### ISSUE TITLE
Citation format is wrong

### ISSUE THREAD

**Issue by raffaem** [jgm/pandoc#10191]
**Explain the problem.**

Given the following documents:

test.md:
```
---
title: "Title Here"
bibliography: bibliography.bib
---

# Abstract

Lorem ipsum [@europeanresearchcouncilForesightUseImpact2023]

# References

<div id="refs"></div>
```

bibliography.bib:
```
@book{
  europeanresearchcouncilForesightUseImpact2023,
  title={Foresight: Use and impact of Artificial Intelligence in the scientific process},
  url={https://erc.europa.eu/sites/default/files/2023-12/AI_in_science.pdf},
  author={European Research Council},
year={2023} }
```

and the following command line:
```
pandoc --from markdown --to pdf --csl https://www.zotero.org/styles/elsevier-harvard --citeproc --output test.pdf test.md
```

(csl to be found [here](https://www.zotero.org/styles/))

pandoc  renders it as `(Council, 2023)` inline and `Council, E.R., 2023` in the references:
![image](https://github.com/user-attachments/assets/73ab504d-86b0-4a22-bb02-dc1d29148dba)

while LibreOffice, with the same CSL, renders it as `(European Research Council, 2023)` inline and `European Research Council, 2023` in the references:
![image](https://github.com/user-attachments/assets/8cac0caa-1d4e-4ed9-b466-ce890fcaf4cd)

I believe the correct way is the second.

**Pandoc version?**
```
➜  pandoc --version
pandoc 3.1.9
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/raffaele/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
The issue is with conversion from bibtex. (Is your OpenOffice using a bibtex bibliographic source or a native CSL JSON one?)

Converting your bibtex using `pandoc -f bibtex -t csljson` yields
```
[
  {
    "URL": "https://erc.europa.eu/sites/default/files/2023-12/AI_in_science.pdf",
    "author": [
      {
        "family": "Council",
        "given": "European Research"
      }
    ],
    "id": "europeanresearchcouncilForesightUseImpact2023",
    "issued": {
      "date-parts": [
        [
          2023
        ]
      ]
    },
    "title": "Foresight: Use and impact of artificial intelligence in the scientific process",
    "title-short": "Foresight",
    "type": "book"
  }
]
```
Note this part:
```
    "author": [
      {
        "family": "Council",
        "given": "European Research"
      }
    ],
```
What is wanted is:
```
   "author": [
     { "literal": "European Research Council" }
   ]
```
(and if you use pandoc with this CSL JSON, it will give you the result you want).

Question: how is pandoc supposed to know, in converting from bibtex, that "European Research Council" is not a regular proper name, but the name of a corporate entity?  Pandoc is not an AI.

Solution:  enclose this in braces in your bibtex.

```
author = {{European Research Council}}
```
This is needed with LaTeX, too, to ensure that the whole thing is treated as a unit.

**Comment by raffaem** [comment]
Uhm BetterBibTex Zotero plugin exports authors like this:

```
@article{barnettGoodIntentionsDesigning2020,
  title = {Beyond {{Good Intentions}}: {{Designing CSR Initiatives}} for {{Greater Social Impact}}},
  shorttitle = {Beyond {{Good Intentions}}},
  author = {Barnett, Michael L. and Henriques, Irene and Husted, Bryan W.},
  date = {2020-07},
  journaltitle = {Journal of Management},
  shortjournal = {Journal of Management},
  volume = {46},
  number = {6},
  pages = {937--964},
  issn = {0149-2063, 1557-1211},
  doi = {10.1177/0149206319900539},
  url = {http://journals.sagepub.com/doi/10.1177/0149206319900539},
  urldate = {2023-04-17},
}
```

So the format is `surname, name and surname, name` etc.

Is the `name1 name2 name3 surname` format standardized?

My LibreOffice uses neither, just the Zotero LibreOffice plugin.

**Comment by jgm** [comment]
> So the format is surname, name and surname, name etc.

That's one way you can do it in bibtex, but not the only way.  Many bibtex files just use "First Middle Surname."  So pandoc can't assume that such things are corporate names; instead, we use heuristics to parse the names into surnames, etc.

Anyway, the solution to your problem is simple: either use a CSL JSON bibliography, which makes this explicit (and is what the Zotero plugin uses), or use the braces in your bibtex file.

**Comment by raffaem** [comment]
Thanks for bearing with me.

In reality I use Quarto with the RStudio Visual Editor, which exports from Zotero into a project-level .bib file.

I don't know whether it can export in CSL JSON.

Maybe I should open a bug report against RStudio asking them to quote names?

Of course the immediate workaround is to just add those quotes in the.bib file manually.

**Comment by jgm** [comment]
Yes, RStudio could probably do a better job in export. But you wouldn't want them to put braces around all names, just names that appear in CSL JSON as "literal".

**Comment by jgm** [comment]
I saw your bug report. You should amend it, I think. There is no need to do `{SURNAME}, {NAME}`.  Your suggestion should be that when the name field in CSL JSON uses "literal" instead of "family" and "given", the whole thing should be put in braces.  This will give more reliable behavior if the bibtex file ever needs to be used by pandoc or converted back to another format.

**Comment by raffaem** [comment]
I don't know what `CSL JSON` and `literal` are.

RStudio is exporting directly from Zotero, and this is what I see in Zotero:

![image](https://github.com/user-attachments/assets/1f9e63a7-f798-4347-a5e9-715644c67b74)

There is no "literal", only author with name and surname

**Comment by raffaem** [comment]
Actually in Zotero there is a switch near author names that allow you to switch between one or two fields for author fields:

![image](https://github.com/user-attachments/assets/f600059b-4197-490f-aefb-3d9d8989a685)

If you switch to one field, it gets escaped when exported:

```
author = {European Investment Bank, },
```

I think this implements your literal/given-family distinction.
