### ISSUE TITLE
Markdown to Typst: Unnecessary semicolon if a hyperlink is followed by a non-whitespace character

### ISSUE THREAD

**Issue by jsx97** [jgm/pandoc#10240]
Pandoc 3.4, macOS Sonoma 14.5.

If converting from Markdown to Typst, if a hyperlink is followed by a non-whitespace character, e.g. a comma, period, colon, or semicolon, Pandoc adds unnecessary semicolon. The issue is similar to <https://github.com/jgm/pandoc/issues/10148>.

Markdown:

```
Lorem [ipsum](http://ipsum.com): dolor sit amet.

Source: <http://google.com>.
```

Typst, current output:

```
Lorem #link("http://ipsum.com")[ipsum];: dolor sit amet.

Source: #link("http://google.com");.
```

Typst, expected output:

```
Lorem #link("http://ipsum.com")[ipsum]: dolor sit amet.

Source: #link("http://google.com").
```

**Comment by jgm** [comment]
Here the semicolon is harmless, even if unnecessary.  Not like #10148 where the semicolon was causing undesirable results.

There are cases where the semicolon is needed.  For background, see #9252.

Perhaps pandoc could be smarter about when it is needed; for now, we have just been conservative (and it is particularly easy to do it this way, because we can use a `doclayout` combinator that inserts content only if followed by a non-space).
