### ISSUE TITLE
CLI can't pass files that include space with automated bash script

### ISSUE THREAD

**Issue by realhackcraft** [jgm/pandoc#10275]
**Explain the problem.**
I want to run `pandoc --top-level-division=chapter --toc -o .output/output.pdf title.md $(cat ordered_files.txt)`

where `cat ordered_files.txt` prints:

```
01\ manuscripts/01\ Chapter\ One/01\ abc.md
```

(The backslashes are contained in the file)

However, this doesn't work.

`pandoc: 01\: withBinaryFile: does not exist (No such file or directory)`

When I run `pandoc --top-level-division=chapter --toc -o .output/output.pdf title.md 01\ manuscripts/01\ Chapter\ One/01\ abc.md` there are no problems

**Pandoc version?**
pandoc 3.5
macOS 15.1

**Comment by jgm** [comment]
What happens if you do
```
ls $(cat ordered_files.txt)
```
?  If there is a problem there too (which there was in my test), it shows that this is not an issue with pandoc specifically.

**Comment by alerque** [comment]
You need to quote your command substitution: `pandoc ... "$(cat ordered_files.txt)"`. This has nothing to do with Pandoc, it is just the way shell expansion works in bash. The values generated by a command in command substitution are not processed the same way ones you type in the shell by hand would be.

Also you'll want to ether stop adding the `\ ` escape sequences to the text file in the first place or used `sed` or similar instead of `cat` to remove them.

If you are trying to output a series of file names from the same file you're going to have to get fancier. The shell construct you're trying just won't work like that. As @jgm suggested you can test this with `ls` easier.

Here is how you could do it if you had one file per line and did *not* use escape sequences for your spaces, just leave them as is:

```console
$ cat ordered_files.txt | xargs -d'\n' pandoc ...
```

**Comment by realhackcraft** [comment]
Thanks for the help with the bash! With your suggestion, a single file in ordered_lists.txt works. But not when the file contains multiple paths on different lines.
