### ISSUE TITLE
Wrong markdown table cell lines concatenation during docx conversion

### ISSUE THREAD

**Issue by banderlog** [jgm/pandoc#10315]
The problem in pandoc 3.5

This table, achieved from docx -> md conversion via pandoc
```
+:------------+:-----------:+:------------:+:-------------------------+
| ![](med     | ![](med     | ![           | test                     |
| ia/image11. | ia/image12. | ](media/imag | ![]                      |
| png)        | png)        | e13.png)     | (media/image14.png)      |
+-------------+-------------+--------------+--------------------------+
```

will fail backward md -> docx conversion with next errors:

```
[WARNING] Could not fetch resource med%20ia/image11.%20png: replacing image with description
[WARNING] Could not fetch resource med%20ia/image12.%20png: replacing image with description
[WARNING] Could not fetch resource media/imag%20e13.png: replacing image with description

```

because it concatenates strings with single space character

**Comment by jgm** [comment]
The problem is that the cells aren't wide enough for the content, so pandoc has to break them in a way that affects the syntax.

One way to fix that would be to use `--columns=120` (or some other large number), which would cause the markdown writer to make the table cells wider. Of course, this might also have undesirable effects elsewhere in your document.

You could also try using `--reference-links`, which might produce shorter links that would fit.

**Comment by banderlog** [comment]
`--wrap=none` also works
