### ISSUE TITLE
RST: Option Lists not supported

### ISSUE THREAD

**Issue by ZoomRmc** [jgm/pandoc#10318]
An **[Option Lists](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#option-lists)** are a part of reStructuredText specs. Superficially looking I couldn't find any information on when it was included in the specs.

The following block (that adheres to the Option List specs) is currently read as a Definition List and a paragraph.

```rst
-a      Line
        Next-line
-b arg  Next-option
```

```
[ DefinitionList
    [ ( [ Str "-a" , Space , Str "Line" ]
      , [ [ Para [ Str "Next-line" ] ] ]
      )
    ]
, Para
    [ Str "-b" , Space , Str "arg" , Space , Str "Next-option" ]
]
```

I'm not sure if it's a bug or a feature request, as I'm not particularly interested in this part of the specs being supported. This issue is supposed to document pandoc not following the specification. I'm OK with closing it as not-planned or tagging as low-importance.

The **main** motivation for raising this issue is that *I couldn't find any indication that this feature is not supported in pandoc docs*. I think the docs should include a section which lists the cases where pandoc does not follow the specs of the supported formats (at least for readers) and known limitations of pandoc's native representation. If it's OK with the maintainers, I can either create a separate issue with this request or start small and make a PR with this addition to the docs.

**Comment by jgm** [comment]
I think we could fairly easily support option lists.

Documenting all the reST features we don't support might be interesting, but I don't think it goes in the manual because it might be quite long, and because it would be odd to include this without similar sections about every other format (and that would be *really* long).  We could think about including a separate document on the website, the way we have a document about Org-mode support.

**Comment by ZoomRmc** [comment]
Perhaps a convenient place for a permanent list of spec deviations is a big tracking issue right here that can be referenced and edited as things get implemented. It's also beneficial for potential contributors.
