### ISSUE TITLE
Python filter on windows

### ISSUE THREAD

**Issue by larmarange** [jgm/pandoc#1096]
When applying a python filter on Windows, I have the following error:

```
pandoc.exe: Error running filter ./comments.py
./comments.py: createProcess: invalid argument (Exec format error)
```

Python is installed and available in the path.
It seems that only .exe filter are accepted.

**Comment by paulsmirnov** [comment]
Are you sure that the issue is fixed? I'm testing **pandoc.exe 1.15.0.6** and both problems arise:

- cannot find `caps.py`, runs only via `caps.bat`,
- when python script finishes processesing, `Failed reading: satisfyElem` error is raised.

caps.py:
```
"""
Pandoc filter to convert all regular text to uppercase.
Code, link URLs, etc. are not affected.
"""

from pandocfilters import toJSONFilter, Str

def caps(key, value, format, meta):
    if key == 'Str':
        return Str(value.upper())

if __name__ == "__main__":
    toJSONFilter(caps)
```

caps.bat:
```
python caps.py %*
```

test.md:
```
Hello!
```

test.bat:
```
pandoc.exe test.md -o test.html --filter=caps.py

pandoc.exe test.md -o test.html --filter=.\caps.py

pandoc.exe test.md -o test.html --filter=.\caps.bat
```

output:
```
W:\Sandbox\pandoc>pandoc.exe test.md -o test.html --filter=caps.py
pandoc.exe: Error running filter caps.py
W:\Sandbox\pandoc\caps.py: createProcess: invalid argument (Exec format error)

W:\Sandbox\pandoc>pandoc.exe test.md -o test.html --filter=.\caps.py
pandoc.exe: Error running filter .\caps.py
W:\Sandbox\pandoc\caps.py: createProcess: invalid argument (Exec format error)

W:\Sandbox\pandoc>pandoc.exe test.md -o test.html --filter=.\caps.bat
pandoc.exe: Failed reading: satisfyElem
```

**Comment by paulsmirnov** [comment]
When I modify `caps()` function:
```python
def caps(key, value, format, meta):
    import sys
    sys.stderr.write('{key}: {value}\n'.format(key=key, value=value))
    if key == 'Str':
        return Str(value.upper())
```

then I get output:
```
W:\Sandbox\pandoc>pandoc.exe test.md -o test.html --filter=.\caps.bat
Para: [{'c': 'Hello!', 't': 'Str'}]
Str: Hello!
pandoc.exe: Failed reading: satisfyElem
```

so it seems that filter is applied and the error is at a later stage.

**Comment by riverar** [comment]
```
pandoc 1.15.0.6
Compiled with texmath 0.8.2.2, highlighting-kate 0.6
```

I've found using ``./script.py`` instead of ``.\script.py`` resolves the matter for [scripts that are supported by findExecutable](https://github.com/jgm/pandoc/blob/3fe6b57b60962ec531fe775052d16f0baa8ef120/pandoc.hs#L108-L114) like python, ruby, etc. But items that require bouncing through an intermediate (e.g. cmd.exe) cause the satisfyElem error to surface.

This renders pandoc-filters (nodejs) unusable.

Suspect it's a bug in System.Directory or System.IO but I don't know much about staging a Haskell environment to debug this.

**Comment by AliHeggie** [comment]
I am also getting the error: "createProcess: invalid argument (Exec format error)" when trying to use caps.py and tikz.py filters (I have not tried any others).

Wrapping the filter in a .bat file like this, "python tikz.py %*" I get a different error: "Error in $: Failed reading: not a valid json value"

**Comment by jgm** [comment]
What version of pandoc, and what command, exactly, are you
using?

+++ AliHeggie [Sep 19 16 07:23 ]:

**Comment by AliHeggie** [comment]
I am using pandoc-1.17.2

I do 
`pandoc` --filter tikz.py tikz-sample.md -f markdown -t html -o -tikz-sample.html``

**Comment by jgm** [comment]
Is python in your path?  Can you try with `./tikz.py` instead  of `tikz.py`?
Also, I'm assuming the hyphen before the output file name is a typo.

**Comment by AliHeggie** [comment]
Python is in my path and the extra hyphen is a typo, oops.

I tried `./tikz.py` on the sample and it works. Which is great. I still have problems using the filter how I want to, but possibly this is just me using it incorrectly rather than any bug.

I have copied tikz-sample.md to another directory and added pandoc filters to my path. If I try do `pandoc --filter ./tikz.py tikz-sample.md -f markdown -t html -o tikz-sample.html` in this location pandoc reports that `./tikz.py` was not found, as expected. 

If I use just tikz.py it again fails with: 

`pandoc.exe: Error running filter tikz.py
[mypath]/tikz.py: createProcess: invalid argument (Exec format error)`

So presumably it is able to find the filter. However, if I copy tikz.py to this new location and then use ./tikz.py I get a long error which ends like this:

`("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\frontendlayer\tikz\
s\tikzlibrarytopaths.code.tex")))
No file tikz.aux.
ABD: EveryShipout initializing macros
("C:\Program Files (x86)\MiKTeX 2.9\tex\context\base\supp-pdf.mkii"
[Loading MPS to PDF converter (version 2006.09.02).]
) ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\oberdiek\pdftexcmds.s
("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\oberdiek\epstopdf-base.st
("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\oberdiek\grfext.sty"
("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\oberdiek\kvdefinekeys.s
("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\oberdiek\kvoptions.sty"
("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\oberdiek\kvsetkeys.sty"
("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\oberdiek\etexcmds.sty")
[1{C:/ProgramData/MiKTeX/2.9/pdftex/config/pdftex.map}] (tikz.aux) )<C:
 Files (x86)/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on tikz.pdf (1 page, 11064 bytes).
Transcript written on tikz.log.
Invalid Parameter - /tikz.pdf
Created image tikz-images\bb4ca6ef38e388bee5236368e2ae316cc8af1ed4.png`

**Comment by jgm** [comment]
Manual says:
```
    Note that the *EXECUTABLE* will be sought in the user's
    `PATH`, and not in the working directory, if no directory is
    provided.  If you want to run a script in the working directory,
    preface the filename with `./`.
```
So, you can either (a) make tikz.py executable and put it in your path, or (b) specify the path to tikz.py on the command line (./tikz.py if it's in the working directory).
