### ISSUE TITLE
Pandoc expands LaTeX macros with extra layer of { }s

### ISSUE THREAD

**Issue by dubiousjim** [jgm/pandoc#1390]
I just noticed that Pandoc's internal processing of LaTeX macros in math mode wraps the expansion in an unexpected additional layer of `{ }`s---at least it does so for output to HTML using MathJax.

Here's a minimal working example:

```
\newcommand\foo{+}
Testing: $\mu\foo\eta$.
```

HTML will contain:

```
<p>Testing: <span class="math">\(\mu{+}\eta\)</span>.</p>
```

(This would also be true if we had instead said `\newcommand\foo\alpha`, without using `{ }`s in the definition.)

I can get myself into the mindset where this would seem like a good idea, to avoid the expanded text getting smushed together with something following it and then wrongly interpreted. But are there are any cases where that could really happen? Won't the subsequent text already have to start with whitespace, or a `\` or a `}` or something else, for Pandoc's lexer to have stopped reading `\foo` in the first place?

The downside of the existing behavior is that it messes up the math spacing. `\mu+\eta` will be spaced properly, with `+` interpreted as a `mathrel`; whereas `\mu{+}\eta` will be spaced smushed together, with `{+}` interpreted as a `mathord`.

**Comment by lierdakil** [comment]
Here's one relatively crazy idea: would implementing "honest to god" LaTeX parsing (f.ex. with [HaTeX](https://hackage.haskell.org/package/HaTeX)) help with this and probably other LaTeX-related issues? Just thinking out loud.

**Comment by lierdakil** [comment]
Disregard that about HaTeX, it seems its parser is rather basic, so it's not going to help much.

Anyway, I think this issue is pretty much unsolvable, unless we know exactly how many arguments a given LaTeX command has, since argument expansion pretty much depends on it.

Consider, for example,
```latex
\newcommand{\plus}{plus}

$$\mu\plus\gamma$$

vs

$$\hat\plus\gamma$$
```
Former case doesn't need any additional grouping, while latter does.

Given an unholy number of various LaTeX packages and commands in existence, I don't think it's very reasonable to hard-code those. And I don't really see any other "valid" options short of reimplementing LaTeX in Haskell from ground up.

We could, however, settle for some random convention, e.g. if a macro token is immediately preceded with command or `}`, then expansion would be surrounded by `{}`, otherwise, if there is a space, or other characters (including `{`) between command/`}` and token, it won't. It's a simple heuristic, and probably won't be sufficient in some more difficult cases, but hey, it's a start.
