### ISSUE TITLE
Nook Simple Touch "exception" when open EPUB build with pandoc

### ISSUE THREAD

**Issue by rgaiacs** [jgm/pandoc#1396]
I built a EPUB from HTML using pandoc

```
$ wget https://raw.githubusercontent.com/r-gaia-cs/bc/bug-nook/book-text-only.html
$ pandoc -f html -t epub -o book-text-only.epub book-text-only.html
```

but when try to read it at my [Nook Simple Touch](http://en.wikipedia.org/wiki/Nook_Simple_Touch) a unknown "exception" make the EPUB close before it open or right after it. (The same EPUB works fine at Calibre, FBReader and Readium.)

After playing with some of pandoc options, one that work was

```
$ pandoc -f html -t epub --toc --toc-depth=2 --epub-chapter-level=2 -o  book-text-only.epub book-text-only.html
```

I couldn't reproduce this issue when build very small examples and didn't found any strange when looking at the diff from the two EPUBs.

**Comment by Gumnos** [comment]
I had similar issues and can pretty readily reproduce similar results (it doesn't crash the Nook Simple Touch, but does get considered an invalid document):

    $ curl -s https://dev.mutt.org/doc/manual.html > mutt_manual.html
    $ sha256sum mutt_manual.html 
    9958c6316fbc94c4ef83a1d5ae71f4d53e1908960bcc144c5134c662410f7d8a  mutt_manual.html
    $ pandoc -f html -t epub -o mutt_manual.epub mutt_manual.html
    $ mount /media/nook
    $ mv mutt_manual.epub /media/nook
    $ umount /media/nook

Attempting to open the file on the Nook Simple Touch results in the first page being partially rendered (with just the H1 of "The Mutt E-Mail Client" calculated as page 1/165; the total number of pages sounds reasonable) but then an error dialog covers it.  The error reads 

> Error Dialog
> Sorry, cannot open this book
> [OK]

Clicking the `[OK]` button returns me to my library.

I tried @rgaiacs' extra `pandoc` parameters which at least resulted in a file that could be opened without error, but it was pretty horribly mangled (looks like list-items in the ToC may have had improper styling applied, so they were run-on as if they were inline-block rather than each on its own line) and paging through the output looked nothing like the original HTML file.  Also, after several page-downs, the page-number jumped from something less than 20 to >160 without touch any of the intermediate pages.

In case this matters, my `pandoc` is stock on Debian Stable:

    $ pandoc --version | head -1
    pandoc 1.17.2

I'm not 100% certain this is the *exact* same issue, but this was the closest Google hit I could find while attempting to research it.  I can create this as a new issue if needed.

**Comment by jgm** [comment]
You're using a very old version of pandoc.  I suggest trying
with the latest release (there's a linux deb available
at the GitHub downloads page for jgm/pandoc).

But, looking at the mutt_manual.html, I think there will
still be problems.  Pandoc's algorithm for breaking
documents into epub chapters assumes that there will be
header (h1, h2, etc.) elements at the top-level, not buried
under layers of divs.

For a possible fix, see https://github.com/jgm/pandoc/pull/3712

Also, pandoc creates its own table of contents, so you'll
want to strip off the TOC in the HTML before running it
through pandoc.

+++ Tim Chase [Jul 30 17 19:59 ]:
>   I had similar issues and can pretty readily reproduce similar results
>   (it doesn't crash the Nook Simple Touch, but does get considered an
>   invalid document):
