### ISSUE TITLE
Levels 2-3 of Bulleted Lists in odt have a missing character

### ISSUE THREAD

**Issue by bexelbie** [jgm/pandoc#1400]
Levels 2-3 of bulleted list get a bad bullet character.

Image attached

Markdown:
- Level 1-a
  - Level 2-a - BROKEN BULLET
  - Level 2-b - BROKEN BULLET
    - Level 3-a - BROKEN BULLET
      - Level 4-a
    - Level 3-b - BROKEN BULLET
  - Level 2-c - BROKEN BULLET
- Level 1-b

![screenshot from 2014-07-03 16 54 51](https://cloud.githubusercontent.com/assets/7413661/3471327/080a4e72-02c2-11e4-94a3-2bbc9baa49c4.png)
## 

pandoc 1.12.3.3
Compiled with texmath 0.6.6.1, highlighting-kate 0.5.6.

**Comment by gawrysz** [comment]
I just run into same problem. Default combination of characters and fonts results in some placeholder printed instead of bullets for levels 2, 3, 5, 6, 8 and 9 when I use the .odt output in Linux. IIRC on Windows machine there were correct bullets displayed in the same file

After unzipping and opening content.xml in emacs I saw "‣" and "⁃" defined as bullet characters for the problematic list levels. I created a fresh .odt with LibreOffice 5 and saw that somewhat different characters were used there by default.

My temporary fix for broken bullet characters is to process content.xml through `sed -i 's/‣/◦/g;s/⁃/▪/g'` inside Makefile but it is far from elegant and I have no idea how bulletproof it is ;-) I just hope these findings can shed some light on the issue.

**Comment by jgm** [comment]
What were the default bullet characters for linux LibreOffice 5?

+++ Artur Gawryszczak [Mar 13 17 15:22 ]:

**Comment by gawrysz** [comment]
In Libreoffice I've found the ones, which I used in sed: 
* "◦" for levels 2, 5 and 8
* "▪" fof levels 3, 6 and 9

**Comment by jgm** [comment]
If you can verify that this produces odts that work on
both LibreOffice/Linux and LibreOffice/Windows, I'd be
happy to make the change.

+++ Artur Gawryszczak [Mar 14 17 02:04 ]:
>   In Libreoffice I've found the ones, which I used in sed:
>     * "◦" for levels 2, 5 and 8
>     * "▪" fof levels 3, 6 and 9

**Comment by gawrysz** [comment]
Yes, after replacing bullets inside content.xml from "‣" and "⁃" to "◦" and "▪" with sed, the .odt files (and .pdf converted from .odt) look the same and are displayed correctly on both my computers at work (Ubuntu 14.05 LTS and Windows 10) and a machine with Fedora 25 at home.

I've got an idea for a nice feature. If there was an option to feed pandoc with a string made of characters intended to be used in bullet lists it would give more control and provide a solution on computers with strange font collections (such as localized to national languages). Something like `pandoc --bullet-chars="•◦▪"`.
