### ISSUE TITLE
inline code containing _ leads to an error in pdf output but works fine in html output

### ISSUE THREAD

**Issue by helferthomas** [jgm/pandoc#1613]
Hi, my name is Helfer Thomas. I am a new user to pandoc.

I am trying to create a slideshow using pandoc. The following pandoc-markdown code leads to an error in pdf output but not in html output :

- removing code introduced in the standard
    - `enable\_if`{.cpp}, `typetraits`{.cpp}, `shared\_ptr`{.cpp}

I am using pandoc 1.12.4.2.

I used to following command to build the pdf:

pandoc -f markdown+tex_math_single_backslash --slide-level 2 --toc -t beamer -V theme:Warsaw test.md -o test.pdf

I used this command to build the html output :

pandoc -s -f markdown+tex_math_single_backslash  --slide-level 2 --toc --mathjax -i -t revealjs -V theme:night test.md -o test.html

Helfer Thomas

**Comment by olivuntu** [comment]
Hello, 
I am posting here because I've recently had the same issue using pandoc to produce beamer slideshows and found this thread. I was wondering if there is progress ? Would it be possible to add a 'fragile' option to markdown elements converted into frames for instance ? Message from @mszep suggests that pandoc already includes this, but it does not seem to perform well. But wonderful toolbox anyway !
