### ISSUE TITLE
Support variables in template includes

### ISSUE THREAD

**Issue by mietek** [jgm/pandoc#1638]
It would be nice to have an option to support variables in template includes, i.e. `--include-in-header`, `--include-before-body`, `--include-after-body`.

This was (briefly) proposed before in #812, with no discussion, and also led to #909.

**Comment by eberkund** [comment]
I would also be interested in this feature

**Comment by edusantana** [comment]
Hi @cboettig, here's a workaround.

What happens if the run pandoc with *just a YAML block*? It will try to replace the yaml variable at the *current template*.

Now you can design your a custom header template, run it with just the YAML file and generate a new file to include with `--include-in-header`.

It will do the work.
