### ISSUE TITLE
Syntax for columns in presentations.

### ISSUE THREAD

**Issue by 9peppe** [jgm/pandoc#1710]
I believe it is necessary, even the beamer manual tells users to use columns in frames (§5.1.3).

Alternatives I have in mind are:
- syntax for divs in #168, with `{.column width=xx%}`;
- using the three-dotted syntax used in `stmd` for side by side examples.

**Comment by N4M3Z** [comment]
What is the progress on this? Something along the lines of `{.column width=xx%}` seems like the way to go. Can we help with implementing it?

**Comment by jgm** [comment]
I like the div solution on the input side.  What I'd need to know is what the output should look like in all of the slide show formats we support, or as many of them as support it -- but, at least, beamer and revealjs.

**Comment by jgm** [comment]
I assume that in revealjs and other HTML formats we can use CSS to position things --- either floats or, probably more reliably,

``` html
<div style="display: inline-block; width: 50%; vertical-align: top;">
</div>
```

but I haven't actually tested this.  In fact, it might be sensible to support this in all HTML output (whether slide or not).

**Comment by N4M3Z** [comment]
For Beamer, two column output should look like this:
```
\begin{columns}
  \begin{column}{0.48\textwidth}
    Left column
  \end{column}
  \begin{column}{0.48\textwidth}
   Right column
  \end{column}
\end{columns}
```

There is a very nice summary of various options implemented by others: http://stackoverflow.com/questions/20847371/two-column-layouts-in-rstudio-presentations-slidify-pandoc

I like the R studio solution a lot.

**Comment by jgm** [comment]
So, for beamer, if we have `<div class="column" width="N%">`, do we always want `(N-1)\textwidth` in beamer?

**Comment by N4M3Z** [comment]
Hmm, I think not. If I am not mistaken, the width percentages need not add to `1`, LaTeX will simply not use the remaining space. Hence, we should be fine with specifying `<div class="column" width="N%">` as `N\textwidth`. Let me know if you want me to do some testing.

**Comment by jgm** [comment]
Another syntax possibility.  Currently, if you use a header with level (slidelevel + 1), you'll get a block environment.
```
\begin{block}{Header}

contents

\end{block}
```

We could set things up so that, if the main header for a slide has the class "columns", then subsidiary headers create columns instead of blocks:
```
# My slide {.columns}

## First column

contents

## Second column

contents
```
Widths could be computed automatically (unless there is a really compelling reason for being able to specify them manually.)  An empty header could be used if you don't want a subhead at the top of the column.  This approach would be more naturally syntax-wise, but a bit less flexible.

**Comment by N4M3Z** [comment]
I consider the ability to specify width essential. This is particularly useful for side-by-side figures of different proportions.

Concerning the syntax, personally I am not sure I like it since I might want to use both blocks and columns. I still have a problem once I start using blocks, there is no way to tell pandoc to end the block and continue writing text outside the block and I am afraid the same thing would happen here.

**Comment by jgm** [comment]
Looks like currently the "block syntax" breaks entirely if you put it inside a div.
So we may need more serious changes to the LaTeX writer to make this all work smoothly.

**Comment by N4M3Z** [comment]
I suggest to take the simplest approach to bring the column functionality at least partially to pandoc and taking care of blocks inside columns later. It is a very unlikely use-case I would say.

**Comment by barronh** [comment]
I can get basic usage with the multicol package.  I 

I added one use statement and two new commands to my beamer template.

```
\usepackage{multicol} 
\newcommand{\beginmulticols}[1]{\begin{multicols}{#1}} 
\newcommand{\stopmulticols}{\end{multicols}}
```

And tested with the habits.txt modification below
```
% Habits - Testing Multicol
% Barron
% 2016-05-05

# In the morning

## Getting up

\beginmulticols{2}

- Snooze alarm
- Roll over
- Snooze alarm
- Roll over
- Snooze alarm
- Roll over
- Snooze alarm
- Roll over

\columnbreak

- Turn off alarm
- Get out of bed

\stopmulticols

## Breakfast

- Eat ~~eggs~~ cereal
- Drink **coffee**

```

**Comment by kaspersoerensen** [comment]
That works well @barronh - but when using images in the columns it seems that the figure captions are removed.

**Comment by trou** [comment]
I think this functionnality would be awesome. I've been using a python [filter](http://stackoverflow.com/a/24040087), but the problem lies in practice in `block`:

```md

## Slide

[columns]

[column=0.5]

### block1

[column=0.5]

### block2

[columns]

```

will generate the following latex code:
```latex
\begin{columns}
\column{0.5\textwidth}
\begin{block}{Block 1}
text
\column{0.5\textwidth}
\end{block}
\begin{block}{Block 2}
text2
\end{columns}
\end{block}
```

As you can see, pandoc doesn't close the first block before adding the column (of course).
Two ways this could be solved:
* add a way for the python filter to close the current block (including updating the current pandoc state)
* add column support in haskell

**Comment by jgm** [comment]
I think you just need to take a different approach in your
filter.  One more straightforward approach would be to
match on header attributes.


    ## Slide {.columns}

    ### block1 {column=0.5}

    ### block2 {column=0.5}

**Comment by trou** [comment]
That's an interesting workround but it wouldn't allow for 2 different blocks in a columns

**Comment by jgm** [comment]
I think the div option is good, but this should be implemented for HTML formats too.

**Comment by mb21** [comment]
I agree that the div with a class seems to be the right vehicle for inputting this (both in markdown input and AST).

For HTML output, there are two options for the [necessary CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Using_multi-column_layouts) ([browser support](http://caniuse.com/#search=columns) includes IE>=11) Either:

    .column {
      column-count: 2;
    }

or:

    .column {
      column-width: 100px;
    }

**Comment by barronh** [comment]
The auto-flowing approach would need to be easily separated from the intentional flow. It is frequently the case that the left and right have intentional comparisons: pros vs cons; old results vs new results; etc.

The column-width approach does not work because the number of columns is not knowable and neither is the content. The column-count approach is better, but still the content of the columns cannot be specified.

**Comment by HaoZeke** [comment]
Surely with CSS Grid columns are a cinch in HTML as well... SO maybe this should be looked at again?

**Comment by mb21** [comment]
@Haozeke, this was implemented, see the commit referenced above

**Comment by henryiii** [comment]
@mb21 , I think @HaoZeke was looking at that comment, which shows it was added for LaTeX, and no other backends, like HTML. However, upon testing, the syntax in the release notes (almost) works.

There are two problems. The first is that the release note syntax has a 4 space indent, visually looks nice in the markdown but causes unformatted monospaced text.

The other problem is that blocks are not supported! So this fails to compile for beamer (failing hard):

```md
<div class="columns">
<div class="column" width="40%">
## Block one
- Item
</div>
<div class="column" width="60%">
## Block two
- Item
</div>
</div>
```

**Comment by mb21** [comment]
@henryiii You should probably open a new issues with the exact command used. If you have an idea how the generated LaTeX should look like, it would be great if you could post that as well...

**Comment by mb21** [comment]
@henryiii Have you looked at the discussion in https://github.com/jgm/pandoc/issues/816 ? I think this is currently expected behaviour...

**Comment by henryiii** [comment]
@mb21 , I believe this is a different issue - the section level is something that's a bit odd, but I'm used to it. Pandoc produces non-valid LaTeX if you put a heading of any sort in a div, and I believe it doesn't ever produce blocks. I'll open dedicated issues.

**Comment by zedsmith52** [comment]
I have been trying to attempt something similar - the html file I have is test.html containing:
<div class="col">
  column1
</div><div class="col">
  column2
</div>
<style>
.col {
  width: 40%;
  float: left;
}
</style>

Whatever I do, I cannot get pandoc to output two columns in docx or pdf.
I've tried tables, various css and although it works in html through a browser, pandoc just does not seem to be able to convert it.

On a side note, I also lose background images when I convert from html too.

Is this the same problem or something anyone has run into?

**Comment by henryiii** [comment]
Have you tried the pandoc 2 syntax? I use it heavily, but only tried it through the pdf output. (Use triple back ticks around what you are trying to keep github markdown from swallowing it up)
