### ISSUE TITLE
[Feature Request] Table format for multi-line tables

### ISSUE THREAD

**Issue by svenax** [jgm/pandoc#1737]
It would be great if Pandoc supported a table format where each cell can contain multiple paragraphs, that does not force manual alignment. This would be very useful when writing, for instance, wiki text.

Maybe it could be based on the [_MediaWiki_ format](https://www.mediawiki.org/wiki/Help:Tables):

```
{| *formatting directives*
|
Lots of text.

Multiple paragraphs.
|
More text
|-
|
Next table row
|
* Item 1
* Item 2
* Item 3
|}
```

**Comment by ickc** [comment]
Sorry, I don't quite understand this. Isn't what you ask already doable in grid table syntax? What does it mean by "not forcing manual alignment"? Do you mean the cell in grid has to be manually "wrap around"?

You could checkout my filter, pantable (in github.com/ickc/pantable), which could probably do what you need, albeit through a filter only.

I don't think syntax like you proposed, or the CSV syntax used in my pantable would make into official pandoc as a markdown syntax. It is just not in the philosophy of markdown (people had proposed to added CSV reader in pandoc, and CSV table syntax in pandoc markdown, but apparently they have been abandoned due to the non-markdown-ish nature of CSV).

**Comment by jgm** [comment]
Yes, agreed; I can see that this is easier to write, but Markdown focuses on source readability.
