### ISSUE TITLE
Docx Reader enhancements

### ISSUE THREAD

**Issue by s7726** [jgm/pandoc#1740]
https://github.com/Versal/word2markdown

Stumbled on this project. It looks like it may have been created in parallel with the docx reader in pandoc. As such I'm wondering what is needed to eliminate the need for the crazy script they put together. It seems like this is something pandoc alone should be able to solve.

**Comment by benbalter** [comment]
I run a similiar project (https://github.com/benbalter/word-to-markdown). I'd love to be able to remove most (all) of the code in favor of Pandoc (right now I use LibreOffice). The biggest issue right now is that even as a filter, I can't access font-size information from the original Word document. Is it possible to see the original font size of a given line of text? The JSON AST seems to only have the text and p tag.

**Comment by mpickering** [comment]
Pandoc only retains structural information about text rather than specifics such as font-size. Most of the output formats are plain-text so the concept doesn't make that much sense. It might be worth making a post to the mailing list with a more fleshed out description about what you want to use pandoc for.
