### ISSUE TITLE
Duplicate ToC entry from LaTeX to epub

### ISSUE THREAD

**Issue by larsga** [jgm/pandoc#1745]
In the LaTeX source I have this:

```
% ...
\section{Six favourite beers}
% ...
\subsection{Jovaru Alus}\label{jovaru-alus}
% ...
\section{Farmhouse brewers}
% ...
\subsection{Jovaru Alus}
```

In the nav.xhtml in the epub I then get:

```
            <li id="toc-li-25">
              <a href="ch002.xhtml#six-favourite-beers">Six favourite beers</a>
              <ol class="toc">
                <li id="toc-li-26">
                  <a href="ch006.xhtml#jovaru-alus">Jovaru Alus</a>
                </li>
                <li id="toc-li-27">
                  <a href="ch002.xhtml#seklycios">Piniavos Seklyčios</a>
                </li>
```

As you can see, the toc entry points to the second subsection titled "Jovaru Alus", not the first. Essentially the same problem recurs in toc.ncx, where the corresponding entry also refers to the second subsection.

As a result, conversion to .mobil by kindlegen fails.

**Comment by jgm** [comment]
Problem is that `reftable` at l. 500 is
```
[("six-favourite-beers","ch001.xhtml#six-favourite-beers"),("jovaru-alus","ch001.xhtml#jovaru-alus"),("farmhouse-brewers","ch002.xhtml#farmhouse-brewers"),("jovaru-alus","ch002.xhtml#jovaru-alus")]
```

**Comment by jgm** [comment]
OK, the real problem is with `registerHeader` in `Text.Pandoc.Parsing` (this is used, in this case, by the LaTeX reader).

When it finds a header without an identifier, then, if the `auto_identiifers` extension is set (as it is by default in this case), it autogenerates a header based on the header text.  It keeps a running list of header identifiers it has seen, and generates identifiers that are unique relative to this list.  But the identifiers it generates can still clash with (a) manually specified identifiers in headers it still hasn't seen in parsing and (b) identifiers on Divs, Spans, Images, and Links.

It's a bit hard to see how to fix this.  One option would be to generate the header ids only after parsing is finished, so we can test it against a complete list of manually specified ids.  This might have some performance implications.  Another option would be to create the automatically generated identifiers in such a way that they'd be unlikely to clash with anything, e.g. `pandoc0003`, but this is ugly.

I will explore the first approach.
