### ISSUE TITLE
Support the html "base"-tag

### ISSUE THREAD

**Issue by fredefox** [jgm/pandoc#1751]
Maintaining the integrity of hyperlinks of online `html`-documents would be a lot easier if `pandoc` had support for the [`base`-tag](http://www.w3schools.com/tags/tag_base.asp).

Inserting

    <base href="http://example.com"/>

In the `head`-section of the document and subsequently converting it would thus maintain the link-structure so a relative link on the page like say:

    <a href="somefile"/>

Would become a link to `"http://example.com/somefile"` in the resulting document.

**Comment by jgm** [comment]
Dup of #1670?

**Comment by fredefox** [comment]
I do believe it is a duplicate yes. Though in #1670 it looks as though it's relevant only to the EPUB-writer.

**Comment by fredefox** [comment]
Hello,

I might be interested in actually implementing this. If anyone could give me any pointers on how to
contribute. Especially wrt. this particular problem that would be welcome.

**Comment by lierdakil** [comment]
Short version:

1) Fork this repo
2) Clone forked version to your workstation
3) Create new branch to work on (`git checkout -b new-branch`)
4) Implement-commit-push. Do try to have meaningful commit messages, preferably prefixed with the component you changed (e.g. `HTML Reader: Support for <base> tag`). Bonus points for implementing tests for your feature. I also recommend rebasing on `master` before next step.
5) Create pull request. Actually I suppose you can create it at any point you need feedback, but it tends to become messy if you do this too early.

Bonus points for updating documentation (i.e. README)

That's for github side of things.

As for Haskell side of things... I assume you are somewhat familiar with Haskell development, know about cabal, cabal sandboxes, cabal tests. If not, do read up on cabal, it's an essential tool. I also assume you have a favorite editor set up for Haskell.

So, HTML Reader sources are in `src/Text/Pandoc/Readers/HTML.hs`. You'll probably want to extend `HTMLState` data structure with a new field to keep base url in. Then you'll probably want to extend `pHead` parser to actually handle `<base>` tag. Lastly, you'll want to update `pRelLink` and probably `pImage` parsers to use base url, by appending said base to relative urls. I'll leave it to your imagination on how to identify relative urls.
Tests are in `tests/`. Since html reader tests are rudimentary (actually, I think there is only one, and is described in `tests/Tests/Old.hs` at lines 89-90), you are free to create new `tests/Tests/Readers/HTML.hs`. I hope you are at least somewhat familiar with HUnit and TestFramework.

If you have further questions, feel free to ask. Have fun!

**Comment by fredefox** [comment]
It sounds great.

I will look into it and see what I can do. I am familiar with haskell.
Although I have not contributed to larger projects before. I have
limited knowledge of `cabal` and I see that I'd probably need to read
up on this to be able to figure out how to interact with the source.

As for testing, I have only used `quickcheck` (and hand-written unit-
tests).

On Mon, Apr 13, 2015 at 5:11 PM, Nikolay Yakimov <notifications@github.com>
wrote:

> Short version:
>
> 1) Fork this repo
> 2) Clone forked version to your workstation
> 3) Create new branch to work on (git checkout -b new-branch)
> 4) Implement-commit-push. Do try to have meaningful commit messages,
> preferably prefixed with the component you changed (e.g. HTML Reader:
> Support for <base> tag). Bonus points for implementing tests for your
> feature. I also recommend rebasing on master before next step.
> 5) Create pull request. Actually I suppose you can create it at any point
> you need feedback, but it tends to become messy if you do this too early.
>
> Bonus points for updating documentation (i.e. README)
>
> That's for github side of things.
>
> As for Haskell side of things... I assume you are somewhat familiar with
> Haskell development, know about cabal, cabal sandboxes, cabal tests. If
> not, do read up on cabal, it's an essential tool. I also assume you have a
> favorite editor set up for Haskell.
>
> So, HTML Reader sources are in src/Text/Pandoc/Readers/HTML.hs. You'll
> probably want to extend HTMLState data structure with a new field to keep
> base url in. Then you'll probably want to extend pHead parser to actually
> handle <base> tag. Lastly, you'll want to update pRelLink and probably
> pImage parsers to use base url, by appending said base to relative urls.
> I'll leave it to your imagination on how to identify relative urls.
> Tests are in tests/. Since html reader tests are rudimentary (actually, I
> think there is only one, and is described in tests/Tests/Old.hs at lines
> 89-90), you are free to create new tests/Tests/Readers/HTML.hs. I hope
> you are at least somewhat familiar with HUnit and TestFramework.
>
> If you have further questions, feel free to ask. Have fun!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgm/pandoc/issues/1751#issuecomment-92394867>.
>



-- 
Regards
*Frederik Hanghøj Iversen*

**Comment by jgm** [comment]
+++ Frederik Hanghøj Iversen [Apr 13 15 08:17 ]:
>As for testing, I have only used `quickcheck` (and hand-written unit-
>tests).

Take a look at Tests.Readers.LaTeX (which lives in the tests/
directory).  You could us this as a model for Tests.Readers.HTML.

**Comment by lierdakil** [comment]
I forgot to mention, that you may also want to look over [CONTRIBUTING.md](https://github.com/jgm/pandoc/blob/master/CONTRIBUTING.md), which has some general guidelines for contributions.

**Comment by jgm** [comment]
@fredefox are you working on this?
If not, I can do it, but I'd like to get this done before the 1.14 release.

**Comment by fredefox** [comment]
It's definitely something that I would like to do. But honestly it's very
much of a learning process for me.
I've never used sandboxes before and I've been receiving errors when trying
to build the project.
Which I thought was due to using an old version of GHC so I updated it. I
think that's gone now.

I just need to wrap my head around this. I haven't started the actually
programming so I won't blame
you if you feel the need to take over. When are you planning to release
1.14?

On Mon, May 11, 2015 at 7:07 AM, John MacFarlane <notifications@github.com>
wrote:

> @fredefox <https://github.com/fredefox> are you working on this?
> If not, I can do it, but I'd like to get this done before the 1.14 release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgm/pandoc/issues/1751#issuecomment-100766881>.
>



-- 
Regards
*Frederik Hanghøj Iversen*

**Comment by jgm** [comment]
+++ Frederik Hanghøj Iversen [May 11 15 00:03 ]:
>I just need to wrap my head around this. I haven't started the actually
>programming so I won't blame
>you if you feel the need to take over. When are you planning to release
>1.14?

Ideally by the end of May.

**Comment by bpj** [comment]
@jgm couldn't this be done just with a template variable?  I have done that for a long time.

**Comment by jgm** [comment]
This is about input not output.
