### ISSUE TITLE
GPL licensing prevents BSD applications from using Pandoc

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#180]
<pre>
The BSD license is probably the most popular license for Haskell
applications and libraries.  A primary reason for this is that GHC has not
historically supported dynamic linking, and the legality of static linking
is a bit murky in the GPL and LGPL.

In xmonad, we recently decided to generate our manpage using the pandoc
library rather than the assortment of regular expressions that we currently
use.  However, xmonad is licensed under BSD meaning we'd have to relicense
our manpage script to GPL.  We would also need to be very careful about how
we use the code in xmonad, as it is not possible to relicense all of xmonad.

Has a linking exception ever been considered for Pandoc [1]?  This would
allow BSD Haskell applications and libraries to use Pandoc without fear.

[1] http://en.wikipedia.org/wiki/GPL_linking_exception

Google Code Info:
Issue #: 175
Author: SpencerJ...@gmail.com
Created On: 2009-10-29T23:41:03.000Z
Closed On: 
</pre>

**Comment by jsl** [comment]
Thanks for creating such a useful library! I'm sorry to revive such an old issue, but I wanted to mention that we unfortunately have to avoid the use of Pandoc in two proprietary projects due to the use of GPL in this codebase. There will likely be more projects where we will have to avoid Pandoc in the future unless the license changes.

While I'd love to use this library, and have our team make contributions upstream as we find places to improve it, we are choosing other dependencies at this point based on the use of GPL in Pandoc.

FWIW, if the Pandoc license were LGPL instead of GPL, I think we wouldn't have to actively avoid using it in very many projects.

Anyway - thanks again for creating this project. I will use it when embedding it inside of other projects is possible based on their license type.

**Comment by jgm** [comment]
This is a dead issue.  Even if I wanted to change the
license, I'd have to get approval from over a hundred
contributors.  And then, there are downstream libraries that
are GPL.  E.g., highlighting-kate has to be GPL because some
of the kate syntax definitions are GPL.
