### ISSUE TITLE
Org reader handles links poorly

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#1812]
The org format allows for many different types of [external link types](http://orgmode.org/manual/External-links.html). Many of these are not supported by the org reader.

See also #756.

**Comment by tarleb** [comment]
The current link parsing code is a rather ugly piece of code. I'm rewriting it completely.  Progress is slow as free time is a bit scarce right now.

**Comment by marcbowes** [comment]
In HTML, `/` means "relative from the server root". In mediawiki, `/` means "a subpage of the current path". What are you plans to handle this sort of conflict?

If you're only exporting for a single target (e.g. org to mediawiki) then it doesn't really matter because you can just author the source in a way that works in the target. But if you're exporting to both mediawiki and HTML then one of them is going to be broken.

Personally, I would prefer that the semantics of the source form were preserved. That is, the syntax for all of the relative links that org supports should be translated to the targets' syntax:

* subpage of the current path, e.g. if you are at `/foo` (HTML) then you need to be able to link to `/foo/bar`
* sibling of the current path, e.g. `/foo` -> `/bar`
* ancestor of the current path, e.g. `/foo/bar` -> `/foo` or `/baz`
* relative from the root, e.g. `/foo/bar/baz` -> `/peanuts/and/bananas`

I'm not exactly sure how you're meant to understand "root" in pandoc sites, so I'm happy to work around that with postprocessors if it's difficult..

**Comment by jgm** [comment]
@tarleb is this still an issue?

**Comment by tarleb** [comment]
It's not optimal yet, but link handling has improved considerably since my last comment.  I believe the remaining issues mentioned above are solvable via pandoc filters and not a reader problem, so this can be closed.
