### ISSUE TITLE
Malformed div tag causes content to vanish until next div tag

### ISSUE THREAD

**Issue by elliottslaughter** [jgm/pandoc#1820]
I recently observed that malformed div tags could cause entire regions of content to vanish. Note the space between "</" and "div>" after paragraph 2.

    $ cat test.md
    This is paragraph 1.
    
    <div>
    
    This is paragraph 2.
    
    </ div>
    
    This is paragraph 3.
    
    <div>
    
    This is paragraph 4.
    
    </div>
    
    This is paragraph 5.
    $ pandoc test.md -t html # output from current pandoc version
    <p>This is paragraph 1.</p>
    <div>
    <p>This is paragraph 2.</p>
    
    <p>This is paragraph 4.</p>
    </div>
    <p>This is paragraph 5.</p>

Given that the div tag is malformed, I think Pandoc's behavior with respect to where to draw the div tags is reasonable, but blowing away the paragraphs in between is not desirable behavior! Ideally I'd like the output to look something like:

    $ pandoc test.md -t html # output from hypothetical pandoc version
    <p>This is paragraph 1.</p>
    <div>
    <p>This is paragraph 2.</p>
    <p>&gt;/ div&lt;</p>
    <p>This is paragraph 3.</p>
    
    <p>This is paragraph 4.</p>
    </div>
    <p>This is paragraph 5.</p>

That way, the garbage in the output tells me I've done something wrong.

    $ pandoc --version
    pandoc 1.13.1

**Comment by lierdakil** [comment]
Would parse fail be agreeable strategy for this, or should we ignore innermost/outermost (not sure which would be easier) unclosed div tag?

**Comment by jgm** [comment]
First I'd like to understand why we get this behavior.
I did a bit of investigating, and now I think I do understand.

One thing that surprised me is that `< /div>` is treated as
a comment by the HTML5 parser!  I don't know why. Is this
a bug in tagsoup our just a dark corner of the HTML5 spec?
(I think probably the latter.  It looks as if HTML5 switches
to "the bogus comment state" on a parse error.
http://www.w3.org/TR/html5/syntax.html#bogus-comment-state

```
Prelude Text.HTML.TagSoup> x <- readFile "test.md"
Prelude Text.HTML.TagSoup> parseTags x
[TagText "This is paragraph 1.\n\n",TagOpen "div" [],TagText "\n\nThis
is paragraph 2.\n\n",TagComment " div",TagText "\n\nThis is paragraph
3.\n\n",TagOpen "div" [],TagText "\n\nThis is paragraph 4.\n\n",TagClose
"div",TagText "\n\n"]
```

Anyway, the `htmlTag` parser in `Text.Pandoc.Readers.HTML`, which
we use in the Markdown reader to parse raw HTML, operates
under the assumption that an HTML comment will end with the
next `>` following the opening `<!--`.  That is a bad assumption,
and it explains why everything up to the next `<div>` tag is
swallowed up.

A safer assumption would be to parse until we hit `-->` (although
even then there are probably some exceptions, since the HTML
comment rules are a bit strange).  But that won't help in this
case, where `< /div` begins the comment!

**Comment by jgm** [comment]
First I'd like to understand why we get this behavior.
I did a bit of investigating, and now I think I do understand.

One thing that surprised me is that `< /div>` is treated as
a comment by the HTML5 parser!  It looks as if HTML5 switches
to ["the bogus comment state"](http://www.w3.org/TR/html5/syntax.html#bogus-comment-state)
on a parse error.

```
Prelude Text.HTML.TagSoup> x <- readFile "test.md"
Prelude Text.HTML.TagSoup> parseTags x
[TagText "This is paragraph 1.\n\n",TagOpen "div" [],TagText "\n\nThis
is paragraph 2.\n\n",TagComment " div",TagText "\n\nThis is paragraph
3.\n\n",TagOpen "div" [],TagText "\n\nThis is paragraph 4.\n\n",TagClose
"div",TagText "\n\n"]
```

Anyway, the `htmlTag` parser in `Text.Pandoc.Readers.HTML`, which
we use in the Markdown reader to parse raw HTML, operates
under the assumption that an HTML comment starts with
`<!--` and ends with the next `>` following the opening `<!--`.
That assumption breaks in this case, since the comment
starts with `<\`. And it explains why everything up to the next `<div>` tag is
swallowed up.

**Comment by jgm** [comment]
I think I have a really simple fix.

**Comment by lierdakil** [comment]
@jgm Wait a second. 13b230a works for spaces, but there are other possible typos which will result in "bogus comment mode". A couple probable examples:
```html
</.div>
</'div>
```
Also numbers (e.g. `</1div>`) -- although that's less probable. Shouldn't it be more like `letter` instead of `nonspaceChar`?

**Comment by jgm** [comment]
Yeah.  Well, letter is too restrictive, because after all we want to
allow `<!--`.  But you're right that this doesn't get everything.
Further PR welcome!

**Comment by lierdakil** [comment]
Oh wow. `</-` will also trigger described behavior. `<!.` as well. Okay. Probably need something more sophisticated to solve this for good. Care to reopen as a reminder?

**Comment by jgm** [comment]
A simple thing to do would be to check for:

letter or `!--` or `!` + letter or `?` + letter or `/` + letter

**Comment by lierdakil** [comment]
Honestly, I'd prefer to find a less tacked-on solution. HTML reader doesn't
choke on this input after all (silently ignoring malformed tag), so it
should be possible, I think.

2015-04-18 5:25 GMT+03:00 John MacFarlane <notifications@github.com>:

**Comment by jgm** [comment]
More principled:  if the tag parses as a Comment but the input doesn't start with `<!--`, then we fail in `htmlTag`.
