### ISSUE TITLE
URLs cut at double-dash (treated as em-dash?)

### ISSUE THREAD

**Issue by jonassmedegaard** [jgm/pandoc#1838]
Pandoc 1.12.4.2 seems to cut URLs a double-dash - specifically this one: http://en.euwiki.org/w/index.php?title=Ensuring_utmost_transparency_--_Free_Software_and_Open_Standards_under_the_Rules_of_Procedure_of_the_European_Parliament

**Comment by jgm** [comment]
This particular example seems to be fixed now.
```
% pandoc -f mediawiki
http://en.euwiki.org/w/index.php?title=Ensuring_utmost_transparency_--_Free_Software_and_Open_Standards_under_the_Rules_of_Procedure_of_the_European_Parliament
^D
<p><a href="http://en.euwiki.org/w/index.php?title=Ensuring_utmost_transparency_--_Free_Software_and_Open_Standards_under_the_Rules_of_Procedure_of_the_European_Parliament" class="uri">http://en.euwiki.org/w/index.php?title=Ensuring_utmost_transparency_--_Free_Software_and_Open_Standards_under_the_Rules_of_Procedure_of_the_European_Parliament</a></p>
```

**Comment by dark-panda** [comment]
Sorry to resurrect this issue, but there's an interesting discrepancy as to how Pandoc is handling the double dashes in this situation.

```html
<a href="https://example.com/foo-bar">https://example.com/foo-bar</a>
<a href="https://example.com/foo--bar">https://example.com/foo--bar</a>
<a href="https://example.com/foo%2Dbar">https://example.com/foo-bar</a>
<a href="https://example.com/foo%2D%2Dbar">https://example.com/foo--bar</a>
<a href="https://example.com/foo%2D%2Dbar">https://example.com/foo%2D%2Dbar</a>
```

Produces:

```latex
\url{https://example.com/foo-bar}
\href{https://example.com/foo--bar}{https://example.com/foo--bar}
\href{https://example.com/foo\%2Dbar}{https://example.com/foo-bar}
\href{https://example.com/foo\%2D\%2Dbar}{https://example.com/foo--bar}
\url{https://example.com/foo\%2D\%2Dbar}
```

Basically, the double dashes produces a `\href` but without the double dashes produces a `\url` when the link text is the same as the `href`. If you URL-escape the the dashes, a `\url` is again used. I noticed this because some of the links in my document were being generated with `\href` and weren't being given monospaced font and weren't line breaking correctly as my `\url`s were. I've started URL-encoding dashes in my links as a result and it works fine and consistently using `\url`, which is what I want.

**Comment by jgm** [comment]
Why don't you open a new issue for this?

**Comment by dark-panda** [comment]
Cool, opened in #5340.
