### ISSUE TITLE
Groff ms writer

### ISSUE THREAD

**Issue by mardukbp** [jgm/pandoc#1839]
Suppose I want to write a simple document in Markdown, that I want to convert to PDF. However, Pandoc requires LaTeX in order to generate the PDF, whereas groff is bundled with every Linux distro and OS X. I realize that pandoc converts markdown to man page, but groff is capable of much more. It just has an ugly, archaic syntax.

**Comment by Hasimir** [comment]
There is another path to PDF (and a few other things) that hasn't been mentioned here, though it might be a bit too much for a "quick alternative" and that's [DITA](http://docs.oasis-open.org/dita/v1.2/spec/DITA1.2-spec.html) with additional bits via [D4P](http://dita4publishers.sourceforge.net/).  I doubt it will be a quick implementation, though (depedning on how much from XHTML can be adapted.  OTOH it would make pandoc pretty much the only dead simple migration path to it and whoever manages it might get nominated for godhood at some point.  It does, however, already have OS platform independence and full UTF-8 support.

**Comment by jgm** [comment]
I should mention that I've recently played around with a
direct PDF renderer for CommonMark that doesn't use LaTeX
at all -- it uses the libharu C library.

See the jgm/cmarkpdf repository.

Something similar could in principle be done for pandoc
using the HPDF library.  Some problems, though:  HPDF
doesn't seem to be actively maintained, and it doesn't seem
to support loading of fonts other than the standard PDF
ones.  Also, supporting everything pandoc supports
(including tables and math) with direct PDF rendering
would be very difficult.

**Comment by Hasimir** [comment]
I'm currently looking into using pandoc with LibreOffice as a means of getting to print/PDF by way of ODT (because pandoc can apply ODT/OTT styles on the command line and LibreOffice headless can't, go figure) as an alternative to all the ever so precious and delicate FOP based "solutions" in DITA and DocBook land.  The only ones to work consistently literally cost thousands of dollars ... for PDF?!  Ridiculous.  So the aim is to convert DITA to ePub 2 (easy, also avoids javascript), then use that as input via pandoc and pick a file for a stylesheet (I test with the über-ridiculous LibreOffice Writer Guide from version 4.0 and once it's an ODT it can either go to PDF, straight to print, stay as it is or head towards DOCX land (obviously the same thing would woth with DOCX files, though I doubt Microsoft provide the equivalent of "/path/to/soffice.bin --headless --convert-to pdf foo.odt"

Another one that might be worth a look, though, is [wkhtmltopdf](http://wkhtmltopdf.org/), which uses Qt4.8 and webkit (it's from Google, of course; it takes [X]HTML (including 5) input,applies CSS and generates PDF out.  It also includes a wkhtmltoimage which does the same thing to GIF, JPG, PNG and something else I forget which (I use PNG).  The image bits are great for side-stepping [Twitter character limits](https://www.adversary.org/wp/2015/10/03/so-you-want-to-tweet-longer/).

**Comment by jgm** [comment]
+++ Ben McGinnes [Dec 20 15 10:29 ]:
>   Another one that might be worth a look, though, is [1]wkhtmltopdf,
>   which uses Qt4.8 and webkit (it's from Google, of course; it takes
>   [X]HTML (including 5) input,applies CSS and generates PDF out. It also
>   includes a wkhtmltoimage which does the same thing to GIF, JPG, PNG and
>   something else I forget which (I use PNG). The image bits are great for
>   side-stepping [2]Twitter character limits.

Yes, maybe we could make `pandoc -t html5 -o doc.pdf`
produce a pdf using wkhtmltopdf.  That might be a nice
alternative for some people, even though the result doesn't
match latex.

**Comment by jgm** [comment]
I've added some preliminary wkhtmltopdf support.
Seems to work okay, but I want to set some wkhtmltopdf
options based on metadata fields (paper size for example).

+++ Ben McGinnes [Dec 20 15 10:29 ]:

**Comment by alerque** [comment]
Just to throw this out there, another route to typeset PDFs is using the [SILE Typesetter](http://www.sile-typesetter.org/). It's still young but already a good deal more flexible than LaTeX and a world lighter.

I've working on a SILE writer for Pandoc (and indeed have it functioning enough to generate press-ready books PDFs from Markdown sources) but the code is pretty rough and only has the markup I've used so far not all the markup others are likely to need. I'll be contributing it at some point—in the mean time anyone interested can contact me.

**Comment by jgm** [comment]
I have a prototype groff ms writer in a branch.
The PDF output is not very good, though, compared to LaTeX.
And to support math, we'd need to implement an eqn converter in texmath.

**Comment by ickc** [comment]
@alerque, any update on your SILE experiment?

**Comment by alerque** [comment]
@ickc Yes actually I've made progress on it, but it still suffers from the problem that I'm using it for my own projects and it's hard to finish up to the point of being ready to contribute upstream when it meets my needs already. See also [this discussion](https://github.com/simoncozens/sile/issues/413) for some more status notes and an example. If you have a use case for it hit me up and lets talk about what it would take to make it work for you. Since we're wandering off topic for this issue maybe opening a dedicated issue for this would work catch me in [SILE's gitter room](https://gitter.im/simoncozens/sile).

**Comment by ickc** [comment]
In pandoc-discuss, there's a post mentioning a tool slightly related to this: [\[OT\] rinohtype 0.3.0 - an alternative to LaTeX - Google Groups](https://groups.google.com/d/msg/pandoc-discuss/pDcTVOMjuNQ/m-9Tg1ksCQAJ). If you don't mind using pandoc to output to rst first and pipe it through this extra dependency, you can get a PDF. It is a very early alpha(?) though.

**Comment by pepa65** [comment]
The Laplace example worked here with `groff -mom -e -k math.mom | ps2pdf - doc.pdf` but not with `pdfmom -e -k math.mom > math.pdf`
But when I fed it some Thai, it gave warnings like `t.groff:21: warning: can't find special character `u0E27'` and it didn't work.

**Comment by jgm** [comment]
We might consider merging the `groff_ms` branch's groff_ms writer even without math support.

Adding eqn support to texmath would be a fun project for someone!

**Comment by jgm** [comment]
eqn branch in jgm/texmath is almost finished.

**Comment by jgm** [comment]
Is it worth using the texmath eqn writer for math in man pages as well?

**Comment by jgm** [comment]
I have added a groff `ms` writer to the master branch.
Not perfect yet, but coming along.  It translates math into eqn format, tables into tbl format.

**Comment by jgm** [comment]
You can now go straight to pdf via ms:

    pandoc input.txt -t ms -o output.pdf

This uses pdfroff, which is packaged with recent versions of groff (but not the default groff on macos, which is old).

**Comment by mardukbp** [comment]
Thank you very much John! I just tried it and tex_math_dollars works, but tables do not work. I tried simple_tables and pipe_tables and I got the TBL code rendered in the PDF instead of a table.

**Comment by jgm** [comment]
I forgot to add the -t parameter when calling pdfroff.
I'll add that now.

+++ Marduk Bolaños [Mar 23 17 14:57 ]:

**Comment by mardukbp** [comment]
I just did a `git pull`and ran `stack install --test`. The following test failed:

```
 ms
      writer
        basic:                                                     FAIL (0.09s)
          
          ------------------------------------------------------------------------
          --- writer.ms
          +++ /home/marduk/pandoc-git/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/pandoc/pandoc --quiet --data-dir ../data testsuite.native -r native -w ms --columns=78 --variable pandoc-version= -s
          +  33 .nr PI 2m
          -  33 .nr PI 0
          ------------------------------------------------------------------------
```

**Comment by jgm** [comment]
+++ Marduk Bolaños [Mar 25 17 00:25 ]:
>   I just did a git pulland ran stack install --test. The following test
>   failed:

Try again now (pull again).  It should work.

**Comment by mardukbp** [comment]
Now stack finishes, but tables still do not work. Using the examples for `simple_tables` or `pipe_tables` I get the following:

```
eqn:<standard input>:157: unquoted escape
eqn:<standard input>:157: unquoted escape
<standard input>:137: warning: numeric expression expected (got `\&')
<standard input>:149: warning: numeric expression expected (got `\&')
<standard input>:166: warning: numeric expression expected (got a special character)
<standard input>:182: warning: numeric expression expected (got `\&')
<standard input>:182: warning: numeric expression expected (got `\&')
<standard input>:194: warning: numeric expression expected (got `\&')
<standard input>:203: warning: numeric expression expected (got `\&')
```

In the PDF I get less columns than there are in the .md file.

**Comment by jgm** [comment]
@mardukbp are you running groff manually on the ms produced by pandoc?
If so, you need to add `-t` to process the tables and `-e` if you have any math.
Or you can use pandoc to go straight to PDF via ms:

    pandoc -t ms input.md -o output.pdf

This should automatically use the right flags to handle your tables and equations.

If you're already using `-t`, can you give the specific examples you're referring to?

**Comment by mardukbp** [comment]
This is what I am doing:

`pandoc test.md -f markdown+tex_math_dollars+pipe_tables -t ms -o out.pdf`

test.md

```
# Groff test

$a^2+b^2=c^2$


| Column A | Column B |
|----------|----------|
|   12     |    22    |
```

And here is the output

![pandoc groff](https://cloud.githubusercontent.com/assets/1140106/24330829/64e70532-1227-11e7-9017-5e3c12a7b58d.png)

**Comment by jgm** [comment]
Great, can you start a new issue for this?
We're likely to lose track if it's a comment on a closed
issue.

**Comment by jgm** [comment]
Seems to be a strange interaction between eqn and tbl.
Either `-t` or `-e` works fine by itself, but when you
use both it doesn't work.

**Comment by jgm** [comment]
I think I've isolated the problem.

Consider this groff file:

```
.EQ
delim ||
.EN
.LP
.EQ
x
.EN
.PP
.TS
tab(@);
l.
T{
A
T}
_
T{
1
T}
.TE
```

Process this with `pdfroff -t -e` and you'll get the errors.
No remove the first three lines; the errors go away.

Pandoc includes those first three lines in any document with
math (since we use | delimiters for inline math).  Perhaps
the | character has a special meaning for tbl?

**Comment by jgm** [comment]
Indeed:

from man tbl:

       |      The corresponding column becomes a  vertical  rule  (if  two  of
              these are adjacent, a double vertical rule).

So we need to choose a different character to use for inline
math delimiter.

**Comment by jgm** [comment]
OK, never mind the issue, this is fixed!

**Comment by mardukbp** [comment]
Thanks a lot John! I did some tests. Column alignment works, as well as horizontal rules, bold and italics.
