### ISSUE TITLE
Trying to convert a Github Wiki to an .epub ebook

### ISSUE THREAD

**Issue by preslavrachev** [jgm/pandoc#1857]
I wanted to make an .epub ebook out of the following Github wiki: https://github.com/codepath/android_guides/wiki 

I cloned it locally, and spotted that the wiki has its TOC structure laid out like this: 

```markdown
* [[Constructing View Layouts]] (How to layout views)
* [[Defining Views and their Attributes]] (Gravity, Margin, Padding, etc)
* [[Working with the TextView]] (Properties, Drawables, Custom Fonts)
* [[Working with the EditText]] (Properties)
* [[Working with the ImageView]] (Size, Scale, Density, Raw Bitmaps)
* [[Working with Input Views]] (Spinner, RatingBar, etc)
* [[Working with the Soft Keyboard]]
* [[Working with the WebView]]
* [[Working with the ScrollView]]
```
which correspond to actual .md files in the same directory (e.g. 'Constructing-View-Layouts.md')

Yet, when I convert the Home.md to an .epub ebook, it is the only one that actually gets converted, and all of the internal link notations remain as displayed. I assume that I would need to write a parser script that concatenates all the separate files in order, and rewrites those as chapter anchors. Is this correct? Do you have any solution in mind?

**Comment by bpj** [comment]
Pandoc doesn't follow links. You have to list all the files on the command line and they will be concatenated into a single file in the order you list them. To make it easier you can either write a wrapper script where you put all the files in the right sequence into an array or process them individually. Another way to get the files concatenated in the right sequence is to create a branch where you give the filenames a zero-padded leading number

```
00-Index.md
01-Some-file.md
02-Another-file.md
...
10-The-tenth-file.md
...
```

then you can just use a wildcard and you will get them in the right order:

```
pandoc -o book.html *.md
```

Note the zero padding which is necessary because the shell globs the files in ASCII order and not numerical order. 

With chapters in a book I number e.g. chapter 1-8 as `1000-chapter1.md` to `8000-chapter8.md`, then I can number sections in separate files in the tens `2010` and so on and if I need to rearrange or insert a chapter I give that chapter a number in the hundreds  like `2500` rather than having to renumber all the files.

**Comment by bpj** [comment]
BTW since renamed files are dissociated from their counterparts in the main branch you might want to give every file a number starting with zero, because when you later pull and merge from the main branch you will have unnumbered files lying around. You can then delete the old files for those files which were changed and then number changed/added files appropriately and glob `0*.md` bypassing unnumbered copies of unchanged files. However if you get a lot of that you may want to keep and edit an ordered list of files in a script instead.

**Comment by bpj** [comment]
Den 2015-01-06 10:22, Preslav Rachev skrev:
> I wanted to make an .epub ebook out of the following Github wiki: https://github.com/codepath/android_guides/wiki
>
> I cloned it locally, and spotted that the wiki has its TOC structure laid out like this:
>
> ```markdown
> * [[Constructing View Layouts]] (How to layout views)

Sorry for the noise!

Now I see what you mean: those wiki links don't become links!

Something like this should do the trick:

(Not tested as I'm in a hurry!)

``` perl
#!/usr/bin/env perl

# wikilink2link.pl - Convert GitHub wikilinks to Pandoc links.

# USAGE:
#
# Remember to always work in a new branch even if you make backups!
#
#   git checkout -b wikilink2link
#   perl wikilink2link.pl *.md && pandoc [OPTIONS] *.md

use strict;
use warnings;

use open :utf8; # decode/encode input/output
use open :std;  # decode/encode STDIN/STDOUT/STDERR

use File::Copy;

sub wikilink2link {
     my($link_text) = @_;
     my $file_name = $link_text;
     # Convert spaces to hyphens.
     # Should possibly be $file_name =~ s/\s+/-/g; instead!
     $file_name =~ s/\s/-/g;
     $file_name .= '.md';    # Add file ending
     # Assuming all files are in the same directory!
     return "[$link_text]($file_name)";
}

mkdir('bak');
-d 'bak' or die "Couldn't create 'bak' or not a directory!\n";

my @files = glob('*.md');

FILE:
for my $file ( @files ) {
     copy( $file, 'bak' )
         and -f "bak/$file"
         or die "Couldn't copy '$file' to 'bak'\n";

     open my $in_fh, '<', "bak/$file"
         or die "Couldn't open 'bak/$file' for reading: $!\n";
     open my $out_fh, '>', $file
         or die "Couldn't open '$file' for writing: $!\n";

     LINE:
     while (<$in_fh>) {    # read input line by line
         # Replace wiki links with real links
         $_ =~ s{\[\[(.*?)\]\]}{ wikilink2link( $1 ) }eg;
         print {$out_fh} $_;
     } # end LINE
     close $in_fh or die "Couldn't close 'bak/$file': $!\n";
     close $out_fh or die "Couldn't close '$file': $!\n";
} # end FILE
```

**Comment by jgm** [comment]
I don't see a bug in pandoc here, so I'm closing this.  Wikilinks aren't yet implemented in `markdown_github`. I hope your question about the multiple input files has been answered.  In general, the best place to ask questions is not here but on the pandoc-discuss list, where many people can help answer them, and many can benefit from the answers.
