### ISSUE TITLE
Add syntax highlighting to ICML

### ISSUE THREAD

**Issue by omerida** [jgm/pandoc#1873]
AFAIK, this is an enhancement request. If you use `--highlight-style` to generate ICML files for indesigne, the Code Block do not have any styles for syntax highlighting associated with them

Take a simple block like (ignore the backslashes, but adding them makes github render the rest correctly):

``````
\~~~{.php}
foreach ($lines as $line) {
    echo trim($line);
}
\~~~
``````

For HTML, pandoc generates the following:

~~~~
<pre class="sourceCode php"><code class="sourceCode php"><span class="kw">foreach</span> <span class="ot">(</span><span class="kw">$lines</span> <span class="kw">as</span> <span class="kw">$line</span><span class="ot">)</span> {
    <span class="fu">echo</span> <span class="fu">trim</span><span class="ot">(</span><span class="kw">$line</span><span class="ot">);</span>
}</code></pre>
~~~~

But for ICML, there's no information to style keywords, variables, functions, etc...

~~~~
<ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/CodeBlock">
  <CharacterStyleRange AppliedCharacterStyle="$ID/NormalCharacterStyle">
    <Content>foreach ($lines as $line) {
    echo trim($line);
}</Content>
  </CharacterStyleRange><Br />
</ParagraphStyleRange>

~~~~

**Comment by mb21** [comment]
As far as I know, Pandoc uses [highlighting-kate](https://github.com/jgm/highlighting-kate) which currently only supports HTML and LaTeX output.

I guess if you really need this, you could write a filter that again uses Pandoc to generate small PDFs of the code snippets with LaTeX and then embeds them in the document's AST as images/figures, replacing the original codeblocks.

**Comment by jgm** [comment]
+++ mb21 [Jan 17 15 04:11 ]:
>As far as I know, Pandoc uses [highlighting-kate](https://github.com/jgm/highlighting-kate) which currently only supports HTML and LaTeX output.

Pandoc also supports docx highlighting, though we do that with some
extra code in the docx writer rather than in the highlighting-kate
library itself.

highlighting-kate works much like pandoc:  it creates a structured
object representing the tokens in the parsed source code, and provides
renderers for this structured object to different formats.

So, you could write an ICML renderer similar to
Text/Highlighting/Kate/Format/HTML.hs, and use that in your filter.

**Comment by omerida** [comment]
Sadly, writing a filter is a bit outside my skill set.
