### ISSUE TITLE
Problem converted header containing span with ID into LaTeX

### ISSUE THREAD

**Issue by mpickering** [jgm/pandoc#1886]
Trying to convert: https://www.haskell.org/haskellwiki/Applications_and_libraries/Generic_programming/Strafunski

LaTeX output: https://gist.github.com/mpickering/6f7caf78ef73631e1289

LaTeX error: 

```
Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\@ifnextchar' on input line 180.

! Argument of \@sect has an extra }.
<inserted text> 
                \par 
l.180 Strafunski }}
```

Can anyone see what's going on?

**Comment by jgm** [comment]
Odd.  Compare

% pandoc -t latex --toc
# Hi {#foo}
^D

See [blah](#foo)
\hyperdef{}{foo}{\section{Hi}\label{foo}}

See \hyperref[foo]{blah}

---

Here the hyperdef is outside the section command; in your example it's inside.
Changing that in the tex source fixes things.

Question is, why did pandoc do it the other way here?

Probable answer:  because here the id is on a span inside the h2,
rather than on the h2 itself:

<h2> <span class="mw-headline" id="Approach:_Strafunski">1 Approach: Strafunski\
 </span></h2>



+++ Matthew Pickering [Jan 18 15 04:22 ]:

**Comment by jgm** [comment]
Note:  The problematic text in the page being converted is
```
<h2> <span class="mw-headline" id="Expressibility">3  Expressibility </span></h2>
```
It's the span with id inside the header that causes the problem.

This could be fixed by (a) removing id's on spans in headers, and putting the ids on the headers themselves (if one is not already present), or (b) having the writer refrain from inserting a hyperdef if we're inside a header.

**Comment by jgm** [comment]
This seems to be fixed now.
