### ISSUE TITLE
No javascript link to mathjax using --from markdown_github --mathjax 

### ISSUE THREAD

**Issue by pedrofurla** [jgm/pandoc#1892]
The error is very easily reproducible, so I am only a sequence of bash commands below:

````bash
echo 'equation: $f(x)=\sum_{n=0}^\infty\frac{f^{(n)}(a)}{n!}(x-a)^n$' > equation.md
pandoc -s --from markdown_github --mathjax equation.md -o bad.html
pandoc -s --from markdown --mathjax equation.md -o good.html
````

Comparing the `good` and `bad` html files, it is immediately noticeable the `bad` html misses the link to the MathJax CDN. Btw, notice one is from `markdown_github` and the other `markdown`.

As side note: trying to test the browser rendering from the files locally (file:///) doesn't work. The link produced omits the protocol, I guess to force the browser reuse the host page's protocol (http vs https).

**Comment by jgm** [comment]
I don't think this is an error.  `markdown_github` supports the `\(...\)` and `\[...\]` style of TeX math, but not the `$...$` style.  (At least, this was true when I added the extension.)  So in `bad`, pandoc doesn't generate a math element.  It doesn't include the link because it sees that there's no math element on the page.  Try using `\(...\)`.

On the protocol issue:  yes, with the `//` format is that the protocol is inherited from the parent page.  That's not what you want when you're looking at a page locally but want MathJax to come remotely.  You can always use a custom template where you sub `http://` for `//` in the mathjax link.

**Comment by pedrofurla** [comment]
Cool thanks! Indeed using the other math delimiters worked just fine. Sorry for my ignorance.

As for the protocols, would make command line like `--mathjax="http:..."` (or https, or file, or whatever), than replace `...` with the existing url be sensible?

**Comment by jgm** [comment]
Oh, you can just do `--mathjax=FULLURL` and that should work too.  I
think it's getting too fancy to do replacement on `...`.

+++ Pedro Furlanetto [Jan 20 15 22:00 ]:

**Comment by pedrofurla** [comment]
Yeah, yeah, thats what I am doing. Closing the issue.
