### ISSUE TITLE
Markdown "text <email> text" is incorrectly converted to DocBook

### ISSUE THREAD

**Issue by pospispa** [jgm/pandoc#1895]
IMHO, the below Markdown text is incorrectly converted to DocBook:
Markdown:
Some text <email> text continues
Resulting DocBook:
<para>
  Some text <email> text continues
</para>
Online pandoc:
http://johnmacfarlane.net/pandoc/try/?text=Some+text+%3Cemail%3E+text+continues&from=markdown&to=docbook

IMHO, the resulting DocBook should be:
<para>
  Some text &lt;email&gt; text continues
</para>

**Comment by pospispa** [comment]
I'm sorry, that the Markdown and DocBook source code is incorrectly displayed. I should have used Markdown.
So once again:
Markdown:
```
Some text <email> text continues
```
Resulting DocBook:
```
<para>
  Some text <email> text continues
</para>
```

IMHO, the resulting DocBook should be:
```
<para>
  Some text &lt;email&gt; text continues
</para>
```

**Comment by jgm** [comment]
Markdown allows inline HTML, and because it's handy to have inline
tags in non-HTML formats too, we just pass through anything that
looks like a tag.  Although this can lead to odd results in cases
like yours, it also gives you lots of power to insert raw DocBook
tags when you need to.

Your solution is to backslash-escape the `<`:  `\<email>`.

+++ pospispa [Jan 22 15 03:14 ]:

**Comment by pospispa** [comment]
Thank you very much for the explanation.
