### ISSUE TITLE
LaTeX reader - pandoc ignores \part

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#1905]
Converting the following LaTeX code:

```
\part{Part}

\chapter{Chapter}

\section{Section}
```

[in markdown format](http://pandoc.org/try/?text=part{Part}%0A%0Achapter{Chapter}%0A%0Asection{Section}&from=latex&to=markdown) gives the following code:

```
\part{Part}

Chapter
=======

Section
-------
```

`\part` is ignored.

I wonder whether it would make sense to convert it to `# Part {.part}` or to enable a `--part` option in pandoc.

**Comment by juh2** [comment]
I would vote for a `--part` option in pandoc as `\part` is a LaTeX only feature. But +1 for this enhancement. It would be great to have this option.

**Comment by ousia** [comment]
I have just realized that a `--parts` option makes sense when writing LaTeX documents, not when reading them.

**Comment by mpickering** [comment]
I'm not sure what the best way to support this is.

**Comment by loindutroupeau** [comment]
'part' also exists in epub (at least in epub3). Indeed, it would be great to have a correspondance with the latex command \part.

**Comment by ousia** [comment]
@mpickering, wouldn’t it be possible to implement `--parts` in a similar way `--chapters` has been implemented?

**Comment by ickc** [comment]
Hi, I stumbled upon the same issue today. As I used to MultiMarkdown's behavior, I thought setting `--base-header-level=0` would solve the problem: that level 1-6 markdown headings becomes level 0-5 LaTeX headings. But there's an error. Searching the pandoc-discuss results in this: [--base-header-level= - Google Groups](https://groups.google.com/forum/#!searchin/pandoc-discuss/base-header-level|sort:relevance/pandoc-discuss/iEI47MAMF0U/ePYDAFdcz3gJ). And then searching in GitHub issue tracker results in this issue.

It seems mapping level 1-6 markdown headings to level 0-5 LaTeX headings is natural. In terms of command line option, from markdown to LaTeX should accept `--base-header-level=0` to trigger this behavior.

Currently, from LaTeX to Markdown seems to map LaTeX 1-5 to Markdown 1-5, when no option or `--base-header-level=1` is used. So following this logic, it seems `--base-header-level=2` should map LaTeX 0-5 to Markdown 1-6. This way, backward compatibility issue is minimize, since if it is left as default, the part, having level 0, would not be mapped to a markdown heading at level 0.

**Comment by jgm** [comment]
We have a `--top-level-division` option now.  I suppose we could set things up so that the LaTeX reader parsed `\part` as a section header if that is set.  Alternatively, we could have it always
parse `\part` as a section header (automatically bumping up chapter to level 2, section to level 3, etc.).

**Comment by rauschma** [comment]
`--top-level-division=part` works well, but there are two problems:

* Numbering doesn’t work. For example, `--number-sections` now numbers chapters in HTML.
    * It’d be great if everything down to and including sections could be numbered in HTML. But that’s relatively complex: continuing chapter numbers across parts, different numbering for chapters in the front matter, etc.

* The TOC isn’t formatted properly. You still get nested ULs.

However, if you can live without numbered chapters, there is much you can do via CSS:

```css
nav#TOC ul {
    list-style: none;
}

nav#TOC > ul > li {
    margin-top: 1em;
}
nav#TOC > ul > li > ul {
    margin-top: 1em;
}
nav#TOC > ul > li > a {
    margin-top: 4em;
    text-transform: uppercase;
}
nav#TOC > ul > li > ul > li {
    margin-top: 0.5em;
}
nav#TOC > ul > li > ul > li > a {
    font-weight: bold;
}
```
