### ISSUE TITLE
bug in YAML title?

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#1908]
@jgm, I have a document with the following metadata:

```
---
title: `pandoc`
subtitle: An Introduction
author: It Was Me
publisher: <http://www.pandoc-is-great.com>
...
```

When compiling it, I get the following error:

```
pandoc: Could not parse YAML header: found character that
cannot start any token "source" (line 3, column 8)
```

Isn’t it a bug in pandoc-1.13.2?

At least the error message is misleading, because it points to the colon after the subtitle field name.

**Comment by jgm** [comment]
Since `` ` `` is a special character in YAML (it doesn't yet have a special
meaning, but it's "reserved for future use"), you need to put the title in quotes.

+++ Pablo Rodríguez [Jan 28 15 10:56 ]:

**Comment by ousia** [comment]
> Since `` ` `` is a special character in YAML (it doesn't yet have a special meaning, but it's "reserved for future use"), you need to put the title in quotes.

@jgm, many thanks for your fast reply.

I thought the character couldn’t be escaped in YAML.

Closing the issue myself.

**Comment by bpj** [comment]
As a rule of thumb for the record: whenever a string in YAML contains any
punctuation it should be put in single quotes to silence potential errors.
To get a single quote inside single quotes it should be doubled -- 'that''s
right' -- all other characters are non-special inside single quotes in
YAML. A few punctuation characters -- notably forward slash and dollar --
are guaranteed to remain non-special but rather than memorizing which
characters aren't special just memorize the two rules that every string
containing punctuation characters should be singlequoted and the way to get
a single quote inside single quotes is to double it. This goes for both
keys and values BTW.
Den 28 jan 2015 23:55 skrev "Pablo Rodríguez" <notifications@github.com>:

**Comment by ousia** [comment]
> As a rule of thumb for the record: whenever a string in YAML contains any punctuation it should be put in single quotes to silence potential errors.

Many thanks for the tip, @bpj.
