### ISSUE TITLE
change --extract-media destination folder

### ISSUE THREAD

**Issue by m-baumgartner** [jgm/pandoc#1986]
The doc says the following : 

```
--extract-media=DIR
Extract images and other media contained in a docx or epub container to the path DIR, creating it if necessary, and adjust the images references in the document so they point to the extracted files. This option only affects the docx and epub readers.
```

This works fine to me but it creates a `/media` folder in the specified `DIR`. How can I make pandoc puts the media file in a folder with a different name? eg. `img`

If this behaviour is not possible yet I think it this issue should be turned into a request.

Thanks

**Comment by jgm** [comment]
+++ m-baumgartner [Mar 03 15 09:06 ]:
>The doc says the following :
>```
>--extract-media=DIR
>Extract images and other media contained in a docx or epub container to the path DIR, creating it if necessary, and adjust the images references in the document so they point to the extracted files. This option only affects the docx and epub readers.
>```
>
>This works fine to me but it creates a `/media` folder in the specified `DIR`.

This is because the files live in a `/media` folder inside the docx container.  The relative path inside the docx container is preserved.  Remember, `--extract-media` also works with epub, so we don't want to make its behavior dependent on details of a particular container.  (Indeed, in an epub there is no particular location for media.)

> How can I make pandoc puts the media file in a folder with a different name? eg. `img`

    pandoc my.docx --extract-media=DIR && mv DIR/media DIR/img

**Comment by m-baumgartner** [comment]
Thanks for your answer. 
This partially work. The images are correctly moved to the defined `DIR/img` folder but the markdown links in the `.md` file still points to `DIR/media` instead of `DIR/img`.

**Comment by mpickering** [comment]
I'm not sure why we retain the `media` folder structure. I seem to remember there was some discussion about this when the feature was first implemented. @jkr do you remember why?

**Comment by jgm** [comment]
+++ Matthew Pickering [Mar 03 15 15:50 ]:
>I'm not sure why we retain the `media` folder structure. I seem to remember there was some discussion about this when the feature was first implemented. @jkr do you remember why?

I thought the reason was the one I gave earlier in this thread.
`--extract-media` works the same for docx and epub.  But in epub, at
least, there's no particular place media has to be.  You could have all
images in `img`, or in the top level, or some in one subdirectory and
some in another.  So the only sane approach is to keep the internal
directory structure intact.

**Comment by nkalvi** [comment]
Also, when you insert an image in current version of Word, it is saved under *media* folder in docx.

**Comment by mpickering** [comment]
Ah right, that makes sense.

**Comment by jgm** [comment]
+++ m-baumgartner [Mar 03 15 11:44 ]:
>   Thanks for your answer.
>   This partially work. The images are correctly moved to the defined
>   DIR/img folder but the markdown links in the .md file still points to
>   DIR/media instead of DIR/img.

Oh, yes.  I'd forgotten about that part of it.  You could use a filter to change the paths on images.

**Comment by Lynntaohan** [comment]
&& mv does not work and get error

**Comment by Lynntaohan** [comment]
these answers partially work, but how to sue a filter to change the paths on images? and how to move the default media sub-folder though?
