### ISSUE TITLE
--include-in-header and similar options don't work for epub

### ISSUE THREAD

**Issue by danmichaelson** [jgm/pandoc#1987]
It appears the default epub template doesn't include header-include, include-before, or include-after.

**Comment by jgm** [comment]
The issue here (as discussed on pandoc-discuss) is that the epub templates are per-chapter.  So if these options were included, they would affect each chapter; "include-before" would come at the beginning of each chapter, rather than just once at the beginning of the document.

Because of this, the feature didn't seem very useful to me, but if you think it would still have a use, we can add these variables.

**Comment by danmichaelson** [comment]
I think it still has a lot of value. If I'm inserting content into the head typically I do want it for all chapters. Same (often) goes for a header or footer. The caveat could just be documented. The behavior is also less surprising this way since if you're affirmatively using these options, your expectation is that they work rather than the inverse.
