### ISSUE TITLE
Parsing MediaWiki nested bullet point lists (unordered)

### ISSUE THREAD

**Issue by peterjc** [jgm/pandoc#1991]
Consider this example,

```
$ cat bullets.mediawiki 
This example nests bullet points:

* Top level
:* Second level line one
:* Second level line two
::* Third level
:* Second level again
* Top level again
:* Second level once more

The end.
```

Here is the (mangled) output from pandoc 1.13.2 as RST,

```
$ pandoc -f mediawiki -t rst bullets.mediawiki 
This example nests bullet points:

-  Top level

:\* Second level line one

:\* Second level line two

::\* Third level

:\* Second level again

-  Top level again

:\* Second level once more

The end.
```

Default markdown,

```
$ pandoc -f mediawiki -t markdown bullets.mediawiki 
This example nests bullet points:

-   Top level

:\* Second level line one

:\* Second level line two

::\* Third level

:\* Second level again

-   Top level again

:\* Second level once more

The end.
```

And my preferred output, GitHub Flavored Markdown,

```
$ pandoc -f mediawiki -t markdown bullets.mediawiki 
This example nests bullet points:

-   Top level

:\* Second level line one

:\* Second level line two

::\* Third level

:\* Second level again

-   Top level again

:\* Second level once more

The end.
```

In this case I am hoped to get something like this,

```
This example nests bullet points:

* Top level
    * Second level line one
    * Second level line two
        * Third level
    * Second level again
* Top level again
    * Second level once more

The end.
```

This markdown is rendered nicely by GitHub:

This example nests bullet points:

* Top level
    * Second level line one
    * Second level line two
        * Third level
    * Second level again
* Top level again
    * Second level once more

The end.

**Comment by jgm** [comment]
+++ Peter Cock [Mar 04 15 14:29 ]:
>   Consider this example,
>$ cat bullets.mediawiki
>This example nests bullet points:
>
>* Top level
>:* Second level line one
>:* Second level line two
>::* Third level
>:* Second level again
>* Top level again
>:* Second level once more
>
>The end.

Can you point to MediaWiki documentation for this?  At http://www.mediawiki.org/wiki/Help:Formatting#Text_formatting_markup I see the following syntax for nested bullet lists, which pandoc handles well:

```
* top level
** second level line one
** second level line two
*** third level
** second level again
* top level again
```

The colon is used for definitions in definition lists, but pandoc assumes you don't have a definition list unless you have an item (the term) with a semicolon.

Oh, I just tried this on MediaWiki sandbox.  What's happening in your example is this:

```
<ul>
<li>Top level</li>
</ul>
<dl>
<dd>
<ul>
<li>Second level line one</li>
</ul>
</dd>
</dl>
etc.
```

That's a mess.  It may look right on the page, but it isn't semantically correct.  It's an unintended consequence of the fact that the MediaWiki parser allows you to have definition list items containing definitions but no terms.

It would be possible to modify pandoc's MediaWiki parser to allow definition list items with no terms, but you're not going to get a Markdown nested list out of your input, because semantically it's not a nested list (it just looks like one).

**Comment by peterjc** [comment]
I was looking at http://www.mediawiki.org/wiki/Markup_spec#Start_of_line_only to explain a pre-existing usage pattern. The intended meaning on combining the unary symbols is a little unclear to me from that text, but you are likely right that this example is semantically incorrect.

It sounds like the simplest option here is to edit our source MediaWiki entry to a more mainstream/semantic mark up of the nested bullets.

**Comment by jgm** [comment]
For compatibility, we should probably change pandoc to allow definition list items with no terms, but as I said this won't help you if you're converting to Markdown.

**Comment by peterjc** [comment]
I'll leave this issue open if you want to tackle definition list items with no terms.

In the meantime, I have edited the wiki page which was triggering this (resulting in a slightly different layout, but acceptable), which should now display consistently once converted into markdown with pandoc. Thanks!
