### ISSUE TITLE
\newcommand* (starred version) unsupported

### ISSUE THREAD

**Issue by daurnimator** [jgm/pandoc#2005]
(still trying to compile https://github.com/wahern/cqueues/blob/master/doc/cqueues.tex)

Pandoc seems to ignore `\newcommand*{\cqueues}[0]{\texttt{cqueues}\xspace}`
Removing the `*` seems to make things work...

**Comment by daurnimator** [comment]
Thanks for fixing this.

btw, when compiled to markdown, macros get a `<span>` around them.
Could this be removed?

**Comment by jgm** [comment]
You can do `pandoc -f latex -t markdown-native_spans-raw_html` and you won't get the span (or any other raw HTML).

Why is the span there?  Because we put the content of the expanded macro in `{...}` (see #1390), and this gets treated as a pandoc Span element in the LaTeX reader.  (We need to treat `{...}` content as a Span in order to properly handle protected capitalization in bibtex entries.)

So the way to get rid of the span tag would be to fix #1390.  Unfortunately that's a hard nut to crack.
