### ISSUE TITLE
Multiple bibliography files

### ISSUE THREAD

**Issue by azrdev** [jgm/pandoc#2041]
I'm writing markdown, converting it to latex, and like to add multiple BibLaTeX bibliography files. Thus I added `--biblatex` to the command line, and removed the `--filter pandoc-citeproc` argument.

* If I use multiple `--bibliography` arguments to pandoc, only the first one is used, i.e. the result is `\bibliography{file1}`.
* If I use a yaml list in the metadata, no `\bibliography{}` statement will be generated thanks to #1661 

```
> pandoc --version
pandoc 1.12.3.3
...
> pandoc-citeproc --version
pandoc-citeproc 0.3.1
```

**Comment by nkalvi** [comment]
Could you please update to current version (1.32.2) and test it? I could test it if you could share some test files.

**Comment by lierdakil** [comment]
First, please update, 1.12.3.3 is more than a yead old. Second, you can use `pandoc ... -V biblio-files=file1,file2` instead of `--bibliography`, which should work nicely in your case.

Please also understand that template variables (set with `-V`) and YAML metadata are two completely separate concepts. `--bibliography` setting both is just a compatibility hack.

**Comment by lierdakil** [comment]
@nkalvi 1.32.2? :laughing: typo, eh?

Latest Pandoc version is 1.13.2

**Comment by nkalvi** [comment]
:blush:  This much Pandoc activity is intoxicating.

**Comment by azrdev** [comment]
@lierdakil thanks! `-V biblio-files` works as expected, i.e. inserts `\bibliography{file1.bib,file2.bib}`.

The distinction you make w.r.t. metadata blocks is new to me, cannot find it in the readme: http://johnmacfarlane.net/pandoc/README.html#extension-yaml_metadata_block only gives an example of setting author, so maybe you should make that more clear.

As for the versions: [1.13 is shipped with current Fedora 21](https://apps.fedoraproject.org/packages/pandoc).

**Comment by lierdakil** [comment]
@azrdev, see http://johnmacfarlane.net/pandoc/README.html#templates . You
may also notice that README does not say anything about using
--bibliography with --biblatex (although it probably should), only with
pandoc-citeproc.

2015-03-29 20:26 GMT+03:00 azrdev <notifications@github.com>:

**Comment by mpickering** [comment]
Can this be closed? Should the documentation be updated? @lierdakil

**Comment by jgm** [comment]
Since `--bibliography` can be used multiple times (producing a list), and since in a recent commit we allowed that `--bibliography` would populate the `biblio-files` variable when `--natbib` or `--biblatex` is used, we should probably fix things so that it can handle a list.

**Comment by lierdakil** [comment]
I think at least "citations" section (http://pandoc.org/README.html#citations) should be updated with information on `--natbib` and `--biblatex`. At the moment it doesn't mention those. And since using `--bibliography` with `--natbib` and `--biblatex` is somewhat supported, "citation rendering" section (http://pandoc.org/README.html#citation-rendering) should probably be updated to reflect that as well.

**Comment by jiucenglou** [comment]
> Since `--bibliography` can be used multiple times (producing a list), and since in a recent commit we allowed that `--bibliography` would populate the `biblio-files` variable when `--natbib` or `--biblatex` is used, we should probably fix things so that it can handle a list.

Could we assign a list of files to `--bibliography` currently ?  :D
