### ISSUE TITLE
Docx/fb2/dokuwiki templates?

### ISSUE THREAD

**Issue by lierdakil** [jgm/pandoc#2044]
Other output formats do have configurable templates, even odt and epub, but not these three. Are these simply not implemented, or is there any other reason for that?

**Comment by jgm** [comment]
There is a dokuwiki template.

For FB2, it's an xml format, and I'm not sure there's any room for customization.  In any case, it has never come up as a need for anyone.  I don't know much about the format; the module was contributed by one of the main FB2 developers.

With docx, one can imagine the use for some kind of template (e.g. company letterhead).  But it makes sense to have something one can edit in Word, without mucking with XML directly. Perhaps the thing to do is to have a reference.dotx rather than reference.docx.  I don't know anything about the dotx format, but this might be worth looking into.

**Comment by lierdakil** [comment]
Somehow I missed dokuwiki template. Awkward.

Don't know much about inner workings of fb2, but I think there is some extended metadata, like number in series and the like, which can be in principle supplemented via template variables, I think? I'll have to research a bit to have a meaningful proposal though.

As for docx, I do have a meaningful proposal. odt offers basic xml template, so why doesn't docx I wonder? There is a reason to want one in order to control relative placement of meta-elements like author, date, etc, or adding new ones. F.ex., I use pandoc for scientific papers, and most local journals (and some co-authors) tend to prefer doc to other formats. Being able to make a template that adheres to a particular formatting would be a godsend in some cases (for now I have to edit pandoc's output by-hand, and it is a chore). Not sure if it'd be possible with dotx template, but personally, I prefer raw xml to clunky word... not that I assume that everyone would, but I'd like to have an option at least. I'll look into dotx, but if docx is any indication, it's probably a horribly convoluted and fragile format...

**Comment by jgm** [comment]
I'm open to a specific proposal about a docx template, and I see the use of that.  But I still think that (even for people who prefer editing XML to opening Word) it makes more sense to have something like a reference.dotx.  The reason is that many customizations you might wish to make in a template involve resources that would need to be in a container (e.g. you might want a template with company letterhead).  Anyway, let's close this, and when you're ready you can open another issue or PR for a specific docx template proposal.
