### ISSUE TITLE
TEI writer

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#2047]
"The Text Encoding Initiative (TEI) is a standard for the representation of textual material in digital form through the means of text encoding.This standard is the collaborative product of a community of scholars, chiefly from the humanities, social sciences, and linguistics who are organized in the TEI Consortium (TEI-C http://www.tei-c.org)."  http://teibyexample.org/

Of course TEI contains lots of rich semantic markup that doesn't correspond to anything in the Pandoc document model.  But it might be useful to people who encode things in TEI if they had a quick way to import documents to a rough (but valid) TEI document that could be progressively enhanced.

**Comment by markuskiller** [comment]
great idea! +1

**Comment by adunning** [comment]
This would be excellent. There are a few journals experimenting with the use of TEI as a base format, such as DH Quarterly and RIDE, and Pandoc support would be a huge help. You will have to choose a customization for output; TEI Simple (https://github.com/TEIC/TEI-Simple) might be suited to this purpose.

**Comment by jasonseeley** [comment]
+1 I've been kinda wanting this, too. I think TEI-Tiny might be more appropriate than Simple, though, especially with its wide adoption. (http://www.tei-c.org/Guidelines/Customization/Lite/)

**Comment by ousia** [comment]
:+1: 

I think _TEI Lite_ would be a better option than _TEI Simple_ because of its widespread adoption.

@jasonseeley, you meant _TEI Lite_, didn’t you?

**Comment by adunning** [comment]
@sebastianrahtz, do you have any thoughts on the best TEI customization to implement here?

**Comment by sebastianrahtz** [comment]
The difference between TEI Lite and TEI Simple in this respect is trivial. Don't worry about it. I'd be very very surprised if the sort of lowest-common-denominator that is  Pandoc's everyday business would trigger complex TEI XML that exposed the differences.  More interesting is whether to use @rend, or@rendition or @style to indicate changes of emphasis (where you can't tell why the emphasis changes). TEI Simple standardizes on @rendition, with a fixed range of values - I might suggest Pandoc follows those. See list in "3.5. Attribute classes" in http://htmlpreview.github.io/?https://github.com/TEIC/TEI-Simple/blob/master/teisimple.html

**Comment by Hasimir** [comment]
I was thinking of requesting a a writer for [DITA](http://docs.oasis-open.org/dita/v1.2/spec/DITA1.2-spec.html) support (or partial support, just enough to cover file conversion to DITA Topics since the bloody thing is monstrously enormous and about to get more so with [version 1.3](http://docs.oasis-open.org/dita/dita/v1.3/dita-v1.3-part3-all-inclusive.html) in public review).  However, since TEI and DITA are already coming together for things like [DITA for Publishers (D4P)](http://dita4publishers.sourceforge.net/), this might be just what I and others need to get what we want with less pain for all.

**Comment by c-forster** [comment]
I have gotten a TEI writer working which writes out TEI that is consistent with [TEI Simple](https://github.com/TEIC/TEI-Simple), using the standardized @rendition values mentioned by @sebastianrahtz above. The relevant writer files are available in [this repo](https://github.com/c-forster/pandoc/tree/teiwriter); a template in a branch of the pandoc-templates repo [forked here](https://github.com/c-forster/pandoc-templates/tree/teiwriter), allow the writer to produce a complete and valid TEI file (which validates against the DTD in the TEI-Simple repo) with the standalone flag.

This writer is based on the existing Docbook writer, and some of that shows (for instance, in how it handles headings). It's not perfect, but it produces valid output against the current TEI Simple DTD. I'd be interested in any feedback and would love to get this in shape for a pull request, if it looks up to snuff.

**Comment by adunning** [comment]
This is a great start; thanks for taking it on. Maybe use <lb/> for LineBreak?

**Comment by c-forster** [comment]
Thanks for the suggestion @adunning; I've added `<lb />` for `LineBreak`. I've gone ahead and made a Pull Request; please feel free to continue to make suggestions for improvements there.

**Comment by jgm** [comment]
Closed via #2638
If there are further suggestions for improvement, please open new, targeted issues.

**Comment by fbaube** [comment]
DITA could be implemented in its new variant form LwDITA.

**Comment by Hasimir** [comment]
It's probably not even necessary to restrict it to just Lightweight DITA since there's already a Markdown to DITA conversion function in the latest release of [oXygenXML Editor](https://www.oxygenxml.com/) and it doesn't restrict the conversion to just Lightweight DITA, it utilises the full standard definition and namespace.

Now that particular method won't be released as GPL code (maybe Apache 2, but I haven't checked), it proves the most important point: that it can be done.  The main issue is how it was done and I suspect XSLT 2.0 or higher was involved.
