### ISSUE TITLE
Documenting usage of docx styles

### ISSUE THREAD

**Issue by jo-tud** [jgm/pandoc#2048]
Even though paragraphs in a word docx document are formatted with a stlye named _Verbatim Char_ this is not reflected in the markdown document.
According to the documentation this should work, right?

**Comment by lierdakil** [comment]
I'm confused. Are you talking about docx reader?

**Comment by jo-tud** [comment]
Yes - is this the wrong place for docx reader?

Am 01.04.2015 21:37 schrieb Nikolay Yakimov <notifications@github.com>:

I'm confused. Are you talking about docx reader?

**Comment by lierdakil** [comment]
No, it's the right place. Probably because I was working on docx *writer* last couple weeks, I became a little confused with your report is all.

There is a multitude of reasons why this might not work. Two most obvious are 

1. `Verbatim Char` should be a character style, and not paragraph style.
2. Word can sometimes mangle style identifiers, and docx reader does not handle all cases of that well (yet).

If you can't resolve this, consider sharing a minimal example docx so that we could look and see what went wrong. You can upload it somewhere, or e-mail me directly (see github profile).

**Comment by jo-tud** [comment]
Thank you, it is working now. You were right, I had overlooked the fact that it must be a character style. While googling I stumbled upon the  *pandoc/tests/docx/codeblock.docx* file and saw that it is possible to have a style named *Source Code* as a paragraph style. This fit my purpose even more - but I think it is not yet reflected in the documentation.

**Comment by jgm** [comment]
We should add something to the documentation about the SourceCode style,
and how it is added automatically.

**Comment by lierdakil** [comment]
In all honesty, we should properly document use of docx styles by reader
*and* writer, because right now it's... not the best documentation I've
seen.
02 апр. 2015 г. 19:55 пользователь "John MacFarlane" <
notifications@github.com> написал:

**Comment by mb21** [comment]
Fixed through https://github.com/jgm/pandoc/pull/2318
