### ISSUE TITLE
Browser and antivirus blocking the download of msi setup

### ISSUE THREAD

**Issue by tymric** [jgm/pandoc#2051]
Hi,

My browsers (Chrome and Firefox) are blocking the download of the msi file. When I try to proceed anyway, the antivirus (Comodo Internet Security) then blocks the download. Could you please post the md5 sums so one could verify that the files are secure? Thanks

**Comment by jgm** [comment]
The msi is signed with a code signing certificate that I purchased from
Comodo (ironically!).

You can safely download the msi.  Assuming the msi on github has
not been tampered with, Windows will verify the key when
you install the package from the msi.  (If it isn't a properly
signed package, Windows will give you a very stern warning.)

MD5 (pandoc-1.13.2-windows.msi) = d368d072a2b84c72f1ed863db96d7826

I'm not sure how posting this on the github releases site would
help give confidence, though, since if someone could have tampered
with the msi on the site, they could presumably also have altered
the MD5, right?

+++ Tymric [Apr 04 15 18:43 ]:

**Comment by tymric** [comment]
I understand, but it's reassuring nonetheless, and I thought I ought to raise the issue in case someone else encounters it. I've reported it as false alert. Thank you
