### ISSUE TITLE
Operator keywords not highlighted for Python

### ISSUE THREAD

**Issue by dato** [jgm/pandoc#2054]
Hello!

Consider the following Markdown file, _python.md:_

```
~~~ { .python }
for x in y:
    print x
​~~~
```

I would expect Pandoc to highlight all three keywords: `for`, `in`, and `print`; but `in` isn’t.

```
$ pandoc <python.md
```
gives:
```html
<pre class="sourceCode python"><code class="sourceCode python"><span class="kw">for</span> x in y:
    <span class="dt">print</span> x</code></pre>
```

My pandoc version is:

```
pandoc 1.13.2
Compiled with texmath 0.8.0.1, highlighting-kate 0.5.11.1.
```

highlighting-kate 0.5.11.1 lists the operators, [of course](https://github.com/jgm/highlighting-kate/blob/0.5.11.1/xml/python.xml#L31), so I don’t know where the bug is.

Many thanks in advance!
___
P.S.: The _python.md_ above has a zero-width space because I didn’t know how to get GitHub Markdown unconfused. Beware of copying & pasting.

**Comment by lierdakil** [comment]
I can confirm it’s the same with highlighting-kate-0.5.14. But that’s
because all list_operators are rendered as Normal in Python syntax
definition, and Normal is not marked by highlighting-kate in any way (as it
shouldn’t be). I don’t think this can be considered a bug. More like a
“feature” of Kate’s syntax model for Python.
​

2015-04-06 2:16 GMT+03:00 Dato Simó <notifications@github.com>:

**Comment by jgm** [comment]
Yes, this doesn't look like a bug -- the library pandoc uses for highlighting, highlighting-kate, constructs its tokenizers from kate's xml syntax definitions, and it looks like this was done correctly.  You may not like the way the syntax definition works, but I'd rather not make ad hoc changes to this.
