### ISSUE TITLE
Serious regression in markdown reader

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#2062]
```
echo "## [y]" | pandoc
pandoc: <<loop>>
```

This doesn't happen in 1.13.2, so it must have been introduced by subsequent changes.
We'll need to bisect to find out where this bug comes from.  The `<<loop>>` makes me suspect it may have to do with the changes removing the F Monad, but that's just a speculation it would be easy enough to confirm.

**Comment by jgm** [comment]
Speculating that it has something to do with `registerHeader`, since it seems header-specific.

**Comment by mpickering** [comment]
Almost certainly my fault - I can look at it over the weekend.

**Comment by jgm** [comment]
@mpickering, I confirmed that the problem exists in the first commit after your F Monad removal changes were merged in, and does not exist  in the first commit before your changes.  So, as we suspected, it seems to have something to do with the way `registerHeader` interacts with those changes.

**Comment by lierdakil** [comment]
Okay, I dug around a little... And I don't understand how this recursive definition is supposed to work (and it probably loops here -- any strictly evaluated call to `ask` causes loop)

```haskell
runMarkdown :: ReaderOptions -> String -> MarkdownParser a -> a
runMarkdown opts inp p = fst res
  where
    imd = readWithM (retState p) def{ stateOptions = opts } (inp ++ "\n\n")
    res = runReader imd s
    s :: ParserState
    s   = snd $ runReader imd s -- I'm confused about this bit
```

(from 13fb1d61017ecdf6f4e16f811c39fb2f6ca34c99)

The problem is, as far as I can gather, that `registerHeader` takes `text` parameter, which in this particular case is parsed (or at least tried) through `referenceLink` parser, and those seem interdependent via state variables. Somewhere in this mess, evaluation is forced and we get a loop. I'm too confused on how is this *supposed* to work to dig any further.

**Comment by jgm** [comment]
Yes, I think only @mpickering really understands this (he made this change to simplify lots of other things in the readers), and he's going to have a look this weekend.

**Comment by mpickering** [comment]
The problem is that `registerHeader` forces the parsed value to decide what the header ID is.

**Comment by jgm** [comment]
Is there a solution?

>   The problem is that registerHeader forces the parsed value to decide
>   what the header ID is.

**Comment by nkalvi** [comment]
@mpickering 
Pardon this comment with zero Haskell knowledge:

The code checks for *Ext_auto_identifiers*
```
if null ident && Ext_auto_identifiers
```
but does it check for *implicit_header_references*?

**Comment by mpickering** [comment]
Yes but.. this might be a reoccuring problem. I'm beginning to think that it might not be a good idea. If there's anywhere else in the Reader which uses the result of the parse before the whole parse has finished then it will `<<loop>>`. Especially as I don't have much time to devote to this it might just be better to revert the patch.

**Comment by mpickering** [comment]
On the other hand, if this is the only place where this kind of introspection is necessary then I can just patch it and we can move on.

**Comment by lierdakil** [comment]
Correct me if I'm wrong, but in order to keep this from blowing up, can't
we use iterative approach as a fallback? I.e. have it run starting from
default state and then arrive at the static solution after a couple of
iterations? This will be several times slower, and by all means we should
print a warning, but it will keep pandoc from blowing up. Over time, we
could fix warnings that will pop up (if any) and include regression tests
for those. All in all, I do like @mpickering's approach, although it's
somewhat headache-inducing.

I might be not thinking clearly, though. It's nearly morning and I had a
couple of scotches earlier. Sorry if I blabber.

2015-04-10 23:35 GMT+03:00 Matthew Pickering <notifications@github.com>:

**Comment by nkalvi** [comment]
@lierdakil Glad to have you back from your 'rest' :smile: Since you seemed to be tired of resting, and I don't know any Haskell, could you please see whether changes here are relevant to the issue:

https://github.com/jgm/pandoc/commit/13fb1d61017ecdf6f4e16f811c39fb2f6ca34c99#diff-2db348243eee8710717037a8cd14c4d3 around
```
implicitHeaderRefs <- option False $
                          True <$ guardEnabled Ext_implicit_header_references
-  let makeFallback = do
-       parsedRaw' <- parsedRaw
-       fallback' <- fallback
-       return $ B.str "[" <> fallback' <> B.str "]" <>
+  let makeFallback =
+                B.str "[" <> fallback <> B.str "]" <>
                 (if sp && not (null raw) then B.space else mempty) <>
-                parsedRaw'
-  return $ do
-    keys <- asksF stateKeys
-    case M.lookup key keys of
-       Nothing        -> do
-         headers <- asksF stateHeaders
-         ref' <- if labIsRef then lab else ref
-         if implicitHeaderRefs
-            then case M.lookup ref' headers of
-                   Just ident -> constructor ('#':ident) "" <$> lab
-                   Nothing    -> makeFallback
-            else makeFallback
-       Just (src,tit) -> constructor src tit <$> lab
+                parsedRaw
+  keys <- asks stateKeys
+  headers <- asks stateHeaders
+  return $
```

@mpickering Pardon me again for commenting with zero Haskell knowledge, I'm wondering whether it is related to fallback while handling implicit header references in Markdown reader module.

**Comment by lierdakil** [comment]
@nkalvi, not really relevant. It's a really mind-bending problem, and I
believe at the moment only @mpickering understands this code well, since he
wrote it. However, I can tell that it's not directly related to *any*
markdown extensions or handling thereof (sorry if I misunderstood your
question). Mail me directly if you have further questions (see github
profile), let's not create noise here.
11 апр. 2015 г. 4:28 пользователь "nkalvi" <notifications@github.com>
написал:

**Comment by nkalvi** [comment]
@lierdakil thank you!

As you may already know,
 `echo "## [y]" | pandoc -f markdown-implicit_header_references` works fine.
(outputs `<h2 id="y">[y]</h2>` as expected).

So does: `echo '[y]' | pandoc`

**Comment by jgm** [comment]
+++ Nikolay Yakimov [Apr 10 15 18:07 ]:
>   we use iterative approach as a fallback? I.e. have it run starting from
>   default state and then arrive at the static solution after a couple of
>   iterations? This will be several times slower, and by all means we

Some background:
Originally pandoc did a couple of passes over the input,
first extracting notes and links, then parsing the rest.

Then I figured out how to do it with one pass.  The trick
was for the parsers to return, not Inlines or Blocks or
other Pandoc objects, but objects in a special Reader monad
(the "F Monad" for "Future"), which would then be run at
the end of parsing to integrate all the notes and
references.

This gave us a one-pass parse, at the price of some ugly
code, and required us to have several versions of some
shared parsers (since not all readers used the F Monad).

Matt's aim was to remove the reliance on the F Monad, and
clean up the code, while retaining the one-pass parsing
strategy.  And it works, except for this problem -- and
any other similar problems we might introduce with future
changes.

**Comment by lierdakil** [comment]
What I meant was:

1. Try to parse with one pass, as per Matt's algorithm
2. Catch `NonTermination` exception
3. On exception, print a warning, and run with two passes (i think two is enough?)

This would keep things from blowing up for users, but would also print a warning, which could be reported and subsequently fixed. That would be a suboptimal fallback just in case we don't catch all places where it can `<<loop>>`. Not arguing we should revert to two-pass algorithm for good.

That way, we can live both without F monad and with no fear of angry users.

Just a thought.

**Comment by jgm** [comment]
@lierdakil thanks for the clarification. I guess it's partly a question of whether the present issue can be "fixed," or if this kind of `<<loop>>` issue is going to be unavoidable with the current architecture.  I don't have a good sense for this, but maybe @mpickering does.  If this issue can be patched up, maybe the thing you suggest would make sense.

**Comment by jgm** [comment]
I decided to revert back to the F Monad for now.  If we ever figure out a safe way to do this, we can go back again.  @mpickering, if you have a chance to look over the patch for this commit, could you let me know if I've messed anything up?
