### ISSUE TITLE
--self-contained with a specific text inside <pre> tags

### ISSUE THREAD

**Issue by rasta0** [jgm/pandoc#2147]
Problem with transforming text inside \<pre\> tags, from markdown into html, with pandoc 1.13.2, command : pandoc -t html5 -o tst.html --standalone --self-contained

Input:
\<pre\>&in\</pre\>
Output:
\<pre\>∈\</pre\>
Expected:
\<pre\>&amp;in\</pre\>

The older version 1.11.1 worked fine.
When I tried more examples: \<pre>&i\</pre\> or \<pre\>&on\</pre\> - the result was correct.

**Comment by nkalvi** [comment]
`&in` is being parsed as the named HTML entity `in;` (http://www.w3.org/TR/html5/syntax.html#named-character-references). So you may want to try with `<pre>&amp;in</pre>`.

@jgm Would it be better to have `parseTags` in SelfContained.hs treat input as entities only when they end with `;`? It may help to avoid some issues like this.

**Comment by jgm** [comment]
@nkalvi All the entity resolution is handled by the tagsoup library, which according to its documentation uses the algorithm from the HTML5 spec.

@rasta0 You do realize that this is invalid HTML, right?  What output are you expecting?  If you want a literal `&in`, you need to escape `&` as `&amp;`.

**Comment by nkalvi** [comment]
@jgm I noticed that tagsoup library has `parseOptions` with
>The options optEntityData and optEntityAttrib control how entities, for example `&nbsp;` are handled. Both take a string, and a boolean, where True indicates that the entity ended with a semi-colon ;. 

Per http://www.w3.org/html/wg/drafts/html/CR/syntax.html#character-references
>Named character references
The ampersand must be followed by one of the names given in the named character references section, using the same case. The name must be one that is terminated by a ";" (U+003B) character.

That's also why I was suggesting the change.
Though `&in` is not valid HTML, many browsers don't seem to complain about it.

----
@rasta0 Would it be feasible to use verbatim code blocks instead of `<pre>`? They will be properly escaped. F.ex. `echo '    &in' | pandoc --self-contained` will produce `<pre><code>&amp;in</code></pre>`.

**Comment by jgm** [comment]
+++ nkalvi [May 11 15 22:04 ]:
>@jgm I noticed that tagsoup library has `parseOptions` with
>>The options optEntityData and optEntityAttrib control how entities, for example `&nbsp;` are handled. Both take a string, and a boolean, where True indicates that the entity ended with a semi-colon ;.
>
>Per http://www.w3.org/html/wg/drafts/html/CR/syntax.html#character-references
>>Named character references
>The ampersand must be followed by one of the names given in the named character references section, using the same case. The name must be one that is terminated by a ";" (U+003B) character.
>
>That's also why I was suggesting the change.
>Though `&in` is not valid HTML, many browsers don't seem to complain about it.

I didn't know about the option, thanks.

**Comment by rasta0** [comment]
Thank you guys, you helped me. I used verbatim code locks without \<pre\> tags.
