### ISSUE TITLE
Double <a>

### ISSUE THREAD

**Issue by ghost** [jgm/pandoc#2159]
Hello,
First: Thank you for you job :+1: 

- the exact command line used:

``` pandoc --from markdown_github --to html --standalone```

- the exact input used

```Github is at [https://github.com/jgm/pandoc](https://github.com/jgm/pandoc)```

- the output received

```<p>Github is at <a href="https://github.com/jgm/pandoc"><a href="https://github.com/jgm/pandoc" class="uri">https://github.com/jgm/pandoc</a></a></p>```

- the output you expected instead

```<p>Github is at <a href="https://github.com/jgm/pandoc" class="uri">https://github.com/jgm/pandoc</a></p>```

> % pandoc --version
> pandoc 1.12.4.2
> Compiled with texmath 0.6.6.1, highlighting-kate 0.5.8.5.

**Comment by nkalvi** [comment]
@mozzie42 Just `Github is at https://github.com/jgm/pandoc` should give what you expect.
BTW, the current version of Pandoc is 1.13.2.

**Comment by mozzie42** [comment]
Of course, your example is correct but :

```[http://t.co/OnKyJh3ePh](http://www.sysforensics.org/2015/05/introduction-to-hardware-forensics)```

It's the same with last version :) (I use debian package)

**Comment by nkalvi** [comment]
@mozzie42 I had a feeling that you'd come back with something like this :smile:

**Comment by nkalvi** [comment]
Experts will give you a better answer, but why not try this in the meantime:
```html
<a href="http://www.sysforensics.org/2015/05/introduction-to-hardware-forensics">http://t.co/OnKyJh3ePh</a>
```

**Comment by jgm** [comment]
+++ domble [May 18 15 18:06 ]:
>Of course, your example is correct but :
>
>```[http://t.co/OnKyJh3ePh](http://www.sysforensics.org/2015/05/introduction-to-hardware-forensics)```

Here's why this happens.  github_markdown enables a feature that
treats bare URLs as links.  In a link of form [a](b), pandoc parses
the 'a' part as Markdown inline elements.  Since we have a bare URL
in there, it gets parsed as a link, and we end up with the (unwanted)
link-in-a-link.

I don't know if this is a bug.  Consider this small variant:

    [<http://t.co/OnKyJh3ePh>](http://www.sysforensics.org/2015/05/introduction-to-hardware-forensics)

Here, as you can see from
[BabelMark2](<http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5B%3Chttp%3A%2F%2Ft.co%2FOnKyJh3ePh%3E%5D(http%3A%2F%2Fwww.sysforensics.org%2F2015%2F05%2Fintroduction-to-%0Ahardware-forensics)%0A>), lots of implementations give you the link-in-link behavior.  And this seems natural; after all, the `<...>` is telling you, I want this to be an autolink!

One way of thinking about the `autolink_bare_uris` option in pandoc is
that it treats bare URIs as if they were surrounded by `<..>` (the
normal Markdown syntax for a hyperlinked URI).

So, from that point of view the current behavior is correct.

I think it's a pretty rare use case where you have a URI as the
link label, but you want the href to be something different.
(Indeed, this should be discouraged, as it actively misleads
users!)  If you really want this, there are a few ways of getting
it.  For example, you could use `&#58;` instead of the colon in
the URI to avoid autolinking it.  Or you could put it in code
backticks.
