### ISSUE TITLE
pandoc-1.14 build fails because make-pandoc-man-pages won't link properly

### ISSUE THREAD

**Issue by peti** [jgm/pandoc#2190]
Citing from http://hydra.cryp.to/build/903001/log/raw:

~~~~~~~~~
Preprocessing executable 'make-pandoc-man-pages' for pandoc-1.14...
[1 of 1] Compiling Main             ( man/make-pandoc-man-pages.hs, dist/build/make-pandoc-man-pages/make-pandoc-man-pages-tmp/Main.dyn_o )
Linking dist/build/make-pandoc-man-pages/make-pandoc-man-pages ...
Preprocessing executable 'make-reference-files' for pandoc-1.14...
[1 of 1] Compiling Main             ( data/make-reference-files.hs, dist/build/make-reference-files/make-reference-files-tmp/Main.dyn_o )
Linking dist/build/make-reference-files/make-reference-files ...
dist/build/make-pandoc-man-pages/make-pandoc-man-pages: error while loading shared libraries: libHSpandoc-1.14-K3HoBQ8YOCZ1VEC9exe6pr-ghc7.10.1.so: cannot open shared object file: No such file or directory
~~~~~~~

This error did not occur in previous versions of pandoc.

**Comment by jgm** [comment]
Are you using some kind of non-default build (looks like dynamic
linking?)  If so, please give details.

+++ Peter Simons [May 28 15 12:47 ]:

**Comment by peti** [comment]
The build log I referred to contains every detail you may want to know; full configure flags, ghc version, versions of the dependencies involved, etc.

**Comment by jgm** [comment]
As far as I can see, the issue is that you're building with
`--enable-shared`.  make-pandoc-man-pages depends on the main
pandoc library.  It is included in a stanza that cites 'pandoc'
as a dependency, and it lives in a different build directory,
which tells cabal to use the library it just built rather than
recompiling everything again.  With static linking this raises
no issues.  With dynamic linking it seems to cause a problem;
make-pandoc-man-pages is dynamically linked with pandoc, and
when it is run the shared pandoc library cannot be found.
I have no idea why; I've never played around with shared libraries
in Haskell or cabal.  You may want to consult with a cabal
expert about this.

I imagine there's a way to tell make-pandoc-man-pages where
to look for its dynamic library dependencies at run time,
but where should it look for the just-built pandoc library?

+++ Peter Simons [May 28 15 12:54 ]:

**Comment by peti** [comment]
There is a way to triage that build, no doubt, I probably just have to pass appropriate `-rpath` flags to the linker phase or set `$LD_LIBRARY_PATH`, etc.

I believe it's worth thinking about whether it's a good idea to expose users of this package to these kind of issues, though. I think it's nice that `make-pandoc-man-pages` is built without too much duplication, and it's nice that it's built without being installed too. At the same time, I think it's nice if the build just works without too much of a fuss, too. Not everyone is a Cabal expert.

**Comment by jgm** [comment]
Point taken.  I'm experimenting with another design.  This will just add `--man1` and `--man5` options to pandoc, to generate the man pages.  Then we can dispense with man page creation in the build process.
