### ISSUE TITLE
otherlang not working with babel

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#2209]
@jgm,

`otherlang` works fine with polyglossia, but not with babel.

Sample:

``` markdown
---
lang: english
otherlang: greek, italian, latin, french, german
...

dealing with multiple languages
```

Language code in LaTeX output:

``` latex
\ifxetex
  \usepackage{polyglossia}
  \setmainlanguage{english}
  \setotherlanguages{greek, italian, latin, french, german}
\else
  \usepackage[shorthands=off,english]{babel}
\fi
```

I think this should be fixed.

**Comment by nickbart1980** [comment]
(Please disregard the pull request, that wasn't thought through.)

With the current implementation, you should use nothing but the `lang` variable:

~~~
---
lang: greek, italian, latin, french, german, english
...
~~~

LaTeX output:

~~~
\ifxetex
  \usepackage{polyglossia}
  \setmainlanguage{english}
  \setotherlanguages{greek,italian,latin,french,german}
\else
  \usepackage[shorthands=off,greek, italian, latin, french, german, english]{babel}
\fi
~~~

(I totally agree that most _other_ formats require the “main” language only, i.e., the last one in the `lang` list. That's why I feel that `lang` should be parsed into `mainlang` and `otherlang` for _all_ formats. Non-LaTeX templates then will typically contain `$mainlang$` only, of course.)

**Comment by ousia** [comment]
@nickbart1980, sorry, but i need to understand first.

> I totally agree that most _other_ formats require the “main” language only, i.e., the last one in the `lang` list.

The main language (instead of the list of used languages) is a requirement for _all other_ formats than LaTeX (even ConTeXt doesn’t need it).

Or which other format am I missing? 

> That's why I feel that `lang` should be parsed into `mainlang` and `otherlang` for all formats. Non-LaTeX templates then will typically contain `$mainlang$` only, of course.)

Sorry, but why do you want to force `lang` to behave like LaTeX (actually, babel and polyglossia) requires it instead of inviting LaTeX users to list all secondary languages in the `otherlang` variable specifically created for this?

Which is the reason behind adapting all other formats to LaTeX?

**Comment by jgm** [comment]
Has this now been sorted, with the latest round of changes to the latex writer + templates?

**Comment by nickbart1980** [comment]
I think so. Let’s close this but keep https://github.com/jgm/pandoc/issues/895 open.
