### ISSUE TITLE
Multiple references to a footnote cause duplicated footnotes

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#224]
So I was writing up a little something, and I created a footnote [^foo]
with the respective entry at the bottom of the page ([^foo]: full ref) and
then I happened to later cite the same paper and so I chucked in another
[^foo] in there.
Later I happened to notice that this worked, but my reference appears
_twice_! That is, I had expected something like Wikipedia's references
where multiple references link to the same anchor and then back - eg.
https://secure.wikimedia.org/wikipedia/en/wiki/Fujiwara_no_teika#cite_note-famine-66

Google Code Info:
Issue #: 129
Author: gwe...@gmail.com
Created On: 2009-02-21T03:20:15.000Z
Closed On: 2009-12-05T08:00:57.000Z

**Comment by shintakezou** [comment]
pandoc 1.12.3.3; still behaves like that, duplicating the whole note. 

It is not good. All the talk about being able to go back through the backlink makes sense just for those kinds of output format which support hyper links. If my output is LaTeX (for actual print), I want the second "use" of the note to be a reference, no matter how it is really done; it is important that the text of the footnote is not repeated twice (or more times). 

If not automatic, the writer should be able to reference a specific footnote; e.g. `[^15]` generates a link to the footnote (and its back-link, if exists, links back to where `[^15]` appears first), but then I must be able to obtain the "name" and the anchor (thinking about html) for that footnote, say `[^*15]`.

Even if I want to cope with it by myself, I have to do, e.g. "`text[^2]`", then, "`text[^2b]`", but then when I "define" the note `2b` I would like to write "see note `[X](#anchorto2)`". Thus, I need to be able to generate the number assigned to the footnote `[2]`, and its anchor I can use in a link.

**Comment by fasiha** [comment]
I'd totally forgotten about this thread, but today I was working on a custom writer in Lua to target [tufte-css](http://www.daveliepmann.com/tufte-css/) HTML and I thought to myself, "Self, since I have the entire AST, I might as well embed the footnote reference identifier (i.e., '1' in [^1] or 'longnote' in [^longnote]) in the generated HTML (maybe for JavaScript enhancers to later exploit)", but I see that the `Note` node in the AST doesn't include the identifier used to create it.

Could you very briefly sketch how one could accomplish (1) or (2) from your post on [2014 Jun 30](https://github.com/jgm/pandoc/issues/224#issuecomment-47611921), without the identifier being in the AST? Thanks!

P.S. It's awe-inspiring that a professor like you would spend so much time working on ancillary software for others. Truly a million thanks.

**Comment by MrLoh** [comment]
Any chance that this will ever be supported for LaTeX output?

**Comment by jgm** [comment]
The current Pandoc document model just stores footnotes
together with their text.  There is no way to distinguish
between (a) two distinct footnotes with identical text and (b)
two identical footnotes (same note reference and text).

So, it would require a fairly large change in the document
model to support multiple references to the same note.
Any chance ever?  Sure.  Not soon.

+++ Tobias Lohse [Oct 09 15 06:14 ]:

**Comment by fasiha** [comment]
I was planning on writing a filter that scanned for various footnote-related things (like repeated references to the same footnote, but also syntax for sidenotes vs endnotes vs proper footnotes) and placed specific markers at the beginning of the footnote's contents (so it passes through the AST disguised as content), plus a custom writer that understands those markers and properly converts them. Though now that I've said it, I can see it sounds complicated, but I think it would be straightforward to implement for a custom setup—a more general solution is hard, since the Pandoc AST doesn't have space for metadata related to footnotes (such as the reference used, etc.), just the content.

**Comment by technocrat** [comment]
@fasiha I'm working a similar problem with filtering. Following the suggestion of @jgm in another thread, I'm working with custom div classes to create blocks that require special filtering. My immediate filtering needs aren't so complicated as yours, but as I'm working the problem in parallel with learning Haskell, it is feasible to identify the div class, and I think (hope) I'm getting close to being able to correctly walk the enclosed RawBlocks

**Comment by jgm** [comment]
+++ Ahmed Fasih [Oct 10 15 19:33 ]:
>   I was planning on writing a filter that scanned for various
>   footnote-related things (like repeated references to the same footnote,
>   but also syntax for sidenotes vs endnotes vs proper footnotes) and
>   placed specific markers at the beginning of the footnote's contents (so
>   it passes through the AST disguised as content), plus a custom writer
>   that understands those markers and properly converts them.

You could probably get by without a custom writer; just have
your filter insert appropriate raw blocks or inlines for
your target format.

**Comment by krumelmonster** [comment]
Why was this closed? I think it is an issue or, atleast, it would be a neat feature to be able to avoid these duplicate footnotes.
I mean the "(2) ability to have several footnotes in the text that have the same number and refer to the same footnote text."
Alternatively, the option to merge footnotes with the same content (in contrast to footnotes with the same id/number) would be a nice workaround. Would that be a lot of work or is it just not important enough for the developers? In the latter case, I'd try to write a patch.
Problem still occurs in pandoc 1.15.2.1 when converting Markdown to LaTeX to PDF and it's not in the Release notes for 1.16.

**Comment by jgm** [comment]
We have #1603 open, it is essentially the same issue.

Merging all footnotes with the same content isn't a good solution.  Imagine you have a document with several footnotes that say "Ibid."  You certainly don't want to merge these!

**Comment by krumelmonster** [comment]
In my case it would be ok because I'd simply use the same reference instead of using Ibid. By "the option to merge", I meant opt-in this workaround.

**Comment by wilx** [comment]
What about using the solution described in <http://tex.stackexchange.com/a/262956/28495>?

**Comment by jgm** [comment]
+++ krumelmonster [Jan 04 16 07:18 ]:
>   In my case it would be ok because I'd simply use the same reference
>   instead of using Ibid. By "the option to merge", I meant opt-in this
>   workaround.

In my experience it's most common to have separate
references even when the content is the same (e.g. "Smith
2000."), instead of having multiple references to the same
note.  So even as an opt-in I think this would not have
wide appeal.

**Comment by sebunger** [comment]
This really sucks. I use pandoc to first process my source from pandoc to pandoc to make the indentation and table layouts consistent. Then the result gets processed into HTML and PDF. With this problem my source pandoc contains the text for each footnote as many times as there are references. And this should respect DRY since it is a source document. I also happen to agree with the OP that this is very bad style in the output. I have a table with several rows and some of the rows reference a footnote that should appear under the table to give some common special note that applies to those rows. Now I get that duplicated once for each row. With that I could just as well have written it into the row. The whole *point* here was to get only one copy of the explanation.

**Comment by sebunger** [comment]
As a side-node, pandoc should also keep the longnote IDs when processing pandoc to pandoc.

**Comment by airtower-luna** [comment]
Duplicate footnotes may be fine for references, but having duplicate explanation footnotes for the same thing on the same page is not a good look and rather annoying to the reader (because they can't see from the number that they already read the same explanation).
