### ISSUE TITLE
Some HTML <div> content wrapped in <p> unnecessarily 

### ISSUE THREAD

**Issue by nkalvi** [jgm/pandoc#2247]
F. ex. 
With Pandoc 1.14.0.4
```
echo '<div>
 <span>test</span>
</div>' | pandoc'
```
results in:
```
<div>
<p><span>test</span></p>
</div>
```

where as Pandoc 1.13.0.1 produces expected output:
```
<div>
<span>test</span>
</div>
```

**Comment by jgm** [comment]
Not a bug, I think, just the result of the addition of "native divs."

With `native_divs`, pandoc parses whatever is inside the div tags just
as it would have parsed it by itself, and sticks the result in the Div
container.

**Comment by nkalvi** [comment]
Thanks again @jgm for clarifying.

Yes, I can get the expected results with `-f markdown-native_divs`.
But I feel that having this (and `native_spans`) turned off by default may be better. 
Some former users may see unexpected changes in some output when upgrading to 1.14.x or higher.

**Comment by jgm** [comment]
I just checked: `native_divs` has been in pandoc since 1.13, and changing the default now would not be a good idea.

This raises the question why you're seeing a difference between 1.13.0.1 and 1.14.  Clearly something changed in how `native_divs` behaves.

I believe this is due to 598d3ee23b708634ac8526cdc03291f17803eb2a, see #1591.
This change was in 1.13.2.

**Comment by nkalvi** [comment]
I didn't see that it was in 1.13 - yes, it's better not to change the default.

Yes, it does look like it is related to the change prompted by #1591.
While it makes sense to wrap 'plain' content inside *div* without requiring extra blank line, 
wrapping inline elements in *p* seems unnecessary.

I'm sorry, I cannot see (don't know Haskell yet) from the diff in the reader why it affects only inline HTML elements. F.ex. 

With the following input *h1* doesn't get wrapped in `<p>` in the output:
```html
<div>
  <h1>testing</h1>
</div>
```
while *iframe* in the following does:
```html
<div>
  <iframe src="http://www.w3schools.com"></iframe>
</div>
```

**Comment by jgm** [comment]
The h1 doesn't get wrapped because this by itself would be an HTML block, not a paragraph:
```
<h1>testing</h1>
```
The iframe does get wrapped because this would not be parsed as an HTML block; the iframe tags get parsed as inline HTML:
```
  <iframe src="http://www.w3schools.com"></iframe>
```

You can check this using `pandoc -t native`:
```
[Para [RawInline (Format "html") "<iframe src=\"http://www.w3schools.com\">",RawInline (Format "html") "</iframe>"]]
```

Unfortunately iframe is one of those tags that can be used either in block or inline contexts.  In CommonMark we're working out a better way of dealing with these, so authors will at least have the option of getting them treated as block tags.
