### ISSUE TITLE
1.15.0.3 build fails on Mac OS 10.10.4 while creating manpage

### ISSUE THREAD

**Issue by dunn** [jgm/pandoc#2260]
Here are the [full build logs](https://gist.github.com/dunn/297b517492f80136b741). The relevant error is in `04.cabal`:
```
Creating man/pandoc.1
pandoc: Error running filter man/capitalizeHeaders.hs
fd:4: hPutBuf: resource vanished (Broken pipe)
cabal: Error: some packages failed to install:
pandoc-1.15.0.3 failed during the building phase. The exception was:
ExitFailure 83
```

I had the same problem with 1.15.0.2.

**Comment by jgm** [comment]
This is quite puzzling.  This error was expected with
1.15.0.2, which didn't actually include the file
man/capitalizeHeaders.hs.

1.15.0.3 does include this, so the reason is different.

One possibility is that cabal isn't finding
man/capitalizeHeaders.hs.  (I assume that paths in Setup.hs
are always interpreted relative to the base source directory,
and that has always worked for me in the past, but could
there be something different about your build setup?)

Another possibility is that the file is found, but there's
an error running the filter because (e.g.) the modules
Text.Pandoc.Walk and Text.Pandoc.JSON (or Data.Char) can't
be found.  These belong to modules that are
build-dependencies for pandoc, so I don't see how there
would be a problem here, but again there may be something
special about your setup.  (It shouldn't just be that
it's a sandbox -- I use a sandbox to create the osx
package.)

A third possibility is that runhaskell isn't found in the
path.

Any thoughts?  You might be able to do some local
experiments to narrow down the possibilities.

**Comment by dunn** [comment]
I'm using the Homebrew build environment (I came across this while trying to update the [pandoc formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pandoc.rb)) so there could be something funny going on there.

**Comment by jgm** [comment]
+++ Alex Dunn [Jul 02 15 14:39 ]:
>   I'm using the Homebrew build environment (I came across this while
>   trying to update the [1]pandoc formula) so there could be something
>   funny going on there.

Yes, I had no trouble in my own build environment on OSX,
but nonetheless, I'd like the build procedure to be as
robust as possible, so I'd like to figure out what's going
wrong in your case.

**Comment by jgm** [comment]
I suspect the issue is that you're installing in a sandbox.  So, pandoc-types has been installed, but runhaskell doesn't see it, because it's in the sandbox.  Not quite sure what to do about this.  I may have to break down and just include the built man page in the repository...

**Comment by lslah** [comment]
I've had the same issue when trying to build pandoc in a sandbox on 1.15.0.2/3. Building & Installing pandoc without the sandbox works fine.
git-bisect found that the issue was introduced in 28cb505.
The problem is fixed for me with the current master, but just in case it helps, this might confirm your suspicions:

```
$  dist/dist-sandbox-6644bc13/build/pandoc/pandoc README --filter man/capitalizeHeaders.hs
pandoc: Error running filter man/capitalizeHeaders.hs
fd:4: hPutBuf: resource vanished (Broken pipe)


$  dist/dist-sandbox-6644bc13/build/pandoc/pandoc README| runhaskell man/capitalizeHeaders.hs

man/capitalizeHeaders.hs:1:8:
    Could not find module ‘Text.Pandoc.JSON’
    Use -v to see a list of the files searched for.

man/capitalizeHeaders.hs:2:8:
    Could not find module ‘Text.Pandoc.Walk’
    Use -v to see a list of the files searched for.

```

**Comment by dunn** [comment]
1.15.0.4 works, thanks so much!
