### ISSUE TITLE
Inline latex math in markdown: Typographical error

### ISSUE THREAD

**Issue by jenicek** [jgm/pandoc#2261]
When a sign (+,-,*) is a superscript in inline latex math, it is treated as an operator instead of a normal superscript - it is surrounded by spaces. I have this problem with version 1.15 using the implicit latex math processor when converting from markdown to html. The resulting html code of `$h^+$` is `.. <sup> + </sup>` in contrast to `.. <sup><em>a</em></sup>` for `$h^a$`.

**Comment by cryptocraft** [comment]
This is an issue for me too.  When converting markdown to HTML, binary operators are set with &amp;#8197; / &amp;#x2005; HTML entity ("four-per-em space") Unicode characters each side.  This is undesirable in a number of situtations e.g. $2^{-3}$, the $\oplus$-operator.

In TexMath/Readers/TeX.hs, - is parsed to ESymbol Bin "\x2212" and  \oplus is parsed to ESymbol Bin "\x2295".  When maths is rendered to Pandoc inline elements by TexMath/Writers/Pandoc.hs, expToInlines tt (ESymbol t s) adds these Unicode space characters when t is Bin x, but not (for example) when t is Ord x.

The way maths lists are rendered in TeX is discussed in Appendix G of the TeXbook.  Here, a Bin atom which is either first or last in a maths list, or follows a Bin, Op, Rel, Open or Punct atom, is changed to an Ord atom.  Something along these lines is desirable in TexMath/Writers/Pandoc.hs.

**Comment by jgm** [comment]
OK, try

    cabal update
    cabal install --reinstall  --force pandoc texmath-0.8.4

**Comment by cryptocraft** [comment]
Very nice!  That's solved the problem I was hoping you could solve, and very speedily too - thanks very much indeed.  I (rather pedentically) notice that it doesn't quite avoid "spacing on a binary symbol that follows a Bin, Op, Rel, Open, or Punct atom" - for example, $+++$ is rendended as +<medspace>+<medspace>+.  But I also notice that TeX happens to render $+++$ in the same way, because it changes the first Bin to an Ord, and then the 3rd Bin to an Ord, and then introduces inter-atom spaces according to the table in Chapter 18 of the TeXbook; curiously, it renders $++++$ as +<medspace>+<medspace>++, because it converts Bin Bin Bin Bin to Ord Bin Ord Ord (if the last atom is a Bin it changes it to Ord).  All of which is probably more than anyone really wants to know about the spacing of consecutive Bin atoms.
