### ISSUE TITLE
Markdown writer does not escape initial `+` or `-`

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2279]
A `+` or `-` at the beginning of a paragraph is not escaped in the Markdown writer, whereas `*` is, in Pandoc 1.15.0.4. One would expect the following to return the same result as the input:

```shell
pandoc -f html -t markdown << EOT | pandoc
> <p>* P1</p>
> <p>- P2</p>
> <p>+ P3</p>
> EOT
```

But this is the actual result:

```html
<p>* P1</p>
<ul>
<li><p>P2</p></li>
<li><p>P3</p></li>
</ul>
```

It must be admitted that in many cases this is likely to be desirable behaviour, but not always: I ran into this with [Magna Carta 1215](http://www.bl.uk/magna-carta/articles/magna-carta-english-translation).

**Comment by jgm** [comment]
I've thought about this.  The problem is that the current
escaping code in the Markdown writer doesn't make it
possible to detect if you're at the beginning of a line.
I could escape all `-` and `+` characters, but I think this
would produce messy output (especially  for `-`) that would
be unnecessary in all but very special cases. So I'm
inclined not to make this change.

Note that the CommonMark writer (i.e. cmark), which I
designed with the benefit of hindsight, does keep track of
when you're at the beginning of a line and escape things as
needed.

+++ Andrew Dunning [Jul 06 15 22:11 ]:

**Comment by adunning** [comment]
If that is the case, I agree; I've found that even escaping the square brackets results in output that is more verbose than necessary. Thanks for your consideration!
