### ISSUE TITLE
Undocumented behaviour on template variable

### ISSUE THREAD

**Issue by qsantos** [jgm/pandoc#2281]
The manpage of Debian stretch says:

```
$if(variable)$
X
$else$
Y
$endif$
```

> This will include `X` in the template if `variable` has a non-null value; otherwise it will include `Y`.

However, setting `variable` to "n" or to "no" inserts `Y` as well. While this is not a problem _per se_, it was confusing at first.

I successfully tested this behavior on both 1.15-1 (Github release) and 1.13.2.1 (Debian repository), while converting from Markdown to LaTeX.

**Comment by jgm** [comment]
It's more complex than that, I'm afraid:
```
% cat test.tpl
$if(x)$
YES
$else$
NO
$endif$
% echo "" | pandoc --template test.tpl --variable x=no
YES
%  echo "" | pandoc --template test.tpl --metadata x=no
NO
```
What the man page says is correct, about variables set directly from the command line (which used to be the only option).  Now that variables are set implicitly from metadata, there is a discrepancy.  The difference is this:  metadata fields get parsed into YAML types with Markdown content, so "no" resolves to a boolean False.  But variables are just treated as plain strings, so "no" as a variable resolves to the string "no".  And False and "no" behave differently in the template.

At the very least we need better documentation, because this is confusing.

**Comment by qsantos** [comment]
Oh, I did not expect YAML parser to do that. It would be great if the documentation was clarified on this point. Also, maybe porting this behavior to `--variable` would help consistency?

**Comment by gusbemacbe** [comment]
Good afternoon, @jgm and @mb21 !

I apologise for bringing this old issue, but I am facing this same issue even with the latest version of Pandoc. 

The `pandoc` command parameter `-V` does not understand the key and the value from the YAML `defaults` file's `variables`. 

* `defaults` file:
  
   ```yml
   template: "assets/templates/confluence.html"

   variables:
      confluence_css: true
   ```

* `template` file:

   ```html
   <body>
   $body$
   $if(confluence_css)$
      Here are the relative CSS links
   $else$
      Here are the remote CSS links
   $endif$
   </body>
   ```

Here is the full command:

```sh
pandoc input.md -p -s --wrap=auto -d "confluence.yaml" -V confluence=false --from markdown_github --to html -o "output.html"
```

In the result, in the HTML output file, only `Here are the remote CSS links` always appeared. 

I also tried with `-M` (`--metadata`), but it did not work either.

**Comment by jgm** [comment]
@gusbemacbe The reason is that when you specify `-V confluence_css=false` on the command line, you're setting the variable to the string value `false` (as documented).  Any nonempty string value counts as true when `$if` is used in a template.
