### ISSUE TITLE
Disorderd HTML p tags using video and source

### ISSUE THREAD

**Issue by s-fiebig** [jgm/pandoc#2290]
Using R Markdown I found a problem that @yihui could track down to pandoc (#https://github.com/yihui/knitr/issues/1067). HTML with a video and source tag with an inner HTML are transformed so that the inner HTML surrounding p tags are disordered.
Minimal example working with pandoc 1.15.0.4:

test.md:
```
<video ><source src="foo"/>asdf</video>
```

Run pandoc test.md -o test.html and you get:
```
<video >
<source src="foo"/>
<p>asdf</video></p>
```

Expected is:
```
<video >
<source src="foo"/>
<p>asdf</p></video>
```

**Comment by jgm** [comment]
Try

```
<video>
<source src="foo/">
asdf

</video>
```

The blank line will ensure that pandoc treats asdf as a
separate paragraph.  The issue is that "video" can be either
a block-level or inline-level tag, and pandoc tries to
figure that out based on context.  (It could be more
intelligent about this, admittedly, but the solution
above seems easy enough.)

+++ s-fiebig [Jul 10 15 09:18 ]:

**Comment by s-fiebig** [comment]
That was fast. Thanks for your suggestion! I've solved it by introducing p tags in knitr myself (as written in my old issue linked above). But @yihui must introduce this change.
