### ISSUE TITLE
facility to write custom readers in lua --- please expose Builder API of pandoc to lua callbacks

### ISSUE THREAD

**Issue by zaxebo1** [jgm/pandoc#2311]
As Haskell and its pure functional programming is out of reach - for many mortals like us. 

IF 
(1) luatex can comprehesively expose each of its internals to lua, and
(2) neovim is comprehensively exposing each of its internals to lua , and
(3) Pandoc writer API can be exposed to lua callbacks, 
THEN when  "Pandoc reader API in haskell" is exposed to lua, then it will be real big feature for us. Exposing reader API to lua is of much more importance and far more useful than exposing the writers API to lua.

Coming from asciidoctor, i want to contribute to "pandoc reader for asciidoc" (see https://github.com/jgm/pandoc/issues/1456 ), but I can not give my contribution to this Haskell code, as it will be a big philosophical change/effort for me and many many people to learn Haskell. 

**If pandoc reader API is exposed to lua callbacks, then I and many people , can  easily undertake effort to implement Asciidoc input reader for pandoc.** Even two competing readers (one for haskell and one user contributed effort in lua ) for same format will co-exist in future easily.

This feature is of prime importance, IMHO
Thanks.

**Comment by zaxebo1** [comment]
Once "reader API exposure to lua" is implemented for usage of mass public - It will lead to lesser maintenance of reader and writers in pandoc core on your part.

**Comment by jgm** [comment]
I don't really know what you mean by "pandoc reader API being exposed to lua callbacks."
I assume you don't just mean making `readMarkdown` etc. available.
Do you mean adding lua functions for building up a Pandoc AST?

**Comment by zaxebo1** [comment]
yes, i meant adding lua functions for building up a Pandoc AST, so that full implementation can be achieved

====

> https://en.wikipedia.org/wiki/LuaTeX
> The main objective of the project is to provide a version of TeX where all internals are accessible from Lua.
> In the process of opening up TeX much of the internal code is rewritten. Instead of hard coding new 
> features in TeX itself, users (or macro package writers) can write their own extensions.

Though luatex is not exactly comparable with pandoc, but i am pointing in the sense that having internals available in lua, helped luatex/lualatex flexibility a lot.
In the same way, lua functions for pandoc AST will help a lot, for mortals like us - for whom functional language like Haskell is too too much uphill task, for our procedural-languages-frozen-brains.

**Comment by amerlyq** [comment]
I suppose there still no support for custom pandoc readers yet ?
Therefore the distant future when I could read from my own outline-based markdown format to any other format is even beyond horizon ?:)

**Comment by tarleb** [comment]
I started to work on the lua part of pandoc, but progress is slow. I'm just learning the details of hslua, the basis for pandoc's lua integration. Ömer Sinan Ağacan, the current maintainer of hslua, was so kind to grant me push access to the repo. That might make it simpler to integrate lua even deeper into into pandoc.

I'm currently aiming at integrated Lua filters as a first step. That also touches the builder API.  There isn't much to show yet though. (Well, there is my [panlunatic](https://github.com/tarleb/panlunatic) experiment, but that's on the writer side and only tangentially related).

**Comment by jgm** [comment]
@tarleb with your recent additions, do you think this issue can be closed?

**Comment by tarleb** [comment]
The pandoc.lua module should be complete enough to consider this done. Maybe it could even be combined with your (jgm) lunamark library, which would be very interesting.

**Comment by zaxebo1** [comment]
some url link for where to find a small example or documentation for using this?

**Comment by tarleb** [comment]
Documentation is work in progress.  There is a [very first draft](https://github.com/jgm/pandoc/blob/master/doc/lua-filters.md) available, feedback is welcome.  The module documentation mentioned in that file must be generated from the [`data/pandoc.lua`](https://github.com/jgm/pandoc/blob/master/data/pandoc.lua) module via [LDoc](https://github.com/stevedonovan/LDoc): `ldoc data/pandoc.lua -o pandoc-module -f markdown`.

The whole lua-filter system will be part of the next pandoc version when it is released.  A snapshot of the current development version can be downloaded from the non-official [pandoc-nightly](https://github.com/pandoc-extras/pandoc-nightly) website.

**Comment by tarleb** [comment]
If you have questions, feel free to mail me directly. I'm curious how what you have in mind and how the docs and module can be improved to make things easier.

**Comment by amerlyq** [comment]
@zaxebo1, were your experiments to create custom reader considered successful ?
Even with recently updated version of docs in aforementioned draft I can't comprehend where to start with.
Because custom formats require custom parsing beforehand but lua-filters in pandoc allow us to manipulate AST only after parsing was done. I feel like missing some point there though.

**Comment by zaxebo1** [comment]
nope, its not working :-( 

1) i guess we will have to wait for release of pandoc 2.0 which is due in October end.
  ref: https://github.com/jgm/pandoc/blob/master/doc/lua-filters.md

2) I think apart from "just tidbits" of example lua reader code, a *real full scale "working example" of custom reader* implemented in lua (With properly documented code) will be very useful. Say, orgmode or some other format reader fully and "officially" implemented in lua by @tarleb or anybody who is developing this interface. 
So that others can use that fully working reference code as reference to implement their own custom format.

**Comment by jgm** [comment]
lua filters don't affect parsing itself.  They only
manipulate the AST after parsing.  That's enough for a lot
of customization, though.

**Comment by amerlyq** [comment]
@jgm, it's exactly what I meant. Whole this issue is about how to provide custom format parsing facilities to pandoc. I supposed it would be similar to Builder pattern, where pandoc provides API to access raw file content in Lua, and latter builds AST on its own, calling pandoc ast API with corresponding pieces of extracted data.

And, similar to @zaxebo1 I would appreciated example, however much less greedy in wishes -- any fictitious simplified markup will do: e.g simplified markdown as proof-of-concept.

**Comment by tarleb** [comment]
I've got to apologize, it seems like I misunderstood and underestimated the amount of customization you require for your projects.

What I meant above is that methods to build new pandoc elements are now available in lua filters, making it possible to do *additional* parsing. The parsing step itself cannot be altered.

Here is a quick example: Imagine an org-mode file in which CSV data is included in src blocks:

    #+BEGIN_SRC csv
    value 1,value 2,and even more values
    #+END_SRC

Assume that each row is now to become a list. This can be done by applying a function on all `csv` code blocks, parse the content and create the lists from that.

``` lua
function CodeBlock(elem)
  if elem.classes[1] == "csv" then
    local lists = {}
    for line in elem.text:gmatch("[^\r\n]+") do
      local items = {}
      for item in line:gmatch("([^,]*)") do
        table.insert(items, {to_block(item)})
      end
      table.insert(lists, pandoc.BulletList(items))
    end
    return lists
  end
end

function to_block(str)
  return pandoc.Plain{pandoc.Str(str)}
end
```

All calls to members of the `pandoc` module construct new elements.

If you know that the items are in org format, then you could also use pandoc to parse it for you instead of constructing the list item block by hand:

``` lua
function to_block(str)
  return pandoc.read(str, "org").blocks[1]
end
```

This is a contrieved example, plus the pattern-based "parsing" used above is rather bad. One would get better results by using something like [LPeg](http://www.inf.puc-rio.br/~roberto/lpeg/lpeg.html).

**Comment by amerlyq** [comment]
@tarleb, thanks for example.
However, it seems with this approach even extending/altering syntax of regular readers is tricky.

Some time ago -- I assume after issue was closed without actual solution in May -- I was desperate and started writing my own reader in haskell, completing about one third of required code. It was not easy but not hard either.
And still all those efforts were in vain -- when I understood why and for which usecase I'm writing it.
I never ever will be contributing that parser into pandoc codebase.
Simply because it's niche markup -- there is no one who ever need it, beside me and that guy at neighbour table.

I have collection of notes in two more obsolete markups from my own past. 
Also there are some structured notes of my predecessor from current proprietary project, which are as heavenly beautiful as they alien to anything I know -- but which must be ported to confluence some day. And on top of that there is some legacy 3rd party documentation which is formatted in such a way that I can't stop wondering wtf-is-that, being obviously crappily converted from whatever it was before. I'm only glad that these convertion results are regular enough to be parsed.

So, I need markup for me, for that guy, and for several one-time tasks, efforts to write full-fledged parsers in haskell for which are not worthy. And maintaining my own fork with all of them isn't the best way to spend time and resources, assuming I need `stack` with 100+ packages on 3+GB space and regular merging with upstream.
So, I'm strongly interested in constructing AST by Lua and keeping only single separate file somewhere.

I'm sure @zaxebo1 has it's own hardships, therefore similarly requires non-native reader.

**Comment by jgm** [comment]
+++ Dmytro Kolomoiets [Oct 08 17 22:40 ]:
>   So, I'm strongly interested in constructing AST by Lua and keeping only
>   single separate file somewhere.

You can write a parser for this custom format in any
language you like, and emit pandoc JSON to be consumed
by pandoc.  Then you can target any output format pandoc
supports.

**Comment by zaxebo1** [comment]
> You can write a parser for this custom format in any language you like, and emit pandoc JSON to be consumed by pandoc

ya, great idea.  :-) 
but stumbling block is that, i think pandoc JSON is currently not documented anywhere

**Comment by jgm** [comment]
+++ zaxebo1 [Oct 09 17 04:22 ]:
>     You can write a parser for this custom format in any language you
>     like, and emit pandoc JSON to be consumed by pandoc
>
>   ya, great idea. :-)
>   but stumbling block is that, i think pandoc JSON is currently not
>   documented anywhere

True, but you can figure it out easily enough by using

    pandoc -f native -t json

**Comment by zaxebo1** [comment]
> pandoc -f native -t json

ohh, i somehow missed that simple point.
Thanks for pointing it out

====================

@jgm 
Q) is JSON format planned to be largely backward compatible. (As this is an internal format, so we fear that it may be broken on every major release.)

**Comment by jgm** [comment]
+++ zaxebo1 [Oct 08 17 21:46 ]:
>   [1]@jgm
>   Q) is JSON format planned to be largely backward compatible. (As this
>   is an internal format, so we fear that it may be broken on every major
>   release.)

We try to avoid breaking it too often.  There will be at
least some changes whenever there's an increment of the
first, second or third digit in the version of pandoc-types.
But we often go through several pandoc versions without any
changes to pandoc-types.

**Comment by tarleb** [comment]
Here's a less contrieved example which demonstrates how filters can be used to extend or alter an existing format. The below code reads a Markdown format, but parses text emphasized using underscores chars as special spans. It's buggy and intended only as a proof-of-concept. It would be used by defining the *actual* input file via the `infile` meta value:

    echo " " | pandoc -t html --lua-filter=read_custommark.lua -Minfile=my-file.custom-format`

where `read_custommark.lua` contains this:

``` lua
local matches = {}

function replace_underlined_with_hash(str)
  -- Below code could be made more efficient by using `string.find`.

  local sha1
  local hashes = {}
  local underline_pattern = "_([^_]+)_"
  -- find and store all underlines
  for pre, outer, inner, post in str:gmatch("(.?)(" .. underline_pattern .. ")(.?)") do
    if (pre == "" or pre:match("%s")) and
       (post == "" or post:match("[%s.,;:%(%)/!?]")) then
      sha1 = pandoc.sha1(outer)
      matches[sha1] = {inner = inner, outer = outer}
      hashes[inner] = "_" .. sha1 .. "_"
    end
  end

  -- replace all underlines with their hash value
  local res = str
  for _, m in pairs(matches) do
    res = res:gsub(underline_pattern, hashes)
  end
  return res
end

--- Parse the file specified by the `infile` meta field as custom markdown.
function parse_input_file(doc)
  local infile = io.open(doc.meta.infile)
  local contents = infile:read("*a")
  local hashed_underlines = replace_underlined_with_hash(contents)
  infile:close()
  return pandoc.read(hashed_underlines, 'markdown')
end

function expand_hashes(str_elem)
  local match_tbl = matches[str_elem.text]
  if match_tbl then
    local inlines = pandoc.read(match_tbl.inner, "markdown").blocks[1].content
    return pandoc.Span(inlines, {"", {"underline"}, {}})
  end
end

function unwrap_underline(elem)
  local first = elem.content[1]
  if first.t == "Span" and first.classes[1] == "underline" then
    return first
  end
end

return {
  {Pandoc = parse_input_file},
  {Str = expand_hashes, Emph = unwrap_underline}
}
```

It will be simpler to go via JSON in most cases, but a hacky solution like the above might safe you some time if your input format is very similar to one supported by pandoc.
