### ISSUE TITLE
headers + header_attributes + verbatim inline formatting

### ISSUE THREAD

**Issue by mavenaut** [jgm/pandoc#2324]
The essence of the bug is that the {-} or {.unnumbered} header attribute is ignored if you use verbatim text for the header value.  All other inline formats seem to process correctly.  This holds true for both setext and atx headers.

The bug occurs seems to occur when the verbatim text is the last token before the header attributes.  See the last three example lines.

**Example**

Running pandoc 1.15.0.6

~~~~
pandoc --to=html --number-sections 
~~~~

on

~~~~
# Header 1
## Header 2

`Header 2` {-}
----------

### Header 3 {-}
### *Header 3* {-}
### **Header 3** {-}
### ~~Header 3~~ {-}
### Header ^3^ {-}
### Header ~3~ {-}
### `Header 3` {-}
### `Header 3` {.unnumbered}

### Level `3` header {-}
### `Level` 3 header {-}
### Level 3 `header` {-}
~~~~

produces

~~~~
<h1 id="header-1"><span class="header-section-number">1</span> Header 1</h1>
<h2 id="header-2"><span class="header-section-number">1.1</span> Header 2</h2>
<h2 id="header-2-1"><span class="header-section-number">1.2</span> <code class="unnumbered">Header 2</code></h2>
<h3 id="header-3" class="unnumbered">Header 3</h3>
<h3 id="header-3-1" class="unnumbered"><em>Header 3</em></h3>
<h3 id="header-3-2" class="unnumbered"><strong>Header 3</strong></h3>
<h3 id="header-3-3" class="unnumbered"><del>Header 3</del></h3>
<h3 id="header-3-4" class="unnumbered">Header <sup>3</sup></h3>
<h3 id="header-3-5" class="unnumbered">Header <sub>3</sub></h3>
<h3 id="header-3-6"><span class="header-section-number">1.2.1</span> <code class="unnumbered">Header 3</code></h3>
<h3 id="header-3-7"><span class="header-section-number">1.2.2</span> <code class="unnumbered">Header 3</code></h3>
<h3 id="level-3-header" class="unnumbered">Level <code>3</code> header</h3>
<h3 id="level-3-header-1" class="unnumbered"><code>Level</code> 3 header</h3>
<h3 id="level-3-header-2"><span class="header-section-number">1.2.3</span> Level 3 <code class="unnumbered">header</code></h3>
~~~~

**Comment by jgm** [comment]
The reason for this is that in pandoc's markdown, inline
code can take attributes (just like headers).  So in this
case the attribute is being parsed as part of the inline
code, rather than the header.  (Note `code
class="unnumbered"`.)

So it's not really a bug, more a rough edge.  We could make
it go away by not allowing a space between the closing
backtick for inline code and the attributes, but this might
break some existing documents.  If you want to propose this
change, you should raise it on pandoc-discuss.

Otherwise you could work around this by including an empty
attribute for the code span:

    # Header `code`{} {-}


+++ mavenaut [Jul 23 15 00:26 ]:

**Comment by mavenaut** [comment]
Thanks for the insight - work around is just fine.
