### ISSUE TITLE
Three extensions where docu in `README` and code in `Options.hs` do not match

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/pandoc#2332]
Directed by **[this thread in Google `pandoc-discuss` group](https://groups.google.com/forum/#!topic/pandoc-discuss/WZ8J3C1AAQc)**, I compared `src/Pandoc/Options.hs` with the `README` and the generated man page.

I found three items, where the documentation is not in line with `Options.hs`:

1. **`epub_html_exts`** :    
    Not mentioned in man page at all, but in `Options.hs` listed as *"Individually selectable syntax extension"*.    
    Commit was: https://github.com/jgm/pandoc/commit/002ae95d7a72313d979e9da4666cf61ebd009154 (July 30, 2014)

2. **`lists_without_preceeding_blanklines`** :     
    Not listed in man page section which summarizes *"Markdown variants"*, but in `Options.hs` listed amongst *"githubMarkdownExtensions"*.

3. **`shortcut_reference_links`** :    
    Not listed in man page section which summarizes *"Markdown variants"*, but in `Options.hs` listed amongst *"strictExtensions"*.

**Comment by jgm** [comment]
`shortcut_reference_links` is indeed in the README.
It's not listed under variants because it's part of the "strict" subset that all variants include.
`lists_without_preceding_blanklines` is in the README, under `Non-pandoc extensions`.
So the only one really missing from README is `epub_html_exts`.
(That's because it's not a Markdown extension at all, but only affects HTML.)
