### ISSUE TITLE
--reference-docx and --reference-odt doesn't work

### ISSUE THREAD

**Issue by Hi-Angel** [jgm/pandoc#2341]
I converted a LaTeX file with pandoc to an odt, next configured a style for the plain text, next saved style, next saved the file in both odt and docx formats for the future reference.

A LaTeX test example is

	\documentclass[a4paper]{article}

	\begin{document}

	\section{First Section}
	\subsection{a subsection}

	 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec diam sapien, egestas nec nisl ac, venenatis aliquet erat. Aenean quis suscipit nisi. Donec convallis fringilla facilisis. Aenean porttitor est in arcu condimentum tempus. Nullam a mauris eu elit condimentum mollis ut sed ante. Etiam consequat non quam vel aliquam. Nulla faucibus, odio id dictum maximus, neque quam malesuada ante, a gravida neque enim ut nulla.

	\end{document}

After that I tried to convert the same LaTeX example to both of odt and docx with reference to the previously saved files to use their styles. Upon converted, the text never uses the style of a referred document.

Convertation commands were:

	$ pandoc -f latex -t docx -o output.docx --reference-docx="reference.docx" test.tex
	$ pandoc -f latex -t odt -o output.odt --reference-odt="reference.odt" test.tex

*Pandoc version is 1.15.0.6*

**Comment by Hi-Angel** [comment]
I found what's wrong: paragraph in the file with styles declared like `text:style-name="DiplomParagraph"`, but paragraph in the pandoc output file is `<text:p text:style-name="First_20_paragraph">`. So it just didn't copied the paragraph style.

**Comment by Hi-Angel** [comment]
I think we need a clearer explanation for the both options, because it causes a misunderstanding. I experimented whole the day for which I also found alike option in LibreOffice, and that it doesn't work *(at least the way I thought it should)* too.

I asked [the question about the LibreOffice part](http://ask.libreoffice.org/en/question/54048/style-from-a-file-doesnt-work/?answer=54059#post-id-54059), and in the end realized that the only thing that does the option in Office, and, seems, in the pandoc — is adding styles that existed in the reference file to the new file. But it *doesn't automatizes* their application, i.e. it doesn't do anything beyond that.

**Comment by KurtPfeifle** [comment]
I must admit that I have a slight advantage in regard to this topic. Because before I first experimented with it, I read all of the (then) two Pandoc man pages, **`man pandoc`** and **`man pandoc_markdown`**. This gave me a pretty clear idea about how it is supposed to work.

The only glitch I suffered was that for some period my local man pages were behind what the current **[Pandoc README](http://pandoc.org/README.html)** explains.

Therefore, whenever I have to look up something which may have changed recently (Pandoc is developing very fast, with frequent releases and updates), I turn to the online documentation, because it is pretty reliably kept in sync with the code.

If you look at the section describing the **[options affecting specific writers](http://pandoc.org/README.html#options-affecting-specific-writers)**, you will see which styles (and their respective names!) are supported.

* For **`--reference-docx`** it says:

    > *"The following styles are used by pandoc: [paragraph] Normal, Compact, Title, Subtitle, Authors, Date, Abstract, Heading 1, Heading 2, Heading 3, Heading 4, Heading 5, Block Text, Definition Term, Definition, Bibliography, Body Text, Table Caption, Image Caption, Figure, FigureWithCaption; [character] Default Paragraph Font, Body Text Char, Verbatim Char, Footnote Reference, Hyperlink."*

    It doesn't mention that it also snatches the page sizes, page margins, page backgrounds, page footers and page headers from the reference DOCX. But it does, I've used it in the past...

* Hmmm.... I see now, the styles are only enumerated for DOCX, not for ODT (**`--reference-odt`**).

In any case: I created my own completely ugly, but crazy-colorized test document, for which I modified every single style which was available in the user interfaces of LibreOffice and MS Word and applied a differently colored font with different size etc.

Then I Pandoc-created the respective ODT and DOCX with `--reference-{odt,docx}=...` and checked which styles successfully got applied and which didn't....

**Comment by Hi-Angel** [comment]
@KurtPfeifle sorry, but whole readme is really large, careful reading in an ideal situation would take a few hours. So what I did — is read the relevant sections, i.e. the ones that explains how both options are supposed to work. And it happened so that I was needed a bit different thing of the one which actually does the options, while the explanation I read was just the intersection of the two ideas — the real one, and the one I thought.

**Comment by Hi-Angel** [comment]
@KurtPfeifle I am just again looked at both the `--reference-*` sections, let me tell what it looks like for me being supposed that I am doesn't yet know what it really does.

So, the first section I looking for is the `--reference-odt`, because it is a format with a stable specification, and hence as I think would be the most supported of two. I see the explanation that it uses the file as a style reference, and the text being ignored «Aha, so it looks for style of every particular element, like section, subsection, paragraph, and adds the styles to the document to be produced». I see an advice to use for style reference a file initially produced by pandoc, which is understandable, that is all.

Next I look at the  `--reference-docx` section, see that the first part of a text is a copy of the `--reference-odt` section. Next I see the addition about the supported styles. Remember the thought from the previous paragraph about a better support for odt? So, this thought together with the fact that I doesn't see alike list in the odt-section, produces a logical thought that just `docx` support is limited, and there's a list of what *is* actually supported.

That is it.

**Comment by KurtPfeifle** [comment]
> *"[...] the first section I looking for is the `--reference-odt`, because it is a format with a stable specification, and hence as I think would be the most supported of two."*

This assumption is not necessarily matched by reality.

My own feeling and observations in various tests brought me in fact to the conclusion that the support for DOCX writing was better than ODT, at least for a period of time. And this was mainly due to the fact that the *developer* who contributed DOCX support to Pandoc (reading AND writing DOCX) indeed found time and motivation and had the knowledge to implement it (regardless of what the perceived stability of the spec was).

So for quite a long time, ODT (despite of its more FOSS-friendly specification) did not even have a *reader* (only a *writer*): the ODT reader landed only very recently (a bit more than a week ago!) in the Pandoc's source code repository and will hopefully be included in the next release.
