### ISSUE TITLE
More than one URL query value in inline HTML link parsed incorrectly

### ISSUE THREAD

**Issue by ryangray** [jgm/pandoc#2357]
This inline HTML:
 ```html
<a href="http://foo.com?bar=1&bam=0">Test</a>
```
produces:
```html
<p>&lt;a href=&quot;http://foo.com?bar=1&amp;bam=0&quot;&gt;Test</a></p>
```
If you remove the second query parameter, it is fine, so:
```html
<a href="http://foo.com?bar=1">Test</a>
```
produces:
```html
<p><a href="http://foo.com?bar=1">Test</a></p>
```
as expected.

This bug is not present in 1.15 but is there in 1.15.0.5 through current (1.15.0.6). I haven't tested 1.15.0.1 through 1.15.0.4 since they don't have binary releases, but those look like they shouldn't affect this. So, the suspect change to me is either issue #2277 or #2280. I've also only tested this on Win 7 64-bit so far.

**Comment by jgm** [comment]
First observation: it's not valid HTML:  the `&` needs to be escaped.  Pandoc's behavior is still unexpected, though.

<img width="1181" alt="screen shot 2015-08-10 at 3 38 17 pm" src="https://cloud.githubusercontent.com/assets/3044/9186007/e1daddce-3f75-11e5-829a-c889043600e9.png">

**Comment by jgm** [comment]
I think you're right that the fix to #2277 introduced this.

That change caused the raw HTML tag recognizer to fail if TagSoup (the underlying HTML lexer we use) generates a warning.  The intent is to rule out parsing things like `<www.boe.es/buscar/act.php?id=BOE-A-1996-8930#a66>` as HTML tags.  Since your input contains some invalid HTML (unescaped `&`), it generates the warning and the new behavior causes the whole thing not to be treated as a tag.

I'm not sure any change is called for, actually.  The change was well motivated, and it's a bit tough to see how to modify it to avoid the behavior noted in this issue.  Plus, GIGO.

**Comment by jgm** [comment]
The relevant  commit is 99fe8594d94573b8ba8ec1d1e47b57444de4e4cb

**Comment by ryangray** [comment]
Ah, sorry, I missed that; must have had my contexts mixed up. I just checked up on that and now also realize I have to be careful to escape it as `&amp;` to work as a parameter separator rather than `%26`.

**Comment by ryangray** [comment]
Closing.
