### ISSUE TITLE
Numbered example lists in odt output

### ISSUE THREAD

**Issue by AugustH** [jgm/pandoc#2421]
Numbered example lists look very different in Latex, docx and odt.

Example: create a file with 100 lines like `(@) this is the text` and convert it to different formats

 `pandoc num.md -o num.pdf`   -- looks fine

`pandoc num.md -o num.docx` -- looks fine, numbers are left justified and the text is aligned

`pandoc num.md -o num.odt` -- looks bad for numbers above ten (no space between number and text), and the alignment is lost when the number reaches 100.  And I found no way to change this via the template ;-((

**Comment by jgm** [comment]
What program are you using to view the ODT?
It looks fine in, e.g., OSX's Preview.

**Comment by AugustH** [comment]
i use libreoffice 5 and 4 -- problem is independent of libreoffice version and pandoc 1.12 or 1.15

**Comment by jgm** [comment]
I think the issue is that the style sets minimum label width to 1/4 inch.  Probably in your case, with numbers over 100, the label is greater than 1/4 inch (or close that 1/4 inch).
``` xml
    <text:list-style style:name="L1">
      <text:list-level-style-number text:level="1" text:style-name="Numbering_20_Symbols" style:num-format="1" text:start-value="1" style:num-prefix="(" style:num-suffix=")">
        <style:list-level-properties text:space-before="0.25in" text:min-label-width="0.25in" />
      </text:list-level-style-number>
    </text:list-style>
```
We could increase the minimum label width in the default style.  Or, maybe there's another option that would ensure a certain amount of space after the label?
