### ISSUE TITLE
Line missing in odt output

### ISSUE THREAD

**Issue by AugustH** [jgm/pandoc#2434]
The following works with pdf/latex and docx output -- just the odt is missing one line. But just in the case of (@) and a)

pandoc doc.md -o doc.odt

```
# header 1

(@)  item

    some text

    * sub item 1
    * sub item 2

    more text

# header 2

(@)  text

    some text

    a) sub item 1
    b) sub item 2

    more text -- this line is missing in the odt output

#header 3

*  text

    some text

    a) sub item 1
    b) sub item 2

    more text

# header 4
```

**Comment by jgm** [comment]
Confirmed with more minimal sample:
```

(@)  text

    some text

    a) sub item 1
    b) sub item 2

    more text -- this line is missing in the odt output
```
Moreover, in the following we get a two-item list instead of a one-item list:
```
a) item 1

    more text
```
So there are definitely some issues here in the OpenDocument writer.  (Use `-t opendocument` to get the opendocument xml by itself -- that is where the problem lies.)  Unfortunately I didn't write the OpenDocument writer, and I find the code mysterious in places.  Maybe someone who uses ODT would like to attack this bug?

**Comment by jgm** [comment]
I believe this is related (from [pandoc-discuss](https://groups.google.com/d/msgid/pandoc-discuss/fb9cec2f-4c77-42aa-be27-b69c00eb50b9%40googlegroups.com)):
```
% pandoc -t opendocument
1. a
2. b
*  c
^D
<text:list text:style-name="L1">
  <text:list-item>
    <text:p text:style-name="P1">a</text:p>
  </text:list-item>
  <text:list-item>
    <text:p text:style-name="P1">b</text:p>
  </text:list-item>
</text:list>
<text:list text:style-name="L2">
  <text:list-item>
    <text:p text:style-name="P2">c</text:p>
  </text:list-item>
</text:list>
```

**Comment by jgm** [comment]
This problem seems to lie with ordered lists; if you reverse the bullets and numbers in the above example, you don't get a dropped item.
