### ISSUE TITLE
A markdown_in_tex_blocks extension

### ISSUE THREAD

**Issue by yihui** [jgm/pandoc#2453]
This is a feature request to add a Markdown extension `markdown_in_tex_blocks` like `markdown_in_html_blocks` according to the discussion in the mailing list: https://groups.google.com/forum/#!msg/pandoc-discuss/ggcrRN-ja-s/lNeILZdlBwAJ Thanks!

**Comment by andreatta** [comment]
+1  
That is a feature I really would like to see.
I am trying to put two separate tables next to each other on the same line.  

\begin(minipage}[b]{8mm}
#table 1
\end{minipage}
\begin(minipage}[b]{8mm}
#table 2
\end{minipage}

**Comment by jakkubu** [comment]
Workaround for this issue was proposed [here](https://groups.google.com/d/msg/pandoc-discuss/ggcrRN-ja-s/nFyiQ3cXCAAJ)

You can also add it in YAML header, on top of markdown file:

     ---
     header-includes:
         - \newcommand{\hideFromPandoc}[1]{#1}
             \hideFromPandoc{
                 \let\Begin\begin
                 \let\End\end
             }
     ---

and use `\Begin{whatever}` and `\End{whatever}` instead `\begin{whatever}` and `\end{whatever}`

So @andreatta  tables would look like this:

    \Begin(minipage}[b]{8mm}
    #table 1
    \End{minipage}
    \Begin(minipage}[b]{8mm}
    #table 2
    \End{minipage}

**Comment by yihui** [comment]
@jakkubu Sounds like an interesting idea. Thanks!

**Comment by memeplex** [comment]
Why not officialize the Begin/End workaround by including it as a default header for tex and documenting it as a "parsed environment"?

**Comment by yihui** [comment]
That would be great, but it is not important to me now. I have added `\let\Begin\begin` in the preamble automatically in my use cases, and got some pretty environments in both HTML and PDF output, e.g. https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html

**Comment by memeplex** [comment]
Thanks for the link @yihui, it looks really nice.

Btw, I've suggested adding a fake tex command that instructs pandoc to parse its contents as markdown https://github.com/jgm/pandoc/issues/3145, thus allowing reentering the parser in a more official and clean fashion.

**Comment by yihui** [comment]
@memeplex I definitely agree with you. It is just that I could wait any longer. My implementation details are totally hidden from users, so if some day what you envisioned becomes true, I can easily switch to the official approach without changing my top-level API.

**Comment by ickc** [comment]
I read your <https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html> and sees some amsthm def. Have you tried my pandoc-amsthm mentioned in #1608?

And just to cross-reference what I mentioned in #3368:

>I think the much better and stable way to do is via filter. There's a few mentioned in [Pandoc Filters · jgm/pandoc Wiki](https://github.com/jgm/pandoc/wiki/Pandoc-Filters), e.g.
>
>- [pandocfilters/latexdivs.py at master · jgm/pandocfilters](https://github.com/jgm/pandocfilters/blob/master/examples/latexdivs.py)
>- [Pandoc filter to insert arbitrary raw output markup as Code/CodeBlocks with an attribute raw=<outputformat>.](https://gist.github.com/bpj/e6e53cbe679d3ec77e25)

**Comment by ickc** [comment]
Some comments on the hacks mentioned in this thread:

The way to circumvent the pandoc's parsing of LaTeX environment is very "MultiMarkdown"-like. What I mean is it is very similar to the idea of MultiMarkdown's toggling of raw LaTeX commands. In the past (when I was from MultiMarkdown and not using pandoc yet), I have some success writing documents this way to target dual output (LaTeX and HTML). But ultimately I abandoned that approach because the source looks very ugly and hacky and difficult to maintain. (For example, a lot of text expansion might be needed to deal with the ugly syntaxes and glues and hacks.)

The forte of pandoc not only lies in multiple *input* and output formats, but also about the filter system (allowed by the internal AST design). It takes some learning curve at the beginning, but ultimately really worth it. If some are new to filters, I suggest `@sergiocorreia`'s [panflute](http://scorreia.com/software/panflute/guide.html). It has a very mild learning curve and things can get done very quickly. Not to mention the ease in maintaining the code. i.e. clean source in markdown and python, clean output in any formats. Win-win.

**Comment by markmartirosian** [comment]
The extension [raw_attribute](https://pandoc.org/MANUAL.html#extension-raw_attribute) solves this. (ignore the `>`)
```markdown
> ```{=latex}
> \begin{center}
> ```
> Remember to check **Appendix A** for additional resources references and detailed explanations.
> ```{=latex}
> \end{center}
> ```
```

becomes
```latex
\begin{note}
Remember to check \textbf{Appendix A} for additional resources references and detailed explanations.
\end{note}

**Comment by jgm** [comment]
Yes, I think using raw attributes is the solution here.
