### ISSUE TITLE
pipe_tables overflow the page width for PDF output

### ISSUE THREAD

**Issue by ndaniel** [jgm/pandoc#2471]
`pipe_tables` overflow the page width for PDF output!

`multiline_tables` do not overflow the page width in PDF output! This **is/should-be** the expected behavior for every table types (e.g. pipe_tables, multiline_tables, grid_tables, simple_tables)!

Also, the default assumption for `pipe_tables` when fitting a table into page's width is that all its column have the same width.

**Comment by adunning** [comment]
Would you mind providing a minimal example showing the command you used and your input?

**Comment by jgm** [comment]
+++ Daniel Nicorici [Oct 22 15 01:49 ]:
>   pipe_tables overflow the page width for PDF output!
>
>   multiline_tables do not overflow the page width in PDF output! This is
>   (should be) the expected behavior for every table types (e.g.
>   pipe_tables, multiline_tables, grid_tables, simple_tables)!
>
>   Also, the default assumption for pipe_tables when fitting a table into
>   page's width is that all its column have the same width.

But in LaTeX (for PDF) we need either to set the column
width or not.  If we don't set it (as we currently don't for
simple pipe tables), then there's the risk of overflow if
you have very long lines.  If we do set it, though, to
(textwidth / number of columns), we'll get very bad results
for most normal pipe tables, since usually they don't take
up the whole textwidth, and usually the columns have
different natural widths.

With these two options, the least bad is not to set the
widths with pipe tables, since we have no basis for doing so
in an intelligent way.

**Comment by ndaniel** [comment]
Here is an example of what I mean:

https://www.dropbox.com/s/e25yac2ixiegz2a/example.md?dl=0

Please, keep in mind that this is an example and it is not a case which I have. Therefore fixing this example does not solve the bug which I submitted!

In order to fit a table one may change the paper type from A4 to A3 from example but still there is need that the table auto-fits within the page.

**Comment by jgm** [comment]
I think this is going to have to be a "don't fix" for the reason
I gave in my comment above.  With LaTeX tables you either
specify the column width explicitly, or it won't wrap.  If we specify
the width explicitly, the only rational choice is the textwidth divided
by the number of columns.  But this will lead to bad results on
must pipe tables, since it will make all pipe tables, even tiny ones,
render as wide as the page.  So it's better to keep things as they are.

Thinking of other possibilities:

(1) One might be to use a different LaTeX table package,
if there is one that has more HTML-like behavior (automatically
wrapping without explicit column width specifications).  I'm open
to considering this, but (a) I want to avoid depending on uncommon
packages, and (b) I want to allow tables longer than a page (which
longtable allows).

(2)  Another possibility would be for pandoc to estimate, based on table
cell contents, whether the table is likely to overflow textwidth, and set
explicit column widths if it thinks it will.  The problem is that this estimation
is going to be pretty unreliable, as pandoc lacks a lot of the information
that LaTeX would use in determining widths.

**Comment by ndaniel** [comment]
> I think this is going to have to be a "don't fix" for the reason
> I gave in my comment above. With LaTeX tables you either
> specify the column width explicitly, or it won't wrap. If we specify
> the width explicitly, the only rational choice is the textwidth divided
> by the number of columns. But this will lead to bad results on
> must pipe tables, since it will make all pipe tables, even tiny ones,
> render as wide as the page. So it's better to keep things as they are.

The idea is to have some kind of command line option for pandoc which would force the pipe tables (or other types of tables) to be treated like multiline tables (instead of user converting manually all its tables from pipes to multiline tables). Of course the conversion of pipe tables to multiline tables would be a lossy one (i.e. all columns have the same width and the table width will be the page width).  

> (1) One might be to use a different LaTeX table package,..

There is no need for this. See above!

> (2) Another possibility would be for pandoc to estimate, based on table
> cell contents, whether the table is likely to overflow textwidth, and set
> explicit column widths if it thinks it will. The problem is that this estimation
> is going to be pretty unreliable, as pandoc lacks a lot of the information
> that LaTeX would use in determining widths.

An idea here would be for pipe tables to use this line:

```
|:---|----|--------|------------|
```
in order to specify the columns widths for pipe tables (i.e. first column and second column have the same width, the third column is twice wider than first column, and fourth column is three times wider than first column).

**Comment by jgm** [comment]
+++ Daniel Nicorici [Oct 23 15 11:55 ]:
>     I think this is going to have to be a "don't fix" for the reason
>     I gave in my comment above. With LaTeX tables you either
>     specify the column width explicitly, or it won't wrap. If we specify
>     the width explicitly, the only rational choice is the textwidth
>     divided
>     by the number of columns. But this will lead to bad results on
>     must pipe tables, since it will make all pipe tables, even tiny
>     ones,
>     render as wide as the page. So it's better to keep things as they
>     are.
>
>   The idea is to have some kind of command line option for pandoc which
>   would force the pipe tables (or other types of tables) to be treated
>   like multiline tables (instead of user converting manually all its
>   tables from pipes to multiline tables). Of course the conversion of
>   pipe tables to multiline tables would be a lossy one (i.e. all columns
>   have the same width and the table width will be the page width).

Well, that works only if you have no "small" pipe tables in
your source.  For this would make all pipe tables take the
entire page width.  I think that usually this is going to be
quite a bad result.

>   An idea here would be for pipe tables to use this line:
>
> ```
> |:---|----|--------|------------|
> ```
>
>   in order to specify the columns widths for pipe tables (i.e. first
>   column and second column have the same width, the third column is twice
>   wider than first column, and fourth column is three times wider than
>   first column).

Interesting idea.  Indeed, this would also allow tables with
an overall width < the page width.  We could calculate
widths in much the same way as we do with multiline tables
currently.

**Comment by ndaniel** [comment]
Thanks! It works great in pandoc 1.15.1.1 (Compiled with texmath 0.8.4, highlighting-kate 0.6.)!

**Comment by ndaniel** [comment]
Thanks! It works great in pandoc 1.15.1.1 (Compiled with texmath 0.8.4, highlighting-kate 0.6.).

**Comment by tewarid** [comment]
Any reason why this does not work the same when converting gfm to pdf? i.e.
```
pandoc file.md -f gfm -o file.pdf
```
overflows page for tables with long lines.

**Comment by mb21** [comment]
@tewarid try the legacy `markdown_github`, see http://pandoc.org/MANUAL.html#markdown-variants

**Comment by tewarid** [comment]
@mb21 `markdown_github` works properly, thanks! pandoc throws the following warning though
```
[WARNING] Deprecated: markdown_github. Use gfm instead.
```
I'm hoping `gfm` gets fixed.

**Comment by k4rtik** [comment]
Is there a reason `gfm` still does not support wrapping of long rows? `markdown_github` works but I am unsure what I am losing as it is deprecated in favor of `gfm`.

cc: @jgm

**Comment by jgm** [comment]
I don't have any control over how GitHub parses and renders their tables; you'd have to talk to them.
Currently we're trying to match their behavior.

**Comment by k4rtik** [comment]
Thanks for taking a look, but it seems like `gfm` and `markdown_github` are read formats provided by pandoc. The functionality you added to wrap tables must be filtering over these format strings somewhere, no?

For my reference:
> gfm (GitHub-Flavored Markdown), or the deprecated and less accurate markdown_github; use markdown_github only if you need extensions not supported in gfm.

I see that https://github.com/jgm/pandoc/blob/16f0316fbaa4d667ba40772969ab8e28fea6a493/src/Text/Pandoc/Readers.hs#L126 and https://github.com/jgm/pandoc/blob/16f0316fbaa4d667ba40772969ab8e28fea6a493/src/Text/Pandoc/Readers.hs#L132
they seem to be using two different readers. So perhaps the fix is to enable wrapping for commonMark?

**Comment by k4rtik** [comment]
@jgm I see that your fix in https://github.com/jgm/pandoc/commit/eb8aee477db045a7449bc752975528263964b8ce only exists in the Markdown reader, not the CommonMark reader.

My Haskell is rusty, but if it's too much trouble for you, I can try and port the solution in a few days/weeks and send a PR.

**Comment by k4rtik** [comment]
> but I am unsure what I am losing as it is deprecated in favor of `gfm`.

Found a couple of features I lost after switching to the deprecated backend -- link highlighting and footnote support.

Before:

```
❯ pandoc spec.md --pdf-engine=xelatex -V mainfont="TeX Gyre Pagella" -V monofont="Fira Code" -V linkcolor:blue --toc --highlight-style tango -V geometry:margin=2.5cm -f gfm -o spec.pdf
```

<img width="712" alt="Screen Shot 2022-08-07 at 5 03 27 PM" src="https://user-images.githubusercontent.com/374340/183312694-609980bd-8add-4369-b40b-5c29b2ee93f3.png">

After:
```
❯ pandoc spec.md --pdf-engine=xelatex -V mainfont="TeX Gyre Pagella" -V monofont="Fira Code" -V linkcolor:blue --toc --highlight-style tango -V geometry:margin=2.5cm -f markdown_github -o spec.pdf
[WARNING] Deprecated: markdown_github. Use gfm instead.
```

<img width="874" alt="Screen Shot 2022-08-07 at 5 03 48 PM" src="https://user-images.githubusercontent.com/374340/183312705-3e783eb7-0b8a-485d-b9e3-e74b2b659f17.png">
