### ISSUE TITLE
Raw TeX not preserved in case of unbalanced dollar signs in LaTeX environments

### ISSUE THREAD

**Issue by yihui** [jgm/pandoc#2493]
A minimal Markdown example:

```tex
An _environment_:

\begin{foo}
a$b
\end{foo}
```

Run `pandoc -f markdown -t latex` and I get

```tex
An \emph{environment}:

\textbackslash{}begin\{foo\} a\$b \textbackslash{}end\{foo\}
```

Is this by design?

```
$ pandoc --version
pandoc 1.15.1
Compiled with texmath 0.8.4, highlighting-kate 0.6.
```

**Comment by jgm** [comment]
The Markdown reader uses a function from the LaTeX reader
to handle raw LaTeX.  If you try the LaTeX reader on
this snippet, you'll get a parse error (because it expects
the closing `$`).  Since this parser fails, the Markdown
reader just interprets this as regular text (and hence
the `$` gets escaped).

Now, I understand that in principle one can redefine the
behavior of `$` inside a LaTeX environment.  But handling
every such case seamlessly would require reimplementing
TeX inside pandoc.  We handle known verbatim environments,
but that's about it.

+++ Yihui Xie [Oct 30 15 08:21 ]:

**Comment by yihui** [comment]
Fair enough. Thanks for the explanation!
