### ISSUE TITLE
Missing newline at EOF breaks MD -> PDF conversion

### ISSUE THREAD

**Issue by Holzhaus** [jgm/pandoc#2494]
I'm using pandoc 1.15.1.1 (Compiled with texmath 0.8.4, highlighting-kate 0.6.).

```
$ pandoc -s -o myfile.pdf myfile.md variables.yml
! LaTeX Error: Can be used only in preamble.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.166 \usepackage

pandoc: Error producing PDF from TeX source

$ echo "" >> myfile.md
$ pandoc -s -o myfile.pdf myfile.md variables.yml
$ 
```

**Comment by jgm** [comment]
This is not a bug.

You're using two source files (the second is a YAML
metadata block).  When you use multiple source files,
pandoc concatenates them, inserting a single newline
character between each pair.  So, if myfile.md doesn't
end with a newline, the result of concatenating will
be something like:

```
hello world
...
title: My title
---
```

And this doesn't get parsed as a YAML metdata block, since
you need a blank line before a YAML metadata block.

My guess is that your YAML metadata block contains some
include-in-header stuff that can only be used in the
preamble, and the error is raised because this is getting
put in the body of the document.

So, two easy solutions:  either add a newline to myfile.md
or add a blank line at the beginning of variables.yml.

You might ask:  why not add two newlines when concatenating
source files, to avoid this problem?  Answer:  because
sometimes one doesn't WANT a blank line between the
concatenated files, e.g. when one wants to include
a source file in a fenced code block.  It's good to
have this flexibility, and usually when there's not a
newline at the end of a text file, it's done intentionally.


+++ Jan Holthuis [Nov 03 15 07:00 ]:

**Comment by Holzhaus** [comment]
OK, that makes sense. Thanks for your detailed answer.
