### ISSUE TITLE
Feature Request: Please support encodings other than utf-8

### ISSUE THREAD

**Issue by daixtrose** [jgm/pandoc#2499]
For structured LaTeX documents the iconv trick is not really feasible due to the muti-file structure. I'd appreciate support for other file encodings ...

**Comment by mb21** [comment]
Personally, I'm for [utf8everywhere.org](http://utf8everywhere.org/)... any good reason your LaTeX file needs to be in a legacy encoding?

**Comment by daixtrose** [comment]
Well - TeXniccenter fails to read utf-8 files and iconv shows me the finger on umlauts. In summary: I am stuck.

**Comment by mb21** [comment]
www.texniccenter.org lists "full UTF-8 support"..?

**Comment by daixtrose** [comment]
Yes, I know. And maybe I am simply not intelligent enough to figure out where to find the menu entry that fixes this. Note that I am using a Windows platform ...

**Comment by daixtrose** [comment]
AFAICS most of my programs seem to use ISO-8859. Is it difficult to support this?

**Comment by daixtrose** [comment]
AFAICS most of my programs seem to use ISO-8859. Is it difficult to support this?

**Comment by qwindelzorf** [comment]
Adding support for all the old codepages is not necessarily a simple matter, and shouldn't be necessary given Pandoc's support of UTF-8.  

---

I took a look at your underlying complaints about UTF-8 related workflows with Pandoc/TeXnicCenter (not sure how you're using them together), and was unable to produce any encoding related failures. Since you are using TeXnicCenter, I assume you are authoring in TeX, and using Pandoc to generate various output formats. Using TeXnicCenter on a Windows 8.1 system, I created this minimal test TeX document:

~~~
\documentclass{article}

\usepackage{fontspec}
\setmainfont{Arial}

\begin{document}
¢ £ ¤ ¥ ¦ § ¨ © ª « ¬ ® ¯ ° ± ² ³ ´ µ ¶  · ¸ ¹ º » ¼ ½ ¾ ¿ À Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ð Ñ Ò Ó Ô Õ Ö × Ø Ù Ú Û Ü Ý Þ ß à á â ã ä å æ ç è é ê ë ì í î ï ð ñ ò ó ô õ ö ÷ ø ù ú û ü ý þ ÿ 
\end{document}
~~~

Interestingly, on my system, TeXnicCenter defaulted to UTF-8 when saving the source file. I then used Pandoc to convert it to several output formats:

~~~
pandoc -i utf8_test.tex -s -o utf8_test.docx
pandoc -i utf8_test.tex -s -o utf8_test.html
pandoc -i utf8_test.tex -s -o utf8_test.pdf
~~~

Every one of these output formats rendered correctly. 

I suspect that your problem is LaTeX related, and not particularly tied to either TeXnicCenter or Pandoc. Getting any extended character set to render correctly when going through LaTeX can be rough. In this case, Pandoc appears to be detecting the `\usepackage{fontspec}` and switching from pdfLaTeX to XeLaTeX behind the scenes. Because XeLaTeX supports system fonts, its up to you to choose a font that supports the characters you are trying to render: here I chose Arial, since its available by default on Windows systems and has substantial UTF-8 support. My system TeX package (MikTex) provides the XeLaTeX engine, and so everything works cleanly. More details on TeX engine selection with Pandoc are availalbe [here](http://pandoc.org/README.html#creating-a-pdf).

I was also able to directly render this sample TeX document form inside TeXnicCenter by selecting "XeLaTeX => PDF" in the "Output Profile" dropdown and then clicking the "Build and view current file" button in the toolbar.

**Comment by daixtrose** [comment]
Many thanks for your in-depth analysis which led me to fix it w/o change in pandoc. I manually changed all TeX file encodings to UTF-8 **and** used the correct arguments in the latex file: `\usepackage[utf8]{inputenc}`

Can be closed.
