### ISSUE TITLE
Carriage returns created at end of cells in tables in ICML files

### ISSUE THREAD

**Issue by adamjrice** [jgm/pandoc#2501]
When converting to ICML from any flavor of markdown table, an unnecessary carriage return is appended to the contents of each cell

**Comment by mb21** [comment]
That's due to the ICML writer inserting a [linebreak after every paragraph](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/ICML.hs#L474), instead of interspersing them in-between. I should be able to fix this eventually, but takes quite a few changes and I don't have time this week...
