### ISSUE TITLE
Pandoc Hangs Converting CommonMark spec with Github Reader

### ISSUE THREAD

**Issue by mike-ward** [jgm/pandoc#2510]
Using the CommonMark spec, the following causes pandoc to hang.

`pandoc -f markdown_github -t html spec.md >spec.html`

spec.md was generated from the CommonMark spec using the make file in the CommonMark project.

**Comment by jgm** [comment]
`markdown_github` doesn't parse Markdown inside HTML block
tags (like `<div>`).  So if you do `-f markdown_github`,
the code examples are all parsed as non-verbatim sections.

That's not what you want, and it explains why pandoc gets
messed up, since many of these code examples contain things
like unclosed HTML tags.

The `spec.md` is designed to be processed as CommonMark
or pandoc markdown.

Of course, it would be good to figure out if there's a way
to avert the hanging.

+++ Mike Ward [Nov 09 15 14:29 ]:
