### ISSUE TITLE
No dokuwiki reader.

### ISSUE THREAD

**Issue by kenguest** [jgm/pandoc#2521]
There is a dokuwiki writer, which is excellent, but no reader/parser for inputting docuwiki syntax.
It would be useful if there was - are there plans for one?

**Comment by tarleb** [comment]
AFAIK, there is nobody actively working on a writer at this moment.  See also #1792 and the discussions in #386.

**Comment by brozkeff** [comment]
I reused Thorsten Staerk's PHP script to convert dokuwiki to mediawiki as an intermediate step in order to then convert it via pandoc to html. By downloading whole folder of dokuwiki TXTs of individual pages and running the script I instantly get a new bunch of very simple HTML files perfect for inserting to our eshop.

See my script https://gist.github.com/brozkeff/5196968cc159317573c00832ff0ff6eb
forked from https://gist.github.com/hugorodgerbrown/5317616
that in addition to pandoc, uses https://github.com/tstaerk/mediasyntax/blob/master/tools/dokuwiki2mediawiki.php as an intermediate step. Works fine for me.

**Comment by mb21** [comment]
duplicate of #1792
