### ISSUE TITLE
Generate references with list not with div

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#2550]
I see that if you generate html5 doc with references, pandoc generated `<div class="references">` and each bibitem has its own `div` tag. Is it possible to replace that with `ol` and `li` tags instead.

Thanks  in advance,

**Comment by jgm** [comment]
You could use a filter to do this.

+++ Xavier [Nov 21 15 10:42 ]:

**Comment by somenxavier** [comment]
How? I use pandoc-citeproc.

Anyway, mark it as wish, beucause list is more appropiate semantically than div,

**Comment by jgm** [comment]
+++ Xavier [Nov 21 15 11:14 ]:
>   How? I use pandoc-citeproc.
>
>   Anyway, mark it as wish, beucause list is more appropiate semantically
>   than div,

It's not going to become the default, because lists wouldn't
give appropriate output without special styling (which would
be complex to achieve in all the formats we support).

Doing this with a filter wouldn't be hard.  There are people
on pandoc-discuss who could help, but you might first read
the scripting tutorial on the website.

**Comment by jgm** [comment]
Sample filter (untested but should be close):

import Text.Pandoc.JSON

main = toJSONFilter go
  where go (Div ("refs",_,_) items) = BulletList (map (:[]) items)
        go x = x

**Comment by somenxavier** [comment]
Thanks for answering. I will try the filter, but right now it's far away from my level ;-)
Please, reconsider using lists instead of divs. It's the proper way of doing it. And yes, it depends on CSS  but I think it just depends on [start="N"](http://www.w3schools.com/tags/att_ol_start.asp)?
