### ISSUE TITLE
Request: improved documentation of YAML options

### ISSUE THREAD

**Issue by paultopia** [jgm/pandoc#2600]
Right now, it's not terribly clear from the documentation what needs to be set from the command line, and what can be set with YAML.  

I can't be the only one who routinely turns to the R Markdown documentation to figure out what options are available for the Pandoc YAML, just because that documentation is significantly clearer and more comprehensive, and, since R Markdown is based on Pandoc, tends to be close enough that if it's available there, it's probably available here.  

Unfortunately, that sometimes leads to nasty experiences.  For example, I just spent a solid half hour trying to figure out why I couldn't change the fonts for Pandoc PDF output in YAML.  It turns out that the reason is that you can set the *font* in YAML, but you can't change the engine to xelatex in YAML, that has to be done on command line. (See issue https://github.com/jgm/pandoc/issues/1780 .)  

It took so long to figure that out because, unsurprisingly, I was working from the R Markdown docs, and R markdown does support setting the latex engine in YAML (see: http://rmarkdown.rstudio.com/pdf_document_format.html ). (Incidentally, would it be possible to adapt whatever solution the R Markdown folks have found to including the engine in the YAML?)

This sort of thing could be greatly ameliorated if there was something like a canonical list of the options that can be set in YAML, in one readable location.  I'd contribute that myself, except, well, I don't know what those options are.

**Comment by jgm** [comment]
+++ Paul Gowder [Dec 23 15 11:56 ]:

>   This sort of thing could be greatly ameliorated if there was something
>   like a canonical list of the options that can be set in YAML, in one
>   readable location. I'd contribute that myself, except, well, I don't
>   know what those options are.

Andrew Dunning and others have been working on making the
"Variables" section of the pandoc README/User's Guide more
comprehensive.  Anyway, that is where to look first.

**Comment by jgm** [comment]
Look here: http://pandoc.org/README.html#templates

Some basics to keep in mind:

These are template variables.  If you look in the default
templates, you'll see where they are used.

Template variables can be set using the `-V` option on
the command line.  But if they're not set that way,
they get filled automatically be metadata fields.

Different variables are used in different templates. And in
some cases the same variable is used, but it expects a
different kind of value.  That is because these formats
are very different.  We have tried to standardize a few
things -- most recently `lang` -- so that they work the
same way across formats, but that requires nontrivial
conversion below decks.

Because the variables depend on the output format,
we have different sections "Variables for LaTeX",
"Variables for ConTeXt", etc.

Eventually it would be nice to standardize all of this
with behind-the-scenes conversions.  But we're not there
yet, and it would not be easy to standardize (for example)
font selection.

**Comment by paultopia** [comment]
Thanks!  This clarifies a lot.  Pandoc is an amazing tool, by the way.  I can't even tell you how much this has changed my workflow already.

It occurs to me that this may be a job for third-party tools.  I'm feeling the urge to try my hand at a wrapper script that parses the YAML block as well as commandline options and then converts them to expected input, e.g., passes engine information in YAML block to pandoc on the commandline, changes variable values depending on output format, etc. Might give that a crack in a few weeks.

**Comment by jgm** [comment]
OK!  Third-party tools are a good idea.
I'm going to close this, since it's pretty open-ended.  If you have specific requests for improved documentation about some variable or metadata field, please submit them.
