### ISSUE TITLE
Self-contained with custom writer?

### ISSUE THREAD

**Issue by noamross** [jgm/pandoc#2603]
I have a custom lua writer that produces HTML but renders footnotes differently than the default (putting them in `<span>` tags to be rendered as tufte-style sidenotes via the CSS).  When I use this custom writer, `--self-contained` does not work, presumably because, according to the README

>This option works only with HTML output formats, including html, html5, html+lhs, html5+lhs, s5, slidy, slideous, dzslides, and revealjs.

Can there be a way to allow self-contained for custom HTML writers?

**Comment by jgm** [comment]
This isn't possible, and I wouldn't want to make
--self-contained work with custom writers in general,
since they aren't all HTML writers.

Your best bet would be to use a filter instead of a custom
writer.  The filter could handle the alternative footnote
rendering, and you'd still be able to use --self-contained.
You also would get the benefits of further improvements
to the HTML writer.

+++ Noam Ross [Dec 25 15 18:26 ]:
