### ISSUE TITLE
Converting pipe tables into LaTeX

### ISSUE THREAD

**Issue by vancleve** [jgm/pandoc#2626]
I have some pipe tables with some long rows and when they get converted to LaTeX, the columns widths add up to more than one, resulting in the table extending into and beyond the margin of the page.

I can reproduce the behavior for even a small table with the `--columns` argument set small enough. For example, if `test.md` is:
```
| test  | header | row    |
|-------+--------+--------|
| first | row    | elemnt |
```
Then running
```
pandoc test.md --columns=12 -t latex
```
yields
```
\begin{longtable}[c]{@{}lll@{}}
\toprule
\begin{minipage}[b]{0.61\columnwidth}\raggedright\strut
test
\strut\end{minipage}
&
\begin{minipage}[b]{0.68\columnwidth}\raggedright\strut
header
\strut\end{minipage}
&
\begin{minipage}[b]{0.68\columnwidth}\raggedright\strut
row
\strut\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.61\columnwidth}\raggedright\strut
first
\strut\end{minipage}
&
\begin{minipage}[t]{0.68\columnwidth}\raggedright\strut
row
\strut\end{minipage}
&
\begin{minipage}[t]{0.68\columnwidth}\raggedright\strut
elemnt
\strut\end{minipage}\tabularnewline
\bottomrule
\end{longtable}
```
where the columns widths in a row sum to more than one `\columnwidth`. In fact, narowing the 
`--columns` make the problem worse:
```
pandoc test.md --columns=10 -t latex
```
produces
```
\begin{longtable}[c]{@{}lll@{}}
\toprule
\begin{minipage}[b]{0.73\columnwidth}\raggedright\strut
test
\strut\end{minipage}
&
\begin{minipage}[b]{0.82\columnwidth}\raggedright\strut
header
\strut\end{minipage}
&
\begin{minipage}[b]{0.82\columnwidth}\raggedright\strut
row
\strut\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.73\columnwidth}\raggedright\strut
first
\strut\end{minipage}
&
\begin{minipage}[t]{0.82\columnwidth}\raggedright\strut
row
\strut\end{minipage}
&
\begin{minipage}[t]{0.82\columnwidth}\raggedright\strut
elemnt
\strut\end{minipage}\tabularnewline
\bottomrule
\end{longtable}
```

**Comment by jgm** [comment]
The relative column widths are calculated by looking
at the widths of the separator lines, relative to
the total column width as set by `--columns`. (To
be precise, we take the number of dashes in the
separator line and add 1, then divide by the
value of `--columns`.)

So, if you set `--columns=12`, then a separator that is 6
characters wide will have a width of 50%.  If you have
three separators, each more than 6 characters wide, then
the relative  column widths will sum to more than 100%.

So, the solution is simply to scale your separator lines
appropriately.

A possible change in pandoc would be to renormalize column
widths after this calculation, so that they never exceed
100% total.  This is probably worth doing.

**Comment by vancleve** [comment]
Thanks @jgm! Tables look great after this change!
