### ISSUE TITLE
pandoc -f html -t markdown_github -s my_file.htm does not generate YAML

### ISSUE THREAD

**Issue by tedhudek** [jgm/pandoc#2672]
The -s switch causes HTML meta tags to be converted to YAML frontmatter in Markdown when you use -t markdown, but the YAML block is not created when you use -t markdown_github.  Is there a reason this option is not supported for GFM?

**Comment by jgm** [comment]
You can enable it:

    pandoc -t markdown_github+yaml_metadata_block

I don't recall why it isn't the default.  Probably because
(a) at the time I added it, gfm didn't allow YAML metadata,
or maybe because (b) gfm only allows YAML metadata in
certain contexts.  Also, note that pandoc uses a `...`
end delimiter for the YAML (in accord with the YAML spec),
and I'm not sure GitHub accepts this.  See #2668.

+++ Ted Hudek [Jan 22 16 12:35 ]:

**Comment by tedhudek** [comment]
You just made my day!  Thanks for the quick reply, John.  I'll propose an update to the Readme to add this info.
