### ISSUE TITLE
add attributes for autolinks

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#2678]
[With latest version](http://pandoc.org/try/?text=[http%3A%2F%2Fpandoc.org]%28pandoc.org%29{%23superlink}%0A%0A%3Chttp%3A%2F%2Fpandoc.org%3E{%23superlink}&from=markdown&to=html):

``` md
[http://pandoc.org](pandoc.org){#superlink}

<http://pandoc.org>{#superlink}
```

outputs the following HTML code:

``` html
<p><a href="pandoc.org" id="superlink">http://pandoc.org</a></p>
<p><a href="http://pandoc.org" class="uri">http://pandoc.org</a>{#superlink}</p>
```

I don’t know whether this is intended. But would it be possible to have attributes in autolinks?

**Comment by ousia** [comment]
It would be also important to add attributes for automatic internal links, such as

```markdown
# Introduction

# Chapter One

As outlined in the [Introduction]{.internal-automatic}...
```

Since this issue isn’t really independent from the one described in  the comment above, I’m reporting it here.

**Comment by jgm** [comment]
These internal links are just reference links, so the real
issue is that reference links don't currently take attributes.

**Comment by d-dorazio** [comment]
@jgm I probably have a [fix](https://github.com/d-dorazio/pandoc/commit/60712cfc0fee6c174289b22ff9c19767a00d3607) to add attributes for autolinks(I'm a Haskell newbie so it's possible it works by chance :sweat_smile:). However, I'm a bit unsure about the addition for automatic internal links, because that's the syntax for [native spans](https://github.com/jgm/pandoc/commit/e95047ed85872fbc44e261df74add4e4f9bef30d), isn't it?

**Comment by jgm** [comment]
@d-dorazio you're right about the conflict with native spans.

Personally I don't think we should allow reference links to have custom attributes (or, more properly, the attributes should be defined in the link references themselves).  In the case of automatic internal links, perhaps we should add a special attribute to them automatically, so they can be distinguished from other links?

I'm also unsure whether autolinks should have attributes, though I suppose the risk of conflict is low.

**Comment by d-dorazio** [comment]
@jgm I'm not sure I follow you on the risk of conflicts for autolinks, but I like the idea of supporting attributes in autolinks even for just a matter of consistency with links. If we don't want to support them then I _think_ we should update the `MANUAL.txt`, because I think it's not clear that `link_attributes` work for link only.

**Comment by jgm** [comment]
True.  One comment then on your patch:  I don't think we should skip spaces, since we don't allow spaces before the attributes in other links.

**Comment by ousia** [comment]
@jgm and @d-dorazio,

you’re right, the syntax I proposed for internal references was the actual syntax for native spans.

Would it be possible that pandoc adds a class (such as `internal-automatic` or something similar) for internal references?

**Comment by jgm** [comment]
Closing this since attributes for autolinks have been merged.

@ousia, your suggestion about internal references doesn't belong in this issue.  You can open a new one if you like.

**Comment by ousia** [comment]
@jgm, many thanks for granting attributes for autolinks.

I guess that the suggestion is covered in #2535.
