### ISSUE TITLE
Prevent interpretation of TeX formulas

### ISSUE THREAD

**Issue by baskerville** [jgm/pandoc#2679]
I've written a script to convert embedded TeX math in EPUBs to SVG images (via *dvisvgm*) and I've noticed that *pandoc* converts formulas to HTML whenever it can, e.g.:

If *test.md* contains:
```
$$\int_{-\infty}^\infty e^{-x^2} = \sqrt{\pi}$$

$$n! = \int_0^\infty x^n e^{-x} dx$$
```
then `pandoc -t html test.md` yields
```html
<p><br /><span class="math display">$$\int_{-\infty}^\infty e^{-x^2} = \sqrt{\pi}$$</span><br /></p>
<p><br /><span class="math display"><em>n</em>!=∫<sub>0</sub><sup>∞</sup><em>x</em><sup><em>n</em></sup><em>e</em><sup>−<em>x</em></sup><em>d</em><em>x</em></span><br /></p>
```
The first formula is left alone but the second formula is interpreted as HTML.

If there a way to prevent *pandoc* from trying to translate TeX formulas to HTML?

**Comment by jgm** [comment]
See the manual under "Math rendering in HTML."  The
conversion you mention is done in the writer.  There are
various options you can use that will preserve the TeX
sections, e.g. --mathjax.  You could  use one of those.

A cleaner solution might be to write a pandoc filter,
rather than using a script that operates on the output.
(A filter would operate directly on the abstract
representation of the document, and you could easily
have it just affect Math sections and replace them with
images.)

+++ Bastien Dejean [Jan 24 16 07:26 ]:

**Comment by baskerville** [comment]
Thanks.

My initial idea *was* to write a filter but my first attempt failed due to my inability to grasp the AST.

My [second attempt](https://github.com/baskerville/bin/blob/macosx/pandoc-filter-svgmath) succeeded.

Long live *pandoc*!
