### ISSUE TITLE
Enable colorlinks results in undefined color Maroon

### ISSUE THREAD

**Issue by tolot27** [jgm/pandoc#2680]
As soon as colorlinks variable is set, the following error occurs with Pandoc from version 1.15.2.1 till 1.16.0.2 if markdown is converted to PDF:

```
! Package xcolor Error: Undefined color `Maroon'.

See the xcolor package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.254 ...hyperlink{annotation}{Annotation Process}

pandoc: Error producing PDF from TeX source
```

Changing the latex template to passing package options to `xcolor` rather than `color`fixes the problem:
```
\PassOptionsToPackage{usenames,dvipsnames}{xcolor} % xcolor is loaded by hyperref
```

**Comment by jgm** [comment]
@adunning - you added this line originally.  Do agree with the proposed change?

**Comment by adunning** [comment]
That shouldn't in theory work, because `xcolor` isn't loaded by anything in the default template (`hyperref` loads `color`, not `xcolor`). Are you using a custom class, @tolot27?

**Comment by adunning** [comment]
I am not having any problems with the following:

```markdown
pandoc -V colorlinks -o test.pdf << EOT
# This is a test

So [This is a test].

[Test link](http://test.com).

EOT
```

**Comment by tolot27** [comment]
I cannot reproduce this error anymore and don't now why it has appeared.

**Comment by JelteF** [comment]
I had this same issue and the fix also worked. When upgrading from Ubuntu 15.04 to 15.10 it was fixed. I guess that 15.04 a `hyperref` package that uses `xcolor` instead of `color`.

**Comment by jmicrobe** [comment]
I'm having this same issue as well, and I'm wondering if it's because I want colored links and I'm also passing -H to use lstset, to set a style for code blocks. Here's my listings setup:

`% Contents of listings-setup.tex

\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault}
\usepackage{xcolor}

\lstset{
    basicstyle=\ttfamily,
    backgroundcolor=\color{black!10},
    showspaces=false,
    showstringspaces=false,
    showtabs=false,
    tabsize=2,
    captionpos=b,
    breaklines=true,
    breakatwhitespace=true,
    breakautoindent=true,
    linewidth=\textwidth
}` 

and the command I use:

`pandoc README.md ANALYSIS.md --listings -H listings-setup.tex -V colorlinks -o concat.pdf`

The undefined color I get in this case is 'Blue'. If I remove `-V colorlinks` the pdf is made, but links aren't colored.
