### ISSUE TITLE
support for djvu

### ISSUE THREAD

**Issue by mcandre** [jgm/pandoc#2683]
Please add support for converting to and from DjVu format

**Comment by bluebirch** [comment]
DjVu is a picture format specially designed for scanned text documents. Out of curiosity, why would you want to convert from/to such a specialized format?

**Comment by mcandre** [comment]
Many technical books are available in DjVu format, but I'd prefer to convert these to PDF, as very few ereaders can view DjVu format.

**Comment by jgm** [comment]
It's not really a structured text format, so it's not appropriate for pandoc.
(Note that pandoc can't take PDF input either.)

**Comment by KurtPfeifle** [comment]
@mcandre:

Have you ever tried other tools to convert DjVu files to PDF? If so, why were they not good enough for you?

1.  DjVuLibre ships with a few command line tools. One of these, **`djvups`**, converts DjVu files to PostScript. Once you have PostScript, you can easily convert it to PDF with the help of Ghostscript. Here is  how to do it in a single command pipeline:

         djvups -level 3 in.djvu - | gs -o out.pdf -sDEVICE=pdfwrite -

    DjVuLibre is available here:

    * http://djvu.sf.net/

2.  Then there is **`djvu2pdf`**, available here:

    * http://0x2a.at/site/projects/djvu2pdf/

    It can convert multiple DjVu files in one go. If you run

        djvu2pdf /path/to/in.djvu

    it will create a file named *in.pdf* in your current directory.

(Caveats: I myself have not really tested any of these conversion paths thoroughly, because I do not frequently use DjVu files -- I just know that these tools exist and how you would use them if needed.)
