### ISSUE TITLE
pandoc -f markdown_github -t markdown_github get different result after format twice

### ISSUE THREAD

**Issue by QMonkey** [jgm/pandoc#2695]
Example code is below.
<pre>
# [POST] /abc/cde/efg

- TestA
- TestB
- TestC

```
Test test test
test test setst
```
</pre>
After I use the command 'pandoc -f markdown_github -t markdown_github' to format the source code, I get the result below (Please remove '@').
<pre>
\[POST\] /abc/cde/efg
=====================

-   TestA
-   TestB
-   TestC

<@!-- -->

    Test test test
    test test setst
</pre>
And then, I use the same command to format the above formated code, and I get the result below (Please remove '@').
<pre>
\[POST\] /abc/cde/efg
=====================

-   TestA
-   TestB
-   TestC

<@!-- -->
    Test test test
    test test setst
</pre>

**Comment by jgm** [comment]
+++ Charles Qiu [Feb 02 16 23:13 ]:
>   Example code is below
># [POST] /abc/cde/efg
>
>- TestA
>- TestB
>- TestC
>
>```
>Test test test
>test test setst
>```
>
>   After I use the command 'pandoc -f markdown_github -t markdown_github'
>   to format the source code, I get the result below (Please remove '@')
>\[POST\] /abc/cde/efg
>=====================
>
>-   TestA
>-   TestB
>-   TestC
>
><@!-- -->
>
>    Test test test
>    test test setst

Pandoc uses indented code blocks by default for code blocks
without any attributes.

Because the indented code block occurs after a list, an HTML
comment is added; otherwise it would be a continuation
paragraph of the list.

The backslash escapes are added to the brackets to avoid
having it interpreted as a link.  (Sure, in this case we
know that it's not a link because there's no reference
defined for `[POST]`.  But what if you were compiling
a fragment that was going to be combined with other
Markdown files, including a definition for `[POST]`?
Playing it safe here.)

>   And then, I use the same command to format the above formated code, and
>   I get the result below (Please remove '@')
>\[POST\] /abc/cde/efg
>=====================
>
>-   TestA
>-   TestB
>-   TestC
>
><@!-- -->
>    Test test test
>    test test setst

This is semantically equivalent to the previous one.

Note that all of these get parsed exactly the same way by
pandoc.  They are semantically equivalent.

You should expect md -> md transformations to be
semantically equivalent, but they won't be syntactically
equivalent.

The one odd thing here is the disappearing blank line after
the comment.  The Markdown writer should perhaps be tweaked
to make sure there's a blank line after a raw HTML block.

**Comment by jgm** [comment]
> The one odd thing here is the disappearing blank line after
> the comment.  The Markdown writer should perhaps be tweaked
> to make sure there's a blank line after a raw HTML block.

On second look, doing this would have some undesirable effects elsewhere.  I don't see anything here that *needs* changing.

**Comment by QMonkey** [comment]
> On second look, doing this would have some undesirable effects elsewhere. 

Yes. Due to the disappearing blank line, the final markdown code cannot display correctly in [vim-instant-markdown](https://github.com/suan/vim-instant-markdown/).
