### ISSUE TITLE
Support starred figure environment for two-column figures in latex

### ISSUE THREAD

**Issue by jhrmnn** [jgm/pandoc#2701]
This should be as easy as

``` markdown
![Caption](figure.png){star}
```

which would get translated with the implicit_figures extension as

``` latex
\begin{figure*}[htbp]
\centering
\includegraphics{figure.png}
\caption{Caption}
\end{figure*}
```

**Comment by jgm** [comment]
According to
https://en.wikibooks.org/wiki/LaTeX/Floats,_Figures_and_Captions
figure* environments can only be placed at the top of the
page or on their own page.  So that would be a significant
disadvantage for non-two-column users.

+++ Jan Hermann [Feb 06 16 13:08 ]:

**Comment by azag0** [comment]
Ok, how about the star gets honored only when the latex writer is run with a `twocolumn` variable? That would open another possibility, which would be no `star` tag, but all figures specified with a percentage width and wider than 50% would be translated into figure* when the twocolumn variable is passed.

**Comment by MiaoDX** [comment]
Hei, @azag0 , your suggestion about whether the width larger or smaller than `50%`  is really what I want, so how do you handle this at last? Since suggestion of @wilx  will make `figure` all become `figure*`. which is not so appealing. So is there some new advances?

**Comment by jayanthkoushik** [comment]
I think this works as a reasonable solution.

First, we define hide_from_pandoc ([source](https://stackoverflow.com/questions/40982836/latex-multicolumn-block-in-pandoc-markdown)).

    ---
    header-includes:
      - \newcommand{\hide_from_pandoc}[1]{#1}
      - \hide_from_pandoc{
          \let\Begin\begin
          \let\End\end
        }
    ---

Then we define a new environment for wide figures

    \newenvironment{widefig}{\renewenvironment{figure}{\begin{figure*}\centering}{\end{figure*}}}

Now, we simply use this environment for including wide figures.

    \Begin{widefig}
    
      ![Caption](img){#fig:name}
    \End{widefig}

Since the environment is hidden from pandoc, it doesn't effect non-latex outputs (afaik).

**Comment by tarleb** [comment]
It seems that a change would be problematic, and good alternative solutions exist. Thus closing.

**Comment by lukeflo** [comment]
@jhrmnn its been a while since your question. But I've written a Lua filter implementing a Latex workaround which allows to locally change a regular figure into a starred figure using an attribute.

You and everyone else interested might have a look: [9268](https://github.com/jgm/pandoc/issues/9268#issuecomment-1864282920)
