### ISSUE TITLE
unnumbered header becomes numbered if it ends with code

### ISSUE THREAD

**Issue by k16shikano** [jgm/pandoc#2706]
It seems that `unnumbered` for a header title dose not work properly when the title is ended with an element of `Code` type. 

```
# `Only code` {-}

# End with `code` {-}

# There is `code` somewhere {-}

# No code {-}
```

With Pandoc 1.16.0.2, I tried to convert the above Markdown file with `--number-section` and got a HTML below.

```
<h1 id="only-code"><span class="header-section-number">1</span> <code class="unnumbered">only code</code></h1>
<h1 id="end-with-code"><span class="header-section-number">2</span> end with <code class="unnumbered">code</code></h1>
<h1 id="around-code-somewhere" class="unnumbered">around <code>code</code> somewhere</h1>
<h1 id="no-code" class="unnumbered">no code</h1>
```

If there's a `code` at the end of the title strings, the `class="unnumbered"` is attached to the `code` element instead of their parent `h1`.  More seriously, the section number appears in such case despite being `unnumbered`.

**Comment by k16shikano** [comment]
FYI, if the title string ends with `em` element, there seems no problem at all.

**Comment by jgm** [comment]
This isn't a bug.  The problem is that code spans and
headers can both accept attributes in `{}`.  Here the
attribute is being assigned to the code span rather than
the header.

That's not wrong -- it's just not what you intended.

Workaround:  put something else between the code span and
the header, or put an empty attribute on the code span:

    # `only code`{} {-}

    # `only code`  {-}

**Comment by k16shikano** [comment]
I understand it's not a bug. Thank you for the workaround!
