### ISSUE TITLE
escaped square brackets in markdown converts as math instead of normal brackets

### ISSUE THREAD

**Issue by jaredmcguire** [jgm/pandoc#2707]
I am doing `-f markdown_github -t html`
and this `\[money\]` is producing this `<br /><span class="math display"><em>m</em><em>o</em><em>n</em><em>e</em><em>y</em></span><br />`

The web converter isn't so bad but it still converts it as math. [[link](http://pandoc.org/try/?text=%5C%5Bmoney%5C%5D&from=markdown_github&to=html)]

Correct me if I'm wrong but shouldn't this convert as normal brackets? `[money]`

**Comment by jgm** [comment]
You're right.

At one point in the (now perhaps distant) past,
github-flavored markdown support `\[...\]` for LaTeX
math.

I said at the time that this was a terrible idea,
because `\[` is needed for an escaped bracket.

Maybe they finally got the message.

Anyway, I can change this so `tex_math_single_backslash`
is not default for `markdown_github`.  In the mean time,
you can work around it by using

    -f markdown_github-tex_math_single_backslash


+++ Jared McGuire [Feb 09 16 22:12 ]:

**Comment by jaredmcguire** [comment]
Thanks for the work around. That worked great!
