### ISSUE TITLE
Embedding block level commands when using ConTeXt

### ISSUE THREAD

**Issue by AidanNichol** [jgm/pandoc#2751]
Is there any way to embed block level commands and get the content interpreted as markdown?
 e.g. I want todo something like

``` markdown
\startfrontmatter
... markdown contents
\stopfrontmatter
\startbodymatter
... markdown content
\stopbodymatter
\startbackmatter
... markdown content
\stopbackmatter 
```

**Comment by ousia** [comment]
@AidanNichol, sorry if I didn’t see your point, but let me guess a reply.

Why do you need Markdown sources to mimic a ConTeXt source file? Wouldn’t it be better to use the ConTeXt source file?

Markdown and pandoc make sense when you need a single source to generate different output formats. As a lightweight markup for TeX (either LaTeX or ConTeXt), it would be just the crazy way of doing it (sorry for being so assertive, but I guess we tend to forget this).

The real answer: yes, there is a way, but you have to deal with XML in ConTeXt MkIV. Otherwise, you have to rewrite the ConTeXt writer in pandoc (and I think this would be the wrong way to do it).

The _Markdown_ source should read (something like):

``` markdown
<div class="frontmatter">
the front part
</div>
<div class="bodymatter">
the body part
</div>
<div class="backmatter">
the body part
</div>
```

And how to deal with XML in ConTeXt MkIV is described in [this PDF document](http://pragma-ade.com/general/manuals/about.pdf).

A real world sample may be <http://www.from-pandoc-to-context.tk/>.

But let me know whether I miss something in (or your whole) point.

**Comment by AidanNichol** [comment]
@ousia thanks for the reply - most interesting.

I'm dealing with an environment where the documents are being created created by non-technical people and I want any addition to the markdown to be as simple as possible. I am creating epub, mobi and html5 output as well as PDF so I thought that if it is the latter that is being adjusted then raw ConTeXt would be preferable to raw HTML because it would be ignored by the other writers. I toyed with idea of inserting something into the markdown source that gets manipulated in a filter but that gets a bit complicated.

Your suggestion of using the ability of ConTeXt to handle XML (XHTML) is causing me a lot of churn in my thinking. Assuming that I have a starting environment file that give the equivalent of the pandoc ConTeXt writer then it gives a lot more flexibility in styling the PDF.

Can I check my understanding with an example. I would like have a definition list formatted in a more compact way using ```width=fit``` to get the term on the same line as the definition. I could override the default for all definitionlists (undesirable) or I could create a ```\start...``` and ```\stop...``` block in which I could override the default setup --- assuming I can somehow persuade pandoc to let me define the block. In html5 I could do this by CSS using a class on a parent section of preceding header.

If understand correctly you are suggesting instead of trying to find ways to override the defaults in ConTeXt I could just define my own description format ```\mydescription``` and using the XML->ConTeXt mapping environment get it to use that rather than the standard ```\description``` using the same type of selection criteria available to me in CSS..

I'm going to try your environment file and see how I get on.

**Comment by mb21** [comment]
I'd probably go with a pandoc native div (current syntax is html as below, but see #168) and write a filter to convert it to the context command.

```
<div class="style-startfrontmatter">
foo _bar_
</div>
```

Also see #2542 for a discussion of building that functionality right into pandoc (so you wouldn't have to write a filter..)
