### ISSUE TITLE
Suggestion: Add --wrap=justify

### ISSUE THREAD

**Issue by qua-bla** [jgm/pandoc#2779]
I am using pandoc to pretty print markdown. Adding justification would make it even prettier.

**Comment by jgm** [comment]
I think justification in fixed-width fonts is too ugly to make it worth adding.
(And adding it would add a lot of complexity.)

**Comment by v1kn** [comment]
can text alignment be done through templates? I tried adding `text-align: justify;` to the paragraph section of a CSS file I call with `-c` flag, but the text isn't justified in a browser

**Comment by jgm** [comment]
+++ v1kn [Jan 07 17 00:22 ]:
>   can text alignment be done through templates? I tried adding
>   text-align: justify; to the paragraph section of a CSS file I call with
>   -c flag, but the text isn't justified in a browser

Hm, this should work, and I've often done this.
Maybe there's a small problem with the way you're doing it?

**Comment by v1kn** [comment]
@jgm 
Thank You for responding, even though I deleted my comment (because I was commenting on a similar things in a different issue)

Is is entirely possible there's a problem with how I'm doing it, so here's the rundown:

* invocation command:

    pandoc -f markdown_github+footnotes+fenced_code_attributes+yaml_medatada_block+shortcut_reference_links+blank_before_header+subscript+superscript+implicit_header_references \
    --standalone \
    --smart \
    --toc
    -c /pathto/my-css-file.css

* [here][1] is my css file

If You can point me in the right direction I would appreciate it

[1]: https://github.com/v1kn/dotfiles/blob/master/pandoc/.pandoc/css/jekyll-test.css

**Comment by jgm** [comment]
I tried with your css file and it worked (justified
paragraphs).  So I'm not sure what to suggest.  Take a
look at the generated html file and make sure it contains
a reference to your CSS.  Do any of the CSS properties
work?  Is it possible your browser is not finding the CSS
file (you could confirm this by using a browser debugger).

**Comment by jgm** [comment]
There's a stray '2' in the h1 stanza of your CSS,
maybe this is confusing the browser?


+++ John MacFarlane [Jan 07 17 12:57 ]:
>I tried with your css file and it worked (justified
>paragraphs).  So I'm not sure what to suggest.  Take a
>look at the generated html file and make sure it contains
>a reference to your CSS.  Do any of the CSS properties
>work?  Is it possible your browser is not finding the CSS
>file (you could confirm this by using a browser debugger).
>

**Comment by v1kn** [comment]
@jgm 
maybe, but I think I found what may be the culprit - I use vim, and I use hard wrapping at 80 characters. I now tried soft wrapping and text is justified. 

Do You have an idea how to deal with justifying hard-wrapped text?
I tried justifying it in vim, but the additional spaces get ignored during conversion

**Comment by v1kn** [comment]
since I don't have these files published (and I am using someone else's article as a testbed), I can only offer screenshots:

[source text in vim][1], first paragraph soft-wrapped, the rest hard-wrapped

[html file in fiefox][2]

[1]: http://imgur.com/a/QPFSt
[2]: http://imgur.com/a/pydWj

**Comment by v1kn** [comment]
I can reproducibly confirm what is causing this: `markdown_github` as an input format

As soon as I switched from it to standard `markdown`, everything is now justified.

Should I open an issue for this?

**Comment by jgm** [comment]
The problem is undoubtedly that markdown_github includes the
hard_line_breaks extension, which causes each newline to
turn into a `<br>` tag in HTML.  (That will mess up
justification.)

This is how GitHub's markdown works in comments (though not
in README and other long form content).

To turn it off, use:

    -f markdown_github-hard_line_breaks


+++ v1kn [Jan 07 17 04:50 ]:

**Comment by v1kn** [comment]
yes this is the solution I came to yesterday. However, since lack of `hard_line_breaks` changes how some parts of my documents will look like (I did not follow strict markdown's rules on double space at the end of the line to introduce hard line break), I opted to instead use `escaped_line_breaks`.

Using `pandoc -f markdown_github-hard_line_breaks+escaped_line_breaks` does not work as expected though (escaped_line_breaks extension is ignored). Usually, I would start disabling other extensions to see what the culprit is, but as You can see from my comment on issue #583 regarding `\LaTeX`, even when I disabled *all* the extensions defined in markdown_github, the issue still persisted.

So as a solution, I now use `-f markdown`, and am adding all the extensions from github variant to it, except hard_line_breaks

Thank You for Your assistance.

**Comment by jgm** [comment]
+++ v1kn [Jan 07 17 16:10 ]:

>   Using pandoc -f markdown_github-hard_line_breaks+escaped_line_breaks
>   does not work as expected though (escaped_line_breaks extension is
>   ignored).

Why don't you opne a new issue on this, with an example to
reproduce.

**Comment by v1kn** [comment]
No problem.
