### ISSUE TITLE
Feature Request: Switch for placement of table captions before or after the table

### ISSUE THREAD

**Issue by wuffi** [jgm/pandoc#2868]
Dear pandoc developers,
Captions for tables were originally put below table (at least in docx writer), but now (due to a new commit), they are put above the table.
It would help users, if they could switch between these two ways of placing the captions.
Best

**Comment by jgm** [comment]
Putting table captions above (and figure captions below)
is standard practice.  See e.g.
http://tex.stackexchange.com/questions/3243/why-should-a-table-caption-be-placed-above-the-table

The change you're referring to brought the docx writer into
conformity with this standard, and also with the other
writers (PDF, HTML, etc.).

In principle, table caption location could be made
configurable, but this would require a change to the
underlying Pandoc data structure, which is a fairly
major change affecting the whole pandoc ecosystem.
It probably won't happen unless there's strong demand.

**Comment by reagle** [comment]
I would like this, since `Table: ` can be above or below in the markdown, why not forward its placement into the output format?

**Comment by phiresky** [comment]
Putting table captions above is not standard practice everywhere, e.g. the CVPR template puts captions below templates ([see here](http://cvpr2019.thecvf.com/submission/main_conference/author_guidelines)).

Right now, this means I have to write my tables in latex instead of in markdown. So it would be nice if this was configurable. I think a global flag would be enough, and since the latex generation is mostly hard coded anyways (can't be changed via template), it seems like making it configurable via the frontmatter should be possible?

**Comment by njbart** [comment]
The [koma-script manual](http://ctan.math.utah.edu/ctan/tex-archive/macros/latex/contrib/koma-script/doc/scrguien.pdf), too, describes this question as debatable:

> For tables, opinions differ as to whether captions should be placed above the table or, consistent with captions of figures, below it.

What’s more, certain university departments’ style guides force students to either put both table *and* figure captions above, or both below.

Even worse, in one case I am aware of the requirement is to put table and figure captions (with labels) above, and a second caption, indicating sources, below.

Not sure how the last bit could be handled sensibly, but in general, some kind of toggle for both tables and figures would be very welcome.

**Comment by jgm** [comment]
@njbart #1024 is probably the best place for this kind of comment (rather than this closed issue).
