### ISSUE TITLE
Separate paragraph style after display equation in docx

### ISSUE THREAD

**Issue by danil-tolkachev** [jgm/pandoc#2871]
The paragraphs after equations contain extra padding when identation are used to separate paragraphs. It would be nice for these paragraphs to use it's own style, by analogy with the First Paragraph style.

For example, the following markdown
```
In elementary algebra, a quadratic equation (from the Latin quadratus for "square")
is any equation having the form
$$ax^2+bx+c=0$$
where $x$ represents an unknown, and $a$, $b$, and $c$ represent known numbers 
such that a is not equal to $0$.

The following equation is equivalent to the quadratic equation:
$$\left(x+\frac{b}{2a}\right)^2=\frac{b^2-4ac}{4a^2}.$$

Taking the square root of both sides, and isolating x, gives:
$$x=\frac{-b\pm\sqrt{b^2-4ac\ }}{2a}.$$
```

produces 
![extra-indent](https://cloud.githubusercontent.com/assets/12847693/14754413/e90489dc-08e3-11e6-8019-55d42d08b6c5.png)

With separate style for paragraph after display equation it will be possible to remove extra indent from 'where'
![no-extra-indent](https://cloud.githubusercontent.com/assets/12847693/14754443/04c5f2e6-08e4-11e6-9cea-05a458035104.png)

**Comment by danil-tolkachev** [comment]
@jkr, could you look at this issue, please.

**Comment by danil-tolkachev** [comment]
I found that paragraph after equation starts with space. That let me write hack for unindent paragraph after equation. Here python script with using [python-docx](https://github.com/python-openxml/python-docx) package:
```{python}
import sys
import docx

fname = sys.argv[1]
doc = docx.Document(fname)
noindent = doc.styles['Compact']

for p in doc.paragrapsh:
    if p.text.startswith(' '): # paragraph starts with space
        p.style = noindent # apply style
        p.runs[0].text = p.runs[0].text[1:] # remove space

doc.save(fname)
```

**Comment by jkr** [comment]
Fixed with b103f829f0d14055744998a6a6f624797fbd0d40. Paragraphs after Display Math are now set to `First Paragraph` style.

Note that the space at the beginning of the math that you used in the above script was a bug, that was fixed in 2c62f0e122d71dad356cba949269377ce98ed3f8. Hopefully you won't need the script anymore though.

**Comment by danil-tolkachev** [comment]
@jkr, Thank you. I think using `First Paragraph` style in this case is not optimal. For example, in the Russian typographic tradition first paragraphs indent like other paragraphs. So I tune `First Paragraph` style  as `Body Text`. It may be better to use `Compact` style (or something else) for paragraphs after Display Math?

**Comment by jkr** [comment]
Well, First Paragraph actually has a few uses: it's also used for after block-quotes, tables, etc. So that seems appropriate for this case as well. Your particular case seems to be about the first paragraph of sections, or a document. We could add a different class there, but it might not work with someone else's workflow. Anything is going to take some manual fiddling. What we have now seems like a good happy medium. And I'm worried about adding a million extra styles. So I'd reccomend setting `First Paragraph` to no indent and setting the first paragraphs of sections by hand.

You're welcome to start a discussion on pandoc-discuss, though -- perhaps there will be some consensus about what would work best for the greatest number of people.

In any case, it would be nice to have a scriptable way to set paragraph styles.

**Comment by danil-tolkachev** [comment]
OK, you know better. I don't understand, what do you mean by "scriptable way to set paragraph styles"?
