### ISSUE TITLE
Unnumbered section heading with the last word being <code>

### ISSUE THREAD

**Issue by yihui** [jgm/pandoc#2878]
This is a bug originally reported at https://github.com/rstudio/bookdown/issues/96 A minimal reproducible example:

```md
# AB

## CD

### AB and `CD` {-}

```

Run

```sh
pandoc -f markdown -t html -N
```

and you get

```html
<h1 id="ab"><span class="header-section-number">1</span> AB</h1>
<h2 id="cd"><span class="header-section-number">1.1</span> CD</h2>
<h3 id="ab-and-cd"><span class="header-section-number">1.1.1</span> AB and <code class="unnumbered">CD</code></h3>
```

The h3 title should not be numbered.

**Comment by jgm** [comment]
It's not really a bug, I'd say.  Note that
```
`hi` {.class}
```
creates a code span with attributes.  So pandoc is interpreting the attributes in your example as applying to the final code span, rather than the heading as a whole.  It's a precedence issue.  Sure, in this case it's obvious what was intended, but pandoc doesn't have AI to figure these things out.

**Comment by yihui** [comment]
I see. Thanks for the explanation!
