### ISSUE TITLE
PDF pagination bug

### ISSUE THREAD

**Issue by lukebaker** [jgm/pandoc#2889]
I've run across an odd situation where the page breaks don't appear to be inserted early enough and so text runs into the bottom margin of the page and some of the text is clipped. The case where I've see this happen is when a page starts with an image and includes a table. Here's a [gist containing the sample markdown file](https://gist.github.com/lukebaker/74536f1d6910405b6b4d8f6ee0f867a7) that manifests the problem and the [resulting PDF](https://github.com/jgm/pandoc/files/243034/pagination-bug.pdf)
 from running `pandoc -s -S -o output/pagination-bug.pdf pagination-bug.md`.

The sample file is simply setting up the situation where the image will be at the start of a page that also includes a table with an additional page following that one. I used an inline base64 image for ease of duplication, but all images I tried (including non base64 encoded images) exhibited the problem.

Environment:
* Ubuntu 14.04.4
* Pandoc 1.17.0.2
* pdfTeX 3.1415926-2.5-1.40.14

**Comment by jgm** [comment]
I've seen this before; I think it's a longtable package bug.
See
http://tex.stackexchange.com/questions/213911/figure-or-longtabu-longtable-causes-bottom-margin-overflow
Your example fits this description: longtable after float.
Try the fix recommended to longtable.sty and let me know if
that works!

+++ Luke Baker [Apr 29 16 12:14 ]:

**Comment by lukebaker** [comment]
John, thanks for pointing me in the right direction. The longtable patch fixed my issue.

**Comment by KurtPfeifle** [comment]
> I've run across an odd situation where the page breaks don't appear to be inserted early enough and so text runs into the bottom margin of the page and some of the text is clipped. The case where I've see this happen is when a page starts with an image and includes a table.
> [...]
> Environment:
> 
> Ubuntu 14.04.4
> Pandoc 1.17.0.2
> pdfTeX 3.1415926-2.5-1.40.14

I've seen this also happening yesterday, for the first time. My environment is different, though, and even more important: I'm not using a longtable nor a float in the document.

**Environment:**
Windows 10
Pandoc 1.17.0.2
MikTeX  2.9.5857 (Portable Version)

As said above I do not use any figure, image, float or table in the Markdown source. 

The only "unusual" in the source is that it uses very long lines of level 3 ATX headers without any paragraph text (yet).

It was meant as an initial draft outline for the final document's structure when starting to work on a longer expertise ordered by a court. (Otherwise, with some text in between -- as would happen in a later stage of the work -- the problem would probably have remained un-discovered.)

However, when I replaced the long heading lines by shorter ones, the problem didn't go away. The only condition which seems to trigger the problem is the fact that no paragraph texts are (yet) in the Markdown.

An almost minimal example demonstrating the bug is **[at this Gist](https://gist.github.com/KurtPfeifle/c0132928421ebfdebcc13d8060fa55e2)**.

The simple command  `pandoc -o out.pdf gistcontent.md` produces a PDF where the last page is overflowing.

**Comment by jgm** [comment]
Again, this seems to be a LaTeX layout issue, and not
something we can fix in pandoc.  Probably LaTeX expects
that section headers will have content under them.

+++ Kurt Pfeifle [May 02 16 07:47 ]:

**Comment by toebbel** [comment]
I think there is an urgent need to shift away from `longtable` as I ran across this issue and had to apply [this patch here](http://www.latex-project.org/cgi-bin/ltxbugs2html?pr=tools/3512 ) manually which i found [on stack overflow](http://tex.stackexchange.com/a/233096/9082). 

The Pull Request on the longtable package states

> State: open
> Arrival date: Sun Mar 09 21:41:00 +0100 2003

Pandoc should not depend on `longtable`, since that seems not to be maintained properly.

**Comment by jgm** [comment]
I'm open to considering alternatives to longtable.  But we
do need to be able to support tables that won't fit on one
page, I think.

+++ Tobias Sturm [Sep 09 16 03:38 ]:

**Comment by wilx** [comment]
Shameless plug: https://github.com/jgm/pandoc/issues/3103
