### ISSUE TITLE
Scientific notation in inline R code fails to compile for pdf output

### ISSUE THREAD

**Issue by yasirs** [jgm/pandoc#2895]
Consider the following .Rmd document

    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    a <- anova(lm(cars$speed ~ cars$dist))
    pval <- a$`Pr(>F)`[1]
    ```
    The p-value for the dependence of speed on dist is `rpval`.
    ```{r cars}
    summary(cars)
    ```
This compiles for HTML or Word, but not for pdf. I am using the Rstudio menu for compiling. It spits the following error:

```
! Missing $ inserted.
<inserted text> 
                $
l.126 1.4898365\times

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
Execution halted
```

**Comment by jgm** [comment]
You should take this up with rmarkdown/rstudio developers.
They can diagnose it further in their environment, and
if it looks like there's a problem with pandoc, they or
you can add an issue here.  There's no reason, at this
point, to think that the problem lies with pandoc, but I
don't really know anything about rmarkdown/rstudio.

+++ yasirs [May 02 16 14:35 ]:
