### ISSUE TITLE
leading 0's in metadata variable get mangled

### ISSUE THREAD

**Issue by legrostdg** [jgm/pandoc#2945]
pandoc seems to mangle the 0's at the beginning of a variable

test.md:

    ---
    testvar: 0001
    ...

template.tex:

    $testvar$

command line:

    pandoc --template template.tex test.md -o test.tex

**Comment by jgm** [comment]
A standard YAML parser is used to parse the metadata.
0001 gets parsed as the number 1.

However, the pandoc metadata type doesn't have a variant
for number, so this gets converted to the string '1'.

Solution:  put 0001 in single quotes, so the YAML parser
will treat it as  a string rather than a number.

**Comment by legrostdg** [comment]
OK, I guess there is not much to do here... YAML is not perfect :-)
