### ISSUE TITLE
Inline Math not Rendering Correctly?

### ISSUE THREAD

**Issue by mike-ward** [jgm/pandoc#2976]
Block (`$$`)  works. Inline (`$` or `\(`) appears not to.
```
► pandoc -f markdown_github+tex_math_dollars --mathjax
$$ \mathcal{C} = \mathcal{{B}_{l, u}} = \left\{ x \mid l \leq {x}_{i, j} \leq u, \; \forall i, j \right\} $$
^Z
<p><span class="math display">\[ \mathcal{C} = \mathcal{{B}_{l, u}} = \left\{ x \mid l \leq {x}_{i, j} \leq u, \; \forall i, j \right\} \]</span></p>

C:\Users\mike\Documents\GitHub\Markdown-Edit\src\MarkdownEdit\bin\Debug
► pandoc -f markdown_github+tex_math_dollars --mathjax
$ \mathcal{C} = \mathcal{{B}_{l, u}} = \left\{ x \mid l \leq {x}_{i, j} \leq u, \; \forall i, j \right\} $
^Z
<p>$ \mathcal{C} = \mathcal{{B}<em>{l, u}} = \left{ x \mid l \leq {x}</em>{i, j} \leq u, \; \forall i, j \right} $</p>


► pandoc -f markdown+tex_math_dollars --mathjax
$$ \mathcal{C} = \mathcal{{B}_{l, u}} = \left\{ x \mid l \leq {x}_{i, j} \leq u, \; \forall i, j \right\} $$
^Z
<p><span class="math display">\[ \mathcal{C} = \mathcal{{B}_{l, u}} = \left\{ x \mid l \leq {x}_{i, j} \leq u, \; \forall i, j \right\} \]</span></p>

► pandoc -f markdown+tex_math_dollars --mathjax
$ \mathcal{C} = \mathcal{{B}_{l, u}} = \left\{ x \mid l \leq {x}_{i, j} \leq u, \; \forall i, j \right\} $
^Z
<p>$  =  = { x l _{i, j} u, ; i, j } $</p>


► pandoc -f markdown_strict+tex_math_dollars --mathjax
$$ \mathcal{C} = \mathcal{{B}_{l, u}} = \left\{ x \mid l \leq {x}_{i, j} \leq u, \; \forall i, j \right\} $$
^Z
<p><span class="math display">\[ \mathcal{C} = \mathcal{{B}_{l, u}} = \left\{ x \mid l \leq {x}_{i, j} \leq u, \; \forall i, j \right\} \]</span></p>

► pandoc -f markdown_strict+tex_math_dollars --mathjax
$ \mathcal{C} = \mathcal{{B}_{l, u}} = \left\{ x \mid l \leq {x}_{i, j} \leq u, \; \forall i, j \right\} $
^Z
<p>$ \mathcal{C} = \mathcal{{B}<em>{l, u}} = \left{ x \mid l \leq {x}</em>{i, j} \leq u, \; \forall i, j \right} $</p>

► pandoc --version
pandoc 1.17.0.2
```

**Comment by mpickering** [comment]
Don't leave a space after the `$` and it will work correctly.

**Comment by RoyiAvital** [comment]
Could Pandoc remove this limitation?
Enforcing no "Space" inside the `$...$` means much less readable code.

Thank You.

**Comment by jgm** [comment]
You can have spaces inside `$...$`, just not at the very beginning or end.

If we allowed spaces after the opening `$` or before the closing `$`, we'd capture things like
```
It costs $4 or $5.
```
as math.  LaTeX can allow the spaces, because in LaTeX the `$` can *only* indicate math mode. In Markdown many `$`s are just `$`s, and we need heuristics to tell the difference.  The rules about initial and final spaces are the heuristics.

**Comment by RoyiAvital** [comment]
I am aware of the "Difficulties" it creates.
But people use Math in MarkDown usually want it Fast and Simple replacement for LaTeX.
in LaTeX you can add space after `$` delimiter.

What I suggest is the user to have the ability to configure the behavior of Pandoc.
I would personally prefer the behavior of LaTeX, other might think differently.

Thank You.

P. S.
What I don't understand is, does Pandoc uses MathJaX behind the scene for Math rendering?
Because MathJaX allows spaces after `$` and before `$`.

**Comment by yxliang01** [comment]
I recommend to add an option for allowing this.... It will help me a lot.

**Comment by linquize** [comment]
Don't leave leading and trailing spaces within `$xxx$` block
