### ISSUE TITLE
Issue with Institute in Markdown YAML header

### ISSUE THREAD

**Issue by ericmjl** [jgm/pandoc#3004]
I usually write in Sublime text, and have two PDF output options from the `pandoc` plugin, which uses the `pandoc` library installed locally (i.e. I know that I need to have pandoc installed for it to work).

In my Markdown file, the following outputs a proper header when I use Pandoc to make the PDF:

    ---
    title:  'This is the title: it contains a colon'
    author:
    - Author One (Affiliation)
    - Author Two (Affiliation)
    ---

However, the following simply replaces author names with "true" and "true":

    ---
    title:  'This is the title: it contains a colon'
    author:
    - name: Author One
    - name: Author Two
    ---

I tried following the [`pandoc` user guide](http://pandoc.org/README.html), but the output also returns "true" and "true" where the author names are supposed to be:

    ---
    title:  'This is the title: it contains a colon'
    author:
    - name: Author One
      affiliation: University of Somewhere
    - name: Author Two
      affiliation: University of Nowhere
    ---
I looked at the `default.latex` template, and noticed that the template uses the `institute` keyword, rather than `affiliation`. So I tried replacing `affiliation` with `institute`, as such:

    ---
    title:  'This is the title: it contains a colon'
    author:
    - name: Author One
      institute: University of Somewhere
    - name: Author Two
      institute: University of Nowhere
    ---

However, I still get "true" and "true" in the author name fields.

The only hack I have been able to get work is as such:

    ---
    title:  'This is the title: it contains a colon'
    author:
    - Author One (University of Somewhere)
    - Author Two (University of Nowhere)
    ---

Might I be missing something in my configuration?

**Comment by Jmuccigr** [comment]
The template file for your output format needs to be able to handle the metadata being passed to it. In this case the default.latex file can handle multiple authors, but that's it. See the guide's section on [YAML metadata blocks](http://pandoc.org/README.html#extension-yaml_metadata_block), where this issue is addressed directly (though admittedly without stating what error you might get).

Also note the `-D` switch which will output the current default template for the various formats (also in the guide).

**Comment by ericmjl** [comment]
Got it, thanks @Jmuccigr!
