### ISSUE TITLE
Markdown not parsed after \noindent command

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#3008]
It seems that Markdown after a `\noindent` command is not interpreted by Pandoc 1.17.1 (presumably related to https://github.com/jgm/pandoc-citeproc/issues/243):

```md
pandoc << EOT
\noindent *Test*

\noindent `Test`
EOT
```

Results:

```html
<p>Test*</p>
<p></p>
```

**Comment by jgm** [comment]
In the first case, what's happening is that the whole `\noindent *` is interpreted as a LaTeX command.  Remember, pandoc tries to treat anything that looks like a LaTEX command as one, and LaTeX commands sometimes have optional `*` variants, where the `*` can be separated from the control sequence by a space.

I'm not sure what's happening in the second case, since if I just do

     % echo '\noindent `Test`' | pandoc

I get

    <p><code>Test</code></p>

as expected.  Something involving shell escaping, I'll bet.
