### ISSUE TITLE
Problem converting from latex to docx

### ISSUE THREAD

**Issue by Jegama** [jgm/pandoc#3054]
After compiling everything with using pdflatex (both in Mac and Windows), I'm not able to create a docx file using pandoc. Am I doing anything wrong?

`pandoc --bibliography=References.bib --csl=myClass.cls -o file.docx file.tex`

I get this error message in both, Windows and Mac:

pandoc-citeproc: 1:1-107:1: Found content after root element: EventContent (ContentText <My custom csl file>)
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1

**Comment by mb21** [comment]
I'd guess there's something wrong with your .csl file, try [validating it](http://validator.citationstyles.org/).

**Comment by Jegama** [comment]
Thank you for the page. I tested my .csl file and one from the ieee that I already now it worked before, and it gave the same error:

> required character (found “%”) (expected “<”)

I tried to add:
```
<?xml version="1.0" encoding="UTF-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text" default-locale="en-US"/>
```

But in addition of the past error, now it says this:

> Lines 1-2: Element “style” from namespace “http://purl.org/net/xbiblio/csl” is missing a required instance of one or more of the following child elements: “info”.

**Comment by jgm** [comment]
If you upload your csl file we can take a look.

**Comment by Jegama** [comment]
Is this one:

https://github.com/vrmpx/templateTesisITAM/blob/master/tesisITAM.cls

**Comment by jgm** [comment]
Are you sure you downloaded the "raw" version and not the
HTML representation?  (That is a common mistake.)

For example, if you did:

    wget https://github.com/vrmpx/templateTesisITAM/blob/master/tesisITAM.cls

then you'd get an HTML document, not the XML CLS document.
What you want is

    wget https://raw.githubusercontent.com/vrmpx/templateTesisITAM/master/tesisITAM.cls


+++ Jegama [Aug 04 16 16:22 ]:

**Comment by jkr** [comment]
@Jegama I think the problem here is you're using a **cls** file (i.e. a LaTeX class file) and not a **csl** file (i.e. a citation style language file). The `--csl` option is for [citation style language](http://citationstyles.org/). You can call a LaTeX class file from your template.

**Comment by Jegama** [comment]
I don't remember which one I used, but I just download the "raw" version and is still not working @jgm 

@jkr is there alternative to use a cls file?

**Comment by jkr** [comment]
No, there isn't an alternative to use a cls file. If you're trying to convert from LaTeX to docx, pandoc can only use the LaTeX subset it understands -- it does allow macros, so it you define commands in your preamble it might be able to handle them.

I'm confused, though -- why are you trying to use a class file? Are there certain LaTeX commands you need? Or is it related to bibliography processing? You do specify a bib file in your command. If it's the latter, you still need a csl (citation style language) file.

What happens if you just run the command without the incorrect "--csl" option?

**Comment by Jegama** [comment]
That's unfortunate. I'm using the class file because it was custom made to fit the thesis requirements of my university, it has some custom commands declared in the class file.

When I try to run the command without the "--csl" option, it converts with the bibliography, but is almost plain text, and all the references to the figures and tables are missing in the text. It doesn't include the on them nor create the table of contents for them.

**Comment by jkr** [comment]
Unfortunately, pandoc will not be able to do all the things that LaTeX can do. You can certainly change the citation style to be something more like the one your university uses. Again, you'd have to investigate http://citationstyles.org in order to learn more about the numerous citation styles available.

The specific commands could conceivably be moved into the preamble of your LaTeX document depending on how they're defined, and what they affect.

You can search the issues and the mailing list for discussions of references to figures and tables. I know it's something people are interested in, and I think there are some third-party ways to deal with it in pandoc, but I don't believe it's currently supported.

SInce the initial bug report was about a failure to read a csl file which was in fact not a csl file, I'll close this issue. But I'm sure foks on [pandoc-discuss](https://groups.google.com/forum/#!forum/pandoc-discuss) will be able to help you with issues specific to your conversion.
