### ISSUE TITLE
Try pandoc with markdown broken ?

### ISSUE THREAD

**Issue by flibustenet** [jgm/pandoc#3099]
In "Try pandoc" online, currently the result **to markdown** seems broken.

```
<a href="/coucou.html?x=3">hop</a>
```

return in markdown :
```
[hop]

  [hop]: /coucou.html?x=3
```

same with textile 

I've not this problem with pandoc 1.9.4.2 (old debian)

**Comment by tarleb** [comment]
I'm guessing that you expected `[hop](/coucou.html?x=3)` instead of the above?  The difference stems from trypandoc's use of the `reference-link` option.  You should be able to reproduce this locally by passing `--reference-link` to pandoc.  Trypandoc isn't as much broken as performing in less undocumented ways.  2e33d36 might be a possible solution.

**Comment by flibustenet** [comment]
Exactly.
Thanks, i'm a beginner with markdown !
