### ISSUE TITLE
Is it possible to have an option to output all spaces as normal spaces instead of including non-breaking spaces?

### ISSUE THREAD

**Issue by x-ji** [jgm/pandoc#3112]
I'm currently frequently using `pandoc` to convert HTML content from the internet to `org` format, in order to paste to my org-mode notebooks. I execute the following command from Emacs:

`python ~/Dropbox/scripts/HTMLClipboard.py | pandoc -f html -t org --wrap=none`

 One thing that's fairly annoying for me is that `pandoc` automatically produces a lot of non-breaking spaces, while Emacs doesn't recognize non-breaking space as a valid separator for keyword highlighters such as `/`(for italics) or `=`(for monospace), and it's fairly complicated to change that since it's hardcoded in an Emacs distribution. This results in my notes being rendered weirdly, e.g. a passage from the webpage http://websharper.com/docs#getting_started/installing_in_visual_studio has a lot of monospace fonts in it, but instead of getting the paragraph rendered as:

> Run the script `runngen.ps1` in PowerShell with administrator permissions to call `ngen.exe` on the compiler. It can be found in the `tools`folder of both `Zafir.CSharp` and `Zafir.FSharp` packages. This creates a cached native image that can speedup compiler tool running time.

I get

> Run the script =runngen.ps1= in PowerShell with administrator permissions to call =ngen.exe= on the compiler. It can be found in the =tools=folder of both =Zafir.CSharp= and =Zafir.FSharp= packages. This creates a cached native image that can speedup compiler tool running time.

with a lot of = visible and non-monospace font displayed.

I can certainly tweak the process so that I pass the output returned by `pandoc` again through some other script, which substitutes all the non-breaking spaces to normal spaces, but I'd just like to know, is there a possibility that `pandoc` adds such an option in its commands? I can imagine certain other older applications also having issues handling non-breaking spaces as well.

Sorry if there's already an option that does it, since I haven't been able to find it.

**Comment by jkr** [comment]
It doesn't seem like an option that would be useful in too many other modes, especially because scripts and filters make it pretty easy to take care of it. So I'm not sure if it makes too much sense to add it as a general option.

But @tarleb: does org-mode only use regular spaces? Or should we at least tweak the writer in the instances that @x-ji is describing?

By the way, @x-ji, in addition to working with pipes after conversion, you can also use a filter in the middle of conversion. Here's one I came up with quickly in haskell, but you could also write one in python. Then just run pandoc with the `--filter` option pointing to this file.  (See [here](http://pandoc.org/scripting.html) for an intro to using filters in pandoc.)

~~~{.haskell}
import Text.Pandoc.JSON
import Text.Pandoc.Builder
import Text.Pandoc.Generic
import Data.Char

replaceSpaces :: String -> [Inline]
replaceSpaces s = toList $ text $ map f s
  where f c | isSpace c = ' '
            | otherwise = c

fixInline' :: Inline -> [Inline]
fixInline' (Str s) = replaceSpaces s
fixInline' il = [il]

fixInline :: [Inline] -> [Inline]
fixInline = concatMap fixInline'

go :: Block -> Block
go = bottomUp fixInline

main :: IO ()
main = toJSONFilter go
~~~

**Comment by x-ji** [comment]
@jkr Thanks for the code and pointing me to filters. I didn't notice that before. However, since I do this conversion in multiple systems, some of which don't have Haskell installed, I'm still currently piping to Python scripts. I'll definitely check out filters for other tasks though.

**Comment by jkr** [comment]
@x-ji FWIW, same thing (I think) in python 2. The unicode stuff might get a bit hairy if you have to go back and forth between 2 and 3. It uses the [pandocfilters](https://pypi.python.org/pypi/pandocfilters) library.

~~~{.python}
import pandocfilters as P
import re

def replace_spaces(s):
    space_pat = re.compile("\s+", re.UNICODE)
    fixed = space_pat.sub(' ', s)
    fixed_split = re.split('(\s)', fixed)
    return [P.Space() if x == ' ' else P.Str(x) for x in fixed_split]
    

def fix_strings(key, value, fmt, meta):
    if key == "Str":
        return replace_spaces(value)

if __name__ == '__main__':
    P.toJSONFilter(fix_strings)
~~~

But, on the whole, the ultimate goal should be to make sure the org writer does the right thing.

**Comment by tarleb** [comment]
> does org-mode only use regular spaces?

I double-checked, the org-writer doesn't insert any non-breaking spaces other than those already present in the input.  So the proposed filter should be able to fix this.

**Comment by jkr** [comment]
@tarleb -- right, but I'm wondering whether it ever makes sense to output nbsp in org-mode, even if it was in the input. Lots of html and LaTeX files use nbsp or `~` for a number of reasons. But if it screws up org-mode rendering, it's not clear to me that it should be passed through to the writer. Not pushing for anything here, just curious.

**Comment by tarleb** [comment]
Ah, I misunderstood then, interesting question.  It's complicated: Org-mode has some weird layout rules, disallowing certain characters around markup.  E.g. `/text/` would be interpreted as emphasized text, but `⍽/text/` would be parsed literally.  Same for `*⍽,⍽*` and `*,*`.  Hacks involving less-common space characters are not that rare, especially since Org-mode doesn't have a proper way to escape markup characters.  The zero width spaces are used the most in these hacks, but nbsps are easier to type on some keyboards. Replacing nbsps would hence break org-markup in some cases and preserve it in others.  We'd need a much smarter writer to pull this off properly.

**Comment by NightMachinary** [comment]
@tarleb Isn't the use of nbsps in valid org irrelevant? pandoc is presumably converting from a non-org source to org, so its nbsps are almost certainly not intended as hacks around org markup.

@jkr Any solutions using Python 3? Python 2 is no longer supported.
