### ISSUE TITLE
LaTeX Writer: Use \slash command

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#3132]
A plain solidus character (`/`) is non-breaking in LaTeX, which can cause problems when using short columns; the breaking version is `\slash`. [WikiBooks](https://en.wikibooks.org/wiki/LaTeX/Text_Formatting#Slash_marks) and [*Digital Typography Using LaTeX*](https://books.google.com/books?id=trIPBwAAQBAJ&lpg=PA227&vq=slash&pg=PA227#v=snippet&q=slash&f=false) ([Springer subscription](https://doi.org/10.1007/b98959), p. 227) recommend that words including the character should always be written using this command, and I wonder whether Pandoc should start doing this.

The main disadvantage I can see is that [a word following `\slash` is not hyphenated](http://tex.stackexchange.com/questions/97310/slash-allows-for-hyphenation-of-only-the-word-on-its-left-how-to-fix-it-for-th), but in the vast majority of cases it would be an improvement. I am happy to be contradicted if there are reasons for not having done this in the past, but I didn't find any issues on the topic.

**Comment by jgm** [comment]
I have no objections to this proposed change.  I didn't even
know about this.

+++ Andrew Dunning [Sep 26 16 06:37 ]:

**Comment by wilx** [comment]
> The main disadvantage I can see is that a word following \slash is not hyphenated, but in the vast majority of cases it would be an improvement. 

This can be remedied by users themselves by overriding `\slash` per answer to "[Help on dealing with items divided with slash](http://tex.stackexchange.com/a/121959/28495):"

```latex
\renewcommand{\slash}{/\penalty\exhyphenpenalty\hspace{0pt}}
```

**Comment by jgm** [comment]
Not sure about this.  Wikibooks says:

> The use of the / character in LaTeX should be restricted to units, such as "mm/year", which should not be broken over multiple lines.

So, sometimes you want `\slash`, but sometimes you don't.  It seems to me that cases like `mm/year` are going to be at least as common as cases like `input/output`, so I'd be reluctant to make all slashes `\slash`.

**Comment by wilx** [comment]
> So, sometimes you want `\slash`, but sometimes you don't. It seems to me that cases like `mm/year` are going to be at least as common as cases like `input/output`, so I'd be reluctant to make all slashes `\slash`.

This is true. I was thinking for a minute that we could be clever and use `\slash` only in context where left of it and right of it are just letters, not numbers, but then it occurred to me that units like `km/s` would fall into this as well and we certainly do not want line breaking there.

I think the solution here is twofold:

- I think that authors should just be aware of this and solve their hyphenation/line breaking issue by inserting ['ZERO WIDTH SPACE' (U+200B)](http://www.fileformat.info/info/unicode/char/200b/index.htm) after the slash in their source text.
- Since the Unicode character does not appear to be recognized by LaTeX itself, not even by XeLaTeX, Pandoc should convert the character to `\hspace{0pt}`.

**Comment by jgm** [comment]
I had no trouble using U+200B with xelatex.  Are you sure?

+++ Václav Haisman [Oct 03 16 07:18 ]:

**Comment by wilx** [comment]
> I had no trouble using U+200B with xelatex.  Are you sure?

You are right. I was wrong. I misremembered. It is non-breaking space (and some other Unicode space characters) that does not seem to work for me as raw character in XeLaTeX.

**Comment by jgm** [comment]
OK, I think I'll close this, then.
