### ISSUE TITLE
Does Pandoc support custom readers?

### ISSUE THREAD

**Issue by jrk** [jgm/pandoc#3192]
The custom writers functionality is great. Is there parallel support for custom readers? I can't seem to find evidence of it. Has this been considered?

**Comment by jgm** [comment]
No.  Of course, if you want to write your own parser from format X to the pandoc AST, you can simply have it emit the JSON representation of the AST that pandoc understands, and pipe its output to `pandoc -f json`.

In the case of writers, the custom writer support made sense because pandoc could handle most of the work of traversing the AST recursively behind the scenes.  In the case of readers (parsers), there's not a lot pandoc can do behind the scenes.

**Comment by jrk** [comment]
Good point! Brain fart on my part. Thanks.
