### ISSUE TITLE
Preserving brackets in image source when converting from markdown to html

### ISSUE THREAD

**Issue by kskyten** [jgm/pandoc#3194]
I'm using pandoc as a preprocessor for python string templates.
Running `echo '![]({img_url}){height=100}' | pandoc -t html` on version 1.12.3.3 produces
```
<p><img src="{img_url}" />{height=100}</p>
```
whereas version 1.18 produces
```
<div class="figure">
<img src="%7Bimg_url%7D" height="100" />

</div>
```
The result I was expecting is
```
<div class="figure">
<img src="{img_url}" height="100" />

</div>
```
I tried to escape the brackets but that did not work either.

**Comment by jgm** [comment]
`%7B` is URL-encoding for `{`, and `%7D` for `}`.  It's recommended to percent-encode these symbols in URLs, so that's what we do.

Easy solution for you is to postprocess pandoc's output with something that replaces `%7B` and `%7D` with the braces.

Or, resolve the template on the Markdown source and then apply pandoc.
