### ISSUE TITLE
top-level-division not replacing chapters with sections in reports

### ISSUE THREAD

**Issue by jbertran** [jgm/pandoc#3197]
The `--top-level-division=section` option seems to be ineffective with the `report` documentclass.
### Sample input

```
%My title
%Me

# Heading 1
# Heading 2
```
### Command line

`pandoc test.md -o test.pdf --top-level-division=section --variable documentclass=report`

Using pandoc 1.18 installed by downloading the Debian package from github.
### Expected

A report with \section as the top level division
### Obtained

A standard report with \chapter as the top level division, \subsection as the next division level (checked by generating latex instead of pdf).

**Comment by jkr** [comment]
confirmed. @tarleb: the issue seems to come form 754-55 in the LaTeX
writer:

~~~{.haskell}
  let topLevelDivision = min (if book then Chapter else Section)
                             (writerTopLevelDivision opts)
~~~

The effect is that if it has a book template, it ignores
`top-level-division` set to `section`. 

The issue, I think, is that it can't differentiate between `Section` as
the default division, and it being explicitly set. The easiest thing to
do would be to make `writerTopLevelDivision` into a `Maybe Division`, and
only set it `Just Section` if that's explicitly set. So 754-- would
become:

~~~{.haskell}
let topLevelDivision = case writerTopLevelDivison opts of
                         Just div -> div
						 Nothing -> if book then Chapter else Section
~~~

plus whatever other fiddling might be necessary. Does this make sense?

**Comment by tarleb** [comment]
I guess either my thinking was along the lines of "filters can do that if needed". @jbertran, you can get the desired behavior by calling this snippet as a filter (save to a file and pass it as the argument of `--filter`):

``` haskell
#!/usr/bin/env runhaskell
import Text.Pandoc.JSON

main :: IO ()
main = toJSONFilter promoteHeader

promoteHeader :: Block -> Block
promoteHeader (Header n attr title) = Header (n + 1) attr title
promoteHeader b = b
```

I agree with you analysis @jkr, I should have implemented it like that in the first place. Changing it now would mean yet another API change.  @jgm, would you object if we were doing that?

**Comment by jgm** [comment]
Another option of course would be to remove the behavior of setting the default to chapters for book classes, and require people to specify this explicitly on the command line.

**Comment by jkr** [comment]
@jgm that would certainly simplify matters, and would keep us from having to worry about edge cases (`\documentclass[article]{memoir}`, for example). But it feels like a regression. My preference, at first blush, would be to keep doing the right-ish thing, and have the switch available in the rare case someone wants something else.

But it's true, my proposed change would require changing a constructor type (`writerTopLevelDivision`) within a  publicly exposed type (`WriterOptions`). Though it wouldn't change cli behavior. So I'm not sure if that would force a minor-number bump.

**Comment by tarleb** [comment]
> that would certainly simplify matters, and would keep us from having to worry about edge cases (\documentclass[article]{memoir}, for example)

The LaTeX template uses the result of these tests, it contains this snippet:

    $if(book-class)$
    \renewcommand\bibname{$biblio-title$}
    $else$
    \renewcommand\refname{$biblio-title$}
    $endif$

We'd likely still have to deal with edge cases.

**Comment by jkr** [comment]
Well, in principle this could be changed to something like

~~~{.haskell}
defField "book-class" (writerTopLevelDivision /= Section)
~~~

so it would only be dependent on the `--top-level-division` argument.

But, as I said, I'd prefer to keep the automagic behavior we have.

**Comment by jgm** [comment]
I've never loved implicitly setting the option based on the template, but you're right that this could break existing workflows.

Switching the option to a Maybe would be possible, but it would definitely require a bump to 1.19 according to the PVP.

**Comment by jkr** [comment]
Hmm... well, I'm not sure how the PVP deals with executables, but changing output on book classes seems like it would be better saved till 1.19 as well. Though I do have some preference for the current behavior, I don't feel all that strongly (I'm usually using a makefile for anything book-length anyway).

John, I don't know how you feel about such a quick version bump for such a relatively minor change. Because we didn't have `--no-chapters` before, the current state of affairs isn't really breaking anything that used to work, so I suppose it isn't urgent. But if we do want to keep it as is for a while, we should probably document that it doesn't work as expected. (The only time you would specify sections is if it weren't already sections, which means that that option won't work most of the time.)

**Comment by jgm** [comment]
Putting out a release is always a bit time-consuming.
A bump in minor version even more so, since packages
that depend on pandoc need to be updated.  But we can
certainly do it.  Nothing says we have to wait a long
time between version bumps.

**Comment by jgm** [comment]
I'm fine with the proposed change, even though it will require a bump to 1.19.

**Comment by tarleb** [comment]
I'll try to get it done over the weekend.
