### ISSUE TITLE
Markdown to rST: Raw <img> tags stripped

### ISSUE THREAD

**Issue by nschloe** [jgm/pandoc#3198]
I have a Markdown document that contains a raw `img` tag for specifying the image size, e.g.,
```
<img src="https://github.com/favicon.ico" width="48">
```
When converting the document to rST, the image tag is stripped off.

Is there way to prevent this?

**Comment by jgm** [comment]
+++ Nico Schlömer [Oct 31 16 03:14 ]:
>   I have a Markdown document that contains a raw img tag for specifying
>   the image size, e.g.,
><img src="https://github.com/favicon.ico" width="48">
>
>   When converting the document to rST, the image tag is stripped off.

This is parsed as raw HTML, and rST doesn't have a way to
include raw HTML in inline text.

If you can use pandoc extensions, use

    ![alt text](https://github.com/favicon.ico){width="48"}

in your Markdown source.

**Comment by nschloe** [comment]
I'm using pandoc to convert a GitHub `README.md` to a `README.rst` to be displayed on [pypi.python.org](https://pypi.python.org), so it seems I cannot use GitHub extensions.

Writing
```
<img src="https://github.com/favicon.ico" width="48">
![alt text](https://github.com/favicon.ico){width="48"}
```
will result in the correct rST file, but display the image twice on Markdown, unscaled the second time.

Is there way to include an image only when translating to rST? I guess could play around with regexs a bit.

**Comment by jgm** [comment]
One option is to generate both the gfm readme and the rst
file from a single, pandoc-markdown source.

Or you could write a pandoc filter that changes
raw HTML images into proper pandoc Images.

But the easiest approach would probably be to use
a regex to preprocess the README.md before sending it
to pandoc.

You might wonder why pandoc doesn't just parse the HTML
and insert an Image node, rather than raw HTML.  This
wouldn't be a good idea in general, because HTML is
more expressive than Markdown and in HTML->Markdown
translations something is often lost.  But perhaps there
could be an option that says, "do your best to convert
all raw HTML to native elements."  This would make sense
when targetting output formats that don't support raw HTML.

Or maybe this is what `markdown-raw_html` should do?

Anyone have thoughts on this?

**Comment by nschloe** [comment]
> Anyone have thoughts on this?

I'd say it's alright if HTML is just stripped – at least by default. Otherwise, the output will depend on the pandoc version, and it's never clear what and what isn't translated.

**Comment by jkr** [comment]
> Anyone have thoughts on this?

I'd vote for avoiding interpreting. Would we try interpret LaTeX as well? I think doing raw pass-through to matching output is best. (as we do it now.)

If I'm wishing, though, what I would like to see is a half-way solution: don't interpret, but match delimiters. So instead of 

`RawInline (Format "html") "<a href="http://.pandoc.org">",Str "Pandoc!",RawInline (Format "html") "</a>"`

something like

`RawSpan (Format "html")  ("<a href="http://.pandoc.org">", "</a>") Str "Pandoc!"`

So if you wanted to do something with all your anchors or imgs or whatever, in either Html or Tex, it would be possible without writing an ad-hoc inline parser.
