### ISSUE TITLE
html reader removes "name=" attribute from <a> tags

### ISSUE THREAD

**Issue by rose00** [jgm/pandoc#3226]
The "name" attribute is apparently dropped from <a> tags by the HTML reader.

~~~~
% echo '<a name="anchor"/>hello world' | /usr/local/bin/pandoc-1.18 -f html -t html
<a href=""></a>hello world
~~~~

Note also that the HTML reader also inserts an "href" attribute even if there wasn't one to start with.

This is not the case in the markdown reader, which apparently copies the tag through unanalyzed:

~~~~
echo '<a name="anchor"/>hello world' | /usr/local/bin/pandoc-1.18 -f markdown -t html
<p><a name="anchor"/>hello world</p>
~~~~

This behavior started around pandoc 1.16.  It makes it hard to accurately read some legacy HTML files.

A workaround is to preprocess the input to pandoc, although in general this requires another full HTML reader besides pandoc:

~~~~
echo '<a name="anchor"/>hello world' | sed '/<a name=/s//<a id=/g' | /usr/local/bin/pandoc-1.18 -f html -t html
<a href="" id="anchor"></a>hello world
~~~~

**Comment by jgm** [comment]
Rather than considering html->html conversions, it's more
useful to isolate the HTML reader:

    % echo '<a name="anchor"/>' | pandoc -f html -t native
    [Plain [Link ("",[],[]) [] ("","")]]

Essentially, all a elements get parsed as links.

We could change that, but the question is what a elements
without href attributes should be parsed as?

I would suggest turning them into Spans (which are native
elements in pandoc, and will render sensibly in many
output formats), rather than RawInline "html" (which
will only render in HTML and Markdown output).  I would
also suggest turning the name attribute into the Span's
identifier.

This would mean that in html->html conversion,

    <a name="anchor"/>

would turn into

    <span id="anchor"/>

but that would be better than what we have now.

**Comment by rose00** [comment]
>> in html->html conversion,
>> 
>> <a name="anchor"/>
>> 
>> would turn into
>> 
>> <span id="anchor"/>
>> 
>> but that would be better than what we have now.
> 

I agree. That would be useful given an IR that centers on MD. 

Perhaps a decoration would help filters:

>> <span orightmltag="a" id="anchor"/>

Or maybe that would just be noise.
