### ISSUE TITLE
<td>&nbsp;</td> becomes Â when converting markdown to html

### ISSUE THREAD

**Issue by Hemken** [jgm/pandoc#3234]
Similar to issue #490.

I have a markdown document with some html in it as well.  When I try to convert this to a full html document, <p>&nbsp;</p> becomes Â.

**Comment by jkr** [comment]
Can't reproduce. What version of pandoc are you using? (Current is 1.18.)

**Comment by Hemken** [comment]
I was using whatever version is included with RStudio (on a Windows OS), but I get the same result since I updated to 1.18.  I get the same result whether I use RStudio or command line pandoc.

Attached is an example.
The html is at
http://www.ssc.wisc.edu/~hemken/SASworkshops/SASWindows/Markdown/SASmdtopics0.html
which was produced with command line pandoc.

and the markdown is again at
http://www.ssc.wisc.edu/~hemken/SASworkshops/SASWindows/Markdown/SASmdtopics0.md

**Comment by jgm** [comment]
Most likely your browser is treating the text as latin1
rather than UTF-8.  Try selecting UTF-8 explicitly (Encoding
in yoru menu).

Better, be sure to use the -s option so you get a standalone
HTML file, which will tell the browser to use UTF-8.

**Comment by Hemken** [comment]
I don’t think so.

Rstudio uses –standalone

And when I add this to my pandoc command line, it certainly changes the header of the html file, but makes no difference in the outcome.



The html file I linked now points to a standalone file.

**Comment by jgm** [comment]
+++ Doug Hemken [Nov 15 16 08:00 ]:
>   I don’t think so.
>   Rstudio uses –standalone
>   And when I add this to my pandoc command line, it certainly changes the
>   header of the html file, but makes no difference in the outcome.
>   The html file I linked now points to a standalone file.

Well, the behavior you're describing is exactly what happens
when a browser is treating the content as latin1 rather than
UTF-8.  Does your HTML header contain a meta tag specifying
UTF-8?  When you view the HTML file in an editor with UTF-8
encoding selected, do you see the correct character?  What
about selecting UTF-8 in your browser?

**Comment by mb21** [comment]
In your HTML template, include this:

    <meta charset="utf-8">

Your existing one doesn't seem to work for me:

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

**Comment by Hemken** [comment]
Firefox is using Unicode by default, I’ve reset Chrome to use UTF-8, and various versions of the page include one or both of these metatags.

The fullest version of the html file is at
http://www.ssc.wisc.edu/~hemken/SASworkshops/SASWindows/Markdown/SASmdtopics.html

and it’s markdown is at
http://www.ssc.wisc.edu/~hemken/SASworkshops/SASWindows/Markdown/SASmdtopics.md

(Note in this version of the file there are some stray characters introduced by the R function knitr(), which produces the markdown file.  But from the markdown, all the &nbsp;  *in the final table* is being converted by pandoc.)

**Comment by jgm** [comment]
OK, when I view it in Safari, I see the strange character instead of a
nonbreaking space.  I go to View->Text Encoding on the menu,
and it says "Default."  I switch this to "UTF-8" -- problem
solved.

Note: there seems to be some garbage in the source md file:

    ï»¿<div class="branch">

The fix was already given in this thread.  Since you're
using an HTML5 doctype, you need a different sort of meta
tag.  If this template is part of RStudio, it may be worth
alerting the authors that they need to use a different meta
tag.

**Comment by jgm** [comment]
To be more specific, instead of

```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
```

for HTML5 you need

```
<meta charset="utf-8">
```

Since the default pandoc HTML5 template has the right meta tag, you must be using a custom template (perhaps indirectly via RStudio).  The template needs to be fixed.
