### ISSUE TITLE
Latex reader: cannot use macro in image path?

### ISSUE THREAD

**Issue by sgdjs** [jgm/pandoc#3236]
For the same Latex document to come out in different "flavors", I put a macro in the image path, like this:

```
\documentclass{report}

\usepackage{graphicx}
\newcommand{\mycolor}{red}

\begin{document}

\includegraphics[width=17cm]{\mycolor /header}
Magnificent \mycolor{} header.

\end{document}
```

So with images named the same in both red and blue folders, changing the value of mycolor once changes all the images of the file.

Pandoc convertion to HTML converts only the second macro correctly: `pandoc source.tex -o index.html --default-image-extension=png` gives

```
<p><img src="\mycolor /header.png" alt="image" width="642" /></p>
<p>Magnificent <span>red</span> header.</p>
```

How to convert such a latex document to HTML with images ? thanks

**Comment by cagix** [comment]
Imho the content/arguments of latex macros (and environments) will be passed to the writer as "raw tex". This works fine for the latex writer, since latex can expand your macro inside the `\includegraphics`. However, the html writer does not understand the tex code inside the `\includegraphics` (i.e. `\mycolor /header` in the given example), so the parameters are not processed by pandoc or the html writer (it is "raw tex").

You could try some kind of pandoc filter, like 

```python
from pandocfilters import toJSONFilter, Str, Image
import re

image = re.compile('\\\\includegraphics.*?\{(.*)\}$')

def textohtml(key, value, format, meta):
    if key == 'RawInline':
        fmt, s = value
        if fmt == "tex":
            m = image.match(s)
            if m:
                return Image([Str("description")], [m.group(1),""])  

if __name__ == "__main__":
    toJSONFilter(textohtml)
```

(not tested, should work for pandocfilters < 1.3.0 (`Image` hat got some more parameters in pandocfilters >= 1.3.0)).

**Comment by sgdjs** [comment]
Hello, thanks for the answer. I have not used filters before but I'll test your solution when I can. I suppose this issue can be closed if it's the best way.
Thanks again

**Comment by cagix** [comment]
Hmmm, it seems, I had an "out of coffee exception" without proper exception handler in place ;(

The proposed solution will not solve your problem completely, since the argument of `\includegraphics` is still not processed, i.e. you would still end up in the html with `<img src="\mycolor /header.png">`. The filter needs to process the `m.group(1)` before returning the image ...
