### ISSUE TITLE
pipe_tables doesn't seem to be working (docx->md)

### ISSUE THREAD

**Issue by hassanshaikley** [jgm/pandoc#3240]
I created a doc in google docs and want to convert it to markdown with pipe tables, and this gets outputted.

These arne't pipe_tables, though : (

` pandoc -f docx docxTest\ \(1\).docx -t markdown+pipe_tables --extract-media=media`

```
  table column 1   table colum 2   3
  ---------------- --------------- -------------
  row 2            row 2.2         row 2.3
  Another row      another row     another orw

```

**Comment by jgm** [comment]
`+pipe_tables` just means pipe tables CAN be used.
(And it's redundant, since they are already included
in 'markdown'.)

Since other table formats are also enabled, pandoc may
use one of them.

You can disable the other table formats if you ONLY want
pipe tables.  (Or try `-t markdown_github`, which does
this.)

+++ Hassan Shaikley [Nov 17 16 12:19 ]:
