### ISSUE TITLE
Org writer: wrong indentation of properties block

### ISSUE THREAD

**Issue by ngirard** [jgm/pandoc#3245]
When typing either
`echo "<h2>Title</h2>" | pandoc -f html -t org`
or
`echo "** Title" | pandoc -f org -t org`
Pandoc produces
```org
** Title
   :PROPERTIES:
   :CUSTOM_ID: title
   :END:
```

The properties block shouldn't be aligned to the title but rather start at column 0:
```org
** Title
:PROPERTIES:
:CUSTOM_ID: title
:END:
```

I'm using a fresh version of Pandoc built from trunk.

**Comment by tarleb** [comment]
What makes you think this is wrong?  If you run `org-set-property` (<kbd>C-c C-x p</kbd>), the `PROPERTIES` block is inserted indented.  Pandoc simply mimics this behavior.  Any reason why we should derive from this?

**Comment by tarleb** [comment]
I'm closing this for now.  Feel free to reopen if there are pressing reasons to change the current behavior.

If you want to change this for your installation, you can delete `nest (level + 1)` from line 190 in `src/Text/Pandoc/Writers/Org.hs` and recompile.  That will cause the properties block to be emitted unindented.

**Comment by ivanhjc** [comment]
@tarleb 

> I'm closing this for now. Feel free to reopen if there are pressing reasons to change the current behavior.
> 
> If you want to change this for your installation, you can delete `nest (level + 1)` from line 190 in `src/Text/Pandoc/Writers/Org.hs` and recompile. That will cause the properties block to be emitted unindented.

Is this an option now? Because if the properties drawers are inserted indented and `org-indent-mode` is turned on, they appear unindented with the headings. For example, the following snippet

```
* Test
  :PROPERTIES:
  :CUSTOM_ID: ddd
  :END:
```

will be displayed like this when `org-indent-mode` is turned on:

```
* Test
    :PROPERTIES:
    :CUSTOM_ID: ddd
    :END:
```

I'm currently using pandoc 2.14.0.1 and org 9.3.

**Comment by ivanhjc** [comment]
I found a solution which is to run `org-indent-region` after conversion.

**Comment by hpfr** [comment]
> What makes you think this is wrong? If you run org-set-property (C-c C-x p), the PROPERTIES block is inserted indented. Pandoc simply mimics this behavior. Any reason why we should deviate from this?

@tarleb It looks like this behavior has been fixed in Org. Nowadays drawers are not indented by `org-set-property` (and indeed `org-indent-region` now corrects Pandoc's indentation), so this issue is probably worth reopening. Could Pandoc's default behavior be changed to match Org's new default behavior?

**Comment by jgm** [comment]
I agree.  I just tried org-indent-region and, although the :PROPERTIES: did *look* indented when viewed with org-mode, it isn't actually indented (as you can see if you look at the file with less).
I'll change the writer so it doesn't insert this indentation.

**Comment by tarleb** [comment]
:+1: staying close to the default org behavior seems best. I'll make the changes.
