### ISSUE TITLE
'<' is not encoded when convert markdown to html

### ISSUE THREAD

**Issue by cnblogs-dudu** [jgm/pandoc#3257]
Use command line: `pandoc -f markdown_github -t html`
Input markdown text: https://gist.github.com/cnblogs-dudu/c9fde76518998e5386f6e66bd89b281a
<img width="228" alt="screen shot 2016-11-26 at 17 32 39" src="https://cloud.githubusercontent.com/assets/3196961/20639450/b2b707f8-b3fe-11e6-82a7-5779c9ddbd16.png">
Get the following html when use pandoc 1.17.2 or pandoc 1.18.
```html
<p>i（i<j)

```javascript
function binarySearch1(a, target) {
  while(start <= end) {
    var mid = ~~((start + end) >&gt; 1);<br />
}<br />
}<br />
```</p>
```
Expect the following right html. It works on pandoc 1.17.
```
<p>i（i&lt;j)</p>
<div class="sourceCode"><pre class="sourceCode javascript"><code class="sourceCode javascript"><span class="kw">function</span> <span class="at">binarySearch1</span>(a<span class="op">,</span> target) <span class="op">{</span>
  <span class="cf">while</span>(start <span class="op">&lt;=</span> end) <span class="op">{</span>
    <span class="kw">var</span> mid <span class="op">=</span> <span class="op">~~</span>((start <span class="op">+</span> end) <span class="op">&gt;&gt;</span> <span class="dv">1</span>)<span class="op">;</span>    
  <span class="op">}</span>
<span class="op">}</span></code></pre></div>
```

**Comment by jgm** [comment]
I'm pretty sure this is because of commit
773bbb8fc73a3b6598188dbae64a841eb6680b38

We used to fail if the HTML tokenizer yielded any warnings.
This commit changed this...in fact we got lots of complaints
about pandoc's failure to parse malformed HTML.

Unfortunately the same change that allows pandoc's HTML
reader to accept things like unescaped `&` also allow
your case.

So this needs more thought.

**Comment by jgm** [comment]
Note:  I recommend that if you are including math, you
either backslash-escape the `<` sign or, better, use
tex math.

    i\<j and j\>k

or

    $i<j \text{and} j>k$

Otherwise there's always a risk of interpretation as HTML,
and this would remain even if we made the parser stricter.
E.g. in

    x<a and y>z

we parse as an "a" element with boolean attributes "and" and
"y".  (Yes, those aren't official HTML attributes, but we
don't validate tags and attributes, because we want pandoc
to be flexible enough to accept custom elements, docbook,
etc.)
