### ISSUE TITLE
AST Documentation?

### ISSUE THREAD

**Issue by hassanshaikley** [jgm/pandoc#3262]
Hey!

I am looking to build a to Pandoc AST (JSON) converter in Node. 

Is there any documentation on Pandoc AST? I have been unable to find any.

Thanks!

**Comment by jgm** [comment]
Have you seen
https://github.com/mvhenderson/pandoc-filter-node

No, there's no real documentation (mainly because,
originally, we just relied on automatic serialization and
deserialization in Haskell filters, and it didn't really
matter what the JSON looked like).  You can study one
of the existing filter libraries, e.g. pandocfilters
or panflute.  Or use `pandoc -t json` and study its
output.  The output is pretty regular and predictable
from the types in Text.Pandoc.Definition
once you see the patterns.

Other thing to be aware of is that the format changed
in 1.18 (see the 1.18 changelog for details).



+++ Hassan Shaikley [Nov 28 16 18:40 ]:

**Comment by mb21** [comment]
here the link to [Text.Pandoc.Definition](https://github.com/jgm/pandoc-types/blob/master/Text/Pandoc/Definition.hs#L94) btw...

**Comment by hassanshaikley** [comment]
Do you have any examples on iterating through nodes? : )

**Comment by mb21** [comment]
check out <http://pandoc.org/scripting.html <http://pandoc.org/scripting.html>> if you haven’t already...

**Comment by ickc** [comment]
I'm suggesting to consider this issue a special case of #3288 and close this one.
