### ISSUE TITLE
Config file for customizing output

### ISSUE THREAD

**Issue by stomar** [jgm/pandoc#327]
There should be a feature for customizing the output writer's behavior (a command line option specifying a configuration file).

This would be very helpful for documents in foreign languages (e.g. in connection with the `--smart` option and the style for the used "curly" quotes). It would also be useful for authors who need to meet certain styling conventions, possibly different for different documents.

Some things that should be customizable:
- general
  - table of contents entry for the epub cover image (default: "Title Page")
- with the `--smart` option
  - curly quotes (opening/closing/inner/outer separately)
  - dashes (substitution of `--` and `---`)

Best regards,
Marcus

**Comment by nichtich** [comment]
This issue seems to mix two feature requests:

* additional options to configure writers, especially for internationalization (e.g. headings for TOC, footnotes and bibliography...)
* support of setting such options in a config file

The former could be implemented by configurable extensions (see below).

The latter was also discussed before in #2069. I would welcome a way to read *all* pandoc options (as listed with `pandoc --help`) from a config file. By now only some of these options can be set as document metadata (option `-M` / `--metadata`) but others such as `pdf-engine`, `self-contained`...  not. The requested config file format could look like this:

~~~
---
pdf-engine: xelatex
self-contained: true
metadata:  
  key: value...
variable:
  key: value...
extension:
  foobar:
    Emph:
      start: _
      end: _
---
~~~

Example usage:

* `pandoc -t html` (adds `--self-contained` from config file)
* `pandoc -t markdown+foobar`

**Comment by mb21** [comment]
> This issue seems to mix two feature requests:

Agreed.

> * additional options to configure writers, especially for internationalization (e.g. headings for TOC, footnotes and bibliography...)

There has been progress on this: see [Translations.hs](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Translations.hs) and `--abbreviations` (https://github.com/jgm/pandoc/commit/c93d069d49fcf724fc59405b82587d608724c2c6) for example. For additional suggestions, please open more (and look for) more specific issues.

> * support of setting such options in a config file

see https://github.com/jgm/pandoc/issues/4627
