### ISSUE TITLE
Man writer doesn't escape periods at the beginning of lines

### ISSUE THREAD

**Issue by mkllnk** [jgm/pandoc#3270]
I have the following example. Source markdown:
```markdown
It saves the deployed state by uploading the SHA1 hash in the .git-ftp.log file.
There is no need for Git to be installed on the remote host.
```
Converted to groff man:
```groff
.PP
It saves the deployed state by uploading the SHA1 hash in the
.git\-ftp.log file.
There is no need for Git to be installed on the remote host.
```
https://pandoc.org/try/?text=It+saves+the+deployed+state+by+uploading+the+SHA1+hash+in+the+.git-ftp.log+file.%0AThere+is+no+need+for+Git+to+be+installed+on+the+remote+host.%0A%0A&from=markdown&to=man

The automated line breaks put `.git\-ftp.log` at the beginning of a new line. It starts with a dot and man will discard the whole line.

**Comment by jgm** [comment]
The current architecture makes it impossible to escape things conditionally on their position in the line, since the line breaking is delegated to the pretty-printer.

We used to escape all periods, but that made the output incredibly ugly, so we stopped, in the belief that this kind of thing would be very rare.

Note that it would be good practice to put `.git-ftp.log` in code backticks, and then things should be fine in your man output.

**Comment by jgm** [comment]
+++ Maikel [Dec 03 16 14:52 ]:
>   And the pretty-printer is not groff aware? Sounds like a false
>   assumption that it can introduce newlines wherever it's pretty without
>   understanding the language it's formatting.

Indeed.  We use a generic prettyprinter for many of the
textual output formats, and every once and a while this
sort of thing happens (see also #3276 which just came in).

Obviously we should think about how to do it better,
but it would require some larger architectural changes,
not a simple fix.

**Comment by mkllnk** [comment]
Wow. Well done on fixing it.
