### ISSUE TITLE
\tag in LaTeX not being converted to PDF

### ISSUE THREAD

**Issue by sn0wyfall** [jgm/pandoc#3281]
I have a .tex file with the normal, unaltered pandoc preamble (the one which is inserted into the .tex file when, for example, a .md file is converted into .tex). I won't paste it in here as it is too long, but I hope you know what I mean.

Here is what I have for the body in the .tex file:

```
\begin{document}
\begin{align*}
a &= b \tag{Definition}\\
\end{align*}
\end{document}
```

When I open this .tex file in TeXmaker and compile it, it compiles it into a PDF without any problems. However, I get this error if I try converting the .tex to a .pdf from pandoc:

```
! Package amsmath Error: \tag not allowed here.

See the amsmath package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.60 a &= b \tag
```

This is on version 1.19 of pandoc.

**Comment by jgm** [comment]
When pandoc converts this to tex (as you can see using
--verbose option), it turns into

    \[\begin{aligned}
        a &= b \tag{Definition}\\\end{aligned}\]

which is the source of the problem.

Why does it do this, you might ask?  Why not just leave it as raw tex?

If we parsed it as raw TeX, it would not appear as math in non-TeX output
formats (such as docx) So we have reason to put it into a Math element,
changing `align` to `aligned` (since the former cannot go in math mode)

You might ask: why not do this transformation only when the output
format is non-tex?

Answer:  Pandoc's readers and writers function completely separately.
The reader doesn't know what writer will be used.  Indeed, sometimes
json is written out, processed by a filter, and read in by a different
pandoc instance.

+++ sn0wyfall [Dec 05 16 12:31 ]:

**Comment by sn0wyfall** [comment]
Great explanation, thank you. But I can't see the problem here. 

```
\[\begin{aligned}
a &= b \tag{Definition}\\\end{aligned}\]
```

seems to be rendered in MathJax just fine, so it doesn't look like there are any problems there. So if pandoc converted it to the code above, there shouldn't be an error, right?

Ninja edit: I see, it doesn't seem like it renders in when I put it in as TeX. That's the problem you were talking about, I guess :<

**Comment by sn0wyfall** [comment]
Just saw [this](https://github.com/jgm/pandoc/issues/1938P) and looks like there's no real solution. Well, I guess that answers it then.
