### ISSUE TITLE
TikiWiki reader [patch]

### ISSUE THREAD

**Issue by rlpowell** [jgm/pandoc#3284]
I turned TWiki.hs plus a bunch of work into a passable Reader for TikiWiki documents; you're welcome to do anything you like with it (including nothing ^_^ ).  It's at https://github.com/rlpowell/hblog/blob/master/lib/Text/Pandoc/Readers/TikiWiki.hs

The project overall is MIT license, but TWiki.hs is GPLv2, so I guess TikiWiki.hs is too.

**Comment by jgm** [comment]
Thank you.  I'm happy to consider integrating this, but at minimum we'd need some tests.
See `tests/twiki-reader.twiki` and `tests/twiki-reader.native`; all that would be needed would be files corresponding to these + a small change in `tests/Tests/Old.hs`.

**Comment by mb21** [comment]
@rlpowell I'm not familiar with the differences between TWiki and TikiWiki syntax... are they very different? If not, it would probably make more sense to modify pandoc's existing [TWiki reader](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/TWiki.hs) to take a flag into account that results in it reading TikiWiki syntax...

**Comment by ctrueden** [comment]
Thanks @rlpowel for working on this. I need to do a one-time conversion of old tikiwiki content to another format (preferably Markdown), so I starting trying to polish this into a PR. But I am no Haskell programmer, and ran into various build errors in `TikiWiki.hs`. My efforts can be seen [on this branch](https://github.com/jgm/pandoc/compare/master...ctrueden:tikiwiki). I am now stuck on the errors:
```
.../pandoc/src/Text/Pandoc/Readers/TikiWiki.hs:42:23: error:
    Variable not in scope: stateWarnings :: ParserState -> t

.../pandoc/src/Text/Pandoc/Readers/TikiWiki.hs:79:19: error:
    Variable not in scope: readerTrace :: ReaderOptions -> Bool
```

I fear I will not be able to push this work any further, since I do not understand Haskell's indentation rules. But I wanted to post what I had done so far here, in case anyone else cares enough to comment/suggest/continue.

**Comment by rlpowell** [comment]
@mb21 They are considerably different; TWiki is what I started with but the changes are substantial.

**Comment by rlpowell** [comment]
Welllll, better late than never, right??

https://github.com/jgm/pandoc/pull/3800

@ctrueden I wrote the original against an older version of Pandoc, but you were trying to make a PR against master; it turns out there were several significant API changes internal to Pandoc in the meantime, and the re-jiggering was substantial and required a pretty thorough understanding of Haskell.  In other words: don't feel bad that you couldn't make the PR yourself!

**Comment by rlpowell** [comment]
@ctrueden It's merged into pandoc mainline now.  Closing this out.
