### ISSUE TITLE
Add a manual: Using the pandoc API

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#3289]
Topics:

- basic use of pandoc as a library
- using Builder to create documents programatically
- using Walk and generics to modify the AST
- writing filters in Haskell
- error handling (PandocError) and warnings (logging)

This should wait until pandoc 2.0 is released with the new API.

**Comment by ickc** [comment]
> This should wait until pandoc 2.0 is released with the new API.

Setting a v2.0 milestone?

**Comment by jgm** [comment]
There should be a note somewhere that pandoc's Markdown reader (and some other readers) can exhibit exponential performance in pathological cases; hence, we advise anyone using this module in a web application or other application that receives untrusted input to put it under a timeout to avoid DOS attacks.

**Comment by dbaynard** [comment]
Are options passed to filters? It seems like they are passed to lua filters, but not (say) haskell filters, even if the haskell filter imports the pandoc api.

**Comment by jgm** [comment]
No, reader and writer options aren't passed to filters.  I can see how that makes it difficult for an "include" filter.

**Comment by ickc** [comment]
> I can see how that makes it difficult for an "include" filter.

It is a problem for pantable too (and any filters that read something containing markdown syntax. e.g. any of the csv filters out there). This problem is kind of unique to markdown because markdown extensions can be customized.

There's another pandoc arg unrelated to markdown extensions that is needed in another filter I want to rewrite (pandoc-amsthm): the `--top-level-division`, which affects the numbering used in amsthm.

So in general it seems hard to predict which pandoc arg could be needed from a filter. So it will be nice to have some way to pass all user-specified pandoc args to the filter and let it decide. Backward compatibility might be impossible here, but may be we can break it a bit in pandoc 2.0? (some people has suggested to put the args into the JSON.)

**Comment by jgm** [comment]
I've added To/FromJSON instances for ReaderOptions and the filters are now run in an environment with a JSON-encoded version of the ReaderOptions in PANDOC_READER_OPTIONS.
Not exactly convenient, but accessible.

**Comment by dbaynard** [comment]
That may be useful; I'm not quite able to judge right now. But one thing I did notice is the reader options and the writer options are set from the supplied options in `convertWithOpts`. The API would be far more pleasant if these were factored out, and available as separate functions, so one could construct those as necessary.

The difficulty with an 'include' filter seems to be pandoc must be called recursively, but the suitable function within `Text.Pandoc.App`, `convertWithOpts`, does too much — it combines option processing with running the effects, and then returns `()`.

My personal use case for an include filter concerns writing a thesis; it is useful to be able to produce standalone chapters and a combined document without having to change any files. One issue I've recently encountered is `pandoc-citeproc` being run when I don't want it to, because the individual chapters have a 'bibliography' field in their yaml metadata; this is a special case in `convertWithOpts`.

Taken together, it seems one useful action would be to refactor `convertWithOpts :: Opt -> IO Pandoc`. It's straightforward to factor into multiple functions, which I've done in one of the branches on my fork (the code is minimal with `RecordWildCards` and I did some unnecessary things with type families as an experiment). The branch introduces a data type corresponding to all the internal options needed (e.g. `filters'`).

For the include filter, I've ended up with a function, `toAST :: Opt -> IO Pandoc` which is like `convertWithOpts` but doesn't write the input to a file; it can therefore be made into a filter, though the whole thing has to be written as a wrapper to the API. And the other boundaries make it trivial to remove citeproc from the list of filters manually as `filters'` can be modified before filters are run.

I wonder whether with a similar change, pandoc could take an option to run recursively (presumably with a limit to prevent infinite recursion on pathological input) meaning no need to encode an 'include' filter natively, but such filters will no longer depend on pandoc itself. Though I haven't given this much thought.

In any case, whatever happens, hopefully this discussion will provide a useful guide to the limits of filters and the API, and perhaps some good examples of what is possible.

**Comment by ickc** [comment]
@dbaynard, 

> My personal use case for an include filter concerns writing a thesis; it is useful to be able to produce standalone chapters and a combined document without having to change any files.

Did you try other means to achieve this? e.g. I've explored various pandoc-include filters, but in the end find that using a makefile is easier to achieve what you described. There are some other cases that "pandoc-include" is more natural (such as similar to using templates and CMS), but if your documents in the end is just a catenation of a numbers of files, then makefile is easier and allow you to have more control. e.g. I have a setup that produces different variants from the same sources (e.g. one document has file 1, 3 and another has file 2, 3) where in this case using a makefile plus a couple of stand UNIX tools will be easier than to type different "master" documents that include the sources. (I can share the makefile if you want to take a look.)

And then I think that the use of include is often more like using "templates", like how one would use pandoc's template system, of those generating a website. So to separate includes using some kind of "template language" seems to be more natural than embedding this into the pandoc's markdown language. In fact, as far as I understand, the other markdown variants that do support include (MultiMarkdown, and the markdown editor Marked2) also process the includes as a preprocessor, not all that different from how a template language is used on top of the underlying markup language.

By the way, @jgm, speaking of the template language used in pandoc (which is by the way in the topic of #3288 to better document it), I recently am thinking about using pandoc templates in a "non-standard" use, i.e. rather than for generating a single document, but for something like a CMS. But this has some complications (similar to the issues mentioned when I asked about "header-includes" and recursively resolving templates) and limitations. Would you consider to expand the template language to include more logic, and perhaps has an include there (hence solving the "pandoc-include" problem). And then may be having 2 "layers" of template language / levels to resolve the templates, so that one is for "internal use" like the usual pandoc templates, and another is for building documents, like the header-includes, and a CMS-like template system?

**Comment by jgm** [comment]
+++ dbaynard [Sep 15 17 18:08 ]:
>   That may be useful; I'm not quite able to judge right now. But one
>   thing I did notice is the reader options and the writer options are set
>   from the supplied options in convertWithOpts. The API would be far more
>   pleasant if these were factored out, and available as separate
>   functions, so one could construct those as necessary.
>
>   The difficulty with an 'include' filter seems to be pandoc must be
>   called recursively, but the suitable function within Text.Pandoc.App,
>   convertWithOpts, does too much — it combines option processing with
>   running the effects, and then returns ().

convertWithOpts is really only intended for someone who
wants to produce a front-end for pandoc.  For your purposes,
you should use the other API functions: readMarkdown,
writeHtml, etc., and Reader/WriterOptions.

>   My personal use case for an include filter concerns writing a thesis;
>   it is useful to be able to produce standalone chapters and a combined
>   document without having to change any files. One issue I've recently
>   encountered is pandoc-citeproc being run when I don't want it to,
>   because the individual chapters have a 'bibliography' field in their
>   yaml metadata; this is a special case in convertWithOpts.

See above. Don't use convertWithOpts, use readMarkdown.

>   I wonder whether with a similar change, pandoc could take an option to
>   run recursively (presumably with a limit to prevent infinite recursion
>   on pathological input) meaning no need to encode an 'include' filter
>   natively, but such filters will no longer depend on pandoc itself.
>   Though I haven't given this much thought.

The RST reader already has an include function (including a
check to avoid infinite recursion).  In a filter, you could
increment a special field in metadata to keep track of
recursion depth, I suppose.

**Comment by jgm** [comment]
+++ ickc [Sep 16 17 03:38 ]:
>   By the way, [2]@jgm, speaking of the template language used in pandoc
>   (which is by the way in the topic of [3]#3288 to better document it), I
>   recently am thinking about using pandoc templates in a "non-standard"
>   use, i.e. rather than for generating a single document, but for
>   something like a CMS. But this has some complications (similar to the
>   issues mentioned when I asked about "header-includes" and recursively
>   resolving templates) and limitations. Would you consider to expand the
>   template language to include more logic, and perhaps has an include
>   there (hence solving the "pandoc-include" problem). And then may be

See #3697.
