### ISSUE TITLE
Parse certain TeX environments as RawInline instead of RawBlock?

### ISSUE THREAD

**Issue by aoles** [jgm/pandoc#3309]
The way math blocks are output in HTML varies widely depending on how they are input in the markdown source. In particular, display math entered as a LaTeX environment is not enclosed in \<p\> ... \</p\> tags. But even more surprisingly, paragraphs containing such math blocks fail to render as paragraphs, which seems like a bug to me. This causes problems when applying formatting to paragraphs.

Consider the following sample file illustrating the issue.

```
<style>
p {
padding-left: 100px;
background: #eee;
}
</style>

This paragraph and the following equation are entered in separate paragraphs and indented
as expected.

$$
x = 1
$$

However, equations entered as LaTeX environments are not enclosed in \<p\> ... \</p\> tags.

\begin{equation}
x = 2
\end{equation}

This paragraph containing an equation is typeset properly,
$$
x = 3
$$

unlike this one which fails to be enclosed in a \<p\> tag.
\begin{equation}
x = 4
\end{equation}
```

which when rendered with `pandoc -s --mathjax math_issue.md -o math_issue.html` displays as

![screen](https://cloud.githubusercontent.com/assets/6545356/21138447/5e7c5872-c12e-11e6-8b61-36a5171aa484.png)

See below for the relevant part of the HTML source.
```html
<p>This paragraph and the following equation are entered in separate paragraphs and indented as expected.</p>
<p><span class="math display">\[
x = 1
\]</span></p>
<p>However, equations entered as LaTeX environments are not enclosed in &lt;p&gt; ... &lt;/p&gt; tags.</p>
<span class="math display">\[\begin{equation}
x = 2
\end{equation}\]</span>
<p>This paragraph containing an equation is typeset properly, <span class="math display">\[
x = 3
\]</span></p>
unlike this one which fails to be enclosed in a &lt;p&gt; tag.
<span class="math display">\[\begin{equation}
x = 4
\end{equation}\]</span>
```

**Comment by mb21** [comment]
Not sure whether there's a good reason inline raw TeX is not wrapped in paragraphs (probably there is), but I'd recommend changing your CSS to:

    p, span.math {
      display: block;
      padding-left: 100px;
      background: #eee;
    }

and inserting a blank line between your paragraphs and `\begin{equation}`...

**Comment by aoles** [comment]
Thank you @mb21 for your suggestion! However, it doesn't really solve the problem because `span.math` is used both for display and inline math, such as
```
How about $y = x + 1$?
```
What I would like to achieve is to change the styling of display math without affecting inline math.

**Comment by mb21** [comment]
Then use `span.display`... (feel free to have a look at the generated html)

**Comment by aoles** [comment]
Sorry, I missed that!

Anyway, I find the fact that paragraphs containing `\begin{equation}...\end{equation}` don't render as HTML paragraphs somehow unexpected.

**MD source**
```
A paragraph.

Shouldn't this be a paragraph as well?
\begin{equation}
y = x
\end{equation}

Another paragraph.
```
**HTML output**
```html
<p>A paragraph.</p>
Shouldn't this be a paragraph as well?
<span class="math display">\[\begin{equation}
y = x
\end{equation}\]</span>
<p>Another paragraph.</p>
```

**Comment by jgm** [comment]
+++ Mauro Bieg [Dec 14 16 10:05 ]:
>   Not sure whether there's a good reason inline raw TeX is not wrapped in
>   paragraphs (probably there is),

TeX environments are parsed as RawBlock (Format "tex")
rather than RawInline (Format "tex"), which is why they
don't go in p tags.

Maybe this needs to be reconsidered for certain
environments, such as this, "math", etc.

**Comment by Selbosh** [comment]
I would like to add to his, from the perspective of converting to LaTeX/PDF output.

As far as I am concerned, all LaTeX environments should be parsed as RawInline unless surrounded by blank spaces. I don't understand why there is even a distinction. Otherwise we get the situation where

`pandoc mwe.md -f markdown -t latex`

converts this Markdown

```latex
Lorem ipsum dolor sit amet,
\begin{equation}
E = mc^2,
\end{equation}
consectetur adipiscing elit.
```
into this LaTeX
```latex
Lorem ipsum dolor sit amet,

\begin{equation}
E = mc^2,
\end{equation}

consectetur adipiscing elit.
```
which is **not** the same thing in LaTeX at all. By turning one paragraph into three, extra vertical spacing and indents are added which we didn't ask for. See [this issue](https://github.com/rstudio/bookdown/issues/358).

On the forums, some people have suggested the following non-solutions for LaTeX output:

1. Use `\noindent` on the text after the `\end` tag. This does not fix vertical spacing, so not a solution.
1. [Use an `\empty{}` tag](http://stackoverflow.com/questions/25952137/pandoc-adds-extra-paragraph-breaks) around the environment. This might seem to work but is extremely fragile: it stops Markdown inside being parsed, and the content inside is omitted completely when converting to HTML. Not a solution.
1. Change your LaTeX template's `\abovedisplayskip` and `\belowdisplayskip` length, say, to reduce the unwanted extra spacing around block environments. Not a solution — this muddies the waters between semantics and presentation. It will appear to work for some environments and then break others. And it does nothing about indents etc.

See also
- [Issue #2171](https://github.com/jgm/pandoc/issues/2171)
- [A related discussion about inconsistency between raw HTML and raw LaTeX](https://groups.google.com/forum/#!topic/pandoc-discuss/P3fV_0jw9-U)
