### ISSUE TITLE
Internal anchors not preserved when converting HTML to RST

### ISSUE THREAD

**Issue by AlmightyOatmeal** [jgm/pandoc#3319]
When one has an anchor in HTML like:

```
<a href="#tacocat">tacocat</a>
...
<a name="tacocat"/>
```

The source link gets created:

```
`gauge.cluster.active-primary-shards <#gauge.cluster.active-primary-shards>`__   
...
.. _tacocat: #tacocat
```

But there is one very important thing missing... The reStructuredText anchor!

I see:

```
Tacocat
~~~~~~~
...
```

But not

```
.. tacocat:

Tacocat
~~~~~~~
...
```

Also, there should be a `:ref:` link when referencing RST internal anchors as well (http://www.sphinx-doc.org/en/1.5.1/markup/inline.html#ref-role)

Full pandoc string:
```
$ pandoc --from=html --to=rst --smart --normalize --reference-links --output=test.rst test.html
```

**Comment by AlmightyOatmeal** [comment]
Hello? Bueller?

**Comment by jgm** [comment]
Pandoc parses the HTML
```
<a name="tacocat"/>
```
as a span with id "tacocat":
```
[Plain [Span ("tacocat",[],[]) []]]
```
The question is, what is the RST writer supposed to do with this?
What you suggest,
```
.. tacocat:
```
won't work in general because  a span might occur in the middle of other span-level text.

We could special-case it when there's just the one span in a Para or Plain container, i suppose, but that's a bit klutzy.

**Comment by AlmightyOatmeal** [comment]
@jgm,

That sounds like incorrect HTML parsing as internal anchors are legitimate HTML and there is no 'id' tag so why would it be parsed as a span with an "id" value of the "name" attribute? To me that sounds like incorrect parsing of HTML by Pandoc or did I misread what you meant?

**Comment by jgm** [comment]
Pandoc's internal document model has Span and Div elements
with an id attribute, so these are the closest things to
an anchor with a name that we have to parse them into.

+++ Jamie Ivanov [Jan 09 17 09:15 ]:

**Comment by AlmightyOatmeal** [comment]
@jgm,

Okay but I don't see how that correlates here considering normal anchors work just fine. There is no need to convert them to div or span tags as that is not what anchors are whether internal or external. It should be trivial to add support for internal anchors specific to reStructuredText as I've given an example. If you would like more examples, I would be more than willing to share more information.

**Comment by jgm** [comment]
I think you're missing something important about how pandoc
works.  It doesn't directly convert HTML -> RST.  Instead,
it converts HTML to an internal document model (Pandoc AST),
then  it converts that to RST.  That's how we can support
m x n conversions with m readers and n writers.

Because of this architecture, we can't simply specify the
intended RST equivalent; we need to find a close equivalent
in the Pandoc AST.

+++ Jamie Ivanov [Jan 10 17 14:44 ]:

**Comment by AlmightyOatmeal** [comment]
@jgm,

Oh, that makes sense. With that in mind, is this something that can be accomplished by Pandoc or am I better-off writing my own?

(I apologize if the tone of the question came off sounding harsh as that wasn't the intent; there is no malice intended in my words)

**Comment by mb21** [comment]
@AlmightyOatmeal you can always write a [pandoc filter](http://pandoc.org/scripting.html) to adjust the AST to your needs...

**Comment by jgm** [comment]
Well, as I said, it's certainly possible for pandoc
to generate an anchor (with code changes); see my original
comment.

One possible approach would be to look for Span with id
inside a Para or Plain element, and print the
RST anchors before the paragraph.

In the short term you could write a pandoc filter that would
find AST elements matching

    [Plain [Span (ident,[],[]) []]] | not (null ident)

and replace them with

    RawBlock (Format "rst") (".. " ++ ident ++ ":")

See https://pandoc.org/scripting.html
