### ISSUE TITLE
Large tables with markdown output and wrap=none 

### ISSUE THREAD

**Issue by widdma** [jgm/pandoc#3348]
pandoc version: 1.19.1 

arguments: `-t markdown --wrap=none`

input:

```
  ----- ------------------------------------------------
    foo bar

    foo this is a long
        line of text
  ----- ------------------------------------------------
```

output:

```
  ----------------------------- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            foo bar
                            foo this is a long line of text
  ----------------------------- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


```

expected output:

```
  ----- -----------------------------
    foo bar

    foo this is a long line of text
  ----- -----------------------------
```

I believe this is flawed since a line 270 characters wide is produced. Others can be larger. 

Arguably, a second problem with this output is that the blank line between rows is removed. This means the the table will now be handled with the `simple_tables` extension rather than the `multiline_tables` one. It also means the transformation isn't idempotent, ie

    pandoc -t markdown --wrap=none test.md
    pandoc -t markdown --wrap=none test.md | pandoc -t markdown --wrap=none

are different. The latter gives
```
  ----- -----------------------------
    foo bar
    foo this is a long line of text
  ----- -----------------------------

```

That said, I don't think it's clear what the correct behaviour with tables should be with `--wrap=none`.

**Comment by jgm** [comment]
The following change seems to fix this:
``` diff
diff --git a/src/Text/Pandoc/Writers/Markdown.hs b/src/Text/Pandoc/Writers/Markdown.hs
index e3bb3ee..cd49214 100644
--- a/src/Text/Pandoc/Writers/Markdown.hs
+++ b/src/Text/Pandoc/Writers/Markdown.hs
@@ -612,7 +612,7 @@ pandocTable opts headless aligns widths rawHeaders rawRows = do
   let noWordWrapWidth
         | writerWrapText opts == WrapAuto
                               = fromIntegral $ maximum (map minNumChars columns)
-        | otherwise           = fromIntegral $ maximum (map    numChars columns)
+        | otherwise           = fromIntegral $ maximum (map minNumChars columns)
   let relWidth w = floor $ max (fromIntegral (writerColumns opts) * w)
                                (noWordWrapWidth * w / minimum widths)
   let widthsInChars
```
though it may introduce other issues.

@bjpe could you look into this, since this comes from your commit 2761fecd57203c7dcdb30d72e194386942e62251?  I wasn't sure what the logic was here, but clearly it's not working for this case.

**Comment by bjpe** [comment]
@jgm I think the issue here was to both guarantee that no line is wrapped *and* that the relative column widths are retained. However, the produced output looks strange, and I'll have a deeper look shortly.

**Comment by bjpe** [comment]
Hi @jgm, unfortunately, I did not find the time to solve this problem yet, but at least I can provide an analysis. Using some trace output, I discovered the following:

- The relative widths of the columns are computer as `[8.333333333333333e-2,0.6666666666666666]`, thus 1/12 and 2/3 = 8/12. Currently, I do not know why they don't sum up to 1.
- Since the wrapping of long lines is disabled, the maximal width of the column texts is computed, which is 29, originating from 27 characters and two characters required for alignment indication.
- This width is taken as the width of the smallest column, such that the first colums is scaled to 29 characters, and the second column, which is 8 times as wide, is scaled to 8*29 = 232 characters.

While this approach is safe, it constructs unnecessarily wide columns, and I will have a further look on how to optimize this.

**Comment by ickc** [comment]
> 1/12 and 2/3 = 8/12

1/12 + 2/3 = 3/4

The number works this way:

1. column 1: 6 character wide
2. column2 : 48 character wide
3. total (default): 72

6/72 = 1/12, 48/72=2/3

Reference: <https://groups.google.com/d/msg/pandoc-discuss/OiLX2LF3dC0/ZcH-x0w0CAAJ>

> I do not know why they don't sum up to 1.

It won't scale to 1.0. It just provide what's necessary. Otherwise all table will occupy full width.

**Comment by ickc** [comment]
Another problem I found from this example is that the markdown is not "stable":

```bash
$ pandoc -t markdown test.md
  ------ ------------------------------------------------
     foo bar
     foo this is a long line of text
  ------ ------------------------------------------------


$ pandoc -t markdown test.md | pandoc -f markdown -t markdown
  ----- -----------------------------
    foo bar
    foo this is a long line of text
  ----- -----------------------------
```

**Comment by ickc** [comment]
So I think a more suitable approach is, rather than making the minimum of the column width equals to the maximum cell width, one should:

1. calculate the sum of the column width (where each is the maximum of the cell width in that column)

2. take the maximum between the last number and 72 (default), and set this as the full (absolute) width of the table

3. divide each column width by the last number to get relative width of each column

(The calculation above assumes the inclusion of whatever padding is necessary (2 or 3?))

**Comment by jgm** [comment]
+++ ickc [Jan 23 17 13:36 ]:
>   Another problem I found from this example is that the markdown is not
>   "stable":

This is not an issue, because these are simple tables and
simple tables don't record relative width information.

**Comment by ickc** [comment]
>This is not an issue, because these are simple tables and
simple tables don't record relative width information.

In the sense it still represent the same AST, yes.

But it would be nice it won't take a few passes for it to "converge" to a stable representation of markdown (so it's still the idempotent thing). And I think my proposed algorithm that (suppose to) fixes this issue can also fix the problem I'm talking about.
