### ISSUE TITLE
Incorrect table header when the simple table follows a bullet

### ISSUE THREAD

**Issue by yihui** [jgm/pandoc#3364]
Originally reported at https://github.com/yihui/knitr/issues/1349 and I have reduced it to a minimal reproducible example below:

```
## Buggy table

- From 1972 to 2011, momentum strategies that buy winners and sell losers, and which are formed based on the past twelve month returns, generate significant momentum premia:

    Market        Average returns (%)    Sharpe ratio 
---------------  ---------------------  --------------
  U.S. Stocks             7.7                0.45     
   UK Stocks              7.2                0.48     
 Europe Stocks            9.8                0.75     
 Japan Stocks             2.2                0.13     
```

Save it as `test.md` and run

```bash
$ pandoc -f markdown -t latex test.md
```

Output:

```latex
\subsection{Buggy table}\label{buggy-table}

\begin{itemize}
\item
  From 1972 to 2011, momentum strategies that buy winners and sell
  losers, and which are formed based on the past twelve month returns,
  generate significant momentum premia:

  \begin{longtable}[]{@{}lll@{}}
  \toprule
  Market Ave & rage returns (\%) Sha & rpe ratio\tabularnewline
  \midrule
  \endhead
  U.S. Stocks & 7.7 & 0.45\tabularnewline
  UK Stocks & 7.2 & 0.48\tabularnewline
  Europe Stocks & 9.8 & 0.75\tabularnewline
  Japan Stocks & 2.2 & 0.13\tabularnewline
  \bottomrule
  \end{longtable}
\end{itemize}
```

The table header is supposed to be

```
Market & Average returns (\%) & Sharpe ratio\tabularnewline
```

but for some reason, the words `Average` and `Sharpe` were split.

My guess is that the leading white spaces before `Market` are the culprit, but I don't know this behavior is expected or not. I have tested both Pandoc 1.17.2 and 1.19.1.

**Comment by jgm** [comment]
I don't think this is a bug.

Since "Market" is indented four spaces, pandoc interprets it
as a continuation paragraph of the preceding list.

Of course a human wouldn't see it that way, since it looks
like it goes with what follows.  But technically pandoc is
doing the right thing here (also according to the CommonMark
spec).

Solutions:

1)  Indent "Market" less than 4 spaces
2)  Insert an empty HTML comment between the list and the
table.

Note that this sort of thing also happens when you have an
indented code block following a list, and solution (2) above
is the accepted one there.



+++ Mauro Bieg [Jan 19 17 01:18 ]:

**Comment by mb21** [comment]
> I don't think this is a bug.
> Since "Market" is indented four spaces, pandoc interprets it
as a continuation paragraph of the preceding list.

Right, this makes sense. Closing this then...
