### ISSUE TITLE
make debpkg does not work

### ISSUE THREAD

**Issue by federerfanatic** [jgm/pandoc#3369]
Hi, I currently run the latest pandoc from git hub. make debpkg:

pandoc MANUAL.txt -t man -s --template man/pandoc.1.template \
	--filter man/capitalizeHeaders.hs \
	--filter man/removeNotes.hs \
	--filter man/removeLinks.hs \
	--variable version="pandoc 1.19.1" \
	-o man/pandoc.1
pandoc: Error running filter man/capitalizeHeaders.hs
fd:4: hPutBuf: resource vanished (Broken pipe)
Makefile:41: recipe for target 'man/pandoc.1' failed
make: *** [man/pandoc.1] Error 83
 
If I run (from main pandoc directory) the script deb/make_deb.sh: I get

[from_dir_deb_run.txt](https://github.com/jgm/pandoc/files/719841/from_dir_deb_run.txt)

**Comment by ickc** [comment]
If you look into the contents of the `makefile`s, you'll see that probably those options are for @jgm's private use: it seems he setup a virtual machine hosted on a Mac and that `make debpkg` will ultimately points to that virtual machine running some form of Debian.

I tried running `make_deb.sh` before and has no luck as well. Who knows what dependencies has been included in the Virtual Machine.

In the end, those scripts are not intended to be run by us. You should follow [Pandoc - Installing pandoc](http://pandoc.org/installing.html) to install it in your local machine (e.g. using stack). For end users there seem to have no reason why one would create a deb package. I studied these only because I want to build alternative builds (32-bit, ARM, etc.) for the other systems. But may be it is easier to just distribute the `pandoc` binaries for those system than a `.deb` distribution. If we're interested in asking questions on how to build that for alternative systems, we should start it in [Google Groups](https://groups.google.com/forum/#!forum/pandoc-discuss).

The only improvement I can see in this repository is may be to separate those "private commands" that is not intended for other people to use into their own makefile/script. So I think this issue should be closed.

**Comment by federerfanatic** [comment]
Yes. I suspect that is the case also. Although it almost looks like it
works. The dpkg tool suite ought to work fairly well. I have built packages
in the distant past with dpkg tools but have sadly forgotten the details.




--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by ickc** [comment]
Why do you want to build a deb rather than installing through stack/cabal?

**Comment by federerfanatic** [comment]
Curiousity..I suppose. I did use the stack approach--but the main stack
command appears to be binary only? No opensource?

FF




--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by ickc** [comment]
> Curiousity..I suppose. I did use the stack approach--but the main stack
> command appears to be binary only? No opensource?

? Do you mean this [commercialhaskell/stack: The Haskell Tool Stack](https://github.com/commercialhaskell/stack)?

There's a cabal method to install from source too: [Pandoc - Installing pandoc](http://pandoc.org/installing.html). The guide there is pretty extensive.

And curiosity really sounds like belongs to pandoc-discuss. So I think this one should be closed.

**Comment by federerfanatic** [comment]
Sure. Go ahead and close or can it be moved to pandoc discussion with
a command? -FF

**Comment by ickc** [comment]
You need to click the close you see down here. And go to https://groups.google.com/forum/m/#!forum/pandoc-discuss to post your question about the skylighting error.

**Comment by jgm** [comment]
+++ Federer Fanatic [Jan 20 17 13:57 ]:
>   Curiousity..I suppose. I did use the stack approach--but the main stack
>   command appears to be binary only? No opensource?

stack is open source.  They distribute a binary for
convenience.

**Comment by ickc** [comment]
@federerfanatic 

`@jgm` commited faf4f78 fixing the skylighting dependency.

**Comment by federerfanatic** [comment]
Yes. I guess you can use the binary version to build the source
version...doing it as I type this...




--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)
