### ISSUE TITLE
Relative image paths in Markdown not appearing in Context PDF

### ISSUE THREAD

**Issue by alnjxn** [jgm/pandoc#3380]
- the pandoc version (check using pandoc -v)
  - 1.19.1
- the exact command line used
  - `pandoc -f markdown_github -t context -o output.pdf sec02_mechanical.md`
- the exact input used
  - `![](media/image2.jpg)`
- the output received
  - ![screen shot 2017-01-25 at 11 20 17 am](https://cloud.githubusercontent.com/assets/1423708/22298931/4586f3c0-e2f0-11e6-8e79-837b7e33546f.png)
- the output you expected instead
  - The rendered image

=================

Running pandoc 1.19.1
Mac OS X
Using MacTex via homebrew

The following markdown renders as shown below. If I use the absolute path, the image loads properly. Is this a bug or a configuration setting? 

`![](media/image2.jpg)`

![screen shot 2017-01-25 at 11 20 17 am](https://cloud.githubusercontent.com/assets/1423708/22298931/4586f3c0-e2f0-11e6-8e79-837b7e33546f.png)

How can I enable relative paths, this does not happen with LaTeX.

Thanks.

**Comment by jgm** [comment]
Bug confirmed.

**Comment by jgm** [comment]
Problem is that TEXINPUTS doesn't work in context like it does in latex.

We build in a temp directory; in LaTeX, we use TEXINPUTS to allow latex to find images in the original directory.

That doesn't work in context.  Tried using the `--path=` command line argument, no luck.  Tried inserting a `\setupexternalfigures[directory=[PATH]]` into the source, no luck.

context automatically tries the parent directory, so one thing that did work was using `withTempDirectory "."` instead of `withSystemTempDirectory`.  But I'd rather not create even temp files in the working directory.  (Why?  Well, say you're in a DropBox directory. You don't want a bunch of generated temp files to be uploaded.)

Another approach would be to do a transformation of the Pandoc before we write ConTeXt, turning all relative image paths into absolute paths.

**Comment by jgm** [comment]
Another potential solution: if we can wrestle makePDF into PandocMonad, we can use fetchItem and insertMedia.

**Comment by alnjxn** [comment]
@jgm Thanks for looking into this. Our team has relied heavily on Pandoc for as of late for compiling a large part of our documentation. This fix removes the additional step of having to upload images to the cloud in order to get a web link. We chose ConTeXt for the flexible styling an Pandoc has been amazing in building and distributing documents. Thank you.
