### ISSUE TITLE
convert html to markdown/org input, <li> tag produce two spaces

### ISSUE THREAD

**Issue by llj098** [jgm/pandoc#3417]
Hi, 

My commands in the shell is 

`echo "<ul><li>1</li><li>2</li></ul>" | pandoc -f html -t org` 

The output is 

```
-  1
-  2
```

Please NOTE that there are two space character after `-` (-t markdown did same).

---
My pandoc version is:
```
pandoc -v
pandoc 1.19.2
Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.3
```
OS: OS X Sierra

---

Is this a bug or I did something wrong?

Thanks.

**Comment by jgm** [comment]
In the markdown writer, we line up lists so that their
contents start at the 4-space mark.  This produces better
output in general, since list continuation paragraphs
have to start there.  And the number of spaces after
the bullet doesn't matter.

I imagine a similar decision was made in the org writer,
but I'm not sure.

**Comment by tarleb** [comment]
The Emacs org-to-org exporter writes lists using two indents only.  I guess changing this to two spaces for org exports makes sense.
