### ISSUE TITLE
Underscores missing

### ISSUE THREAD

**Issue by gayathriw** [jgm/pandoc#3418]
A lot of times I see underscores are missing in the parsed text. Is there any specific reason for this? Quite important to have correct data, in my case.

**Comment by mb21** [comment]
You'll have to give us a small sample of input and output, pandoc version and what exact command you used...

**Comment by ickc** [comment]
@gayathriw, please read the CONTRIBUTING guideline on submission of bug report. The criteria is simple: we need a replicable recipe for the issue you have. e.g. source, pandoc version and command used, output, and what you think should be the output instead.

Since `_` in markdown has special meaning, if you want it to be a literal underscore, you might need to escape it. Read the MANUAL/user guide to see the escape rule. e.g. `\_`.
