### ISSUE TITLE
convert html netsted list to org incorrect

### ISSUE THREAD

**Issue by llj098** [jgm/pandoc#3425]
Below is my testing:

1. nested list in `<li>` 
```
> echo "<ul><li>1</li><li><ul><li>1.1</li></ul></li></ul>" | pandoc -f html -t org
-  1
-

   -  1.1

```

2. nested list not in `<li>`

```
> echo "<ul><li>1</li><ul><li>1.1</li></ul></ul>" | pandoc -f html -t org
1

-  1.1

```

The above dose not work correctly, Is this a bug or I did something wrong ?

- pandoc version: pandoc 1.19.2 Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.3
os: OS X Sierra

Thanks.

**Comment by jgm** [comment]
It's an HTML reader issue:
```
% echo "<ul><li>1</li><ul><li>1.1</li></ul></ul>" | pandoc -f html -t native
[Para [Str "1"]
,BulletList
 [[Plain [Str "1.1"]]]]
```

My impression was that you couldn't have a nested list like this, with a ul as a child of another ul (not of an li). This is confirmed by most of the responses here:
http://stackoverflow.com/questions/12129037/correct-semantics-for-ul-in-ul
and also by the HTML5 validator https://html5.validator.nu:

![screen shot 2017-02-06 at 15 31 38](https://cloud.githubusercontent.com/assets/3044/22650954/827260a4-ec81-11e6-8e3b-67bcb4488afb.png)

Since this is invalid HTML, I think the issue can be closed.
But you may comment here if you have other information.

**Comment by tarleb** [comment]
Just to be sure: do you also find the output of your first snippet unexpected, or only that of the second?
What output would you have expected instead?

**Comment by llj098** [comment]
@jgm @tarleb 

The first snippet does not work correctly either I think, the html is 

```
<ul><li>1</li><li><ul><li>1.1</li></ul></li></ul>
```

The pandoc's output is 

```
-  1
-

   -  1.1
```

I think it should be 

```
-  1
   -  1.1
```

**Comment by jgm** [comment]
I think normal HTML corresponding to this would be:
```
<ul>
<li>1
<ul>
<li>1.1</li>
</ul></li>
</ul>
```
which does get translated to org as
```
- 1

  - 1.1
```
(I don't know if the blank line is significant in org mode.)

Your HTML renders in my browser as:
<img width="170" alt="screen shot 2017-02-09 at 9 05 21 am" src="https://cloud.githubusercontent.com/assets/3044/22774331/eda0a8aa-eea6-11e6-8e83-a4c2e3bc42a5.png">

which is essentially the same as the org mode rendering you don't like.
So I really don't see a bug here, but feel free to comment if you have additional information.
