### ISSUE TITLE
Pandoc does not detect quotes in odt files

### ISSUE THREAD

**Issue by kuba-orlik** [jgm/pandoc#3437]
I'm using `pandoc 1.19.1`. 

Consider a file called `quote.md`:

```
# Title

> this is a quote

This is the body.
``` 

now, convert it to `.odt`:

```
# pandoc quote.md -o quote.odt
```

Looking at the newly generated odt file, pandoc has correctly applied the "Quotations" style to the "this is a quote" part.

Now, let's convert this new `odt` file back to `.md`:

```
# pandoc quote.odt -o quote2.md
```

The `quote2.md` file has lost the information about which part of the text is quotes:

```
Title
=====

this is a quote

This is the body.
```

**Comment by jgm** [comment]
@MarLinn can you have a look?

**Comment by MarLinn** [comment]
Odt has no semantic concept of block quotes. Therefore the reader has to use guesswork. Right now it just looks at indentation. I agree that that is rather primitive and that it's unfortunate that you can't round-trip, but it seemed like the simplest, most unintrusive solution in the past. 

Ways to solve this:

A. Better documentation (where?)
B. A command line argument to provide a paragraph-style-name for quotations
C. Define a pattern that a paragraph style name must match to be converted like .*[qQ]uot(e|ation).*
D. Change the default odt template so that the "Quotations" style triggers the heuristic

I have my preferences, but which would you as a user prefer?

(That reader needs a thorough overhaul anyway, I might have some time soon, and this should be a nice quick fix to get back into the code.)

**Comment by blindmelon** [comment]
At least in the current version of LibreOffice, and using English locale, "Quotations" is a default style. To me, it makes sense to look for this.

**Comment by MarLinn** [comment]
"English locale" is a problem though. Style names are localised and there is no requirement by anyone to keep them consistent in one locale between tools or versions.

Even ignoring that second part, I personally live in a non-English-speaking country and by now I resort to set all my locales to some versions of English by default because too many badly-written programs implicitly assume that. It's a wide-spread disease that can be a real PITA to deal with. I'd like to try to avoid making Pandoc as horrible to use as all those other half-baked tools out there.

**Comment by Jmuccigr** [comment]
@MarLinn, yeah, but how? Just worry about the default name in all the valid localizations?

I agree that certainly the default style name "Quotations" should be turned into a block quote, but  I don't mind the regex @MarLinn provides either.

**Comment by mb21** [comment]
Maybe the goal here should simply be round-tripping (`pandoc -t odt | pandoc -f odt`). For that we don't need to guess all manners on how people format quotes in ODT but pick one way that both the ODT writer and reader agree on...

**Comment by MarLinn** [comment]
Let's call "Maintain a long list of localised style names" *option E*. Yeah, it's not perfect in any way… Maybe some tool could go through the localisation files of LibreOffice regularly and update a list in the repo or something, and/or Pandoc could look up the names online somewhere whenever it converts an odt by interpreting the document language settings… Hacks upon hacks and gateways to complexity.

But what do users want? Convenience? Predictability? I personally don't even have an idea what kind of users Pandoc (let alone the reader) has. Are they expecting magic or are they hackers?

The same applies to round-tripping: What's the real world use case? I get that it's nice for testing, but what else? Please excuse my ignorance.

**Comment by mb21** [comment]
I guess the case for round-tripping is generating and odt from markdown, send it to someone who uses libreoffice or editing > import back from odt to markdown, finish editing etc. and maybe finally generate the PDF.

**Comment by kuba-orlik** [comment]
> I guess the case for round-tripping is generating an odt from markdown, send it to someone who uses libreoffice for editing, import back from odt to markdown, finish editing etc. and maybe finally generate the PDF.

That's exactly the use-case during which i stumbled upon this issue. It kind of blocked the flow that I have imagined.

**Comment by kuba-orlik** [comment]
I've just created a document with quotes using Polish LibreOffice Writer and opened it using an English-localised Writer. It properly recognized the quotes as "Quotations", not as "Cytaty" (as it is in polish). I've also run `strings file-qith-quotations.odt` and I didn't find anything resembling neither "Quotes" nor "Cytaty". My suspicion is that perhaps the Quotations style is somehow a built-in one and therefore is not denoted by a localized string?

**Comment by MarLinn** [comment]
Ok, I hadn't thought about that use case, good point. That would mean a regex, a command line argument, or changing the styling of the default output template would all help. That third option would be the least stable, but something you can use right now as a crutch.

The automatic re-interpretation by LibreOffice is interesting. There's nothing in the specs about such behaviour that I'm aware of, so I'm guessing this is something application specific. Applications can store their own settings in the document, so the information may be in that part or it may be some heuristic of their own. If it's the former we might be able to re-use that information – with one caveat: odt's are basically a bunch of zipped-up xml files, and the application specific settings are stored in files that the reader doesn't even touch right now if I remember correctly. So that approach would mean a bit of extra complexity. But first more research is necessary.

As a result, for the short term I propose to use the regex plus a command line argument. That should solve the round-tripping issue. I'd like to postpone the wider interpretation for now, but that's something to keep in mind. If LibreOffice does indeed do something funny with its application-specific settings that might mean the odt writer might need to be aware of that as well in some way, especially when using custom templates.

**Comment by mb21** [comment]
> As a result, for the short term I propose to use the regex plus a command line argument.

Not sure what exactly you mean by that...

Sorry if I missed something, but can't we just output a deterministic style (for quotations, and also for code blocks to solve https://github.com/jgm/pandoc/issues/2746) which the odt reader can convert back?

**Comment by jgm** [comment]
+++ Mauro Bieg [Feb 14 17 00:52 ]:
>     As a result, for the short term I propose to use the regex plus a
>     command line argument.
>
>   Not sure what exactly you mean by that...
>
>   Sorry if I missed something, but can't we just output a deterministic
>   style (for quotations, and also for code blocks to solve [1]#2746)
>   which the odt reader can convert back?

I think I'm also a bit unclear about what @MarLinn is
proposing.  Just to be pragmatic about it, I like the idea
of outputing a deterministic style to enable a round-trip.

**Comment by kizu** [comment]
I would really like to see it implemented in any way, right now I think there is just no way to get blockquotes from OpenOffice or LibreOffice when saving document as .odt.

Even some predefined list of common names for styles would help, as for me it would be enough to create a style named `BlockQuote` and use it whenever I'd want a blockquote. So even without all the localised strings having some styles to match blockquotes would be so so helpful!

**Comment by dowens76** [comment]
I would love to see this too. My use case is a small book company in Vietnam that uses LibreOffice to edit, and then we convert to HTML. I'd love to be able to convert either to Markdown or HTML and preserve block quotes.
