### ISSUE TITLE
Issues with emphasized text in org-mode to HTML conversion

### ISSUE THREAD

**Issue by nirbhasa** [jgm/pandoc#3444]
The following strings do not convert properly to emphasized text - instead, the forward slashes are left in place.

`/ text,/`  (`/text/,` is converted properly)
`[/text/]` (` /[text]/`  is converted properly)
`/[italic text /normal text/]/`

**Comment by tarleb** [comment]
Please state precisely what's contrary to your expectations.  Is pandoc's behavior different from that of Emacs exporters?  Please also include the pandoc version that you are using.

**Comment by tarleb** [comment]
I tested the given examples with both emacs and the most recent pandoc release. They are essentially equivallent, with the exception of the last example:

Emacs org-mode latex exporter:

```latex
\emph{[italic text /normal text/]}
```

Pandoc:

```latex
/{[}italic text \emph{normal text/{]}}
```

This is due to a fundamental difference in the way pandoc and emacs parse the syntax.  It's a border case, and I don't see a simple way to change this without rewriting the reader (but would be happy to learn if there is a simple method to eliminate this difference).

The other cases seem to work as expected (see emacs documentation for `org-emphasis-regexp-components` for specifics), so I'm closing this.
