### ISSUE TITLE
Inline code seems to be broken

### ISSUE THREAD

**Issue by 8084** [jgm/pandoc#3453]
Input:
```markdown
$a `$b` c `d`
```
Output:

```html
<p><span class="math inline">$a `$</span>b<code>c</code>d`</p>
```

Preview:
![2017-02-17-143245_89x30_scrot](https://cloud.githubusercontent.com/assets/18447310/23063989/9df5962a-f51e-11e6-958b-8a4c4edd8c9e.png)

Expected:
![2017-02-17-143024_104x64_scrot](https://cloud.githubusercontent.com/assets/18447310/23064069/047d61f2-f51f-11e6-8e69-c76ff0351fa0.png)

Version:
```
pandoc 1.19.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9, highlighting-kate 0.6.3
```

**Comment by jgm** [comment]
It's a precedence issue:  which binds tighter, the backticks or the `$` for tex math, or do they have equal precedence so that the first wins?  Currently pandoc assumes the last of these options.  Markdown is too under-specified to resolve this, and the `$` is an extension anyway.

So it's not really obvious what the correct answer is.  Maybe pandoc's parser should be changed.

Workaround:  disable the `tex_math_dollars` extension or backslash-escape the first `$` so it doesn't get interpreted as tex math.

**Comment by jgm** [comment]
An argument for the present behavior:  if backticks always bound more tightly than `$`, then there'd be no way to have tex math that uses the backtick character.
