### ISSUE TITLE
Enable raw_tex extension for docx output 

### ISSUE THREAD

**Issue by cellulosa** [jgm/pandoc#3470]
I am trying to implement a markdown + YAML workflow as opposed to plain LaTeX (to make things cleaner and easier e.g. making/reading a table in LaTeX is hell). Unfortunately, some features are not working well with markdown and I therefore need to implement some LaTeX syntax too. If I understood correctly, this would make use of the `raw_tex` extension, that does work only on certain outputs - is this correct? Is it not possible to render the following to `docx`?

    ---
    title: Title
    subtitle: Sub-title
    author: Name Surname
    header-includes:
        - \usepackage{cleveref}
    toc-title: Content
    ---

    \listoffigures

    # Heading

    ![This is a markdown image\label{image}](image.png)

    This is a reference \cref{image} using LaTeX.
    This is a citation using markdown [@citation2017].

**Comment by lierdakil** [comment]
No, it's not possible, since LaTeX is only handled by LaTeX, and stripped out of other outputs. Also there's no good way to support this save for reimplementing LaTeX engine in Haskell, and that would be clearly out of scope.
But, from what I can tell from the example, you want cleveref-like cross-references. That's doable (although with a bit of awkward syntactic extension to Markdown instead of raw tex commands), see [pandoc-crossref filter](https://github.com/lierdakil/pandoc-crossref) or [pandoc-fignos filter](https://github.com/tomduck/pandoc-fignos).

Pandoc-crossref supports output to LaTeX with classic `\ref`s or cleveref (almost) seamlessly, btw (although there are some quirks related to configurability, i.e. you'll have to configure cleveref and other output formats separately, which can be somewhat awkward)

Disclaimer: I am the author of pandoc-crossref, so take my recommendation with a pinch of salt. While I think it's the best piece of software ever, YMMV. I do try to maintain it to the best of my ability, so filing issues is effective.

**Comment by mb21** [comment]
Please use pandoc-discuss for questions...

**Comment by lierdakil** [comment]
@mb21 it could be argued that this is a somewhat misguided feature request though.

As a side note, creating an issue template and adding link to pandoc-discuss near the top of `CONTRIBUTING.md` could help enforce this policy.

**Comment by cellulosa** [comment]
@lierdakil thanks for your inputs. Yes I did find `pandoc-fignos` but I missed `pandoc-crossref` which seems to work much better than the former - great work. Yes I think making note of pandoc-discuss it would help.

**Comment by mb21** [comment]
@lierdakil good point, done: https://github.com/jgm/pandoc/commit/9d91b8825f6338e415eceb1163bba95d3178a49a
