### ISSUE TITLE
LaTeX-to-HTML conversion omits contents of \textsf{}

### ISSUE THREAD

**Issue by nschneid** [jgm/pandoc#3488]
For example, on the [Try page](http://pandoc.org/try/):

```tex
\newcommand{\fnf}[1]{\textsc{\textsf{#1}}}
\newcommand{\fnr}[1]{\textbf{\textsf{#1}}}
\newcommand{\ggg}[1]{\textsf{#1}}
\newcommand{\lex}[1]{\textit{#1}}

\fnf{Abcd}

\fnr{Efgh}

\ggg{Ijkl}

\textsf{Mnop}

\lex{Zzzzz}
```

converted to HTML results in

```html
<p><span><span style="font-variant: small-caps;"></span></span></p>
<p><span><strong></strong></span></p>
<p><span></span></p>

<p><span><em>Zzzzz</em></span></p>
```

The same holds true for converting a full LaTeX file where these macros are used. (Version 1.19.2.1.)

1. Should `\textsf{}` be supported out-of-the-box?
2. If a LaTeX command is unknown, how should it be handled in HTML?
3. Would it be possible to have an alternate treatment of macros—e.g., specify them as classes in an HTML span, like `<span class="fnr">Efgh</span>`? It could be left to the user to define appropriate CSS.

**Comment by jgm** [comment]
>    1. Should \textsf{} be supported out-of-the-box?

Yes, at least its contents should come through unscathed,
and probably there should be a span with an attribute.

This should be a simple change to the LaTeX reader.

>    2. If a LaTeX command is unknown, how should it be handled in HTML?
>    3. Would it be possible to have an alternate treatment of macros—e.g.,
>       specify them as classes in an HTML span, like <span
>       class="fnr">Efgh</span>? It could be left to the user to define
>       appropriate CSS.

Unfortunately, this wouldn't work well, because many latex
commands have contents that aren't meant to be printed
(e.g. \ref{}, \label{}, many others).

If we defaulted to including all of their contents (in a
span or not), the default output would be very messy.

Pandoc 2.0 will at least give good warnings about things it
is ignoring.

**Comment by jgm** [comment]
I've just made changes that give the following result for your input:
``` html
<p><span><span class="smallcaps"><span class="sans-serif">Abcd</span></span></span></p>
<p><span><strong><span class="sans-serif">Efgh</span></strong></span></p>
<p><span><span class="sans-serif">Ijkl</span></span></p>
<p><span class="sans-serif">Mnop</span></p>
<p><span><em>Zzzzz</em></span></p>
```
