### ISSUE TITLE
org-mode INCLUDE ignored

### ISSUE THREAD

**Issue by b3** [jgm/pandoc#3510]
When converting from `org-mode` included files (as specified by `#+INCLUDE:` directives) are just ignored.

For instance the following `main.org` file :

    #+include: "sub1.org"
    #+include: "sub2.org"

with `sub1.org` listed as :

    text from sub1

and `sub2.org` listed as

    text from sub2

should be translated by `pandoc -t org -f markdown -o main.md main.org` to

    text from sub1
	text from sub2

but is translated instead to a file containing just a newline character.

**Comment by tarleb** [comment]
This should probably be implemented analogous to the file include mechanism of the LaTeX writer. I haven't used the new PandocMonad yet; would it make sense to generalize the existing `insertIncludedFile` such that it becomes usable with the Org parser state? @jgm @jkr

**Comment by jgm** [comment]
+++ Albert Krewinkel [Mar 16 17 11:01 ]:
>   This should probably be implemented analogous to the file include
>   mechanism of the LaTeX writer. I haven't used the new PandocMonad yet;
>   would it make sense to generalize the existing insertIncludedFile such
>   that it becomes usable with the Org parser state? [1]@jgm [2]@jkr

Yes, we could do that.  What it would take would be adding a
new typeclass to Text.Pandoc.Parser, HasContainers (or
something -- that's not the most descriptive name).
Instances could then be defined for ParserState and for
org's ParserState, and we could generalize the function
using the typeclass.  If you'd like to do this, go ahead.
It's precisely analogous to what we've done with HasMacros,
etc.

Of course, it's possible that when you look into the details
of org includes, you'll decide that you need your own
function.  In the RST reader we couldn't reuse
insertIncludedFile, because RST's include mechanisms
include options for a line number range and other things.
So we have a bit of code duplication there.

**Comment by phmarek** [comment]
Would you please include that in the next release? The last one is from February, and I'm not sure about the release plans for 2.0...

This feature would help tremendously in creating and updating nearly-identical files.

**Comment by tarleb** [comment]
The new version (pandoc 2.0) is probably going to be released sometime next month.  You could try the latest [inofficial nightly build](https://github.com/pandoc-extras/pandoc-nightly) if you don't want to wait.
