### ISSUE TITLE
csv table support for RST

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#3533]
Docs: http://docutils.sourceforge.net/docs/ref/rst/directives.html#id4

Example:
```
.. csv-table:: Frozen Delights!
   :header: "Treat", "Quantity", "Description"
   :widths: 15, 10, 30

   "Albatross", 2.99, "On a stick!"
   "Crunchy Frog", 1.49, "If we took the bones out, it wouldn't be
   crunchy, now would it?"
   "Gannet Ripple", 1.99, "On a stick!"
```

Investigate this library with no dependencies:
https://hackage.haskell.org/package/readcsv-0.1

**Comment by mb21** [comment]
I've been using [spreadsheet](https://hackage.haskell.org/package/spreadsheet) for [pandoc-placetable](https://github.com/mb21/pandoc-placetable) and haven't had any issues with it. If I see this correctly, it has the advantage that you can specify a custom delimiter and quotechar...

**Comment by nichtich** [comment]
There is no CSV specification but many dialects. See http://specs.frictionlessdata.io/csv-dialect/ for an attempt to specify at least some of the dialects. To add CSV support to pandoc we likely need some kind of `pancsv`.

**Comment by jgm** [comment]
I think `spreadsheet` is a good choice of library for this.
Simple API:  `fromString quotechar sepchar string` gives you a list of lists of strings.
Here are the specific attributes supported in RST:

- widths : integer [, integer...] or "auto" [SUPPORT]

  A comma- or space-separated list of relative column widths. The default is equal-width columns (100%/#columns).  The special value "auto" may be used by writers to decide whether to delegate the determination of column widths to the backend (LaTeX, the HTML browser, ...).

- header-rows : integer [SUPPORT]

  The number of rows of CSV data to use in the table header. Defaults to 0.

- stub-columns : integer [SUPPORT, throw out stubs]

  The number of table columns to use as stubs (row titles, on the left). Defaults to 0.

- header : CSV data [SUPPORT]
 
  Supplemental data for the table header, added independently of and before any header-rows from the main CSV data. Must use the same CSV format as the main CSV data.

- file : string (newlines removed) [SUPPORT]

  The local filesystem path to a CSV data file.

- url : string (whitespace removed) [SUPPORT?]

  An Internet URL reference to a CSV data file.

- encoding : name of text encoding [DON'T SUPPORT, assume UTF-8]

  The text encoding of the external CSV data (file or URL). Defaults to the document's encoding (if specified).

- delim : char | "tab" | "space" [2] [SUPPORT]

  A one-character string[3] used to separate fields. Defaults to , (comma). May be specified as a Unicode code point; see the unicode directive for syntax details.

- quote : char [SUPPORT]

  A one-character string[3] used to quote elements containing the delimiter or which start with the quote character. Defaults to " (quote). May be specified as a Unicode code point; see the unicode directive for syntax details.

- keepspace : flag [DON'T SUPPORT]

  Treat whitespace immediately following the delimiter as significant. The default is to ignore such whitespace.

- escape : char [DON'T SUPPORT]

  A one-character[3] string used to escape the delimiter or quote characters. May be specified as a Unicode code point; see the unicode directive for syntax details. Used when the delimiter is used in an unquoted field, or when quote characters are used within a field. The default is to double-up the character, e.g. "He said, ""Hi!"""

- align : "left", "center", or "right" [DON'T SUPPORT]

  The horizontal alignment of the table. (New in Docutils 0.13)

Print warnings for unsupported atributes.

**Comment by jgm** [comment]
Is this a bug in `spreadsheet`?
```
Prelude Data.Spreadsheet> fromString '\'' ',' "33, 44\n55, '66'"
Exceptional {exception = Just "line end expected", result = [["33"," 44"],["55"," "]]}
```
Shouldn't this be valid CSV?

**Comment by ickc** [comment]
Just want to ask, are there any chance CSV table will also be supported in markdown, after all?

**Comment by mb21** [comment]
@jgm There are actually two issues with the csv example you posted (`33, 44\n55, '66'`):

1. as you noted, the space in front of the quotes
2. the csv is supposed to end with a newline (correct: `33, 44\n55,'66'\n`).

Because users usually don't end their code blocks containing csv data with an additional newline, I decided to always append a newline in pandoc-placetable...

**Comment by jgm** [comment]
I ended up writing my own small CSV parser, since none
of the ones I could find had exactly the features I wanted.

**Comment by ickc** [comment]
> as you noted, the space in front of the quotes is not allowed by RFC 4180

I've seen people filed an issue in ickc/pantable when they have a space in front of a quote. So while it isn't standard, you may need to be prepared for malformed CSV from countless different CSV parsers' behavior. (or may be just hand-typed CSV).

**Comment by ickc** [comment]
> I ended up writing my own small CSV parser, since none
> of the ones I could find had exactly the features I wanted.

Since this issue is about CSV in RST specifically, it might be worth mentioning these:

- CSV table in RST uses the csv module from the standard library from Python. The CSV module defines these for different dialects: [cpython/csv.py at master · python/cpython](https://github.com/python/cpython/blob/master/Lib/csv.py#L35-L41), and has these unit tests: [cpython/test_csv.py at 6f0eb93183519024cb360162bdd81b9faec97ba6 · python/cpython](https://github.com/python/cpython/blob/6f0eb93183519024cb360162bdd81b9faec97ba6/Lib/test/test_csv.py#L909-L956)
- From my experience, the Python2 and Python3 CSV modules behaves slightly differently. I guess when they differs, Python3's should be a better reference.

Also some other notes from my experience:

- CSV can has variable no. of columns per row. Don't know how RST handles this, but Python's CSV module handles this perfectly. But pandoc's current Table AST (probably) cannot handle this.

And then again for the obvious question on if this csv library you're writing will also be added as a markdown extension?

- pros:
    - unifies currently at least 4 different 3rd parties pandoc filters doing a similar thing (3 packaged, 1 panflute example)
    - you get it "almost free" when it is already implemented in the RST reader
    - having 4 3rd parties filters doing similar things might means it is a popular feature needed
- cons:
    - pandoc's CSV will unlikely be able to replace filters completely (e.g. markdown in CSV which I doubt you'll allow it?)
    - not markdown-ish (that's why you reject it before?)

If CSV table will not be in pandoc's markdown extensions, then this reminds me something I wanted to do in this past: a filter that allows freely mixed pandoc supported formats in the same file. This then allows one to have an RST CSV table in a markdown source for example.

I've a couple of questions out of curiosity too:

- why would this feature be even considered in the first place? Are you going to "fully" implement the RST extensions here?
- how hard would it be to translate between pandoc AST and docutils AST?

**Comment by jgm** [comment]
@ickc My CSV parser is forgiving about the spaces by default (as the rst implementation requires; there's an option to set the stricter behavior).  I'm sure there are bugs, so testing with real-world CSV will be most welcome.

My parser is probably quite a bit slower than cassava; hopefully that won't be an issue.

I don't plan to add this as a Markdown extension, because (as noted) it's not Markdownish.  But it is part of the RST spec, so it's implemented.

I don't know anything about the docutils AST.
