### ISSUE TITLE
Progress output

### ISSUE THREAD

**Issue by fulldecent** [jgm/pandoc#3540]
Many third-party programs use Pandoc for conversion. During this process they make a message like this:

![screen shot 2017-03-30 at 9 38 27 am](https://cloud.githubusercontent.com/assets/382183/24506854/d5106eb8-152c-11e7-80bf-1f6a9e06e729.png)

Please allow Pandoc to report on progress of operations so that dialogs like this can be more informative.

**Comment by jgm** [comment]
Most but not all of the readers currently support tracing output with `--trace`.
This tracks parsed blocks and gives line numbers as it goes.  This feature was designed to help performance issues where the parser backtracks.  In principle the trace output could be consumed by a status bar; if the total number of lines of input is known, it would give information about how far the parser has gotten.  This is not completely reliable, though, since some parsers do allow backtracking.  It also only covers the parsers, not the writers.

**Comment by fulldecent** [comment]
Fair enough, thank you, this is usable for now.
