### ISSUE TITLE
[Feature request] MD030 support

### ISSUE THREAD

**Issue by Kristinita** [jgm/pandoc#3573]
### 1. Summary

It would be nice, if pandoc will support [**MD030**](https://github.com/mivok/markdownlint/blob/master/docs/RULES.md#md030---spaces-after-list-markers) markdownlint rule. I don't find in [**lists documentation**](http://pandoc.org/MANUAL.html#lists), how I can get expected behavior.

### 2. Argumentation

Compatibility with the most famous linter for Markdown.

### 3. Settings

I have a file `Kristina.html`, it content:

```html
<ul>
    <li>Kristina,</li>
    <li>yellow</li>
    <li>blue</li>
    <li>bus</li>
</ul>

```

### 4. Steps to reproduce

I run command in a terminal:

```shell
pandoc -t markdown_github Kristina.html
```

### 5. Expected behavior

1 space after mark.

```shell
- Kristina,
- yellow
- blue
- bus
```

### 6. Actual behavior

3 spaces after mark.

```shell
-   Kristina,
-   yellow
-   blue
-   bus
```

I get MD030 error:

![MD030](http://i.imgur.com/hwWOKdo.png)

Thanks.

**Comment by jgm** [comment]
There's a good reason for pandoc's behavior (and a good
reason NOT to adopt this linter's recommendation).

Because pandoc respects the four-space rule, contents of
list items must be indented four spaces.  By making the
top of the list item indented to that level, pandoc allows
it to line up with continuation paragraphs.

Thus:

```
-   This looks good.

    Second paragraph of list.

        indented code inside list item, indented 8 spaces
        as required by Gruber's syntax definition.

-   Second list item
```

Whereas:

```
- This looks bad.

    Second paragraph of list (doesn't line up!)

        indented code inside list item, indented 8 spaces
        as required by Gruber's syntax definition.

- Second list item
```

Although not all Markdown implementations respect the
four-space rule, respecting the four-space rule is necessary
for maximum compatibility across implementations.

So, I'd say this is a problem with the linter, not with pandoc.

**Comment by jgm** [comment]
Note also that on the MD030 documentation, it explicitly
says that 1 space is only the default, and that this can
be adjusted for document style by changing another
parameter.  So you have an easy solution there. This
can be closed.

**Comment by Kristinita** [comment]
@jgm , how I can personally set 1 space?

Thanks.

**Comment by jgm** [comment]
You can't customize this in pandoc's markdown writer.

+++ Саша Черных [Apr 15 17 02:14 ]:
