### ISSUE TITLE
MediaWiki reader chokes on quotes inside <tt> elements

### ISSUE THREAD

**Issue by ktk** [jgm/pandoc#3585]
For MediaWiki to Markdown conversion there seems to be a problem with quotes.

I have in MediaWiki:

    * Same but bzip2 it and nice it <tt>zfs send tank/storage/data/svn@daily-2014-03-20_00.00.00--2w | nice -15 bzip2 | ssh user@hyper.somewhere.org "> /storage/c-3po/tank-storage-data-svn.dmp.bz2"</tt>

When I convert that to Markdown I get:

    -   Same but bzip2 it and nice it `zfs send tank/storage/data/svn@daily-2014-03-20_00.00.00--2w | nice -15 bzip2 | ssh user@hyper.somewhere.org `“`>`` ``/storage/c-3po/tank-storage-data-svn.dmp.bz2`”

At one point it seems to get confused by the double-quote in there and breaks the command.

**Comment by mb21** [comment]
A more minimal example is:

    echo '<tt>">"</tt>' | pandoc -f mediawiki -t native
    [Para [Quoted DoubleQuote [Code ("",[],[]) ">"]]]

Somehow the `<tt>` code tags don't take precedence over the quotes as they should, expected output:

    [Para [Code ("",[],[]) "\">\""]]

**Comment by jgm** [comment]
I'm inclined to close this.  Formatting is supposed to be interpreted inside `<tt>`.  We can't literally include a DoubleQuoted in a `<tt>`, so this is the best we can do.  Of course, this doesn't match MediaWiki's own interpretation, but that's because MediaWiki doesn't have smart punctuation by default.

I would just suggest that we change the default extensions on the MediaWiki reader so that smart punctuation is not enabled.

**Comment by jgm** [comment]
Actually, I'll also fix it so that, even with `smart` enabled, double quotes aren't transformed inside `tt` elements.

**Comment by ktk** [comment]
tnx @jgm will check that out in the next release
