### ISSUE TITLE
Support more listings languages in highlighting (fsharp, cs and yaml)

### ISSUE THREAD

**Issue by peterhirn** [jgm/pandoc#3606]
Please add `fsharp`, `cs` and `yaml` to `langsList` in `pandoc/src/Text/Pandoc/Highlighting.hs` if possible.

Thank you.

**Comment by jgm** [comment]
fsharp, c#, and yaml aren't on the list of languages supported by listings (http://texdoc.net/texmf-dist/doc/latex/listings/listings.pdf).  That is why they aren't included.

If you want highlighting for these languages, may I suggest using pandoc's native highlighting capacities instead of listings?

**Comment by peterhirn** [comment]
I see, thank you!
