### ISSUE TITLE
Pandoc fails with Google font CSS import in self-contained HTML

### ISSUE THREAD

**Issue by klmr** [jgm/pandoc#3629]
Pandoc seems to fail to download resources from Google Fonts when specifying multiple fonts (delimited by a pipe `|`) for a self-contained HTML document.

MWE + error:

```bash
⟩⟩⟩ pandoc --version | head -2
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.4

⟩⟩⟩ more test.md
foobar

⟩⟩⟩ more test.css
@import url('https://fonts.googleapis.com/css?family=Open+Sans|Roboto');

⟩⟩⟩ pandoc test.md --css test.css --self-contained -o test.html
pandoc: Could not fetch ./https://fonts.googleapis.com/css?family=Open+Sans|Roboto
./https://fonts.googleapis.com/css: openBinaryFile: does not exist (No such file or directory)
```

If only a single font is specified, this works.

**Comment by mb21** [comment]
Not saying this is not a bug, but pipes are not commonly used in URLs. As a workaround, you can urlencode the pipe:

    https://fonts.googleapis.com/css?family=Open+Sans%7CRoboto

**Comment by jgm** [comment]
```
Prelude Network.URI> isURI "https://fonts.googleapis.com/css?family=Open+Sans|Roboto"
False
```
I can confirm that with @mb21's encoding fix, it works.
Also, note that pandoc 2.0 (dev version) gives a less informative error message:
```
% pandoc --css test.css --self-contained -o test.html MANUAL.txt 
pandoc: user error (file not found in resource path)
```
No indication of which file is at issue.  We should figure out why and fix this.

**Comment by klmr** [comment]
I was expecting the Google Font website to give me valid code. But indeed it’s not clear that an unencoded pipe is actually valid in URIs. Thanks, I’ll percent-encode it.

**Comment by jgm** [comment]
I didn't realize Google was violating its own recommendations.
Perhaps we could tweak pandoc's code so that the `|` is automatically escaped in a case like this.

**Comment by jgm** [comment]
Update: I did fix the issue with `|`.  That wasn't enough, though, to get google fonts working with `--self-contained`.  The problem is that the `@import` statement brings in some CSS code that *itself* contains a `url(...)`.  So I changed the code so that these interior urls are also processed.  Result:  I get code that seems okay, but doesn't work properly in the browser.
```
  <style type="text/css">@import url(data:text/css; charset=utf-8,%40font%2Dface%20%7B%0Afont%2Dfamily%3A%20%27Open%20Sans%27%3B%0Afont%2Dstyle%3A%20normal%3B%0Afont%2Dweight%3A%20400%3B%0Asrc%3A%20local%28%27Open%20Sans%27%29%2C%20local%28%27OpenSans%27%29%2C%20url%28data%3Afont%2Fttf%3Bbase64%2CAAEAAAASAQA...etc.
```
Note that the main data: uri includes another encoded data: uri (for the font itself).
I'm not sure why this doesn't work; if anyone has ideas, please comment.
You can try it with the latest dev version.

**Comment by klmr** [comment]
> That wasn't enough, though, to get google fonts working with `--self-contained`.

I contemplated filing another issue for that but decided against it because fixing it seemed nontrivial. :-/

**Comment by jgm** [comment]
+++ Konrad Rudolph [May 06 17 10:32 ]:
>     That wasn't enough, though, to get google fonts working with
>     --self-contained.
>
>   I contemplated filing another issue for that but decided against it
>   because fixing it seemed nontrivial. :-/

If I understood what the problem was, I'm sure I could fix
it.  But I don't see why it's not working, and I don't get
any clues from the browser's diagnostics.

**Comment by mb21** [comment]
Current master url-encodes the data in the data-urls. I think you have to use base64 instead, e.g.:

    @import url(data:text/css;charset=utf-8;base64,Ym9keSB7Zm9udC1zaXplOiAxMDBweH0=);

**Comment by jgm** [comment]
@mb21 we url-encode if the data is all textual, base64 if it's binary.
Here we have two data: uris.  The inner one has binary data, and it's base64 encoded.
But then the outer one has only textual data to encode, since the base64 encoded font is textual.  So it should be safe to use url-encoding.
I think in my earlier experiments I tried changing this so that base64 was always used, and it still didn't work.

**Comment by jgm** [comment]
I've also added support for e.g.

    @import "test.css";

with no `url()`.
