### ISSUE TITLE
markdown_mmd source option doesn't properly handle fenced code blocks

### ISSUE THREAD

**Issue by jonBoone** [jgm/pandoc#3637]
$ pandoc --version
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.4

```

~~~~~json
{
  "test" : "testing"
}
~~~~~

```

when converting to pdf via latex using the following command:
pandoc -o test.pdf --read=markdown --latex-engine=xelatex test.md
everything works as expected

however, when using this command:
pandoc -o test.pdf --read=markdown_mmd --latex-engine=xelatex test.md
the output is rendered incorrectly

**Comment by jgm** [comment]
mmd didn't used to support fenced code blocks.  It looks
like they do now, but only the backtick style (not tildes):
http://fletcher.github.io/MultiMarkdown-5/fences.html

I will revise pandoc so that backtick code blocks are
included in markdown_mmd. In the mean time you can
enable them manually with

    --read markdown_mmd+backtick_code_blocks


+++ Jon Boone [May 04 17 06:59 ]:

**Comment by ickc** [comment]
Just realized this change when reading the changelog.

This is strange, because I remembered that MultiMarkdown has long (don't know how long though) been able to parse the

    ```yaml
    testing
    ```

style codeblock with optional language attribute.

And then I recalled I once checked all relevant pandoc markdown extensions is enabled in the `markdown_mmd` variant. But apparently I missed this.

To @jonBoone, markdown variants like `markdown_mmd` in pandoc is not perfect, and you may call it an "emulation mode". So be aware of this if you use it.
