### ISSUE TITLE
.docx to .md - escaping special characters

### ISSUE THREAD

**Issue by hiteshguptacompro** [jgm/pandoc#3644]
I am trying to convert a .docx file into .md file.
My doc file has some special characters, when pandoc processes it and outputs md file, it adds escape character before it.

For example
Line in docx
\`\`\` [my-data] {"type":"obj1","options":{"data":{"showGraphs":["pos","vel","acc"],"showProfiles":["profile1","profile2","profile3"],"hideInputs":["smoothness"]}}} \`\`\`

Required O/P
\`\`\` [my-data] {"type":"obj1","options":{"data":{"showGraphs":["pos","vel","acc"],"showProfiles":["profile1","profile2","profile3"],"hideInputs":["smoothness"]}}} \`\`\`

Original O/P
\\\`\\\`\\\` \\[my-data\\] {"type":"obj1","options":{"data":{"showGraphs":\\["pos","vel","acc"\\],"showProfiles":\\["profile1","profile2","profile3"\\],"hideInputs":\\["smoothness"\\]}}} \\\`\\\`\\\`

for more clarification refer .docx and .md files attached

[pandoc.zip](https://github.com/jgm/pandoc/files/980836/pandoc.zip)

Please suggest how I can do it.

**Comment by jgm** [comment]
What you want is to get that material into a Markdown code block.  You've put triple backticks in the Word file -- that's not going to do it, since that's Markdown syntax, not Word.

Try creating a paragraph style called "SourceCode" and apply it to that paragraph. The docx reader should then recognize it as a code block (though I admit I haven't tried this).
