### ISSUE TITLE
Most writers can't output tables produced with Text.Pandoc.Builder.simpleTable

### ISSUE THREAD

**Issue by labdsf** [jgm/pandoc#3648]
This bug was closed for Markdown (see issue #70), but remains for some other writers.

Here is my `table.native` file, it contains a table produced with `simpleTable`, without aligns and widths:
```
[Table [] [] []
 []
 [[[Plain [Str "First"]]
  ,[Plain [Str "Second"]]]
 ,[[Plain [Str "Third"]]
  ,[Plain [Str "Fourth"]]]]]
```

Markdown produces correct result:
```
$ pandoc -f native -t markdown < table.native
  ------- --------
  First   Second
  Third   Fourth
  ------- --------
```

Dokuwiki is wrong:
```
||
||

```

HTML is wrong:
```
<table>
<tbody>
<tr class="odd">
</tr>
<tr class="even">
</tr>
</tbody>
</table>
```

RST produces weird result:
```
++
| First | Second |
+-------+--------+
| Third | Fourth |
+-------+--------+
```

And so on.

Of all writers, the following have a bug:
- CommonMark
- Docx
- DokuWiki
- EPUB
- FB2
- HTML
- Haddock
- ICML
- LaTeX
- MediaWiki
- ODT
- OPML (it does not produce tables at all)
- OpenDocument
- RST (reader can't read back what writer produced)
- RTF
- Texinfo
- Textile
- ZimWiki

**Comment by mb21** [comment]
Thanks for bringing this up, I've stumbled over this as well. Currently, there are just too many ways to represent basically the same table in the AST. Depending on what's convenient when writing the code, the AST is read and written differently.

- `Para` vs `Plain`
- In the case of no headers: is the row `[]` or `[[], [], []]` (or even `[[Plain [], Plain [], Plain []]]`)
- The same goes for the `Alignment` list: `[]` vs `[[], [], []]`

We should probably document _one right way_, then make sure `Text.Pandoc.Builder` produces that and change all readers to use those functions, and make sure all readers work for that _right way_.

**Comment by jgm** [comment]
The problem, more specifically, is that `simpleTable`
(and `table`) allow you to create a table with an empty
list for headers (or with an empty list for alignments/widths).
These tables cause problems for some writers.

I guess the question is whether to adjust the other writers 
so that they can handle tables with empty lists for headers
and alignments, or adjust simpleTable (and table) so that
if headers is empty, a nonempty list of empty header cells is
provided, of length equal to the longest row.
  
The latter is probably easiest. 

We're going to rethink tables anyway (#1024), and it will
be good to remember this issue in that connection.

**Comment by jgm** [comment]
PS. To avoid the problem, just make sure that when you use `simpleTable`, you specify a list of empty cells for your header, rather than an empty list.
