### ISSUE TITLE
The Windows binary is 32-bit and cannot handle extremely large conversion jobs

### ISSUE THREAD

**Issue by eubr** [jgm/pandoc#3669]
I'm using the prebuilt 1.19.2.1 windows installer. I'm trying to convert the whole php manual to epub with this command:

```pandoc php-bigxhtml.txt -f html -t epub -o php.epub```

I have 32GB ram, but after about 2GB allocated, pandoc just says:

```pandoc: Out of memory```

**Comment by mb21** [comment]
From http://stackoverflow.com/questions/30704736/how-to-increase-heap-memory-in-pandoc-execution, try:

    pandoc.exe +RTS -M2048

**Comment by eubr** [comment]
interestingly, it uses bytes for me instead of megabytes. it seems like the max it can go is 4GB:

```pandoc php-bigxhtml.txt -f html -t epub -o php.epub +RTS -M4294967295```

That is unfortunately not enough: I get the same OOM error.

**Comment by mb21** [comment]
probably depends on the Windows version (32 vs 64bit), see https://jonathanchang.org/blog/fixing-pandoc-out-of-memory-errors-on-windows/

also feel free to ask on the pandoc-discuss mailing list, but this issue tracker is actually for bug reports / feature requests...

**Comment by eubr** [comment]
I tried already to do what that blog suggests: still OOM.

>32 vs 64 bit

I have a 64 bit operating system, and I downloaded the only available installer from https://github.com/jgm/pandoc/releases/tag/1.19.2.1

>this issue tracker is actually for bug reports / feature requests...

I'm aware of that. I consider the fact that pandoc is able to use less than 10% of my memory a bug, but even if it's not, it's at the very least a reasoable feature request.

**Comment by mb21** [comment]
I believe pandoc still only provides 32bit binaries for Windows, so that may indeed be an issue...

**Comment by jgm** [comment]
@eubr Can you link to or upload the big input file you're using, so we can test ourselves?

**Comment by eubr** [comment]
@jgm http://php.net/download-docs.php the english Single HTML file

**Comment by jgm** [comment]
@eubr would you mind testing with the binary here?
https://ci.appveyor.com/project/jgm/pandoc/build/1.0.1173/artifacts
I've changed the appveyor script so it manually sets LARGEADDRESSAWARE using the method described in the blog linked above.

**Comment by eubr** [comment]
This time it reaches 4GB - I probably did a mistake when I patched it - but unfortunately it still dies OOM.

**Comment by GiantCrocodile** [comment]
I was able to achieve a 8 GB RAM consumption of pandoc.exe with your example and this version: https://ci.appveyor.com/api/buildjobs/6vubnd97hagm5usx/artifacts/windows%2Fpandoc.msi on Windows 64-bit.

**Comment by jgm** [comment]
I confirmed this on a 32 GB EC2 instance.  With the manual intervention to set LARGEADDRESSAWARE, pandoc is killed with OOM error when it gets up to 4 GB.  With an earlier binary (without the manual intervention), it is killed when it gets up to 2 GB.  So, clearly this intervention has an effect, but it still doesn't allow all the memory to be used.

Now I see why; we're using a 32-bit version of stack (which I assume fetches a 32-bit version of ghc).
If we replaced `http://www.stackage.org/stack/windows-i386` in appveyor.yml with `-x86_64`, then I suspect it would all work (and the manual intervention would be unnecessary).

As I see it, these are our alternatives:

1.  Change to using 64-bit Windows binaries in our Windows installers.
2.  Offer users a choice between 64-bit and 32-bit binaries, building both.
3.  Keep offering 32-bit binaries.

Although (2) sounds good, it might be difficult in practice. We'd have to change the appveyor script so that it compiles pandoc twice, with different ghc versions.  Since we're already close to the timeout limit, I don't think this would work.  This also makes deployment more complicated and makes users make a decision.

(3) has the advantage of portability.  The only real disadvantage is that very large files like this one can't be supported on high-memory machines.  (This is a 16MB HTML file!)

As for (1), I'm not sure.  Are there many 32-bit Windows machines out there still?  Would it cause difficulties for users if we no longer provided binaries for them?

**Comment by eubr** [comment]
>Offer users a choice between 64-bit and 32-bit binaries, building both.

I just want to throw an idea out there (that unfortunately doesn't help with appveyor): provide an Advanced section that says something along the lines of (but written better and less condescending):

>If you are not sure about what these builds are for, please use the other downloads. Download this only if you are sure about what it does.

**Comment by eubr** [comment]
As for 1, the only article I can find about concrete numbers is this:

http://news.softpedia.com/news/Microsoft-Explains-Why-Windows-10-32-Bit-Is-Still-Needed-469563.shtml

>As far as statistics are concerned, Aul also reveals that, in December 2014, a total of 70.6 million computers with a 32-bit architecture connected to Windows Update to get the latest patches released by Microsoft.

there is also the steam HW survey: http://store.steampowered.com/hwsurvey

**Comment by jgm** [comment]
For your purposes @eubr I suggest you just compile from source.
Use the [quick stack method](http://pandoc.org/installing.html#quick-stack-method) which only requires you to install one thing (stack -- use the 64-bit version).
This will take quite a bit of disk space, for the compiler and all the dependencies, but it should work.

**Comment by jgm** [comment]
@eubr I've tried setting up a dual-architecture build system. Do you want to try the 64 bit binaries here?
https://ci.appveyor.com/project/jgm/pandoc/build/1.0.1204/job/epuyjhsljqqw5fma/artifacts

**Comment by eubr** [comment]
Thanks for your work! It took a while, and my computer reached 97% memory usage, then pandoc dropped to 0 memory usage, then started climbing again, got to 24GB... then managed to terminate succesfully!

The epub seems to be unreadable. As soon as I try to turn page in calibre's viewer, it freezes. This is obviously not pandoc's fault though.

What surprises me though is that pandoc needed 24GB of memory to convert a 60MB html. That's 400x. Is this expected in general, or might there be something about this file worth investigating?

**Comment by jgm** [comment]
I think this is consistent with what we're measuring in #3169.  Pandoc is currently a bit of a memory hog, and it would be good to improve that in the future.

**Comment by jgm** [comment]
Note; running `tidy -e` on the input file shows a large number of HTML errors.
I see, for example, lots of `</p>` tags with no corresponding `<p>` tag.
It's possible that this is contributing to the problem.

**Comment by gitkrax** [comment]
I just add my two cents to note that I also encountered this problem trying to convert html files with large images included. The set of files was sufficiently large that converting the images to smaller ones was impractical. Having a 64 bit version available would've helped in that case.

**Comment by sharpe5** [comment]
To add my two cents - if the pdf file grows to 1000 pages, then PanDoc simply won't work, as it exits with an out-of-memory error every time.

The 64-bit version of PanDoc mentioned above works - but this version is no longer compatible with generating reports under R in RStudio. The reason? The PanDoc switch has changed from "--latex-version" to "--pdf-version" when going from v1 to v2, which breaks backwards compatibility, which prevents me from using the only 64-bit build that I can find.

All in all, I think that a 64-bit version of PanDoc is essential to handle large .pdf files.

**Comment by agusmba** [comment]
@sharpe5 I remembered reading a solution for your problem (calling pandoc2 as if it was pandoc1), check [this](https://github.com/dalibo/pandocker/blob/master/pandoc.sh) out.
I guess you'd need to put this script in your path so that it is found before the original (and you'd probably need to use the full path for the pandoc binary in the script, or configure RStudio to call this script instead of pandoc proper...).

I haven't tested this, I just thought it could help you a bit.

**Comment by jgm** [comment]
I've changed the appveyor script so it builds both a 32 and a 64 bit version.
When the build completes, you can grab the 64 bit build from artifacts.
If this works, I need to make some revisions to the packaging procedure.

**Comment by sharpe5** [comment]
Oh wow, thats just fantastic - stellar work!

I was prepared to write the hacky batch file, but this is much more elegant - and I get to use the latest version!

**Comment by jgm** [comment]
OK, I'm going to try releasing both 32- and 64-bit windows binaries at the next release.
