### ISSUE TITLE
Support \xspace command

### ISSUE THREAD

**Issue by schrieveslaach** [jgm/pandoc#3681]
The `\xspace` command in LaTeX is a very useful command in order to add spaces when they will be needed. For example, following code defines a document with nice spaces and saves to write additional braces (c.f. colon at the end).

```latex
\documentclass[a4paper,11pt]{article}
\usepackage[utf8]{inputenc}
\usepackage{xspace}

\begin{document}

\newcommand{\cicd}{CI/CD\xspace}

Software developers create \cicd pipelines to… Following issue can be resolved by \cicd:

\end{document}
```

The plain text look like this.

```
Software developers create CI/CD pipelines to… Following issue can be resolved by CI/CD:
```

Is it possible that pandoc supports this behaviour?

**Comment by jgm** [comment]
I don't see why not.

**Comment by schrieveslaach** [comment]
I tried to implement it. I had a solution which works for following LaTeX code (I think something with `notFollowedBy noneOf ".:,"`).

```latex
Software developers create CI/CD\xspace{}pipelines to… Following issue can be resolved by CI/CD\xspace{}:
```

However, when `\xspace` is used in a macro, this solution did not work. I assume, that you cannot look up what comes after a macro. Right?

**Comment by jgm** [comment]
The problem is that we currently handle macros by expanding the macro, then parsing the expanded contents as a string.  This means that the environment following the macro is not accessible when we're parsing the expanded `\xspace`.

See #982, #984.  If we instead expanded macros by altering the input stream (using `setInput`), this problem would be solved (as well as some of the others).  The main difficulty is that we'd lose accurate source position information for errors, though perhaps we could fix this by inserting special commands that the parser uses to reset source position.

**Comment by schrieveslaach** [comment]
Thanks for this clarification. 👍 

Do you have any plans of fixing #982 in near future?

**Comment by schrieveslaach** [comment]
@jgm, I saw your commit 0feb750 fixing #982. I tried to implement the `\xspace` command but I'm confused with the new API. I something like this (does not compile):

```haskell
doxspace :: PandocMonad m => LP m Inlines
doxspace = do
  return (try $ satisfyTok startsWithLetter >> space) <|> mempty
  where startsWithLetter (Tok _ Word t) =
          case T.uncons t of
               Just (c, _) | isLetter c -> True
               _ -> False
        startsWithLetter _ = False
```

I want to return a space when `\xspace` is in front of letter, otherwise it should return nothing (mempty). Can you help me out?

**Comment by jgm** [comment]
I think you must intend something like

```haskell
    (space <$ lookAhead (satisfyTok startsWithLetter)) <|> return mempty
```

>

**Comment by schrieveslaach** [comment]
Thanks! That works. See pull request 😉
