### ISSUE TITLE
Extraneous line break before \begin{align}, \begin{equation}, \begin{eqnarray}

### ISSUE THREAD

**Issue by dataopt** [jgm/pandoc#3726]
I have the following pandoc markdown:

```
# This is my book

This is an equation:
\begin{equation}
y+2 = 3
\end{equation}

This is a system of equations:
\begin{align*}
x^2+y^2 & = 2 \\
\sin(y) & = 0.5
\end{align*}

This is Euler's formula:
\begin{eqnarray*}
e^{i\pi} + 1 & = & 0.
\end{eqnarray*}
```

pandoc outputs the following LaTex with an extra line feed before each of the three environments:
```
\section{This is my book}\label{this-is-my-book}

This is an equation:

\begin{equation}
y+2 = 3 
\end{equation}

This is a system of equations:

\begin{align*}
x^2+y^2 & = 2 \\
\sin(y) & = 0.5
\end{align*}

This is Euler's formula:

\begin{eqnarray*}
e^{i\pi} + 1 & = & 0.
\end{eqnarray*}
```

The extra line feed leads to too much gap between the sentence and the environment that follows it.

**Comment by mb21** [comment]
`\begin{equation}` starts a new paragraph and as such there is necessarily a gap there, this is not a bug. You can customise the layout by modifying your LaTeX template, feel free to ask on pandoc-discuss...

**Comment by dataopt** [comment]
If one modifies the latex output quoted above to the following and run `pdflatex`, the extra gap disappears in the PDF output.  So the issue here is that pandoc inserted a blank line that is not necessary.

```
\section{This is my book}\label{this-is-my-book}

This is an equation:
\begin{equation}
y+2 = 3 
\end{equation}

This is a system of equations:
\begin{align*}
x^2+y^2 & = 2 \\
\sin(y) & = 0.5
\end{align*}

This is Euler's formula:
\begin{eqnarray*}
e^{i\pi} + 1 & = & 0.
\end{eqnarray*}
```

**Comment by jgm** [comment]
This is because the equation environment is parsed as raw
LaTeX, and LaTeX blocks are emitted in the output with blank
lines between them.

If you put it in `$$..$$`, you'll get proper display math as
part of the paragraph, but of course you can't use the
equation environment inside `$$..$$`.

+++ Kevin Cheung [Jun 07 17 07:48 ]:

**Comment by dataopt** [comment]
Thanks for the clarification, John.  Would it be feasible to add an option that suppresses the padding of blank lines around LaTex blocks?

**Comment by jgm** [comment]
It's not that simple, @dataopt, because at least sometimes we need the blank lines (e.g. between paragraphs).  A better solution would be to teach pandoc that `\begin{equation}...\end{equation}` can sometimes be inline, rather than block, latex.  And in fact we've already done that in master.  Here's what I get for the original sample above with pandoc dev version, `pandoc -t latex`:

```
\hypertarget{this-is-my-book}{%
\section{This is my book}\label{this-is-my-book}}

This is an equation: \begin{equation}
y+2 = 3
\end{equation}

This is a system of equations: \begin{align*}
x^2+y^2 & = 2 \\
\sin(y) & = 0.5
\end{align*}

This is Euler's formula: \begin{eqnarray*}
e^{i\pi} + 1 & = & 0.
\end{eqnarray*}
```
As you can see, the blank lines are gone.

**Comment by ak9** [comment]
I've run into this issue, which is quite cumbersome from an automation point of view.
Have the changes you mention, @jgm, been applied to release versions of pandoc yet, or is there a plan to do so?

**Comment by ak9** [comment]
Ah, I realised that it's likely because I'm using math environments that are not recognised as "inline-able": namely, using flalign gives always block behaviour when it should be inline.

**Comment by jgm** [comment]
We could consider adding flalign to the list of `inlineEnvironments` in T.P.Readers.LaTeX.Math, but please submit a separate issue.
