### ISSUE TITLE
RST reader produces headers below top level

### ISSUE THREAD

**Issue by labdsf** [jgm/pandoc#3750]
The bug is similar to the one fixed in Muse reader in PR #3749 

As a result, conversion to FB2 may produce an "unexpected header in section text":

```
pandoc -f rst -t fb2 <<EOF
 - a

   b
   ---
EOF
```

**Comment by jgm** [comment]
Not sure about this.  docutils' rst2html.py will simply abort on this input with a severe error.  We don't do that; pandoc's general approach is not to exit with an error (though we might rethink that).

Since this is invalid RST anyway, is it terrible if pandoc interprets it as having a header inside a list item?

I can see more reason to be concerned about pandoc's RST *writer*, if it produces this.

**Comment by labdsf** [comment]
> pandoc's general approach is not to exit with an error (though we might rethink that).

Well, in my example pandoc exits with an error because FB2 writer does not expect headers inside a list

I have not checked with rst2html. If it is invalid RST then ok, I just though it may be better to just parse --- as something else, like text "b ---", or abort with an error. Header inside a list item just does not make sense.

**Comment by jgm** [comment]
OK, it's really more an issue with the FB2 writer then, since in some formats you certainly can have headers inside lists.  I've changed the writer so it handles this more gracefully.

**Comment by labdsf** [comment]
Ok, I tested it, now it outputs `[info] Not rendering Header 1 ("b",[],[]) [Str "b"]` if `--verbose` is used.

With Muse reader it is a bug in Muse reader, through.
