### ISSUE TITLE
Markdown to odt: image captions are missing

### ISSUE THREAD

**Issue by jondo** [jgm/pandoc#376]
I am using pandoc 1.8.2.1 (from cabal) and LibreOffice 3.4.4 on Windows 7.

**Comment by andrewheiss** [comment]
Has there been any progress on ODT captions?

**Comment by lierdakil** [comment]
@andrewheiss well, there is #570, which is seemingly abandoned and has some problems. I'll make it a priority to look at this when I get some time. Probably sometime this month. Doesn't look too complicated.

**Comment by andrewheiss** [comment]
Yeah, all related ODT caption issues seem to have died out. Thanks for checking on it—it'll be nice to not have to convert to Word first or manually add the missing captions after.

**Comment by lierdakil** [comment]
I've played around with this, and I have a question: should I try to make it as, e.g. libreoffice, with frames and everything, or would doing it like in docx will do? (i.e. placing an image and just adding a caption line underneath)

Because frames are weird, and I'd like to avoid those if possible (well, not entirely possible, since I can't put an image without a frame, but I can avoid nested frames -- those are quite terrifying and hard to get right).

Also, does your version of Open-/Libreoffice honor "Keep with next paragraph" style option? (found in paragraph style under 'Text Flow') Because seems like mine does not (libreoffice 4.4.2.2)

**Comment by andrewheiss** [comment]
Doing it like it is in docx is fine, with styles named "Image caption" and "Table caption," etc.

LibreOffice 4.4.0.3 honors "Keep with next paragraph" for me on OS X 10.10.3.

**Comment by lierdakil** [comment]
Okay then, #2070 should work somewhat satisfactory. If you have additional comments, please leave those directly on PR.

**Comment by andrewheiss** [comment]
Awesome—thanks! I look forward to the PR going through!
