### ISSUE TITLE
Missed normalisation opportunity for emphs separated by spaces

### ISSUE THREAD

**Issue by bucklereed** [jgm/pandoc#3788]
In HEAD:
```
echo '<em>hello </em><em>world</em>' | pandoc -f html
<em>hello</em> <em>world</em>
```

This could be `<em>hello world</em>`, unless I'm mistaken? Note that the first emphasis's boundary in the input is after the space, so pandoc is already doing a transformation that doesn't preserve spaces' and emphases' relative ordering.

**Comment by jgm** [comment]
This is intentional.  It comes from the HTML reader's use of extractSpaces: "Extract the leading and trailing spaces from inside an inline element and place them outside the element.  SoftBreaks count as Spaces for these purposes."  The reason we do this is that in some formats, like Markdown, emphasis delimiters can't border a space.  See #1146 for the motivation.

**Comment by jgm** [comment]
It's true that in principle we could normalize better in your case, while still extracting spaces in other cases.  But that's not possible the way we're currently doing things in the parser, and I don't see that this is an urgent issue.
