### ISSUE TITLE
Markdown highlighting doesn't seem to do much

### ISSUE THREAD

**Issue by okdana** [jgm/pandoc#3812]
**Markdown input:**  
~~~markdown
```markdown
*Testing* **Markdown** _syntax_ `highlighting`
```
~~~

**HTML output:**  
~~~html
<div class="sourceCode"><pre class="sourceCode markdown"><code class="sourceCode markdown">*Testing* **Markdown** _syntax_ <span class="bn">`highlighting`</span></code></pre></div>
~~~

Please compare GitHub's own highlighting of the input to Pandoc's output. Pandoc doesn't seem to highlight any of the Markdown syntax except for the back-ticks (`.bn`). Am i misunderstanding the expected behaviour? It should highlight the other stuff too, right?

Replicated with pandoc 1.19.2.1 from Homebrew as well as the [on-line test thing](http://pandoc.org/try/). Behaves the same way when using `~~~` instead of `` ``` ``.

Thank you!

**Comment by jgm** [comment]
This really should go in jgm/skylighting, since skylighting is the library that does the highlighting.

Skylighting cosntructs highlighters from kate (KDE) syntax descriptions.  If you look at the xml file for markdown, you'll see

```xml
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="common" defStyleNum="dsNormal"/>
      <itemData name="strongemphasis" defStyleNum="dsNormal" italic="true" bold="true"/>
      <itemData name="emphasis" defStyleNum="dsNormal" italic="true"/>
      <itemData name="strong" defStyleNum="dsNormal" bold="true"/>
      <itemData name="ruler" defStyleNum="dsNormal" bold="true"/>
      <itemData name="strikeout" defStyleNum="dsNormal" strikeOut="true"/>
      <itemData name="linebreak" defStyleNum="dsNormal" underline="true" color="#999999"/>
```

and this shows what the problem is.  Skylighting only uses the `defStyleNum` information, so emphasis gets parsed as a "normal" token.  The additional style information `italic=true` is not used.

The same problem affects rendering of LaTeX, which uses the bold and italic attributes.

I decided early on to just use the `defStyleNum`, which gives semantic information about the types of various tokens, in order to make the output completely configurable -- styles determine whether a `dsKeyword` is rendered as bold, italics, what color, etc.  If we let the style information be hard coded, that can interfere with the user's ability to style.  But it might be worth supporting at least the italic and bold attributes.

**Comment by okdana** [comment]
Oops, i'm sorry for filing against the wrong repo. Should've looked harder for the right place.

>I decided early on to just use the defStyleNum, which gives semantic information about the types of various tokens, in order to make the output completely configurable -- styles determine whether a dsKeyword is rendered as bold, italics, what color, etc. If we let the style information be hard coded, that can interfere with the user's ability to style.

I assume the distinction is that `defStyleNum` can be used to associate an HTML class with the token, whereas the other attributes would have to forcibly set `style="font-weight: bold;"` or similar?

For my part, i'm not bothered about the element styling — whether bold is actually rendered bold or not, it doesn't matter, i was just hoping for a class/element to select for.

Would it not be feasible to simply assign some unused token style (like `dsAnnotation`) to the tokens in question? Or is that a semantic concern?

**Comment by jgm** [comment]
I've messed around with the necessary changes in skylighting, but I'm not convinced they're a good idea.  They change output in a number of programming languages, and some of the changes don't look like improvements to me.  Still considering it though -- there's a `moreformatting` branch now in jgm/skylighting.

Note: with pandoc 2.0 you'll be able to specify a custom xml highlighting file for your syntax (markdown in this case).  You can simply change the itemdata element so that different classes are associated with italic, bold, etc.

Note also that kate's highlighting of Markdown is pretty bad.  Indented paragraphs in lists get treated as code.  I prefer not to use highlighting at all for Markdown.  After all, it's designed to be easy to read on its own.

**Comment by okdana** [comment]
Yeah, i can imagine that hard-coding formatting styles might be problematic. I generally dislike syntax-highlighters that screw with the text style, myself — i prefer to limit it to just colours.

A future option to provide a custom highlight file would work well for me. And it's not a big deal anyway, i just thought maybe it was an over-sight. I would not at all be bothered if you decided to just leave it. Thank you either way!

**Comment by jgm** [comment]
I think I'll just leave it for now.  Thanks.
