### ISSUE TITLE
backslash-escape does not work in markdown_github

### ISSUE THREAD

**Issue by cnblogs-dudu** [jgm/pandoc#3850]
Pandoc version: 1.19.2.1

Command line used: 
```shell
pandoc -f markdown_github+tex_math_dollars -t html --mathjax
```

Complete input:
```
\$test\$
```
Actual output:
```
<p>\$test\$</p>
```

Expected:
```
<p>$test$</p>
```

It woks in the following command line. 
```shell
pandoc -f markdown+tex_math_dollars -t html --mathjax
```

**Comment by cnblogs-dudu** [comment]
Command line used: 
```shell
pandoc -f markdown_github -t html
```

Complete input:
```
|test|test|
|:-------|------:|
-v \| --verbose | test2 |
```

Actual output:
```html
<table>
<thead>
<tr class="header">
<th align="left">test</th>
<th align="right">test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">-v \</td>
<td align="right">--verbose</td>
</tr>
</tbody>
</table>
```

Expected:
```html
<table>
<thead>
<tr class="header">
<th align="left">test</th>
<th align="right">test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">-v | --verbose</td>
<td align="right">test2</td>
</tr>
</tbody>
</table>
```

It woks in the following command line. 
```shell
pandoc -f markdown -t html
```

**Comment by jgm** [comment]
This is because markdown_github doesn't include the
`all_symbols_escapable` extension.  (You can turn it
on using `markdown_github+all_symbols_escapable`.)

Why doesn't it?  Because, until fairly recently,
GitHub's Markdown didn't allow you to backslash-escape
the $.  After all, $ is not a special character in
GitHub's Markdown.

Recently, though, GitHub switched to CommonMark, and
$ is again escapable.  The upcoming pandoc 2.0 includes
a `gfm` output format that should render things exactly
lie GitHub (since it uses the same underlying library).

We could add `all_symbols_escapable` to the
`markdown_github` extensions, but going forward,
`markdown_github` is going to be deprecated anyway
in favor of `gfm`.

**Comment by jgm** [comment]
Same thing here.  Backslash-escaping behavior changed quite
a bit when GitHub adopted CommonMark.  pandoc 2.0 will have
an accurate GitHub-based Markdown reader as `gfm`.

**Comment by cnblogs-dudu** [comment]
Thanks.  `markdown_github+all_symbols_escapable` works.
