### ISSUE TITLE
PandocParsecError handler displays wrong line

### ISSUE THREAD

**Issue by labdsf** [jgm/pandoc#3865]
PandocParsecError handler, as defined in src/Text/Pandoc/Error.hs, exctacts input source and position from PandocParsecError. Input source is [set by readWithM](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Parsing.hs#L1025). The problem is that if the error happens inside `parseFromString`, the source is different. And error handler extracts wrong line:

```
$ pandoc -f muse
First
Second
Third
<em>Foo

actual error is here</em>
^D
Error at "chunk" (line 3, column 1):
unexpected 'a' or '\n'
expecting lf new-line, end of input or inline
Third
^
```

It should show third line of `<em>` tag, but it shows third line of stdin.

^D is the end of input where I pressed Ctrl + D.
Current commit is 41baaff32737e57dd9ec0a1153416ca24a12dca1, just for reference.

**Comment by jgm** [comment]
Yes, this is a known issue when using `parseFromString`.
Note that the error is reported as occurring in "chunk", which is a signal that the line numbering is relative to a string chunk.  By itself, that's not very informative, of course.

Maybe we need a `parseFromString` variant where you can set the start position.  Then, your parser would do something like:

```
  pos1 <- getPosition
  raw <- getRawContent
  parseFromStringWithPos parser pos1 raw
```

**Comment by labdsf** [comment]
Maybe just pass current position inside. Or, even better, maintain both absolute position and relative position (the last we already have).

**Comment by jgm** [comment]
+++ Alexander [Aug 22 17 16:49 ]:
>   Maybe just pass current position inside. Or, even better, maintain both
>   absolute position and relative position (the last we already have).

Current position is almost always wrong, because we normally
call parseFromString AFTER parsing the raw string -- so the
current position is actually at the end of the section to
be parsed, and we want the beginning.

We could try to get tricky and calculate  the start position
from the current position and the raw string, but I don't
think this will work in most cases, since the raw string is
often processed from the original (prefixes removed,
sometimes blank lines, etc.).

**Comment by jgm** [comment]
Hm, due to changes in the muse reader, the initial example no longer allows you to reproduce the problem.

**Comment by labdsf** [comment]
@jgm that is why I left commit reference at the end of first message.

**Comment by jgm** [comment]
Right, but it would be nice to have some way to reproduce the issue with the current dev version (for tests etc.)

**Comment by labdsf** [comment]
Just though, maybe we should avoid reading text into a string and parsing it with `parseFromString`. That is how most parsers parse lists now, but maybe we can deal with indentation better, without two-pass approach when we first remove it and parsing the resulting string again.

**Comment by jgm** [comment]
Yes, parseFromString is better to avoid when you can.
But it's complex to avoid it everywhere, especially in
Markdown where you have laziness.  (I managed to write
a CommonMark parser that handles list indentations without
this sort of thing, but the algorithm is imperative and
not easily ported to Haskell.)

+++ Alexander [Nov 18 17 14:14 ]:

**Comment by labdsf** [comment]
@jgm I see you have also implemented some parsers using PEG. Is it any better then parser combinators when dealing with this problem?

By the way Haskell itself has the same problem, and it solves it by introducing an intermediate step, which deals specifically with indentation.

**Comment by jgm** [comment]
+++ Alexander [Dec 11 17 15:24 ]:
>   [1]@jgm I see you have also implemented some parsers using PEG. Is it
>   any better then parser combinators when dealing with this problem?

It's not a problem with parser combinators, just with the
particular way we're doing the parsing.

The most straightforward solution would be to have an
initial tokenization step, so that instead of parsing raw
text, we convert the text into a list of tokens, each
carrying information about the source location.

We do this now in the LaTeX reader, and it gives us much
better error messages.

It would be a lot of work, though, to convert all the other
readers to use this style, and it's not clear it would be
worth it.
