### ISSUE TITLE
extension table_captions produces the table caption twice from docx to markdown

### ISSUE THREAD

**Issue by tolot27** [jgm/pandoc#3874]
Consider the follwing simple table example:

```markdown
: A simple table

-------
     12
-------
```

If it gets converted to docx with the command `pandoc -t docx+table_captions -o table_captions.docx table_captions.md` and than converted back to markdown with the command `pandoc -t markdown+table_captions -o table_captions2.md table_captions.docx`, the table caption is doubled:

```markdown
A simple table

  ----
  12
  ----

  : A simple table
```

I would expect that if the extension `table_caption` is enabled, a paragraph formated as `Table Caption` will just be converted once to the appropriate markdown table caption syntax.

**Comment by jgm** [comment]
We changed the docx writer without making a corresponding change in the reader. @jkr How hard would it be to make the reader look for a paragraph with the TableCaption style in front of a table, and parse it as the table's caption?

**Comment by jkr** [comment]
Not hard at all, I think. I'll take a look.On Aug 24, 2017 9:11 PM, John MacFarlane <notifications@github.com> wrote:We changed the docx writer without making a corresponding change in the reader. @jkr How hard would it be to make the reader look for a paragraph with the TableCaption style in front of a table, and parse it as the table's caption?

**Comment by tolot27** [comment]
I believe, the reader already looks for a TableCaption style because it produces `  : A simple table` out of the docx if the extension is enabled (`pandoc -t markdown+table_captions`). But it does not remove the plain text.

**Comment by tolot27** [comment]
Interesting, the reader source does not contain tableCaption specific code.

**Comment by tolot27** [comment]
@jkr Did you have a look at this issue? Is it harder to fix?

**Comment by jkr** [comment]
There's no `+table_captions` extensions in the docx writer. (I guess it's the default?) So it's actually the writer that doubles it: one in a paragraph, and one in the table caption field. The reader reads both.

In fact, we should probably only read the paragraph with `TableCaption` class. Note though that when I try to add a caption with Word 2013, it produces it with the `Caption` class instead.

So, how about this: don't read the `w:tblCaption` val, and read paragraph with `Caption` field before after. And read `TableCaption` as well? Or change the writer to writer `Caption` style too?

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Mar 05 18 09:30 ]:
>   There's no +table_captions extensions in the docx writer. (I guess it's
>   the default?) So it's actually the writer that doubles it: one in a
>   paragraph, and one in the table caption field. The reader reads both.
>
>   In fact, we should probably only read the paragraph with TableCaption
>   class. Note though that when I try to add a caption with Word 2013, it
>   produces it with the Caption class instead.
>
>   So, how about this: don't read the w:tblCaption val, and read paragraph
>   with Caption field before after. And read TableCaption as well? Or
>   change the writer to writer Caption style too?
>

Sounds reasonable. Not sure why we use Caption instead of
TableCaption in the writer, but I'm guessing there's a
reason I've forgotten...which might be revealed by a grep of
the changelog or git log.

**Comment by tolot27** [comment]
According to [Table Properties] (https://msdn.microsoft.com/en-us/library/documentformat.openxml.wordprocessing.tableproperties.tablecaption.aspx), `w:tblCaption` is only available in Word 2010. Beginning with Word 2013, `w:Caption` is used. Hence, we should read `w:Caption` first. If not available, try to read `w:tblCalption`. The writer should write `w:Caption` only, unless we want to support old versions of Word.

**Comment by jkr** [comment]
Okay, so it seems like (a) the writer should write text with a `w:val=Caption` pstyle, and we should update the styles.xml, and (b) we should read from the that text, and not the w:tblCaption field. I'd be curious to see how many `w:tblCaption` vals there are in the wild, but since any recent version of word will ignore it altgother it would probably just make sense for us to ignore it too.

We should also decide, as a matter of convention, what to do if there's a `w:Caption` paragraph above and below a table. Word will never produce that, but you could produce that in pandoc using, say, custom-styles. Let's say, in that case, the top one will be a caption, and the bottom one will be a paragraph (with `custom-style=Caption`, if  `+styles` is turned on). It's possible then that roundtripping would flip which one is a caption, but there's no way for us to no.

I'll hope to implement this this weekend.

**Comment by danse** [comment]
The situation for an image caption in an OpenXML document is similar to this. i'm not sure why you write that word will never put that styled paragraph, it does put styled paragraphs when it comes to image captions, which are currently not correctly converted to figures.

While preparing to work on captions for images i noticed that there is room for improvement by [unifying some data models](https://github.com/italia/pandoc/commit/04a900b4555a03de424ccb63d4b59b1b346bb9e5) and thanks to that [reusing some logic](https://github.com/italia/pandoc/commit/d89994c9a15316e0e48b0f9d7179d7a28460c05b).

The topic of image captions is different, but i'm mentioning it here because it might help us to spot bigger patterns or opportunities to reuse the code, especially considering that in both cases a `Caption` style is used. Currently it's possible to correctly convert an OpenXML image+caption by enabling styles and applying [this filter](https://github.com/italia/pandoc-filters/blob/master/filters/figure.hs#L19)

**Comment by tolot27** [comment]
@jkr Did you run into further issues during implementation?

**Comment by jgm** [comment]
this seems no longer to be an issue (pandoc 3.3). closing.
