### ISSUE TITLE
dash and ellipsis in Chinese

### ISSUE THREAD

**Issue by Stone-Zeng** [jgm/pandoc#3893]
In Chinese language, one should use two em-dashes (`U+2014`) to typeset a Chinese dash (or 破折号, `——`). When using pandoc, it will parse a Chinese dash into `------`. However, it will lead to the symbol be typesetted with normal font, not cjk font. In an ordinary cjk font, there should be no space between two em-dashes, while a common western font  (used fot Latin script or etc) will not do this.

For Chinese ellipsis (or 省略号, `……`), things are similar. The normal way is to use two horizontal ellipsis (`U+2026`), but pandoc will change it into `\ldots{}\ldots`.

You may find the difference in the following pictures:

![default](https://user-images.githubusercontent.com/18233088/30001155-9448566e-90b7-11e7-9d6e-ab330423019c.PNG)

Example code:

```markdown
<!-- test.md -->

# Chinese dash
汉字 —— 汉字

# Chinese ellipsis
汉字 …… 汉字
```

I use the follwing settings:
```bat
pandoc test.md ^
  --verbose ^
  --latex-engine=xelatex ^
  --variable mainfont="Linux Libertine O" ^
  --variable CJKmainfont="Source Han Serif SC" ^
  --output=test.pdf
```
The main part in the generated TeX files is the following:

```latex
\begin{document}

\section{Chinese dash}\label{chinese-dash}

汉字 ------ 汉字

\section{Chinese ellipsis}\label{chinese-ellipsis}

汉字 \ldots{}\ldots{} 汉字

\end{document}
```

The result is

![2](https://user-images.githubusercontent.com/18233088/30001183-dbc84458-90b8-11e7-927a-29477fa1d9ec.PNG)

PS: For some fonts (e.g. Latin Modern), the difference between them are not so obvious, so I use Linux Libertine O here.

**Comment by wilx** [comment]
How would those be rendered correctly if you were writing it in LaTeX directly?

**Comment by Stone-Zeng** [comment]
I will just type in `——` and `……` as I have shown in the markdown code above. Most of the [Chinese input methods](https://en.wikipedia.org/wiki/Chinese_input_methods_for_computers) have this function.

Note: these two symbols may not display correctly on your computer due to the lack of high-quality cjk fonts.

**Comment by wilx** [comment]
Maybe you could input the [TWO-EM DASH](http://www.fileformat.info/info/unicode/char/2e3a/index.htm) character directly. Then the rendering depends on availability of the character in the font.

**Comment by wilx** [comment]
It seems to me this can work just fine if you use the correct font. I have just tried with [Source Han Serif](https://github.com/adobe-fonts/source-han-serif) (TTC) for both `mainfont` and `CJKmainfont` and it seems to work well.

![screenshot_2017-09-03_15-19-10](https://user-images.githubusercontent.com/1098563/30003301-745360ac-90bb-11e7-8f59-b36a1c0c1e7e.png)

**Comment by Stone-Zeng** [comment]
That's a good idea. However, Source Han Serif doesn't have italic or slant shape and it's very rare to include an italic or slant shape in a cjk font family. That's why I only use it as `CJKmainfont`.

And how about the ellipsis?

**Comment by wilx** [comment]
[**@Stone-Zeng**](https://github.com/Stone-Zeng) commented on [Sep 3, 2017, 3:34 PM GMT+2](https://github.com/jgm/pandoc/issues/3893#issuecomment-326805330 "2017-09-03T13:34:53Z - Replied by Github Reply Comments"):
> Thank you for your help. However, Source Han Serif doesn't have italic or slant shape and it's very rare to include an italic or slant shape in a cjk font family. That's why I only use it as `CJKmainfont`.
> 
> Another thing is that `TWO-EM DASH` is not easy to input...

Well, it seems to me that you will have to do some post-processing of either the Markdown source, or of the generated LaTeX source, or both, to get better than the initial result.

**Comment by ickc** [comment]
A few notes:

- when you say pandoc parse them into `------` and `\ldots{}\ldots`, have you tried to use `--no-tex-ligatures` to turn off this conversion?

- It is true that unicode 2-em dash might be better, if it can be typed easily. If you use text expansion, then I would recommend you to auto-replace 2 em dashes to 2-em dash.

- Note that for any given CJK fonts, you can apply fake-slant and fake-bold to generate a slanted of bolded variants of the font. But, I understand that auto-generated fonts are not beautiful. You can experiment with different parameters for a relatively larger sample of Chinese characters to see if they look acceptable to you.

- Another notes on CJK font is, even if there's a provided slanted variants, because they are slanted, often time it doesn't distinguish the slanted and not slanted characters enough. In western typography, sometimes it is advised to not use the "italic" font on san serif font because their "italic" is often just slightly slanted. This is because of the same reason: it doesn't offer much visual distinction between normal characters and "emphasized" italic characters. So to apply the same rule to Chinese characters, slanted might be avoided for the same reason, and hence only normal and bold should be used.

    - If this ruled is followed, there's only 2 levels of emphasis (with and without), in the case of more emphasizing levels are needed, we'll hope to find a font that has more weights available (e.g. 400, 500, 700 or 400, 700, 900). If not, may be using auto-bold in LaTeX to fake it through again.

    - On the other hand, sometimes we need to ask ourselves if that many of levels of emphasis is really needed. e.g. ***italic and bold*** is a legitimate level of emphasis, but is sometimes discouraged in typography. *italic* might be useful in some subtle emphasis, but without which we could still do fine.

P.S. I wish the situation of Chinese typography is easier. But the availability of good quality, free (in both sense) fonts is really limited. The original beauty of Chinese characters becomes a burden and ugliness in the digital word. I mean, the number of combinations makes it so difficult in many ways. In this sense, simplified Chinese is even worse because it has no beauty but the digitization problems remain. Romanized Chinese could solves the digitization problem, but then it takes away all the beauty and culture of Chinese. Another problem might be that Chinese has practically no history in typography (*I might be wrong though*). Modern Chinese punctuation doesn't exist until less than a century ago. And it seems to me in more "ancient" Chinese writing, they didn't concern about the typography as in the western sense. So while Chinese characters ("the fonts") are more advanced, typographically it is premature if existed at all (well, it is true that some typography rules doesn't make sense in Chinese since the characters are of equal width and size, and there's no space).

**Comment by Stone-Zeng** [comment]
@ickc Thank you for your comment. And now my solution is to use a simple python script to process the generated TeX files.

**Comment by ickc** [comment]
Then should this issue be closed? You can click the close issue button below.

By the way, if you use UNIX, you can also use sed. Something like

```bash
sed -e 's/------/——/g' -e 's/\\ldots{}\\ldots/⋯⋯/g'
```

**Comment by Stone-Zeng** [comment]
Actually, I did more things than the simple replacement in the script, e.g. to ensure that `\TeX` and `\LaTeX` can display normally in `\section` etc.

**Comment by Stone-Zeng** [comment]
More information about the `\TeX` etc:

Macros in `\section` will be ignored via `\texorpdfstring`. For example, `## History of \TeX` will be parsed as `\section{\texorpdfstring{History of \TeX}{History of }}`. I just simply remove the complicated things in this situation (when section title has `\TeX` or `\LaTeX`), so it becomes `\section{History of \TeX}`. With specific packages such as `hologo`, it will display correctly in PDF bookmarks.
