### ISSUE TITLE
LaTeX Reader: \newcommand not parsed when it's in a file included through \input{file.tex}

### ISSUE THREAD

**Issue by mb21** [jgm/pandoc#3971]
Tried to convert the pretty complex LaTeX from <https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/ctfp.tex>

    git clone git@github.com:hmemcpy/milewski-ctfp-pdf.git
    cd milewski-ctfp-pdf/src
    pandoc ctfp.tex -o book.epub

(There are probably more interesting cases in there, including an "unexpected end of input".)

But what caught my interest were the `[warning] Skipped '\code{f}'`. They don't appear if I move the `\newcommand{\code}[1]{\texttt{#1}}` to the main file.

**Comment by jgm** [comment]
I tried a simple example where the code macro is defined in an
included file, and it worked. Something more complicated is
going on here, maybe specific to this preamble.tex.  It
would be good to track this down!  (And in general this
would be a good case for finding other issues.)

Here's a simple case that has problems: 

``` {file=a.tex}
\documentclass{article}
\include{b}
\code{f}
\end{document}
```

``` {file=b.tex}
\newcommand{\code}[1]{\texttt{#1}}
\begin{document}
```

With `pandoc a.tex` we get: 

```
Error at "source" (line 1, column 15):
unexpected {
\documentclass{article}
``` 

which is a crazy message.  If we remove the documentclass
command, we get: 

```
Error at "b.tex" (line 2, column 17):
unexpected end of input
expecting \end{document}
\code{f}
```

If we put the `\begin{document}` and `\end{document}` in
the same file, it works just fine.

You can see that `\input` is implemented using
`insertIncludedFile`.  This is a function (from Parsing)
that takes a block parser as argument.  It reads the
file, resets the source position with the name of the new
file, parses the file, and resets the source position before
returning the blocks.

So, it won't work when we have only half an environment in
the included file.

I think I did it this way (rather than simply adding the
contents of the included file using setInput) because
this way we can accurately report source positions in
included files.  But it has the drawback we see above.

I think that in the case of the LaTeX reader, we could
(and should) do better.  For the LaTeX reader uses a
tokenized representation of the input, with each token
containing its own source information.  So with the
LaTeX reader we really could just tokenize the contents
of the included file and add the new tokens with setInput.
And I think we should do that.
