### ISSUE TITLE
Option or extension to set bullet spacing

### ISSUE THREAD

**Issue by willfaught** [jgm/pandoc#3981]
Currently, pandoc does this:

```
$ echo "- a\n- b\n- c\n" | pandoc -f markdown -t markdown
-   a
-   b
-   c

$
```

Note the extra two spaces between the bullets and their text.

I would expect the original text, since it's valid Markdown:

```
$ echo "- a\n- b\n- c\n" | pandoc -f markdown -t markdown
- a
- b
- c

$
```

Note the single space between the bullets and their text.

I've searched the entire man page, and nowhere is this list syntax normalization behavior documented. Maybe I missed it, but if I did, it's too hard to find in my experience. Infuriatingly, the pandoc man page shows Markdown formatting that pandoc doesn't produce, and doesn't mention this:

```
   Lists
   Bullet lists
       A bullet list is a list of bulleted list items.  A bulleted list item begins with a bullet (*, +, or -).  Here is a simple example:

              * one
              * two
              * three
```

Again, here's that actual Markdown outputted by pandoc:

```
$ echo "* one\n* two\n* three\n" | pandoc -f markdown -t markdown
-   one
-   two
-   three

$
```

Note that it also doesn't preserve the asterisk syntax, but that's a separate (but related) issue.

I'm all about sane defaults and consistency, but things like this should at least be overridable, since the input is valid Markdown in any interpretation.

Since pandoc changes valid Markdown, you can't use it to simply verify that text conforms to a certain Markdown flavor. For example, say you want to check whether text files are GitHub-flavored Markdown. You can't just run pandoc against a file and see if anything changes, because it's going to re-format all the (well-formed) lists.

I understand that the extra bullet spaces align multiple paragraphs in a single list item, which is a nice thing, but it does this at the expense of efficiently writing single-paragraph list items. The list syntax is *twice* as long with 3 spaces, compared to 1 space. It's a repetitive-stress injury waiting to happen. You can't assume that pandoc will be available where/when the Markdown is written to normalize it.

Multiple-paragraph list items are the exception, not the norm, in my experience. I would think the default should favor the norm, but can we at least get an option or extension to favor it? In other words, can we get an option or extension to preserve or set the bullet spacing?

Even better, if the formatter automatically preserved the list syntax, then the author could simply write whatever syntax works best for the list content.

**Comment by jgm** [comment]
See the discussion at https://groups.google.com/d/msg/pandoc-discuss/MCeUEKUwujo/FvrUNlwDBQAJ for background on why pandoc does this.

I'm not inclined to add an option for this.  There are many, many different individual preferences about these matters of Markdown style.  Some people like lists like
```
  - a
  - b
```
some like
```
- a
- b
```
some like
```
-   a
-   b
```
Then there's the question of which bullet to use, `-`, `+`, or `*`?

I could list about 2,000 other little features of Markdown documents that aren't preserved by pandoc in Markdown -> Markdown conversions.  Adding options for all of them would be insanity.  Building information about these things into the AST doesn't make sense, given pandoc's goals.  Pandoc was not designed to be a Markdown reformatter.  It can serve as one only if you're happy with its defaults.

As for repetitive stress: it's easy to configure your editor so that you can type `-` + TAB and get the spaces you need.

**Comment by willfaught** [comment]
Thanks for linking to my question. I should have done that.

>Pandoc was not designed to be a Markdown reformatter. It can serve as one only if you're happy with its defaults.

Makes sense. Thanks for responding!
