### ISSUE TITLE
Slide columns in reveal.js

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc#4028]
I'm testing the multi-column slides in pandoc 2.0.1 and do not see what I would expect.

```
## Columns

:::::::::::::: {.columns}
::: {.column width="40%"}
left column content
:::
::: {.column width="60%"}
right column content
:::
::::::::::::::
```

Yields this [slide], but I don't see any columns....? Am I supposed to add additional CSS somewhere?

[slide]: http://reagle.org/joseph/talks/2014/exemplar.html#/columns

**Comment by mb21** [comment]
This was added in https://github.com/jgm/pandoc/commit/892a4edeb1c9b9810c8386e639d8e457bbae7e86
Let me note a few things:

- The current output would work if there was no space or newline between the two inner divs in the HTML source. As it is, the math works out as `40% + 60% + width-of-one-space > 100%`, thus the two inline-blocks aren't on the same line.
- The `width` attribute is actually not allowed on divs by validators, should it be `data-width`?
- The `.column{...}` CSS should probably be added to `epub.css` as well.

**Comment by jgm** [comment]
Reopening to reconsider two issues:

+ Why is some CSS on the style attribute and some in the template in .column?

It's not possible to move it all to the template, because some varies with the width attribute.  But we could dispense with the CSS in the template and put the `display: inline-block` in the style attribute of the tag. Is there a reason to do this?

+ The `.column{...}` CSS should probably be added to epub.css as well.

Yes, unless we decide to put it in the style tag.

**Comment by mb21** [comment]
Agreed, the `width` has to go on the style attribute. But is the `min-width` necessary? Usually, it's good practice to put as much CSS as possible behind classes (i.e. in the template in our case). Then other CSS can also override it if necessary (and it's easily customisable by modifying the template).

So maybe the CSS should look like this, with only `width` potentially overriden by a style attribute if the user specifies a width on the div.

```
.column {
  width: 50%;
  display: inline-block;
  vertical-align: top;
}
```

**Comment by reagle** [comment]
Works, thank you!
