### ISSUE TITLE
Pandoc v2.0.1: Crash if Strikeout in MD Heading

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#4038]
If I try to convert from gfm to gfm a heading with strikedout text, pandoc crashes.

Example document:

``` markdown

# ~~Heading~~

```

... will fail with `pandoc -f gfm -t gfm` on Win 10 x64:

```
>pandoc -f gfm -t gfm TEST.md
Assertion failed!

Program: C:\Users\XXXX\AppData\Local\Pandoc\pandoc.exe
File: cbits\commonmark.c, Line 467

Expression: false

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

I won't fail when converting from gfm to HTML. I haven't tested all possible combinations, but this crash must be a bug since the same doc is converted to HTML without errors.

**Comment by jgm** [comment]
The problem is that the github fork of commonmark only implements extensions for the commonmark reader, not the commonmark writer.  For tables and definition lists, I worked around this by constructing raw chunks manually, but it looks like I forgot to do the same for strikethrough.  Should be pretty easy to fix.
