### ISSUE TITLE
<img src="foo.png" /> stopped working for EPUB output in Pandoc 2.0

### ISSUE THREAD

**Issue by yihui** [jgm/pandoc#4055]
This might be a regression caused by #3720. Here is a minimal reproducible example: [test.zip](https://github.com/jgm/pandoc/files/1454951/test.zip).

```markdown
---
title: Test images
---

Here is an image.

<img src="test.png" />
```

![image](https://user-images.githubusercontent.com/163582/32566733-7a36f23a-c47e-11e7-9f32-fa1ccc846b78.png)

The image cannot be found if the EPUB output is generated by `pandoc -o test.epub test.md`. One workaround is `pandoc -o test.epub --epub-subdirectory= test.md`.

```bash
$ pandoc --version
pandoc 2.0.1.1
Compiled with pandoc-types 1.17.2, texmath 0.10, skylighting 0.4.3.2
```

**Comment by jgm** [comment]
This is essentially the same issue as #4050.

Note: the epub writer is 2.0.1.1 has problems.  These are
fixed in HEAD and I'll try to do a new release soon.
The "workaround" you mention won't work after the fix
(because --epub-subdirectory wasn't doing what it was
advertised as doing).

There might be residual issues.  I suggest you compile
HEAD from source (stack install) and test with that.
(Or use pandoc-nightly.)

**Comment by jgm** [comment]
Yes, there's still a bug that I need to fix even in the dev version.

**Comment by yihui** [comment]
Okay, I'll remove the workaround after the new release. Thanks!
