### ISSUE TITLE
Windows 10 chocolatey pandoc memory leak?

### ISSUE THREAD

**Issue by jdshkolnik** [jgm/pandoc#4129]
I installed pandoc with chocolatey and am at version 2.04. Any attempt to use pandoc, even something like "pandoc -v" results in an ever-growing list of pandoc.exe processes which can only be stopped by killing the process tree or rebooting.

![image](https://user-images.githubusercontent.com/2047520/33734940-d696f496-db5b-11e7-9b5f-b8d72ee9ea92.png)

**Comment by jgm** [comment]
I haven't had any other reports like this.  Can anyone else
who uses Windows confirm this?

I also don't know anything about chocolatey, or how their
binary is generated and installed.  This may have something
to do specifically with chocolatey.  Can you try removing
the chocolatey-installed pandoc and installing instead
from the msi we provide?  If the pandoc from the msi works,
that is evidence that the issue is chocolately-related.

Another thing is to make sure you're running the real
binary and not, e.g., a shell script that calls it.

+++ John D. Shkolnik [Dec 07 17 11:35 ]:

**Comment by jgm** [comment]
Note:  "shimgen" is part of chocolatey:
https://github.com/chocolatey/shimgen
I really suspect the issue here is with chocolatey, which seems to be calling pandoc with a shell script, rather than pandoc itself.

**Comment by jdshkolnik** [comment]
You're right, it looks to be related to Chocolatey's pandoc package. Thanks.
