### ISSUE TITLE
Enable --dpi flag for wkhtmltopdf

### ISSUE THREAD

**Issue by adius** [jgm/pandoc#4142]
It's possible to set a `--dpi` flag for wkhtmltopdf, but the pandoc general writer flag `--dpi` does not get translated yet.
Should be supported just like pandoc's `--variable margin-top:5mm` is already supported.

**Comment by mb21** [comment]
I'm not absolutely sure that pandoc's and wkhtmltopdf's `dpi` flags always indicate exactly the same thing. In pandoc, it's currently only used to convert cm and inches to px (or vice versa) when scaling images. 

What exactly does it do for wkhtmltopdf? How does it relate to `--zoom`? (There is also `--image-dpi` which presumably resamples images without changing their size on the page?)

**Comment by bob-marcus** [comment]
@mb21 The `dpi` flag is pretty much necessary on Windows to have good font kerning, otherwise the final document is very hard to read.
Compare this document created by the command `pandoc lorem.txt --pdf-engine=wkhtmltopdf -o loremnodpi.pdf`
[loremnodpi.pdf](https://github.com/jgm/pandoc/files/5417476/loremnodpi.pdf)
and this document created with the commands
```
pandoc lorem.txt -o lorem.html
wkhtmltopdf.exe --dpi 200 lorem.html lorem200dpi.pdf
```
[lorem200dpi.pdf](https://github.com/jgm/pandoc/files/5417486/lorem200dpi.pdf)
The second document is much more readable. [See this for further information](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/45#issuecomment-307340493).

**Comment by alerque** [comment]
This should be fixed on `wkhtmltopdf`'s end of things. If the defaults are as bad as you say then they should be fixed at the point where they are bad defaults!

By the way your "200dpi" output has nothing to do with DPI *per se*, the entire document layout is completely different. I think it did some sort of canvas zoom operation, it certainly didn't just change the resolution that things were output as both examples have vector shapes anyway! The ugly first example just has atrociously bad kerning, probably due to some misguided attempt to "hint" the output for a certain tiny size (even though the output is vector not raster!).

**Comment by mb21** [comment]
> The dpi flag is pretty much necessary on Windows 

you can do:

    pandoc --pdf-engine wkhtmltopdf --pdf-engine-opt=--dpi=200

**Comment by michaelfreiberg** [comment]
`pandoc --pdf-engine wkhtmltopdf --pdf-engine-opt=--dpi=200` did not work in my case (Win 10 cmd, pandoc 2.18, wkthtmltopdf 0.12.6). I had to pass --pdf-engine twice.

`pandoc -t html -o out.pdf in.txt --pdf-engine-opt="--dpi" --pdf-engine-opt="300"`
