### ISSUE TITLE
Please use Semantic Versioning

### ISSUE THREAD

**Issue by jondo** [jgm/pandoc#4149]
I suggest that Pandoc should use [Semantic Versioning](https://semver.org/), to make the version numbers easier understandable.

I see that none of 2.0.1 to 2.0.5 were pure bugfix releases. When do you plan to use "2.1.0"?
When you want to avoid high numbers, you can still jump from e.g. 2.19 to 3.0 (similar to [what the Linux kernel did](http://www.zdnet.com/article/linux-kernel-turns-over-release-odometer-to-4-0/)).

**Comment by mb21** [comment]
AFAIK pandoc follows more or less https://pvp.haskell.org/, i.e. `EPOCH.MAJOR.MINOR.PATCH`

**Comment by jondo** [comment]
I see. So it's basically like SemVer with an additional epoch prefix and leaving out the patch levels of ".0"; and "2.1.0" will have incompatible API changes.

Still, normal users from outside the Haskell ecosystem will falsely interpret "2.0.5" as `MAJOR.MINOR.PATCH`.

**Comment by mb21** [comment]
Yeah, I guess @jgm should decide whether to stick to PVP and if so communicate this in the README or somewhere...

**Comment by jgm** [comment]
We're using the versioning policy that is common in the  Haskell world and expected for packages published on  Hackage:  <https://pvp.haskell.org>.  This isn't going to change.

I'm not so worried about people from outside the Haskell ecosystem, because only people who are using pandoc as a Haskell  library will need to worry about API compatibility, and they will be coming from within the Haskell ecosystem.

**Comment by jondo** [comment]
As long as people's output (and command line) does not break when switching to 2.1.0 ...

**Comment by jgm** [comment]
+++ Robert Pollak [Dec 15 17 22:24 ]:
>   As long as people's output (and command line) does not break when
>   switching to 2.1.0 ...

To be clear, the versioning is based on the Haskell library
API, as per the versioning policy.  It doesn't give you any
information about command-line behavior.
