### ISSUE TITLE
Performance degradation in pandoc 2.0.6

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#4216]
Pandoc 2.0.6 seems to be ~30% slower than 2.0.5:

    % time ( ./pandoc-2.0.5 MANUAL.txt  -t json >/dev/null )
    ( ./pandoc-2.0.5 MANUAL.txt -t json > /dev/null; )  0.44s user 0.02s system 98% cpu 0.479 total

    % time ( ./pandoc-2.0.6 MANUAL.txt  -t json >/dev/null )
    ( pandoc MANUAL.txt -t json > /dev/null; )  0.65s user 0.02s system 98% cpu 0.678 total

**Comment by tarleb** [comment]
Seems like this exists since 28b736bf.

**Comment by jgm** [comment]
I can confirm this:

% bench "pandoc-2.0.6/bin/pandoc -t json MANUAL.txt"
benchmarking pandoc-2.0.6/bin/pandoc -t json MANUAL.txt
time                 879.8 ms   (647.3 ms .. 1.254 s)
                     0.980 R²   (0.952 R² .. 1.000 R²)
mean                 975.7 ms   (907.1 ms .. 1.034 s)
std dev              93.77 ms   (0.0 s .. 101.3 ms)
variance introduced by outliers: 22% (moderately inflated)

% bench "pandoc-2.0.5/bin/pandoc -t json MANUAL.txt"
benchmarking pandoc-2.0.5/bin/pandoc -t json MANUAL.txt
time                 745.3 ms   (715.2 ms .. 777.4 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 753.1 ms   (748.6 ms .. 756.8 ms)
std dev              5.878 ms   (0.0 s .. 6.429 ms)
variance introduced by outliers: 19% (moderately inflated)

I note that with the html reader, we get the reverse (2.0.6
faster):

% bench "pandoc-2.0.6/bin/pandoc -t json MANUAL.html"
benchmarking pandoc-2.0.6/bin/pandoc -t json MANUAL.html
time                 738.0 ms   (716.4 ms .. 784.1 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 734.1 ms   (727.5 ms .. 738.8 ms)
std dev              7.120 ms   (0.0 s .. 8.160 ms)
variance introduced by outliers: 19% (moderately inflated)

% bench "pandoc-2.0.5/bin/pandoc -t json MANUAL.html"
benchmarking pandoc-2.0.5/bin/pandoc -t json MANUAL.html
time                 852.1 ms   (830.5 ms .. 868.7 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 857.3 ms   (852.3 ms .. 860.9 ms)
std dev              5.495 ms   (0.0 s .. 6.283 ms)
variance introduced by outliers: 19% (moderately inflated)

With latex reader, 2.0.6 is also faster:

% bench "pandoc-2.0.6/bin/pandoc -t native MANUAL.tex"
benchmarking pandoc-2.0.6/bin/pandoc -t native MANUAL.tex
time                 425.0 ms   (391.8 ms .. 465.9 ms)
                     0.999 R²   (0.996 R² .. 1.000 R²)
mean                 439.1 ms   (431.6 ms .. 446.2 ms)
std dev              12.09 ms   (0.0 s .. 12.38 ms)
variance introduced by outliers: 19% (moderately inflated)

% bench "pandoc-2.0.5/bin/pandoc -t native MANUAL.tex"
benchmarking pandoc-2.0.5/bin/pandoc -t native MANUAL.tex
time                 530.3 ms   (467.7 ms .. NaN s)
                     0.998 R²   (0.995 R² .. 1.000 R²)
mean                 550.8 ms   (536.4 ms .. 562.2 ms)
std dev              17.86 ms   (0.0 s .. 19.84 ms)
variance introduced by outliers: 19% (moderately inflated)


This would all be consistent with your theory
that 28b736bf957da0df79ffb211fc5e7ec4ff713c4b is to blame,
since this mainly affects raw latex in markdown.  And
indeed, when we turn off raw_tex we get a speedup instead
of a slowdown:

% bench "pandoc-2.0.6/bin/pandoc -t json MANUAL.txt -f markdown-raw_tex"
benchmarking pandoc-2.0.6/bin/pandoc -t json MANUAL.txt -f markdown-raw_tex
time                 623.1 ms   (619.3 ms .. 631.2 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 623.6 ms   (622.4 ms .. 624.5 ms)
std dev              1.371 ms   (0.0 s .. 1.568 ms)
variance introduced by outliers: 19% (moderately inflated)

% bench "pandoc-2.0.5/bin/pandoc -t json MANUAL.txt -f markdown-raw_tex"
benchmarking pandoc-2.0.5/bin/pandoc -t json MANUAL.txt -f markdown-raw_tex
time                 745.6 ms   (729.6 ms .. 757.0 ms)
                     1.000 R²   (1.000 R² .. NaN R²)
mean                 739.4 ms   (738.0 ms .. 740.7 ms)
std dev              1.952 ms   (0.0 s .. 2.107 ms)
variance introduced by outliers: 19% (moderately inflated)

+++ Albert Krewinkel [Dec 30 17 01:55 ]:

**Comment by jgm** [comment]
Confirmed that this fixes the problem.  (Indeed, HEAD is now faster than 2.0.5.)
