### ISSUE TITLE
cannot convert math formula correctly when formula was added with Hyperlinks  

### ISSUE THREAD

**Issue by redstoneleo** [jgm/pandoc#4244]
cannot convert math formula correctly when formula was added with Hyperlink -- formula and Hyperlink were removed after converted , tested with the file 
https://drive.google.com/file/d/1cmNvFveVDKIU-ZQYrTACdRAEIa2sY1OQ/view
and the command
`pandoc b.docx -t markdown --wrap=none -o b.md`

**Comment by jkr** [comment]
Hmm... there can be `<w:hyperlinks>` inside `<m:omath>`. It looks like there can be a few other types of tags in there is well (`<w:sdt>`, track-changes stuff). It's easy enough to move it outside if covers the whole thing like this one (`<m:oMath><w:hyperlink...>...</w:hyperlink></m:oMath>`). But I can't tell from the online specs whether it can always be counted on to do that. @jgm, what do you think?

1. go through omath(para) and strip them before handing it off to texmath
2. have texmath take care of the stripping
3. try not to strip -- i.e. in this case move the hyperlink tags outside the omath tags
4. split math tags so we never have to strip. (i.e. if the hyperlink doesn't cover the whole thing, split it so that we have one omath that it does cover, and then move it outside).

**Comment by jgm** [comment]
Easiest approach is probably to have texmath ignore these
tags.

+++ Jesse Rosenthal [Jan 10 18 21:10 ]:

**Comment by jkr** [comment]
Okay -- for now I'll close and submit an issue to texmath. I'll try to put up a PR for the OMML reader in the next day or two.
