### ISSUE TITLE
Selection of code in html documents is impossible for Microsoft browsers

### ISSUE THREAD

**Issue by aubertc** [jgm/pandoc#4278]
**Version:** pandoc 2.0.5, Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.5

**Markdown document:**
```
---
title: Test
---

~~~~~~~{ .numberLines}
pandoc \
	--standalone \
	-t html5 \
    test.md -o test-html5.html
~~~~~~~~~

~~~~~~~{.bash}
pandoc \
	--standalone \
	-t html5 \
    test.md -o test-html5.html
~~~~~~~~~

```

**Command:** `pandoc --standalone -t html5 test.md -o test-html5.html`

**Output:** a `html5` file **where both codes cannot be selected with Microsoft Edge 20.10240 or Internet Explorer 10.240**. The code can be selected (and copied) just fine with any other browsers. 

**Expected output**: The expected output is that the behavior is consistent across browsers, and that the code can alway be selected, preferably without the line numbers, as it is now.

My guess was that something was going wrong with the [CSS `user-select` Property](https://www.w3schools.com/cssref/css3_pr_user-select.asp), but I couldn't find a workaround. Without the `bash` nor `numberLines` selectors, the selection works fine.

**Comment by jgm** [comment]
@dbaynard - here's another issue with the current HTML formatting from skylighting.  Any ideas?

**Comment by aubertc** [comment]
I made my example slightly more minimal.
I'm happy to migrate my bug report to https://github.com/jgm/skylighting/issues if needed.

**Comment by mb21** [comment]
there's a lot of discussion at https://github.com/jgm/pandoc/issues/4128 and https://github.com/jgm/skylighting/issues/32

**Comment by dbaynard** [comment]
I think it might be to do with the `pointer-events: none` call. Unfortunately I don't have access to a windows machine to test.

These were introduced in https://github.com/jgm/skylighting/commit/38f086a0d80e19725fad2b39aee430b5f4c88ba0 so that the line numbers (when clicked) move the page view to the relevant line, but clicking on the rest of the line does not  have that impact. As a side effect, with subsequent changes, it appears code can only be copied in whole lines (this is probably a desirable property).

So @aubertc please try deleting the two uses of `pointer-events` in your example, and if that fixes the issue, we'll open a separate issue on skylighting.

Note: According to [caniuse](https://caniuse.com/#feat=user-select-none) those browsers should support `-ms-user-select` as implemented. `pointer-events` is supported in edge 12 but only from ie 11, so that still doesn't quite explain it.

**Comment by aubertc** [comment]
You were right: if I remove `pointer-events: none` from `a.sourceLine` elements, then the selection is still a bit erratic, but at least it become possible to select the code from my example with both Internet explorer and Edge.

I agree that the property you mention is positive, but breaking completely selection in Microsoft's browser seems a high cost.

**Comment by dbaynard** [comment]
A high cost indeed. Thanks for the report. I've opened jgm/skylighting#33. It might be fixable directly, though I suspect it won't be worth it, in which case I'll restrict the `pointer-events` calls to non-Microsoft browsers.

This appears to be a [confirmed bug in Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8295099/).

**Comment by dbaynard** [comment]
@aubertc Would you try moving the `pointer-events: none` in css to `code.sourceCode` and see if that fixes both selection and the link issue?

**Comment by aubertc** [comment]
If we move `pointer-events: none` to `code.sourceCode`, the bug is still present, probably because `a.sourceLine` inherits from it. If, additionally, we set `a.sourceLine` to have `pointer-events: auto` (thus overriding the inheritance of the `css` property), then the selection is possible, although somehow messy. On the other hand, the whole line becomes clickable, which really isn't that great.

I'm happy to continue testing this issue, but maybe you could fine the following resources to emulate Internet Explorer or Edge of some use:
- https://chrome.google.com/webstore/detail/test-ie/eldlkpeoddgbmpjlnpfblfpgodnojfjl?hl=en
- https://www.browserling.com/
- https://www.browserstack.com/test-on-microsoft-edge-browser#live-cloud

**Comment by aubertc** [comment]
(This may be off topic, but why are there links created when only the `numberLine` option is given in pandoc? I.e., without `lineAnchors`, I would expect the links not to be created.)
