### ISSUE TITLE
ordered list missing from .docx

### ISSUE THREAD

**Issue by ashnur** [jgm/pandoc#4298]
```
$ pandoc --version
pandoc.exe 2.0.6
Compiled with pandoc-types 1.17.3, texmath 0.10.1, skylighting 0.5.0.1
Default user data directory: C:\Users\Aron_Zsolt_Gabor\AppData\Roaming\pandoc
Copyright (C) 2006-2017 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

```
pandoc ./Test2.docx -t json -o Test.json
```

`Test.json` content:
```
{"pandoc-api-version":[1,17,3],"meta":{},"blocks":[{"t":"Header","c":[2,["heading-content",[],[]],[{"t":"Str","c":"Heading"},{"t":"Space"},{"t":"Str","c":"content"}]]},{"t":"OrderedList","c":[[1,{"t":"UpperAlpha"},{"t":"Period"}],[[{"t":"Para","c":[{"t":"Strong","c":[{"t":"Str","c":"Inner"},{"t":"Space"},{"t":"Str","c":"list"},{"t":"Space"},{"t":"Str","c":"heading"},{"t":"Space"}]}]},{"t":"Para","c":[{"t":"Str","c":"Inner"},{"t":"Space"},{"t":"Str","c":"list"},{"t":"Space"},{"t":"Str","c":"content."}]}]]]}]}
```

[Test2.docx](https://github.com/jgm/pandoc/files/1661038/Test2.docx)

Output contains only one list. Input has two.

**Comment by jgm** [comment]
Looks fine to me. The docx has a Heading and a list.

Both come through in the conversion.
```
pandoc -t native Test2.docx
[Header 2 ("heading-content",[],[]) [Str "Heading",Space,Str "content"]
,OrderedList (1,UpperAlpha,Period)
 [[Para [Strong [Str "Inner",Space,Str "list",Space,Str "heading",Space]]
  ,Para [Str "Inner",Space,Str "list",Space,Str "content."]]]]
```
@jkr may be able to comment further about this case.

**Comment by ashnur** [comment]
i am sorry, perhaps we see something different, but the input has 2 lists and just one is coming through. the external one that contains the heading is completely missing. 
![untitled](https://user-images.githubusercontent.com/407934/35353059-42a6f2e8-0146-11e8-8cb6-28dd6aac6d34.png)

**Comment by jkr** [comment]
The docx does have two lists, but the contents of the top one is also a header. We convert one-element header lists to headers, because docx translates nearly all of them to ordered list (as a result of writing a number and period before the header). See 7fe54505df. 

@ashnur -- you meant the top one to be a header? And was it only a one-element list in your document, as in this one? (By the way, `--verbose-docx` output, whatever form that might take, wouldn't solve the issue here.)

Not sure of the best way to deal with this -- the unintentional headers come up *far* more often (like every time users number their headers) than this case.

**Comment by jkr** [comment]
@ashnur, that picture isn't of the document you sent. This is what you uploaded:
![screenshot from 2018-01-24 14-48-54](https://user-images.githubusercontent.com/835121/35353653-d3d645ce-0115-11e8-971b-8b0507686c58.png)

**Comment by ashnur** [comment]
I don't understand why this heavily opinionated take on the semantics of certain structures is not optional. I understand the reasoning behind the feature to be on by default, but as you can see, sometimes it's intentional. I have no control over the contents of the docx. 

I don't actually need the external list, actually i just need to convert these docs to markdown, but because of this `trick` and probably some more like this the original quite organized structure of the docx file gets garbled up in unpredictable ways. Most of the headings remain where they should but some not and that creates "breaks" in the whole structure.

**Comment by jkr** [comment]
The reason why this and other things are not optional is because we can't make a countless number of different command-line options for docx. `Docx -> Markdown` is necessarily lossy, and these were considered decisions.

Now, we'd be willing to engage in discussion about the wisdom of this move (we reconsider decisions all the time). Yet you say here that you "don't need the external list", which would seem to support our initial decision.

You also suggest that there are numerous other things breaking the conversion. Maybe some of them are bugs! I'd love to try to fix them, if so.. Please report the issues if things don't work as you expect. But I'd ask that you proceed with a more polite and collaborative tone.

**Comment by ashnur** [comment]
you are saying docx to markdown is lossy, but this issue is about docx to pandoc ast. i would like to have an option to not lose data from the original structure, because in that case this issue would be absolutely solved without guessing for mistakes and without trying to pinpoint what dozen other things might be confusingly either bugs or features.

i am not sure what you mean by more polite and collaborative tone, i haven't had training in picking tones based on how strangers might find it more or less polite or collaborative, i am doing my best here to convey as much information as possible in as little time as possible

**Comment by jgm** [comment]
Yes, the AST is not as expressive as many of the input formats; hence docx -> AST is a lossy translation, in general.  As for tone, it's always a delicate thing, but remember that pandoc is written and maintained entirely by volunteers, who receive no compensation for the work they put in.  You're asking someone to devote some of their precious time to fixing a problem you have.

**Comment by ashnur** [comment]
I thought it's not just my problem :) I am not asking for anything for myself. I described the issue. You all do whatever you want to do :).
