### ISSUE TITLE
URL Mismatch in Table Of Contents with anchor reference link

### ISSUE THREAD

**Issue by rudi48** [jgm/pandoc#4323]
Problem with web browser **does NOT jump** on mouse click from TOC to anchor.
See: [github.com/rudi48/dso150-110-plot/wiki](https://github.com/rudi48/dso150-110-plot/wiki)

pandoc version 2.1.1
**Command line:**
$ pandoc -f html -t gfm -o JyeTechDSO150.md JyeTechDSO150-rudiswiki9.html

**HTML TOC:**
`<a href="#JYE_Tech_DSO150">JYE Tech DSO150</a><ol><li>`
**Markdown gfm:**
`<li><a href="#JYE_Tech_DSO150">JYE Tech DSO150</a>`

**HTML anchor:**
`</p><h2 id="JYE_Tech_DSO150">JYE Tech DSO150</h2>`
**Markdown gfm:**
```
<span id="line-5" class="anchor"></span>

JYE Tech DSO150
---------------

<span id="line-6" class="anchor"></span>
```

**Chrome/Firefox/Safari:** mouse move over anchor shows as link:
    ...#jye-tech-dso150

Only lower case, and minus for space. So it can not  match the TOC link.

I have solved that by editing the TOC links.

Is there a better solution?

**Comment by jgm** [comment]
The problem is that the gfm output format does not support
attributes on headers.  If you do

    -t markdown

instead, you'll get

    [JYE Tech DSO150](#JYE_Tech_DSO150)

    JYE Tech DSO150 {#JYE_Tech_DSO150}
    ---------------

but of course GitHub doesn't understand the id attribute
on the header, so in gfm output there's no anchor.

We could perhaps modify the gfm writer to insert some
raw HTML with an anchor in this case.

**Comment by rudi48** [comment]
Thank you for taking care about that topic.
I am editing the .md file here on MacOS with MacDown (version 0.7.1).
When I convert with 
`-t markdown`
I will get no **Table Of Contents** (in HTML), which is more effort to restore.
I just thought there might be a better solution, which I overlooked.
Regards, Rudolf

**Comment by jgm** [comment]
+++ Rudi [Jan 30 18 05:14 ]:
>   Thank you for taking care about that topic.
>   I am editing the .md file here on MacOS with MacDown (version 0.7.1).
>   When I convert with
>   -t markdown
>   I will get no Table Of Contents (in HTML), which is more effort to
>   restore.

Did you try with --toc -s ?
That will give you a Markdown table of contents.

**Comment by rudi48** [comment]
Thank you for your help.
Unfortunately --toc -s did not help to create a markdown TOC. My command line:
`$ pandoc -f html -t markdown --toc -s -o dso150-110-plot.md http://www.rudiswiki.de/wiki9/JyeTechDSO150`

Regards, Rudolf

**Comment by jgm** [comment]
`--toc` doesn't work here because your section headers are embedded in divs.
I'm not sure I see any good automated solution for you.  If you target `gfm`, then your links to headers should use the auto-generated ids that GitHub supports.  For
```
JYE Tech DSO150
---------------
```
that would be `jye-tech-dso150`.  It probably wouldn't be too hard to create a perl script or something that modifies the IDs in your HTML input so that they conform to this.
