### ISSUE TITLE
EPUB reader can’t fetch images with spaces in file path

### ISSUE THREAD

**Issue by labdsf** [jgm/pandoc#4344]
How to reproduce:

1. Convert any text with images to EPUB using pandoc.
2. Open produced EPUB as ZIP archive, rename "media/file0.png" to "media/file 0.png" and change corresponding URL in EPUB/text/...
3. Try to convert EPUB to FB2 with pandoc: `pandoc 1.epub -o 1.fb2 -s`
4. Get warning: `[WARNING] Could not fetch resource 'media/file%200.png': PandocResourceNotFound "media/file 0.png"`

**Comment by mb21** [comment]
I cannot reproduce this with pandoc 2.1.1
Please reopen with an attached epub if you can reproduce it.

**Comment by labdsf** [comment]
1. Download [1.zip](https://github.com/jgm/pandoc/files/1800451/1.zip)
2. Run `pandoc -f epub 1.zip -o 1.fb2`

**Comment by danse** [comment]
I found a similar problem with the ODT reader, in this case the `--extract-media` option is needed in order to trigger the error.

1. Download [4344.odt.zip](https://github.com/jgm/pandoc/files/1897875/4344.odt.zip)
2. Rename `4344.odt.zip` to `4344.odt`
3. Run `pandoc --extract-media media 4344.odt`

A warning similar to the issue topic is visible. It's followed by a fatal error which can be unrelated and i am investigating separately

**Comment by mb21** [comment]
My guess would be that the bug is somewhere in [downloadOrRead](https://github.com/jgm/pandoc/blob/937bec95a970dfef2c7623561b4d0892399523dc/src/Text/Pandoc/Class.hs#L576)...

**Comment by danse** [comment]
untestable code is always in the front row among the culprits ;)

**Comment by jgm** [comment]
Not really untestable; you can just use fetchItem,
which doesn't do much besides call this function.

**Comment by danse** [comment]
wow hadn't realised that it's all wrapped in the Pandoc monad :100:
