### ISSUE TITLE
org-mode: allow emphasis in brackets

### ISSUE THREAD

**Issue by mclearc** [jgm/pandoc#4378]
right now emphasis is backslash escaped when converting from org to other formats rather than being properly translated into the correlated emphasis. For example:

`echo '[/emph/]' | pandoc -f org -t markdown` produces   `\[/emph/\]` instead of `[*emph*]`. I recognize that there should be no expectation of feature parity with markdown conversion, but I hope you might consider this a feature request.

As it stands priority of this is relatively low since one can simply use latex (e.g. `[\emph{emph}]`) as a work around.

**Comment by tarleb** [comment]
This behavior is consistent with the way Emacs orgmode interprets this input.  Exporting `[/emph/]` via orgmode gives me the same, literal string in any chosen output format. This is due to org-mode's (sometimes weird, IMHO) rules of what should be considered part of a word – emphasis *within* a word is disallowed in orgmode, and square brackets are treated as part of a word.

I don't think we should deviate from Emacs behavior without good reason, so I'm closing this for now.

**Comment by tarleb** [comment]
I might have been a bit hasty in closing this. It *would* be nice if this would work. In Emacs, this can be achieved by changing the variable `org-emphasis-regexp-components`. It would be nice if the org reader offered a customization method to get similar results.

**Comment by mclearc** [comment]
thanks! and I should have said that I have changed `org-emphasis-regexp-components` to allow `[]` with emphasis, which is how I discovered the issue (I put it below in case that is helpful to anyone). Thanks for considering it!

```
(with-eval-after-load 'org
; chars for prematch
(setcar org-emphasis-regexp-components            "     ('\"{“”\[\\") 
; chars for postmatch
(setcar (nthcdr 1 org-emphasis-regexp-components) "\] -   .,!?;''“”\")}/\\“”") 
; forbidden chars
(setcar (nthcdr 2 org-emphasis-regexp-components) "    \t\r\n,\"")
; body
(setcar (nthcdr 3 org-emphasis-regexp-components) ".")
; max newlines 
(setcar (nthcdr 4 org-emphasis-regexp-components) 1)
(org-set-emph-re 'org-emphasis-regexp-components org-emphasis-regexp-components))
```

**Comment by tarleb** [comment]
What would be a good way to customize this in pandoc? I'm currently experimenting with special lines à la

    #+pandoc-emphasis-pre: "-\t ('\"{["
    #+pandoc-emphasis-post: "-\t\n .,:!?;'\")}[]"
    [/emph/]

Should give you the expected result. The main benefit of this approach would be that changes can be made for the whole document or just for some paragraphs and then changed back to another value if desired.

Does this seem like a reasonable approach?  Is there an alternative method you have in mind?

**Comment by mclearc** [comment]
That seems pretty flexible. Given that different people are likely to have different views on which emphasis markers to use, etc., the per-document proposal might be best. It would be nice to have a global setting too, but this is pretty easy to put into a metadata template.

**Comment by tarleb** [comment]
Ok, one more thing to think about: what happens if the arguments to these special lines are not valid strings? a) Do nothing, b) restore the default, c) throw an error.  So far I've implemented b), but a) seems reasonable, too.

Also: were should this to be documented?  The manual is already pretty long, so maybe a separate document on special pandoc org-mode features?

**Comment by tarleb** [comment]
I've opened #4387 so I won't forget to write the missing documentation.

**Comment by mclearc** [comment]
Sorry for not responding sooner - agreed that either a) or b) seems reasonable. Seems like the biggest thing would be predictability so reverting to the default seems fine. And also agreed that separate documentation would be great. As of now I end up doing word searches on pandoc releases just to try to get a sense of what's happing with org-mode.
