### ISSUE TITLE
.odt bullets misplaced horizontally

### ISSUE THREAD

**Issue by kuba-orlik** [jgm/pandoc#4385]
Using: 

```
# echo "* element 1
* element 2" | pandoc --from=markdown --to=odt > odt.odt
```
Gives the following result:

![selection_085](https://user-images.githubusercontent.com/2697916/36501074-71426bd0-1746-11e8-8a56-ce9d1f904b04.png)

^ The bullet is too far to the left, leaving an awkard space.

The default spacing in Libreoffice is much nicer, and gives more ergonomic results:

![selection_088](https://user-images.githubusercontent.com/2697916/36501080-747dca7e-1746-11e8-9049-e284bb888d39.png)

I'm not saying that pandoc should make everything look same as Libreoffice does by default, but that in this particular case bringing the bullet closer to the text of the list element kind of makes sense.

The style difference basically boils down to "Indent" and "Width of numbering" style properties for list elements. In Libreoffice, it's 0.25''/ 0.25'': 

![selection_087](https://user-images.githubusercontent.com/2697916/36501177-b58b6080-1746-11e8-9a3a-844d5fb9d521.png)

Whereas the odt output from pandoc gives 0.00''/ 0.40''

My pandoc version:

```
pandoc 2.0.6
Compiled with pandoc-types 1.17.3.1, texmath 0.10.1.1, skylighting 0.5.0.1
```

**Comment by kuba-orlik** [comment]
To make the case for readability - compare the usability of these two outputs:

![selection_089](https://user-images.githubusercontent.com/2697916/36501537-aa57b60e-1747-11e8-9c3d-609193f3c521.png)

![selection_090](https://user-images.githubusercontent.com/2697916/36501542-acf370a6-1747-11e8-8058-62f3c0f4fa2c.png)

**Comment by Jmuccigr** [comment]
If I make an odt file with your input and then add my own list after it, here's what they look like in the content.xml file from the odt (after xml tidy):

```xml
      <text:list xml:id="list2755162617" text:style-name="L1">
        <text:list-item>
          <text:p text:style-name="P1">one</text:p>
        </text:list-item>
        <text:list-item>
          <text:p text:style-name="P1">two</text:p>
        </text:list-item>
      </text:list>
      <text:list xml:id="list971299886" text:style-name="L2">
        <text:list-item>
          <text:p text:style-name="P3">One</text:p>
        </text:list-item>
        <text:list-item>
          <text:p text:style-name="P3">two</text:p>
        </text:list-item>
      </text:list>
```

If I change that text:style-name from P1 to P2 on the first, pandoc-generated list, it now is indented like mine. (If I check the odt list preferences, I also see a bullet-20 character instead of the default "bullet", which is just a little different, and of course the changed position, which is what you're noticing.)

I don't know much about the odt xml files, but I do see that related topics have come up before, e.g., #910, so this may be a little complicated.

Perhaps though, the OpenDoc writer can modify this line to use the standard bullets?:

`                    , ("text:style-name" , "Bullet_20_Symbols")`

**Comment by Tagirijus** [comment]
Having the same issue with version 2.3.1. Are there at least any workarounds for now?
