### ISSUE TITLE
LaTeX writer: image with % height attribute uses \textwidth not \textheight

### ISSUE THREAD

**Issue by jpcirrus** [jgm/pandoc#4389]
```bash
$ pandoc --version
pandoc 2.1.1
```

An image is specified with a % height attribute:

```markdown
![Image caption.](image.jpg){height=40%}
```

The resulting LaTeX from the command:

```bash
pandoc demo.md --output=demo.tex --standalone
```

is:

```latex
\includegraphics[width=\textwidth,height=0.4\textwidth]{image.jpg}
```

where the height is a % of `\textwidth` not `\textheight`.

**Comment by danaukes** [comment]
Hi, this fix has broken pandoc for me.

Former use case: I had markdown files which got converted either to html or pdf.  By supplying a percentage in the width I could scale the size of images up or down while keeping the aspect ratio.  The output format didn't matter, this worked the same.

Now, unless I calculate the desired output image in pixels myself, I will get different aspect ratios for documents converted to html or pdf.  This is because % in html is relative to the image, not the box it is in.

**Comment by mb21** [comment]
Make sure you're not using a custom LaTeX template, or set up graphicx like in the default template...

> I will get different aspect ratios for documents converted to html or pdf.

which has the correct aspect ratio? can you post a sample image input and what's wrong with the output?

**Comment by jgm** [comment]
@danaukes if you're having problems with aspect ratio, this is addressed in the manual and [here in the FAQs](http://pandoc.org/faqs.html#when-i-specify-an-image-width-of-50-and-convert-to-latex-pandoc-sets-the-height-to-textheight-and-the-aspect-ratio-isnt-preserved-how-can-i-prevent-this).

But I think maybe your issue isn't about aspect ratio, but about what "50%" means in the different formats.  Manual says (quoting):

> The `%` unit is generally relative to some available space. For example the above example will render to the following.
> - HTML: `<img href="file.jpg" style="width: 50%;" />`
> - LaTeX: `\includegraphics[width=0.5\textwidth,height=\textheight]{file.jpg}` (If you’re using a custom template, you need to configure graphicx as in the default template.)
> - ConTeXt: `\externalfigure[file.jpg][width=0.5\textwidth]`

If what you're saying is right, this is misleading, because width 50% doesn't mean "use 50% of available space" in HTML.  If I understand you right, you're saying that you'd prefer 'width=50%' to mean 50% of the natural image size in all formats.

Anyway, please don't continue this discussion here, in a closed issue where nobody will see it.  If you want to continue the discussion, please post on pandoc-discuss as suggested in CONTRIBUTING.md.

**Comment by mb21** [comment]
@jgm, the percentage unit is quite weird but quite flexible in HTML/CSS, that's why the manual is vague and says "The % unit is generally relative to some available space."
