### ISSUE TITLE
Custom writers Lua file relative requires paths

### ISSUE THREAD

**Issue by ehildenb** [jgm/pandoc#4393]
I looked through to see if this issue already has been reported, let me know if I missed something.

When using a custom `writer.lua`, if the writer includes another Lua file, the include is taken relative to the directory that `pandoc` is run in, not in the directory that the file `writer.lua` is in.

For reference, in the below example, `script.lua` is the same as `tangle.lua`, except the `requires` lines have been flattened so that `script.lua` contains the contents of `utilities.lua`, `css-selector.lua`, and `tangle.lua`.

Steps to reproduce:

```sh
mkdir scratch
git clone 'https://github.com/ehildenb/pandoc-tangle'
cd pandoc-tangle
git checkout one-script

# works as expected
pandoc --from markdown --to tangle.lua --metadata=code:.sh test/doc1.md

# also works
pandoc --from markdown --to script.lua --metadata=code:.sh test/doc1.md

# go up a directory
cd ..

# does *NOT* work
pandoc --from markdown --to pandoc-tangle/tangle.lua --metadata=code:.sh pandoc-tangle/test/doc1.md

# does work
pandoc --from markdown --to pandoc-tangle/script.lua --metadata=code:.sh pandoc-tangle/test/doc1.md

# move the included files to current directory
mv pandoc-tangle/utilities.lua ./
mv pandoc-tangle/css-selector.lua ./

# now *DOES* work (and probably shouldn't)
pandoc --from markdown --to pandoc-tangle/tangle.lua --metadata=code:.sh pandoc-tangle/test/doc1.md
```

On a side note, I'm curious about why the Lua package is included in the `pandoc` codebase, instead of being separated out into its own codebase.

**Comment by jgm** [comment]
> On a side note, I'm curious about why the Lua package is included in the pandoc codebase, instead of being separated out into its own codebase.

I'm not sure I understand the question.  Pandoc links in hslua, which is a Haskell interface to the lua interpreter.  Since static linking is the default for ghc, this means that the lua interpreter is statically linked into the pandoc binary. This is pretty convenient, because it means you can always use lua filters and custom writers without worrying about external dependencies.  But it is possible to compile hslua with a flag that tells it to use the system lua interpreter instead.

@tarleb, do you have thoughts about the include path issue?

**Comment by tarleb** [comment]
If I understand correctly, then the issue is that Lua writers should have a way to access script-relative files. That does seem like a desirable feature. We currently discard all information on the writer-path before calling Lua. Maybe we can store the path in a global variable like `PANDOC_SCRIPT_FILEPATH` and/or `PANDOC_SCRIPT_DIRNAME`.

@ehildenb for the time being, your best option, is to set `LUA_PATH` to include your *pandoc-tangle* directory, e.g.

    LUA_PATH='pandoc-tangle/?.lua;;' pandoc --from=markdown --to=pandoc-tangle/tangle.lua …

or

    export LUA_PATH='/absolute/path/to/pandoc-tangle/?.lua;;'
    pandoc --from markdown --to pandoc-tangle/tangle.lua …

**Comment by ehildenb** [comment]
@jgm ahhh, sorry, I read "Pandoc comes with its own Lua interpreter" somewhere in the docs and assumed the worst, but I should have looked at the code instead.

and @tarleb that seems like a reasonable and acceptable solution to me. Would it be difficult for `pandoc` to just set that environment variable appropriately before calling `hslua`?
