### ISSUE TITLE
Mention --self-contained does not affect Templates

### ISSUE THREAD

**Issue by jidanni** [jgm/pandoc#4399]
The man page should mention --self-contained does not affect Templates,
which will still include
```
    <script src="//cdnjs.cloudflare...
````
etc. So maybe add an --offline.
This --offline option would ensure all the intended baggage is downloaded by pandoc and plopped in the current directory, so the HTML will be 100% usable later offline.
(Actually one would rather want a --pure-html which would not included such baggage in the first place.)

**Comment by mb21** [comment]
The Manual actually says:

> Limitation: resources that are loaded dynamically through JavaScript cannot be incorporated; as a result, --self-contained does not work with --mathjax, and some advanced features (e.g. zoom or speaker notes) may not work in an offline “self-contained” reveal.js slide show

**Comment by jgm** [comment]
`--self-contained` actually does operate on the HTML document produced after the template is integrated.  So, it does apply to things in templates.

However, there is one line in the default template that includes an HTML5 shiv for IE 9:
```
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
```
This won't be handled by `--self-contained`, because it's in a comment, but that probably won't matter unless you've got a very old (and unsupported) Windows browser.

**Comment by jidanni** [comment]
Good. Be sure to document that.
