### ISSUE TITLE
pandoc command param --epub-cover-image generate fail

### ISSUE THREAD

**Issue by friends110110** [jgm/pandoc#4416]
I wanna generate docx from markdown files(a.md,b.md,c.md) ,and insert into the conver picture, I can use --epub-cover-image.
then command:
`pandoc -s a.md b.md c.md -o example.docx --epub-cover-image cover.png` 

It generate example.docx file, but the cover.png does not insert into the docx file ?

pandoc --version
pandoc 2.1.1
Compiled with pandoc-types 1.17.3.1, texmath 0.10.1, skylighting 0.6

**Comment by tarleb** [comment]
The `--epub-cover-image` option only has an effect on epub output, not when writing docx.

Issues like these, i.e., questions rather than bugs or feature requests, are best asked on the pandoc-discuss mailing list as noted in the [contributor guide](https://github.com/jgm/pandoc/blob/master/CONTRIBUTING.md).

**Comment by friends110110** [comment]
But how to generate cover-image in docx
