### ISSUE TITLE
FB2 writer: output blockquotes after headings as epigraphs

### ISSUE THREAD

**Issue by link2xt** [jgm/pandoc#4428]
Any quote or right after heading is, almost certainly, an epigraph. FB2 has a special tag for epigraphs, which is currently not used by FB2 writer.

Poems also can be epigraphs, but they should only be converted to epigraph if the are inside a blockquote. Otherwise we risk accidentally converting collections of poems with headings into collections of epigraphs.

**Comment by jgm** [comment]
I'm not persuaded we should do this.  It violates expectations if the FB2 writer treats this as an epigraph, but e.g. the LaTeX writer doesn't.  I wouldn't be against having the FB2 writer treat a div with class "epigraph" specially, though.

**Comment by labdsf** [comment]
@jgm 

DocBook reader reads epigraphs as blockquotes and most lightweight formats (RST is an exception) have ways to typeset quotes but not epigraphs. Requiring an epigraph class will make it impossible to typeset proper epigraphs in most lightweight markups and there are existing texts with epigraphs typeset as blockquotes.

> It violates expectations if the FB2 writer treats this as an epigraph, but e.g. the LaTeX writer doesn't.

Nothing wrong happens if some format treats epigraphs as simple blockquotes. It is less than perfect (no right-alignment etc.) but still readable.

> I wouldn't be against having the FB2 writer treat a div with class "epigraph" specially, though.

Need to add classes to blockquotes then or add support for such divs to all other formats, otherwise they will become plain paragraphs. But what I dislike the most about this approach is that it requires user to manually markup blockquotes at the beginning of a section as epigraphs, while it is possible to automatically detect them: epigraph is a quote at the beginning of a section by its definition.

**Comment by jgm** [comment]
My thought is that, if we adopt the "implicit over explicit" approach, we should treat block quotes at the start of a section as epigraphs everywhere, not just in the FB2 writer.  Otherwise the meaning of the source document varies with the writer.

Whether we should do this, I'm not sure.  It does have a certain appeal, but it also makes it impossible to start a section with a normal block quote -- do we really want to remove the ability to do that?  Perhaps this should be discussed on pandoc-discuss.
