### ISSUE TITLE
combine consecutive Str

### ISSUE THREAD

**Issue by tolot27** [jgm/pandoc#4456]
As discussed in https://groups.google.com/forum/#!topic/pandoc-discuss/0nO13bdD4Iw, there are cases when AST elements are changed in a way (i. e. using a filter) that `Str`s are returned which are not separated from a previous `Str` i. e. by a `Space`. One example is the acceptance/rejection of track changes. A subsequent filter which expects combined words (i. e. "foobar") will not find them if they were split into two consecutive strings. Also, a word counter would return a smaller number of words.

**Comment by tolot27** [comment]
A general solution for this problem would be, if the Lua subsystem would compare the class of a filter result with the previous elements class (taking attributes into account) and would merge them if they are equal.

**Comment by labdsf** [comment]
I am doing it in Muse writer, mostly to satisfy round-trip test: https://github.com/jgm/pandoc/blob/2eba15c181639f893f647c45c7b43b352e14bc98/src/Text/Pandoc/Writers/Muse.hs#L312

Maybe it makes sense to move this function outside Writers.Muse instead of reimplementing it.

I am not sure joining things like `Span` is a correct thing to do, though, because joined and consecutive spans in HTML can be displayed differently and mean different things.

**Comment by tolot27** [comment]
> I am not sure joining things like Span is a correct thing to do, though, because joined and consecutive spans in HTML can be displayed differently and mean different things.

Maybe you are right. Lets start with `Str`, at least for automatic merging. A general merging function could be called upon request.

**Comment by tarleb** [comment]
I think it's best not to change the current behavior, as the opposite behavior – splitting strings into smaller chunks – can be useful as well and would be made impossible by automatic merging.

However, this can now be solved by using an [`Inlines`](https://pandoc.org/lua-filters.html#filters-on-element-sequences) filter to merge consecutive Str elements. Requires pandoc 2.9.2 or newer.
