### ISSUE TITLE
input filenames containing "." are ignored

### ISSUE THREAD

**Issue by holtzermann17** [jgm/pandoc#4518]
Pandoc version: pandoc 1.19.2.1

`\input` files with dots in the file name  (like `a.b.tex`) don't seem to be processed properly by pandoc.

Here's an illustration, with the main top-level file named `sample.tex` and two included files.

# `sample.tex`:

``` latex
\input{a.b}
\input{a-b}
```

# `a.b.tex`:

``` latex
Should work the first time.
```

# `a-b.tex`:

``` latex
It only works the second time!
```

Now interactions are as follows:

```
$ pandoc --from=latex --to=html sample.tex
<p>It only works the second time!</p>
```
I would have expected this output:

``` html
<p>Should work the first time.</p>
<p>It only works the second time!</p>
```

**Comment by mb21** [comment]
Can you try with the newest pandoc?

**Comment by jgm** [comment]
See https://tex.stackexchange.com/questions/24773/how-to-avoid-automatic-tex-extension-in-filenames
which recommends:

> Avoid in TeX multiple dots like the plague.

We should add the `.tex` extension in this case, but I'm actually not sure about the rules followed by `\input` in latex:  presumably if your filename is `a.sty` rather than `a.b`, the extension isn't added?

**Comment by jgm** [comment]
This seems to work fine now, so closing.
