### ISSUE TITLE
rST written with inconsistent indentation.

### ISSUE THREAD

**Issue by NickVolynkin** [jgm/pandoc#4563]
rST writer uses either 3- or 4-space indentation for various elements. When combined, this results in a set of all possible `N * 3 + M * 4` indents.

This produces an rST source that is hard to maintain. Writer has to manually count and set indents for every block that they are editing. Many text editors maintain `4 * N` spaces with <kbd>Tab</kbd> and <kbd>Backspace</kbd>, so getting some 7- or 10-space indent becomes tricky.

Please add at least an option to force 4-space indentation in rST writer.

Here's an example HTML that is turned into an inconsistent rST:

```html
<p>Just some paragraph text, zero indented</p>

<pre class="example">directive name is indented with 3 spaces,
but code is at 4 spaces</pre>

<ul>
  <li>
    <p>List item is at 3 spaces.</p>
    <p>Continued paragraphs are also at 3.</p>
    <pre class="example">Here's some code in a list.
Now directive name is indented with 6 spaces,
and code is at 7 spaces</pre>
  </li>
  <li>3 spaces
    <ul>
      <li><p>6 spaces</p>
        <pre class="example">Guess what happens in a nested list?</pre>
      </li>
    </ul>
  </li>
</ul>
```
Here's the output:
```rst
Just some paragraph text, zero indented

.. code:: example

    directive name is indented with 3 spaces,
    but code is at 4 spaces

-  List item is at 3 spaces.

   Continued paragraphs are also at 3.

   .. code:: example

       Here's some code in a list.
       Now directive name is indented with 6 spaces,
       and code is at 7 spaces

-  3 spaces

   -  6 spaces

      .. code:: example

          Guess what happens in a nested list?
```

**Comment by jgm** [comment]
There's no way to enforce a fixed indent level across the board, because of the way ordered lists must be lined up.  For example, here we can't use a 4-space indent, or the content is not considered part of the list:
```
999. hi

    there
```

I'd like to change things so that 3-space indents are used wherever possible, except when more indentation is required because of the width of an ordered list marker.  This allows indented content to line up with the directive name, which is aesthetically pleasing and agrees with the examples in the reStructuredText documentation.

**Comment by NickVolynkin** [comment]
@jgm why not use autonumbered lists? 
```
#. hi

   there
```
The only exclusion is when we need to start from anything except 1:

```
5. hi
#. there
#. !
```

**Comment by jgm** [comment]
We do use `#.` for lists with style DefaultStyle and
delimiter DefaultDelim.  But if a particular style
and delimiter are specified, we use a number/letter.
