### ISSUE TITLE
data file contains embedded nonfree ICC profile

### ISSUE THREAD

**Issue by jonassmedegaard** [jgm/pandoc#4588]
The file data/pptx/docProps/thumbnail.jpeg contains an embedded ICC color calibration file which is copyright Apple and lacks free license.

Please acquire appropriate license for use of the ICC profile, replace with a freely licensed ICC profile, or simply strip the profile (and transform the image to sRGB colorspace, default for screen use when ICC profile is omitted, if needed).

**Comment by jonassmedegaard** [comment]
One way to check images for metadata of embedded ICC profiles is by use of commandline tool exiftool, part of the perl module Image::ExifTool,

**Comment by jgm** [comment]
@jkr how would you like to handle this?

**Comment by jkr** [comment]
Solution in this specific case is pretty easy. The thumbnail is unneccessary -- we don't put it in the document. (It's a thumbnail of the document, and we don't make that.) I'll remove it and make sure everything still works.

More generally, though: is there anywhere else we have to keep an eye out for this? There's a png in `/data/odt/Thumbnails/thumbnail.png`. Otherwise, all our images are in the test dir, which is okay because it's not distributed, right?

**Comment by jonassmedegaard** [comment]
test dir is included with tarball.

For Debian we currently repackage to strip the following files containing nonfree parts:

 data/LaTeXMathML.js
 data/pptx/docProps/thumbnail.jpeg
 tests/docx/block_quotes.docx
 tests/docx/char_styles.docx
 tests/docx/deep_normalize.docx
 tests/docx/drop_cap.docx
 tests/docx/hanging_indent.docx
 tests/docx/headers.docx
 tests/docx/inline_formatting.docx
 tests/docx/inline_images.docx
 tests/docx/link_in_notes.docx
 tests/docx/links.docx
 tests/docx/lists.docx
 tests/docx/metadata_after_normal.docx
 tests/docx/metadata.docx
 tests/docx/normalize.docx
 tests/docx/notes.docx
 tests/docx/numbered_header.docx
 tests/docx/tables.docx
 tests/docx/table_with_list_cell.docx
 tests/s5-fancy.html

**Comment by jonassmedegaard** [comment]
(above list is not yet adjusted for the 2.x rename tests → test)

**Comment by jgm** [comment]
>  data/LaTeXMathML.js

data/LaTeXMathML.js is GPL2, or so says the comments in the source!
Do you know otherwise?  Same applies to test/s5-fancy.html,
presumably that's in there because it contains this script?

In the other cases I think we should identify the nonfree parts
and remove them.  Is there a particular file component that
is nonfree?

**Comment by jkr** [comment]
@jonassmedegaard How did you determine those test/docx/*.docx files to be nonfree?

**Comment by jgm** [comment]
Reopening.  The thumbnails have ICC profiles, like the other.
Easy to remove these using `convert -strip`.
