### ISSUE TITLE
Pandoc warns about unset template variables when set from command line

### ISSUE THREAD

**Issue by ehildenb** [jgm/pandoc#4614]
### Version

```
# Pandoc from commit 3d766b5c4

$ pandoc --version
pandoc 2.2
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.2, skylighting 0.7.0.2
Default user data directory: /home/ehildenb/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

### Input Files

-   Markdown source: `test.md`

```
A Header
========

Some text.

-   Bullet
-   Points
```

-   HTML Template: `site.tmpl`

```
<title>title: $title$</title>

$body$
```

### Bug

-   Invoke `pandoc` with no template, everything OK

```
$ pandoc --from markdown --to html test.md
<h1 id="a-header">A Header</h1>
<p>Some text.</p>
<ul>
<li>Bullet</li>
<li>Points</li>
</ul>
```

-   Pass `pandoc` the template, correctly warns about missing template variable `title`

```
$ pandoc --from markdown --to html test.md --template=site.tmpl
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'test'
<title>title: </title>

<h1 id="a-header">A Header</h1>
<p>Some text.</p>
<ul>
<li>Bullet</li>
<li>Points</li>
</ul>
```

-   Set the variable `title` on the command-line, *unexpectedly* continues to warn about missing variable `title`, but *does* use command-line definition of variable to fill in template

```
$ pandoc --from markdown --to html test.md --template=site.tmpl --variable=title=test-title
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'test'
<title>title: test-title</title>

<h1 id="a-header">A Header</h1>
<p>Some text.</p>
<ul>
<li>Bullet</li>
<li>Points</li>
</ul>
```

**Comment by mb21** [comment]
try -M instead of -V

**Comment by jgm** [comment]
You're using a nonstandard custom template.  In the default template, we generate the contents of the title tag (this is the `pagetitle` variable) from the metadata title. This is necessary because the title tag should contain a plain string, and the metadata title might contain formatting.

If you use a custom template like yours, then the title element will be filled even though pandoc has no metadata title to use in populating `pagetitle`.  But the HTML writer doesn't *know* that the title element is being filled.  The template is like a black box to it; it just sets variables and calls a function to resolve them.

So, if the warning bothers you, use the `pagetitle` variable instead of `title`.  Or set `title` using `-M` as @mb21 recommends.  (The warning itself tells you the same.)
