### ISSUE TITLE
email autolinks have no class in HTML

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#4615]
Autolinks have no HTML class, [as in](https://pandoc.org/try/?text=%3Ca%40b.com%3E%0A%0A%3Chttps%3A%2F%2Fpandoc.org%3E&from=markdown&to=html4):

``` markdown
<a@b.com>

<https://pandoc.org>
```

HTML output from the code above reads:

``` html
<p><a href="mailto:a@b.com">a@b.com</a></p>
<p><a href="https://pandoc.org" class="uri">https://pandoc.org</a></p>
```

This comes back to the implementation of the class when fixing #1501.

Today I included the first email address in a Markdown document and I realized that the implementation didn’t include email addresses (because of the `mailto:` suffix in the `href` attribute).

Would it be possible that also email autolinks in HTML could be granted the `uri` class?

Many thanks for your help.

**Comment by labdsf** [comment]
The problem is in `obfuscateLink` function, it was implemented this way from the start. If `writerEmailObfuscation opts == NoObfuscation` is true, email class is not added.

**Comment by labdsf** [comment]
The original commit is https://github.com/jgm/pandoc/commit/81157c7cc6ab72fc70bfba18f90c3f12142b7e4e

What I don't understand is why it is implemented in HTML writer. The original intention was to mark autolinks, so it should be done in Markdown reader, not HTML writer, no?

**Comment by ousia** [comment]
@labdsf, many thanks for your reply.

I’m afraid that `--email-obfuscation=references`.

Would it be possible that if `WriterEmailObfuscation opts == NoObfuscation` were true, the `uri` class could be added?

I don’t know (I cannot code), but this might be a simpler fix.

**Comment by jgm** [comment]
Alexander <notifications@github.com> writes:

> The original commit is https://github.com/jgm/pandoc/commit/81157c7cc6ab72fc70bfba18f90c3f12142b7e4e
>
> What I don't understand is why it is implemented in HTML writer. The original intention was to mark autolinks, so it should be done in Markdown reader, not HTML writer, no?

The reason, I'll bet, is that at the time of that commit, we didn't have
attributes on links, so there was no way to add this in the reader.
Clearly, adding it in the reader is a better approach, and we should
do that instead.

**Comment by cjerdonek** [comment]
I'm a little confused by the meaning and utility of adding `class="uri"` because, for example, when converting from HTML to Pandoc Markdown, links show up as autolinks regardless of whether `class="uri"` was present in the HTML. Here is an example in the web interface: [example](https://pandoc.org/try/?text=%3Cp%3E%3Ca+href%3D%22mailto%3Aa%40b.com%22%3Ea%40b.com%3C%2Fa%3E%3C%2Fp%3E%0A%3Cp%3E%3Ca+href%3D%22mailto%3Aa%40b.com%22+class%3D%22uri%22%3Ea%40b.com%3C%2Fa%3E%3C%2Fp%3E%0A%3Cp%3E%3Ca+href%3D%22https%3A%2F%2Fpandoc.org%22%3Ehttps%3A%2F%2Fpandoc.org%3C%2Fa%3E%3C%2Fp%3E%0A%3Cp%3E%3Ca+href%3D%22https%3A%2F%2Fpandoc.org%22+class%3D%22uri%22%3Ehttps%3A%2F%2Fpandoc.org%3C%2Fa%3E%3C%2Fp%3E%0A%3Cp%3E%3Ca+href%3D%22https%3A%2F%2Fpandoc.org%22%3EPandoc%3C%2Fa%3E%3C%2Fp%3E&from=html&to=markdown).

Similarly, when converting from Pandoc Markdown to HTML, `class="uri"` is added regardless of whether it was written in the Markdown as an autolink. Here is an interactive example: [example](https://pandoc.org/try/?text=%3Chttps%3A%2F%2Fpandoc.org%3E%0A%0A%5Bhttps%3A%2F%2Fpandoc.org%5D(https%3A%2F%2Fpandoc.org)%0A%0A&from=markdown&to=html5).

**Comment by jgm** [comment]
Note that with the fix to #4913, email autolinks now get the class `email`, and URI autolinks get the class `uri`.  Is this satisfactory? @mb21 has raised the question whether it would be better for email autolinks to get both `email` and `uri` classes.

**Comment by ousia** [comment]
@jgm, I think it would be great that email autolinks would be granted both `email` and `uri` classes.

**Comment by jgm** [comment]
The reason I balk at `uri` is that email addresses are not URIs.

**Comment by ousia** [comment]
Then, how about `autolink`?

**Comment by jgm** [comment]
> Then, how about `autolink`?

This would make sense if the URI autolinks also got an
`autolink` class.  But changing the current `uri`
class would break existing documents, not something I'd
want to do lightly.  I suppose one could use `autolink
uri` for the URIs and `autolink email` for the emails.
But this is quite verbose.

Note that the current setup gives you all you need to
style things; you can simply apply the same styles to
.email and .uri (or different ones if you prefer). So
I don't see a very strong reason for changing.

**Comment by ousia** [comment]
There is an alternative approach: to add an `uri` class and to convert (in HTML) `<user@domain.com>` into `<a href="mailto:user@domain.com" class="uri">user@domain.com</a>`.

The target would be an URI (or [so it seems](https://stackoverflow.com/a/2184776)).

**Comment by jgm** [comment]
Pablo Rodríguez <notifications@github.com> writes:

> The target would be an URI (or [so it seems](https://stackoverflow.com/a/2184776)).

Yes, the link target is a URI, but not the link text.

If we were going to put a "uri" class on every link
with a URI as its link target, we'd be putting it on
many links that are not autolinks!

**Comment by mb21** [comment]
Well, technically a [`mailto:`-string _is_ a URI](https://en.wikipedia.org/wiki/Mailto).

As far as I understand, pandoc simply started using the `uri` class because we couldn't detect autolinks? (https://github.com/jgm/pandoc/issues/1501) But otherwise it would have been the `autolink` class all along? Not sure where that leaves us... do people need to know in the HTML output whether it was `<mailto:foo@bar.com>` or `[mailto:foo@bar.com](mailto:foo@bar.com)`?

Personally, I never understood the use-case for identifying autolinks in the output anyway... but if it's useful to some people... I'm all for it :)

**Comment by jgm** [comment]
> https://github.com/jgm/pandoc/issues/4615

Yes, the link target -- the `mailto:` part -- is a URI.  But the link text -- the email address itself -- is not.  That was my point.  If we're going to give a special class to every link whose *target* is a URI, then lots of non-autolinks should get it too.

> Personally, I never understood the use-case for identifying autolinks in the output anyway

I've _completely_ lost track of what this feature is for.  @ousia - perhaps you could elaborate, because you're the one who requested it.  @cjerdonek - maybe you could also say why you think it's important that autolinks be specially marked in the AST.  (One possible reason would be to allow round-trips md -> md, but we don't have that anyway because of the opportunistic autolinking in the md writer.)

**Comment by ousia** [comment]
@jgm, I always thought that autolinks where the addresses that got inside `<>`. Email addresses are only a special case of autolinks.

My original request for an special class of autolinks was that styling was different in these cases:

```
You might download it from [the website](https://pandoc.org).

Available from <https://pandoc.org>,
```

The link text in first paragraph is standard text and it doesn’t need special formatting. The second paragraph contains an URI, which should be formatted in some way (italics, monospaced or sans-serif).

A similar reason is behind having an `implicit_header_references` class (#2535).

**Comment by jgm** [comment]
> The link text in first paragraph is standard text and it doesn’t need special formatting. The second paragraph contains an URI, which should be formatted in some way (italics, monospaced or sans-serif).

This motivation argues for our original way of dealing with this issue, which was to have the HTML writer check to see if the link description text is a URL.  (So, it didn't matter whether the source had `<https://pandoc.org>` or `[https://pandoc.org](https://pandoc.org)`.)

This changed with the change #4913 proposed by @cjerdonek.  Now the special class is only assigned if the source contains an actual autolink.

I can see the motivation for the old way of doing it, but I'm not sure I see any motivation for tracking whether there was an autolink in the source.  (One possible motivation would be allowing round-trip md -> md, but we don't have that anyway, because the markdown writer creates autolinks opportunistically.)

@cjerdonek - in light of this I'm considering reverting the change #4913.  Can you explain again the motivation for the change?
