### ISSUE TITLE
Beamer TOC

### ISSUE THREAD

**Issue by eyJhb** [jgm/pandoc#4622]
# Pandoc not generating TOC when using beamer

## Version
```
pandoc 2.2
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.2, skylighting 0.7.0.2
Default user data directory: /home/eyjhb/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

## Testing .md file
```
---
toc:
- true
title:
- test
author:
- Eyjhb
---

# test section0
Yeah!

# test section1
Yeah!

## test section2
Yeah!

### test section3
Yeah!

#### test section4
Yeah!
```
## Testing command
`pandoc test.md -t beamer --toc -o latex-test.pdf`

## Expected result
Expect a TOC after the title page.

**Comment by jgm** [comment]
Read up in the manual about "slide level."  In your document, slide level = 1, because you have content directly under a level 1 header.  If you want your document to have "sections," then just use level-1 headers for section headings, and put all the content under level-2 (slide level will then = 2).
```
# Section

## Slide one

contents

## Slide two

contents

# New section

## Slide three

contents
```
