### ISSUE TITLE
RawBlock merging with adjacent blocks

### ISSUE THREAD

**Issue by gpoore** [jgm/pandoc#4629]
RawBlocks are very useful. I've encountered some situations that might benefit from more documentation, or could be bugs. How are RawBlocks supposed to behave relative to adjacent blocks?

Both
``````markdown
before
```{=markdown}
raw
```
after
``````
and
``````markdown
before

```{=markdown}
raw
```

after
``````
(any number of empty lines before/after raw content) give the same JSON
```json
{"blocks":[
    {"t":"Para","c":[{"t":"Str","c":"before"}]},
    {"t":"RawBlock","c":["markdown","raw"]},
    {"t":"Para","c":[{"t":"Str","c":"after"}]}
],"pandoc-api-version":[1,17,4,2],"meta":{}}
```
When round-tripped from markdown to markdown (`pandoc -f markdown -t markdown`), these yield
```markdown
before

raw
after
```
The RawBlock and following Para are merged. The only way to prevent this is to have one or more empty lines inside the RawBlock, at the end:
``````markdown
before
```{=markdown}
raw

```
after
``````
Is this the intended behavior? It would be helpful if the documentation explained how these cases are handled. I can think of several ways they could be dealt with.
* A RawBlock merges with the preceding/following block if its opening/closing fences are immediately adjacent to the preceding/following block (no leading/trailing empty lines). Otherwise, there is no merging. This would be useful in inserting large amounts of text inside a block, which might be difficult or impossible with a RawInline. This would be maximally powerful, but I expect there might be some difficult edge cases.
* A RawBlock always produces one or more blocks, and never merges with adjacent blocks. This would be very easy to reason about.
* The current behavior. This seems surprising, at least given the visual appearance in markdown compared to the output.

**Comment by jgm** [comment]
The behavior is actually very simple and predictable. A final newline
is not included in the contents of the raw block in parsing markdown (you
can verify this using -t plain). In writing markdown, the contents of
the raw block are printed, with a following newline.  That's it.

This explains why, if your raw block does not contain a blank line at
the end, then there will be no blank line between it and a following
paragraph.

The real problem is that the AST

    [RawBlock (Format "markdown") "hi"
    ,Para [Str "ok"]]

is being rendered as

    hi
    ok

in which "ok" is not a separate paragraph.

One solution for this would be to have the markdown writer ensure that
there is blank line between a Para and any preceding block.

**Comment by gpoore** [comment]
Thanks for the explanation. I just ran across what appears to be another example of the same behavior with the markdown writer, but without using the new, explicit raw block syntax in the markdown source.

```markdown
\newcommand{\test}[1]{X#1X}
\test{A}

before\test{B}after
```
gives the AST
```
[RawBlock (Format "latex") "\\newcommand{\\test}[1]{X#1X}\nXAX"
,Para [Str "before",RawInline (Format "tex") "XBX",Str "after"]]
```
but `pandoc -f markdown -t markdown` returns
```markdown
\newcommand{\test}[1]{X#1X}
XAX
beforeXBXafter
```
