### ISSUE TITLE
Chinese characters in MathML are not parsed

### ISSUE THREAD

**Issue by KangSpace** [jgm/pandoc#4642]
Pandoc Version: 
```
pandoc 2.2
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.2, skylighting 0.7.0.2
Default user data directory: C:\Users\kangxuefeng\AppData\Roaming\pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```
Pandoc command:
```
pandoc -f html --mathml -o latex.docx mathml-chinese.txt
```
Mathml  file:

[mathml-chinese.txt](https://github.com/jgm/pandoc/files/1991273/mathml-chinese.txt)

run result:

![image](https://user-images.githubusercontent.com/26271023/39865610-f8c422bc-547f-11e8-8659-3adbb0942539.png)

And the result is not contain Chinese characters : 汉字 ,中国 .
Correct display:

![image](https://user-images.githubusercontent.com/26271023/39865771-8ee772da-5480-11e8-966e-828db1d5d793.png)

I guess the font ' Cambria Math' not contains Chinese characters

**Comment by mb21** [comment]
Indeed:

    echo '<math xmlns="http://www.w3.org/1998/Math/MathML"><mn>1.</mn><msubsup><mo>∫</mo><mrow><mn>-2</mn><mrow><mi>汉字</mi><mi>≠ 中国 ≠</mi></mrow></mrow><mrow><mn>2</mn><mrow><mi>--&#65;&#x4e2d;&#x56fd;</mi><mi>汉字</mi></mrow></mrow></msubsup><mn>4</mn><mo>-</mo><msup><mi>x</mi><mrow><mn>2</mn><mrow><mi>x</mi><mi>x</mi></mrow></mrow></msup><mi>d</mi><mi>中国</mi></math>' | pandoc -f html -t native

    [Plain [Math InlineMath "1.\\int_{-2{\\neq\\ \\ \\neq}}^{2{--A}}4 - x^{2{xx}}d"]]

**Comment by jgm** [comment]
There are two issues: conversion to docx (omml), and conversion to latex.

As @mb21's example shows, the Chinese characters are dropped in conversion to LaTeX, because the texmath library doesn't find any LaTeX math mode equivalents for them.

In the case of docx, the problem is different:  the characters are passed through in the XML, but the font (Cambria Math) doesn't contain these glyphs.

Note that we currently don't specify a font at all for math -- Cambria Math seems to be a default.  Perhaps there's some way to specify a fallback font for Asian alphabets, on the surrounding oMath element?

**Comment by jgm** [comment]
Wait, hold on!

I've just realized that the Chinese characters are NOT in the docx file, so it's not a docx font issue.

The issue, of course, is that pandoc's AST stores the math as latex.  Since texmath loses the Chinese characters in the translation to LaTeX, they don't appear in the docx (even though texmath can successfully translate the mathml directly to omml!)

```
% pandoc -f html -t native
<math xmlns="http://www.w3.org/1998/Math/MathML"><mn>1.</mn><msubsup><mo>∫</mo><mrow><mn>-2</mn><mrow><mi>汉字</mi><mi>≠ 中国 ≠</mi></mrow></mrow><mrow><mn>2</mn><mrow><mi>--&#65;&#x4e2d;&#x56fd;</mi><mi>汉字</mi></mrow></mrow></msubsup><mn>4</mn><mo>-</mo><msup><mi>x</mi><mrow><mn>2</mn><mrow><mi>x</mi><mi>x</mi></mrow></mrow></msup><mi>d</mi><mi>中国</mi></math>
[Plain [Math InlineMath "1.\\int_{-2{\\neq\\ \\ \\neq}}^{2{--A}}4 - x^{2{xx}}d"]]
```

Perhaps texmath could be taught to leave otherwise untranslatable unicode characters alone.

**Comment by jgm** [comment]
We now require texmath 0.11 which fixes this.

**Comment by KangSpace** [comment]
Nice ,Thank you.
