### ISSUE TITLE
Fix inconsistent handling of unknown languages in fenced code blocks

### ISSUE THREAD

**Issue by ad-si** [jgm/pandoc#4688]
When I have a markdown file `test.md`:

~~~markdown
---
title: Inconsistent Syntax Highlighting
...

```UnknownLanguage
const test = 123
```

vs.

```JavaScript
const test = 123
```
~~~

and render it with `pandoc --standalone test.md > test.html`
it yields this HTML:

```html
…
<pre class="unknownlanguage">
  <code>const test = 123</code>
</pre>
<p>vs.</p>
<div class="sourceCode" id="cb2">
  <pre class="sourceCode javascript">
    <code class="sourceCode javascript">
      <a class="sourceLine" id="cb2-1" data-line-number="1">
        <span class="kw">const</span> test <span class="op">=</span> 
        <span class="dv">123</span>
      </a>
    </code>
  </pre>
</div>
…
```
which is really inconsistent and makes it hard to style the website.

Why ist not generating this?

```html
<div class="sourceCode" id="cb1">
  <pre class="sourceCode unknownlanguage">
    <code class="sourceCode unknownlanguage">const test = 123</code>
  </pre>
</div>
```

(Although I would actually argue that the wrapping `div` is unnecessary in both cases)

**Comment by dbaynard** [comment]
I think the offending line is 760, below, as it bypasses `skylighting` when there is to be no highlighting of code snippets, and calls into `blaze` directly.
This means that changes introduced to code in `skylighting` to represent lines of code as elements in the html output do not apply.

https://github.com/jgm/pandoc/blob/158344d26d64f4ec146bf3ed3c22d08648d89ad0/src/Text/Pandoc/Writers/HTML.hs#L755-L762

The correct output should be:

```html
<div …>
<pre … class="unknownlanguage">
  <code …>
     <a …>const test = 123</a>
  </code>
</pre>
</div>
```

As far as I can tell, `skylighting` insists on highlighting everything, so to fix this either

1.  Add a null option to `skylighting` that simply formats the code, or
2.  Replicate all changes to the html output of `skylighting` here.

I'd choose option 1.

---

By way of explanation: the javascript example has

1.  a wrapping `div` for the element,
2.  a wrapper for the code block (`pre`),
3.  an indication that the contents are code (`code`),
4.  the wrapper `a` (which is due to change) to indicate a line of code, and
5.  the code itself, wrapped with `span` for syntax highlighting.

Both code blocks show 2 and 3. The latter two, 4 and 5, are required for styling individual lines or elements of code. 

On 1, 2 and 3: as it stands the `div` includes the entire contents, the `pre` includes everything but the line numbers (i.e. the `pre` is shifted to the right by the width of the line numbers) and the `code` includes just the code.

This means it is possible to style different all the different parts.

**Comment by jgm** [comment]
dbaynard <notifications@github.com> writes:

> I think the offending line is 760, below, as it bypasses `skylighting` when there is to be no highlighting of code snippets, and calls into `blaze` directly.
> This means that changes introduced to code in `skylighting` to represent lines of code as elements in the html output do not apply.
>
> https://github.com/jgm/pandoc/blob/158344d26d64f4ec146bf3ed3c22d08648d89ad0/src/Text/Pandoc/Writers/HTML.hs#L755-L762
>
> The correct output should be:
>
> ```html
> <div …>
> <pre … class="unknownlanguage">
>   <code …>
>      <a …>const test = 123</a>
>   </code>
> </pre>
> </div>
> ```
>
> As far as I can tell, `skylighting` insists on highlighting everything, so to fix this either
>
> 1.  Add a null option to `skylighting` that simply formats the code, or
> 2.  Replicate all changes to the html output of `skylighting` here.
>
> I'd choose option 1.

I agree, option 1 seems like the way to go here.

**Comment by belka-ew** [comment]
In case someone is looking for a workaround:

````gfm
```default
const test = 123
```
````

**Comment by jgm** [comment]
I think this issue can be closed (particularly now that we have `default`).
It wouldn't be appropriate to assume that the code block marked `UnknownLanguage` is, in fact, source code.  Preformatted text can be used for lots of different purposes.  And one might want to distinguish the appearance of source code from, e.g., program output.

If `UnknownLanguage` is in fact source code, then you have two good options with current pandoc:

1.

``` {.default .UnknownLanguage}
const test = 123
```

which will format it as source code and add class `UnknownLanguage`.

2.  Create a simple syntax definition for `UnknownLanguage` (perhaps even copying `default.xml`) and load it using `--syntax-definition`.
