### ISSUE TITLE
Please have PandocPDFProgramNotFoundError take optional package name

### ISSUE THREAD

**Issue by jonassmedegaard** [jgm/pandoc#4702]
Hi,

the function PandocPDFProgramNotFoundError takes one argument, the name of the command failing.

But the output of that function reuses that argument not only to tell what failed to run, but also an instruction what to install.

For operating systems like Debian where the thing installed in a package (not each executable) that is confusing.

Please extend PandocPDFProgramNotFoundError to optionally take a second argument - usable e.g. to tell that when pdfroff fails please install groff.

**Comment by mb21** [comment]
Not sure I understand. Can you provide actual and expected output when `groff` is not found?

Or do you want to modify the source and build a custom version for debian?

**Comment by jgm** [comment]
I'm not too inclined to do this.  The problem is that
the "install hint" part will vary greatly from one OS
to another, and even from one linux distro to another.

So, to do this, we'd have to make the build system
much more complicated, adding some way to customize
this for each compile target, in the way suggested
here:

> It might make sense to modify source to emit hints optimized for the 
> build environment (e.g. not xelatex nor texlive but texlive-xetex for 
> Debian),

Generally I'm against extra complexity unless it's
really needed. Here, I think most users will
eventually be able to google "how to install pdfroff
on debian" and figure things out.

> but if error message emits _both_ the commandline tool (and the 
> beginning) _and_ project (at the end) that might be adequate to clue in 
> the user what that might correlate to for their particular system.

I'm just not sure there's enough consistency about the
project name.  E.g., for pdflatex, what's the project?
latex?  texlive?  But on Windows you don't use
texlive.
