### ISSUE TITLE
Inconsistent URL parsing in gfm and markdown_github

### ISSUE THREAD

**Issue by petterreinholdtsen** [jgm/pandoc#4719]
I discovered that the two input formats do not identify URLs in the text the same way.  I could not find anything in the documentation indicating that they should interpret URLs differently, so I suspect this is a oversight in some regular expression.  Note how the » character is part of the link with gfm, but not part of the link with markdown_github.

```
% cat y.md; echo =============; pandoc --top-level-division=chapter -f gfm -t docbook4 y.md -o y.xml ; cat docbook/y.xml ; echo =============; pandoc --top-level-division=chapter -f markdown_github -t docbook4 y.md -o y.xml ; cat docbook/y.xml 
# Some text

Some URLS can be problematic, like
rel=»http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-mappe/» which
should not include the trailing quote character as part of the URL.

=============
<chapter id="some-text">
  <title>Some text</title>
  <para>
    Some URLS can be problematic, like
    rel=»<ulink url="http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-mappe/»">http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-mappe/»</ulink>
    which should not include the trailing quote character as part of the
    URL.
  </para>
</chapter>
=============
[WARNING] Deprecated: markdown_github. Use gfm instead.
<chapter>
  <title>Some text</title>
  <para>
    Some URLS can be problematic, like
    rel=»<ulink url="http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-mappe/">http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-mappe/</ulink>»
    which should not include the trailing quote character as part of the
    URL.
  </para>
</chapter>
%
```

**Comment by mb21** [comment]
This behavior is enabled by the normal markdown reader with the [autolink_bare_uris extension](http://pandoc.org/MANUAL.html#extension-autolink_bare_uris) (enabled with `markdown_github`).

I don't understand why it works in the commonmark reader, since my understanding of the spec is that it shouldn't autolink [unless a link is wrapped in `<...>`](https://spec.commonmark.org/0.28/#autolinks), and it doesn't work in the [commonmark js implementation](https://spec.commonmark.org/dingus/?text=Some%20URLS%20can%20be%20problematic%2C%20like%0Arel%3D%C2%BBhttp%3A%2F%2Frel.kxml.no%2Fnoark5%2Fv4%2Fapi%2Farkivstruktur%2Fny-mappe%2F%C2%BB%20which%0Ashould%20not%20include%20the%20trailing%20quote%20character%20as%20part%20of%20the%20URsL.&smart=1).
