### ISSUE TITLE
texinfo writer is not consistent when naming references and anchors

### ISSUE THREAD

**Issue by doronbehar** [jgm/pandoc#4731]
I'm not totally sure if it's exclusively a problem with the `texinfo` writer, or perhaps the source of this is with the reader I used, as in this example:

I'm reading `mediawiki` and writing to `texinfo`. Here is the excerpt where I've encountered the issue with the `mediawiki`:

```mediawiki
=== Wireless ===

Wireless is provided by r8723bs SDIO driver. Rather unstable, but it is still usable.
See [[#See also]]
```

And the title `See Also` in the `mediawiki` file is:

```mediawiki
== See also ==
```

The `texinfo` that was produced is this:
```texinfo
@node Wireless
@subsection Wireless
@anchor{#wireless}
Wireless is provided by r8723bs SDIO driver. Rather unstable, but it is
still usable. See @ref{#See_also,#See also}
```

While the `See also` node in the generated `texinfo` file is:

```texinfo
@node See also
@section See also
@anchor{#see-also}
```

As you can see, in the `@ref` it's `#See_also` and in the `@anchor` it's `#see-also`. That leads to errors from `makeinfo` on this file such as:
```
4Good CL110.texinfo:171: @ref reference to nonexistent node `#See_also'
```

### Note:

The real file I used before running `makeinfo` was a little different from the one you might get when converting a `mediawiki` file with this text to a standalone `texinfo` file. It's sections / chapters division is different since I've filtered it through some `sed` commands to fix other problems I've encountered. I'll report these as a separate issue after I'll see this issue fixed, I just don't know how to explain it yet.

You can use [this `mediawiki` file](https://gist.github.com/e4e3cec079c66ff17c837aa239382663) (taken from the Arch Linux Wiki) with these commands to run in order to convert it to a **valid** `texinfo` file:

```sh
pandoc --standalone -V titlepage -V title="4Good CL110" --from=mediawiki "4Good CL110.mediawiki" --to=texinfo --output "4Good CL110.texinfo"
# These two fix #4728 which was not fixed in the release..
sed -i 's/@textsuperscript/@sup/g' "4Good CL110.texinfo"
sed -i 's/@textsubscript/@sub/g' "4Good CL110.texinfo"
# These two fix the other issue I'll report later when I'll understand it fully.
sed -i 's/@section\b/@chapter/g' "4Good CL110.texinfo"
sed -i 's/@subsection\b/@section/g' "4Good CL110.texinfo"
```

Running `makeinfo`  on `4Good CL110.texinfo` gives the warning I've quoted above.

**Comment by jgm** [comment]
I believe this is an issue with the mediawiki reader, rather than the texinfo writer.
The mediawiki reader isn't sensitive to internal links of the form `[[#foo bar]]`.  But can you explain how these work?  I tried it in the mediawiki sandbox and got a link with visible link text `# foo bar` and destination `#foo_bar`.  This seems undesirable because of the visibile `#` -- are you sure this is the right way to create a link to a section on the same page?

**Comment by doronbehar** [comment]
According to the Media wiki official documentation yes: https://mediawiki.org/wiki/Help:Links#Internal_links

**Comment by mb21** [comment]
@doronbehar pull request welcome! for an ad hoc fix, you could write a lua filter...

**Comment by jgm** [comment]
We use `registerHeader` in the MediaWiki reader; when `auto_identifiers` is set, as it is by default, this creates automatic identifiers using our normal system (documented in the manual). However, this system doesn't match up with mediawiki's system, which uses `_` instead of `-` (and probably has other differences as well).  So I guess  what we need is another extension along the lines of `gfm_auto_identifiers`, like `mediawiki_auto_identifiers`.  The relevant algorithm would then have to be implemented in `inlineListToIdentifier`.

A lighter-weight solution could be to add a bit of code to the mediawiki reader that simply transforms the attributes passed back from `registerHeader` by changing `-` into `_`.  Let me try this first.
