### ISSUE TITLE
No easy way to use color font for emojis in html output

### ISSUE THREAD

**Issue by wanders** [jgm/pandoc#4743]
The gfm input handles `:slightly_smiling_face:` style emojis by converting them to the corresponding unicode code point. This however makes it hard to use a separate font for them in html output (e.g a special color emoji font such as https://www.google.com/get/noto/help/emoji/ ).

If they were wrapped in `<span>` tags with a special class it would be trivial.

**Comment by mb21** [comment]
Not saying the `span` tag is a bad idea, but I guess you could also use CSS fallback fonts for [specific unicode ranges](https://24ways.org/2011/creating-custom-font-stacks-with-unicode-range/) (or [character positions](https://css-tricks.com/css-basics-fallback-font-stacks-robust-web-typography/#article-header-id-0)).

**Comment by wanders** [comment]
@mb21 Interesting. I wasn't aware that was possible. Can that be mad to work work with combining characters? As an example the `:zero:` emoji (:zero:) which is an ordinary ascii zero followed by U+FE0F and U+20E3. Having a separate font for the standard ascii zero codepoint will obviously cause other problems.

**Comment by mb21** [comment]
@wanders I don't know, you'd have to try it out and see how different browsers handle it I guess...

**Comment by jgm** [comment]
Instead of modifying the HTML writer, as suggested in the PR, and adding a new option (which I like to avoid whenever possible), what about just having the markdown reader put all emojis in pandoc Span elements?  e.g.
```
Span ("",["emoji"],[("title",":smile:")]) [Str "\128516"]
```
This would have the desired result in HTML output, and in most other formats the span would be ignored.  But in textual formats (like Markdown) we could emit the ASCII fallback when the `--ascii` option is specified.  (Currently emojis break the `--ascii` guarantee.)

Some things I'd like comment on:

- I'm not sure the `title` attribute is the right place to put the fallback.  Alternatively one could use `data-emoji`, or use an additional class prefixed with `emoji-` (though this is harder to extract programmatically).
- I'm not sure if the fallback value should be `:smile:` or `smile`.
- Maybe there are drawbacks I haven't considered to always including the span?

**Comment by wanders** [comment]
@jgm Thanks, I'll try to hack it up when I get and chance so it can be tried out.

**Comment by wanders** [comment]
@jgm Find it implemented here: https://github.com/wanders/pandoc/commit/1f384637c5150b0d75876cf324e0c730dc3e96f7

I think this feels much cleaner than doing it in the html writer.
Went with `class="emoji"` and `data-emoji="emojiname"`.

If you think this is the way to go, should the markdown reader be updated to wrap in Span too?

**Comment by jgm** [comment]
> If you think this is the way to go, should the markdown reader be updated to wrap in Span too?


Yes.  And to avoid code duplication, we should
probably put an "emojiSpan" builder in the Emoji
module, which takes as input the emoji name and
outputs the Span.  Something like

    emojiSpan :: String -> Maybe Inline

**Comment by wanders** [comment]
Created new PR #4759
