### ISSUE TITLE
Show the input filename and line of UTF-8 encoding errors

### ISSUE THREAD

**Issue by bulrush15** [jgm/pandoc#4765]
Pandoc v2.2.1 on Windows 7

Sometimes I get this error when making an EPUB file from Markdown or HTML files: 

> pandoc: Cannot decode byte '\x92': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

For all errors, especially this one, can Pandoc write out the name of the input filename and the line of the input filename where the error occurred? This would be helpful in finding odd characters that shouldn't be there.

I might have 20 input files so editing them to find the error, or even using iconv, can be a pain. I might choose to do a search and replace the bad character instead. 

Thanks! Love your program!

**Comment by frastlin** [comment]
Is there any way to do this, I have a single document and I'm getting:

`pandoc: Cannot decode byte '\x96': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream`

Which is extremely unhelpful. Is there some way to hunt down these errors?

**Comment by mb21** [comment]
@frastlin what version are you on? try the newest pandoc version...

**Comment by frastlin** [comment]
I updated to 2.7 and now I'm getting the byte number. That's a little better, but not the best. I can't find any program that will tell me what byte I'm currently on. I've got characters and lines, but not bytes.
Is it possible to maybe have a dictionary of common codes, like left quote and right quote and say what the character is in the output?

**Comment by mb21** [comment]
> a dictionary of common codes

that's exactly what unicode _is_. And the error says: that byte-sequence wasn't any valid character in the UTF-8 dictionary.

You can e.g. use `iconv -t utf-8 doc.txt > doc-cleaned.txt` and then diff the doc.txt and doc-cleaned.txt to see what's the difference...

But yes, I suppose we could also print the line number as well...

**Comment by frastlin** [comment]
Line number would help so much, that's what pretty much all coding environments show for trace backs and that's what I'm used to.
Thank you,

**Comment by frastlin** [comment]
I'm on windows, but for me what it is yelling at are:

‘ ’ “ ” – —

**Comment by agusmba** [comment]
It looks like your file is not UTF8 but window-1252 encoded.

**Comment by frastlin** [comment]
Switching the encoding doesn't change those characters.
I'm copying and pasting from Google Docs or Word, and sometimes people forget to turn off the smart characters, so that's when this happens. I get the error in Pandoc, then need to find where that character is, then replace it in the original document. The line number would speed this up considerably.

**Comment by agusmba** [comment]
Indeed, switching the encoding doesn't change the characters (if done right).

This would solve the problem you were reporting:

> pandoc: Cannot decode byte '\x92': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

However from your latest message:

> I'm copying and pasting from Google Docs or Word, and sometimes people forget to turn off the smart characters...

It seems your problem is that you have smart characters as input and you don't want them (or that you are working with the wrong encoding locally). That is another problem, which pandoc could help you with, but you still need to have the proper encoding in your files.
