### ISSUE TITLE
YAML title does not allow colon (:), should it?

### ISSUE THREAD

**Issue by bulrush15** [jgm/pandoc#4774]
Pandoc v2.2.1 on Windows 7

When the YAML title for a book, using Markdown, contains a colon, Pandoc displays an error. Should the YAML title allow colons? I've gotten this error on 2 other books. I always use a YAML title block with multi-markdown.

Example test.md Markdown file: 

```
---
title: The Big L: Logistics in World War 2
author: Alan Gropman
date: 1997
---

# Ch 1

This is a test

These are more lines.
```

Here is the batch file with command line I use: 

`pandoc --from=markdown_mmd+backtick_code_blocks+yaml_metadata_block+line_blocks+auto_identifiers+escaped_line_breaks  --to=epub -o test.epub test.md
`

I removed the part about `-css` style because it should not affect the output or error message.

**Comment by latk** [comment]
This is by design – you need to quote the metadata entry.

[YAML](http://yaml.org/) is a fairly complex format. It usually does what you want but can have surprising edge cases like this: a same-line map value cannot start with something that looks like a map key. Here, there is an illegal ambiguity between a nested map:

``` yaml
title:
  The Big L:
    Logistics in World War 2
```

and a string value:

``` yaml
title: "The Big L: Logistics in World War 2"
```

YAML string values can be plain (unquoted), double quoted, and single quoted. Plain values might not be strings, e.g. when they look like numbers or booleans (or mappings, as in this case). Quoted strings are always strings, but now you have to take care of escaping: double-quoted strings allow C-style backslash escapes, whereas single-quoted strings only escape single quotes. You cannot mix quoting styles or use escapes in unquoted strings. These three strings are equivalent:

``` yaml
- here's to "quotes"
- "here's to \"quotes\""
- 'here''s to "quotes"'
```

YAML also has block-styles for strings. Here is a folded-chomped block scalar that is equivalent to the quoted string:

``` yaml
title: >-
  The Big L: Logistics
  in World War 2
```

**Comment by bulrush15** [comment]
Thank you! Can this be documented in the user guide? I didn't see anything like this info in there.

**Comment by mb21** [comment]
@bulrush15 That's just how YAML works, and the MANUAL is already lengthy enough. But maybe we could add a link to a good YAML tutorial in http://pandoc.org/MANUAL.html#extension-yaml_metadata_block ?

**Comment by jgm** [comment]
Adding a link to good YAML documentation might be a
good idea.  Any suggestions?
