### ISSUE TITLE
[Windows] The WiX-based installer is always 32-bit, even for 64-bit builds

### ISSUE THREAD

**Issue by FaultyRAM** [jgm/pandoc#4795]
32-bit MSIs have different semantics from 64-bit ones, mainly to do with "redirection". On 64-bit Windows you have `Program Files (x86)` for 32-bit programs, and `Program Files` for 64-bit programs; if you try installing to either one, msiexec detects this and redirects to the "correct" folder. Since we have a 32-bit installer that bundles 64-bit binaries, Pandoc ends up being installed to the wrong folder. There's no way to override this behaviour short of modifying the registry, but as a workaround you can pass a shortened path to the .msi, as these aren't subject to redirection:

```
.\pandoc-2.2.2.1-windows-x86_64.msi /passive ALLUSERS=1 APPLICATIONFOLDER="C:\Progra~1\Pandoc"
```

**Comment by jgm** [comment]
pandoc.wxs has: 

    <?if $(sys.BUILDARCH)=x64?>
    <?define ProgFilesFolder="ProgramFiles64Folder"?>
    <?else?>
    <?define ProgFilesFolder="ProgramFilesFolder"?>
    <?endif?>

My assumption was that this would set the appropriate
Program Files directory for the architecture. Are you
saying that this setting is being overridden by
"redirection"? I'm not sure I understand why: does
msiexec assume that a 32-bit installer must be
installing a 32-bit program?

The other question is why the msi is 32-bit.  We
produce these on appveyor.  WiX is installed there
via chocolatey.  My understanding is that chocolatey
should install 64-bit programs on a 64-bit machine,
since there's an option to override this behavior,
but maybe that's not so?  Is there something we can
do to make the msi 64-bit?

(Sorry, I have to rely on the wisdom of others to
produce the Windows package -- I don't use Windows
myself.)

**Comment by jgm** [comment]
We need some more information here, or I'll have to close this issue.
Can anyone shed more light on this?

**Comment by K4zuki** [comment]
I am not expert of MSI stuff but I reproduced 64-bit installer tries to install to `Program Files (x86)`

- using `pandoc-2.2.3.2-windows-x86_64.msi`
- Windows10 Enterprise 64bit

![](https://user-images.githubusercontent.com/9379328/44761015-875b4480-ab7c-11e8-9cf1-c74a6e57df7e.png)

from here I clicked **"Advanced"** and:

![](https://user-images.githubusercontent.com/9379328/44761016-87f3db00-ab7c-11e8-8666-a6159d3460f6.png)

this page may be a hint?: <https://stackoverflow.com/questions/50012385/how-do-i-make-a-64-bit-msi>

**Comment by jgm** [comment]
Thanks: I tried a minimal change: using `-arch` with `candle` in the build process.
If this doesn't work, there are a few other tricks from that link we can try (like using `$(var.Platform)$` instead of `$(sys.BUILDARCH)`, and setting the Win64 flag for components and registry.  But let's see first if this small change makes a difference.

Unfortunately I can't easily test, so I'd appreciate if someone else could.
https://ci.appveyor.com/project/jgm/pandoc
Assuming the builds complete successfully, the installers will be under 'artifacts' for each of the builds (32 and 64 bit).

**Comment by jgm** [comment]
@FaultyRAM (or anyone else):  I've made various changes to the way the packages are built, and it would be great if someone could test to see if this issue remains.

64-bit msi can be found here: <https://ci.appveyor.com/project/jgm/pandoc/build/1.0.2784/job/cxhar61y1jf3ytkh/artifacts>

**Comment by FaultyRAM** [comment]
Tested it just now on my 64-bit Windows machine. It defaults to `C:\Program Files\Pandoc` and successfully installs Pandoc there, so I'd say this one is fixed. Thank you!
