### ISSUE TITLE
Raw latex causes performance hit

### ISSUE THREAD

**Issue by jspayne** [jgm/pandoc#4812]
Pandoc 2.2.2.1

In a generated document with a large number (thousands) of \nopandoc\hypertarget performance degrades exponentially.

A test source file can be generated using this python script, an example is attached:

```
start_string1 = "# Item Stuff and Things {#ref"
end_string1 = "}\n"
start_string2 = "\\nopandoc{ \\hypertarget{ref"
end_string2 = "}{} }\n"


with open('test.md','w') as f:
    out = []
    for i in range(500):
        out.append(start_string1 + str(i) + end_string1  
        + start_string2 + str(i) + end_string2)
    f.write('\n\n'.join(out))
```

[test.md.gz](https://github.com/jgm/pandoc/files/2254204/test.md.gz)

**Comment by jgm** [comment]
I don't see exponential behavior here.
```
% time pandoc -t latex --quiet test.md >/dev/null
real	0m1.291s
% time pandoc -t latex --quiet test.md test.md  >/dev/null
real	0m2.871s
% time pandoc -t latex --quiet test.md test.md test.md >/dev/null
real	0m4.920s
% time pandoc -t latex --quiet test.md test.md test.md test.md >/dev/null
real	0m6.999s
```
This is close to linear with the input length.

**Comment by jgm** [comment]
What is true is that the the latex bits slow things down quite a bit.  If you replace them with some regular markdown content, the times are much faster (e.g. 1.38s for 4x, instead of 6.99s).

This is probably because of the overhead involved in tokenizing the input so it can be consumed by the latex reader.  (Note that because this is done "lazily", the whole remaining input isn't tokenized -- just what is needed.  If the whole remaining input were tokenized, then we would see nonlinear timings.)
