### ISSUE TITLE
support epub types frontmatter, bodymatter and backmatter

### ISSUE THREAD

**Issue by SushiTee** [jgm/pandoc#4823]
see [discussion](https://groups.google.com/forum/#!topic/pandoc-discuss/K5iTLz4hR34) for comparison.

epub supports different sections: frontmatter, bodymatter, backmatter

See [here](http://www.idpf.org/epub/profiles/edu/structure/#h.l0bzsloklt10)

There is currently no way to generate those special attributes for the _body_ tag because the body tag is generated depending on which level of headers the document is split into single files.

I suggest that there is a special class which can be applied to a header which tells pandoc to put it into a _body_ with the given attribute.
This is especially important for things like appendix which may need a special form of numbering in the toc.

E.g:

```
# Some header {.epub_backmatter epub:type=appendix}

Some content.
```
this should generate to:

```
<body epub:type="backmatter">
  <section epub:type="appendix">
    <h1>Some header</h1>
    <p>Some content</p>
  </section>
</body>
```

**Comment by jgm** [comment]
SushiTee <notifications@github.com> writes:

> I suggest that there is a special class which can be applied to a header which tells pandoc to put it into a _body_ with the given attribute.
> This is especially important for things like appendix which may need a special form of numbering in the toc.

That's not really going to work, because there can
only be one body tag in the document. This is provided
by the template, not by the HTML writer.

Note that currently there's a single template for
epub3. It includes a conditional `$if(titlepage)$`
so that part of it is used for the title page and
part of it is used for the other pages.

Perhaps we could do something similar for back matter.
The writer would determine whether the page it is
generating is back matter (perhaps by examining
attributes on the header), and set a special variable.
The template could include attributes on the body
tag conditional on this variable.

**Comment by mb21** [comment]
Maybe @SushiTee's suggestion would have worked after all?

    # Some header {.epub_backmatter epub:type=appendix}

Guessing the `backmatter` or `frontmatter` from the epub:type seems fragile. Especially, since this appears to be a bigger vocabulary in newer drafts, if I'm reading this correctly. See http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-epub-type-attribute, which links to https://idpf.github.io/epub-vocabs/structure/.

**Comment by jgm** [comment]
Mauro Bieg <notifications@github.com> writes:

> Maybe @SushiTee's suggestion would have worked after all?
>
>     # Some header {.epub_backmatter epub:type=appendix}
>
> Guessing the `backmatter` or `frontmatter` from the epub:type seems fragile. Especially, since this appears to be a bigger vocabulary in newer drafts, if I'm reading this correctly. See http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-epub-type-attribute, which links to https://idpf.github.io/epub-vocabs/structure/.

Let's see how the present system works out.  In
general it seems better to do this automatically,
rather than forcing the writer to do it and possibly
ending up with a bad combination of front/backmatter
and the type.

If people find they need more types, we can revisit.
