### ISSUE TITLE
GFM reader: single tilde interpreted as strikethrough

### ISSUE THREAD

**Issue by cjerdonek** [jgm/pandoc#4840]
It seems like Pandoc (with the latest release, version 2.2.3.2) is interpreting the tilde character (`"~"`) incorrectly when converting from `gfm` to, say, HTML 5.

The GFM docs [say](https://github.github.com/gfm/#strikethrough-extension-) that two tilde characters are required to convert to strikethrough, but Pandoc only seems to require one.

For example, Pandoc converts `~Hi~ Hello` to `<p><del>Hi</del> Hello</p>`:
https://pandoc.org/try/?text=~Hi~+Hello&from=gfm&to=html5

**Comment by mb21** [comment]
Apparently, GFM decided to go with two tildes as the canonical way to denote strikethrough (that's why it's mentioned in the docs like that), but the actual implementation supports ["single-tilde and any-tilde cases are for legacy docs"](https://github.com/github/cmark/issues/71#issuecomment-373181790).

See the [Single tilde in GFM spec](https://github.com/github/cmark/issues/99) issue on github/cmark.

I guess, eventually they will change their fork of `cmark` to reflect their documentation. By than it will be in agreement with both pandoc's `markdown` reader and pandoc's docs.

**Comment by cjerdonek** [comment]
Okay, thanks for that info.

By the way, when I try converting `~Hi~` from HTML to GFM on the demo page, I get back the original string `~Hi~`:
https://pandoc.org/try/?text=~Hi~&from=html&to=gfm

This also happens for `~~Hi~~`. Shouldn't the tildes be backslash-escaped in the output in both cases?

**Comment by mb21** [comment]
Indeed! The GFM writer doesn't escape tildes properly. Not sure where this should be fixed: in pandoc? or does `cmark-gfm` support the strikeout-extension? @jgm?

**Comment by jgm** [comment]
The commonmark writer in github's cmark variant
doesn't properly support strikeout, so we implement
this ourselves in the wrapper Text.Pandoc.Writers.Commonmark.

The escaping is done in the C library, though, so we
can't do much about that.  (Well, in theory we could
do our own escaping and produce a raw commonmark node
instead of a Str node, but I'm not sure it's worth it.)

**Comment by cjerdonek** [comment]
Oh, wow, that’s great. Thanks!

**Comment by cjerdonek** [comment]
I think there's another issue related to Markdown and tildes (with the Pandoc markdown writer).

When writing from, say, HTML to Pandoc markdown with the subscript extension disabled, tilde characters aren't escaped (`~~Hi~~` --> `~~Hi~~`):

```
$ pandoc -f html -t markdown-subscript
```

even though they still have special meaning because of the strikeout extension, which is enabled by default (`~~Hi~~` --> `<p><del>Hi</del></p>`):

```
$ pandoc -f markdown-subscript -t html
```

I think this is because the code doesn't also check for whether the strikeout extension is enabled when deciding whether to escape the tilde character:
https://github.com/jgm/pandoc/blob/cc4753367c503777339eaf889a0aaf514d1ec427/src/Text/Pandoc/Writers/Markdown.hs#L301

I think this logic was first added here: https://github.com/jgm/pandoc/commit/cb4ae6112e4bf9b12b3131fa96fc8d29b1e77dec

**Comment by jgm** [comment]
Thanks, just fixed that one too!

**Comment by cjerdonek** [comment]
> I sent some PRs into github's cmark parser, which should fix these issues.

For future reference, these were issues https://github.com/github/cmark/pull/104 and https://github.com/github/cmark/pull/106, I believe.
