### ISSUE TITLE
When converting to latex, pandoc inlines TeX macro definitions

### ISSUE THREAD

**Issue by hseg** [jgm/pandoc#4846]
MWE:
```markdown
---
header-includes: |
    \let\Im\relax
    \DeclareMathOperator{\Im}{Im}
    \let\Re\relax
    \DeclareMathOperator{\Re}{Re}
...

We have $(\Re i, \Im i)=(0,1)$, $(\Re 1, \Im 1)=(1,0)$
```

Version:
```
pandoc 2.2.3.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
```

Command line: `pandoc test.md -so test.tex`

Expected output (snipped): `We have \((\Re i, \Im i)=(0,1)\), \((\Re 1, \Im 1)=(1,0)$`

Actual output (snipped): `We have \((\relax i, \relax i)=(0,1)\), \((\relax 1, \relax 1)=(1,0)\)`

**Comment by jgm** [comment]
To avoid this behavior, use

    pandoc -f markdown-latex_macros

When the `latex_macros` extension is enabled (as it is by default for pandoc markdown), then macros get expanded in parsing.  Note that this is normally what you want to happen when you're targeting a format other than latex, since it makes conversion of math more reliable.

This *is* a behavior change from 1.19.x, and it contradicts the current manual, [which says](http://pandoc.org/MANUAL.html#extension-latex_macros) that the `latex_macros` extension only affects "output formats other than LaTeX."  However, the manual does helpfully add: "When `latex_macros` is disabled, the raw LaTeX and math will not have macros applied. This is usually a better approach when you are targeting LaTeX or PDF."

What changes are called for?  I can think of two different ways to go:

1.  Modify the documentation so it no longer says "For output formats other than LaTeX."

2. Automatically disable the `latex_macros` extension in Text.Pandoc.App when the output format is latex.

I prefer (1) to (2).  In general, in pandoc the operation of the readers does not depend on which writer is being used.  I think this is a good principle to maintain.  It ensures, for example, that `pandoc -t latex` will not diverge from `pandoc -t json | pandoc -f json -t latex`.

**Comment by hseg** [comment]
I can see your reasoning. I'll just point out that some writers lose data, and that therefore I'd not be surprised if this is disabled for LaTeX by default.
Thinking on this further, we probably want to distinguish between serialising the AST into a format such as JSON (which should be lossless) and rendering the file in some format. In the latter, it's clear that we'd try to emulate unsupported features, which might be lossy.

On 21 August 2018 2:10:34 GMT+03:00, John MacFarlane <notifications@github.com> wrote:
>To avoid this behavior, use
>
>    pandoc -f markdown-latex_macros
>
>When the `latex_macros` extension is enabled (as it is by default for
>pandoc markdown), then macros get expanded in parsing.  Note that this
>is normally what you want to happen when you're targeting a format
>other than latex, since it makes conversion of math more reliable.
>
>This *is* a behavior change from 1.19.x, and it contradicts the current
>manual, [which
>says](http://pandoc.org/MANUAL.html#extension-latex_macros) that the
>`latex_macros` extension only affects "output formats other than
>LaTeX."  However, the manual does helpfully add: "When `latex_macros`
>is disabled, the raw LaTeX and math will not have macros applied. This
>is usually a better approach when you are targeting LaTeX or PDF."
>
>What changes are called for?  I can think of two different ways to go:
>
>1.  Modify the documentation so it no longer says "For output formats
>other than LaTeX."
>
>2. Automatically disable the `latex_macros` extension in
>Text.Pandoc.App when the output format is latex.
>
>I prefer (1) to (2).  In general, in pandoc the operation of the
>readers does not depend on which writer is being used.  I think this is
>a good principle to maintain.  It ensures, for example, that `pandoc -t
>latex` will not diverge from `pandoc -t json | pandoc -f json -t
>latex`.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jgm/pandoc/issues/4846#issuecomment-414493096

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jgm** [comment]
I'll close this then.
