### ISSUE TITLE
comments in tex math can cause problems

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#4880]
Simple example:

```
% pandoc -t latex
$hi%there$
\(hi%there\)
```

Possible solutions:

1.  Strip all comments from tex math before including in the AST.
2. Tokenize tex math before writing as LaTeX, and if it ends with a comment, add a newline.

(Note:  we don't in general want to add a newline, because pandoc's markdown needs the closing `$` to be adjacent to non-whitespace.)

**Comment by HaoZeke** [comment]
Isn't this the expected behavior for math environments?
The idea is that % has meaning in $$ right?

**Comment by jgm** [comment]
Yes, % has meaning in $$.  But if the % occurs on the
same line as the closing $$, you have problems,
because the whole thing turns into a comment!

**Comment by HaoZeke** [comment]
So is the intended use-case to add comments in inline math environments? AFAIK (just tested) comments are not recognized inside $ $ normally.

1. Sounds more like the expected behavior, since comments in $ $ would not make make sense
2. Tokenizing and adding a newline would mean (?):

```latex
$\sin %test
$
```
Which would still not be interpreted as a comment.

**Comment by jgm** [comment]
> Which would still not be interpreted as a comment.

Yes it would (in latex, but not in pandoc's markdown).
We're talking about writing LaTeX here - also, we use `\(..\)` delimiters, so the output would be
```
\(\sin %test
\)
```
