### ISSUE TITLE
use of reference link in a list item is considered redefinition of the reference

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#4899]
I can see this warning with pandoc 2.2.3.2:

```
>type test.md
[ref]: https://google.com

List:

- [ref]: This is a ref.

>pandoc -f markdown -t native test.md
[WARNING] Duplicate link reference '[ref]' at chunk line 1 column 1
[Para [Str "List:"]
,BulletList
 [[]]]
```

It seems to me that the use of `[ref]` in the list item should not be parsed as reference link definition.

**Comment by jgm** [comment]
A list item can contain any block-level content,
including reference link definitions.  So
you just need to escape the colon to defeat
its interpretation as a referenc link definition.

(Btw, commonmark behaves the same way, partly
because of the principle of uniformity: you
should be able, in general, to lift block
level content into list items or block
quotes without changing its meaning.)

This can be closed.
