### ISSUE TITLE
Using "logo" or "titlegraphic" field  in YAML metadata block with beamer class returns error

### ISSUE THREAD

**Issue by duffau** [jgm/pandoc#4929]
When including a `logo` or `titlegraphic`, as variables in the YAML metadata block,

    ---
    tiltle: My Slide show
    logo: my_logo.png
    ---

and compiling a pdf with the command

    $ pandoc -t beamer slides.md -o slides.pdf`

I get the error 
    
    Error producing PDF.
    pandoc: ./tex2pdf.-219b124216504224/input.log: hGetBufSome: does not exist (No such file or directory)

If I use a custom template and manually put in the path for the `logo` or `titlegraphic` and 

    $ pandoc -t beamer slides.md -o slides.pdf` --template custom_template.tex

it runs without a problem.
pandoc version 2.3
Ubuntu 16.04

**Comment by jgm** [comment]
Here's what I get:
```
 % pandoc -t beamer my.md -o my.pdf
Error producing PDF.
! Package pdftex.def Error: File `my\T1\textunderscorelogo.png' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.95 \end{frame}
```
So I'm guessing the problem is with escaping of the underscore in your filename.  Remember that all metadata content is interpreted as markdown, and converted in the usual way to the output format.  Nothing in the metadata or template tells pandoc that this is intended as a filename, and should be escaped differently.

Here's the solution:  you need to tell pandoc that this is raw LaTeX content:
```
logo: '`my_logo.png`{=latex}'
```

Note: the outer single quotes are needed because it's YAML.  For the rest, see
http://pandoc.org/MANUAL.html#extension-raw_attribute
