### ISSUE TITLE
org mode internal target links and gfm

### ISSUE THREAD

**Issue by memeplex** [jgm/pandoc#4948]
Pandoc is producing `<span id="..."></span>` targets for internal links when the output type is gfm, but github removes every span tag there. The link targets should be exported as `<a id="..."></a>` instead.

```
pandoc 2.2.3.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.3
```

Example:

```
~:: cat /tmp/test.org 
<<xxx>>  [[xxx][my link]]
~:: pandoc -t gfm /tmp/test.org 
<span id="xxx"></span>[my link](#xxx)
```

**Comment by jgm** [comment]
This surprised me, but I was able to confirm it on the wiki sandbox.
My `<span id="foo">` gets rewritten to `<span>`.
My `<a id="foo">` also gets rewritten, to `<a id="user-content-foo>`.

This seems contrary to the gfm spec.  It lists [some disallowed tags](<https://github.github.com/gfm/#disallowed-raw-html-extension->), not including span, and says "All other HTML tags are left untouched."  So this seems to be undocumented behavior, unless I'm not looking in the right place.

@kivikakk can you shed some light on this?

**Comment by kivikakk** [comment]
We perform much post-processing to user content on GitHub; the README file on [`github/markup`](https://github.com/github/markup#readme) shows the additional steps that are taken after Markdown to HTML conversion. While step 1 is the GFM parser ([`github/cmark`](https://github.com/github/cmark)) without any changes, we then transform the rendered HTML in many ways. You're seeing sanitisation in effect, which doesn't happen in our Markdown parser. This makes sense when you consider e.g. @mentions such as @kivikakk aren't part of the GFM spec, nor many other GitHub-specific features.

We prefix the `<a>` element's `id` in order to prevent users from clobbering ids of elements in the surrounding page, which could become a security issue given our JavaScript will lookup elements by `id`, not expecting that user content could arbitrarily replace them.

**Comment by jgm** [comment]
@kivikakk, thanks for the explanation. The transformation of the id makes sense.  What's a bit more surprising is that the id element on a span gets removed entirely, whereas the id on an a element is simply altered.  What's the rationale for that?

**Comment by kivikakk** [comment]
Ugh — `<span>` is not meant to be an allowed tag at all (seeing as it can serve no use given it allows no attributes). The wiki code is a bit behind the code on the rest of dotcom, where `<span>` is stripped entirely.

**Comment by kivikakk** [comment]
`<span>` as a tag is intended to be entirely disallowed — if we were to make any changes to Wiki formatting behaviour, it would be to bring the Wiki sanitisation in line with the rest of the site, rather than changing the rest of the site to allow `<span>` (and then to additionally allow `id` on it). Our security team needs rationale for modifying the sanitiser, and I don't think this case (Pandoc using `<span>` for anchors instead of `<a>`) would be considered enough.

**Comment by jgm** [comment]
I understand about style.  I still think it's too bad that `<span>` + id doesn't work; that's a useful combination.  We could think about having pandoc special-case the rendering of native Spans for gfm, using `<a>` instead of `<span>`, but that seems a bit odd, and it might be surprising to some users.

**Comment by mb21** [comment]
Span is a non-semantic general-purpose inline container. With GitHub (understandably) disallowing the `style` and `class` attributes, the only remaining use-case is the `id` attribute to make some kind of anchor, but historically an empty `<a>` has been used for that in HTML.

Another way would be for pandoc to use an empty link instead of an empty span to represent an anchor in the AST. Unfortunately, that doesn't seem to work in `gfm` either:

    $ echo '[](){#foo} [mylink](#foo)' | pandoc -t gfm
    []() [mylink](#foo)

**Comment by jgm** [comment]
Well, I suppose we can just modify the gfm writer so
that for Span attr ils, it emits an `<a>` tag with an
id (if attr includes an id), omitting other
attributes, and nothing if attr has an empty id.

**Comment by kivikakk** [comment]
@jgm We have the 👍  from security to make the whitelist change, so let me know which path you'd prefer.

**Comment by jgm** [comment]
Cool!  Well, my preference would be for GitHub to pass through spans without stripping id attributes.

**Comment by memeplex** [comment]
@jgm is it not more robust (say against other hosts, like gitlab) to use <a> for links and <sub>, <sup> for sub/super scripts?

**Comment by kivikakk** [comment]
@jgm this'll be done once my PR gets merged. I'll let you know!

**Comment by kivikakk** [comment]
<span id="xyz">Fixed!</span> (try checking the HTML of this comment for reference.)

**Comment by jgm** [comment]
Great, glad to hear about the fix. Closing this.
