### ISSUE TITLE
Do not override --quickcheck-tests= argument

### ISSUE THREAD

**Issue by link2xt** [jgm/pandoc#4956]
Since commit https://github.com/jgm/pandoc/commit/13f8f3c1a8b4a8b01a7ba71a7e42afa6615e537b running

    $ stack test --fast --test-arguments='-p Muse.Blocks.Round --quickcheck-tests=10000'

runs only 25 tests. Instead of simple `withMaxSuccess 25` there should be some check for non-default value.

Not urgent, I can remove `withMaxSuccess` temporarily when needed, but anyway.

**Comment by jgm** [comment]
If you want to create a variant of withMaxSuccess that
is conditional on a check for default value, that
would be okay with me.

Or maybe there's a way to modify the round-trip test
you're using so that it takes less time with the
default values; then we could remove withMaxSuccess
here.

I do think it's important that the default test suite
runs fairly quickly.
