### ISSUE TITLE
Latex \lambdabar unexpected end of input

### ISSUE THREAD

**Issue by Munken** [jgm/pandoc#4966]
I'm typesetting a document with the ƛ symbol. There is no native LaTeX symbol for this, so I'm using the solution provided here: https://tex.stackexchange.com/a/96482

A minimal example looks like this:
```latex
\documentclass{article}

\makeatletter
% \renewcommand{\baselinestretch}{2} 
\newcommand{\lambdabar}{{\mathchoice
    {\smash@bar\textfont\displaystyle{0.25}{1.2}\lambda}
    {\smash@bar\textfont\textstyle{0.25}{1.2}\lambda}
    {\smash@bar\scriptfont\scriptstyle{0.25}{1.2}\lambda}
    {\smash@bar\scriptscriptfont\scriptscriptstyle{0.25}{1.2}\lambda}
  }}
\newcommand{\smash@bar}[4]{%
  \smash{\rlap{\raisebox{-#3\fontdimen5#10}{$\m@th#2\mkern#4mu\mathchar'26$}}}%
}
\makeatother

\begin{document}
$\lambdabar$
\end{document}
```

This fails with:
```
> pandoc -s pandoc.tex -o pandoc.txt
Error at "source" (line 17, column 3):
unexpected end of input
$\lambdabar$
```

I do not expect pandoc to realize that this is lambda bar, but I would expect it not to choke.

**Comment by jgm** [comment]
Pandoc chokes because it is trying to parse the
math (for conversion to other formats).

It can handle most vanilla latex, but it can't
handle the use of low-level tex typesetting primitives
in your macros.

The solution, if you want pandoc to ignore it, is
to throw a macro redefinition into your document:

\renewcommand{\lambdabar}{ƛ}

(or whatever).
