### ISSUE TITLE
Pdf shows "List of Tables" and "List of Figures" even if there are none!

### ISSUE THREAD

**Issue by anishmittal2020** [jgm/pandoc#4968]
pandoc 2.2.1

Pdf shows "List of Tables" and "List of Figures" even if there are none present in the markdown files. I add `lof: true` and `lot: true` in a common Yaml config file, such that `List of Figures` and `List of Tables` are displayed if exists.

# Example

```markdown
---
lof: true
lot: true
---

# H1

## Table and Figure

This file has no Figures and Tables
```

# Expected Output

Should not show "List of Tables" and "List of Figures"  when no tables or figures are present.

**Comment by jgm** [comment]
`lof: true` means: include a list of figures.  That's just what pandoc did.  I'm not sure why you expected it to do something else.

**Comment by anishmittal2020** [comment]
@jgm I was hoping that lof and lot should be included only if there is a picture or a table respectively, when they configured to be true.

**Comment by jgm** [comment]
Anish Mittal <notifications@github.com> writes:

> @jgm I was hoping that lof and lot should be included only if there is a picture or a table respectively, when they configured to be true. 

Two possible ways to achieve that:

- Define a special version of \listoffigures that just
  does nothing if there are no figures (unlike the
  normal \listoffigures).  Actually, you're welcome to
  do that now; if you redefine \listoffigures in a
  custom template, things will work as you like. But
  this may be a difficult tex project.  I wouldn't
  know how to do it myself, and I wouldn't want to put a
  complex definition in the default template.

- Have pandoc override the user's setting of the `lof`
  and `lot` variables, so that even if the user sets
  them to True, pandoc will make them False if there
  are no figures/tables.  This might be pretty
  surprising to users.

**Comment by agusmba** [comment]
> - Have pandoc override the user's setting of the `lof`
  and `lot` variables, so that even if the user sets
  them to True, pandoc will make them False if there
  are no figures/tables.  This might be pretty
  surprising to users.

I agree this would raise a few eyebrows.
Wouldn't this be doable in a lua filter so that the user explicitly seeks this behavior?

**Comment by mb21** [comment]
Agreed, let's close this. Feel free to reopen if anyone comes up with a simple solution that's non-surprising to the user.

**Comment by anishmittal2020** [comment]
@mb21 To prevent surprising users, we could provide this feature as a Pandoc extension, which a user has to manually include.

**Comment by anishmittal2020** [comment]
@mb21 is it worth reopening this issue?

**Comment by jgm** [comment]
A lua filter would definitely be possible. The filter would inspect the document for Figure and Table elements, and update the metadata `lof` or `lot` variables accordingly.
@anishmittal2020 if you need help with writing such a filter, you can ask on pandoc-discuss.

**Comment by jgm** [comment]
> To prevent surprising users,

Note that this only comes up if you have `lot` and `lof` in a standard metadata file that you include in every document. I don't know how common this is.
