### ISSUE TITLE
Write raw openxml blocks in Powerpoint writer

### ISSUE THREAD

**Issue by noamross** [jgm/pandoc#4976]
While the Docx writer writes ```{=openxml}` blocks ([here](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Docx.hs#L939-L940)), the Powerpoint writer does not, ignoring all raw blocks ([here](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Powerpoint/Presentation.hs#L449)).  It would be great if we could pass raw openxml to the Pandoc writer.  The use-case I am considering is inserting programmatically-generated vector graphics into presentations. (Via R Markdown and @davidgohel's [**rvg**](https://github.com/davidgohel/rvg) which generates office DrawingML).

**Comment by jgm** [comment]
@jkr this seems a reasonable suggestion, and it should be fairly easy to implement (see what we do for RawInline and RawBlock in the Docx writer).  What do you think?

**Comment by jkr** [comment]
In principle, it should be possible. The only concern I have is that
ooxml changes in an individual slide might have to be mirrored or
referenced in other documents (see
http://officeopenxml.com/anatomyofOOXML-pptx.php). We can build this in
when we go from the internal type to pptx, but it can be trickier if
we're entering raw xml. So really it should just be for (selectively
formatted) text.

But, that being said, the same applied for adding raw ooxml to docx, so
I guess a general hand-washing caveat emptor is sufficient from our end?

I'll try to take a look at this soon, but if I end up lagging (as has
been the case a lot recently), a roadmap would be:

1. in Presentation.hs

   a. Add some sort of Raw{Block/Inline} types to the Shape and ParaElem
      algebraic datatypes

   b. convert to them appropriately with
      blockToShape/inlineToShapeElemes. This should probably parse the
      xml instead of just recording the text to make the next step
      easier.

2. in Output.hs

   a. in shapeToElement/paraElemToELement, convert the Raw types to xml
      (parse if you didn't in the previous step). We can't just keep
      them as text, because we want them to be part of an element.


Parsing and reserializing seems easier than keeping as text, since
otherwise we'd have to figure out some trick of keeping a placeholder in
the elements during the conversion step in output.hs, and then inserting
the text during the final printing. But I could be missing something.

**Comment by jkr** [comment]
> Parsing and reserializing seems easier than keeping as text, since otherwise we'd have to figure out some trick of keeping a placeholder in the elements during the conversion step in output.hs

The alternative approach would be somehow to change some of the output functions to produce `Content` instead of `Element`. This would let us keep the ooxml in its raw form, though would add hassles along the way.

**Comment by jkr** [comment]
Oh -- okay, I just looked at the docx writer, and it is parsed there. So that's probably the best way.
