### ISSUE TITLE
Performance issue converting markdown containing HTML code (<span>)

### ISSUE THREAD

**Issue by jschleus** [jgm/pandoc#5023]
I'm the admin of a FOSS server that allows also browsing of HTML-formatted markdown files (using the great program Pandoc). That works for thousand of such files very well but today an according Pandoc process after two hours (!) hasn't finished. The version in use is Pandoc 2.3.1 (the Linux binary was taken from GitHub) and the file is `nss/gtests/google_test/gtest/docs/advanced.md` from the package
  https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_40_RTM/src/nss-3.40.tar.gz
By the way, just the mentioned member file can be separately downloaded via
  https://fossies.org/linux/nss/nss/gtests/google_test/gtest/docs/advanced.md?m=t

After some trail and error tests I came to the conclusion that the problematic code seems to be in the lines 2158-2172 looking like
```
<span style="color:green">[----------]<span style="color:black"> 1 test from FooTest<br/>
```
In a reduced test szenario I found depending of the number N of such lines an exponential increase of the according conversion time:
```
 N  secs
==  ====
 6     1
 7     4
 8    16
 9    70
10   280
11  1133
```

**Comment by jgm** [comment]
Pandoc's parsing algorithms do have some bad
performance characteristics in certain edge cases
(e.g. a whole string of open spans with no closers,
as in your example -- pandoc searches to the end
looking for the closers, each time, which is why
you get exponential blowup).  See also #1735.

Because of this, any web-facing service that uses
pandoc should have a timeout on threads.

If you want a markdown parser written with performance
in mind, you might try cmark (which I also wrote).
Or you could try using the gfm output format of pandoc
(since this just uses libcmark).  Of course, this
means you'd have to do without all the nice pandoc
options.

Note, finally, that this doesn't actually concern raw HTML.
Pandoc is trying to parse the span tags as "native spans"
(see the manual).  If you turn off the `native_spans` extension,
I think you'd see different behavior.

**Comment by jgm** [comment]
Confirmed:  with `-f markdown-native_spans` this input is no longer a performance problem.

**Comment by jschleus** [comment]
Thank you for your very detailed explanation. And yes, `-f markdown-native_spans` helps "dramatically" (nevertheless I implemented additionally an according monitoring service).

`<ADV>`
By the way, Pandoc is also featured on the mentioned server  (amongst others with Doxygen docs): https://fossies.org/linux/pandoc
`</ADV>`
