### ISSUE TITLE
rst references with one underscore `g <www>`_ not remembered

### ISSUE THREAD

**Issue by rpuntaie** [jgm/pandoc#5081]
Pandoc 2.4

[RST](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#hyperlink-references>) 
distinguishes between one underscore and two underscore links.

Pandoc does not.

This works:

```
    echo "`g <www.google.com>`_. Go to `g`_" > t.txt
    rst2html.py t.txt
```

But Pandoc reports `[WARNING] Reference not found for 'g' at line 1 column 35`.

```
    pandoc -f rst -t html t.txt
```

**Comment by jgm** [comment]
Test case, for convenience:
```
Go to `g`_  `g <www.google.com>`_. 
```
(Note that these can be in either order.)

From the docutils manual, for convenience:
```
A hyperlink reference may directly embed a target URI or (since Docutils 0.11) a hyperlink reference within angle brackets ("<...>") as follows:

See the `Python home page <http://www.python.org>`_ for info.

This `link <Python home page_>`_ is an alias to the link above.
This is exactly equivalent to:

See the `Python home page`_ for info.

This link_ is an alias to the link above.

.. _Python home page: http://www.python.org
.. _link: `Python home page`_
The bracketed URI must be preceded by whitespace and be the last text before the end string.

With a single trailing underscore, the reference is named and the same target URI may be referred to again. With two trailing underscores, the reference and target are both anonymous, and the target cannot be referred to again. These are "one-off" hyperlinks.
```
(I see this is docutils 0.11+, which explains why pandoc didn't have it originally.)

This will be tricky to implement, given the current two-pass parsing strategy, since we only pick up references from explicit reference definitions.  We may need to change to using the F Monad, as we do in the Markdown reader, to support this properly.
