### ISSUE TITLE
Add support for blank slides with powerpoint output.

### ISSUE THREAD

**Issue by W1M0R** [jgm/pandoc#5097]
### Original (24 November 2018)

There is currently no way to specify an intentional blank slide for powerpoint output.

For blank slides with reveal.js, I can specify markdown input like this:

```markdown
# [Blank Slide]{.hidden} {data-background-color="black"}

[This slide is intentionally left blank. It contains notes about the next slide. Apply the blank slide layout.]{.hidden}
```

`.hidden` is my own CSS style that applies `display: none`. This allows headings and content to still display (for information purposes) in non-slide output formats (e.g. pure html or pdf).

I would like to have the powerpoint output to also know that the slide should be blank. I have a reference.pptx file with the blank layout in the slide master as I would like to have it (e.g. no text with a completely black background), but I don't have a way to specify that the 'blank' layout should apply to the slide.

Blank pages are useful: https://en.wikipedia.org/wiki/Intentionally_blank_page

Perhaps YAML frontmatter can be used to specify the slide layout for powerpoint output specific? It may even be made more general to apply to all slide output formats, but a powerpoint-only solution would satisfy my requirements.

### Edit (18 December 2018)

Just some clarifications about what I mean.

It is possible to create 'blank content' slides for powerpoint output using markdown input. But the powerpoint layout used for the blank slide is the same layout as for the non-blank slides. Powerpoint master slide layouts support a variety of predefined layouts, that can each be styled separately. I think Pandoc supports four of those predefined layouts, and applies them automatically based on the content of the slide. One of the predefined powerpoint layouts, is called 'Blank' or 'None'. I would like this predefined Blank layout to be applied to slides that have no content. If I edit the reference document or template (let's say reference.pptx), and change the properties of the Blank layout (let's say to use a black background instead of the default white), then the blank slides in my pandoc-generated pptx file, should have a black background.

If this can't be achieved using the predefined Blank layout, then perhaps it should be possible to style a powerpoint slide (i.e. set its background color) using Pandoc classes or some other method.

**Comment by jkr** [comment]
I see the need for this. But it's tricky because we have to remove empty slides that are produced by the way slides are split (see cdbe45e8).

So we need some way to indicate an intentional blank slide. Perhaps two consecutive hrules would be a good way to signify this from the markdown side? @jgm: what do you think?

**Comment by jkr** [comment]
It doesn't work at the moment. The issue was that the process of making
slides requires some fairly opinionated splitting (images have to create
new slides, for example) due to the fact that everything has to fit into
pre-existing slide templates. The result was that there were a number of
ways that you could get accidental blank slides. The easiest solution
was to remove blank slides, but this turns out to disallow something
people want to do.

The better, though more difficult, way would be to try to enumerate the
ways in which you could get blank slides accidentally and try to deal
with them ahead of time.

It might be cleaner to just introduce an IntentionallyLeftBlank slide
type, since it might be easier to catalog the ways blank slides are
intentionally created, rather than cataloging the ways they might be
unintentionally created.

**Comment by jgm** [comment]
Jesse Rosenthal <notifications@github.com> writes:

> It doesn't work at the moment. The issue was that the process of making
> slides requires some fairly opinionated splitting (images have to create
> new slides, for example) due to the fact that everything has to fit into
> pre-existing slide templates. The result was that there were a number of
> ways that you could get accidental blank slides. The easiest solution
> was to remove blank slides, but this turns out to disallow something
> people want to do.

OK, I see.

> It might be cleaner to just introduce an IntentionallyLeftBlank slide
> type, since it might be easier to catalog the ways blank slides are
> intentionally created, rather than cataloging the ways they might be
> unintentionally created.

I'd prefer, if possible, to have all the slide formats
work the same way.  Since a blank heading or hrule
can currently create a blank slide in the other
formats, it would be nice if this also worked in pptx.

I don't understand why images have to create new
slides.  Can't you have powerpoint slides with a header,
then an image, then more text?  Seems like most
powerpoint slides I've seen are like that.

**Comment by jgm** [comment]
Jesse Rosenthal <notifications@github.com> writes:

> John MacFarlane <notifications@github.com> writes:
>
>> I don't understand why images have to create new
>> slides.  Can't you have powerpoint slides with a header,
>> then an image, then more text?  Seems like most
>> powerpoint slides I've seen are like that.
>
> The issue is that powerpoint isn't a flowing format. It's a visual
> format, with boxes (shapes) placed at coordinates depending on a
> laouts. We use four layouts, which are found in default templates
> (including the ones shipped with MS PP).

Ah yes, that makes sense.

Rather than introduce a new, ad hoc way of doing blank
slides for powerpoint, why not just document in the
manual that if you want a blank slide you should have
a slide with a blank header and a single &nbsp; as content?
