### ISSUE TITLE
AsciiDoc Writer: Support Single-Line Comments

### ISSUE THREAD

**Issue by znerd** [jgm/pandoc#5130]
Please extend the AsciiDoc writer to support single-line comments.

**Steps to reproduce:**
1. Have a file `test.html`, like this:
```
$ cat test1.html                                  
<html>
<head><meta charset="UTF-8"><title>Doc Title</title></head> 
<body>Sentence 1. <!-- Comment 1 --> <p>Sentence 2. <!-- Comment 2 --></body>
</html>
```
2. Run pandoc with `raw_html` extension:
```
$ pandoc -t html+raw_html < test1.html
```

**Expected results:**
1. Output produced in step 2 is:
```
Sentence 1.
// Comment 1

Sentence 2.
// Comment 2
```

**Actual results:**
1. NOK: Output produce in step 2 is:
```
Sentence 1.

Sentence 2.
```

**Extra information:**
- Using Pandoc 2.5
- Asciidoctor syntax reference for AsciiDoc comments: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#comments

**Comment by jgm** [comment]
Pandoc's internal document model doesn't have any place for comments.  The comments in your input are parsed and stored as raw HTML; that's why they are omitted.  If we had native comments, we could do things differently, but we don't.  See #1926.  Since this is basically the same issue, I'll close this one.
