### ISSUE TITLE
<i> and <b> tags in Textile

### ISSUE THREAD

**Issue by sephshewellbrockway** [jgm/pandoc#5263]
Any chance of implementing the HTML `<i>` and `<b>` tags, which (as of HTML5) have different semantics from `<em>` and `<strong>`? Textile in particular requires that `__blah__` be rendered as `<i>blah</i>`, as opposed to the single-underscored version _blah_ which is `<em>blah</em>`. Similarly, Textile includes the syntax `?blah?`, rendered as `<cite>blah</cite>`. These tags are necessary if Pandoc is to implement the Textile standard correctly.

I am happy to do the coding necessary to implement these features.

**Comment by mb21** [comment]
That would probably require changes to pandoc's internal document AST, which is modeled after markdown where such a distinction does not exist.

There have already been a few discussions to whether pandoc should make a distinction between `<i>` and `<em>` and the conclusion was that it's not really worth it. You can always write a pandoc filter to change them or when writing markdown use [spans](https://pandoc.org/MANUAL.html#extension-bracketed_spans) and convert them with a filter.

For textile input, you can use a pandoc filter or simply use raw HTML:

    echo '<i>foo</i> _bar_' | pandoc -f textile

    <p><i>foo</i> <em>bar</em></p>

**Comment by jgm** [comment]
I agree that this should probably be closed.  Pandoc conversions generally lose distinctions, because everything goes through a document model that is simpler than most of the formats we support.  This is discussed right at the beginning of the manual.

With `?cite?` we might want to consider parsing it as a span with a class; then at least you can do something with it.

**Comment by jgm** [comment]
Looks like we don't currently parse `?cite?` as anything, but this should be a separate issue I think.

**Comment by duckwork** [comment]
I just discovered Textile and I like its distinction between semantic distinctions between tags, as I write a lot about books and would like an easy way to use a <cite> tag et al.

Would a good middle-ground be to use Pandoc to transform `__italic__`, e.g., to `<em class="i">italic</em>`, with Textile and other formats, so that users who don't care about the distinction will still have the bare, simpler markup from Pandoc, and those who *do* care can use a filter to easily convert the classes to the proper tags? It could be switchable, too, perhaps.

**Comment by jgm** [comment]
We can convert to `<em class="i">`.  Currently Emph elements don't have attributes in the pandoc AST.

I think this issue should be closed, and a separate issue opened to parse `?cite?` if desired.
