### ISSUE TITLE
Dokuwiki math support [enhancement]

### ISSUE THREAD

**Issue by bachmeil** [jgm/pandoc#5319]
Conversion from Dokuwiki doesn't support math. The standard way to add math to a Dokuwiki page is with the MathJax plugin, and the syntax is the same as markdown. This currently fails:

```
$$y_{i} = \varepsilon_{i}$$
```

with message

```
Error at "source" (line 5, column 5):
unexpected "i"
expecting "{{"
$$y_{i} = \varepsilon_{i}$$
    ^
```

The error message says `expecting "{{"` but that's because it's trying to link to an image. That doesn't help with math.

**Comment by RyanGreenup** [comment]
Yeah I just ran into this, I tried:

```bash
pandoc -f dokuwiki+tex_math_double_dollars -t latex 
```
and it returns an error saying that there is no support.

I would love to see this implemented because dokuwiki is very common and as opposed to mediawiki does not require a database making it more portable.

A workaround that I hope continues to work is to do this:

```bash
pandoc input.txt -f dokuwiki -t org | pandoc -f org -t pdf -o file.pdf
```

This isn't too bad because `org-mode` supports a tonne of markup and so should handle most things fairly well.

**Comment by RyanGreenup** [comment]
Actually, after thinking about this, `org` supports escaping and commenting so that behavior might change over time, a better work around would be this:

```bash
cat input.txt | \
pandoc -f dokuwiki -t html | pandoc -f html+tex_math_dollars+tex_math_single_backslash -t html --mathjax \
-s  -o file.html
```

When *DokuWiki* is exported to *HTML* the math is just wrapped in paragraph tags like this `<p> $4x^3$ </p>`, they won't be captured by mathjax because they don't have the correct class, this is unlikely to be changed because it's expected syntax/behavior.

By piping that HTML back into `pandoc` with the `tex_math` extensions, the math should be appropriately wrapped to something like `<p><span class="math inline">\(1y\)</span></p>`, this again is unlikely to change, because, it's expected behaviour of the extension.

the `-s` option will be necessary to have the mathjax javascript in the header, but, if you needed to use `--self-contained` to embed images and CSS you'd probably want to leave that off (I personally wrap CSS files in style tags, throw `<script>...mathjax...</script>` into the file and use the `-B` option with `--self-contained`, it's usually simpler)

HTML is pretty much as descriptive a markup language as you can get so going from there to latex/mediawiki/markdown should be a non-issue.

This also works in reverse to go from HTML into dokuwiki.

## Example

<details><summary><b> CLICK HERE</b></summary><p>

```bash
 echo '                                                                                                                                                      
        ====== SandBox ======
        Some Math



        \( 1x \)

        \[
        2x
        \]

        $1y$

        $$
        2y
        $$
        ' | \
        pandoc -f dokuwiki -t html | \
       pandoc -f html -t html+tex_math_dollars+tex_math_single_backslash --mathjax \
       -s 
```
</p>
</details>

**Comment by RyanGreenup** [comment]
To go in the other direction from `org-mode` to dokuwiki without losing raw LaTeX this filter could be used:

```python
#!/usr/bin/env python

"""
Pandoc filter to convert raw tex to paragraph for dokuwiki
"""

from pandocfilters import toJSONFilter, Emph, Para

def raw_to_para(key, value, format, meta):
  if key == 'RawBlock' and value[0] == 'latex':
    math_content = value[1]
    math_value=[{
            "t": "Str",
            "c": math_content
                }]

    return Para(math_value)

if __name__ == "__main__":
  toJSONFilter(raw_to_para)
```

so save that in `filter.py` and then run:

```bash
chmod +x filter.py
pip install pandocfilters
pandoc file.txt -f dokuwiki -t org --filter ./filter.py 
```

**Comment by jgm** [comment]
This case now works fine with `-f dokuwiki+tex_math_dollars`.
