### ISSUE TITLE
Image align in commonmark

### ISSUE THREAD

**Issue by sents** [jgm/pandoc#5329]
I am converting dokuwiki  pages to commonmark and it appears to me, that image alignment doesn't work.
An example for the source:
```
|{{ :changelog:mathematica-logo.png?nolink}}The //Mathematica// license server has been upgraded to version x.x.x. Mathematica has been upgraded to on all linux hosts.|
```
And get converted to:
```
<td><img src="/changelog/mathematica-logo.png" alt="mathematica-logo.png" class="align-right" />The <em>Mathematica</em> license server has been upgraded to version x.x.x. Mathematica has been upgraded to on all linux hosts. </td>
```
In the image tag we see class="align-right" so it seems pandoc has inferred that it should use right align.
However with commonmark class="align-right" will not work. Instead align="right' should be used.

**Comment by jgm** [comment]
What's happening here is that the commonmark writer is using HTML for the table, since commonmark by default doesn't have a native table syntax.

The HTML is perfectly valid.

If you want this HTML to render with a right-aligned cell, you just need to add some CSS that reacts to this class.

The `align` attribute on `img` is not supported in HTML5.  That is why a class is used instead.
https://www.w3schools.com/tags/tag_img.asp

**Comment by sents** [comment]
Thanks for the clarification!
