### ISSUE TITLE
Disable smart extension by default if output format is man

### ISSUE THREAD

**Issue by danielbayley** [jgm/pandoc#5384]
I've been [working] on some useful `--lua-filter`s for converting Markdown `README`s to `man` pages… and realised that I can’t think of any good reason for the smart typography extension to be enabled by default in this scenario.

[working]: https://github.com/danielbayley/homebrew-pandoc-mandown

**Comment by jgm** [comment]
Do you mean on the reader or the writer?  `smart` can be enabled or disabled separately on each.
`smart` is enabled by default for the markdown reader, no matter what the output format, and that won't change.  (As a general principle, reader behavior is not affected by the writer used.)  As far as I can see, `smart` has no effect on the man writer (though it is not enabled by default).  So I can't see anything to do here.  You can turn off `smart` in the markdown reader by doing `-f markdown-smart`.

**Comment by jgm** [comment]
Anyway, with `smart` the markdown -> man translation is good.
You get `\[lq]` and `\[rq]` instead of `\[dq]`.
And man will know how to render that in a way that is appropriate for the output format.  (Remember that man pages can be rendered to HTML or PDF as well as the terminal.)

**Comment by alkisg** [comment]
I agree with @danielbayley that smart should be disabled for the markdown reader when the output is man; i.e. the default reader options **should** be affected by the writer used.

Without it, `command --option` get transformed into `command \[en]option`, which of course doesn't work when copy/pasted in shell.

Until this is fixed, I'd like to use `pandoc -s -f markdown-smart -t man`, but this fails on older Debian and Ubuntu versions because their pandoc doesn't have the smart extension.
So I'd like to do a version check; which was the first pandoc version that supported the smart extension for the markdown reader?

Thank you.

**Comment by jgm** [comment]
You ought to be using a code span for this anyway:
```
`command --option`
```
will not be affected by `smart`.

**Comment by alkisg** [comment]
Hi @jgm, thank you for your input,

code spans should not be used in man page definition lists. See an example from the [ltsp.8.md man page](https://github.com/ltsp/ltsp/blob/main/docs/ltsp.8.md#options):

```markdown
**-t**, **--tftp-dir**=_/srv/tftp_
:   LTSP places the kernels, initrds and iPXE files in /srv/tftp/ltsp, to be
    retrieved by the clients via the TFTP protocol. The TFTP server of dnsmasq
    and tftpd-hpa are configured to use /srv/tftp as the TFTP root.
```

In manpage definition lists, the option itself should be in bold, and the placeholder/example/variable part should be in italic.
These are described in [man man](https://manpages.debian.org/man):

```shell
bold text         type exactly as shown.
italic text       replace with appropriate argument.
[-abc]            any or all arguments within [ ] are optional.
-a|-b             options delimited by | cannot be used together.
argument ...      argument is repeatable.
[expression] ...  entire expression within [ ] is repeatable.
```

A workaround is to escape the second dash with backslash, e.g. `**-\-tftp-dir**=`, but markdown is supposed to make life simpler, not harder...

Would you happen to remember in which pandoc version the smart extension was added, so that I can special-case it in my Debian packages build scripts?

**Comment by jgm** [comment]
Code spans indicate that the enclosed content is to be taken literally, and not interpreted as markdown, which is what you want.  As for rendering, pandoc-generated man pages render these in boldface anyway.  See pandoc's own manual.  Here's a section of the markdown source:
````
`-o` *FILE*, `--output=`*FILE*                          
                                                               
:   Write output to *FILE* instead of *stdout*.  If *FILE* is
    `-`, output will go to *stdout*, even if a non-textual format
    (`docx`, `odt`, `epub2`, `epub3`) is specified.
````
This is rendered by `man` as

<img width="663" alt="Screen Shot 2022-01-15 at 10 36 06 AM" src="https://user-images.githubusercontent.com/3044/149633812-2860d5e3-6b1b-4f49-9347-7b258652e131.png">

Note that `\f[CB]` is used here, so that when you render the man page to HTML, you'll get a monospace font in addition to boldface; again, I think this is desirable.

**Comment by alkisg** [comment]
While this is a solution, it is a solution that is specific to pandoc. It doesn't cover for example the "render the man page via mkdocs" route; we'd have to patch mkdocs, [markdown-extended](https://marketplace.visualstudio.com/items?itemName=jebbs.markdown-extended) and whatever other tools we're using to write and publish our man pages.

See for example how mkdocs renders that page in our site: https://ltsp.org/man/ltsp/#options
Had we used a code block there, it would render with the usual gray background, and it wouldn't look good, nor would it match the manpage formatting recommendations:

`-o` *FILE*, `--output=`*FILE*

Another example is when we want to include quotes in the variable part (where you put the `*FILE*`), e.g. `*"some example that needs quotes"*`; these then render as smart quotes and make the example unusable.

**Comment by jgm** [comment]
The convention of rendering options as boldface comes from the need to display man pages in a terminal, where there really isn't an option of putting the options in a monospace font (since everything is monospace).  It makes sense for terminal rendering (and there pandoc conforms to the normal expectations), but I don't see why it makes sense for the web.  I don't agree that your example looks bad with a code span in its default formatting.  To the contrary, that makes it much clearer which parts of the specification are meant to be typed literally.  But, perhaps this is a matter of taste.

**Comment by jgm** [comment]
Another solution for mkdocs is to [customize your theme](https://www.mkdocs.org/user-guide/customizing-your-theme/) with something like
```
dt code { font-weight: bold; }
```

**Comment by alkisg** [comment]
Indeed, but it's still the wrong presentation (code span), fixed with CSS, instead of being bold in the first place.
Why is it so important to give em-dash a priority when writing man pages? Do people need em-dash frequently? As a programmer, I never use em-dash...

Anyway I think we both made our points, and of course the choice is up to you, if you don't want to support this use case we can always just post-sed the pandoc generated man pages. Thank you very much!

**Comment by jgm** [comment]
I'd say it's the right presentation.  This is verbatim text and belongs in a code span.  If you want, you can use CSS to make this render boldface, as it does in terminals (but only because there was no good alternative there!)  Anyway, we've both said our piece and I won't persuade you.  The real issue is that reader and writer behavior should be independent, so the default extensions on the reader should not depend on what writer is being used.  (That would add a lot of complexity and make behavior less predictable.) Asking you to say `-f markdown-smart` is not asking a lot.  If you're using  pandoc < 1.9.2, then  `--smart` is not the default when output is `man`, so you can just do `-f markdown -t man`.
