### ISSUE TITLE
export md to pdf: the iframe not display all

### ISSUE THREAD

**Issue by wxqanl** [jgm/pandoc#5399]
export md to pdf: the iframe not display all

<iframe src='json.json'  />

When the jsonn file is alway more 100 lines, the after converted, the pdf can not show all the lines

**Comment by mb21** [comment]
By default pandoc uses LaTeX for pdf creation, so this is expected behaviour. For alternatives see http://pandoc.org/MANUAL.html#creating-a-pdf

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
