### ISSUE TITLE
ipynb+citeproc: references div isn't picked up

### ISSUE THREAD

**Issue by choldgraf** [jgm/pandoc#5452]
I'm playing around with references and citeproc in the Jupyter Notebook, and found that things tend to work well but the `::: {#refs} :::` div seems to be missed.

For example, if I have the following markdown:

```
## A bibliography

Here's my bibliography

::: {#refs}
:::

That's it!
```

If this is in a Jupyter Notebook markdown cell, then the references are correctly converted to titles etc, but the bibliography is appended to the end of the document and the `::: { #refs} :::` section is still in there. Here's what I ran:

```
pandoc --filter pandoc-citeproc --bibliography ./bibliography.bib ./post.ipynb -o published/post.html -f ipynb+citations
```

If this is in its own markdown file, then the bibliography is correctly inserted into the middle of the document instead of the end.

Here's what I ran for the markdown conversion:

```
pandoc --filter pandoc-citeproc --bibliography ./bibliography.bib ./post.md -o published/post.html -s
```
Is there a piece of metadata / cell type / etc that I'm missing in the notebook?

**Comment by jgm** [comment]
I see the issue here.  The default syntax extensions for `ipynb` is:
```
    [ Ext_all_symbols_escapable
    , Ext_pipe_tables
    , Ext_raw_html
    , Ext_fenced_code_blocks
    , Ext_auto_identifiers
    , Ext_gfm_auto_identifiers
    , Ext_backtick_code_blocks
    , Ext_autolink_bare_uris
    , Ext_space_in_atx_header
    , Ext_intraword_underscores
    , Ext_strikeout
    , Ext_task_lists
    , Ext_lists_without_preceding_blankline
    , Ext_shortcut_reference_links
    , Ext_tex_math_dollars
    ]
```
which doesn't include the `fenced_divs` extension.  So, if you try to use this extension in a markdown cell in a Jupyter notebook, it won't work.

You can enable the extension by specifying `-f ipynb+fenced_divs` when reading an ipynb and `-t ipynb+fenced_divs` when writing an ipynb.

The question could be asked whether `fenced_divs` should be enabled by default.  Let me explain why it isn't:  I figure that by default people will want markdown in their notebooks that is compatible with GitHub and with the Jupyter app, which as far as I'm aware doesn't support this particular pandoc extension.

**Comment by jgm** [comment]
Since this doesn't seem to be a bug, I'm closing this.
Feel free to comment further if I've missed something.

**Comment by choldgraf** [comment]
oops! I just realize that I wrote the following comment but somehow github didn't send it, I agree it's fine to close :-)

---

yep, that is probably correct - maybe as more folks play around with Pandoc we'll see more notebook workflows that include pandoc syntax, but until then I agree it probably makes sense to assume github-flavored markdown.

I'll close this and will bake this into documentation etc for the jupyter side of things!
