### ISSUE TITLE
Include source location information in debug version of AST

### ISSUE THREAD

**Issue by alerque** [jgm/pandoc#5461]
# The Scenario

I'm tired of using Regular Expressions to try to parse Markdown.

I run a publishing house where the canonical version of all our source material is stored in Markdown, and in the process of editing, translating, and publishing our materials there are a ton of operations that need to be done on the source files that require some level of contextual understanding. As our internal tooling is starting to look more and more like an IDE, more and more of our scripts are having to make guesses about lines in our source files. The most frustrating question to answer reliably is probably this one:

**Is line *N* inside a blockquote? a list item? a fenced code block? a div? a header? some nested combination of blocks?**

This question is surprisingly difficult to answer using general purpose stream editors and text manipulation tools. It isn't very hard to whip a RegEx that takes a wild guess, but it also isn't very hard to start running into edge cases where that guess is wildly off.

Inline context is much easier to parse with RegEx, but still error prone.

**Is word *Y* inside emphasis markup? an inline span with a language attribute?**

# The Request

Implement an optional `--source-location` flag or similar that keeps track of byte offsets while reading input and adds this to the AST tree. This would probably include line, column, and overall input byte offset.

Consider input file `test.md`:

```markdown
foo

> bar
```

I would want to return something like this:
```bash
$ pandoc --source-location -t json | jq
{
  "blocks": [
    {
      "t": "Para",
      "l": {
        "l": 1,
        "c": 1,
        "b": 1
      },
      "c": [
        {
          "t": "Str",
          "l": {
            "l": 1,
            "c": 1,
            "b": 1
          },
          "c": "foo"
        }
      ]
    },
    {
      "t": "BlockQuote",
      "l": {
        "l": 3,
        "c": 1,
        "b": 6
      },
      "c": [
        {
          "t": "Para",
          "l": {
            "l": 3,
            "c": 3,
            "b": 8
          },
          "c": [
            {
              "t": "Str",
              "l": {
                "l": 3,
                "c": 3,
                "b": 8
              },
              "c": "bar"
            }
          ]
        }
      ]
    }
  ],
  "pandoc-api-version": [
    1,
    17,
    5,
    4
  ],
  "meta": {}
}
```

# What could this be used for?

My use case is for the Markdown reader, but I suspect any plain text input format would find benefits for this.

* LaTeX→PDF has a tool callede [SyncTeX](https://tex.stackexchange.com/q/118489/5100) that generates PDFs that can be used in a "preview" type output scenario and clicking on _any_ element can take you back to the line in the source TeX file. This is great boon for IDE's. I would like to do this with Markdown and other source document formats as well without re-inventing the wheel.
    * I would like to build an EPUB reader on our website that people can report translation issues or even be linked to an online editor with the source markdown for that paragraph open to contribute a fix.
    * I would like to print draft layouts that include a footer that shows the source file and line number range represented on each page so that proof readers can easily jump to the right context to make changes. Etc.
* Syntax highlighters often struggle to get Pandoc's more advanced syntaxes sorted out and being able to check the context of a region by inspecting the AST tree would be a huge boon.
* Linters could be implemented as pandoc filters, using Pandoc as the parser to get the context right, but returning output that can be used in the context on an editor.
* Spell checkers
* Natural language analysis tools (like grammar checkers or translation tools).
* ...
* This would also solution for #1417.

**Comment by tarleb** [comment]
I believe this is a duplicate of #4565.

**Comment by alerque** [comment]
@tarleb Which in turn was a duplicate of #3809. Honestly I did search first, but the uses for this are so varied we're all using different terminology and not sure what to call it. The "source map" terminology from web development is certainly related, although that mainly covers minified sources that are the same language on both input and output, hence the separate map file. I think what's needed here is a bit different. The output I described (using `json` because it was easier to syntax for invent than `native`) should work for everybody's use case that I've seen so far.

**Comment by bpj** [comment]
An alternative approach I've used on occasion is to walk through a [Pandoc::Elements][] document object (which essentially is an AST as retrieved from JSON produced by Pandoc plus some Perl magic so that the JSON objects in the AST become Perl objects which can have methods called on them) giving each element object a number unique among all objects and another number unique among the objects of the same type. The code exploited the fact that the `walk()` function of the [Pandoc::Walker][] module incidentally traverses the elements of a document mostly in the order in which they appear in the rendered document, with some extra help to ensure that everything was traversed depth-first. Things were also set up so that for each element there existed a list containing the unique numbers of all its ancestors in order, and in addition to hashes keying unique numbers by object reference addresses there were hashes keying references to the objects themselves by the unique numbers. All this extra info was stored outside the objects in global hashes to avoid circular references and to avoid that the objects were broken when serialized back to JSON. Although I couldn't determine the absolute position of an element in the input text I could determine the relative positions of elements in the AST, answering the questions "does this element come after/before that element" and "is this element an ancestor/descendant of that element". Another limitation was that if I removed some element or replaced it with something else I had to take extra measures to record that removal and/or make the replacement(s) locatable. In practice that was hardly ever needed though. Since the unique numbers were in effect ordered serial numbers I could at any point loop through all elements in the document/of a given type in order by looping through the keys of the serial-to-object hashes in numerically sorted order.

[Pandoc::Elements]: https://metacpan.org/pod/Pandoc::Elements

[Pandoc::Walker]: https://metacpan.org/pod/Pandoc::Walker

**Comment by bpj** [comment]
When you want to match something with a regex, but also want to skip something else which may contain something which would otherwise match the thing you want to match a useful trick is to make a regex with an alternation where the first branch matches the kind of thing you want to skip and the second branch matches the thing you really want to match. The code handling the match checks whether the capture group capturing the thing to skip is defined (i.e. whether it matched anything) and if it did the code just returns/keeps the thing to skip. Otherwise it does whatever it wants to do with the thing you really want to match.

Here is an example implementation in Perl which either matches a Pandoc Markdown "literal" — a backslash-escaped character, a fenced code block or an inline code span, both with or without some attributes — or a fenced div, then either leaves the "literal" in place or replaces the div with something.

All the regexes use named captures, which are generally sanity-preserving in large regexes with many capture groups and many branches. This means that that the code needs perl 5.10.1 to work, but that should hardly be a problem in 2019. (In theory 5.10.0 supported named captures, but a lot of things, notably nested named captures, were broken in that version.)

The regex matching the "literal" is first defined separately so that it can be reused or used to actually match a "literal". It is then included as the first branch in the regex matching a div. (Note that the div-matching regex reuses the named subpatterns for matching attributes defined in the "literal" matching regex.)

You could likewise include the "literal" regex in some other regex, or add further branches matching other things and have the match handling code check which top-level branch matched — i.e. which top-level capture group is defined — and do different things depending on what the regex matched. I usually use a dispatch table where the keys are the names of top-level capture groups and the values are the functions for handling each case, then for each match I loop through the keys and call the function corresponding to the group which matched, with a hash reference containing the named captures from the match among the arguments.

Some things in these regexes will probably need some changes to make them work e.g. with Python's extended *regex* module. For one thing I think only Perl supports multiple capture groups with the same name. They very convenient and are used in a spot or two.

````````perl
=begin Explanation

This regex matches 

1.  a Pandoc fenced code block (tildes or bacticks), 

2.  a backslash-escaped `\W` character or 

3. a Pandoc inline code span,

and captures the whole into the named capture group "literal",
and into the named capture group
"codeblock", "escaped" or "code"
as the case may be.

This regex may be prepended to another which matches something else, 
so that you can first match code/escapes which you want to leave in place,
or something else which you want to modify.

There are admittedly some edge cases: 
 
1. An inline code span starting with three or more backticks 
and with line breaks inside where the first line looks like
the start of a code block will be misidentified as a code block, 
but such things will surely be very rare.

2. Since a code block may be the first thing in a list item there
is no check that the start of a code block is the only thing on a line, 
but for the end of a code block there is such a check.

=end Explanation

=cut

use utf8;
use 5.010001; # so that nested named captures work!
use strict;
use warnings;


my $code_or_escape_re = qr{
  (?<literal>
    # backslash escape
    (?<escaped> \\ \W )
  | # code block
    (?<codeblock>
      (?<Codefence> 
        (?<Codefencechar> \~ ){3,}
      | (?<Codefencechar> \` ){3,}
      ) 
      \h* 
       (?<codeblock_attrs>(?&AttrOrClass) )? 
      \h* $
      # code block content
      .*? # non-greedy match
      # closing fence, as wide or wider
      # on its own line
      ^ \h* 
      \g{Codefence} 
      \g{Codefencechar}* 
      $
    )
  | # inline code
    (?<code>
      (?<Codedelim> \`+ )
      .+?
      \g{Codedelim}
      (?<code_attrs> (?&Attr) )?
    )
  ) # end of "literal" capture
  (?(DEFINE) # Attribute pattern definitions
    (?<Attr> # code attrs: possibly nested braces
      \{
        (?: 
          [^\{\}\\]+ # normal
        | \\ .       # escape
        | (?&Attr)   # recurse
        )++
      \}
    )
    (?<AttrOrClass> # code block attrs
      (?<div_attrs> (?&Attr) ) (?! \S )
    | 
      # valid class name, somewhat too loose
      [^_\W\d] [-\w]* \b (?! \S )
    ) 
  )
}msx; # multiline, dot matches all, spaceout mode

=for Explanation
  Now to match a div but skip code blocks:
  Unlike Pandoc itself this requires that nested
  divs have progressively shorter *or* longer fences

=cut

my $literal_or_div_re = qr{
    $code_or_escape_re
  | (?<div>
    (?<Divfence> \:{3,} )
    \h* (?&AttrOrClass)? \h* $
    (?<divbody> # somewhat imprecise
      .*?
    )
    ^ \h* \g{Divfence} \h* $
    )
}msx;

=for Explanation
  This function computes the replacement text
  of a regex match which captured a div as per the
  regex just above. The argument is a hash reference
  with those named captures which matched
  as copied from `%+`. As an example it normalizes
  the attributes of the div if these are just a class.

=cut

sub do_something_with_div {
  my($captures) = @_;
  if ( $captures->{div_attrs} !~ /\{/ ) {
    $captures->{div_attrs} = "{.$captures->{div_attrs}}";
  }
  # do something meaningful
  my $new_text;
  # ... assemble value of new text
  # return new text if defined or original div
  return $new_text // $captures->{div};
}

=for Explanation
  The hash `%+` contains the named captures.
  The keys are capture names and the values are the text
  captured by the first group of that name which matched.
  You want to copy it to a normal hash ASAP
  since it will be clobbered by the next successful regex match.
  `$capt{literal} // do_something(...)` evaluates to
  the text matched by the capture group "literal"
  *if* that group matched anything and thus has a defined value,
  or otherwise to the return value of the subroutine `do_something()`
  
=cut

sub match_and_modify_div {
  my($text) = @_; # unpack args
  # match regex and execute code for replacement
  $text =~ s{$literal_or_div_re}{
    my %capt = %+; # save a copy of named captures
    $+{literal} // do_something_with_div(\%capt)
  }egmsx;
  return $text;
}
````````

**Comment by alerque** [comment]
@bpj Thanks for a good case study on why it would be so much nicer if Pandoc (which we already depend on to do the heavy lifting in a canonical way) would just keep track of the source bytes internally. I started off this issue because I was tired of re-inventing the wheel and writing markdown parsers in RegEx. More case studies where more people have invented their own wheels can only make the case for getting this done upstream stronger!

**Comment by alerque** [comment]
@bpj Thanks for a good case study on why it would be so much nicer if Pandoc (which we already depend on to do the heavy lifting in a canonical way) would just keep track of the source bytes internally. I started off this issue because I was tired of re-inventing the wheel and writing markdown parsers in RegEx. More case studies where more people have invented their own wheels can only make the case for getting this done upstream stronger!

**Comment by jgm** [comment]
I'm working on a new commonmark-compliant parser which will also handles (most) pandoc extensions (jgm/commonmark-hs).  It tracks source location for everything, so once we slot this in it would be feasible to have a mode that adds source location info to the AST.  However, there's no really good "slot" for this information currently, since elements don't all accept attributes.  One could create spans around arbitrary inlines and put source location on them.  commonmark-hs also provides a way to create a separate source map that can be used for highlighting, etc.  (Currently this is demoed by the `--highlight` option, which highlights a markdown file.)

**Comment by jgm** [comment]
Closing as a dup. The other issue is general enough to cover all ways of storing source information (whether a source map or in the AST itself).
