### ISSUE TITLE
Pandoc YAML metadata string/number behavior changed in 2.7.2 vs 2.7.1

### ISSUE THREAD

**Issue by Ricq** [jgm/pandoc#5479]
As reported on the `pandoc-discuss` mailing list, I believe there is an issue in Pandoc 2.7.2's YAML parsing, which has changed since 2.7.1.

What I believe the issue comes down to is that I'm including a YAML variable which holds a color in HTML format (RRGGBB), which I set to `'000000'` for black. However, since 2.7.2 it parses as `0` instead of `000000`, which is not a valid color anylonger and produces the following error:
```
Error producing PDF.
! Undefined control sequence.
<argument> \@@scl

l.274 \color[HTML]{0}
```

I took care to place the 000000 in single quotes to make it a string in YAML, instead of a number. But in 2.7.2 it just breaks.

I'm using the (great) [Eisvogel template](https://github.com/Wandmalfarbe/pandoc-latex-template), from which I've included the template itself in the example. _Note: this is not my template and you should check the license and use it from the source if you want to do anything with it_.

I've stripped down the example as much as possible. I'm running with the following command:
```bash
pandoc --from markdown+yaml_metadata_block -o example.pdf --pdf-engine=xelatex --standalone --template eisvogel.tex example.yaml example.md
```

Note: I've attached the files with `.txt` extension, since Github won't allow me to upload otherwise. Remove the .txt before running.

[eisvogel.tex.txt](https://github.com/jgm/pandoc/files/3139545/eisvogel.tex.txt)
[example.md.txt](https://github.com/jgm/pandoc/files/3139546/example.md.txt)
[example.yaml.txt](https://github.com/jgm/pandoc/files/3139547/example.yaml.txt)

**Comment by Ricq** [comment]
Reference to the mailing list discussion: https://groups.google.com/forum/#!topic/pandoc-discuss/IX0AiTC6FgY

**Comment by tarleb** [comment]
It seems that this is not related to YAML parsing, the intermediate structure contains the correct value:

    % echo "---\ntitle: '000000'\n---" | docker run --rm -i pandoc/core:2.7.2 -t native -s
    Pandoc (Meta {unMeta = fromList [("title",MetaInlines [Str "000000"])]})
    []

The problem seems to be caused by later steps. Weirdly enough, it works with some variables but not is mangled in others:

    % echo "---\ntitle: '000000'\n---" | docker run --rm -i pandoc/core:2.7.2 -t latex -s | grep title
     pdftitle={000000},
    \title{0}
    \maketitle

**Comment by tarleb** [comment]
I ran

    $ git bisect start 2.7.2 2.7.1 --
    $ git bisect run ./latex-title-test.sh

where `latex-title-test.sh` contains

    #!/bin/sh
    git lg -n1
    stack build
    printf -- "---\ntitle: '000000'\n---\n" | \
      stack exec pandoc -- --to=latex --standalone | \
      grep --quiet '\\title{000000}'

This leads to commit 2b0a0bba9c996d6eb3adde1a550383090d4d6569 as the one that introduced the problem. I didn't have time yet to debug this further.

**Comment by tarleb** [comment]
Not sure about the proper way of solving this, but a good work-around is to write your YAML like this:

``` yaml
---
# ...
titlepage-text-color: |
    000000
---
```

**Comment by jgm** [comment]
The underlying problem here is that we have MetaString but not MetaNumber in our metadata types.
So a number has to be represented internally as a MetaString.

This can cause problems in round-tripping with formats where metadata is represented in JSON, since JSON distinguishes strings and numbers.  What prompted this change is that in ipynb -> ipynb translations, JSON numbers like 5 in the ipynb metadata would change into JSON strings like `'5'`.  Commit 2b0a0bb fixes the problem by modifying the translation from MetaValue -> JSON.  If a MetaString is interpretable as a JSON number, then it is converted into a number rather than a string.

This fixes the round-trip problem noted above, but causes problems in your case, since you want `000000` to be interpreted as a string.

Note also that pandoc template rendering uses a JSON value as the "context" (supplying values for variables).  That's why `title` in your example turns into `0`.  (The `title-meta` variable used for `pdftitle` is special-cased, that's why it behaves differently.)

How to fix this?  Obviously, it is important to allow people to pass through strings like `000000`.  We could change the algorithm for recognizing MetaStrings as numbers, so that strings with leading 0s do not get treated as numbers.  It seems to me that this minimal fix might be enough for this particular case.

A more effective fix would be to introduce a numerical metadata field type, but that requires changes in pandoc-types.

**Comment by dhimmel** [comment]
> A more effective fix would be to introduce a numerical metadata field type, but that requires changes in pandoc-types.

This seems like a good idea. Metadata fields are one of the primary ways for passing configuration values to filters, and the inability to pass numeric metadata values to a filter causes some confusion. Since metadata is specified via a yaml metadata block, my initial assumption was that all YAML types would be supported.... although that may be ambitious because I know YAML can get funky.

**Comment by jgm** [comment]
@dhimmel you may want to open a new issue to request this
