### ISSUE TITLE
Reference links not disambiguated

### ISSUE THREAD

**Issue by alerque** [jgm/pandoc#5495]
It is possible to badly confuse the Markdown writer when combining `--reference-location=section` with  `--reference-links`. Without the per-section reference location option it will correctly disambiguate the links. However with the per-section references it will not notice when an identifier has been re-used. This MWE exhibits the problem:

```markdown
# One

All because of [1](#one) link...

# Two

[This](#one) will break Pandoc.
[This](#two) will make you laugh.
```

Note that the source document has an inline link on the text "1". Later when the text "This" is linked to two different things Pandoc will realize that it needs to make separate references for them, but it tries to do this by numbering the — starting at 1.

```sh
$ pandoc --wrap=preserve --atx-headers --reference-location=section --reference-links -t markdown
# One

All because of [1] link...

  [1]: #one

# Two

[This] will break Pandoc.
[This][1] will make you laugh.

  [This]: #one
  [1]: #two
```

If you consider that output normalized and try to process it again for some reason even Pandoc will complain about the duplicate key (`... | pandoc`):

> [WARNING] Duplicate link reference '[1]' at line 13 column 1

**Comment by jkr** [comment]
Looks like we have to add another state field (ie `stDocumentRefs`) that keeps all previously used refs and doesn't empty them like `notesAndRefs` does. I think I wrote the `reference-location` code, so I could try to do this.

**Comment by jkr** [comment]
Actually, what would be the correct output for this? Both of the two are possible, and they mean the same thing. The first is a bit more streamlined, but the second allows each section to have a more self-contained meaning. I'd probably vote for the second:

~~~markdown
One
===

All because of [1] link...

  [1]: #one

Two
===

[This][1] will break Pandoc. [This] will make you laugh.

  [This]: #two
~~~

or 

~~~markdown
One
===

All because of [1] link...

  [1]: #one

Two
===

[This] will break Pandoc. [This][2] will make you laugh.

  [This]: #one
  [2]: #two
~~~

**Comment by alerque** [comment]
I would vote for option two as well on the basis that the result is easier to split up into separate files (whether copy/pasting or some automated method) without breaking the references.

**Comment by jkr** [comment]
Actually, there is a bigger problem, that doesn't have anything to do with `reference-location`. Consider:

~~~markdown
All because of [1](#one) link...

[This](#foo) will break Pandoc.

[This](#bar) will make you laugh.
~~~

with `--reference-links`, we get:

~~~markdown
All because of [1] link...

[This] will break Pandoc.

[This][1] will make you laugh.

  [1]: #one
  [This]: #foo
  [1]: #bar
~~~

So the real issue is a need to update the index if the link is an integer. Easiest implementation would be to just push `stLastIdx` up to it. I'll give that a try.

**Comment by jkr** [comment]
@jgm: could you take a quick look at this? It fixes the issue and passes the tests, but since I'm not that familiar with the writer, I wanted to run it by you.

https://github.com/jkr/pandoc/commit/245ed45a

Also, where is the canonical place for markdown writer tests?

**Comment by jgm** [comment]
This looks good to me.
For tests, either add something to `test/Test/Writers/Markdown.hs` or add a command test in `test/command`.
