### ISSUE TITLE
org reader ignores -resource-path in #+INCLUDE: directives

### ISSUE THREAD

**Issue by hrehfeld** [jgm/pandoc#5501]
CWD is used instead.

Minimal Example:

src/includer.org:

```
this file includes something:
#+INCLUDE: "./included.org"
```

src/included.org:

```
this file was included
```

Reproduce:
```
$ ls
included.org  includer.org
$ pandoc  --resource-path . -t markdown includer.org   
this file includes something:
this file was included
$ pandoc  --resource-path /tmp -t markdown includer.org
this file includes something:
this file was included
$ cd ..
$ ls
src/
$ pandoc  --resource-path src -t markdown src/includer.org
[WARNING] Could not load include file './included.org' at line 3 column 1
this file includes something:
$
```

```
$ pandoc --version
pandoc 2.7.2
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
Default user data directory: /home/hrehfeld/.local/share/applications/pandoc or /home/hrehfeld/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

$ pacman -Qi pandoc
Name            : pandoc
Version         : 2.7.2-25
Description     : Conversion between markup formats
Architecture    : x86_64
URL             : https://pandoc.org
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : ghc-libs  haskell-http  haskell-juicypixels  haskell-sha  haskell-aeson  haskell-aeson-pretty  haskell-attoparsec  haskell-base-compat  haskell-base64-bytestring
                  haskell-blaze-html  haskell-blaze-markup  haskell-case-insensitive  haskell-cmark-gfm  haskell-data-default  haskell-doctemplates  haskell-exceptions  haskell-glob
                  haskell-haddock-library  haskell-ipynb  haskell-skylighting  haskell-hslua  haskell-hslua-module-text  haskell-http-client  haskell-syb  haskell-hsyaml
                  haskell-http-client-tls  haskell-http-types  haskell-safe  haskell-split  haskell-texmath  haskell-network  haskell-pandoc-types  haskell-random  haskell-scientific
                  haskell-tagsoup  haskell-temporary  haskell-network-uri  haskell-unicode-transforms  haskell-unordered-containers  haskell-zip-archive  haskell-vector  haskell-xml
                  haskell-zlib
Optional Deps   : pandoc-citeproc: for citation rendering with pandoc-citeproc filter
                  pandoc-crossref: for numbering figures, equations, tables and cross-references to them with pandoc-crossref filter
                  texlive-core: for pdf output [installed]
Required By     : None
Optional For    : None
Conflicts With  : haskell-pandoc
Replaces        : haskell-pandoc
Installed Size  : 42.29 MiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Wed 08 May 2019 05:04:52 PM CEST
Install Date    : Wed 08 May 2019 09:49:43 PM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by tarleb** [comment]
The roff reader does use `resource-path` when looking for include files, but neither LaTeX nor rst seem to do this. It seems like very reasonable behavior, and implementing this would be a two line change (at least for org). Should we also add this for the other readers which can include files?

We should probably update the manual if we choose to implement this:

> `--resource-path` only has an effect if (a) the output  format  embeds  images (for  example,
>  docx,  pdf, or html with `--self-contained`) or (b) it is used together with `--extract-media`.

**Comment by hrehfeld** [comment]
(FYI from the cmdline & manual I was under the impression that *all* externally loaded resources use resourcepath -- but your quote sounds like I misread.)

I would strongly argue for implementing respath behavior for all resources.
- it's more consistent with orgmode behavior, which includes relative to the file, not the cwd
- if pandoc is used as a library, the resourcepath is the tool of choice - I specifically want to avoid messing with cwd here
- with resourcepath, you can have both local includes and includes from template directories, which is quite useful
- I see no reason to have a separate path for "non-media"-files

**Comment by jgm** [comment]
One key question here is how the original format works.  In the case of LaTeX, pandoc gets the directories to search from TEXINPUTS, imitating LaTeX itself.  That seems a reasonable approach.  We could, I suppose, add TEXINPUTS to the resource path, allowing users to search paths not in TEXINPUTS, but this could be confusing since it would mean pandoc might select a different file than tex...

In the case of org, how does Emacs work?  What directories are searched for the include file?

**Comment by hrehfeld** [comment]
`org-mode` seems to use `default-directory` (emacs' equivalent of CWD), which is initialized to the parent dir of the current document (but can be changed). I would need to check the code to see if any other paths are used -- documentation doesn't mention include paths at all https://orgmode.org/manual/Include-files.html

**Comment by jgm** [comment]
So, if org-mode uses the working directory, why would we want pandoc to behave differently?  Wouldn't that be confusing?

**Comment by hrehfeld** [comment]
(I'm pretty sure, Default-directory is automatically set to the parent dir of file on open.)

With that reasoning, I think resource path should be ignored completely in the orgmode reader.

However I think this is a case where it makes sense to only have the default behavior follow orgmode, and add additional behavior options. Pandoc is used in some additional, different use cases.

**Comment by Delanii** [comment]
Hello, I would like to point this issue to a conversation in pandoc discuss group:

[Org-mode reader: Respect PATHs relative to "main" org file](https://groups.google.com/g/pandoc-discuss/c/ONeCQvMb4H8)

Does this issue mean that `--resource-path` is not implemented in pandoc in terms of using `#+INCLUDE` directives? I am getting same usage error as @hrehfeld in first post.

**Comment by jgm** [comment]
I think the difficulty here is that when you do
```
pandoc -f subdir/file.org
```
Emacs' `default-directory` (relative to which INCLUDEs are processed) would be `subdir` but pandoc interprets paths relative to the working directory.  We could try to work around this by enabling `--resource-path` for org input, but that seems a bit odd because that isn't how org itself works.

The best solution (but one that would break backwards compatibility and increase complexity) would be to change the types of pandoc's readers so that, instead of a `Text` as parameter, it takes something like `[(FilePath, Text)]` (a list of filename, text pairs).  That would allow the parsers to be given information about which file a particular INCLUDE directive occurs in, and then we could mimic Emacs' behavior.  Pinging @tarleb on this; it would be a big change but probably a useful one.

Second thought: to preserve backwards compatibility, we could use a typeclass, making the reader types like this:
```
readOrg :: (PandocMonad m, PandocInput t) => ReaderOptions -> t -> m Pandoc
```
and then define instances of `PandocInput` for both `Text` and `[(FilePath, Text)]`.  (We could even contemplate allowing things like `Handle` and `ByteString` and `String`...though this might break some code that relies on `OverloadedStrings` extension.)
