### ISSUE TITLE
support both caption and long description for picture

### ISSUE THREAD

**Issue by annProg** [jgm/pandoc#5544]
Hi
I want to add both caption and description for figure. Can pandoc achieve this function?

```latex
\documentclass[11pt,a4paper,english]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage[font=small,labelfont=bf,margin=\parindent,tableposition=top]{caption}
\usepackage{blindtext}
 
\begin{document}
   \blindtext
 
   \begin{figure}[!ht]
     \centering
     \caption{Dummy figure}\label{fig:dummy}
     \rule{0.75\textwidth}{0.5\textwidth}
     \caption*{\blindtext}
   \end{figure}
 
   \blindtext
\end{document}
```

![image](https://user-images.githubusercontent.com/4145852/58797504-c1d59e80-8632-11e9-9cf2-37e767d4128e.png)

**Comment by mb21** [comment]
No, however if you're using markdown as input, you can use [raw LaTeX](https://pandoc.org/MANUAL.html#generic-raw-attribute)...

    ```{=latex}
    \begin{figure}[!ht]
    ...
    ```

Yet it seems you're using latex as input? Then why not use `pdflatex` directly, instead of pandoc.

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by annProg** [comment]
I am using markdown as input.  latex and epub(html) as output. So, raw tex is not a good idea.

**Comment by tarleb** [comment]
You could write a Lua filter to produce output for both of these cases. See the [short caption filter](https://github.com/pandoc/lua-filters/blob/master/short-captions/short-captions.lua) for a good starting point.

**Comment by annProg** [comment]
@tarleb thanks! I will try lua filter
