### ISSUE TITLE
Handle rtl annotation in docx reader

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5545]
The structure
```
<w:r>
  <w:rPr>
    <w:rtl/>
  </w:Pr>
  <w:t>the Persian text</w:t>
</w:r>
```
should be parsed as
```
Span ("",[],[("dir","rtl")]) [Str "the",Space,Str "Persian",Space,Str "text"]
```

**Comment by jgm** [comment]
See https://groups.google.com/d/msgid/pandoc-discuss/751ea7a9-4e63-40ba-8afb-214b44d27207%40googlegroups.com

**Comment by nima87** [comment]
First I really don't understand Span or how to use it, not that I don't want to make effort at understanding, I don't know where to start.
Then I don't know if it makes any difference or not, but my text is mainly Persian and Pandoc has no problem in converting it to Rst or md or tex. I wanted to make my work easier by removing the task of adding `\lr{}`_[left to right]_ before Latin word(s).
Then it is not only two words. It can be one letter, one word or more words, for example 15 words. For instances with longer set of Latin words I will put then in a _Latin_ environment.
Thank you.

**Comment by mb21** [comment]
@nima87 We'll have to fix pandoc to read the rtl annotations form docx files. That's what this issue is about.

Meanwhile, if you're converting from markdown, see https://pandoc.org/MANUAL.html#language-variables and ask on pandoc-discuss if you have questions.

**Comment by nima87** [comment]
Correct me if I'm wrong. I said in my comment:
> Then I don't know if it makes any difference or not, but my text is mainly Persian and Pandoc has no problem in converting it to Rst or md or tex. I wanted to make my work easier by removing the task of adding \lr{}[left to right] before Latin word(s).

Now that I extracted a docx file I found out that the default direction of a file in MS Word is LTR, in fact no direction is marked, and only RTL words are marked with xml tags in the document. No matter that one thinks one's document is mainly Persian. it is the Persian words, sentences or Paragraphs that are marked in a docx file. So your insistence on saying that Pandoc needs a fix to **read RTL annotations**. Yet, I don't understand why Pandoc _needs a fix_ on that? 
Cause I encountered no issue in converting my file to md and Latex. Only the Xepersian package needs LTR words or sentences to be included in \lr{...} for smaller chunks and \begin{LTR}...\end{LTR}, Now would you please tell what is the purpose of Pandoc reading rtl annotations from docx files?

**Comment by mb21** [comment]
Should be fixed in the [pandoc nightly builds](https://github.com/pandoc-extras/pandoc-nightly)...

**Comment by nima87** [comment]
@mb21 Yeah you said in your previous answer that you _have to_ and then in this one you said _should_ without any Subject for the sentence. I really can't understand how moving from _have_ to subjectless _should_ answers my question? My question was why does Pandoc needs a fix because I didn't face any problem in converting my files*.

**Comment by mb21** [comment]
I'm sorry, I don't really understand.

> I didn't face any problem in converting my files

then all the better!

**Comment by nima87** [comment]
Let me go into details of a simple example.
Suppose you have a RTL sentence then some where in the middle you have a name of a book which is 5 words.

> نام این کتاب
> Using open-source for every task
> است.
> 

[It means ***The title of the book Using open-source for every task is*** (words for words translation)]
So when Latex(`xepersian` pkg) compiles this sentence it prints from right to left _using_ and _so on_ in the end you'll see this sentence: _task every for open-source Using_
But if you write \lr{Using open-source for every task} it will be rendered correctly.
I wanted to see if it is possible to give instructions to Pandoc to add `\lr{` before **Using open-source for every task** and `}` at the end.
I could manage to do this semi-automatically with emacs `query-serach-regexp`.
I put the result of the pandoc conversion of the docx file I uploaded to google groups.
`pandoc -s fmpandoc.docx --wrap=none -t markdown -o fmpandoc.md`

> نعنا
> ====
> 
> نعنا یا نعناع (نام علمی Mentha) است از رده دو لپه ای های پیوسته گلبرگ که سردسته تیره نعناعیان و از سبزی های خوراکی است. این گیاه تمام اسانس‌ها و خواص پونه را دارد؛ ولی برگ‌هایش کرک کم‌تری دارند و بریدگی‌های کنار برگ‌های آن بیش‌تر از پونه و اسانس آن نیز ملایم‌تر است.
> 
> نعنا[^1] ( (1981). The Wild Flower Key. Frederick Warne & Co. p. 310.) گیاهی است علفی با ریشه هوایی و ساقه‌های مستقیم و چهارگوش و زیرزمینی. ساقه و برگ‌های خوش‌بوی آن خوراکی و دارویی است و گاهی گل‌های رنگین دارد.
> 
> برگ‌های آن به طول ۳ تا ۵ سانتی‌متر، متقابل، نیزه‌ای یا دوکی است، حاشیهٔ آن دارای بریدگی‌های عمیقی است، بریدگی‌های کناره آن نوک تیز است. کرک برگ‌های نعنا کم است. نعنا سبز معمولاً در سرتاسر جهان کشت می‌شود، این گیاه حاصل تبدیل و ماندگاری بوته گیاه ریحان چند ساله می‌باشد. این گیاه در نواحی شمال ایران و اطراف تهران به حالت وحشی و پرورشی می‌روید.
> 
> *پونه Mentha pulegium*
> 
> [^1]: Mint
> 
This is almost perfect. I want a simple txt file with italic, bold, footnote. That's why I insisted to know what was the purpose of pandoc reading rtl annotations, because it has no issue. So would you please tell me what you had in mind when you said _Pandoc have to be fixed_?
Best.

**Comment by jgm** [comment]
>  I ask why did you feel that Pandoc needed a fix?

Quoting from your original pandoc-discuss message:

> Now I want to convert this file markdown and after that convert the md file to TeX. Rendering Latin characters in Persian document style requires putting the Latin characters as the argument of \lr{...} command.

That suggested to me that what you wanted was for pandoc to distinguish the LTR and RTL parts of the document.  I noticed that this information was encoded in the docx but pandoc was not doing anything with it.  So we fixed that.

Evidently that was not the issue you were concerned with, and there are other problems with the conversion.  So, open a new issue for the problem.  Describe it very precisely, and give us *everything* we need to reproduce the issue, including a sample docx file.

No sense commenting further on this (closed) issue.
