### ISSUE TITLE
Option to escape raw HTML on rendering

### ISSUE THREAD

**Issue by Twey** [jgm/pandoc#556]
It seems to me that it would be very useful e.g. for Web applications if there were a way to treat raw HTML as plain text and not HTML (i.e. escape [not remove] it somewhere along the pipeline).  For example, currently the following:

> writeHtml defaultWriterOptions $ readMarkdown defaultParserState "<script>alert('All up in your XSS')</script>"

will result in HTML equivalent to <script>alert('All up in your XSS')</script> where it would be very useful to be able to tell it to produce &lt;script>alert('All up in your XSS')&lt;/script>.  I initially thought that this is the purpose of the stateParseRaw option, but that doesn't seem to be the case.

**Comment by ncfavier** [comment]
Any reason this doesn't work with Commonmark?

```
~ $ pandoc -f markdown-raw_html -t html <<< 'hello <script>world</script>'
<p>hello &lt;script&gt;world&lt;/script&gt;</p>
~ $ pandoc -f commonmark-raw_html -t html <<< 'hello <script>world</script>'
<p>hello <script>world</script></p>
```

**Comment by jgm** [comment]
Because raw HTML parsing is a core feature of commonmark, it can't easily be disabled in the parser with an extension.  In principle we could do it, though, by avoiding the use of `defaultSyntaxSpec` and instead building this up ourselves, omitting the raw HTML parsers if `raw_html` isn't set. This is probably worth doing, though it might create problems down the road if there are changes to `defaultSyntaxSpec` in commonmark-hs.

For now, a good workaround would be to use a filter to remove all the raw HTML bits, or alternatively convert them to regular textual content.

**Comment by jgm** [comment]
I'll make a new issue for this.
