### ISSUE TITLE
plain_color output format

### ISSUE THREAD

**Issue by eadmaster** [jgm/pandoc#5580]
is it possible to make pandoc output colorized text on the terminal (with ascii escape sequences) when invoked like this:
````
pandoc -t plain ../app/src/core/tests.py
````

**Comment by mb21** [comment]
This would require a writer that outputs to terminal colors, which pandoc does not have. And you want that for syntax highlighting? Pretty sure that's out-of scope for pandoc. But see e.g. https://unix.stackexchange.com/questions/267361/syntax-highlighting-in-the-terminal

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by jgm** [comment]
Note:  pandoc uses the `skylighting` library (jgm/skylighting) for syntax highlighting.  And this library does export a formatter for ANSI color codes (Skylighting.Format.ANSI).

So if you just want colored syntax highlighting for to the terminal, the `skylighting` executable will produce that by default.  You can install this using `stack install skylighting --flag skylighting:executable`.  Then just do

```
skylighting ../app/src/core/test.py
```
