### ISSUE TITLE
`--to beamer` should use LaTeX template file

### ISSUE THREAD

**Issue by Wandmalfarbe** [jgm/pandoc#5585]
When using `--template name`, pandoc automatically picks the right template depending on the output format.

- `--template default --to html5` uses `default.html5`
- `--template default --to man` uses `default.man`

Since the default LaTeX and beamer template are merged into one file I would expect that - `--template default --to beamer` uses the template `name.latex`.

But the command

```sh
pandoc --from markdown --template default --to beamer document.md
```

fails with an error:

```sh
Could not find data file templates/default.beamer
```

**Comment by jgm** [comment]
I think it's probably best to keep current behavior, which is consistent with what the manual says.
Changing would be a breaking change, and some people might have templates they use just with beamer.  It's not that hard to say `default.latex` in this case. Or, if you have a custom beamer/latex template, `custom.latex`, you can symlink it to `custom.beamer`, so that it will work with either.
