### ISSUE TITLE
Powerpoint writer - footer, slide numbers, date

### ISSUE THREAD

**Issue by Grandement** [jgm/pandoc#5660]
Hi,

When I use the date keyword the date is displayed only on the title page. But not on other slides. Can we implement something to enable it? Or enable the date, footer or slide numbers in general?

E.g. the date is applied to the title slide but in my reference pptx it is set to "do not show on title slide". It is set in the final pptx as well but displayed on the title page and not on the others.

![image](https://user-images.githubusercontent.com/12670931/61852304-76fd3800-aeb9-11e9-9b79-74667625bb17.png)

**Comment by agusmba** [comment]
This is a tough one.

On the one side I see the benefits of getting a pptx ready to go, but on the other hand I'd also like the pptx to be easily editable in PowerPoint (thus I'd be against hardcoding footer values in the pptx that do not follow standard PowerPoint behavior).

Due to the lack of variable (document property) substitution in PowerPoint (unlike in Word), the templating part of headers/footers must be done via master slides, with sensible use of the Header/Footer option you showed above.

I'm not sure (I didn't implement this feature) but I feel it would be quite complex for pandoc to read and understand the master slides of your reference document so that it could mimic the use of said Header/Footer option.

Personally I just use that option manually from PowerPoint after pandoc generates the pptx, although it can be a pain to always relay on this manual step.

Maybe there could be a way of making pandoc *activate* the Header/Footer option so that when the pptx opens it is populated (like the content index in docx), but I have no idea if this is feasible or not.

**Comment by serussell** [comment]
@agusmba -- can you link to the documentation about how to do document property variable substitution, based on (I assume) header variables in the source document?  I've been wanting to do this, to get things like the subtitle into a docx footer in the template.

**Comment by agusmba** [comment]
Can't remember if there's a detailed guide on this, but it's pretty easy.

Edit your docx reference doc and insert in your footer any DocumentProperty you want (subtitle in your case). If it doesn't exist, create it beforehand, the value doesn't matter, it will be substituted by the correct one by pandoc.

I can't write comfortably on my phone, if there's a need I could write a guide in a few weeks.

**Comment by serussell** [comment]
@agusmba , see, I tried that.  It removed the subtitle from the title page, so I decided that meant that only one replacement was made in the document.  Perhaps I did something wrong; `pandoc` supposed to replace *all* occurrances of styled keyword texts?  I'll try again.

**Comment by agusmba** [comment]
>  It removed the subtitle from the title page

Mmm, that's strange.

Bear in mind that DocProperty substitution will only work out of the box if they are in your header/footer (reference-doc), not in your document text.

**Comment by undergroundquizscene** [comment]
This has been fixed in https://github.com/jgm/pandoc/pull/7572 – footer content specified in the reference document is pulled through into the output presentation. Support includes slide numbers with an optional start number, automatic or fixed date, and static footer content, as well as the "don't show on title slide" option. If the date in the footer is a fixed date in the reference doc, it is replaced with the `date` metadata field, if that is specified.
