### ISSUE TITLE
Docbook-Asciidoc admonitions converted to blockquote

### ISSUE THREAD

**Issue by lopsotronic** [jgm/pandoc#5690]
pandoc -v: pandoc 2.7.3 Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1

CLI: pandoc -f docbook -t asciidoc -s DB.xml -o adoc.adoc

Where DB.xml is DocBook (tested both DocBook4 and 5)) and adoc.adoc is asciidoc.

Docbook admonition elements transformed into asciidoc blockquotes. Asciidoc supports docbook admonitions.

Input
```
<warning><para>This is a warning.</para></warning>
```
Output

```
____
*Warning*

This is a warning.
____

```
Expected output
```

[WARNING]
====
This is a warning.
====
```

**Comment by mb21** [comment]
This is something neither the docbook reader nor the asciidoc writer currently handle AFAIK. Mostly, because it's not clear how to represent this in pandoc's limited internal document AST. But I suppose, we could use a div with class `warning`. That's what the RST reader does to `warning` admonitions...

**Comment by jgm** [comment]
See PR #5593 for one way in which we might parse RST admonitions into something which preserves the semantics better...at the cost of a less satisfactory default rendering in most formats.
Still undecided about that one.

**Comment by mb21** [comment]
Ah yes, seems like #5593 does exactly that. I think I'm in favour of that (using a div with class="warning" instead of the blockquote).

- it preserves the information in the AST
- people could still write a filter to get the old behaviour back (or we could adjust some writers)
- not sure a blockquote is that much better a rendering of most admonitions in the first place (sure, it made sense before we had native divs...)

**Comment by jgm** [comment]
We'd also need to modify the asciidoc writer to respond to this structure.
