### ISSUE TITLE
Backslash and dots strange behavior in MD to MD

### ISSUE THREAD

**Issue by hoijui** [jgm/pandoc#5695]
pandoc 2.7.3

```bash
echo "..\\.." | pandoc -f markdown -t markdown
\....

echo "..\.." | pandoc -f markdown -t markdown
\....

echo "\\..\\..\\" | pandoc -f markdown -t markdown
\....\

echo "..\\..\\" | pandoc -f markdown -t markdown
\....\

echo "C:\\dir\\..\\file.txt" | pandoc -f markdown -t markdown
C:\dir..\file.txt

echo "C:\dir\..\file.txt" | pandoc -f markdown -t markdown
C:\dir..\file.txt
```

the backslashes:
* sometimes get removed
* sometimes "beam back"
* there is a single backslash output with both '\' and '\\'

**Comment by alerque** [comment]
The single backslash output is not Pandoc's fault, that is your testing methodology. Your shell is eating up the double backslashes as if it was an escaped character. Try it without the pipe first to see what is being passed on from your `echo`'s.

**Comment by hoijui** [comment]
... doh! :D
.. I "should" have known that :D
thanks.

**Comment by hoijui** [comment]
Still though, the problem did not much change (except the lat bullet point in my first message)

```bash
$ echo 'C:\\\\dir\\\\..\\\\file.txt' | pandoc -f markdown -t markdown
C:\\dir\\..\\file.txt

$ echo 'C:\\dir\\..\\file.txt' | pandoc -f markdown -t markdown
C:\dir..\file.txt
```

**Comment by alerque** [comment]
Your first two bullet points have something to do with the [`+smart` extension](https://pandoc.org/MANUAL.html#typography). You are thinking about them in terms of file paths, but the examples you give are being interpreted as a way to escape a series of literal periods (`...`) so they do no become an ellipses (`…`). Pandoc is normalizing the syntax so the escaped period is at the beginning rather than the middle of  the set.

**Comment by mb21** [comment]
You probably want to use a code block:

    `C:\dir..\file.txt`

**Comment by hoijui** [comment]
what I want is of course, a valid windows path with backslashes.
I still don't know how to do that (except in an inline code block).
I think it is especially unexpected within a link.

```
echo "C:\\hello\\world\\..\\file.txt" | pandoc -f markdown -t markdown
C:\hello\world..\file.txt

echo "`C:\\hello\\world\\..\\file.txt`" | pandoc -f markdown -t markdown
`C:\hello\world\..\file.txt`

echo "[windows link](..\\hello\\world\\..\\file.txt)" | pandoc -f markdown -t markdown
[windows link](..\hello\world..\file.txt)
```
so.. how would I make it work as I want in case 1 and 3 as well?
also, why does it remove the backslash in case of `\.` but not in case of `\d` and '\f'?

**Comment by alerque** [comment]
Additionally, the `+raw_tex` extension is on by default, so your `C:\\hello` is actually being interpreted as if `\hello{}` was a TeX command. You can see how Pandoc is interpreting your input better by looking at it's native output:

```sh
$ echo -E "c:\\foo\\..\\bar" | tee /dev/stderr | pandoc -f markdown -t native
c:\foo\..\bar
[Para [Str "c:",RawInline (Format "tex") "\\foo",Str "..",RawInline (Format "tex") "\\bar"]]
```

**Comment by alerque** [comment]
You should read the manual on [Backslash Escapes](https://pandoc.org/MANUAL.html#backslash-escapes). I'm guessing turning on the `+all_symbols_escapable` and turning off `-raw_tex` and `-smart` will give you results more like what you expect where you can round-trip escaped slashes:

```sh
$ echo -E "c:\\\\foo\\\\..\\\\bar" | tee /dev/stderr | pandoc -f markdown-raw_tex-smart-raw_sile-escaped_line_breaks+all_symbols_escapable -t markdown
c:\\foo\\..\\bar
c:\\foo\\..\\bar
```

**Comment by hoijui** [comment]
ouh boy! :D
thanks @alerque !
now I realized, that my confusion came form not knowing that latex commands are on by default (I only knew for HTML). that is why one has to escape backslashes... thanks!

**Comment by hoijui** [comment]
It does not work in link targets:
```bash
$ echo -E "c:\\\\foo\\\\..\\\\bar [l-name](c:\\\\foo\\\\..\\\\bar)" | tee /dev/stderr | pandoc -f markdown-raw_tex-smart+all_symbols_escapable -t markdown
c:\\foo\\..\\bar [l-name](c:\\foo\\..\\bar)
c:\\foo\\..\\bar [l-name](c:\foo\..\bar)
```
which means that repeated filtering with pandoc leads to undesired results again:

```bash
$ echo -E "[l-name](c:\\\\foo\\\\..\\\\bar)" | tee /dev/stderr | pandoc -f markdown-raw_tex-smart+all_symbols_escapable -t markdown | pandoc -f markdown-raw_tex-smart+all_symbols_escapable -t markdown
[l-name](c:\\foo\\..\\bar)
[l-name](c:\foo..\bar)
```

but honestly, I just decided to not support/test for these windows paths, as I personally think they should not be used, and because windows supports slash instead of back-slash since a long time already anyway.
not worth the trouble. but thanks for your help! hope this helps someone in the future.

**Comment by alerque** [comment]
What the heck are you even trying to do? Backslashes are not valid in URLs in that way. Even browsers on Windows use forward slashes as a path segment separator. Also the URL scheme you are showing is invalid, to link to a local file you would need something like `[name](file:///C:/foo/bar)`.

If you have an example that is valid Markdown to begin with that is not getting handled properly I'm sure we'd be glad to address it, but I'm not seeing it yet. Your output is unexpected because your input is invalid to start with, and Pandoc is trying to understand it.

Please also use `plain` and `native` output formats to review how Pandoc understood your input before you use `markdown` as an output format. There are different issues involved in reading and writing Markdown, and you are jumbling them up in your tests.
