### ISSUE TITLE
Handle new pandoc-citeproc locator syntax with --biblatex option

### ISSUE THREAD

**Issue by seifferth** [jgm/pandoc#5722]
The new locator syntax introduced in pandoc-citeproc <https://github.com/jgm/pandoc-citeproc/pull/362> does not work with the `--biblatex` switch in pandoc 2.7.3 (full version below).

Input:

```
[@citekey{xii}]
```

output of `pandoc -t latex --biblatex`

```latex
\autocite[xii\}]{citekey}
```

expected output:

```latex
\autocite[xii]{citekey}
```

Full pandoc version information: pandoc 2.7.3, Compiled with pandoc-types 1.17.6, texmath 0.11.2.2, skylighting 0.8.2

**Comment by jgm** [comment]
The `{..}` locator syntax is part of pandoc-citeproc; pandoc itself just has the notion of a citation suffix, and all the parsing of this into locator + other stuff is done in pandoc-citeproc.  Since pandoc-citeproc doesn't get involved when you use `--biblatex`, the parsing isn't done.

We could move the code for doing this parsing to pandoc, and call it from pandoc-citeproc, I suppose.  But then we'd need code to combine a locator + suffix into a single suffix, for biblatex.  A simpler but probably adequate approach might be to remove the curly braces.

**Comment by seifferth** [comment]
I understand that the special locator syntax is specific to pandoc-citeproc. Yet ideally, one would be able to use the same source to get adequate results using either pandoc-citeproc or biblatex. I believe simply removing the curly braces is a reasonable approach, since biblatex has it's own heuristics for parsing locators anyway.
