### ISSUE TITLE
Paragraph Level Id

### ISSUE THREAD

**Issue by Y3cWxaL0Z95j** [jgm/pandoc#5748]
I am writing a series of html documents (memoirs, over 100 docs) with a lot of references to previous articles, and also to future articles via edit. I am using markdown and html.

What I want is **direct links to paragraphs**. One workaround is to filter each paragraph using 7 or more \#'s

    ####### Paragraph content.

This makes each paragraph a div and repeats its contents in the Id. It is not what I want. It should be something shorter.

At the moment I am using a random number for each paragraph.

    <p id="Id-35855" align="justify">
    Paragraph content.
    </p>

However all the Id's are changed each time the document is edited. What I am looking for is some kind of option to give each paragraph a somewhat unique and constant id. Maybe a pandoc option (--paragraph-id) or some kind of filter (but I have no idea of filters or even of what json means.)

### My Suggestion

1)  Generate an Id for a paragraph the same way the markdown "\#\#\#\#\#\#\# Paragraph content." makes it.

2)  Filter the id through md5sum. This converts 

    id="paragraph-content."
    to
    id="dea7e1a5671bf9422a9dff93976179a9"

3)  Add "Id-" to make it begin with a letter.

4)  Shorten the md5sum to five letters. (cut -c -5)

    id="dea7e1a5671bf9422a9dff93976179a9"
    to
    id="dea7e"
    to
    id="Id-dea7e"

5)  And the result is:

    <p id="Id-dea7e" align="justify">
    Paragraph content.
    </p>

**Comment by jgm** [comment]
You could do this using a lua filter.

**Comment by alerque** [comment]
Content-ID tagging in a way that is meaningfully useful is _HARD_. Breaking links because a paragraph before it got inserted, or the target paragraph got a punctuation fix, or something got reordered is not ideal. There are systems to deal with this, but you should probably apply them in an automatic post-processing step to your markup. Just keep your Markdown as-is and let something else tag it with markers based on fragments of the content.

**Comment by jgm** [comment]
If you want stable links, the best bet is to insert something explicitly into your markdown source.
You can already do that using e.g. a div:
```
::: #coolpara
This is a paragraph I want to refer
to using the id `coolpara`.
:::
```

**Comment by mb21** [comment]
Currently, we don't have attributes on paragraphs... this is tracked in an existing issue though, thus closing.

But as mentioned, there may be better solutions for your specific case anyway.  For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
