### ISSUE TITLE
Feature request: allow left-aligned display math in HTML output (with Katex)

### ISSUE THREAD

**Issue by kzvi** [jgm/pandoc#5815]
If Pandoc is invoked with `--metadata=classoption:fleqn` then it will left-align display equations in latex output. I would like to propose that this feature be extended to HTML output, in particular if the `--katex` option is used because Katex has an [option](https://katex.org/docs/options.html) for it.

I think that what it would take to implement this feature is changing [this string](https://github.com/jgm/pandoc/blob/3351dcfc45cf2053ae6cb6fb811d88cb6ebbc969/src/Text/Pandoc/Writers/HTML.hs#L285) depending on the document's metadata. (I'm not the best at Haskell though so I'm not sure how that would work :S)

This would be useful because it would allow for left-aligned display equations in HTML output. Currently I don't think there is any way to have Pandoc pass the `fleqn` option to Katex.

**Comment by jgm** [comment]
What would need to be changed, exactly, in the HTML output with katex for this option to be enabled?  Is it just a change in the katex URL, and if so what specifically?

**Comment by mb21** [comment]
I think @kzvi is right, we could change the line linked to:

    H.script
     "document.addEventListener(\"DOMContentLoaded\", function () {\n  var mathElements = document.getElementsByClassName(\"math\");\n  for (var i = 0; i < mathElements.length; i++) {\n    var texText = mathElements[i].firstChild;\n    if (mathElements[i].tagName == \"SPAN\") { katex.render(texText.data, mathElements[i], { displayMode: mathElements[i].classList.contains(\"display\"), throwOnError: false," <> katexOpts <> "} );\n  }}});"

where `katexOpts` would have to be a JSON serialized string. Do we have a function somewhere `lookupMetaJsonString :: Meta -> String` or similar? (Not the usual `encode` that generates the verbose JSON for filters, which wouldn't work here.)

Then the user could use something like the following YAML metadata:

```
---
katex:
  fleqn: true
  minRuleThickness: 0.06
---
```

Otherwise we'd have to hardcode all the katex options...

**Comment by jgm** [comment]
Actually instead of Meta you probably want Context, which is neutral between things set as variables and as metadata.  Context has a ToJSON instance that would give you a JSON string.  But it's not going to be what you want, probably, because the Context type just has string values, so booleans and numbers would come out as strings.

For now I'd be more tempted to check the context for `fleqn` and if it has a true value, just add that value.  Most of the other customizations don't look too relevant for us.
