### ISSUE TITLE
Can pandoc natively support the conversion of markdown and html to pdf? LaTeX is too big and too complicated.

### ISSUE THREAD

**Issue by linpengcheng** [jgm/pandoc#5832]
Can pandoc natively support the conversion of markdown and html to pdf? 
LaTeX is too big and too complicated.

**Comment by alerque** [comment]
Pandoc supports quite a number of PDF engines as backends besides LaTeX. This is [documented in the manual](https://pandoc.org/MANUAL.html#option--pdf-engine). At the end of the day PDF is a complicated format and needs lots of machinery to create, so you may or may not find something you like better in the alternatives list.

**Comment by jgm** [comment]
Questions should go to the pandoc-discuss mailing list, please -- this tracker is for bug reports.

**Comment by KurtPfeifle** [comment]
You don't necessarily need "big and complicated" LaTeX co-installed with Pandoc to let it create PDFs.

To get a list of supported PDF engines, type the following into a terminal CLI:

    pandoc --pdf-engine[space][tab]

This will spit out a list like the following:

    context latexmk lualatex pdflatex pdfroff prince tectonic weasyprint wkhtmltopdf xelatex

which gives you a hint what sort of third-party-software you'd need to co-install with Pandoc in order to produce PDFs...

**Comment by linpengcheng** [comment]
In the free tool, When I was using wkhtmltopdf, I found that it wasn't good enough for svg  display support, so I will try groff .

 I think it would be a little bit simpler and more common to convert html one-way into pdf, and it would be more complicated to convert pdf to html.
