### ISSUE TITLE
Add option to default files that sets the working or base directory

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5871]
The proposal is to add an option `working-directory` to default files, so that the working directory (or base directory relative to which pandoc interprets relative paths) gets changed for purposes of pandoc's processing.

A special value `%` could mean "the directory containing this defaults file."
Example:

my.yaml:
```
input-files:
- foo.md
- bar.md
output-file: book.pdf
toc: true
working-directory: %
```

If you now did `pandoc -d /projects/documents/my.yaml`, pandoc would convert `foo.md` and `bar.md` from `/projects/documents`, producing `book.pdf` in that directory, regardless of the current working directory.

This would be a way of implementing one of @brainchild0's suggestions from #5790

**Comment by brainchild0** [comment]
A few comments:

- The idea was earlier given, which I consider to be a good idea, that some set of variables might be made available for interpolation for the values of file names and other fields.  As such, use of a solitary percent symbol for a specific meaning offers a much lower level of extensibility than the use of an interpolation syntax that can refer to any variable in a namespace.
- Pursuant to the above, it seems appropriate to define interpolation syntax, and interpolated variables corresponding to the various file and directory paths relevant to the invocation.
- Nevertheless, I feel that that by default path names should be considered to be relative to the file that references them, unless otherwise indicated, as by a static path or preceding interpolated variable to indicate some path resolved dynamically.  Resources being resolved relative to where they are referred is a common pattern an ensures consistency and reliability with minimal reliance  on system-specific rules.  It is for, for comparison, a tenet of web design patterns that when a resource points to a second resource that further points to a third resource, the third resource is resolved relative to the second, not to the first. Otherwise use of the resources would lack desired consistency. Similarly a YAML file that refers to an external file would normally refer to the same external file regardless of where the application is running, the same sensibilities ought to inform the current question.
- Furthermore, overriding of standard behavior with respect to how files are resolved is ideally given per field, not globally, as a global effect makes it harder to ensure predictable results.

Following from the above, I suggest the following:

- Define a syntax for variable interpolation (e.g. `${varname}`).
- Define a variable set that includes values for the current working directory, and for the name and location of the current file, as well as some metadata values from the input.
- Resolve file names relative to the location where the are referred, in this case the location of the *defaults* file, while providing the possibility that the user can override this behavior  as such:
   ```
   output-file: ${cwd}/book.pdf
   ```

The above will not satisfy all possible cases.  A perfectly general solution requires that variables can be passed into the interpolated namespace from the command line.  Such support is not necessary to include initially, only to keep open as a possibility.  In fact, I would consider almost all use cases to be readily satisfied by making only the simple change related to the location from which relative paths are resolved.

**Comment by jgm** [comment]
We can't, in general, resolve references relative to the file containing them.  Why?  Because pandoc doesn't always have this information.  `pandoc foo.md bar.md` behaves more or less like `cat foo.md bim/bar.md | pandoc`. The markdown parser just gets a stream of characters and doesn't know in general what files supplied them; thus when it encounters a relative image reference (for example) it does not know whether it comes from `foo.md` or `bim/bar.md`.  For that reason pandoc has always interpreted everything relative to the working directory, though an alternative search path may be specified using `--resource-path`.

In the case of default files, we do know the path and therefore could resolve relative to the default file.  However, this would be inconsistent with how things work elsewhere, and it would also pose a problem for the main way many people will use this feature -- putting the default files in the user data directory.  You are right that one way to address the second point would be to provide a macro referring to the current working directory.  This doesn't help with the first point, though.

**Comment by brainchild0** [comment]
> We can't, in general, resolve references relative to the file containing them. Why? Because pandoc doesn't always have this information. `pandoc foo.md bar.md` behaves more or less like `cat foo.md bim/bar.md | pandoc`. The markdown parser just gets a stream of characters and doesn't know in general what files supplied them; thus when it encounters a relative image reference (for example) it does not know whether it comes from `foo.md` or `bim/bar.md`. For that reason pandoc has always interpreted everything relative to the working directory, though an alternative search path may be specified using `--resource-path`.

I tend not to understand why it would be proposed as necessary or even desirable that the resolution strategy for references within MarkDown inputs is the same as for those within *defaults* files.  


> In the case of default files, we do know the path and therefore could resolve relative to the default file. However, this would be inconsistent with how things work elsewhere, and it would also pose a problem for the main way many people will use this feature -- putting the default files in the user data directory. You are right that one way to address the second point would be to provide a macro referring to the current working directory. This doesn't help with the first point, though.

Certainly I never intended my comments to extend beyond the context of *defaults* files, which I thought was the subject of the discussion.

Is there some reason why we would need to adopt such a constraint?

**Comment by jgm** [comment]
Certainly it is possible for the paths in the defaults file to be resolved differently than paths elsewhere, and I'll think about this suggestion.  (Comments from others also welcome.)  I think that in general, consistency is good and when things behave differently in different contexts, it can cause confusion.  On your proposal for example one couldn't say, "using a default file that sets `output-file` is just like using the `--output-file` option on the command line, because the significance of relative paths wolud be different.

Also, if we adopted this suggestion we'd probably want a way to specify the working directory explicitly.  Yes, we could set up a system of macros or a templating system within the default files.  But this does open a large can of worms.  Is variable interpolation going to be allowed everywhere?  That will require special escaping in some cases in header-includes and the like.  And it's more complexity, which is always a net loss.

Maybe we wouldn't need it, though.  Maybe there just aren't cases where you'd want to specify paths relative to the working directory, when the defaults file is somewhere else (like the user data directory).

**Comment by brainchild0** [comment]
> consistency is good and when things behave differently in different contexts, it can cause confusion. 

What are the other contexts?  If you are talking about resolving image files referred by a MarkDown document, then the contexts are so dissimilar in appearance and relevance that I doubt substantial confusion will result.  Within a source document it is natural to refer to a resource by its identity, whereas the strategy for finding the resource is determined elsewhere.  It seems like a close analogy to a C file where the header files are referred by name yet the directories to be searched, at least in traditional tool like GNU CC, are passed through the command line. 

> On your proposal for example one couldn't say, "using a default file that sets `output-file` is just like using the `--output-file` option on the command line," because the significance of relative paths would be different.

Isn't that a good thing?  When you give a relative reference, your current location matters, and should be the basis of resolving the reference.  If you are on the command line, your references are relative to the working directory.  If you are in a file, your references are relative to the location of the file.  By close analogy in daily life if you are sitting in a room with someone else and mention a picture on a shelf, you are assumed to be referring to a shelf in that room except when indicated otherwise.




> Also, if we adopted this suggestion we'd probably want a way to specify the working directory explicitly. Yes, we could set up a system of macros or a templating system within the default files. But this does open a large can of worms. 

Yes it can.  But good options are available for starting simply but extensibly, so that the features grow   only as feasible and required.


> Is variable interpolation going to be allowed everywhere? 

Can't think of a single reason why it should be.

> That will require special escaping

Yes simple escaping, simpler than on the shell.  Probably like GMake where `$` marks a macro and `$$` resolves to `$`.

> in some cases in header-includes and the like. 

I'm not sure why LaTeX code would need to interpolated the same way file reference fields need it.

> And it's more complexity, which is always a net loss.

Yes, but macros can be very very simple, and external dependencies can add higher functionality if needed without much design effort.  Might not be needed though.


> Maybe we wouldn't need it, though. Maybe there just aren't cases where you'd want to specify paths relative to the working directory, when the defaults file is somewhere else (like the user data directory).

Maybe, but seems like a very special case to look for a file of a particular name in whatever happens to be the CWD.  More common that a file  resolved dynamically is simply passed on the command line.

Effectively, you can consider two cases.  1) A file is referred, by it by relative path, within  a _defaults_ file, and  2) a file is not referred by a _defaults_ file but rather on the command line, by a path relative to the CWD or an absolute path.  The intermediary case of the name being in the _defaults_ file but the location being determined by the CWD strikes me as hypothetical and practically without usefulness.

**Comment by jgm** [comment]
When you say that relative filenames in the defaults file are resolved relative to the directory containing the defaults file, what counts as a filename?  Is your idea that certain fields are going to be designated as working this way?  (input-files, output-file, css, include-in-header, etc.?)  (If someone has a custom variable that happens to be a filename, then, it *won't* be treated this way.  That's a potential point of confusion.)
 
Similarly, if the variable interpretation feature or a special CWD macro isn't allowed everywhere in the defaults file, where exactly is it allowed?

Both questions could be answered by identifying a subset of defaults fields that take filename arguments, but we'd have to be very clear in documentation that these fields have these special features.

**Comment by brainchild0** [comment]
>  (If someone has a custom variable that happens to be a filename, then, it _won't_ be treated this way. That's a potential point of confusion.)

Hadn't considered it, but a field that is a custom variable is not one that Pandoc processes as a file, so Pandoc never looks for a file by that name.  Isn't the distinction clear and binary between what is file name that Pandoc uses to find a file,   and what is not?


> Similarly, if the variable interpretation feature or a special CWD macro isn't allowed everywhere in the defaults file, where exactly is it allowed?

Well, it could be allowed everywhere, I suppose, but the question would be whether its usefulness is more expansive than file names.  There could be a case for this, but even so, I doubt everywhere is a good idea.  I think for example that the value of `header-includes` should not be interpolated in this way.  I have thought in the past that `header-includes` might benefit from allowing template features, but I think for a block of LaTeX code any template features would be likely to be useful only if following a more sophisticated scheme that includes conditionals and loops.  These enhancements would need to be considered separately, if at all.

> 
> Both questions could be answered by identifying a subset of defaults fields that take filename arguments, 

I would offer three choices:

1.  Only fields that reference files.
1.  Some more general selection of fields containing simple values.
1.  Only  input and output fields.  For other files, the existing *resource path* mechanism may be adequate.  The directory of the *defaults* file might be implicitly appended, and any other needed inclusions can be given explicitly in `resource-path` field.

> but we'd have to be very clear in documentation that these fields have these special features.

Yes, but many fields cannot meaningfully include the characters used in  template escapes anyway, so those fields can in principle use the feature experimentally as to be  hidden from the larger user base.

**Comment by brainchild0** [comment]
> For example, most resource-paths are going to include `.`, and if this gets construed as the user data directory rather than the current working directory, that is probably not going to be very useful.

Does *resource path* have a default currently?  Maybe the best solution is just to  append  implicitly  both locations to the value.  As it is a search path not a single file location, there is more flexibility with respect to handing it.

**Comment by jgm** [comment]
`extract-media` has no default; the default is not to extract media.  But anyway, the issue is this: someone might want to set up a default (using a "defaults" file) so that media are always extracted to the `media` subdirectory of the working directory, for example.  So that is one case in which a file path argument should probably not be interpreted relative to the directory containing the defaults file.

`resource-path` defaults to the working directory, so it's not problem if you don't want to change it.  But when you specify it explicitly, all components must be included, including the working directory (if you want it to be searched -- in some cases you don't).  So this is another case where people may want their path names in a default file to be interpreted relative to the working directory.

In both cases, having something that expands to the working directory might be an acceptable solution.  You'd have to write
```
resource-path: '${CWD}:.'
extract-media: '${CWD}/media'
```
to put both the working directory and the directory containing the defaults file into the resource path, and to extract media to the `media` subdirectory of the working directory.

Still, it might be confusing to some users that setting `extract-media: ./media` in the defaults file doesn't have the same effect as specifying `--extract-media=./media` on the command line.

**Comment by brainchild0** [comment]
> But when you specify it explicitly, all components must be included, including the working directory (if you want it to be searched -- in some cases you don't).

This rule can be revised though when considering the logic to handle the *defaults* file.  We are free to elect that particular locations are appended automatically.



> Still, it might be confusing to some users that setting `extract-media: ./media` in the defaults file doesn't have the same effect as specifying `--extract-media=./media` on the command line.

I don't feel the same.  I am still struggling to get into the mindset that someone thinks that path names given in a file are relative to something outside that file.  Practically, the only common case where I see this pattern is in scripts, which of course operate as programs and are not descriptive data files.  If the user wants to run Pandoc such that media is extracted to the CWD, wouldn't the obvious inclination be to include `--extract-media=.` on the CLI?

**Comment by jgm** [comment]
Seems like you'd get 100% of what you want with a simple wrapper around pandoc that changes directory before running pandoc with the defaults file.  I'm reluctant to add too much extra complexity and possibly break other workflows just to optimize this particular workflow.  If other voices chime in here and say that they'd prefer pandoc to work this way, I might consider it further.

**Comment by jgm** [comment]
By the way, it isn't true that config files in general resolve relative paths relative to the location of the config file.  For example, `cabal.config` (for Haskell cabal build tool) does not.

**Comment by agusmba** [comment]
> Seems like you'd get 100% of what you want with a simple wrapper around pandoc that changes directory before running pandoc with the defaults file.

I think pandocomatic already supports this (or something similar)

**Comment by brainchild0** [comment]
> Seems like you'd get 100% of what you want with a simple wrapper around pandoc that changes directory before running pandoc with the defaults file. 

Well, 100% of _something_, certainly, just not of _what I want_.


> By the way, it isn't true that config files in general resolve relative paths relative to the location of the config file. For example, `cabal.config` (for Haskell cabal build tool) does not.

Sure, the constraint is not true universally, but I suspect that *in general* is a fair characterization.  To what are the paths relative, in this instance, and do you consider this instance to represent the most general pattern, or a special case?

> I'm reluctant to add too much extra complexity and possibly break other workflows just to optimize this particular workflow. If other voices chime in here and say that they'd prefer pandoc to work this way, I might consider it further.

Definitely useful to hear other voices.  In pursuance of this end, assuming that difficulty of implementation is not a central concern, would you consider adding a switchable experimental feature, that users can try to preview the capabilities being considered, that can be tested simply by augmenting the command (rather than editing the file)?
