### ISSUE TITLE
Docx writer: Tables in list inherit indentation

### ISSUE THREAD

**Issue by martinlester** [jgm/pandoc#5947]
I am writing a document with tables inside a list.

When I convert to PDF or HTML, the table looks OK. When I convert to docx, the contents of each table cell is indented, as if it was a continuation of the enclosing list. I think the contents ought not to be indented.

The table looks fine when converted to docx outside a list.

I am using pandoc 2.8.0.1 with this command:

pandoc -o table.docx table.md

Contents of table.md:
````
1. foo

   -----------------------------------------
   xyz           xyz           xyz
   ------------- ------------- -------------
   x             y             z

   x             y             z
   -----------------------------------------

2. bar

---

-----------------------------------------
xyz           xyz           xyz
------------- ------------- -------------
x             y             z

x             y             z
-----------------------------------------
````

Output table.docx/table.pdf attached.

[table.docx](https://github.com/jgm/pandoc/files/3905075/table.docx)
[table.pdf](https://github.com/jgm/pandoc/files/3905076/table.pdf)

**Comment by eliphillips** [comment]
@martinlester I am having this issue as well. Did you ever find a solution?

**Comment by jgm** [comment]
I think the indentation is appropriate; it shows the difference between a table inside a list item and one outside of it.

**Comment by eliphillips** [comment]
I can understand the need for the differentiation, but it looks odd (in my case at least). I've got a table where things are meant to be left aligned, so the cell contents being indented makes them lose this appearance.

I think it'd make more visual sense if the grid itself were indented to be in line with the list items instead of each individual cell - see attached:

## Existing
<img width="987" alt="Screen Shot 2020-11-12 at 12 27 11 PM" src="https://user-images.githubusercontent.com/3180617/98992881-8eaf6400-24e2-11eb-8db5-076b25080566.png">

## Desired
<img width="991" alt="Screen Shot 2020-11-12 at 12 27 59 PM" src="https://user-images.githubusercontent.com/3180617/98992899-953ddb80-24e2-11eb-8b3e-a9695f1819a8.png">

**Comment by jgm** [comment]
I agree, this would make more sense.  So we should leave this open.  Unfortunately fixing it would require wading back into the quagmire of docx format, which I'm not eager to do, so don't expect a quick fix.  Maybe someone else would like to take this on?

**Comment by PRESFIL** [comment]
Any updates on this?

**Comment by jgm** [comment]
I've pushed a change that makes the two tables in the above example render exactly the same.
I think that's strictly better than the old behavior.  Ideally the whole table would be indented, so let's leave this open for that improvement.

**Comment by jgm** [comment]
We could try adding this to the table:
```
<w:tblPr>
<w:jc w:val="start"/>
<w:tblInd w:val="2160" w:type="dxa"/>
</w:tblPr>
```
where instead of 2160 we'd calculate a number depending on list indentation.

**Comment by jgm** [comment]
OK, I think I've got it now:

<img width="772" alt="Screen Shot 2022-08-26 at 3 16 26 PM" src="https://user-images.githubusercontent.com/3044/186997633-d440eb67-2ebd-4307-ba6f-1c4b3d876240.png">
