### ISSUE TITLE
Wild card for --bibliography flag

### ISSUE THREAD

**Issue by jooyoungseo** [jgm/pandoc#5955]
I am using Pandoc v2.8.0.1.

Currently, you cannot pass wildcard to `--bibliography` flag. For example, let's say you want to include all the *.bib files in "bib" folder:

```markup
pandoc document.md --bibliography="bib/*.bib"
```

That does not work.

It would be nicer if we could use wildcard.

**Comment by jgm** [comment]
Indeed, you can't specify multiple files at all: you must do `--bibliography foo.bib --bibliography bar.bib`.  Given this, I think it would be confusing to allow a wildcard here, particularly because there would then be a difference between `--bibliography bib/*.bib` (here the wildcard would be interpreted by the shell and you'd get something unintended) and `--bibliography=bib/*.bib`.

**Comment by jgm** [comment]
Try this (in linux/macos shell):
```
pandoc $(for x in bib/*.bib; do echo --bibliography $x ; done)
```

**Comment by jooyoungseo** [comment]
Thank you very much @jgm; however, I am a Windows user.

Would there be any way to address this request universally?

**Comment by jgm** [comment]
I'm sure there's a way to do this in Windows, but I don't do Windows.
You'd have to ask someone else.
