### ISSUE TITLE
2.9 epub bug?

### ISSUE THREAD

**Issue by psksvp** [jgm/pandoc#5986]
I have been using  pandoc to generate epub.  When I upgraded to 2.9, the epub generated from 2.9 cannot be opened by Apple Book.app and Android Playbook anymore. I unzipped the epub file to inspect the xhtml files. I found multiple `data-number="xxx.xx" ` tags in the same `<section>` tag. Please see example below. 

`<section id="chapter-50-an-evil-is-a-die-hard." class="level1 section" data-number="16" data-number="16">`

Chrome and Firefox reported error when they tried to parse it.

**Comment by kysko** [comment]
I can confirm that in the `section` tags for epubs, `data-number` is duplicated (as well as being in the following header).
It was ok with 2.8.x.
Note that using `make_sections` in lua filters doesn't create duplicates.

**Comment by waynehoover** [comment]
I'm also getting this error with 2.9. Can't open any pandoc epub's with apple books.

Error in apple books looks like this ```“error on line 11 at column 91: Attribute data-number redefined” ```

**Comment by Desbeers** [comment]
I can confirm this error as well. Looks to me related to this issue:

[With Pandoc 2.8, attributes are added to the header element instead of its parent when --section-divs is enabled](https://github.com/jgm/pandoc/issues/5965)

That also broke [EPUB writer: set epub:type on body element intelligently](https://github.com/jgm/pandoc/commit/7318bc91ce58bb6c39e556e334f278e590439c3f)

The pub:type commit from above worked fine in 2.7.3, didn’t work in 2.8 and also not in the latest 2.9 release.

**Comment by mb21** [comment]
Yes, `echo '# hi' | pandoc -t epub` produces:

```
<section id="hi" class="level1 section" data-number="1" data-number="1">
<h1 data-number="1">hi</h1>
</section>
```

**Comment by jgm** [comment]
I'm sorry about this regression.  We need more epub writer tests!
But it's a simple thing to fix and I will fix it soon.
