### ISSUE TITLE
JATS: support articleauthoring tag set

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#6014]
JATS offers three different tag sets: *archiving*, *publishing*, and *articleauthoring*, with the latter ones being a subset of the preceding tag set. Pandoc currently uses the *publishing* set. Since the easy authoring of article is one of pandoc's great strengths, it seems reasonable to also support the most restrictive variant of these tag sets.

As far as I can tell, this would only require different handling of footnotes. The *articleauthoring* tag set does not allow `fn-group` as part of the backmatter, so `<fn>` footnote elements have to be placed inline. All other changes can be handled in a custom template.

The current behavior has been implemented in response to #5511.

**Comment by jgm** [comment]
Can you explain a bit more what you have in mind?  Looks like we already switched from publishing to the archiving DTD.  Are you saying that the response to #5511 (moving from inline footnotes to footnotes in fn-group in the backmatter) was needed only because we were using the publishing DTD, and now we can go back to inline fn elements?

Perhaps it would be clearest if you just prepared a PR with the changes you propose.
