### ISSUE TITLE
Stack space overflow with a very large include-in-header

### ISSUE THREAD

**Issue by ociule** [jgm/pandoc#6031]
To export standalone html files, I currently include a quite large (3163 kB) HTML file containing the minimized plotly.js source code.

This worked fine until plotly 2.7, and breaks since 2.8 (I did not test 2.7.x, confirmed to break on 2.9 and 2.9.1.1)
```
pandoc test.rst -t html5 -o test.html --include-in-header=plotly.min.html_fragment
```
This results in a crash with the following error message:

```
pandoc.exe: Stack space overflow: current size 33624 bytes.
pandoc.exe: Use `+RTS -Ksize -RTS' to increase it.
```

Indeed, adding `+RTS -K512M -RTS` is a good workaround. This looks like a regression bug. Including large content in header is a desirable operation that used to work without workarounds. At the minimum, this issue would be useful for documenting the workaround.

Test.rst content doesn't matter, it's just a minimal file:

```
####
asdf
####
```

The plotly.min.html_fragment contains an html script tag, inside which I have a copy of plotly.js:

```
<!-- Source : https://cdn.plot.ly/plotly-latest.min.js -->
<script>
/**
* plotly.js v1.49.5
* Copyright 2012-2019, Plotly, Inc.

...
</script>
```

Here's a zip of that file for testing: [plotly.min.zip](https://github.com/jgm/pandoc/files/4026595/plotly.min.zip)

Cheers.

**Comment by jgm** [comment]
I can reproduce on macOS as well.

**Comment by jgm** [comment]
Output format is irrelevant.  I suspect this has to do with the change in doctemplates in 2.8.
Template variable values are converted to doclayout Docs, so that they can be wrapped and formatted intelligently in the template.  Perhaps the stack overflow is occurring at this conversion step.  The way to diagnose this would be to find a way to reproduce this in doclayout or doctemplates itself.

**Comment by jgm** [comment]
Can't reproduce it with doclayout alone.
Suspecting doctemplates.

**Comment by jgm** [comment]
Test program using doctemplates:
``` haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
import Data.Text.IO as T
import Data.Text as T
import Text.DocLayout
import Text.DocTemplates
import Data.Map as M

template :: Text
template = "$body$"

main = do
  res <- compileTemplate "mytemplate.txt" template
  x <- T.readFile "../../Downloads/plotly.min.html_fragment"
  case res of
         Left e    -> error e
         Right t   -> T.writeFile "out" $ render Nothing $ renderTemplate t $ Context $
                        M.insert "body" (toVal x :: Val Text) mempty
```
This works with `+RTS -K100K -RTS` but overflows with smaller stack sizes.

**Comment by jgm** [comment]
Running with profiling and `-xc` reveals:
```
*** Exception (reporting due to +RTS -xc): (base:GHC.Exception.Type.SomeException), stack trace:
  Text.DocLayout.realLength,
  called from Text.DocLayout.literal.\,
  called from Text.DocLayout.literal,
  called from Text.DocTemplates.Internal.toVal,
  called from Text.DocTemplates.Internal.toVal,
  called from Text.Pandoc.App.OutputSettings.optToOutputSettings.setListVariableM,
```
So it looks as if `realLength` from doclayout is the culprit.

**Comment by jgm** [comment]
This can be reproduced using just Data.Text.foldr.
```haskell
{-# LANGUAGE BangPatterns #-}
import Text.DocLayout
import Data.Text as T

main = do
  let t = T.replicate 20000000 $ T.singleton 'a'
  print $ T.foldr go (0, False) t
   where
   go !c (!tot, !_combiningChar) =
     case charWidth c of
       0  -> (tot, True)
       !n -> (tot + n, False)
```
Note thaht adding the bang patterns doesn't help.
Data.Text.foldl' works.

**Comment by jgm** [comment]
I tried a change in doclayout, but it didn't fix this issue.
The problem is that pandoc now converts variable values to `Doc Text`, which requires calculating "real widths" (taking into account combining characters, wide characters, etc.).  The calculation of the real width for this 3M string is causing the stack overflow (and also takes considerable time).

**Comment by jgm** [comment]
Well now I'm not sure what the issue is. I tried changing `setVariable` (which sets the variable for include-in-header) so that it doesn't use `realLength`:
```
-- | Set text value in text context.
setVariable :: Text -> Text -> Context Text -> Context Text
setVariable key val (Context ctx) = Context $ M.alter go key ctx
  where go Nothing             = Just $ toVal' val
        go (Just (ListVal xs)) = Just $ ListVal $ xs ++ [toVal' val]
        go (Just x)            = Just $ ListVal [x, toVal' val]
        toVal' t               = SimpleVal $ literal' t
        literal' x = mconcat $ intersperse DL.NewLine $
            map (\s -> if T.null s
                          then DL.Empty
                          else DL.Text (T.length s) s) $ T.splitOn "\n" x
```
But I still get the stack overflow when pandoc is compiled with this change.  It is likely something else related to doctemplates' handling of long literals.

**Comment by ociule** [comment]
Thank you for the great work! Can I assume the fix will be present in the next release of pandoc ?

**Comment by jgm** [comment]
Yes.

**Comment by jgm** [comment]
I should add that this also removes the long delay that you got with the big include after upping the stack space. It's basically instant now.
