### ISSUE TITLE
Number table references like figure references when converting from LaTeX

### ISSUE THREAD

**Issue by human9** [jgm/pandoc#6137]
# Bug report

(Submitting here as suggested from the mailing list)

Using pandoc 2.8, when converting from LaTeX to html and docx, table references behave differently to figure references. The table reference just becomes a hyperlink displaying the label like: [tbl:label], whereas the figure reference is numbered.

## Example
Compiling the input below as test.tex with `pandoc test.tex -o test.html`:
``` latex
This reference to Table \ref{tbl:label} doesn't work.
\begin{table}
        \caption{This caption has no number.}\label{tbl:label}
        \begin{tabular}{ l c r }
          -------- & -------- & -------- \\
          -------- & -------- & -------- \\
        \end{tabular}
\end{table}

This reference to Figure \ref{fig:label} works fine.
\begin{figure}
        \includegraphics[width=\textwidth]{example.png}
        \caption{A numbered caption, if I use pandoc-crossref.}\label{fig:label}
\end{figure}
```
## Actual output

<p>This reference to Table <a href="#tbl:label" data-reference-type="ref" data-reference="tbl:label">[tbl:label]</a> doesn’t work.</p>
<table>
<caption>This caption has no number.<span label="tbl:label"></span></caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">——–</td>
<td style="text-align: center;">——–</td>
<td style="text-align: right;">——–</td>
</tr>
<tr class="even">
<td style="text-align: left;">——–</td>
<td style="text-align: center;">——–</td>
<td style="text-align: right;">——–</td>
</tr>
</tbody>
</table>
<p>This reference to Figure <a href="#fig:label" data-reference-type="ref" data-reference="fig:label">1</a> works fine.</p>
<figure>
<img src="example.png" id="fig:label" alt="" /><figcaption>A numbered caption, if I use pandoc-crossref.<span label="fig:label"></span></figcaption>
</figure>

## Expected output

Table references should become numbered in the same way as figure references.

**Comment by jgm** [comment]
@lierdakil - wanted to check with you about this change, to make sure there are no bad effects on pandoc-crossref.  This change gives us `\ref` resolution for tables when interpreting LaTeX.  No number or label is added to the caption, though. Tables are thus treated like Figures are currently.

**Comment by lierdakil** [comment]
@jgm, thanks for the heads-up.

There shouldn't be any adverse effects on pandoc-crossref per se, but 3fbee8c doesn't _really_ resolve the issue as reported, i.e. pandoc-crossref won't magically number tables or resolve references to tables that have no identifier.

Notice that figures are treated slightly differently: in AST, images, unlike tables, can have attributes, and thus label is parsed as `id`.

IIRC, pandoc-crossref works around the issue that Tables in AST have no attributes by expecting a `Div` to be wrapping a `Table`.

FWIW, pandoc-crossref doesn't "officially" support LaTeX as an input format (since, you know, abusing pandoc citation syntax for references). But it's easy enough to cobble together a simple filter to convert LaTeX references to pandoc-crossref ones.

**Comment by jgm** [comment]
If I wrap the Table in a Div with id, then will pandoc-crossref assign it a number etc.?

Note that the identifier *is* findable; if `\label` has been used, the LaTeX reader puts an empty Span with the identifier at the end of the caption.
```
[Str "This",Space,Str "caption",Space,Str "has",Space,Str "no",Space,Str "number.",Span ("",[],[("label","tbl:label")]) []]
```
So pandoc-citeproc could simply look there.  Enclosing the whole thing in a Div might be more robust, though.

Another possibility would be for pandoc to add "Figure 1:" and "Table 1:" to the beginning of the caption; then the conversion would be complete without the need for pandoc-crossref.  It would be a bit awkward, though, since some output formats may add these things themselves (e.g. LaTeX), so in doing `-f latex -t latex` you'd get it doubled.

**Comment by lierdakil** [comment]
> If I wrap the Table in a Div with id, then will pandoc-crossref assign it a number etc.?

Yes, provided the table in question has a caption and it's label starts with `tbl:` (which hold in the example in the OP).

> Note that the identifier is findable; if \label has been used, the LaTeX reader puts an empty Span with the identifier at the end of the caption.

Ah, I failed to notice that.

While this is workable, current releases of pandoc-crossref won't recognize that. Also, perhaps of note, we discussed something like this recently wrt org reader in #5984. TL;DR, there are downsides to this approach.

> Another possibility would be for pandoc to add "Figure 1:" and "Table 1:"

Does not sound like a good idea -- unless we bite the bullet and implement "proper" item numbering in pandoc (would be cool, but probably infeasible in the short term), adding captions like this will just end up being confusing -- at least unless this behaviour is hidden behind an option. We discussed something similar in #5474, and while that was about the ODT writer, many points still apply.

**Comment by jgm** [comment]
I'm tempted then to replace the current behavior (adding the empty span) with wrapping a div.

**Comment by lierdakil** [comment]
Well, this does sound tempting. For one, I'd argue it would be closer to the semantics of LaTeX labels (as opposed to syntax), since labels are attached to whole floats, and not to captions. For two, it would be more consistent with other readers (JATS, Org).

However, changing that out of the blue might end up being compatibility-breaking for certain workflows, so perhaps better hold this off until the next major-ish release (2.10?).

In the meantime, a lua filter looking something like this might prove to be a reasonable band-aid:
```lua
function Table (tbl)
  local idSpan = tbl.caption[#tbl.caption]
  if idSpan and idSpan.t == "Span" and idSpan.attributes.label then
    table.remove(tbl.caption, #tbl.caption)
    return pandoc.Div(tbl, pandoc.Attr(idSpan.attributes.label))
  end
end
```

**Comment by jgm** [comment]
I already made the change and got rid of the empty Spans (which also had the problem of duplicating id attributes for figures).
