### ISSUE TITLE
Use $0/../share/… as a default search path for --data-dir [feature request]

### ISSUE THREAD

**Issue by sjackman** [jgm/pandoc#6143]
When Pandoc is moved after installation, it would be really helpful for Pandoc to search `$(realpath $0)/../share/…` for its data directory (where `$0` is `argv[0]`). My motivating use case is when installing a binary Pandoc package in my home directory using the Homebrew for Linux package manager. The workaround of creating a `~/.pandoc` symlink is pretty straight forward, but it would be fantastic if it worked out of the box. Compiling Pandoc from source also works, but it's much faster to use a binary package.

```console
$ brew install --force-bottle pandoc
$ pandoc -o foo.html foo.md
Could not find data file /home/linuxbrew/.linuxbrew/Cellar/pandoc/2.9.1.1/share/x86_64-linux-ghc-8.8.1/pandoc-2.9.1.1/data/abbreviations
$ ln -s ~/.linuxbrew/Cellar/pandoc/2.9.1.1/share/x86_64-linux-ghc-8.8.1/pandoc-2.9.1.1/data ~/.pandoc
$ pandoc -o foo.html foo.md
# Success!
```

**Comment by jgm** [comment]
This is a problem with the way homebrew is building pandoc.  It should use the `embed_data_files` flag so that the data files are baked in. (Background: in the old days cabal had nice support for installing data files to the right place, and pandoc could find them, but this is broken in stack.  See commercialhaskell/stack#848.  Embedding the data files fixes the problem.)
I would suggest reporting this to homebrew.

I don't want to implement your suggestion; it strikes me as potential a security risk.

**Comment by sjackman** [comment]
That's very helpful! Thank you, John.
