### ISSUE TITLE
Why does compileTemplate return a TemplateMonad?

### ISSUE THREAD

**Issue by poscat0x04** [jgm/pandoc#6165]
Since Identity is an instance of TemplateMonad the computation must be pure. I see no point in returning a monadic result. Why not just return a `Either String (Template a)` where a is a `TemplatTarget`?

**Comment by jgm** [comment]
Note that this is really a question about doctemplates, rather than pandoc.

> Since Identity is an instance of TemplateMonad the computation must be pure. 

No, this doesn't follow.  See the haddocks for doctemplates:

> The partials are obtained using getPartial from the TemplateMonad class. This may be implemented differently in different monads. The path passed to getPartial is computed on the basis of the original template path (a parameter to compileTemplate) and the partial’s name. The partial’s name is substituted for the base name of the original template path (leaving the original template’s extension), unless the partial has an explicit extension, in which case this is kept. So, with the TemplateMonad instance for IO, partials will be sought in the directory containing the main template, and will be assumed to have the extension of the main template.

The library is designed to let you specify (through the implementation of the instance of TemplateMonad) how partials are to be handled.  If you use the Identity instance, you don't get partials at all.  If you use IO, partials are read from the file system.  But you could also implement an instance that, for example, obtained partials from a database or API query.

**Comment by poscat0x04** [comment]
Ah that makes sense.
