### ISSUE TITLE
Pandoc Package cannot be installed on MacOS Catalina

### ISSUE THREAD

**Issue by jfischeresq** [jgm/pandoc#6169]
Hey,

When I tried to install the Pandoc package on MacOS Catalina, I received an error (see screenshot). I did not see any open issues for this. 

<img width="419" alt="Screen Shot 2020-03-01 at 5 24 09 PM" src="https://user-images.githubusercontent.com/56164294/75635141-b58e6a00-5be1-11ea-820e-04a16d291cd8.png">

**Comment by jgm** [comment]
Odd.  I am able to install it on Catalina.
I'm a bit confused, though.  Where did you download the installer?  Our releases are hosted on this github site (under Releases), but the dialogue box says you downloaded it from pandoc.org?

**Comment by jgm** [comment]
Some info here:
https://apple.stackexchange.com/questions/366542/install-spotify-cant-be-opened-because-apple-cannot-check-it-for-malicious-so
including a workaround.

Here is the background on getting apps properly notarized, which is apparently yet an additional hoop I have to go through besides paying apple for the certificate and signing the code:

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

Here are their instructions for getting pre-existing software notarized:

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution#3087722

Looks like I need to figure out how to use `altool` and `staple` in the release process.

**Comment by jgm** [comment]
Note that they recommend submitting earlier versions of software for notarization as well.

**Comment by jgm** [comment]
Relevant GHC issue
https://gitlab.haskell.org/ghc/ghc/issues/17418

**Comment by jgm** [comment]
I've got this solved now, with the new release process in master.
So the next release should be notarized.
