### ISSUE TITLE
Markdown to plain: ** followed by _ not correct

### ISSUE THREAD

**Issue by Bill-Stewart** [jgm/pandoc#6216]
pandoc version: 2.9.2.1

Command: `pandoc --columns=79 --tab-stop=2 -t plain+smart test.md`

Content of `test.md`:

    Doesn't work: **strong**_emphasized_

    Works: __strong__*emphasized*

Output:

    Doesn't work: strong_emphasized_

    Works: strongemphasized

(The lack of whitespace between the words `strong` and `emphasized` is on purpose to illustrate the issue)

I was expecting both lines in the markdown file to produce the same output. Am I misunderstanding something?

**Comment by jgm** [comment]
Use `pandoc -t native` to see how pandoc is parsing the input:
```
[Para [Str "Doesn\8217t",Space,Str "work:",Space,Strong [Str "strong"],Str "_emphasized_"]
,Para [Str "Works:",Space,Strong [Str "strong"],Emph [Str "emphasized"]]]
```
So, the `_emphasized_` is not being parsed as emphasized text.  That might be a bug in the markdown reader (but you can avoid it with `-f markdown-intraword_underscores`).

In the second line, you don't get a space because the structure being rendered is
```
STRONG "strong", EMPH "emphasis" 
```
which doesn't contain a space.  In plain output, emph and strong are rendered like regular text.

**Comment by Bill-Stewart** [comment]
Thank you, disabling the `intraword_underscores` extension is a good workaround!

I will leave to your discretion as to whether to leave this open (in case of a bug in the markdown reader).

**Comment by jgm** [comment]
I'm not going to worry about the possible issue in the markdown reader, because I'm planning to move over to a commonmark-based system that will eliminate these issues at some point in the future.  So, I don't want to invest time in edge cases.
