### ISSUE TITLE
Not possible to create a TOC with page numbers when converting to PDF using wkhtmltopdf

### ISSUE THREAD

**Issue by advename** [jgm/pandoc#6270]
Using the `-V documentclass=report` parameter while converting markdown to pdf using Latex, the TOC has page number of each Chapter:
```
1. Chapter ..................... 2
   1.1 Chapter ............... 5
2. Chapter ...................... 9
```
But when converting markdown to HTML, using wkhtmltopdf, the TOC has no page numbers.
Is this a feature, having page numbers in the TOC when converting markdown to pdf via html that could be added? Or is there a "hack" available?

**Comment by mb21** [comment]
Looks like you have to use an XSLT stylesheet... https://stackoverflow.com/a/5954424/214446

Different PDF engines all have their different quirks :P 

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by jgm** [comment]
Actually, this is tricky.  wkhtmltopdf allows you to generate a toc with page numbers.
(That would be different from the toc we get with pandoc's `--toc`, which is generated in the HTML file and hence can't have page numbers, because it's pre-layout.)
```
wkhtmltopdf toc my.html my.pdf
```
I tried passing in `toc` using `--pdf-engine-opt=toc` but it didn't work, something about parameter order.  I think maybe we could do something to make this possible in pandoc, so let me open this again.

**Comment by advename** [comment]
Any updates on this? :)

**Comment by jgm** [comment]
Actually, trying it again, it seems to work (this is with HEAD pandoc, you can try a nightly):

```
pandoc -t html -o my.pdf --pdf-engine-opt=toc --pdf-engine=wkhtmltopdf MANUAL.txt
```

This yields a PDF that starts with a TOC generated by wkhtmltopdf, including page numbers.

**Comment by jgm** [comment]
<img width="831" alt="Screen Shot 2020-04-20 at 9 02 45 AM" src="https://user-images.githubusercontent.com/3044/79773043-c015d780-82e5-11ea-9570-778e19d768f5.png">

**Comment by tarleb** [comment]
It appears that the issue has been resolved, so I'm closing this.
