### ISSUE TITLE
Bug: cannot convert to pdf and write to stdout instead of file

### ISSUE THREAD

**Issue by ORESoftware** [jgm/pandoc#6294]
I think this is a bug.

Please compare this behavior:

```
pandoc -f html  --pdf-engine=xelatex -t latex  -o  ./test.pdf
```

with this behavior

```
pandoc -f html  --pdf-engine=xelatex -t latex  >  ./test.pdf
```

I want it to convert the output to PDF in the second case, but I am pretty sure it doesn't since there is no file ending in .pdf in the second case, so pandoc doesn't assume it's writing to pdf.  

My guess:  My guess is that it uses the file extension in the first example to know that it should convert from latex to pdf, but in the second example, it doesn't know that, so just converts to latex and not all the way to pdf?

there are two complains I have:

1. this tecnique would be preferred:

```
pandoc -f html -t latex | pdflatex  >  ./test.pdf
```

instead of using:

```
pandoc -f html  --pdf-engine=xelatex -t latex  -o  ./test.pdf
```

pandoc should not try to do magic behind the scenes - if pandoc can convert something to pdf, it should, otherwise we should be using standard linux pipelines and using the actual program that does the conversion.

2. It should require the developer to be explicit. Instead of inferring the file type from the destination file extension, it should require the `-t xxx` option.  This would probably have helped avoid the bug that this issue likely represents (if it is indeed a bug).

**Comment by ORESoftware** [comment]
I am on:

```
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
Default user data directory: /home/oleg/.local/share/pandoc or /home/oleg/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by ORESoftware** [comment]
for more context: https://github.com/tex-mirror/pdftex/issues/1

**Comment by jgm** [comment]
```
pandoc -f html  --pdf-engine=xelatex -t latex  >  ./test.pdf
```
just tells pandoc to convert to LaTeX.  Implicit conversion to pdf only happens if pandoc is passed an `-o` argument with a pdf extension.  Here it's only the shell that sees the redirection to a pdf.  With recent pandoc versions you can do `-t pdf`.

AS for your other comment
```
pandoc -f html -t latex | pdflatex  >  ./test.pdf
```
This won't work, `pdflatex` doesn't work like that.  In addition, pandoc needs to do a number of transformations on the document and associated (e.g) image files to produce a PDF.  Of course, you're welcome to create latex and pipe it to something that can consume this if that's what you want to do.  But in that case you'll need `-s` so you get the appropriate document header/footer.

```
it should require the -t xxx option.
```
We infer output format from file types quite generally.  You're the first to complain about it; I think most people are happy with this behavior.  If you're not, then you're free to be explicit.
