### ISSUE TITLE
Images are not output to powerpoint when using in a list 

### ISSUE THREAD

**Issue by koppor** [jgm/pandoc#6303]
Works 

```markdown
![alt](test.png)
```

(Image taken from https://github.com/jgm/pandoc/issues/4586 --> https://user-images.githubusercontent.com/20303575/39141146-22cfd3aa-4727-11e8-992a-035197ca2f70.png)

```terminal
pandoc.exe -o slides.pptx slides.md
```

![image](https://user-images.githubusercontent.com/1366654/79719218-5e05a400-82de-11ea-8061-385649808c49.png)

Does not work:

```markdown
- ![alt](test.png)
```

![image](https://user-images.githubusercontent.com/1366654/79719318-97d6aa80-82de-11ea-9883-8d946214bcdf.png)

When using `.docx` outputter, it renders OKish:

![image](https://user-images.githubusercontent.com/1366654/79719343-ab821100-82de-11ea-8345-7767e6d53b0f.png)

(alt put in separate bullet point)

Expected result (for both pptx and docx)

![image](https://user-images.githubusercontent.com/1366654/79719384-c2c0fe80-82de-11ea-91b7-c3460d44d42e.png)

**Comment by jgm** [comment]
@jkr

**Comment by jkr** [comment]
Hi -- the issue here is that images can't be used inline with text in powerpoint output. This has been discussed elsewhere, but essentially: powerpoint is a visual format, so there is no reliable way to place images with relation to text (they can only be placed geometrically on the slide). If you want to integrate images with text, you can use two-column output, or use them with a caption. Beyond this, though, we're limited by the output format.

**Comment by jkr** [comment]
By the way, this has been discussed in commits and issue responses, but isn't clearly in the docs. What would be the best way to put this sort of thing in? Should there be a "Quirks of PowerPoint Output" section somewhere? @jgm?

**Comment by jgm** [comment]
@jkr if you want to write up something for the FAQs I can put it there.
We could also think about adding a section to the manual, as we have for epub.
