### ISSUE TITLE
--pdf-engine: add DomPdf

### ISSUE THREAD

**Issue by muv1** [jgm/pandoc#6309]
Currently `--pdf-engine` allows these:

- `context`
- `latexmk`
- `lualatex`
- `pdflatex`
- `pdfroff`
- `prince`
- `tectonic`
- `weasyprint`
- `wkhtmltopdf`
- `xelatex`

Granted that is a pretty big list, but I have a suggestion. So I prefer to avoid
LaTeX, as its a pretty heavyweight requirement, so that leaves these:

- `pdfroff` (Roff)
- `prince` (HTML)
- `weasyprint` (HTML)
- `wkhtmltopdf` (HTML)

`pdfroff` is a shell script, so that can cause issues with Windows users. Prince
is not open source, so that leaves these:

- `weasyprint` (HTML)
- `wkhtmltopdf` (HTML)

I didnt do much testing with these, but in my search I came across this:

<https://github.com/dompdf/dompdf>

6.9k stars, and is up to date. It doesnt require a browser for conversion. The
download is only 4 MB:

<https://github.com/dompdf/dompdf/releases>

The only issue I had is that it is missing some of the cutting edge CSS. The
standardized CSS seems to be fine though. Only PHP is required. I have used this
with several HTML already and it was a smooth process. I would recommend it.

**Comment by muv1** [comment]
Here is the script I used:

~~~php
<?php
require 'dompdf/autoload.inc.php';
use Dompdf\Dompdf;

$dompdf = new Dompdf();
$s_in = file_get_contents('index.html');
$dompdf->loadHtml($s_in);

$dompdf->render();
$s_out = $dompdf->output();
file_put_contents('index.pdf', $s_out);
~~~

**Comment by alerque** [comment]
> The download is only 4 MB

Plus an entire PHP installation.

**Comment by muv1** [comment]
@alerque why do you have to be like that?

Sigh. Ok, yes, PHP is required. But PHP is 25 MB:

<https://windows.php.net/download>

now lets compare LaTeX. 232 MB:

<https://miktex.org/download>

**Comment by alerque** [comment]
I'm not necessarily opposed to including DomPdf if it provides some compelling advantage in output or features over other options, but just raw disk usage of the installation is not very compelling.

You can use whatever you want, but you get what you pay for. LaTeX is big but it does an absolutely fantastic job of some things that nothing else even comes close too. And I say that as one of the primary authors of a direct competitor, [SILE](https://sile-typesetter.org/) which I'm also proposing be include in Pandoc (see #6087 and WIP at #6088). As somebody who has been though the deepest rings of torture that LaTeX has to offer and put in thousands of hours writing a replacement, I'll still say LaTeX will give the best output for many jobs and when you don't have to think about managing it's internal or the build process because Pandoc does it all for you, a little bit of disk space for tooling is a small price to pay for great output.

**Comment by muv1** [comment]
I too have used Markdown, HTML and LaTeX extensively, though not as much as you by a long shot.

I think my experience and/or needs probably line up with a typical user: They just want something simple coming from a Markdown document, or perhaps simple HTML document.

If you tell them to just use and install LaTeX, thats like shoving a brick wall in their face and saying "climb". LaTeX is powerful, but its the sledgehammer when most people just need a rubber mallet. You more than others should know the headaches of dealing with LaTeX packages.

**Comment by tarleb** [comment]
I'd like to make a slightly off-topic meta-comment about why it was easy to misread the issue. The following is an intentional misrepresentation just to show how the text *can* be interpreted, forgive me for that. The issue starts by outlining why most of the currently available solutions are "bad", ignores the remaining options, then proceeds to suggest an "superior" alternative. At least to me, this seemed more adversarial than it needs to be, as it diminishes previous work. I very much assume that was not the intention, and you just wanted to provide your motivation for proposing another engine, which is good. So let's start over.

DomPdf looks like an interesting project. What are the features which would make it worth it to support it in pandoc? It has a few transitive dependencies, but appears to be relatively easy to install via `composer require dompdf/dompdf`. This makes it similar to `weasyprint`, just in PHP instead of Python. However, it also lists MBString as a requirement, which cannot be installed via composer. It seems that it does not come with a standalone executable, would we have to provide our own PHP scripts?

**Comment by muv1** [comment]
@tarleb thanks for the comment.

I wont try to convince you, as you see to be pretty skeptical to the idea as a
whole. But I can explain my movivation.

Over the years, I have reached for Pandoc from time to time to fill a role. If
I needed some random format converted to some other random format. I knew each
time using it that I should be wary, as my assumption would be that my inputs
and output would need to be simple, as Pandoc might not handle the corner cases
well. Many times Pandoc has impressed me, as it seems to be pretty robust
across a myriad of inputs and outputs. I was quite impressed with its clean and
simple output of Markdown to LaTeX for example.

This is why I was so disappointed when I frist tried to convert Markdown to
PDF with Pandoc. Many will disagree, but personally I feel that Pandoc utterly
failed me in this regard. Part of it was my own fault, I have since come to
realize that Markdown isnt a good input to get to PDF, HTML is a better fit.

The reason I feel Pandoc failed is this. In many cases software can be
difficult to install. Its either a huge download, or its not compiled for your
system, or it has 200 dependencies (hello Rust), or any number of other reasons.
Thats why for me, when software is easy to install I notice. Because typically
someone worked pretty hard to make it easy.

For me, installing PHP is easy. You can run the installer, or even a Zip is
offer that you just unpack. In regard to DomPdf, you dont even have to use
Composer, you can get a 4 MB Zip with everything included:

<https://github.com/dompdf/dompdf/releases>

With regard to WeasyPrint, I recently learned that the Python Zip doesnt include
Pip, and no easy way to get it:

<https://docs.python.org/using/windows.html#the-embeddable-package>

So you have to use the Python installer rather than the Zip. This might seems a
small detail, but again it just lends to the idea that I respect projects that
put in the extra effort to make using their product simpler: smaller downloads,
less dependencies, precompiled and/or prepackages stuff where it makes sense.

After Pandoc failed me, I tried a number of different solutions. AsciiDoc,
reStructuredText, Org Mode, LaTeX, even weird stuff like XPS. and when I came
across DomPdf it was like a breath of fresh air. No, it doesnt have an
"executable" that I know of. But I will take writing the 10 line script I put
above, over downloading a 230 MB LaTeX installer any day. Especially if it
means not having to deal with picking LaTeX packages. With HTML, you dont have
to pick a package just to put a border or margin on something, its included.
I literally had to do that with LaTeX:

<https://tex.stackexchange.com/questions/539143>

Please dont take this the wrong way. I still think Pandoc is a great project.
I just disagree with the direction that was taken with this one type of
conversion. Honestly Im not too concerned if this gets accepted, I mostly wanted
to share the solution I found in case its helpful to anyway wanting to convert
to PDF. Thanks.

**Comment by tarleb** [comment]
Please help us to boil the given information down to the essential points which we need to make a decision. My take-away so far is:

- PHP and DomPdf are comparatively easy to install just by downloading and unpacking zip files, especially on Windows.
- There is no generic method of calling it from other programs.

Valuable additional information would be: feature comparison to other engines, size of an installation (ideally with concrete numbers to compare to the alternatives), a proposed way of involving the converter from pandoc.

Please keep in mind that feature-creep is a real problem, and critically scrutinizing new proposals is essential. The more information we have on its impact, and the greater the evidence for real benefits for a wide user-base, the higher the chance of inclusion of a new feature.

Your effort to share your findings is appreciated in any way. You might want to add the information to the [wiki](https://github.com/jgm/pandoc/wiki).

**Comment by muv1** [comment]
I'm not adding any more. I found a solution for myself that works, and I wanted to share it. I've done that. If no one else thinks it's a good solution fine, but at least I can say I tried.

**Comment by tarleb** [comment]
My point is that we don't have enough information to arrive at that conclusion. If you don't want to continue on that path, and don't want to invest the time to bring the feature forward, then that is fine too.

**Comment by muv1** [comment]
@tarleb but no rule exists that says **I** have to be the one to provide that information. **You** could get the information yourself. **You** could try the solution to see if its any good.

If you dont want to do that, fine. But at least I can say that I didnt selfishly keep a working solution to myself.
