### ISSUE TITLE
Markdown writer doesn't emit boolean false metadata values

### ISSUE THREAD

**Issue by khenriks** [jgm/pandoc#6388]
I am using pandoc 2.9.2.1.

Pandoc doesn't seem to properly output boolean false values in the metadata block when writing markdown. I tested outputting the intermediate data with `-t json` and so verified that it's getting parsed on input, it's just not showing up in the output.

Minimal reproduction:

```shell
cat | pandoc -s -t markdown << EOF
---
nvalue: false
value: true
---

Some text
EOF
```
Actual output:

```
---
value: true
---

Some text
```

Expected output:

```
---
nvalue: false
value: true
---

Some text
```

Thanks!

**Comment by jgm** [comment]
This is because we're formatting this by converting the Meta to a doctemplates Context.  Doctemplates doesn't contain boolean values---it tests instead for empty values---so we have (in T.P.Writers.Shared line 110):
``` haskell
metaValueToVal _ _ (MetaBool True) = return $ SimpleVal "true"
metaValueToVal _ _ (MetaBool False) = return NullVal
```
Not sure we can do better without modifying doctemplates to add an explicit boolean type (which might make sense in any case).
