### ISSUE TITLE
Colorlinks option is not applied to some hyperlinks

### ISSUE THREAD

**Issue by jpeacock29** [jgm/pandoc#6453]
`pandoc --version`
> pandoc 2.9.2.1
> Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2

Create a document, `test.md`, containing:

```
---
colorlinks: true
---

<google.com>
[google.com]()
[google.com](google.com)
```

Running `pandoc test.md -o test.pdf` yields a pdf in which only the last link is actually colored blue; the first two remain black.

**Comment by jgm** [comment]
You'll see from the manual that pandoc gives you very fine-grained control: there are:
`linkcolor, filecolor, citecolor, urlcolor, toccolor`.
Setting `urlcolor` should give you the first one.  I'm not sure why the second one is not being colored, but presumably because there's no URL, hyperref isn't regarding it as a link?
