### ISSUE TITLE
ODT reader replaces TABs by nothing

### ISSUE THREAD

**Issue by cwh42** [jgm/pandoc#6473]
Tried pandoc 2.6 and 2.9.2.

`cwh@thinkcwh:~> pandoc tab-testcase.odt -t native`
`[Para [Str "ThislineisTABseparated."]]`

TABs are completely skipped. I expect them to become spaces.

Find [tab-testcase.odt](https://webeve.de/~cwh/tab-testcase.odt) here.
It looks like this:
![image](https://user-images.githubusercontent.com/336868/85203843-a3f7dc00-b310-11ea-8e81-c127c26c3a36.png)

**Comment by mb21** [comment]
You're expecting one tab to become one space? That sounds reasonable...

**Comment by cwh42** [comment]
Yes, it should work the same as it already works for docx:
`cwh@thinkcwh:~> pandoc tab-testcase.docx -t native`
`[Para [Str "This",Space,Str "line",Space,Str "is",Space,Str "TAB",Space,Str "separated."]]`

**Comment by jgm** [comment]
@MarLinn

**Comment by niszet** [comment]
I send a PR for this issue as https://github.com/jgm/pandoc/pull/7185. Add a function to treat tabs as spaces.
Any combinations of spaces and tabs are replaced as one space correctly.

By following command, ODT which contains tabs are treated correctly.

```
pandoc tab-testcase.odt -f odt -t markdown
```

In the ODT, characters with spaces and tabs are shown as 

![image](https://user-images.githubusercontent.com/28832585/112776476-c296ba80-907a-11eb-86ba-b8fdc8b46ebb.png) .

And it converted to following.

```
A B C D E F G H I J K L M N O
```

Input file is attached here (zipped because odt cannot be placed here).

[tab-testcase.zip](https://github.com/jgm/pandoc/files/6218708/tab-testcase.zip)


Maybe the PR solves this issue.

**Comment by jgm** [comment]
PR has been merged.
