### ISSUE TITLE
pandoc 2.10 i386 windows release contains 64-bit binary

### ISSUE THREAD

**Issue by tonypdmtr** [jgm/pandoc#6493]
pandoc-2.10-windows-i386.zip

has 64-bit binary

**Comment by jgm** [comment]
Oh, that's interesting.  Can you check to see if the previous release has the same problem?
There has been little change in the build procedure.

**Comment by jgm** [comment]
Update: I don't have a Windows box to test on, but the `file` command says that the 2.9.2.1 i386 release contains
```
pandoc.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Window
```
while the 2.10 i386 release contains
```
pandoc.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```
This confirms the report, and shows that the problem only affects the latest release.

**Comment by jgm** [comment]
For now, I've removed the windows-i386 releases for 2.10.

The fundamental underlying problem is that ghc stopped releasing i386 windows binaries some time ago (8.6.3 is the last version with a 32-bit windows binary, I believe).  I had thought that installing the `haskell-stack` from chocolatey with the `--x86` option would work -- as it has in the past -- but this time it did not.

**Comment by jgm** [comment]
Build log shows that ghc 8.6.5 is being downloaded by stack.  That's suspicious, since ghc doesn't release a 32-bit windows binary for that version.

**Comment by jgm** [comment]
Experimenting with a new build using chocolatey's haskell-dev package and cabal: see actions under rc/win-i386-test.

**Comment by tonypdmtr** [comment]
> Oh, that's interesting. Can you check to see if the previous release has the same problem?
> There has been little change in the build procedure.

No, previous release was OK.

**Comment by tonypdmtr** [comment]
Issue still there with 2.10.1 (https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-windows-i386.zip)

**Comment by jgm** [comment]
I'm sorry, I haven't found a solution.
I've deleted the i386 package again.

**Comment by jgm** [comment]
I haven't found a solution, except to stop releasing an i386 windows package.  Sorry!

**Comment by tonypdmtr** [comment]
Too bad :( but life goes on :)

Another solution, perhaps, would be to revert to using the 8.6.3 dependency you mention above.

(Do you have statistics what percentage of your downloads were for 32-bit to know how many people may be affected.)

**Comment by tarleb** [comment]
Using  download stats for pandoc 2.7.3, which is one of the releases with the most downloads: about 5.7% of all Windows binary downloads were for 32 bit systems; the change affects a total of about 1.4% of all pandoc users (possibly less, because Linux users may use alternative installation paths).

One can get this info by running `make download_stats` in the project's root directory.

**Comment by jgm** [comment]
I tried to get it working with 8.6.3, but no success.  If someone else wants to figure this out, I'd consider a PR or pointers, but for me it's not worth the additional time spent.
