### ISSUE TITLE
Please pull https://github.com/jgm/pandoc/pull/6572

### ISSUE THREAD

**Issue by kjambunathan** [jgm/pandoc#6579]
Please pull my documentation changes to `lua-filters.md'.  See https://github.com/jgm/pandoc/pull/6572

> I decided against including this example. All other examples demonstrate a real-world use case, with only the first example being an exception. The proposed example demonstrates how to use the `Pandoc` filter and constructor, without a direct real-world use case.
> 
> The example **is** helpful, but is doesn't has a good place yet in the document. A section on filter functions would be a good place to include an example like this.

@tarleb  It is possible that you have _forgotten_ to push the changes (you  have accepted).

Your comment indicates that you have accepted _a part_ of my proposal.  I don't see a corresponding commit to the master, and _yet the PR is closed_.  I hope you have the changes queued up in your local machine.

**Comment by tarleb** [comment]
There seems to be a misunderstanding. What I said is that I'd like to use "at most one" of the examples, so either 1 or 0. I went with zero, simply because the docs are currently not structured in a way that makes the example a good fit *at the moment*.

I appreciate the time and effort you put into this, and note again that the general idea is good. However, I don't want to merge it at this time due to the reasons outlined in the PR.
