### ISSUE TITLE
Bug: inlining mathjax 3.0 in html fails to load properly [2.10.1]

### ISSUE THREAD

**Issue by gabyx** [jgm/pandoc#6599]
It's probably not a pandoc bug (maybe special character escaping or so?)

**Reproduce**:
```shell
echo '$asd$' | pandoc -f markdown+tex_math_dollars --standalone --self-contained --mathjax -t html5 > Content.html
```
**Output**:
Correct HTML which does not load in Chrome properly because mathjax (I assume) has html tags in the source `,r.write('<html><head><`

Can this somehow be fixed? Escping special characters in the source `.js` ??

**Comment by jgm** [comment]
Did `--self-contained` work with earlier versions of MathJax?
My experience has been that it never worked.  MathJax needs to load a bunch of stuff dynamically (or it used to), and pandoc's self-contained algorithm isn't smart enough to interpret JavaScript and include this.

**Comment by ickc** [comment]
Is pandoc using TeX-AMS_HTML-full everywhere (I only see that it is on the realjs template)? I think years ago I submitted a PR so that pandoc uses the -full variant. If so, it is a self-contained js that will not need dynamic loading of other js. It might still loads some web-fonts. The situation may also change slightly after MathJax 3.0.

**Comment by ickc** [comment]
Oh, c.f. https://github.com/jgm/pandoc/commit/d8ad766d17603784b86fc5c2e1b22864125d04d1 , may be it is not using the full variant now.

**Comment by jgm** [comment]
Unescaped HTML inside a script tag shouldn't be a problem, should it?

I tried the command listed above.  Content.html loaded fine in both Safari and Chrome.  JavaScript console gave three errors, all because of math fonts that could not be loaded. So I don't think there's a problem here other than the (already known) problem of math fonts.

**Comment by gabyx** [comment]
I close this, because I think its suceptical to some weird extension in Chrome which give syntax error in this script!
