### ISSUE TITLE
HTML->zimwiki: links in headers are gone

### ISSUE THREAD

**Issue by 12425** [jgm/pandoc#6605]
``` html
<h1><a href="http://foo/">bar</a></h1>
```

becomes

```
====== bar ======
```

Supposed to be

```
====== [[http://foo/|bar]] ======
```

**Comment by 12425** [comment]
Hello, can I get a few sort of hints?

**Comment by tarleb** [comment]
Could you point to some documentation which shows that this is allowed? I checked the ZimWiki writer sources, and it contains this code:

``` haskell
blockToZimWiki opts (Header level _ inlines) = do
  contents <- inlineListToZimWiki opts $ removeFormatting inlines   -- emphasis, links etc. not allowed in headers
  let eqs = T.replicate ( 7 - level ) "="
  return $ eqs <> " " <> contents <> " " <> eqs <> "\n"
```

So the removal of the link appears to be intentional. However, this is from 2016, so maybe things have changed? If you have access to resources which show how to deal with links in headers, please let us know.

CC @alexivkin, who wrote the ZimWiki writer.

**Comment by alexivkin** [comment]
Sadly, v0.72 ZimWiki still does not allow links in the header. There are no docs around what is and what is not, I had to read the python source code for Zim. Pinging @jaap-karssenberg in case he can help.

**Comment by tarleb** [comment]
Thanks! Closing for now, since this is not a pandoc issue.

**Comment by jaap-karssenberg** [comment]
Latest version of zim *does* allow links in the header

**Comment by tarleb** [comment]
Thanks @jaap-karssenberg! Reopening...
