### ISSUE TITLE
wishlist: Guile support for anything Lua can do

### ISSUE THREAD

**Issue by inklesspen** [jgm/pandoc#6653]
I am learning how to write a Lua filter and it is somewhat hard going, between the lack of a REPL and the limited Lua standard library. I am sure it would be a great deal of work to implement support for [Guile Scheme](https://www.gnu.org/software/guile/learn/) but I think it would make the task of writing filters a lot simpler.

**Comment by alerque** [comment]
What makes you say Lua doesn't have a REPL? Have you tried running `lua` on the command line?

The limited standard library *can* be frustrating. It's (not) there for good reasons, but yet it can be obnoxious. That being said there is a whole ecosystem of Lua modules you can import to your filters. For example the most common thing I `require()` is [Penlight](https://lunarmodules.github.io/Penlight/); you might find it useful.

Honestly I don't think writing filters is going to get any 'simpler' than Lua. Of course simple is a rather subjective metric, but I've used a lot of languages (including Guile/Scheme) and am pretty sure if 'simpler' is the goal Lua is closer to the mark. If it really doesn't suit your taste, filters can also be written in Python pretty easily. Or if you want to get really creative, using C or Rust to write your filter just import it into either Lua or Python.

**Comment by inklesspen** [comment]
Lua does have a REPL, but unless I'm missing something there is no way to get a Lua REPL with the Pandoc modules included.

And while I can use Penlight, that means anyone who wishes to install my filter must also install Penlight, which is kind of a hassle for the end-user.

**Comment by tarleb** [comment]
Guile is a great language, and despite mostly writing Haskell nowadays, I still admire Lisp dialects for their elegance and syntactical simplicity. Lisp is what made me leave biology for mathematics and programming.

I'm telling this because I want to make clear that it's not because of the language when I say this: despite liking the idea behind this proposal, I am absolutely *not* in support of this. It would indeed be "a great deal of work". In fact, that's quite an understatement. Without going into too much detail, but this would be *extremely* expensive in terms of required work just to get this working (think many months of full time work). And we are not even factoring in the need for documentation, updating the surrounding ecosystem, getting people to use Scheme, and adding additional code to the code base.

It's a good idea, but this ship has sailed.

Just adding a Lua REPL to pandoc would be an order of magnitude easier.

**Comment by tarleb** [comment]
I'm closing this, as Guilde bindings are highly unlikely to ever be implemented. Adding a REPL has been discussed before, but there is no issue yet. Please feel free to raise one so we won't forget about it.

**Comment by mcepl** [comment]
For lovers of parenthesis, I would point your interest to https://fennel-lang.org/ … it can help you.

**Comment by alerque** [comment]
Also in case the OP missed it, there is a Lua REPL now too.
