### ISSUE TITLE
LaTeX writer is influenced by `toc` in metadata, but HTML writer is not

### ISSUE THREAD

**Issue by nrnrnr** [jgm/pandoc#6664]
I expected setting `toc` in metadata would cause a table of contents to appear.  This seems true for LaTeX output but not for HTML.

Input file `toc.md`:

````
% Hello

# big header

Content me, please.

---
toc: true
...
````

Commands:

````
> pandoc -s -o f.html toc.md
> pandoc -s -o f.tex toc.md
````

The `.tex` includes a table of contents.  The `.html` doesn't.  Evidence:

```
nr@homedog ©150vm/s/w/modules> grep contents f.tex
\tableofcontents
nr@homedog ©150vm/s/w/modules> grep big f.html
<h1 id="big-header">big header</h1>
```

(If there were a TOC, the word "big" would appear twice, which is what I expected.)

My Pandoc version is 2.2.1, but I've confirmed similar issues with 2.10.1.

I found issue #6016, but was not able to conclude whether that rules out using `toc` to enable a table of contents.  For the LaTeX writer, it does not.

**Comment by jgm** [comment]
This is true, but it's not really a bug.

In some formats, including a table of contents requires setting the `toc` variable in a template.  That's what happens for LaTeX.  Since variables are set implicitly by metadata fields, setting `toc` in metadata will trigger a TOC for LaTeX.

In other formats, the table of contents needs to be constructed by the writer and inserted.  In these formats, it's 
not enough to set `toc`.

I don't regard this as a bug, because nowhere in the documentation does it say you can use `toc` in metadata instead of `--table-of-contents` on the command line (or defaults file).  It works accidentally in a few cases.

**Comment by nrnrnr** [comment]
Totally fair.  I was hoping that `toc` would work.  I’m using the same command line on a moderately large collection of documents, and I’d prefer to keep doing so.  But I’ll jigger my Makefile recipe so it can consult the metadata and then build a command line therefrom.
