### ISSUE TITLE
List will not be recognized in markdown if there is the <a> tag before it

### ISSUE THREAD

**Issue by masterAllen** [jgm/pandoc#6667]
# Pandoc version
2.10.1
# Probelm
If there is the <a> tag before a list in markdown file, the output in html or pdf format will not recognize that list.
# Example
If i write md file like this:
```
# Header
<a></a>
- number
- boolean
- null
```
Then the output in html will be this:
```
<h1 id="header">Header</h1>
<p><a></a> - number - boolean - null</p>
```
What i want in html format is that:
```
<h1 id="header">Header</h1>
<a></a>
<ul>
<li>number</li>
<li>boolean</li>
<li>null</li>
</ul>
```
the output in pdf will be this:
![image](https://user-images.githubusercontent.com/26152844/92361457-f7fcaa80-f120-11ea-8752-32fc8ab6ddc4.png)

**Comment by masterAllen** [comment]
sometimes i write md file like this:
```
# Header
## Header_1
<a id="fruits"><a/>
- apple
- banana
- orange

...

## Header_2
... some [fruits](#fruits) ... 
```
so I think this problem is worth being solved.

**Comment by tarleb** [comment]
This is expected behavior, the current Markdown parser requires a blank line before lists. Either enable the `lists_without_preceding_blankline` extension by calling pandoc with `-f markdown+lists_without_preceding_blankline`, or use CommonMark, where that behavior is the default (via `-f commonmark`).
