### ISSUE TITLE
Using `# Header with $n \not= 0$` leads to wrong LaTeX syntax which is not compatible with xelatex, so PDF is not produced using RStudio

### ISSUE THREAD

**Issue by N0rbert** [jgm/pandoc#6695]
This issue was discovered by using standard bookdown (RMarkdown) → PDF pipeline from RStudio.

The minimal reproducible example is below:

```
---
documentclass: article
output:
  bookdown::pdf_book:
    toc: false
    latex_engine: xelatex
---

# Heading with $n \not= 0$
```

Kniting the above document ends with error:

```
! Argument of \not has an extra }.
<inserted text> 
                \par 
l.78 ...lash not= 0}}\label{heading-with-n-not-0}}

Error: LaTeX failed to compile test.tex.
```

Full problematic part of the document is below:

```
\begin{document}

\hypertarget{heading-with-n-not-0}{%
\section{\texorpdfstring{Heading with \(n \not= 0\)}{Heading with n \textbackslash not= 0}}\label{heading-with-n-not-0}}

\end{document}
```

Notes:

1. disabling XeLaTeX eliminates the issue, but I need to use it to have support of Russian (Cyrillic) text.
1. this happens with latest RStudio, bookdown package, TeXLive 2015 (as in Ubuntu 16.04 LTS) and pandoc 2.10.1.

**Comment by N0rbert** [comment]
Usage of Pandoc 2.7.3 or 2.10.1 with XeLaTeX from TexLive-2020 does not produce errors.
So there is some incompatibility between pandoc and TeXLive-2015 which is a part of Ubuntu 16.04 LTS repository.

**Comment by jgm** [comment]
I don't think this is a problem with pandoc.  Pandoc's output works fine with recent versions of texlive. You're using texlive 2015, which is quite old.  That is very likely the issue.

I'm not sure what the specific issue is, but it may be a LaTeX package bug that has been fixed since 2015.

In any case, unless you have something specific to propose that pandoc could do, I think we should just close this.  (If you want to spend time hunting down the issue, maybe you can find some LaTeX code that would be compatible with the older texlive but still work with the newer and do the same thing....but I'm not going to spend time doing that.)

**Comment by N0rbert** [comment]
@jgm thank you for comprehensive answer. 

I did not plan to blame pandoc. Pandoc is great.

I did some further research and I see that Ubuntu 18.04 LTS with TexLive 2017 do not have this issue. So the problematic package is TexLive, not pandoc.
