### ISSUE TITLE
DocBook to PDF: spaces at the end of an <emphasis> tag are eaten

### ISSUE THREAD

**Issue by dourouc05** [jgm/pandoc#6719]
Pandoc version: 

```
PS C:\Program Files\Pandoc> pandoc -v
pandoc.exe 2.10.1
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: C:\Users\Thibaut\AppData\Roaming\pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Command line: 

```
pandoc -f docbook -t pdf C:\Users\Thibaut\Downloads\mwe.xml -o C:\Users\Thibaut\Downloads\mwe.pdf
```

Generated output: 
[mwe.pdf](https://github.com/jgm/pandoc/files/5327860/mwe.pdf)

![image](https://user-images.githubusercontent.com/285818/95089478-7b131f80-0724-11eb-9539-e3571acd5fd3.png)

Input file:
[mwe.xml.gz](https://github.com/jgm/pandoc/files/5327862/mwe.xml.gz)

The problem is that there is a missing space in the first emphasis, between "emphasized" and "text". Here is the relevant part of the DocBook file: 

```xml
<emphasis>emphasized </emphasis>text
```

When the space is outside <emphasis>, the document renders as expected. 

(This bug was discovered by Kornel Benko from the LyX project, the minimum working example is also due to him.)

**Comment by mb21** [comment]
jep, it's in the docbook reader: https://pandoc.org/try/?text=%3Cemphasis%3Eemphasized+%3C%2Femphasis%3Etext&from=docbook&to=native&standalone=0

**Comment by jgm** [comment]
In general, pandoc readers do some normalization so that spaces aren't found at the end or beginning of an Emph (or Strong or...)... This is because some ormats don't behave well with spaces at the beginning or end of emphasis.  The best way to do this is to use `extractSpaces` in Text.Pandoc.Shared, which actually moves the spaces. Example:
```
% pandoc -f html -t native
<em>hi </em>there
[Plain [Emph [Str "hi"],Space,Str "there"]]
```

Looks like the docbook reader removes the space but doesn't move it.  The solution is to use `extractSpaces` (see the HTML reader for an example) instead of `trimInlines` as the DocBook reader current does.

**Comment by jgm** [comment]
If someone takes this on, it might be good to check other readers too (starting with JATS); I suspect this issue extends more widely.
