### ISSUE TITLE
Support Unicode code

### ISSUE THREAD

**Issue by VincentTam** [jgm/pandoc#6778]
Cross-posted on https://tex.stackexchange.com/q/568030/126386.

![Julialang Unicode var name](https://i.stack.imgur.com/rwJSg.png)

How can I compile

~~~
```julia
🟡 = 2
```
~~~

into

```julia
🟡 = 2
```

by pandoc?

**Comment by jgm** [comment]
If this is a question, and not a bug report, it should be directed to the pandoc-discuss mailing list.

If it is a bug report, it should contain a reproducible example with pandoc version and exact command line.  You don't even say what format you're targeting, so it's very difficult to provide help.  I'd guess you're targeting PDF via latex and the problem is that you're using a monospace font without this glyph, but that's just a guess.

**Comment by VincentTam** [comment]
Thanks for response.  Linked problem resolved.
