### ISSUE TITLE
Rendered Diff from markdown to HTML or PDF.

### ISSUE THREAD

**Issue by countofsanfrancisco** [jgm/pandoc#6785]
Since I write a lot of technical publications which many of them are versioned, I think it would be great if we could support rendered diff.

For example, I would provide a previous version of a markdown and the latest version of a markdown as input into pandoc. Pandoc would do a diff on the raw MD. When generating HTML, the HTML would use strike-through for text changes and may be a yellow background highlight for text insertions in both body and tables too.

For figures, perhaps a simple border around the figure would just indicate the image changed is sufficient.

This would be a nice feature addition to pandoc.

**Comment by alerque** [comment]
I have [some tooling](https://github.com/sile-typesetter/casile/blob/master/bin/branch2criticmark.zsh) baked into [CaSILE](https://github.com/sile-typesetter/casile) that does this. The way I have it setup is for comparing Git branches with Markdown sources. I specify a base branch, and it diffs from that to the current branch. The changes are rendered first in universal diff format, but with word diff enabled (and optionally character diff) instead of line level diffs. Also notably the diff context value is cranked all the way up so the diff shows the full file contents. The diffs are then parsed and converted to [CriticMarkup](http://criticmarkup.com/), which can then be viewed in any Markdown editor that supports CriticMarkup highlighting or in my case, rendered to PDFs using SILE.

My tooling is pretty use case specific. It wouldn't bee too hard to adapt to your specific use case. It would be a lot more complicated to generalize to something that would work for other workflows and formats. I'm honestly not sure how well this would fit into Pandoc itself.

**Comment by sphuong1** [comment]
Oh!!! Thanks for that information. Let me investigate that. Do you know, by any chance, if those tooling can be easily used for github flavored markdown (gfm)?

**Comment by alerque** [comment]
GFM wouldn't be a problem. It does break in some situations because it's just blindly cramming CriticMarkup syntax at a character diff level. For example changing a level 2 header to level 3, the output is a level 2 header with a literal `#` character marked up as being added to the heading content.

A smarter way to do this would be to write something to iterate two Pandoc AST trees and output a new tree with new child nodes for the diff markup, but that would be a lot more complicated to write than the pre-processing method I used — which was good enough for the sorts of copy-editing I was trying to visualize.

**Comment by jgm** [comment]
For the commonmark spec I use https://tools.ietf.org/tools/rfcdiff/ which works well (even though it's not an RFC).
You might try that.
Example of its output: https://spec.commonmark.org/0.29/changes.html

**Comment by tarleb** [comment]
It seems that sufficient alternative solutions exist, and that it's not clear if this is in scope for pandoc, so I'm closing this for now.

**Comment by cknoll** [comment]
For those like me comming accross this issue years after closing: I found pandiff (<https://github.com/davidar/pandiff>) to exactly fit my needs.
