### ISSUE TITLE
docx track-changes should enable accepting/rejecting all changes

### ISSUE THREAD

**Issue by chaoflow** [jgm/pandoc#6801]
The documentation for docx ``--track-changes`` states:

"accept (the default), inserts all insertions, and ignores all deletions. reject inserts all deletions and ignores insertions. Both accept and reject ignore comments. all puts in insertions, deletions, and comments, wrapped in spans ..."

There should be a way to accept all changes, not just insertions, and another to reject all changes, not just deletions.

**Comment by jgm** [comment]
Pinging @jkr since I don't know much about this.

**Comment by jkr** [comment]
Sorry -- this was just unclear documentation. `accept` *does* accept all changes, since it's puts the insertions in and takes the deletions out (i.e. it "ignores" the spans with deletions). `reject` leaves it as it was before by not putting the insertion spans in (i.e., ignoring them) and putting the deletion spans back in. So `accept` and `reject` do what you want, but it could definitely be phrased better.

**Comment by jkr** [comment]
Suggestions for clear, terse phrasing welcome.

**Comment by jgm** [comment]
I've pushed a commit that I think is clearer. If you want to tweak it, let me know or just push a new commit.

**Comment by chaoflow** [comment]
Thank you for the clarification! I missed the notifications for your messages.
