### ISSUE TITLE
[Enhancement proposal] -o json should generate pandocstdout.json

### ISSUE THREAD

**Issue by sebi5361** [jgm/pandoc#6805]
Often my process of working with pandoc goes like this:
`... | pandoc -f markdown -t json`
...than:
`... | pandoc -f markdown -o myfile.json`
...by just recalling the previous command and making the proper adjustments.

But often I type this command instead:
`... | pandoc -f markdown -o json`
...that displays a warning and generates a no-extension file named `json` in `html` format.

I believe not so many people want a file named `json` with `html` in it, am I right?

Wouldn't it be handy to get a `pandocstdout.json` file instead?

pandoc `-o` argument would just have to react on special keywords such as `json`, `native`, etc.

**Comment by alerque** [comment]
Please no! I'd much rather my CLI commands do what I tell them even if I tell them the wrong thing. Automagically guessing when I made a mistake and doing something else instead is confusing and even maddening as an end user. Even when it works it only re-enforces misconceptions and bad expectations about what input the CLI expects and what it should do.

If I ad an `-o`/`--output` flag to a CLI and specify a filename, it shouldn't automatically use a different filename instead just because it things the filename I gave looks like a format instead.

**Comment by sebi5361** [comment]
To every rule there can be exceptions 😉

**Comment by sebi5361** [comment]
Eg. `$@cosx$` is considered to be `AsciiMath` by some parsers as not that many Latex equations start with an `@`...

**Comment by jgm** [comment]
I'd rather not do this.  Pandoc follows a policy of only creating files explicitly specified by the user.

**Comment by sebi5361** [comment]
It was worth asking to get your opinions.
Thanks🙏
