### ISSUE TITLE
Some issues with citations in footnotes

### ISSUE THREAD

**Issue by denismaier** [jgm/pandoc#6813]
This here gives me wrong results with the latest pandoc version:

```
---
references:
- type: book
  id: doeA
  author:
  - family: Doe
    given: John
  title: 'Title A'
- type: book
  id: doeB
  author:
  - family: Doe
    given: John
  title: 'Title B'
---

[^1] [^2] [^3] [^4]


[^1]: @doeA Some text in between. Also @doeB.

[^2]: @doeB

[^3]: @doeB

[^4]: @doeA.
```

This gives me these footnotes:

```
[^1]: 1 Some text in between. Also Doe, *Title B*, n.d.

[^2]: Doe,

[^3]: Doe,

[^4]: 1.  
```

Couple of issues: 
1. There's a incorrect ibid in the second footnote. I think here we would want the short form.
2. The ibid in footnote 3 is correct, but note the comma.
3. The period in footnote 4 seems to start an enumeration.
4. Footnote 1 shows that the enumeration is actually started even without a period. (Is the `@` starting a list here?)

**Comment by jgm** [comment]
Oh, and yes, I see the point about the ibid in n. 2.
I guess that is a citeproc library issue.

**Comment by denismaier** [comment]
> What style are you using?

Chicago-note-bibliography.csl

**Comment by jgm** [comment]
OK, with the latest change I'm getting:
```
[1] Doe, Title A. Some text in between. Also Doe, Title B.

[2] Doe, ibid.

[3] Doe, ibid.

[4] Doe, Title A.
```
Everything okay now I think, except the ibid in n. 2.

**Comment by jgm** [comment]
Actually I think this is also a pandoc issue. We need to recognize when these citations occur inside a note and set citationNoteNum accordingly.

**Comment by jgm** [comment]
Actually I think we conform to the CSL spec: "the current cite is the first cite in the citation, and the previous citation consists of a single cite referencing the same item."

Note that you have two citations in the first note.  So the "previous citation" is to @doeB.

I know, it's a bit unexpected, because if you'd done a regular note citation
`[@doeA; @doeB]` then this whole thing wolud be considered *one* citation and the ibid would not be triggered.

But this is all a result of in-text citations not being really integrated into the spec.

**Comment by denismaier** [comment]
Ok. Looks like we need to amend the spec here. The ibid in note 2 is not wanted. I think citeproc-js suppresses that already. See https://github.com/citation-style-language/documentation/issues/121

**Comment by jgm** [comment]
I think I can get that behavior by modifying citeproc.

**Comment by jgm** [comment]
OK, I've fixed it in citeproc.
