### ISSUE TITLE
--self-contained unfriendly towards --mathjax

### ISSUE THREAD

**Issue by lrem** [jgm/pandoc#682]
I'd like to distribute my notes as standalone html files. They contain both maths to be rendered with mathjax and figures.

The problem is that enabling both `--self-contained` and `--mathjax` ends with error message:

```
pandoc: user error (https not supported)
```

But even if I provide an url without https, mathjax fails to load any of its assets.

**Comment by gfelbing** [comment]
I think there could be a self-contained document with mathjax:

What about letting mathjax render the math-blocks (i.e. as svg) when the document is created and embed only the rendered blocks, not mathjax itself?

@balachia Putting your script into an js-file and pass it with --mathjax=dynoload.js works, not nice but at least it works...

**Comment by jgm** [comment]
Kyle Barron <notifications@github.com> writes:

> @jgm is it still impossible with the current state of Pandoc for `--self-contained` to not work with `--mathjax`?

Nothing has changed in that respect.  The problem is that
mathjax does some dynamic loading of modules.

**Comment by kylebarron** [comment]
Yes, but I think what @jaredlander and I desire is to be permitted to have everything _but_ Mathjax be self-contained. 

For example, I want to distribute notes with image attachments that were created on a private server. Having the images encoded in the HTML document is great because I can't expect the recipients to have access to that private server, but I can expect them to have access to the internet and Cloudflare's Mathjax CDN. 

So it would be ideal for images to be Base64 encoded and for CSS stylesheets included, but for the Mathjax CDN external linking to still be there.

**Comment by jaredlander** [comment]
I do most of my pandoc conversions using rmarkdown now. The way they handle this is they preprocess the document (not with pandoc I believe) to URI encode and embed everything (pictures, css, JavaScript) then does a second pass with pandoc to convert to the final format. Would be awesome to do a similar two-pass with pandoc.

**Comment by jgm** [comment]
Probably best not to comment on closed issues.
If you want to propose a specific change, then a new issue would be appropriate.  Or better, bring it up on pandoc-discuss first.

**Comment by chtenb** [comment]
For me this just works. Is this issue fixed in the meantime? Perhaps it would be good to mention that here.

**Comment by jgm** [comment]
Yes, works for me too. Something changed in mathjax, perhaps?

**Comment by jgm** [comment]
Let me revise that: the basic formula structuring works, but the fonts aren't right, because mathjax tries to load them dynamically.
