### ISSUE TITLE
How to use the ctl extension with docx to solve the ctl problem and more

### ISSUE THREAD

**Issue by vivian-ji** [jgm/pandoc#6820]
Hi, I have encountered the same problems as other users with strange conversions from docx  due to _ctl_ ("_complex text layout_") (rif. #6514, but also issues as: #6501, #6452 and #6419).

I tried the latest official version from brew (version 2.10.1):
```
brew install pandoc
pandoc -f docx+styles-ctl -t html example.docx -o example.html

Result: unknown extension: ctl
```

I thought that the changes of @lierdakil to #6514 hadn't been published yet, so I tried both via git and via zip.

From repository of @lierdakil (version 2.10):
```
git clone -b docx-ctl-flag https://github.com/lierdakil/pandoc
cd pandoc
stack setup
stack install
/Users/vivian/.local/bin/pandoc -f docx+styles-ctl -t html example.docx -o example.html

Result: unknown extension: ctl
```

From [zip](https://github.com/lierdakil/pandoc/archive/docx-ctl-flag.zip) (version 2.10):
```
unzip pandoc-docx-ctl-flag.zip
cd pandoc-docx-ctl-flag
stack setup
stack install
/Users/vivian/.local/bin/pandoc -f docx+styles-ctl -t html example.docx -o example.html

Result: unknown extension: ctl
```

How can I do? Am I wrong something?
When will this extension be included in the official version?

Thanks

**Comment by mb21** [comment]
Sounds like you're referring to [this comment in this pull?](https://github.com/jgm/pandoc/issues/6514#issuecomment-656307712)
That pull request has not been merged... but you can try the link in that comment: https://github.com/lierdakil/pandoc/archive/docx-ctl-flag.zip

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
