### ISSUE TITLE
latex_macros: poor interaction with emphasis

### ISSUE THREAD

**Issue by hseg** [jgm/pandoc#6848]
```
pandoc 2.11.1.1
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,
citeproc 0.1.1.1, ipynb 0.1.0.1
```

Consider the following markdown snippet:
```
\newcommand{\highlight}[1]{\textcolor{red}{#1}}

This should be highlighted: \highlight{hello world!}

This as well: \highlight{hello *world*!}

This should appear: \highlight{hello _world_!}
```

With no flags, a markdown-to-pdf conversion should render all three highlighted ```hello world``` statements, with ```world``` getting varying levels of emphasis. Instead, ```*``` passes through without applying any formatting and ```_``` cancels the entire macro.

Probably the correct answer for this usecase is to build a little Lua filter for coloring. The bug remains, regardless.

**Comment by jgm** [comment]
That's because these are bits of raw LaTeX; the interiors are not interpreted as Markdown, and `_` by itself is invalid in that context in LaTeX.  So, not a bug.  I agree, a lua filter is what you want.  An alternative would be to create LaTeX commands to start and stop highlighting:
`\startHighlighting hello _world_!\stopHighlighting`
With this, the `hello _world_!` won't be interpreted as part of the raw TeX.
