### ISSUE TITLE
Unlinked TOC with commonmark[_x]?

### ISSUE THREAD

**Issue by jaybe-jekyll** [jgm/pandoc#6863]
I noticed that using `-f commonmark_x` (or `commonmark`) with --toc will produce a table of contents however the contents are not hyperlinked to their sections.

Is this the expected behavior?

I experimented and got hyperlinks by adding `+gfm_auto_identifiers`.

**Comment by mb21** [comment]
What output format? Have you tried with the latest pandoc version?

**Comment by jaybe-jekyll** [comment]
Out format is html.

Latest pandoc release.

**Comment by tarleb** [comment]
Pandoc can only link to elements of which it knows the ID. This is why you got the expected result when using `+gfm_auto_identifiers`. You could also manually add an id to each header: `## some header {#my-id}`.

So yes, this is basically intended behavior. Maybe it would be worth to mention the above in the manual?

**Comment by jaybe-jekyll** [comment]
Should not `auto_identifiers` (enabled with `commonmark_x`) provide for this?

```sh
Extension: auto_identifiers

A heading without an explicitly specified identifier will be automatically assigned a unique identifier based on the heading text.
```

**Comment by tarleb** [comment]
Oh, right. That's weird then.

**Comment by jgm** [comment]
OK, I see the issue.
`commonmark_x` includes `auto_identifiers`.  But `auto_identifiers` doesn't actually have any effect on the commonmark reader; only `gfm_auto_identifiers` triggers the autoIdentifierSpec. This is correct, I think, because the autoIdentifierSpec from commonmark implements the gfm style of identifiers.  But we should include `gfm_auto_identifiers`, rather than `auto_identifiers`, in `commonmark_x`.

**Comment by jaybe-jekyll** [comment]
Thank you!
