### ISSUE TITLE
Some EPUB-settings lead to invalid EPUB-containers (X issues)

### ISSUE THREAD

**Issue by abrey66** [jgm/pandoc#6931]
## BUGREPORT: 

pandoc.exe 2.11.1.1
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3, citeproc 0.1.1.1, ipynb 0.1

## input: 
```
    An E-book with YAML-definitions, large markdown-file and customized EPUB.CSS
```
## output: 
```
    The E-book is rejected by validators AND sites for self-publishers (like [Tolino Media](https://www.tolino-media.de/))
```

## Number 01:
```
    CALIBRE-validator: Properties should be known (listed in CSS3 specification) or be a vendor-prefixed property.

/* Set the minimum amount of lines to show up on a separate page. (There is not much support for this at the moment.)
*/
p,
blockquote {
  orphans: 2;
  widows: 2;
  margin-block-start: 0rem; **UNKNOWN**
  margin-block-end: 1rem; **UNKNOWN**
}
```

Workaround
```
    deleted the definition; should be omitted in the default epub.css of pandoc
```

## Number 02:
```
    CALIBRE-validator: RULES are empty

h1.title { }
h2.author { }
h3.date { }
```

Workaround
```
    deleted the rules; pandoc should check (and remove empty rules).
```

## Number 03:
```
    CALIBRE-validator: WARNING - use of !important

@media screen { /* Workaround for iBooks issue; see #6242 */
  .sourceCode {
    overflow: visible !important;
    white-space: pre-wrap !important;
  }
```

Workaround
```
    I accept the warning; is this rule still necessary?
```

## Number 04:
```
    CALIBRE-validator: ILLEGAL ID-Format (non-ascii characters)

<section id="ein-kompendium-der-philosophie-in-fünf-bänden" class="level2" data-number="1.2">
```

Workaround
```
    manual definition of EACH (!tedious) section. SHOULD BE FIXED by pandoc.
    QUICK-SOLUTION:  I suggest replacement of each non-ascii char by '-'
```

Thanks for consideration. Have a good day! 

Andreas (German IT-guy)

**Comment by jgm** [comment]
On 01:  Odd, this is NOT part of the default epub css pandoc uses.  I just produced an epub using pandoc it and did not contain these rules. Are you sure you're not using a custom CSS? Here it would be helpful if you'd give us a *minimal* way to produce what you're seeing -- an input as small as possible and exact command line used, removing everything unnecessary.

On 02:  empty rules are harmless, no?  They are not invalid. (We have left these in the default CSS so that authors can see how to customize.)

On 03:  I believe there was a reason for the `!important`, but in any case, it's not invalid.

On 04: are you producing epub3 or epub2?  In epub3 (which is pandoc's default if you just say `-t epub`) I believe that non-ascii characters are allowed in the ids.  (Contents in epub3 are xhtml5, which allows virtually any character in an id attribute.) If you think I'm mistaken about this, please link to the relevant spec.  It may be that Calibre's validation is unduly restrictive. Note that `epubcheck` does not complain about these characters.

**Comment by abrey66** [comment]
Good morning jgm, 

thx for your quick replies. Actually in point 04 you are absolutely right - I believed -t epub means epub V 2.0 - I thought I explicetly have to indicate -t epub3 to create a V 3.x container. If you are not digging deep (into the opf-file) it is quite hard to see, what version was created. 

I have a question: In my publishing activities there are more issues / comments / suggestions for improvement comming up. Shall I close this bundle-ticket and open single specific issues? Or do you prefer if I append this one? 

So far: 
01 - correct; suggestion: improve CSS-management according to output-type + default / customized.
02 - I disagree on that one.
03 - ok - well, just another warning.
04 - ok - explained here.

Have a good day!

**Comment by jgm** [comment]
separate reports for separate issues are easier to deal with.

**Comment by jgm** [comment]
looks like this can now be closed?

**Comment by abrey66** [comment]
sure - let's close it. seperate reports are easier, I agree.
