### ISSUE TITLE
Tag release 2.11.4

### ISSUE THREAD

**Issue by hseg** [jgm/pandoc#7032]
c83811773e59d78b45ac5a39d8ac1e4f3c58682d forgot to tag with version 2.11.4, breaking my packaging script.
To prevent such issues in the future, might I recommend adding this to the releng checklist?

**Comment by tarleb** [comment]
Pandoc 2.11.4 has not been released yet, so it can't be tagged.
As I understand it, versions in the cabal file will be bumped *in preparation* of a new release, but there is no defined process for when this happens. No assumption should follow from it, and it'll probably be best to update the packaging script.

**Comment by hseg** [comment]
Understood. Will freeze the pckge at 2.11.3.2 until the release is cut.
Am surprised changes to cabal package versions do not correspond to releases, but that's your prerogative.

On January 14, 2021 10:43:52 PM GMT+02:00, Albert Krewinkel <notifications@github.com> wrote:
>Closed #7032.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jgm/pandoc/issues/7032#event-4208132924
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tarleb** [comment]
> Am surprised changes to cabal package versions do not correspond to releases

To be honest, I thought this would be a common practice. I frequently bump the version of my own tools during development to avoid version confusions when testing. To me, everything that happens between tagged commits is basically the wild west (version wise). Is it common to bump the version only shortly before the release?

**Comment by jgm** [comment]
I bumped the version because there was an API change.  I don't see any reason to wait to a release to do this.  People shouldn't be treating the dev code on master as if it's released code.

**Comment by alerque** [comment]
> Is it common to bump the version only shortly before the release?

Yes it's pretty common, but hardly universal. Lots of tooling even exist to bump version numbers as the commit that gets tagged as a release. This is common practice in Javascript, Rust, and a few other language ecosystems. Some of it is language ecosystem expectations, some of it is preference.

My preference is to have this automated so that the build process looks at the source repository and determins whether the build is a tagged release (exactly on a tag) in which case it uses the source code or git tag's declared version, otherwise it uses the last tagged version plus an incrementer `-r{N}-g{SHA}` where N is the number of commits since the last tagged release and SHA is of course the commit being built from.

I don't know if this is possible in `cabal` / Haskell land, just throwing that out there. But even if that level of automation isn't possible to completely remove ambiguity, not bumping the version number until part of the actual release process would be my expectation.

From observation less that experience, I think the C/C++ software world frequently does what you are talking about bumping the version in source directly following a release to bump the version (sometimes with an extra `-dev` suffix of some sort), then leave it that way through the whole development and release cycle.
