### ISSUE TITLE
File extension '.mkdn' not recognized as alias for markdown

### ISSUE THREAD

**Issue by Karl-D-Asmussen** [jgm/pandoc#7034]
Having just upgraded from an earlier version (probably 2.8, lost to an OS crash) I found that the command line utility for pandoc no longer recognizes files with the extension `.mkdn` as markdown. This is a less common extension than '.md' or '.markdown' but it is strange that the functionality regressed between versions.

Using pandoc 2.11.3.2

**Comment by tarleb** [comment]
With version 2.8 a new warning was introduced that notifies users when the input format cannot not be deduced from the file name.

> Add `CouldNotDeduceFormat` constructor to `LogMessage` [API change].
> Issue this warning when we're falling back to markdown or
> html because we don't recognize the extension of the input or
> output files.

Files with extension `.mkdn` have never been identified as Markdown input, but Markdown input is what is assumed by default. It just appeared as if pandoc knew what to do, because the default was correct and it didn't raise a warning.

So this is not a regression but a feature request.
