### ISSUE TITLE
Role and usage of "data-include"

### ISSUE THREAD

**Issue by aubertc** [jgm/pandoc#7046]
The following markdown file

~~~
Here is some code:

```{.md include=test_pandoc.md}
```
~~~

will produce, when processed with

```
pandoc test.md -o test.html
```

```html
<p>Here is some code:</p>
<div class="sourceCode" id="cb1" data-include="test_pandoc.md"><pre class="sourceCode md"><code class="sourceCode markdown"></code></pre></div>
```

what is the role / function of this "data-include"? I couldn't find it anywhere in the documentation or the google group.

I suspect this interfere with the filter `pandoc-include-code` (cf. https://github.com/owickstrom/pandoc-include-code/issues/38 ) but don't really understand the purpose of that feature.

```
pandoc -v
pandoc 2.11.3.2
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.3, ipynb 0.1.0.1
```

**Comment by jgm** [comment]
When rendering HTML, when an element has attributes that aren't official HTML5 attributes (such as `include`), we add `data-` because `data-` + anything is a valid HTML5 custom attribute.

A filter will be looking at the AST, not the HTML.  The AST will include the attribute under the original name `include`, so it shouldn't interfere.

**Comment by jgm** [comment]
Please use the group for questions, by the way.
