### ISSUE TITLE
mmd -> tex: wrong translation of image to \includegraphics

### ISSUE THREAD

**Issue by TS-Tobias** [jgm/pandoc#7080]
When converting images from `markdown` or `markdown_mmd` to latex using

`pandoc --biblatex -o output.tex source.md`

```
![][image]
[image]: image.png {width=100 height=150}
```

```
![][image]
[image]: image.png width=100px height=150px
```

images get translated to 
`\includegraphics{image.png width=100px height=150px}`.

**Expected result** 
`\includegraphics[width=100px, height=150px]{image.png }`.

Version: `pandoc 2.11.4`

**Comment by mb21** [comment]
Could you say why you'd prefer that syntax? I assume both work using pdflatex..?

**Comment by TS-Tobias** [comment]
I might be wrong, but as far as I know, pdflatex does not support this.

The compiler gives me the following error:
`LaTeX Error: Unknown graphics extension: .png width=100px height=150px.`

[Example](https://tex.stackexchange.com/questions/234441/latex-includegraphics-width-and-height/234454)

**Comment by jgm** [comment]
The problem is with your markdown syntax. You need a blank line before the reference link definition.
```
% pandoc -t latex
![][image]

[image]: image.png {width=100 height=150}
^D
\includegraphics[width=1.04167in,height=1.5625in]{image.png}
```

**Comment by jgm** [comment]
Closing since this isn't a bug.

**Comment by TS-Tobias** [comment]
@jgm 
I just put definition and usage together for the report above. 
In my tests, the definition and usage were separated by multiple blank lines and other text in between.

I just tried it again by adding additional empty lines before, after and in between with the same result as described before.

**Comment by jgm** [comment]
OK, well in this test you aren't specifying `-f markdown_mmd`, so that means you're using pandoc syntax, and for that you need braces around the attributes as in my example.

You need the `{..}` as in my example, above, or this isn't recognized as attributes but considered to be part of the image path.

But it still doesn't work with `-f markdown_mmd`.  This may be an issue with our handling of the `mmd_link_attributes` extension. It appears that pandoc expects a title; this will work:
```
[image]: image.png  "" width=100px height=150px
```
If multimarkdown doesn't require that (I haven't checked), we can regard that as a problem with the markdown reader with the `mmd_link_attributes` extension. It has nothing to do with latex output, though; it's a parser issue.

The markdown reader allows spaces in the image path; so it keeps reading image path til it hits a title (double quotes) or an attribute block (looking for `{`).

**Comment by TS-Tobias** [comment]
You are right, this does the trick.

`[image]: image.png "" width=100px height=150px`

with `pandoc --biblatex -f markdown_mmd -o output.tex input.md`.

**Comment by jgm** [comment]
I've fixed it so the title shouldn't be needed in the future.
