### ISSUE TITLE
LaTeX reader - verbatim '&' in tabular environment

### ISSUE THREAD

**Issue by kappat** [jgm/pandoc#7129]
It appears that literal ampersands e.g. `\verb|&|` in `tabular` environment cause the LaTeX reader to fail in parsing number of columns.

- the pandoc version (check using pandoc -v)
```
pandoc 2.11.4
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.7, ipynb 0.1.0.1
```
- the exact command line used
`pandoc -f latex -t markdown reproducer.tex`
- the exact input used
```
\documentclass{article}
\begin{document}
\begin{tabular}{ll} \hline
  FOO & BAR         \\ \hline
  foo & \verb|bar|  \\ \hline
\end{tabular}
\begin{tabular}{ll} \hline
  FOO & BAR         \\ \hline
  foo & \verb|b&r|  \\ \hline
\end{tabular}
\end{document}
```
- the output received
```
  FOO   BAR
  ----- -------
  foo   `bar`

::: {.tabular}
ll FOO & BAR\
foo & `b&r`\
:::
```
- the output you expected instead
```
  FOO   BAR
  ----- -------
  foo   `bar`

  FOO   BAR
  ----- -------
  foo   `b&r`
```
(GitHub doesn't render it as a table without separating columns by pipes, but it's not the point of this report.)

**Comment by jgm** [comment]
What makes this difficult is that we support the `>{$}r<{$}` syntax for adding a token to the begin and/or end of cells in a table column.  Because we support that, we parse the table contents as raw tokens, and then reparse them after adding the extra tokens.  Parsing as raw tokens, we're not sensitive other pieces of syntax that can include `&`.  This is all a bit of a mess; I would like a better way of handling e.g. `>{$}r`.

**Comment by kappat** [comment]
Thank you very much not only for the fix but also explaining the code.
