### ISSUE TITLE
pandoc-2.12 test suite failures

### ISSUE THREAD

**Issue by peti** [jgm/pandoc#7163]
I have a whole lot of test suite errors that look genuine. Check out https://hydra.nixos.org/build/139219761 for the complete build log. Here is a snippet that seems relevant, but there is more:

~~~
    creole
      reader:                                                        OK (0.07s)
    custom writer
      basic:                                                         Could not find data file /nix/store/ncx50ics911dgshmwmh1lfyjf3dbmxdp-pandoc-2.12-data/share/ghc-8.10.4/x86_64-linux-ghc-8.10.4/pandoc-2.12/data/pandoc.lua
FAIL (0.17s)
        user error (Pandoc failed with error code ExitFailure 97)
      tables:                                                        Could not find data file /nix/store/ncx50ics911dgshmwmh1lfyjf3dbmxdp-pandoc-2.12-data/share/ghc-8.10.4/x86_64-linux-ghc-8.10.4/pandoc-2.12/data/pandoc.lua
FAIL (0.06s)
        user error (Pandoc failed with error code ExitFailure 97)
~~~

**Comment by jgm** [comment]
Most of those are due to the changes in texmath 0.12.2, released after pandoc 2.12 but still in its cabal bounds. I suppose I could require specific versions of texmath rather than ranges in pandoc to avoid this happening in the future.

The other issue, the one you quote above, I'm not so sure about.  We usually test with `embed_data_files` set to True, and you have it set to False, so this may indicate a gap in our testing.  I'm hoping @tarleb may have some ideas about the lua data file issue ; I think this has to do with the following noted in the changelog:

```
    + Always load built-in Lua scripts from default data-dir (Albert
      Krewinkel).  The Lua modules `pandoc` and `pandoc.List` are now always
      loaded from the system's default data directory. Loading from a      
      different directory by overriding the default path, e.g. via       
      `--data-dir`, is no longer supported to avoid unexpected behavior
      and to address security concerns.    
```

**Comment by jgm** [comment]
@tarleb I think I see what is happening with pandoc.lua.

The custom writer does some initialization which loads the default "pandoc.lua" module.

`loadDefaultModule` is defined in T.P.Lua.PandocLua.  Here's the documentation comment:
``` hs
-- | Load a pure Lua module included with pandoc. Leaves the result on
-- the stack and returns @NumResults 1@.
--
-- The script is loaded from the default data directory. We do not load
-- from data directories supplied via command line, as this could cause
-- scripts to be executed even though they had not been passed explicitly.
loadDefaultModule :: String -> PandocLua NumResults
```
(This is indeed the change note above.)

So why does this cause a problem with the test suite?  Well, the test suite is running an executable which has not yet been installed, so the data files aren't yet in the default data directory.  To get around that, we specify the `data` subdirectory of the source directory as the user data directory using the `--data` option.  But this new change to `loadDefaultModule` means that this is ignored when it comes to loading `pandoc.lua`.

**Comment by jgm** [comment]
My guess is that this isn't caught in local testing or CI because we're using `embed_data_files`.

**Comment by jgm** [comment]
One solution would be to ensure that pandoc.lua is baked into the binary, and not load it from a data file at all.

**Comment by jgm** [comment]
Sure enough, I get these failures locally if I compile without the `embed_data_files` flag. I'll add a CI build that reproduces this.

**Comment by jgm** [comment]
But how is it that the other Lua module tests are passing?

**Comment by jgm** [comment]
I have a fix....

**Comment by jgm** [comment]
It turns out there is a nice alternative to setting `--data` (probably introduced after our test suite was originally written).  Cabal seems to set `pandoc_data` environment variable to the source directory, and this causes `getDataFilename` etc. to resolve differently when the executable is run.  When spawning a new process to test the executable, we did not set this environment variable.  That's why it worked fine in the lua module tests, but not in the custom writer test.  Simple fix is to preserve the environment variable `pandoc_data` when testing the executable.

**Comment by tarleb** [comment]
Thank you, that's a beautiful solution!
