### ISSUE TITLE
Load custom lua packages in filters

### ISSUE THREAD

**Issue by THS-on** [jgm/pandoc#7194]
https://github.com/jgm/pandoc/pull/7051 changed that lua scripts cannot be included from the data-dir specified location.

This breaks our current setup where we use custom util packages that are shared between our filters. (Tested with pandoc 2.13)
We could overwrite `package.path` in each our filters manually but I think that is not a good way to do this.

I completely understand the reasoning behind that change, but is there a way to still allow a filter to require packages from this location if it is not in the `pandoc` namespace? If this is not possible what is the best way to solve this?

## Example
Create one folder for filters and one for content.
```
mkdir filters
mkdir content
```
Create `test.md` in content
```
touch content/test.md
```
Create `filters/utils.lua` as our custom util package with the content
```
utils = {
    hello_world = "Hello world"
}
```
Create `filters/sample-filter.lua` with the content
```
require "filters/utils"
print(utils.hello_world)
```
In pandoc 2.11.4 the following worked.
```
$ cd content
$ pandoc --data-dir "../" --lua-filter sample-filter.lua  test.md
Hello world

```
But newer versions return the following
```
Error running filter ../filters/sample-filter.lua:
../filters/sample-filter.lua:2: module 'filters/utils' not found:
	filters/utilsis not one of pandoc's default packages
	no field package.preload['filters/utils']
	no file '/usr/share/lua/5.3/filters/utils.lua'
	no file '/usr/share/lua/5.3/filters/utils/init.lua'
	no file '/usr/lib/lua/5.3/filters/utils.lua'
	no file '/usr/lib/lua/5.3/filters/utils/init.lua'
	no file './filters/utils.lua'
	no file './filters/utils/init.lua'
	no file '/usr/lib/lua/5.3/filters/utils.so'
	no file '/usr/lib/lua/5.3/loadall.so'
	no file './filters/utils.so'
stack traceback:
	[C]: in function 'require'
	../filters/sample-filter.lua:2: in main chunk
```

**Comment by alerque** [comment]
It looks to me like you've just hit one of Lua's little foibles. It's designed to be embedded and it expects you to bring your own batteries. I understand how this removal in Pandoc can look like a regression, but I think it's for the best and very much in line with standard Lua practice.

If you inspect the `package.path` from one of your scripts you'll see the two things Lua knows about packages out of the box are the system paths and relative paths. This is documented in the Pandoc manual as well.

My suggestion is you actually make use of relative paths the way Lua expects them: deeper than your CWD. The issue with the example you just cited is your use of code outside of what Pandoc (& Lua) know of as your current working directory (which can be inspected with `pandoc.system.get_working_directory()`).

Instead of:

```
project
└─ filters
│ └─ sample-filter.lua
└─ content
  └─ test.md
```

If you lay out your projects like this:

```
project
└─ filters
│ └─ sample-filter.lua
└ test.md
```

You won't have this trouble.

Alternatively of course package your common filter sets as a Lua Rock and install them to your system! You can do this privately without publishing the Rock of course.

As a final alternative, extend the `package.path` with a location to your common stash of code. Yes this means having one line of code at the top of each filter that needs to `require()` something from your custom repository, but if you don't put that repository on your system and it isn't nested in a standard location relative to your project then I don't think Lua should find it by default without intervention. Extending the package path is the proper intervention. I know you said this is "undesirable", but I think it's the most explicit, portable, safe, and hygienic way to go if the first two are objectionable.

**Comment by THS-on** [comment]
@alerque thanks for the quick answer and your input.
Changing the project layout is not really an option because we have currently a lot of subfolders of small projects that share common filters, templates etc.  
Packaging the util packages would defeat that they are all bundled in our git repository, but if they are mostly stable this could be an option.

I don't have much experience with Lua outside of writing pandoc filters and thought extending `package.path`  was not something you would normally do.  Adding `package.path = '../filters/?.lua;' .. package.path` does work. 
Is there a way to get the specified `data-dir` in the lua-filter to mimic the old behavior or are using relative paths a better idea?

**Comment by alerque** [comment]
> I don't have much experience with Lua outside of writing pandoc filters and thought extending `package.path` was not something you would normally do.

A forgivable assumption. In most languages you wouldn't want to do that, but in Lua it is kind of expected.

> Adding `package.path = '../filters/?.lua;' .. package.path` does work.

Great. But wouldn't that be a subtle change from the examples you wanted to have work? You may want to use `package.path = '../?.lua;' .. package.path` instead if you want "filters/" to be part of your require statement. Of course that may not be what you want—your on the right track though.

> Is there a way to get the specified `data-dir` in the lua-filter to mimic the old behavior or are using relative paths a better idea?

Good question. I didn't see one right off. You could use some debugging data to find the location of the current filter (which Pandoc *would* have found for you), but I don't see anything in the run time environment you can query to get Pandoc's current data dir. **That might be reasonable feature request to come out of this issue.*

Also note you [can put an `init.lua` file in your data dir](https://pandoc.org/lua-filters.html#lua-interpreter-initialization) for things that you want to make available to your other filters. That might be the place to load up your common functions and expose them without adding package.path to every filter.

**Comment by THS-on** [comment]
Adding a `init.lua` with
```
package.path = '../?.lua;' .. package.path
```
works for now. 

> *That might be reasonable feature request to come out of this issue.*
Should I then close this issue and open a new one for querying pandoc command line arguments in lua filters?

**Comment by alerque** [comment]
No I think keeping this issue is fine to track the feature request and the discussion is relevant. Somebody like @tarleb might come along with more knowledge and have a better solution anyway given the background with the exact problem.

**Comment by tarleb** [comment]
I concur with what's been said by @alerque. As for the data dir: we have `PANDOC_STATE.user_data_dir`, does that do what you need?

**Comment by alerque** [comment]
@THS-on It does look that value has the path you need if you want it [docs here](https://pandoc.org/lua-filters.html#type-commonstate):

```console
$ pandoc --data-dir /tmp/foo <(true) -f markdown -L <(echo 'print(PANDOC_STATE.user_data_dir)')
/tmp/foo
``

I see in the [related docs docs](https://pandoc.org/lua-filters.html#global-variables) that there is also a `PANDOC_SCRIPT_FILE` that:

> The name used to involve the filter. This value can be used to find files relative to the script file. This variable is also set in custom writers.

One of those variables to construct a `package.path` *or* using `init.lua` are probably the definitive solution.

**Comment by THS-on** [comment]
> we have `PANDOC_STATE.user_data_dir`, does that do what you need?

Yes, this should work nicely with the `init.lua` method. Is the content of `PANDOC_STATE` somewhere documented?

**Comment by alerque** [comment]
@THS-on Docs link is in my comment above. Probably just passed in transit ;-)

**Comment by THS-on** [comment]
@alerque Yes I saw your comment after I posted mine.

Thanks @alerque  and @tarleb for helping me to solve this issue.  
My final solution is to add a `init.lua` in the `data-dir` with the content
```
package.path = PANDOC_STATE.user_data_dir .. '/?.lua;' .. package.path
```

This adds the old functionality back and seems to be a viable solution.
