### ISSUE TITLE
Can´t update pandoc 2.11 to 2.13 on Windows 10

### ISSUE THREAD

**Issue by daacosta** [jgm/pandoc#7269]
I have been trying to update pandoc to the newer version 2.13 by running the windows executable installer with no luck.  When I do in the powershell terminal

pandoc -v

It gives:

pandoc.exe 2.11
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.2
Default user data directory: C:\Users\USUARIO\AppData\Roaming\pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

I have tried removing all pandoc files on my laptop and reinstalling but haven´t been able to fix the situation...  What can I do please?

**Comment by mb21** [comment]
Be sure to uninstall all old versions of pandoc until the command `pandoc` doesn't work anymore in your terminal. Only then install the new version.

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
