### ISSUE TITLE
Bug: --epub-metadata Conflict with special characters & < in Main article

### ISSUE THREAD

**Issue by ivysrono** [jgm/pandoc#7293]
Windows 10 x64
Pandoc 2.13 and 2.12，2.11.4 is OK

1.md
```
---
title:
- type: main
  text: title
creator:
- role: author
  text: someone
...

& <

```

`pandoc 1.md -f markdown -t epub -o ./1.epub --epub-metadata=./1.md`

```
Invalid XML in epub metadata:
ParseError {errorContexts = [], errorMessage = "Failed reading: takeWhile1", errorPosition = 9:1 (91)}
```

I'm not sure are there more characters, just find `&` and `<` now.

**Comment by tarleb** [comment]
I'm not sure this is a bug. The argument to `--epub-metadata` should be a file containing XML:

> Look in the specified XML file for metadata for the EPUB. The file should contain a series of Dublin Core elements. For example:
>
>     <dc:rights>Creative Commons</dc:rights>
>     <dc:language>es-AR</dc:language>

So if pandoc fails instead of producing garbage output seems like an improvement to me. Pandoc should pickup the metadata from the YAML block anyway, so no need to use `--epub-metadata` unless you need to add more information that cannot be passed in the YAML block.

**Comment by ivysrono** [comment]
Metadata in markdown file itself works fine in pandoc 2.11 and before.

**Comment by tarleb** [comment]
It still works fine as far as I can see. It's just that pandoc now complains about misuse of the `--epub-metadata` option. Do you get unexpected results if you don't use that option?

**Comment by jgm** [comment]
It's definitely not a bug. `--epub-metadata` takes an XML file as argument.

You can certainly include EPUB metadata in a markdown file, as documented, but just pass it in as an additional file argument, not as the argument of  `--epub-metadata`.
