### ISSUE TITLE
Citations not rendering correctly with other content in parantheses (brackets)

### ISSUE THREAD

**Issue by d0rf3n** [jgm/pandoc#7297]
pandco version 2.13.

I want to have (see 4.2 Section in my document; Author1, 2020; Author2, 1973) using: `[see [](#my-section); @auth1; @auth2]`

...but instead I get: [see 4.2 Section in my document; Author1 (2020); Author2 (1973)]

Putting the cross-reference on either side of the citations doesn't work.

I've been looking for a way to do this, but found none. Any way to do this?

**Comment by jgm** [comment]
Try putting a backslash before the first semicolon, so that the whole thing is treated as a prefix. Semicolons separate items in  a citation, and pandoc is expecting a citation before the semicolon if the whole bracketed part is to be a citation.  Because it doesn't find this, it treats this as regular bracketed text and formats @auth1 etc. as author-in-text citations.

**Comment by d0rf3n** [comment]
Thanks! This solved it for me.
