### ISSUE TITLE
`--to native` produces Haskell that `hindent` has problems with

### ISSUE THREAD

**Issue by kjambunathan** [jgm/pandoc#7335]
This is a haskell file output from `writenative`: [testdoc-skeletal-2-output-native.hs.txt](https://github.com/jgm/pandoc/files/6567825/testdoc-skeletal-2-output-native.hs.txt)

When I put the file in `haskell-mode`--yes, I run emacs--and do `M-x hindent-reformat-region`, `hindent` complains with the follwoing message 

```
hindent-reformat-region-as-is: hindent: <interactive>:2:1: Parse error: ;
```
I thought I could get around the problem by passing `{ writerWrapText = WrapNone  }` to `writeNative'.   The problem persists.

So, there are two issues:

1. Native output shouldn't produce invalid haskell when it adds newlines to haskell output 
2. `writeNative` should honor  `writerWrapText` directive.

**Comment by jgm** [comment]
I don't know about this.  The output by itself isn't something you can load into ghci anyway, because there's no top-level declaration.  If you add one, you'll have to indent the whole thing, but keeping the relative indents the same it will work:
```hs
x=
  [Plain [Cite [Citation {citationId = "Brandom1994", citationPrefix = [], citationSuffix = [], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 1}] [Str "(Brandom",Space,Str "1994)"]]
  ,Plain [Cite [Citation {citationId = "Brandom1994", citationPrefix = [], citationSuffix = [], citationMode = AuthorInText, citationNoteNum = 0, citationHash = 2}] [Str "Brandom",Space,Str "(1994)"]]
  ,Plain [Cite [Citation {citationId = "Brandom1994", citationPrefix = [Str "see "], citationSuffix = [Str " chapter 7"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 3}] [Str "(see Brandom",Space,Str "1994,",Space,Str "chap.",Space,Str "7)"]]
  , Div ("refs",["references"],[])
   [Div ("ref-Brandom1994",[],[])
    [Para [Str "Brandom,",Space,Str "Robert.",Space,Str "1994.",Space,Emph [Str "Making",Space,Str "It",Space,Str "Explicit"],Str ".",Space,Str "Harvard",Space,Str "University",Space,Str "Press."]]]]
```
I don't feel too strongly about this, though. We could move the commas to the end of the previous lines.
As for `writerWrapText` -- the current method of inserting line breaks and indentation is not intended to wrap text to fixed width (and it doesn't do this), but to ensure that each new block-level element starts on a new line, so you can see what's going on with the structure of the document.

**Comment by jgm** [comment]
I think that the leading commas are helpful in helping the reader see the structure.

**Comment by jgm** [comment]
We could consider depending on stylish-haskell (library), which would allow us to prettify the output and even respect wrap options.  As far as I can see, this library doesn't depend on anything we don't already depend on. But it would be another dependency, and more complexity (-1).

**Comment by jgm** [comment]
I'd rather not do that; all the writers can be used outside of IO.

**Comment by jgm** [comment]
Closing this because it's really a problem with hindent.
