### ISSUE TITLE
Lua filters - `clone`ing an element that contains a `Null` element raises an exception in v2.14 (and v2.13)

### ISSUE THREAD

**Issue by odkr** [jgm/pandoc#7338]
Calling `elem:clone` raises an exception if `elem` has a `pandoc.Null` AST element as a child node in Pandoc v2.14 and v2.13. Is that intentional?

Given a lua filter `clone-null.lua`:

```Lua
pandoc.Para{pandoc.Null()}:clone()
```

`pandoc -L clone-null.lua /dev/null` outputs:

> [WARNING] Could not deduce format from file extension
  Defaulting to markdown
Error running filter clone-null.lua:
PandocLuaError "Error during function call: Could not get Block value: Could not read list: Could not get Inline value: Unknown inline type: Null"
stack traceback:
	[C]: in method 'clone'
	clone-null.lua:1: in main chunk

Thanks for having a look at this.

**EDIT:** I have tested it with v2.14 and the problem remains.

**Comment by tarleb** [comment]
I can see that this behavior might be unexpected, but it is intentional: A *Para* can contain "inline" elements like *Str* and *Space*, but `pandoc.Null()` gives a block element. Pandoc tries to read the `Null` as an inline, but fails.
The cryptic error message is nothing but horrible, and I hope to improve that within the next few month (see #7191).

**Comment by odkr** [comment]
My bad, I didn’t think of `pandoc.Null` as a Block element, though the documentation is clear enough.
