### ISSUE TITLE
Implementing support for dar

### ISSUE THREAD

**Issue by AvtechScientific** [jgm/pandoc#7353]
It would be nice to have support for [dar](https://gitlab.com/pninim.org/dar/dar-syntax) format. At least the reader.

Thank you very much for the great tool!

**Comment by jgm** [comment]
I wonder how much this is used.  The README mentions one project that uses it.

**Comment by AvtechScientific** [comment]
> I wonder how much this is used. The README mentions one project that uses it.

The README explains how this markup came into existence; you can't estimate how wide it is used based on this. I'm sure it will get much more users once it enters pandoc, as it has quite a few elegant and innovative features that are not present elsewhere.

**Comment by jgm** [comment]
> I'm sure it will get much more users once it enters pandoc, as it has quite a few elegant and innovative features that are not present elsewhere.

We can't base our decisions to include a syntax on a guess about the expected number of users *after* it is supported.  We need to significant usage now.  Keep in mind that adding a new syntax is not just a one-time cost, but an added maintenance and complexity debt into the future.

**Comment by tarleb** [comment]
I'm sorry to close this for now, but it appears that support for the format is out of scope for the time being.

But you can still enable your users to use pandoc, as it's not necessary to have pandoc support a format natively in order to use them together. E.g., [custom Lua writers](https://pandoc.org/MANUAL.html#custom-writers) can be used to produce the format, try [this GitHub search](https://github.com/search?q=pandoc+writer+language%3Alua) to see some examples. Parsing the format can happen in any language with pandoc JSON support:

    my-format-parser input.txt | pandoc --from=json ...
