### ISSUE TITLE
Error when specifying template in defaults file

### ISSUE THREAD

**Issue by matrss** [jgm/pandoc#7371]
When using pandoc to create revealjs slides I experienced a weird issue:
using the defaults file
```
from: markdown
to: html

template: revealjs
standalone: true
```
with
```
pandoc --defaults=slides.yaml <in>.md -o <out>.html
```
I get the error message: `Could not find data file templates/revealjs.html`.
This seems to not be specific for revealjs, the template option `letter` which is used in the example in the docs produces a similar issue for me.

Removing the template specification in the defaults file and instead using `-t revealjs` on the commandline works fine though.

Thanks for the great project though, it's awesome!

version:
```
pandoc 2.13
Compiled with pandoc-types 1.22, texmath 0.12.2, skylighting 0.10.5.1,
citeproc 0.3.0.9, ipynb 0.1.0.1
```

**Comment by jgm** [comment]
The problem is that you've told panda to look for a template called `revealjs`. Since you didn't provide an extension, pandoc uses the output format, which is `html`.  You don't have a template called `revealjs.html` in your user data directory, and there's no default template by that name.

IF you want to create reveal.js slides, use
```
from: markdown
to: revealjs
standalone: true
```
and just let pandoc use its default template.

**Comment by matrss** [comment]
Right, I somehow thought the `-t` cli flag translates to `template:` in the defaults file, but of course it's `to:`.

Thanks a lot for the help!
