### ISSUE TITLE
Captions for figures in Word do not show up in the Table of Figures

### ISSUE THREAD

**Issue by jamesgarriss** [jgm/pandoc#7392]
**Explain the problem.**

The goal is to create a Word doc from Markdown that includes figures whose captions show in the Table of Figures.

1. Create a simple Markdown file.
2. Include a reference to an image.

`![Hello](world.png)`

3. Use Pandoc to convert the Markdown to Word.

```
pandoc readme.md
  --output=readme.docx
  --standalone
  --wrap=preserve
  --table-of-contents
  --toc-depth=2
  --variable=toc-title:"Table of Contents"
  --variable=lof:true 
```

4. Open the Word doc and find the image and its caption.  Observe that there is a ToC but not a LoF.
5. Manually insert a LoF (References > Insert Table of Figures).
6. Observe that there's a LoF, but the image is not listed.  Instead, it says, "No table of figure entries found."
7. In Word, find the image again and delete its caption.
8. Add a new image caption (right click image > Insert Caption).
9. Refresh the LoF (right click LoF > Update Field).
10. Observe that the image is now listed in the LoF.

I assume that this is bug, because I expect Pandoc to create figure captions in a format that can be found by Word's LoF.

**Pandoc version?**

pandoc 2.14.0.1
macOS 11.4 (Big Sur)
Microsoft Word for Mac 16.50 (part of Microsoft 365)

**Comment by jgm** [comment]
Can you upload a short docx that has the correct caption?

**Comment by jamesgarriss** [comment]
The attached Word docx was created by following the steps in my report above.
[readme.docx](https://github.com/jgm/pandoc/files/6686255/readme.docx)

**Comment by jgm** [comment]
``` xml
<w:p w14:paraId="53568348" w14:textId="565B6742" w:rsidR="009D0DC5"
w:rsidRDefault="00EA3425" w:rsidP="00EA3425">
  <w:pPr>
    <w:pStyle w:val="Caption" />
  </w:pPr>
  <w:bookmarkStart w:id="4" w:name="_Toc75152920" />
  <w:r>
    <w:t xml:space="preserve">
Figure 
</w:t>
  </w:r>
  <w:r w:rsidR="00D0641F">
    <w:fldChar w:fldCharType="begin" />
  </w:r>
  <w:r w:rsidR="00D0641F">
    <w:instrText xml:space="preserve">
 SEQ Figure \* ARABIC 
</w:instrText>
  </w:r>
  <w:r w:rsidR="00D0641F">
    <w:fldChar w:fldCharType="separate" />
  </w:r>
  <w:r>
    <w:rPr>
      <w:noProof />
    </w:rPr>
    <w:t>1</w:t>
  </w:r>
  <w:r w:rsidR="00D0641F">
    <w:rPr>
      <w:noProof />
    </w:rPr>
    <w:fldChar w:fldCharType="end" />
  </w:r>
  <w:r>
    <w:t xml:space="preserve">
 - Hello
</w:t>
  </w:r>
  <w:bookmarkEnd w:id="4" />
</w:p>
```

**Comment by jgm** [comment]
vs pandoc's current
``` xml
<w:p>
  <w:pPr>
    <w:pStyle w:val="ImageCaption" />
  </w:pPr>
  <w:r>
    <w:t xml:space="preserve">hello</w:t>
  </w:r>
</w:p>
```

**Comment by jamesgarriss** [comment]
Well, Pandoc's version looks a lot cleaner.  Time to channel your inner Microsoft and fill the output with a bunch of extraneous cruft?  :-)

**Comment by tstenner** [comment]
It can be shorter:

```
---
title: Figure list test
lang: 'en-US'
---

![[Figure `<w:fldSimple w:instr=" SEQ Figure \\* ARABIC "><w:r><w:t>Refresh fields…</w:t></w:r></w:fldSimple>`{=openxml}]{#figureid}: Caption here](fig-1.png)
```

`[Text]{#figureid}` inserts a span with an id attribute (`#figureid`, change this for every figure). The raw field `<w:fldSimple…` inserts an `fldSimple` tag with the `Refresh fields…` placeholder. You could put the number instead of the placeholder there, but it'd be replaced once the fields are recalculated.

One note: with a german libreoffice instance, I had to save and reload the document, otherwise the name for figures wasn't `Figure` but `Abbildung`.

**Comment by jamesgarriss** [comment]
Thanks for the offer of the filter, @tstenner, but I already have this functionality.  I modified the "Image Caption" style in custom-reference.docx to do this.

**Comment by jgm** [comment]
@tstenner thanks.  I guess we should modify the writer to insert this code (and ensure we have unique identifiers for all the figuresr).

**Comment by G1ng3r-10** [comment]
@jamesgarriss what did you do to modify the "Image Caption" style in the custom-reference.docx (such as Style Name; style type (linked or not); style based on; and style for following paragraph)? I have modified my reference doc image caption style (more times that I care to admit) and every time I have to go through your initial stated steps of manually editing the caption & then manually initiating the List of Figures. I believe it has to be something relating to my docx reference file but am at a loss. I am using Pandoc 2.14.2 and have tried with Ubuntu 20.04 and Windows 10...actively resisting the urge to pitch my computer out the window.

**Comment by jamesgarriss** [comment]
@G1ng3r-10, since they fixed Pandoc, this isn't necessary.  But if you want to do it anyway, here are the steps (for Word 16 on macOS):  

- Start Word.  Add an image.  Right click image and "insert caption..."
- Open the styles pane.  Click on the caption.  See the name of the style of the caption in the styles pane.
- In the little drop down to the right of the caption name, the one with the small paragraph icon, select modify style.
- In the bottom left of the modify style window, there's a drop down that currently says format.  Select numbering.
- Look for the numbered tab in the bullets and numbering window.  Click it, click the numbering format with the period, click the customize button.
- Look for the text that says "Enter formatting for number".  There's already a number and a period here.  You can additional text before or after the number.

**Comment by G1ng3r-10** [comment]
I guess I did not explain my issue very well. When pushing a markdown file through pandoc (with the output file being docx) each image is given the style "Image Caption" but when attempting to insert table of figures it returns no figure entries found. Then I have to manually add the caption to each image (so it is given the style "Caption" instead of "Image Caption")...following the manual process the Table of Figures will then have entries. My issue seems to be when converting the markdown file to docx the image captions are not being applied properly (and not getting linked to the image).  
  
  Thoughts?

**Comment by bandel65** [comment]
If it helps root cause the problem, when you open a generated DOCX and go to the "References" ribbon and select "Cross-reference", anything with the "Image Caption" or "Table Caption" style from the reference DOCX show up when "Numbered Item" is selected from the pull-down, but not when "Figure" or "Table" are selected.  So Word is not recognizing them as proper "Figure" or "Table" captions from which LOF or LOT can be generated.

Is there any estimated date on a fix to Pandoc's DOCX writer for this?  Or does anyone have a way of fixing this in the reference DOCX?

**Comment by bandel65** [comment]
Also, when you choose "File->Options->Advanced" and select "Show field codes instead of their values", then click "OK", manually inserted captions (for Tables) appear as " Table 1 { SEQ Table \* ARABIC }. _text of caption_".  No field codes show up for Pandoc generated captions with Style "Table caption" or "Image Caption".  So it seems like this is the key to generating those captions properly.  Which tracks with the longer OpenOffice XML snippet, above.  Any chance of this getting fixed any time soon?

**Comment by bandel65** [comment]
> @G1ng3r-10, since they fixed Pandoc, this isn't necessary. But if you want to do it anyway, here are the steps (for Word 16 on macOS):
> 
> * Start Word.  Add an image.  Right click image and "insert caption..."
> * Open the styles pane.  Click on the caption.  See the name of the style of the caption in the styles pane.
> * In the little drop down to the right of the caption name, the one with the small paragraph icon, select modify style.
> * In the bottom left of the modify style window, there's a drop down that currently says format.  Select numbering.
> * Look for the numbered tab in the bullets and numbering window.  Click it, click the numbering format with the period, click the customize button.
> * Look for the text that says "Enter formatting for number".  There's already a number and a period here.  You can additional text before or after the number.

James, that just makes that style labelled correctly from a readability perspective.  It still lack the actual field code to get Word to treat it as a Figure, Table, or Equation for cross-referencing or "List of Figures" purposes.

**Comment by owenstake** [comment]
> -t docx+native_numbering

bro, this is what i want.
