### ISSUE TITLE
Encoding regression (accent and superscript no longer give expected result)

### ISSUE THREAD

**Issue by bozito** [jgm/pandoc#7422]
It seems there is some regression between 2.7.3 and 2.14.0.3 regarding utf8 encoded text with accent (like accentué) and superscript (like that¹).
See below a minimum working example showing the issue.

[encoding_regression.md](https://github.com/jgm/pandoc/files/6748208/encoding_regression.md)
[encoding_regression_pandoc2.7.3.pdf](https://github.com/jgm/pandoc/files/6748209/encoding_regression_pandoc2.7.3.pdf)
[encoding_regression_pandoc2.14.0.3.pdf](https://github.com/jgm/pandoc/files/6748210/encoding_regression_pandoc2.14.0.3.pdf)

**Comment by mb21** [comment]
Can you post exact command, OS and pdflatex version?

**Comment by bozito** [comment]
1. exact command: 'pandoc encoding_regression.md -t beamer -o encoding_regression.pdf' (it's written in the *.md file)
2. OS: Ubuntu 18.04.5 LTS
3. pdflatex version:
```
pdflatex -v
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.34; using libpng 1.6.34
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with poppler version 0.62.0
```

**Comment by jgm** [comment]
I can't reproduce this. Accents and superscripts are fine when I do this command on my system.

**Comment by jgm** [comment]
I suspect this is related to #7295 changes (see also #7362).
In the case of #7362 an upgrade to tex was sufficient.

**Comment by bozito** [comment]
> In the case of #7362 an upgrade to tex was sufficient.

Hello, I just tried it on another computer (Ubuntu 18.04.5 LTS) with pandoc 2.11 and 2.14.03:

-  compile with 2.11 : no bug
-  compile with 2.14.03 : Bug
- upgrade of texlive-all, compile with 2.14.03 : Bug still there.

So the fix for #7362 does not work for me as I am now using the most recent pdflatex I can get on this distro using the official repos...

**Comment by bozito** [comment]
I forgot to mention that using `--pdf-engine=xelatex` is a workaround for this bug too, but I don't know whether it's going to introduce some compatibility issues with our workflow and existing *.md files...

**Comment by mb21** [comment]
> I am now using the most recent pdflatex I can get on [Ubuntu 18 LTS] using the official repos...

well, the latest Ubuntu LTS is 20...

**Comment by bozito** [comment]
> well, the latest Ubuntu LTS is 20
Fair enough.
But, 18.04 is an LTS that is not EOL, so I was expecting pandoc to work with it, or at least get a  warning of some sort not to use pandoc version above XXwhatever with this distro.
I'm still a bit puzzled that there is such a regression for an LTS : I did not expect pdflatex to ch 
ange that much at that point.

As for 20.04, it's the first time I don't switch right ahead to the shiny new Ubuntu LTS because it's just broken:
1. snap version of applications is forced down the throat of users, to the point where `apt get install thunderbird` installs the snap version of it and there is no easy way to install a "normal" version.
2. snap version of many softs are just not working as expected (like file association being broken for thunderbird) and way slower to start.
3. snap folder cannot be moved out of the home dir.
4. snap does not support NFS or any network mounted folders.

For our organisation, the combination of points 1, 3 & 4 are a real deal breaker as user home dirs are NFS mounted on all the computers, which means that many basic apps are just not usable under 20.04.
So we will have to stick with 18.04 for a while I guess and if that means running an old version of pandoc, so be it...

**Comment by jgm** [comment]
@JohnLukeBentley - another pain point from the move of the author/title metadata to the beginning of the preamble.  Should we reconsider?

**Comment by alerque** [comment]
I think @mb21's comment on this is pretty much the deal: If you want software to play nicely you need to use versions from at least the same epochs. Pandoc's use of LaTeX is very conservative and we support a wide range of versions, but at some point things just don't match and you can't hold back better support for same-generation software because it has side effects for miss-matched generations. Pandoc itself is packaged and distributed in Ubuntu 18 LTS (1.19.2.4). If you want a version that plays nicely with the distro's LaTeX, use them together. If you want something with newer bells and whistles for your pipeline, you've going to need to upgrade your systems LaTeX to at least the same erra as the Pandoc you want to use.

I'm not saying we can't support older versions to an extend possible. We've previously stated intent to support LaTeX rangese from whatever is the latest shinny to whatever is latest in Debian stable. That's generally a pretty wide swatch.

**Comment by JohnLukeBentley** [comment]
@jgm without my having to attempted a reproduction of this bug (of the current thread), let's assume for argument that:

* @bozito's problem is partially a result of being on an older OS version; and
* the right thing broadly for  @bozito to do is either as (@mb21 and @alerque are suggesting): move to a new OS version that plays nicely with the latest pandoc; or stay with their older OS version and use an older pandoc version.

... and so @bozito gets by accordingly.

That wouldn't address the more fundamental issue in #7295 that @gitphilip raised, against which you nicely identified an (apparently) [irreconcilable tension](7295#issuecomment-865149553).

I did respond to that comment and offered a reconsideration (one possible idea). (A comment that might have slipped you by in your considerable and laudable development effort).

Perhaps implementing that idea could solve both @gitphilip's and @bozito's problem, while not regressing on the kind of functionality I now enjoy (e.g. referencing author and title in margins)?

**Comment by jgm** [comment]
@JohnLukeBentley  I'm not too keen on the multiple header-includes idea.  It has been requested before and my response has always been that if you need this sort of thing, just use a custom template.

Even if this particular problem could be solved by upgrading an OS (which is not always feasible for users), II think there are many potential problems like this lurking.  The #7295 problem is just one example.  Maybe someone wants to put an image in the title and thus needs `graphicx` to have been loaded. Or maybe the title contains the euro symbol, which with pdflatex requires textcomp to be loaded.

These particular issues could be solved by moving the metadata commands a bit further down in the preamble -- at the cost of burying them where they're hard to find.  But this wouldn't solve all problems of this kind.  For example, people who use RTL languages may have problems if `\title` and `\author` come before `bidi` is loaded.  And `bidi` needs to be loaded as late as possible...

Hence I'm inclined to solve this by moving these definitions back where they were before (i.e., reverting the change you requested).  Exactly one person has ever requested that `\title` and `\author` get defined before `header-includes`, and multiple people have already needed it to be the other way round. Maybe a custom template is the right solution for your use case?

**Comment by jgm** [comment]
@JohnLukeBentley how about this solution?
Put your code to set the margin contents inside etoolbox's `\AtEndPreamble`.  Then it will execute at the end of the preamble, after author and title are defined.  (Untested.)

**Comment by alerque** [comment]
Two. I realized when the change went through that it would solve a different but related problem I'd been working around another way and was able to start using it. I realize I can use a custom template myself, but the logic of having those variables loaded earlier and blocks of random code later seems like better logic. If either way one set of people has to use. Ironically I would *also* have been bitten the other way with characters that wouldn't render properly, except I happen to use XeLaTeX anyway. Or SILE ;-)

Honestly I'm not sure that changes the equation at all. Also I'm losing track of which bits work on which side of this equation.

**Comment by JohnLukeBentley** [comment]
## Accent/Superscript OK on my machine

(In Windows) I've just tested, under pandoc 2.14.0.3 ...

> ps> pandoc .\test_encoding_regression.md --from markdown --to beamer --pdf-engine=pdflatex --output .\output\test_encoding_regression.pdf

With

> ps> pdflatex -version
MiKTeX-pdfTeX 4.6.1 (MiKTeX 21.6.28)
© 1982 D. E. Knuth, © 1996-2021 Hàn Thế Thành
TeX is a trademark of the American Mathematical Society.
...

... and the output comes out OK.

Not that this is suprsing at this point. It's merely an additional confirmation that some kinds of the later pdflatex engines play nicely with the latest version of pandoc, with respect to this accents issue.

@jgm:
> upgrading an OS (which is not always feasible for users),

Indeed. I'm not able to adjudicate the pros and cons of versions of Ubuntu. But, for example, I'd take @bozito's word for it that "[they] will have to stick with 18.04" and are consequently stuck with an older latex environment.

## \AtEndPreamble

A great suggestion. On a first attempt I haven't got it work. (As I think you had in mind) I reverted a local copy of default.latex to restore title, author, etc to the end of the preamble; I wrapped my margin commands in `\AtEndPreamble{}` (that code appearing high in the preamble); I had to explictly call `\usepackage{etoolbox}` (because in the resulting tex from default.latex etoolbox would not be present for some reason, even though I see etoolbox it in default.latex).

I get an error: "! LaTeX Error: Missing \begin{document}".  The tex seems borked.

My code ...

    \usepackage{etoolbox}
    \AtEndPreamble{\makeatletter
    \let\runauthor\@author
    \let\runtitle\@title 
    \let\rundate\@date
    \makeatother
    \lhead{\it\runtitle}
    %\rhead{\it\rundate}
    \rhead{\it\runauthor}
    \lfoot{\it\rundate}}

## Possible other solutions

@jgm 
>   I'm not too keen on the multiple header-includes idea.  ... my response has always been that if you need this sort of thing, just use a custom template.

That pandoc has a custom template facility as a last resort speaks very well in pandoc's favour. It's a great piece of design.

At the moment the broad options seem to be:

* multiple header-includes;
* ((As before: title, author, etc at the bottom of the preamble.) or (as now: title, author, etc. at the top of the preamble)) and stipulate the lest impacted user group use a custom default.latex.
* some other lateral solution (as ` \AtEndPreamble{}` still might count).

I think you've convincingly argued that there's a potentially signficant number of hypothetical use cases for having title, author, etc., at the bottom of the preamble. And your examples seem to illustrate that this is true even if someone is not using a header-includes. Reading default.latex I see that `textcomp` and  `graphicx` could simply be invoked, and depended upon, under various circumstances that don't entail a header-includes.

But as for the other side ...

 > Exactly one person has ever requested that \title and \author get defined before header-includes.

I'd take your word for it (that I'm the only such person). However, there seems to be more than me that would find it useful for there to be an addtional header-includes, at the very end of the premable (which would come after title, author, etc even if reverted back to the bottom).

@anghyflawn [reports](https://github.com/jgm/pandoc/issues/7295#issuecomment-868550474) in #7295 wanting a header-includes after `\usepackage ... {biblatex}` (whether their needs can be address by overriding the CSL command instead, as you helped us to do in #7286, might be open). They've explicitly stated "I think offering some additional sites for header-includes might be the way to go"

And it seems @alerque (just above) ...

> I realized when the change went through that it would solve a different but related problem 

... is expressing that they'd prefer a header-includes below title, author, etc (even if title, author, etc are reverted back to the end of the preamble but there is an addtional header-includes after that). Is that right @alerque?

## For and against multiple header-includes.

Are these the sort of reasons against, you have in mind?:

* Out of the gate it increases complexity and broadly there's always a heavy burden of justifcation to do this.
* Every output template would now need multiple header-includes, for the sake of consistency (??).

My suspicions are that even if the relativity of title, author, etc. - to a single header-includes - is resolved (one way or the other); then down the track there will still arise a need to insert header code just before the end of the preamble.

However, it may well be that you'd pefer to build up some real, rather than hypothetical, cases before attempting multiple header-includes. At this point, a feasible possible strategy does seem open, to (as I think you have in mind):

* Revert things so that title, author, etc. are at the bottom of the preamble.
* Stick to one header-include, in its current location.
* Myself, @anghyflawn, and @alerque look for work arounds, possibly with your assistance. As a last resort all three of us could use a custom default.latex.

But my suggestion remains:
* Revert things so that title, author, etc. are at the bottom of the preamble.
* Include an additional header-includes just below that (so that this addtional header-includes is the very last thing in the preamble). Perhaps this would need only be done for default.latex?

**Comment by jgm** [comment]
Try your code with `\def` instead of `\let`?

**Comment by JohnLukeBentley** [comment]
Just a different kind of error ...

> Error producing PDF.
! Use of \runauthor doesn't match its definition.
\f@nch@orh ->\it \runauthor \strut

... with ...

    \usepackage{etoolbox}
    \AtEndPreamble{\makeatletter
    \def\runauthor\@author
    \def\runtitle\@title 
    \def\rundate\@date
    \makeatother
    \lhead{\it\runtitle}
    \rhead{\it\runauthor}
    \lfoot{\it\rundate}}

... strange that it didn't fail on `runtitle`.

This is using my "production" files rather than a MWE. Todo: attempt with a MWE.

**Comment by JohnLukeBentley** [comment]
Breakthrough!

[AtEndPreambleMWE.tex](https://gist.github.com/JohnLukeBentley/9dda6166b9ee5c4127afd2b8cd16b70a)

The secret sauce was to keep `\makeatletter` and `\makeatother` out of `\AtEndPreamble{}`.

Give me time to test this in my "production" environment. But AtEndPreambleMWE.tex seems to demonstrate the general principle:

* Author, title, date (whatever other metadata) can be moved to the bottom of the preamble; 
* Pandoc users of `header-includes` in default.latex should be able to exploit `\AtEndPreamble{}` if they need to; and
* It might just be a matter of documenting, in the Pandoc User Guide, any syntax gotcha's with `\AtEndPreamble{}`, the  `\makeatletter` and `\makeatother` thing counting as the first.

**Comment by jgm** [comment]
Excellent.  I think documenting this is too specialized for the user's guide, but we could put it in FAQs or some other searchable location if you want to suggest some text.
So, let's move the title/author stuff back to the end of the preamble, where it was before.

**Comment by jgm** [comment]
I'll wait for your further tests first.

**Comment by JohnLukeBentley** [comment]
Production test passes.

Noted that you'd rather not have this specialised info in the User Guide.

Perhaps having in mind a user contemplating https://pandoc.org/MANUAL.html#option--include-in-header in the User Guide
> `-H FILE, --include-in-header=FILE|URL`
>
>  Include contents of FILE, verbatim, at the end of the header. This can be used, for example, to include special CSS or JavaScript in HTML documents. This option can be used repeatedly to include multiple files in the header. They will be included in the order specified. Implies `--standalone`. [For use with pdf/latex (.tex) see the FAQ] {link}

I might want to impart, in addition, something along the lines of (if the following were in the FAQ (although it'd really be an Infrequently Asked Question)) ...

> When using ` --include-in-header` with pdf or latex (.tex) output, how do I reference tex declarations coming after  `$header-includes$` in [default.latex](https://github.com/jgm/pandoc/blob/master/data/templates/default.latex)?
>
> For pdf output going via latex (.tex), or for conversion straight to latex (.tex) ` --include-in-header` exists toward the bottom of the "preamble", as `$header-includes$` in `default.latex`, but nevertheless not at the very bottom. This is because latex can get quite particular about the order of commands and packages. The current location of `$header-includes$` is a result of a great deal of trial and error and should serve your most common needs. 
>
> However, sometimes you may want to insert code into default.latex's `$header-includes$` that depends on declarations in the preamble coming *after* the `$header-includes$` location. E.g. you might want to reference the `\author` and `\title` metadata values (located at the very bottom of the preamble) and present them in margins. In that case you can wrap your code in etoolbox's `\AtEndPreamble`. The broad principle is demonstrated in [AtEndPreambleMWE.tex](https://gist.github.com/JohnLukeBentley/9dda6166b9ee5c4127afd2b8cd16b70a).
>
> When using `\AtEndPreamble` take note of the following syntax considerations:
> * Keep any `\makeatletter` or `\makeatother` out of `\AtEndPreamble` (as shown in  [AtEndPreambleMWE.tex](https://gist.github.com/JohnLukeBentley/9dda6166b9ee5c4127afd2b8cd16b70a)).

Feel free to copy my gist elsewhere, if you'd want to use it as is. Or just link straight to it (my github account should outlive me).

**Comment by JohnLukeBentley** [comment]
Both the Faq wording and the code "revert" commit look good.

Todo. Some further testing of the output of `\usepackage{etoolbox}` in default.latex. The results of which will have impacts on whether we advise folk wanting to use `\AtEndPreamble` whether they need to declare `\usepackage{etoolbox}` beforehand or can rely on `\usepackage{etoolbox}` being available "for free".

**Comment by anghyflawn** [comment]
Thanks, both! I can confirm that `\AtEndPreamble` can effect the `biblatex` customizations I need, so this is good enough for those purposes.

**Comment by JohnLukeBentley** [comment]
Thanks for that confirmation @anghyflawn! I'm potentionally in need of biblatex customizations myself.

As a matter tangential to the current thread: you might find (and you may or may not already be aware) that in presenting citations and bibliographies you can rely, and potentially customize, pandoc's citation processing which (if I've understood matters correctly) by default bypasses biblatex processing completely .

Having spent a great deal of time working with biblatex mysefl I appreciate that might initially come as a dissappointment given biblatex  is quite the sophisticated processor. However, you gain all the expressive power of the Citations Style Language ecosystem (see, for example, [Zotero Style Repository](https://www.zotero.org/styles)) and can even produce your own custom CSL style (https://docs.citationstyles.org/en/stable/specification.html) to invoke with pandoc, if none of the CSL styles in the repository are quite right.

In addtion you could even override the CSL commands in default.latex through your `header-includes` (as I've done in my environment).

**Comment by anghyflawn** [comment]
Thanks — yes, I’m aware that citeproc can be used to bypass biblatex compilation in LaTeX output, too — I do use this functionality where I don’t need some of the outer reaches of biblatex flexibility; learning more about CSL to see if I can bend it to my will is something I've long wanted to do, but with a large legacy biblatex codebase and established customizations it never quite reaches the top of the agenda! (For me, the big advantage of citeproc at this stage is only compilation speed, as after the introduction of the latexmk engine I don't need to worry about running anything manually anymore.)

**Comment by JohnLukeBentley** [comment]
Great! 

It's entirely possible I might go back to biblatex processing given the power of it to which you allude. (And there my learning would have to extend to using pandoc to invoke biblatex properly). I have found much of the EDTF datetime format support in biblatex has successfully flowed through to CSL/Pandoc (or arisen independently). So that was the main thing for me. And I have some success at bending custom CSL files to my will (so feel free to message me down the track if you need any assistence here ... but it's fairly intuitive once you give it a crack).

**Comment by jgm** [comment]
Currently `etoolbox` occurs in two places in the default  template:
- It is included if the format is not beamer and the document contains (here it is used to fix a weird interaction between longtable and paragraph).
- It is included if the document contains a subtitle and the format is not beamer.

If neither condition holds, it isn't included.  We could consider just including it unconditionally, as it is certainly handy for things like this and it's widely available.  But generally we've followed a policy of including only packages actually used.

**Comment by JohnLukeBentley** [comment]
@jpm. From memory (I've yet to test it specifically) my output didn't include `etoolbox`; and given your summary of the code it looks like my documents didn't trigger those particular conditions.

Yeah, as you suggest: how about we include it unconditionally? ... and so stipulate that `\AtEndPreamble` can be used without the user having to explicitly declare `\usepackage{etoolbox}` before `\AtEndPreamble`. 

If we don't do that then we risk a user of `\AtEndPreamble` ending up with intermediate .tex output (thrown out by default.latex) that has two declarations `\usepackage{etoolbox}`. That would fail to latex-compile.

The unconditional `\usepackage{etoolbox}` in default.latex would need, thererfore, to be above `$header-includes$`.

**Comment by jgm** [comment]
I think people who are sophisticated enough to use `\AtEndPreamble` will also know that it comes from `etoolbox`, and will know how to interpret the error message and add the usepackage to their header-include.  So I don't see this being a serious problem in practice.  Having two `\usepackage{etoolbox}` in the generated tex won't cause a compile error.

**Comment by JohnLukeBentley** [comment]
Right you are about two `\usepackage{etoolbox}` not causing a compile error, my mistake.

On sophistication, I'd never heard of `\AtEndPreamble` before. If you hadn't flagged it was from `etoolbox` I might have supposed it was a native function. Of course anyone attempting `\AtEndPreamble` this deep in the technical weeds is going to immediately google it if they get an error because there is no `\usepackage{etoolbox}`.

Anyway even someone knowing that `\AtEndPreamble` requires a `\usepackage{etoolbox}` might also like that `\usepackage{etoolbox}` is already available in default.latex, available for their use. I mean that would seem to be what you have in mind with "We could consider just including it unconditionally, as it is certainly handy for things like this".
