### ISSUE TITLE
MediaWiki indented codeblocks get split one-per-line in Markdown

### ISSUE THREAD

**Issue by mykolm** [jgm/pandoc#7443]
```
$ cat test.wiki
Here is codeblock:
 line1
 line2
 line3
$ pandoc -f mediawiki test.wiki -t gfm -o test.md
$ cat test.md
Here is codeblock:

`line1`
`line2`
`line3`
```
Expected result:

    $ cat test.md
    Here is codeblock:
    ```
    line1
    line2
    line3
    ```
**Pandoc version?**
```
$ pandoc --version
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
I do like me codeblocks:))

**Comment by mb21** [comment]
Can reproduce with latest version: https://pandoc.org/try/?text=Here+is+codeblock%3A%0A+line1%0A+line2%0A+line3&from=mediawiki&to=gfm&standalone=0

**Comment by jgm** [comment]
There's a reason we do it this way.
Markup is allowed inside these preformatted blocks. Our CodeBlock construct just takes a string.
So for example in mw you can have
```
  ''markups'' '''''can''''' be done.
```
and this is supposed to give you italics and bold with the preformatted text.  We work around this by using code spans instead of a code block.

Still, our implementation isn't perfect.  We lose the line breaks.  Now that we have a LineBlock element in the AST, we should treat these things as LineBlocks instead.

**Comment by jgm** [comment]
My mistake.  We *do* add hard breaks already. So I think our output is fine.

**Comment by jgm** [comment]
Example:
```
pandoc -f mediawiki -t html
  ''markups'' '''''can''''' be done.
  ''markups'' '''''can''''' be done.
^D
<p><code> </code><em><code>markups</code></em><code> </code><strong><em><code>can</code></em></strong><code> be done.</code><br />
<code> </code><em><code>markups</code></em><code> </code><strong><em><code>can</code></em></strong><code> be done.</code></p>
```
