### ISSUE TITLE
markdown reader: startnum extension: incorrectly parsing marker longer than 2 characters

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#7471]
May be related to #7172.

MWE:

```markdown
# Not OK

I.  testing
II. testing
III. testing
    a.  testing
    b.  testing

## OK

I.  testing
II. testing
#.  testing
    a.  testing
    b.  testing
```

Converting using pandoc 2.14.1 (on macOS Big Sur), say by

```sh
pandoc testing.md -s -o testing.html
```

The first example will be incorrect. Changing `III. ` to `#. ` will be ok. The only difference is that `III.` is already 4 character wide.

**Comment by jgm** [comment]
This is not a bug.
```
I.  testing
II. testing
III. testing
    a.  testing
    b.  testing
```
The reason this doesn't work as you expect is that the `a.` and `b.` list items are not indented far enough. They need to be indented to the beginning of the content after `III.` in order to be contained in that list item.  See the manual under lists:

<https://pandoc.org/MANUAL.html#block-content-in-list-items>

Alternatively you can enable the `four_space_rule` extension.

**Comment by ickc** [comment]
There must be a bug somewhere then, may be the markdown writer. It is because this MWE is actually first encountered from a docx source to markdown conversion. I can try to hunt it down later.

**Comment by ickc** [comment]
Actually It's not a bug. I was converting from PDF to Word (using MS Word) and then converting the Word to markdown using pandoc. The problem is the conversions are imperfect, and I then manually fixed them incorrectly.

Thanks and sorry for the noise.
