### ISSUE TITLE
slide-level in metadata block has no effect

### ISSUE THREAD

**Issue by Louson** [jgm/pandoc#7686]
Might be linked to #6030

Using pandoc version 2.14.1

Adding `slide-level: 3` in the metadata yaml block has no effect. The following code gives different result if compiled with --slide-level or not while it should be identical.

```
---
title: 'Example'
author: Me

slide-level: 3

---

# Section 1

## Subsection 1

body 1.1


## Subsection 2

body 1.2

# Section 2

## Subsection 1

body 2.1

## Subsection 2

body 2.2

## Subsection 3

body 2.3
```

Note that the result is also correct if instead we give a default file (option -d) with `slide-level: 3` inside.

**Comment by jgm** [comment]
Metadata and command-line options should not be confused.
In general, you can't set command-line options in metadata.  (There are a few special cases where this works by accident, because the command-line option does nothing more than set a template variable, and template variables will be set from metadata fields.)

See the documentation on default files if you want another way to handle this.

**Comment by Louson** [comment]
Actually, the default-file documentation includes a field slide-level. Isn't it related ?

**Comment by tarleb** [comment]
The fields listed there can be used in *defaults files*, i.e., separate YAML files that are separate from the document and are passed to pandoc via the `--defaults` (or `-D`) command line option. It's conceptually different from document metadata that's included in a YAML block within the document.

**Comment by Louson** [comment]
It seems so strange to me, but well... sorry for the inconvenience

**Comment by tarleb** [comment]
There are technical and security reasons for this. Technical, because we don't want to (or can't) change parser behavior after input parsing has already begun. The YAML headers affect only document output, but *defaults* fields control all parts of the conversion process. A security reason is that some of these options could cause issues when they were controllable via the input document.

**Comment by jgm** [comment]
Also, conceptually, processing instructions are not metadata.
