### ISSUE TITLE
alternative groff pdf engines

### ISSUE THREAD

**Issue by jarnowic** [jgm/pandoc#7735]
**Add -Tpdf as a method to generate PDF's from ms format.**

**Describe alternatives you've considered.**

Turns out that there is another method to generate PDF output with the ms format on groff: instead of calling the `pdfroff` script, add the `-Tpdf` device on a regular `groff` call as follows:

```
groff -e -t -ms -mspdf -mpdfmark -Dutf8 -Tpdf manual.ms
```

This works on hybrid systems, like running WinPandoc on Cygwin on Windows: groff.exe is a native exe on cygwin, unlike pdfroff.exe, which needs to be produced locally. WinPandoc chokes on pdfroff, as it reports a `pdfroff.exe` file not found error, as expected.

The "normal" redirecting through a pipe to `ps2pdf` on unixes works as well.

I suggest to add at least one of these options as ways to produce PDFs via the ms format, the same way that there are alternative ways to generate PDFs with different TeX engines. 

I may submit patches if requested.

**Comment by jgm** [comment]
It would be nice if groff by itself worked, but I haven't gotten it to work on any of my systems (Macs).
On one I get an error about a missing font, on another a complaint about both `-Dutf8` and `-Tpdf`.  Perhaps only very recent versions support this?

I also tried using groff with `-Tps` and then piping through `ps2pdf`. 
```
groff -e -t -ms -mspdf -mpdfmark -Dutf8 -Tps manual.ms | ps2pdf -  m22.pdf
```
This gave me a pdf, but there were weird artifacts around the hyperlinks:

<img width="676" alt="Screen Shot 2021-12-06 at 8 34 38 PM" src="https://user-images.githubusercontent.com/3044/144966993-a0ebd931-39f6-49f7-90b6-43f0b29e60df.png">

**Comment by jarnosz** [comment]
1. On the missing font issue. at first I also received an error message along these lines:

```
Failed to open '/usr/share/ghostscript/9.50/Resource/Font/P052-Roman'
```

And my second thought was to check my gs version, which indeed was `9.54.0`. So I thought I needed to change groff's paths to the fonts, and those are in the `/path/to/groff/1.22.4/font/devpdf/download` file. Since I could not find anything like `updmap` for this system, I just edited the file to update the paths, and it worked.

Cave: the `-Tpdf` option of groff calls a perl script called `gropdf`, which may have to be installed separately on some systems; and it seems that it downloads the whole fonts into the file, instead of partial downloads à la gs/dvips. Therefore, the size of the PDF files may grow very large if downloading fonts, instead of depending exclusively on the Base14 required for PDF, which are assumed to be present in PDF compliant readers.

So, in fact, `pdfroff` and the `-Tpdf` option are calls to a shell and a perl scripts, respectively, to do the job. However, the perl script is called from within the `groff` call; so, contrary to `pdfroff`, it does neither run on its own, nor depend on the `gs` executable to work. It depends on ghostscript's font paths, but not on the executable itself.

2. It seems that the `-mspdf` and `-mspdfmark` macros are not optimized for `grops` output: they seem to go through grohtml to resolve the links; thus the funny lines and nonworking links. They may need a little debugging. So, effectively, the `ps2pdf` route is not working. So I stand corrected.

**Comment by Artoria2e5** [comment]
> This works on hybrid systems, like running WinPandoc on Cygwin on Windows: groff.exe is a native exe on cygwin, unlike pdfroff.exe, which needs to be produced locally. WinPandoc chokes on pdfroff, as it reports a pdfroff.exe file not found error, as expected.

I happen to be on a system like that. Bad luck, I know.

There is one easier solution here though: `sh.exe` is also a native exe on cygwin, so logically whatever works to substitute groff in would also work to just explicitly call have shell exe open the pdfroff script.

**Comment by jarnowic** [comment]
> > This works on hybrid systems, like running WinPandoc on Cygwin on Windows: groff.exe is a native exe on cygwin, unlike pdfroff.exe, which needs to be produced locally. WinPandoc chokes on pdfroff, as it reports a pdfroff.exe file not found error, as expected.
> 
> There is another easier solution here though: `sh.exe` is also a native exe on cygwin, so logically whatever works to substitute groff in would also work to just explicitly call have shell exe open the pdfroff script.

Scusi, but how exactly does that help me?

**Comment by jarnowic** [comment]
after careful thought, it seems to me that forcing it through yet another `--pdf-engine` is excessive; as with `man` or other groff macro packages, it may be filtered through a pipe. `ms` has the additional `-mspdfmark` macro extension which takes care of cross-references, and it seems to me that other macros (`me`, `mom`) do not have that capability...

**Comment by jarnowic** [comment]
any idea why the groff call should be "ms"? it seems to me that a better name, corresponding to the *engine* and **not** the *macro package* would be `pdfroff`. If this is implemented, other macro packages might be used by manipulating the `--pdf-engine-opts` variable in default files or the cmd line. comments?

**Comment by jgm** [comment]
It *is* called `pdfroff`.

**Comment by jarnowic** [comment]
> It _is_ called `pdfroff`.

oh! in `PDF.hs`!!

That's wonderful!
