### ISSUE TITLE
Easy Top and Bottom Borders For Tables

### ISSUE THREAD

**Issue by DarioS** [jgm/pandoc#7770]
I would like to be able to draw a solid border above the column names and at the bottom of the table. From the user manual, it appears that pipe tables don't support a set of dashes above column names or as the last line of the table definition, but other tables do, such as multiline and grid, although when I copy the examples and process them, the top and bottom table borders are missing anyway.

**Comment by jgm** [comment]
Those lines are just to mark out table structure in the markdown source.
They don't correspond to lines in the output.  That's a formatting detail and may vary from one output format to another; pandoc doesn't give you much control over it.
(Questions like this should go to pandoc-discuss rather than the bug tracker.)
