### ISSUE TITLE
Unuseful extra folders creating with 'extract-media'

### ISSUE THREAD

**Issue by mrkingmidas** [jgm/pandoc#7779]
Hello!

Situation:
Files in folders:
```
1\Test.md
1\_d\1.png
_resources\2.png
```

Content of `Test.md`:
```markdown
![](https://pandoc.org/diagram.jpg)

![](_d/1.png)

![](../_resources/2.png)
```

Run command in subfolder `1`:
```
pandoc --extract-media=out -s test.md -o out.md
```

That creates new files with strange structure:
```
1\out.md
1\out\8ebcabebd853a7c26095145ff5527a31f902d291.jpg
1\out\_d\1.png
1\_resources\2.png
```
Content of `out.md`:
```markdown
![](out/8ebcabebd853a7c26095145ff5527a31f902d291.jpg)

![](out/_d/1.png)

![](out/../_resources/2.png)
````

If I am using old version of pandoc, that creates good structure:
```
1\out.md
1\out\31157ff8b768862aec5aa6fb2e6d7662c6639615.png
1\out\68ec1863263240bd65ae52dae769df4f92897a09.png
1\out\8ebcabebd853a7c26095145ff5527a31f902d291.jpg
```
Content of `out.md`:
```markdown
![](out\8ebcabebd853a7c26095145ff5527a31f902d291.jpg)

![](out\31157ff8b768862aec5aa6fb2e6d7662c6639615.png)

![](out\68ec1863263240bd65ae52dae769df4f92897a09.png)
````

Question: How to get the new version to save media files (network, local in the same folder, local in parent folders) in one folder specified in the parameter?

**Versions:**
- Windows 10 1909 x64
- Pandoc old version works great:
```
pandoc 2.12
Compiled with pandoc-types 1.22, texmath 0.12.1.1, skylighting 0.10.4,
citeproc 0.3.0.8, ipynb 0.1.0.1
```
- Pandoc new version works bad:
```
pandoc 2.16.2
Compiled with pandoc-types 1.22.1, texmath 0.12.3.3, skylighting 0.12.1,
citeproc 0.6, ipynb 0.1.0.2
```

**Comment by jgm** [comment]
See the first item in the release notes for
https://pandoc.org/releases.html#pandoc-2.14.0.2-2021-06-13
along with #7345.

In this release, the decision was made to preserve original path names for local resources specified with relative paths, using sha1 hashes only for resources specified using absolute paths.  Using original path names requires also preserving the directory (folder) structure, because you might have two different files with the same name in different directories.
 
I hope that explains the change.  However, your example does reveal something that arguably is a bug.  With the image `../_resources/2.png`, `--extract-media=out` writes it outside of the specified output directory `out`.  This is both unexpected and a potential security issue.  We could change to using sha1 hashes for any relative path containing `..`.

**Comment by jgm** [comment]
OK, fixed that issue with `..` in commit d960282b105a6469c760b4308a3b81da723b7256

I think the other issue is simply whether resources with relative paths not containing `..` should retain their original names and directory structure. I think there was reason to make this change, so I don't consider this a bug.
