### ISSUE TITLE
markdown to PDF fails to read local images with spaces in name

### ISSUE THREAD

**Issue by Jmuccigr** [jgm/pandoc#7819]
Converting markdown with an image file with a space in its name will result in an error when creating a PDF unless the full file path is provided.

For example, assuming a file named "file name.jpg" in the local directory, simple content like

`![Caption](file name.jpg)`

will fail with this error:

```
Error producing PDF.
! Package pdftex.def Error: File `/private/var/folders/yl/xd3tsv2x1959s23ts4k1q
t9m0000gr/T/tex2pdf.-a03f08b592ad4cd0/file name.jpg' not found: using draft set
ting.
```

Providing the full path results in a successful outcome:

`![Caption](/Users/username/directory/file name.jpg)`

Both work for html output.

pandoc 2.16.2
Compiled with pandoc-types 1.22.1, texmath 0.12.3.2, skylighting 0.12.1,
citeproc 0.6, ipynb 0.1.0.2

**Comment by jgm** [comment]
Repeated from mailing list:


Here's the root of the issue:
```
 % pandoc -t native
![moon](La Lune.jpg)
[ Para
    [ Image
        ( "" , [] , [] ) [ Str "moon" ] ( "La%20Lune.jpg" , "fig:" )
    ]
]
```
As you see, the markdown reader converts the space to %20 in the
image path.  This is fine for HTML but when pandoc tries to
create a PDF, it causes problems.  I need to explore further,
but I'm convinced that's it, because if you try `-f native`
with the above, it fails, but replacing `%20` with a space,
it then succeeds.

**Comment by jgm** [comment]
Fixed by changing `writeMedia` so it unescapes percent-encoding in constructing media paths.
This will also affect `--extract-media` (in a good way I think; nobody wants percent-encoding in pathnames).
