### ISSUE TITLE
odt, epub, docx - broken heading labels and their cross-references with Pandoc 2.17.0.1

### ISSUE THREAD

**Issue by N0rbert** [jgm/pandoc#7862]
**Explain the problem.**
Cross-references are broken for labeled headings. Details are at https://github.com/rstudio/bookdown/issues/1301 .

**Pandoc version?**
Pandoc 2.17.0.1 on Ubuntu 21.10.

**Comment by jgm** [comment]
Can you give us a minimal reproducible example that just uses pandoc, not rmarkdown?  Also: is this a regression?  (That is, is this something that worked in a previous version but stopped working in this one?)

**Comment by jgm** [comment]
Can you give us a minimal reproducible example that just uses pandoc, not rmarkdown?  Also: is this a regression?  (That is, is this something that worked in a previous version but stopped working in this one?)

**Comment by N0rbert** [comment]
This is a regression. It first happened with pandoc 2.17 (from *pandoc-2.17.0.1-1-amd64.deb*).

**Comment by tarleb** [comment]
We'll still need an example that uses just pandoc. Otherwise we can't really help.

**Comment by cderv** [comment]
FWIW I'll look at this on the **rmarkdown** to check how the Pandoc upgrade affect our process, then I update here with a reprex if needed. 

I can already confirm that 2.16.2 works correctly for us, and 2.17 does not. I'll investigate

**Comment by cderv** [comment]
Ok I believe this is because of changes regarding HTML wrapping in Pandoc 2.17 (https://github.com/jgm/pandoc/issues/7764)

Previously wrapping had no effect on HTML , and now it has some effect. The default is automatic wrapping so it affects any current HTML output. Previously it was equivalent to `--wrap = "none"` I believe but we know have to explicitly set it to get back previous behavior.

This breaks our processing which appear to be sensible to that. I suppose this change is there to stay so I'll adapt in our tool chain.

**Comment by N0rbert** [comment]
I'm sorry for inconvenience. 
Fixed on bookdown side.
