### ISSUE TITLE
unordered list in Word blockquote

### ISSUE THREAD

**Issue by redstoneleo** [jgm/pandoc#8072]
The unordered list should be included in the Word blockquote, but pandoc didn't do it well.
[fx2.docx](https://github.com/jgm/pandoc/files/8692761/fx2.docx)

tested with pandoc version 2.18 on win11
`pandoc.exe "fx.docx" --self-contained --mathjax -o example35.html`

**Comment by jgm** [comment]
Word doesn't really represent blockquotes explicitly, so we have to guess at which paragraphs are block quotes. There is nothing in this Word file that really tells us that the bulleted list is inside the block quote.
Pandoc takes it to be outside the block quote.  (Yes, it is indented, but some people indent their outer level bulleted lists, so that doesn't tell you anything.)
