### ISSUE TITLE
raw HTML images within figure tag aren't exported from markdown to docx

### ISSUE THREAD

**Issue by jdescelliers** [jgm/pandoc#8083]
**Explain the problem.**
When converting from Github markdown to docx images from the markdown document are not included in the docx output, it works fine when converting from markdown to HTML, all images files are in the same directory as the source markdown file.

I'm using the `figure` and `figcaption` tags so I'm embedding real HTML in the source file like so

```html
<figure>
    <img src="my_image.jpeg" alt="My image">
    <figcaption>This is my image</figcaption>
</figure>
```

The images file format are all in theses file formats: jpeg, webm, png.

**Pandoc version?** 2.18 - MacOS Monterey 12.4 - ARM64

`pandoc --from markdown --to docx  --output my_file.html  my_input.md --standalone`

Is there anything I'm missing? If so, what?

**Comment by jgm** [comment]
Yes, you're missing the fact that raw HTML is only exported to HTML.
It is not parsed into pandoc's AST and then converted.
That is how it has always worked, and this has certain advantages (e.g., sometimes people may include both raw HTML and raw LaTeX for an element, knowing that only the appropriate one will be passed through to the output format).

The easiest workaround is just to use pandoc markdown's "implicit figures":

```
![This is my image](my_image.jpeg)
```

This will come across in a figure environment when translated to HTML (assuming it's by itself in a paragraph).

It's also possible to use a Lua filter to translate raw HTML blocks to pandoc AST elements.

**Comment by NeverBehave** [comment]
First, sorry for reopening this kinda old issue. 

I have similar issue exporting markdown to PDF using pandoc since raw HTML element such as `<img>` is not exported, and I am wondering how to deal with situation like we want to add some simple styles to the img, such as restrict the size of the image with attribute `width`. 

An concrete example would be `<img src="drawing.jpg" alt="drawing" width="200"/>`

I might be missing some configuration for styling etc. and any feedback would be appreciated.

**Comment by NeverBehave** [comment]
First, sorry for reopening this kinda old issue.

I have similar issue exporting markdown to PDF using pandoc since raw HTML element such as `<img>` is not exported, and I am wondering how to deal with situation like we want to add some simple styles to the img, such as restrict the size of the image with attribute width.

An concrete example would be `<img src="drawing.jpg" alt="drawing" width="200"/>`

I might be missing some configuration for styling etc. and any feedback would be appreciated.

---

For anyone came across this, since pandoc is just passthru elements and markdown is compiled into latex first, you can use latex in markdown to do this. 

```latex
\includegraphics[width=0.2\textwidth]{./my_image.jpeg}
```

**Comment by jgm** [comment]
>  I am wondering how to deal with situation like we want to add some simple styles to the img, such as restrict the size of the image with attribute width.

Pandoc's markdown allows you to specify these with attributes:

```
![drawing](drawing.jpg){width="200px"}
```

**Comment by jgm** [comment]
Centering isn't supported natively. You could enclose it in a fenced div with a class or style.
