### ISSUE TITLE
pandoc citation problem

### ISSUE THREAD

**Issue by tinainsz** [jgm/pandoc#8113]
Hi, 

I have two references which the authors have same last name:

> Zhao, K. (2015). The motivation behind China’s public diplomacy. The Chinese Journal of.
> Zhao, Q., & Lei, W. (2015). Blue book of public diplomacy—Annual report of China’s public diplomacy development (2015). Social Sciences Academic Press.

so my citation would be:

> [@zhao2015] 
> [@zhao2015a] 

With I turn .md into .docx, it covert to

> (Q. Zhao & Lei, 2015) 
> (K. Zhao, 2015)

However, in a APA style, it should be

> (Zhao & Lei, 2015) 
> (Zhao, 2015)

Is there any way to fix it?

Here is my .bib document:
[example.bib.zip](https://github.com/jgm/pandoc/files/8852000/example.bib.zip)

Thanks a lot!

**Comment by tarleb** [comment]
Could you ask the question again on the [pandoc-discuss mailing list](https://groups.google.com/g/pandoc-discuss)? We try to reserve this tracker for bugs and feature request; you'll get better support from a wider part of the community by asking on the mailing list. That's why I'm closing the issue here.

When you post there, please also include the command you use to run pandoc. And just to make sure, are you passing the APA CSL to pandoc?
