### ISSUE TITLE
New output format, like 'plain' but with color

### ISSUE THREAD

**Issue by phormio** [jgm/pandoc#8159]
## Request

I sometimes read CommonMark documents by doing:

```sh
pandoc -t plain doc.md
```

However, the output would be more readable if headings, italics, and bold had distinctive colors. So it would be nice if there were a new output format, `plain_color`, to be used as follows:

```sh
pandoc -t plain_color doc.md
```

## A complication

Because different terminals have different background colors, users would want a way to configure the colors.

## Previous discussion

I have read or scanned the following, none of which seem to say exactly what I am saying here:

* https://github.com/jgm/pandoc/issues/5580
* https://groups.google.com/g/pandoc-discuss/c/YIXfVrn0SzI/m/-DJ4s5g7f1IJ
* https://groups.google.com/g/pandoc-discuss/c/IABJMPqEmgE/m/7NiJS5t6WnAJ

**Comment by jgm** [comment]
If you're using commonmark, you can
```
cabal install commonmark-cli
```
or
```
and then
```
commonmark --highlight yourfile.md
```

stack install commonmark-cli
```

**Comment by alerque** [comment]
Since the proposal is not for an output format that is standardized anywhere or used by any other tooling I suggest this is out of scope.

I can understand the desire for an easy-on-the-eyes terminal reader, but there are lots of alternatives out there for this—particularly for Markdown. Besides the tooling already mentioned try piping markdown to `bat -l md`, `grip`, `mdv`, `mdless`, `mdp`, `mdr` (or any number of other terminal markdown viewers) or pipe HTML output to `lynx -stdin` or other `w3m -T text/html`.

**Comment by jgm** [comment]
I agree, this is not really in scope.

**Comment by tarleb** [comment]
For reference, here's another issue for this topic, and where we reached the same conclusion: #6772

**Comment by phormio** [comment]
Sorry for the delay in replying.

Yes, I now see that this feature would be out of scope.

Thanks for the suggestions. I have tried out a few and the best one seems to be @tarleb's [suggestion](#issuecomment-1172440449).

**Comment by dosmanak** [comment]
Perhaps  `patat -d file.md` could be helpful
https://github.com/jaspervdj/patat
