### ISSUE TITLE
Please allow disabling MathML in Epub3 output

### ISSUE THREAD

**Issue by jech** [jgm/pandoc#8164]
**Describe your proposed improvement and the problem it solves.**

Please provide a way for EPub3 output to use Pandoc's default math rendering (using basic HTML instead of MathML).  I am using LaTeX source where the maths have been carefully crafted to format fine with Pandoc's HTML formatter, and MathML breaks my output.

**Describe alternatives you've considered.**

Generating Epub2.  Generating HTML then converting it to Epub3.  Neither is satisfactory.

**Comment by jgm** [comment]
MathML is part of the EPUB v3 spec, so it should be supported by default. That's why we generate it and don't have an option.

You don't explain "MathML breaks my output."

**Comment by tarleb** [comment]
Workaround: use this [Lua filter](https://pandoc.org/lua-filters):

``` lua
function Math (m)
  return pandoc.RawInline(
    'html',
    pandoc.write(pandoc.Pandoc{m}, 'html', {html_math_method='plain'})
  )
end
```

**Comment by jech** [comment]
@tarleb that works for me, thanks a lot.  While I still feel that there should be a command-line option to avoid MathML in EPUB3, my immediate problem is solved, so feel free to close this issue.

**Comment by jgm** [comment]
It is irritating that many EPUB v3 readers don't conform to the spec.

I am open to providing an option, but it's tricky to see how to do it cleanly.  Currently pandoc's default is "fake it with unicode," and options like `--mathml` select non-default behavior.  So the cleanest way to allow options in EPUB v3 would be to have it default to "fake it with unicode," like the HTML writer, and only use mathml if `--mathml` is specified. The problem is that this change could break things for people currently using pandoc to generate EPUB v3, and relying on the mathml default.

**Comment by jech** [comment]
> It is irritating that many EPUB v3 readers don't conform to the spec.

To be fair, the spec includes all of HTML5 and CSS3, and, starting with EPUB 3.2, it no longer refers to a specific revision of HTML5: the spec grows larger as the web people add stuff to HTML5.  So there's no hope for a reader to implement the whole spec.

> it's tricky to see how to do it cleanly

Yes, I was surprised that there's no `--fake-math` option that reverts the effect of `--mathml` and friends.

**Comment by jgm** [comment]
I think the best approach here is to change the writer so that it no longer defaults to using MathML for EPUB v3.
This may be a breaking change for some users, so we'll have to advertise that they need to include `--mathml` explicitly.
But given the bad support for mathml in readers, I suspect there are not that many users who are relying on this behavior currently.
