### ISSUE TITLE
Pandoc generates corrupt docx files with trivial custom writer

### ISSUE THREAD

**Issue by svenboulanger** [jgm/pandoc#8313]
I wanted to write a custom writer for docx documents, and wrote the following:

```lua
local pandoc = require 'pandoc'

function Writer(doc, opts)
    return pandoc.write(doc, 'docx', opts)
end
```

As far as I understand from the documentation, this should be simply falling back to the original writer.

Note that the docx file is corrupt, but also changing the extension to ZIP results in a corrupt zip archive.

I am using pandoc v2.19.2.

**Comment by tarleb** [comment]
The problem is that custom writers are currently expected to be text writers, i.e., that they return UTF-8 encoded text. When binary data is returned, it will contain non-UTF-8 characters, and those will get mangled.

I plan to add support for a `BinaryWriter` function, but it requires some refactoring to the way PDFs are produced.

**Comment by tarleb** [comment]
The current development version allows to do this with

``` lua
function ByteStringWriter(doc, opts)
    return pandoc.write(doc, 'docx', opts)
end
```
