### ISSUE TITLE
reader option --indented-code-classes ignored by gfm reader

### ISSUE THREAD

**Issue by morganwillcock** [jgm/pandoc#8319]
**Explain the problem**
The reader option `--indented-code-classes` seems to be ignored by the gfm reader. Possibly that is an error, if not I cannot find any documentation which indicates that it isn't supported or why that would be. I don't think gfm offers any additional methods over Markdown to set metadata on an indented code block.

```
$ printf "    def\n" | pandoc -f markdown -t html --indented-code-classes=python
<div class="sourceCode" id="cb1"><pre
class="sourceCode python"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span></span></code></pre></div>
```
```
$ printf "    def\n" | pandoc -f gfm -t html --indented-code-classes=python
<pre><code>def</code></pre> 
```

**Pandoc version**
```
$ pandoc --version | head -n4
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
```

**Operating System**
```
$ uname -a
Linux hostname 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
```

**Comment by jgm** [comment]
This is because for gfm we use the commonmark-hs package for parsing (rather than implementing the parser directly in pandoc).  Commonmark-hs gives us an AST that indicates when we have a code block, but doesn't distinguish between indented and fenced code blocks, so there is no way to implement this for gfm.

**Comment by ffaf1** [comment]
@jgm can you tell me where in `commonmark-hs` parsing happens? I don’t think annotating a type with with a `Bool` would be difficult, maybe I can do it myself.

**Comment by jgm** [comment]
It's not difficult, but it's also not appropriate in an AST, since that is annotating the element with something about the concrete syntax used to produce it.

**Comment by jgm** [comment]
Actually, to be more precise, it is difficult.  The commonmark library uses typeclasses so that it is output-format agnostic; there's an IsBlock class with a `codeBlock` method, and this doesn't distinguish between indented and fenced (for the reason above).  commonmark-pandoc simply defines typeclass instances for the Pandoc AST, which also doesn't make this distinction.
