### ISSUE TITLE
pandoc latex output does not generate a xelatex compilable latex file if svg files are used

### ISSUE THREAD

**Issue by miguel-negrao** [jgm/pandoc#8334]
When compiling a markdown file to pdf which has svg files everything works well as the svg files are converted to pdf and are included in the intermediate latex file as pdf files.

When compiling the same markdown file to latex, the generated latex file cannot be compiled with xelatex as it cannot determine the size of the svg image.

The latex file generated during the run of the pdf file has :

```latex
\includegraphics[width=0.8\textwidth,height=\textheight]{/tmp/tex2pdf.-850fcfb7d76085ab/proc.pdf}\\
```

while the latex file generated with `-o file.tex` has

```latex
\includegraphics[width=0.8\textwidth,height=\textheight]{./imgs/proc.svg}\\

```

I believe the issue is present at least in versions 2.14 - 2.19.

I would expect that the latex file generated with `-s -o file.tex `would be the same latex file generated (in a temp file) with `-o file.pdf`, as this is what [is claimed by the manual](https://pandoc.org/MANUAL.html#creating-a-pdf). Shouldn't conversion of svg to pdf also be done for latex files ? If this is not desirable then I would like to have access to the temporary latex file created for the pdf to be able to use it with latexdiff. My end goal is to be able to produce a diff pdf for two markdown files using latexdiff.

**Comment by jgm** [comment]
> Shouldn't conversion of svg to pdf also be done for latex files ? 

Well, this conversion only makes sense if you're actually creating a PDF from the SVG. We can do that when we're making a PDF, because we're using a temporary directory and we can put the PDF there.  But when we're just making a LaTeX file our policy is not to make any other changes to the file system.

What we should probably do in the `latex` writer is add `\usepackage{svg}` to the preamble (must come after `graphicx`) and use `\includesvg` instead of `\includegraphics`.  The `svg` package will use inkscape to convert the svg to pdf on the fly.  I haven't really tried this out with all the engines, though.

In any case it's true that svgs won't work with `\includegraphics`.

> I would like to have access to the temporary latex file created for the pdf

One way to do this is to `--pdf-engine=latexmk --pdf-engine-opt=-outdir=foo`.  The temp files will then be in `foo`.

**Comment by miguel-negrao** [comment]
Thanks for looking at this !

I don't think using `--pdf-engine=latexmk --pdf-engine-opt=-outdir=foo` will work as the `image.pdf` file created by pandoc will have been deleted after pandoc finishes, so although I can have access to `input.tex`, I will not have access to the `image.pdf` created by pandoc. 

```
LaTeX Warning: File `/tmp/tex2pdf.-52e9ed73449d048f/proc.pdf' not found on inpu
t line 917.
```

Possibly the approach of adding native svg support in the generated latex file is the way to go ?

**Comment by jgm** [comment]
I've added the native svg support.  However, currently this won't be used when you go directly to PDF using pandoc.  There we rely on `rsvg-convert` and convert to png.  Perhaps this should now be changed to use the svg package, but then we'll need `inkscape` instead of `rsvg-convert`, and there may be other implications I'm not sure about.
