### ISSUE TITLE
Switch to commonmark_x as default

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#8391]
Not sure if this is too early, but with pandoc 3 in the works, would it make sense to seize the opportunity and switch the default format to commonmark_x?

**Comment by jgm** [comment]
It is too early, I think, because unfortunately `commonmark_x` doesn't have a `citations` extension. (It also lacks grid tables and lots of other things.)  So I think this would be a major breaking change for a lot of people, and not worth it.

I've had a devil of a time designing a commonmark-hs extension that deals with citations.
