### ISSUE TITLE
epub-chapter-level apparently not taken from metadata file

### ISSUE THREAD

**Issue by Iacobus1983** [jgm/pandoc#8426]
I've converted a tex file into epub with option `--epub-chapter-level 2`. Everything as expected.

Than, I've tried to pass the same option via `--metadata-file`, and `epub-chapter-level: 2
` in my yaml file. It seems it has no effect (other settings specified by the same yaml file, e.g. `toc-title:` or `css`, are applied correctly).

I'm using 2.19.2 on MacOs.

**Comment by jgm** [comment]
Command line options =/= metadata.  There is no reason to expect that this should work!  People get confused because there are a few cases in which (through coincidence of the implementation) you can get the same effect by putting something in metadata. For example, all the `--css` option does is set a metadata field (this is because citeproc was originally implemented as a filter and that was the only way to communicate the information).

What you want, perhaps, is a defaults file.
