### ISSUE TITLE
Provide a way to specify multiple base path for finding images, like TEXINPUT

### ISSUE THREAD

**Issue by bwl21** [jgm/pandoc#852]
I get a pandoc message 

```
pandoc: Could not find image `floating-image.pdf', skipping...
```

Would it be possible to make it a bit more expressive such as

```
pandoc: Could not find image `floating-image.pdf`, skipping ... 
               in "mytestfile.md line 1234, producing docx output
```

I was calling pandoc with multiple output formats, the problem only occurs while generating docx. The image file exists, but as it is a pdf, I guess pandoc cannot process it. If this is the case, pandoc should express that fact.

Pandoc could use ghostscript to convert it to a proper format, but that's another story (or another request:-)

**Comment by JJ** [comment]
Same error here when working from Markdown to epub

**Comment by senorhesles** [comment]
I'm having the same issue going from tex -> pdf. The pdf compiles fine using pdflatex, but using pandoc it says it can't find the image.

**Comment by jgm** [comment]
Now that we have a representation of resource path in CommonState, it will be easy to add an option like this.

**Comment by jgm** [comment]
Option could be called `--graphics-path`, `-I`, `--resource-path`?
And we need a convention for breaking it into parts: colon, semicolon, multiple options?

**Comment by JJ** [comment]
: is the most usual way to separate paths :-)

**Comment by bwl21** [comment]
yes, in unix-land; in windows, the like ":". 

AFAIK MikTeX accepts C:/foo/bar;X:/bar/foo; as a valid path. So I would support ";"

**Comment by SamuelePilleri** [comment]
I was about to open an issue on this very same problem.

I managed to hack-in this feature (LaTeX only) this way; the `graphics: true` forces the `$graphics` variable in LaTeX default template to be set to true, otherwise, if no image is included, `\usepackage{graphicx}` is not executed and that command in `header-includes` is invalid.

Directory structure:

```
 +--- sources
      |
      +--- images
      |    |
      |    +--- photo.jpg
      |
      +--- document.md
```

Markdown source:

```markdown
---
graphics: true
header-includes:
- \graphicspath{{./images/}}
---

![Image](photo.jpg)
```

Pandoc does produce an error, but the output is correct:

```
pandoc: Could not find image `photo.jpg', skipping...
```

Since this feature is quite similar to `--default-image-extension`, I think that could be managed in the same way (or just by appending random strings around).

Thanks to all devs and contributors for their excellent work.

**Comment by jgm** [comment]
Perhaps the directory of the first input file should be added automatically to the resource path.

**Comment by SamuelePilleri** [comment]
@jgm I suppose that with "first input" you mean "first file on the command line", in which case I think situations where the first input is a configuration file (ie. .sty, .yaml, ...) should be treated differently. However, that shouldn't be a huge problem since, in most cases, I guess it would just fail and fall back to other paths.

**Comment by jgm** [comment]
TODO:

- [ ] Make this work with PDF output.
- [ ] Automatically set the path, if the option is not specified, to include the path of the first input file. (And document that.)

**Comment by jgm** [comment]
Closed by 8c1b81bbef7125a9a2fde9d6894578f06bf4cedd

**Comment by chrisconlan** [comment]
This issue was the impetus for this project: https://github.com/chrisconlan/md_math_to_pdf

Built a python wrapper just so I could call `os.chdir(markdown_file_directory)` every time before running.

**Comment by antecede** [comment]
It is highly recommended that the PDF format of the picture prompt message alone some obvious!!
Instead of telling you that you can't find the file, it's better to automatically convert the PDF to JPG or PNG later.
At the same time \subfloat, this seed image skips directly without any hint and doesn't seem to find the corresponding PDF
