### ISSUE TITLE
Misplaced \noalign error when converting markdown to pdf

### ISSUE THREAD

**Issue by linquize** [jgm/pandoc#859]
using pandoc 1.11.1-66-g7d7c1f2
Win 7 x64

markdown to pdf error:

```
! Misplaced \noalign.
\newpage ->\noalign
                  {\break }
l.110 \newpage
```

`pandoc -s --toc --number-sections --no-tex-ligatures --latex-engine=xelatex -o bin\D.pdf bug.markdown`

```
\newpage

AAAAAAAAAAAA
============
This is the YYYYYYYYYY.

BBBBBBBBBBBB
============
--- --------------------------------------------------------------
AAA BBBBBBBBBBBBBBB
CCC DDDDDDDDDDDDDDDDD
DDD EEEEEEEEEEEEEE
FFF GGGGGGGGGGGGG
--- --------------------------------------------------------------

\newpage

CCCCCCCCCCCCCCCCCCCC
====================
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
---------------------------------

### EEEEEEEEEEEEEEEEEEEEEEEEEEE
--- ---------------------------
CC  XXXXXXXXXXXX
DD  YYYYYYYYYYYY
--- ---------------------------

### EEEEEE
--------------------------------------- ------------------------------------
FFFFFFFFFFFFF                           999999999999999
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG     111111111111111111111
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHU  8888888888888888888888888888888888
JJJJJJJJJJJJJJJJJJJJJ*                  5555
--------------------------------------- ------------------------------------
*MMMMMMMMMMMMMMMMMMMMMMM

\newpage

FFFFFFFFFFFFFFFFFFFF
====================
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
-----------------------------------------
HHHHHHHHHH
IIIIIIIIIII
JJJJJJJJJJJJ
KKKKKKKKKKK
```

**Comment by hernandik** [comment]
This bug is still present in PanDoc. I'm using version 2.5 and having this same issue

**Comment by jgm** [comment]
Still can't reproduce it, sorry!
If you can produce a minimal example sufficient to generate the bug (exact input and command line), we can open an issue.  (by the way, 2.5 is rather old - we're on 2.10.1 now)

**Comment by xradiation** [comment]
Just for future reference.

I have got somewhat similar error message to what's shown above, and am using linux with an up to date version of pandoc and latex distro.

The issue was multiple hashtags "#" I wrote on a table on a huge document, it took me a while to figure it out by removing the markdown section I suspected the most, compiling if it was successful I add a section or two from the removed sections and recompile again until I see the error message again, this allowed me to narrow down the problem to the specific issue I described earlier.

Best Regards
