### ISSUE TITLE
Fenced_divs extension causes pandoc to run extremely slowly for some input

### ISSUE THREAD

**Issue by bk** [jgm/pandoc#8820]
Here is a short input fragment which takes over two minutes to process on my Linux (x86_64, Intel i7) machine with pandoc 3.1.2:

```
::: abc.01

::: abc.02

::: abc.03

::: abc.04

::: abc.05

::: abc.06

::: abc.07

::: abc.08

::: abc.09

::: abc.10

::: abc.11

::: abc.12

::: abc.13

::: abc.14

::: abc.15

::: abc.16

::: abc.17

::: abc.18

::: abc.19

::: abc.20
```

It seems that each paragraph starting with `:::` causes the processing time to approximately double, since 16 items take about 7 seconds, 17 items take 15 seconds, and so on.

This is obviously related to the `fenced_divs` extension. When I turn it off with `pandoc -f markdown-fenced_divs`, the processing time drops to under 0.04 seconds.

Although this is an artificial example, there are many markdown documents "in the wild" that have been written for markdown variants that use `:::` for some reason or other, often in connection with a syntax extension of some kind. If one attempts to use pandoc (with the default settings) to convert such documents, the processing may be held up for a long time. One example of this is [here](https://github.com/mkdocs/mkdocs/blob/master/docs/dev-guide/plugins.md) in the MkDocs project documentation.

**Comment by tarleb** [comment]
Thanks for the report and the example. Yes, some of pandoc's parsers suffer from this kind of problem. See point 5 in the ["Security Notes" section of the manual](https://pandoc.org/MANUAL#a-note-on-security):

> Pandoc’s parsers can exhibit pathological performance on some corner cases. It is wise to put any pandoc operations under a timeout, to avoid DOS attacks that exploit these issues. If you are using the pandoc executable, you can add the command line options `+RTS -M512M -RTS` (for example) to limit the heap size to 512MB. Note that the `commonmark` parser (including `commonmark_x` and `gfm`) is much less vulnerable to pathological performance than the markdown parser, so it is a better choice when processing untrusted input.

And indeed, the `commonmark_x` parser has no problem with this input and succeeds within milliseconds.

This won't be changed in the default `markdown` parser, but it's quite possible that `commonmark_x` will become the default parser at some point. That's why I'm closing this – if you have suggestions on documentation changes, please let us know.
