### ISSUE TITLE
Underline tags/class not preserved/converted by markdown filters

### ISSUE THREAD

**Issue by xiota** [jgm/pandoc#8888]
Using Arch Linux.  Pandoc installed from repository.
```
pandoc 3.1
Features: +server +lua
Scripting engine: Lua 5.4
```

Underline tag is interpreted properly from html to markdown:
```bash
$ echo '<p>test <u>test</u> test</p>' | pandoc -f html -t markdown
test [test]{.underline} test
```

But not in round trips through the markdown filters (gfm, markdown, markdown_github, markdown_phpextra, markdown_mmd, markdown_strict).  For example:

```bash
$ echo 'test [test]{.underline} test' | pandoc -f markdown -t gfm
test <u>test</u> test

$ echo 'test <u>test</u> test' | pandoc -f gfm -t markdown
test `<u>`{=html}test`</u>`{=html} test
```

Related, the `<u>` tags do not produce underlined text when converting to other formats, like pdf, odt, docx, rtf.  In most cases, the `<u>` tag is entirely ignored with no styling in the output.

Not interested in reviving arguments about "proper" usage of `<u>` tags described in another issue.  Round trips through pandoc should preserve the underline class.

**Comment by jgm** [comment]
It wouldn't be expected that you can round-trip underlining through markdown formats that don't support it.

Sure, we could change things so that an Underline element came out in `gfm` as `<span class="underline">test</span>`, and that could roundtrip back to pandoc's markdown dialect. But it wouldn't show up as underlined text on GitHub, so I don't think that would be a good idea.

**Comment by xiota** [comment]
Underline is not preserved through *any* of the markdown filters: gfm, markdown, markdown_github, markdown_phpextra, markdown_mmd, markdown_strict.

Also not preserved by pdf, odt, docx, rtf.

Many of the formats do support underlining.  Even if a format doesn't support underlining, the class could be preserved and restored when converted to a fotmat that does sypport it.

**Comment by jgm** [comment]
These formats (not "filters") only support underlining via raw HTML.
Since `<u>` just means "raw inline HTML `<ul>`" in these formats, it is translated back to pandoc markdown in the same way.

pdf? We don't even have a reader so round-trip makes no sense there.

odt, docx, rtf: docx and rtf *do* round-trip this, in my tests.  odt converts it to emphasis. You could open an issue for this if it's a concern.
