### ISSUE TITLE
round tripping bracketed span appears to fail

### ISSUE THREAD

**Issue by njamescouk** [jgm/pandoc#8922]
$ type test.txt
    <span id="1">1</span>

    $ pandoc -f html -t markdown test.txt | pandoc -f markdown -t html
    <p>[1]{#1}</p>

    $ pandoc -f html -t markdown test.txt | pandoc -f markdown+bracketed_spans -t html
    <p>[1]{#1}</p>

I was expecting to get back to `<span id="1">1</span>`

This is pandoc 2.14.1 fwiw

**Comment by njamescouk** [comment]
the leading digit is the problem, `[1]{#l}` is fine.

**Comment by jgm** [comment]
No bug here. See how pandoc parses your input:
```
 % pandoc -t native
<span id="1">1</span>
[ Para [ Span ( "1" , [] , [] ) [ Str "1" ] ] ]
```
Because pandoc's markdown includes the `native_spans` extension, this is parsed as a Span element, not as raw HTML.  If you disable `native_spans`, it will be parsed (and passed through) as raw HTML (I'll also disable `raw_attribute` extension on the writer):
```
% pandoc -f markdown-native_spans -t markdown-raw_attribute
<span id="1">1</span>

<span id="1">1</span>
```
Another option is to disable the `bracketed_spans` extension on the writer:
```
 % pandoc -f markdown -t markdown-bracketed_spans
<span id="1">1</span>
<span id="1">1</span>
```
Anyway, the main point is that `[1]{#1}` is pandoc syntax for a span with an identifier "1", and you're getting this because the `<span id="1'>1</span>` is being parsed as a native Span and not as raw HTML.

**Comment by jgm** [comment]
Just to clarify: we don't guarantee syntactic round-tripping.  Your output may contain a different syntactic way of representing the same pandoc AST.  That's what happens in this case, as you can verify: 

```
% pandoc -t native
<span id="1">1</span>

[1]{#1}
[ Para [ Span ( "1" , [] , [] ) [ Str "1" ] ]
, Para [ Span ( "1" , [] , [] ) [ Str "1" ] ]
]
```

**Comment by njamescouk** [comment]
ok thanks for that
