### ISSUE TITLE
Markdown to docx conversion not using the images in the media folder

### ISSUE THREAD

**Issue by SarthakNarayan** [jgm/pandoc#8951]
**Explain the problem.**
I use 
```bash
pandoc --extract-media=./media -t markdown_mmd -s document-2.docx -o output-2.md
``` 
for converting my `document-2.docx` to `output-2.md`. I save the images in the `media` folder.

But when I try to convert docx to markdown using the command: 
```bash
pandoc --extract-media=./media -t docx -s output-2.md -o final-2.docx
``` 
I don't see the images that were present in `output-2.md` in the `final-2.docx`.

**Pandoc version?**
pandoc 3.1.4
Features: +server +lua
Scripting engine: Lua 5.4
OS: MacOS

**Comment by jgm** [comment]
`--extract-media` is for saving media in an input file to a directory.  You shouldn't use it as you're doing in the second command.  The second command ought to work if you drop the `--extract-media=./media` part.  Verify first that your media are in fact in the `media` directory, and that the image tags in `output-2.md` are referring to them at this path.

**Comment by SarthakNarayan** [comment]
It doesn't seem to work.
Here are all the commands that I ran.
I have a media directory and the images are referring to that.
<img width="524" alt="image" src="https://github.com/jgm/pandoc/assets/42849256/a37722e4-e09d-45bf-86b9-a9e6124bf563">

**Comment by jgm** [comment]
Here's the problem:  because you're choosing `markdown_mmd` as your output format, and because this format doesn't have a native way to represent width and height, pandoc is using raw HTML tags instead of a native markdown image link.

These will propagate unchanged to HTML, but if you're writing docx, they will just be ignored.

Solution is to use a markdown format that allows image attributes, like the default `markdown`.

A more complicated option would be to use a small Lua filter to strip out the width and height information that pandoc is getting when parsing the docx.

**Comment by SarthakNarayan** [comment]
Thanks a lot, it works.
