### ISSUE TITLE
Suppression raw_html does not attempt to convert it

### ISSUE THREAD

**Issue by riedel** [jgm/pandoc#8975]
**Explain the problem.**

Pandoc does not try to convert html when surpressing raw_html when converting from markdown to markdown. It does though when converting from html.
 
`printf '# test \n <a target="_blank" href="https://example.com/"><img src="https://example.com/test.png" style="height: 240px;" /></a>' |pandoc -f html -t gfm-raw_html`

outputs:
`\# test [![](https://example.com/test.png)](https://example.com/)`

vs.
 
`printf '# test \n <a target="_blank" href="https://example.com/"><img src="https://example.com/test.png" style="height: 240px;" /></a>' |pandoc -f gfm -t gfm-raw_html`

outputs only: 

`# test`

I expected:
```
# test

[![](https://example.com/test.png)](https://example.com/)
```

for reference:

`printf '# test \n <a target="_blank" href="https://example.com/"><img src="https://example.com/test.png" style="height: 240px;" /></a>' |pandoc -f gfm -t gfm`

outputs:
```
# test

<a target="_blank" href="https://example.com/"><img src="https://example.com/test.png" style="height: 240px;" /></a>
```

**Pandoc version**
```
exe 3.1.6
Features: +server +lua
Scripting engine: Lua 5.4
```

on windows

**Comment by riedel** [comment]
BTW: anyone reading this: a lua filter that actually emulates the expected behaviour would be very welcome (I somewhat failed half-way trying to call pandoc from the filter again)

**Comment by jgm** [comment]
You can see how this is parsed by using `-t native`:
```
% printf '# test \n <a target="_blank" href="https://example.com/"><img src="https://example.com/test.png" style="height: 240px;" /></a>' |pandoc -f gfm -t native
[ Header 1 ( "test" , [] , [] ) [ Str "test" ]
, Para
    [ RawInline
        (Format "html")
        "<a target=\"_blank\" href=\"https://example.com/\">"
    , RawInline
        (Format "html")
        "<img src=\"https://example.com/test.png\" style=\"height: 240px;\" />"
    , RawInline (Format "html") "</a>"
    ]
]
```
Raw HTML bits are then discarded because you disable `raw_html`.  The writers don't, in general, try to convert raw HTML when you disable `raw_html` -- raw HTML is just a passthrough format.

The reason it works differently with `-f html` is that the HTML parser can represent this in the pandoc AST:
```
 % printf '# test \n <a target="_blank" href="https://example.com/"><img src="https://example.com/test.png" style="height: 240px;" /></a>' | pandoc -t native -f html
[ Plain
    [ Str "#"
    , Space
    , Str "test"
    , SoftBreak
    , Link
        ( "" , [] , [ ( "target" , "_blank" ) ] )
        [ Image
            ( "" , [] , [ ( "style" , "height: 240px;" ) ] )
            []
            ( "https://example.com/test.png" , "" )
        ]
        ( "https://example.com/" , "" )
    ]
]
```

**Comment by jgm** [comment]
For a Lua filter, you'd want to:

- match RawInline "html" elements
- call pandoc.read on these
- extract the inline content from the whole document returned by pandoc.read
- return this instead of the raw HTML

There's a small example at https://pandoc.org/lua-filters.html#pandoc.read that might help.

In your case it's going to be complex, because you'd actually have to paste three adjacent RawInline elements together and then call pandoc.read.
