### ISSUE TITLE
HTML table parsing regression

### ISSUE THREAD

**Issue by kysko** [jgm/pandoc#8984]
After (very) belatedly updating pandoc on my system, I've noticed that a "venerable" HTML example, [planets-data.html](https://raw.githubusercontent.com/mdn/learning-area/main/html/tables/assessment-finished/planets-data.html) from `MDN`, wasn't being read correctly anymore. (It was once used as a test in pandoc, IIRC, but can't find it here anymore.)

I've managed to produce a minimal example:

```
<table>
  <tr>
    <th colspan="2">a</th>
    <td>b</td>
  </tr>
  <tr>
    <th>c</th>
    <th>d</th>
    <td>e</td>
  </tr>
</table>
```
The `colspan = 2` disapears upon reading, and a extra empty cell inserted.

I've traced this behavior back to [this commit](https://github.com/jgm/pandoc/commit/f257c97170ba8db3b771135b98b198d5de2bdb5b) that appeared in v. 3.1.4 (2023-06-24) (still present in 3.1.6).

From PR[#8634](https://github.com/jgm/pandoc/pull/8634):

> This PR will set RowHeadColumns to the minimum value of each row, to reduce such abnormal colspan cases.

By fixing one case, this breaks others.

~~I think that if any sense should be made of `RowHeadColumns` for a `TableBody`'s `body`, its value should be the sum of the colspans of headcells in a row (including silent colspan==1 of course), and should be the same for all rows in the `body`.~~**
*Otherwise*, if that value varies across the `body`'s rows, I don't think that value would have a sensible meaning, and a `body` cell's "heading" value should then be relegated to its attribute (and @liruqi seems to agree in his commit, if I understand well). Since it's probably a bit late for this kind of change (AST), maybe the html reader could put it itself in the attributes.

The PR above does mention a `Wikipedia` example where the `RHC` wasn't constant.

In any case, whatever the interpretation given to `RowHeadColumns`, *it should not* decrease a cell's colspan value, or insert new cells.
If a proper constant value for `RHC` across the `body`'s rows can't be found, then maybe just set it to 0 please, rather than changing the table's cell structure which I think is more important than a "header" affectation.

**/Edit: No, that doesn't work when there are row spans in that mix... but the gist of it is that it should be a constant value across the body, along one "true" column.

**Comment by jgm** [comment]
This bug appears to be due to an interaction between the aforementioned change to pandoc, which looked quite innocuous and minimal by itself, and some code in pandoc-types:
```hs
-- | Normalize the 'TableHead' with 'clipRows' and 'placeRowSection'
-- so that when placed on a grid with the given width and a height
-- equal to the number of rows in the initial 'TableHead', there will
-- be no empty spaces or overlapping cells, and the cells will not
-- protrude beyond the grid.
normalizeTableHead :: Int -> TableHead -> TableHead
normalizeTableHead twidth (TableHead attr rows)
  = TableHead attr $ normalizeHeaderSection twidth rows

-- | Normalize the intermediate head and body section of a
-- 'TableBody', as in 'normalizeTableHead', but additionally ensure
-- that row head cells do not go beyond the row head inside the
-- intermediate body.
normalizeTableBody :: Int -> TableBody -> TableBody
normalizeTableBody twidth (TableBody attr rhc th tb)
  = TableBody attr
              rhc'
              (normalizeHeaderSection twidth th)
              (normalizeBodySection twidth rhc' tb)
  where
    rhc' = max 0 $ min (RowHeadColumns twidth) rhc
```

**Comment by jgm** [comment]
@despresc added this code in pandoc-types and would be the best person to comment on this.

**Comment by kysko** [comment]
I do remember seeing this code a while ago, but I haven't learned haskell since, so can't decypher.
I naïvely thought the `RHC` was just a number passively retrieved from the set of rows, for possible use by a writer, so I wondered why changing how it is calculated might change cells...
But if it does have an influence in the "normalization" above, I begin to see the problem.

---

I think we can understand what the RHC should be ideally, the problem is that there are example in the wild that may test this model.

For example, the Wikipedia case cited by liruqi looks like:

```
<table>
  <tbody>
    <tr>
      <th colspan="2">name of person</th>
    </tr>
    <tr>
      <td colspan="2"><image/photo of person></td>
    </tr>
    <tr>
      <th scope="row">key1</th>
      <td>value1</td>
    </tr>
    <tr>
      <th scope="row">key2</th>
      <td>value2</td>
    </tr>
    ... etc...
  </tbody>
</table>
```

It is clear to me that the "name of person" should have been a table caption, or at least in a `<thead>`, the photo maybe in a `<tbody>` of its own, and the list of data in their own `<tbody>` with a clear cut value for the `RHC`... But the table above is valid nonetheless, it just doesn't fit in the ideal model.

**Comment by despresc** [comment]
I added that code when we expanded the table model. From what I recall, we debated between a more loose representation of tables (an HTML-style model that allows for head and data cells to appear anywhere) and more conservative extensions to what tables were before. We ended up going with something more conservative that presumes a single, consistent row head column value and no "holes" in any of the table sections. This is closer to vanilla LaTeX, I believe. As a result, we didn't add any tracking of the header/data cell distinction to individual cells. Pandoc must also modify HTML-style tables it encounters to conform to the model chosen, resulting in the grid structure changes and empty cells suddenly appearing. (Pandoc would need to do that regardless of the table model chosen - it's just that the current table model is more restrictive than HTML).

What all of that means is that given the current model, there will necessarily be some kind of data loss when encountering tables without a consistent row head column value. Your proposed fix (setting the row head column value to zero) should preserve the table's grid structure, but I think it would also turn all of the `th` cells in the rows of a table body into `td` cells, which is not ideal either. Maybe that's still better than changing the grid structure?

The behaviour of pandoc on your first example is consistent with the row head column value being inferred as 1, I think. (It trims the `a` cell to a width of 1, then inserts an empty cell at the end of the row because the first row is suddenly too short). That's definitely a bug, because the table clearly conforms to Pandoc's internal table model, with a row head column value of 2.

I also recall some form of the `planets-data` test being there when I was adding all of this code.

**Comment by despresc** [comment]
Since the model is how it is, changing the calculation from the maximum to the minimum won't actually avoid empty cells or grid structure changes. Having it be the maximum does mean that the shape of cells should never change - it's just that some empty cells might be inserted in the row head section of the table if the table doesn't conform to the model. Having it be the minimum will result in cells being cut down to fit the row head section in those cases, and empty cells might still be added to the rows (just at the very end of the rows).

**Comment by despresc** [comment]
I think the bug is in the HTML reader:

```haskell
-- | Parses a normal table row; returns the row together with the number
-- of header cells at the beginning of the row.
pRow :: PandocMonad m
     => TagParser m Blocks
     -> TagParser m (RowHeadColumns, B.Row)
pRow block = try $ do
  skipMany pBlank
  TagOpen _ attribs <- pSatisfy (matchTagOpen "tr" []) <* skipMany pBlank
  cells <- many (pCell block BodyCell <|> pCell block HeaderCell)
  TagClose _ <- pSatisfy (matchTagClose "tr")
  return ( RowHeadColumns $ length (takeWhile ((== HeaderCell) . fst) cells)
         , Row (toAttr attribs) $ map snd cells
         )
```

The row head width of an individual row is calculated by taking the *number* of row head cells (the `length`), when it ought to be the *sum* of their widths.

Actually, it can't really be the sum of their widths either, because some row head sections might appear artificially short due to cells in previous rows extending downward. Here, having the overall row head column value be the maximum instead of the minimum might be more sensible, as it would allow us to underestimate the widths of certain row's header sections and still produce something correct at the end if the table is model-conforming.

**Comment by kysko** [comment]
> We ended up going with something more conservative (...) This is closer to vanilla LaTeX.

Yes, and I expected this behavior thereafter. No problem with that.

> Your proposed fix...

Only in the context of the change which caught me by surprise once I updated!

My view (as a user) is that whatever the interpretation of the `rhc`, it shouldn't change the number of cells on the rows, nor their spans. In other words, if the `th` were changed to `td`, it shouldn't change the distribution of cells in the rows (although it might change the distribution of rows in the table sections). It seemed to me this is how the HTML model behaves... in fact, there's no `rhc` as such there.

> The behaviour of pandoc on your first example is consistent with the row head column value being inferred as 1, I think.

Before the change in 3.1.4, it gave an rhc of 2, which is what I expect: the sum of the head cells colspans was 2 for each row (no rowspan). The change gives it a value of 1.

> ...when it ought to be the sum of their widths

by "widths", you mean colspans, right?

> Actually, it can't really be the sum of their widths either,...

Yeah, that's the part I striked through in my original post...!
Maybe just infer it from the first row of the section, which wouldn't suffer from a rowspan from above?

**Comment by despresc** [comment]
> by "widths", you mean colspans, right?

Yes

> Before the change in 3.1.4, it gave an rhc of 2, which is what I expect: the sum of the head cells colspans was 2 for each row (no rowspan). The change gives it a value of 1.

Exactly. It being the maximum and not the minimum probably masked that latent bug in https://github.com/jgm/pandoc/issues/8984#issuecomment-1666467926 (which doesn't sum the widths of the cells at all) in a lot of situations. The row head column value should really be the maximum of the sum of widths. (Or some other estimate that is correct when given a table conforming to pandoc's model).

For the other part of the issue, maybe @jgm could comment on what sort of data loss is acceptable in this case (grid shape change and empty cell insertion, or cells changing between header and data). All of this could be avoided by adding handling for tables with a looser structure, but of course that would add complexity elsewhere.

(I haven't looked at https://github.com/jgm/pandoc/pull/8634 in detail, I should say).

**Comment by kysko** [comment]
By the way, I came across an interesting W3.org example with [offset row header cells](https://www.w3.org/WAI/tutorials/tables/two-headers/#table-with-an-offset-column-of-header-cells).

How would/could that fit in the model? Here, the rhc could be interpreted as the last (true) column within the (possibly spanned) cell headers, rather than a sum.
In 3.1.4, the rhc is 0 in this example, without any loss of data (th's simply became td's), so no problem.

(of course, not all cases can be covered, the example was just interesting in our context)

**Comment by despresc** [comment]
I don't know exactly what the current HTML reader does (I'm away from my computer at the moment), but I think it will put the first row in a table head and the rest in a table body. That would result in a row had column value of 0 according to both methods. Regardless, that would be a sensible way of constructing such a table from scratch internally.

**Comment by despresc** [comment]
If that table already has a `thead` and `tbody` then it should respect that and still end up with a value of zero.

**Comment by despresc** [comment]
It might be worthwhile to double-check that the other readers and writers actually interpret the `RowHeadColumns` value correctly, as a width and not number of cells.

**Comment by kysko** [comment]
The current (3.1.6) reader indeed ends up treating that table as if the th's were td's. The native output show rhc=0.

**Comment by despresc** [comment]
Skimming the reader code, it should have done that prior to the minimum/maximum change too.

**Comment by despresc** [comment]
The HTML writer (and hopefully the other writers) uses the `Text.Pandoc.Writers.AnnotatedTable.Table` type, which decorates the table with additional information (including inferring which cells in a body row are `th` cells). I had forgotten that I added that. There shouldn't be anything wrong with them, then.

**Comment by jgm** [comment]
> maybe @jgm could comment on what sort of data loss is acceptable in this case (grid shape change and empty cell insertion, or cells changing between header and data

I think that in cases where we can't preserve everything, we should definitely preserve grid shape. Header vs data is less important.

Do we have any consensus then on the best way forward?  One possibility would be to revert the change from #8634 and fix the [bug noted above](https://github.com/jgm/pandoc/issues/8984#issuecomment-1666467926) (at least taking account widths -- I don't know if we can easily take into account cells extending downward from above).  But maybe there is something better?

**Comment by jgm** [comment]
Looping in @liruqi who wrote #8634 and might have more comments.

**Comment by despresc** [comment]
> Do we have any consensus then on the best way forward? One possibility would be to revert the change from https://github.com/jgm/pandoc/pull/8634 and fix the https://github.com/jgm/pandoc/issues/8984#issuecomment-1666467926 (at least taking account widths -- I don't know if we can easily take into account cells extending downward from above). But maybe there is something better?

Reverting that and fixing the bug is probably for the best in the short term, because right now the reader doesn't work on tables that conform to pandoc's model.

As for preserving the grid shape, one difficulty is that the HTML reader doesn't have easy access to the shape of the table as it would be laid out on a grid while it's reading the table, so it's not so easy to detect when the row heads have varying widths in the general case. (As you said, cells extending downward complicate things).

Maybe we could add a separate function that produces a `TableBody` out of a more HTML-like input, so that it could internally lay out the table body on a grid and then just bail out and set the row head column value to zero if it detected that the row head widths varied across the rows. The main table builders could be modified to have that behaviour too, but that wouldn't be strictly necessary.

I can't think of anything better off the top of my head, given that we want to prioritize preserving the shape of the grid.

**Comment by jgm** [comment]
OK, I've pushed a bunch of commits:

- reverted #8764, but kept the test case
- fixed the bug in pRow noted above
- changed the algorithm so that it computes RowHeadColumns neither by min nor by max, but by consensus: all rows must have the same number of head columns, or RowHeadColumns = 0
- added a test case for this issue

The new algorithm gives good results both for the case in #8764 and for the test case above.

I think I'll leave this open, though, because we really need to handle the case with rowspans.
E.g.
```html
<table>
<tr>
<th rowspan="2">Heading</th>
<td>content</td>
</tr>
<tr>
<td>content2</td>
</tr>
</table>
```
This ought to be turned into a table with RowHeadColumns = 1, but we get RowHeadColumns = 0.

**Comment by kysko** [comment]
> Maybe we could add a separate function that produces a TableBody out of a more HTML-like input, so that it could internally lay out the table body on a grid

tarleb make a [grid representation](https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Writers/GridTable.hs) utility for the writers, and since the pandoc rows input is similar to html rows input, perhaps part of this could be adapted?

**Comment by jgm** [comment]
That `toTable` function takes a `TableBody` as input, and it just takes the row header column information from it.
So that won't help in the reader where we're trying to contruct the TableBody in the first place.
I think what we need to do is move calculation of row header columns from pRow to pBody -- we need to fold over all the rows, so we can take into account rowspans. The accumulator of the fold could be an array of Bool rows x columns, plus an index that tracks the current row.

**Comment by kysko** [comment]
Yes, of course, I didn't mean to use it as is, but adapt it, as a response to despresc's comment, especially `rowsToPart` which has a familiar looking algorithm. But maybe I shouldn't comment on code I can't thoroughly read! 😄 

Anyways, it seems you're on the right track to solve this, so looking forward to it.

Thanks to both of you.

**Comment by jgm** [comment]
I think I've got it working now. We handle the rowspan case and all of the other cases that have been mentioned here.
