### ISSUE TITLE
Man output gives font warning with latest man and groff

### ISSUE THREAD

**Issue by hickford** [jgm/pandoc#9020]
**Explain the problem.**

Pandoc's man output for code blocks and inline code is incompatible with the latest man and groff, giving warnings about fonts such as  "warning: cannot select font 'CB'" and "warning: cannot select font 'C'". 

I am using GNU troff (groff) version 1.23.0.    This issue did not occur with earlier versions of groff.

Pandoc command `pandoc example.1.md -t man -o example.1 --standalone`

Input `example.1.md`:

    Paragraph with `inline code`

    ```
    Code block line 1
    Code block line 2
    Code block line 3
    ```

Output `example.1`:

```
.\" Automatically generated by Pandoc 3.1.6.1
.\"
.\" Define V font for inline verbatim, using C font in formats
.\" that render this, and otherwise B font.
.ie "\f[CB]x\f[]"x" \{\
. ftr V B
. ftr VI BI
. ftr VB B
. ftr VBI BI
.\}
.el \{\
. ftr V CR
. ftr VI CI
. ftr VB CB
. ftr VBI CBI
.\}
.TH "" "" "" "" ""
.hy
.PP
Paragraph with \f[V]inline code\f[R]
.IP
.nf
\f[C]
Code block line 1
Code block line 2
Code block line 3
\f[R]
.fi
```

Run man command with warnings `man -l example.1 | grep warn`

    troff:<standard input>:5: warning: cannot select font 'CB'
    troff:<standard input>:23: warning: cannot select font 'C'

This warning is non-fatal. The man page looks okay to me.

**Pandoc version?**

pandoc 3.1.6.1 on Linux

**Comment by jgm** [comment]
That's quite weird, but I can't see how it could be a bug in pandoc. You should report this to groff. Looking quickly at the changelog for 1.23, I didn't see anything relevant, but you might look more carefully before reporting.

**Comment by hickford** [comment]
@jgm Thanks for taking a look. I'll report this to groff.

**Comment by ischwarze** [comment]
Pandoc is obviously generating lots of bogus code.

1. No manual page should ever attempt to fiddle with low-level formatting details like setting font names.  Preferably, use font macros like .B and .I and font alternation macros.  On those output lines where that isn't possible, which happens in man(7) code generators in some situations, use the standard font escapes: \fB \fI \fR \fP \f(CB \f(CI \f(CR.  Using .ftr is always an extremely bad idea.  For example, mandoc(1) completely ignores that request, meaning that none of the fonts you desire will be used in any output mode, all text will always end up in \fR.

2. In general, avoid conditionals in manual pages.  Do not use .if and .ie.  If you feel a temptation to insert a conditional request into the source code of a manual page, it's usually a symptom of a layering violation, a warning sign that you are about to manipulate low-level implementation details that are better left to the formatter.  When people try to use such low-level roff requests, the end result is almost never portable.

3. Never insert any hyphenation request into the source code of any manual page.  That's a detail that should be left to the formatter.

4. Emitting .PP right after .TH or .SH is a no-op with groff and mandoc.  With other formatters, it could potentially create excessive vertical spacing.

5. A font named "C" usually does not exit, on no formatter and in no output mode.  There may be rare exceptions where it happens to be defined for some weird reason, but in most cases, it is not.

Fiddling with such low-level implementation details guarantees that your output is not portable, neither between different formatters nor between subsequent releases of the same formatter.

While not quite as dire as the above points, using the GNU escape syntax \f[...] is not a particularly good idea.  While most modern formatters support that, it is less portable than using the standard syntax \fB and \f(BI.  Finally, note that while the CB CI CR fonts will usually be available on most modern formatters, using them is more risky than using \fB \fI \fR only.  The C fonts are notoriously error-prone.  Whenever you can, use semantic markup like .EX/.EE.  Yes, that is also slightly risky because a few very uncommon formatters might not provide it, but it is still significantly more robust than trying to manually fiddle with CX fonts.

The discussion whether the particular regressions you see here are pandoc's fault or groff's fault is partially moot.  As long as you poke so deeply into language internals and implementation details, you can bet that you will often see all kinds of misformatting and regressions.

Maintainer of mandoc(1) and maintainer of the groff(1) port in OpenBSD speaking, see: https://mandoc.bsd.lv/

**Comment by jgm** [comment]
Perhaps there are ways to improve pandoc's man output, and we're happy to hear them. But this doesn't explain why this warning is suddenly popping up after this particular groff release.  I'd like to understand that.

My main resource in designing the current man and ms writers were the man pages themselves.  `groff_man(7)` refers you to `groff(7)`.  `groff(7)` lists both `\f(fo` and `\f[font]` as syntaxes for changing fonts.  It also says that `CB` is the font name for constant-width boldface.  So the man page itself certainly suggests that `\f[CB]` should work.  So, why the warning about this (which is just coming up now and has not been reported before)?  What changed in this groff release?

I take the point that `C` is not one of the standard font names, and I will fix that.

Regarding the conditional and low-level formatting you object to at the beginning: the motivation for this is described in #7506, in response to a request from @joeyh, who quite reasonably wanted a visible distinction between code blocks and regular text in a terminal viewer. I wanted to accommodate that by displaying code in boldface, but I didn't want to give up displaying code in a typewriter font when the man page was rendered to HTML. So the intent of this code was to define a font for code blocks that will render as boldface when viewed in the terminal but as monospace when the man page is rendered to HTML. Perhaps this is too fancy a thing to want, but groff man *does* ship with an HTML renderer. Probably we should revert this fanciness and just use `\f(CB`.

The `.hy` is conditional on the `hyphenate` variable.  We are defaulting this to true but should probably default it to false, given what you say.

**Comment by jgm** [comment]
Using `.EX`/`.EE` is also a good idea and I can't recall now whether we didn't do that for a reason or out of ignorance.

**Comment by jgm** [comment]
Experimented with using
```
.IP
.EX
....
.EE
```
for a code block.  Unfortunately, when you process it with `groff -man -Thtml`, it renders as a regular paragraph in the normal font rather than a `<pre>` in a monospace font.  That may be why I didn't use it in the first place.

**Comment by jgm** [comment]
Looking at some man pages on my system, I note that zipinfo.1 actually defines the .EX/.EE macros itself:
```
.de EX
.in +4n
.nf
.ft CW
..
.de EE
.ft
.fi
.in -4n
```

The awk.1 man page also defines `.EX` itself, and then uses it in conjunction with low-level font commands like `.ft CW`.

certtool.1 man page also defines `.EX` and `.EE` before using them.

The perl man pages start with huge conditional macros.  For code blocks they use a custom macro `.Vb` that they define in the page itself, using again `.ft CW`.

Nobody seems to rely on `.EX` without defining their own...

**Comment by jgm** [comment]
I remembered why we use the `\f[CR]` form instead of `\f(CR`.
We sometimes need three letters, e.g. for text that is bold, italic, and monospace we use `\f[CBI]`.  This seems to work -- although the monospace/non-monospace distinction isn't visible in the terminal, `groff -Thtml -man` yields `<tt><i><b>`...

**Comment by ischwarze** [comment]
Hello John,

for the latest groff release, G. Branden Robinson, among other things, did lots of work improving warnings.  For example, \f[C] never really worked reliably, but groff did not warn.  Now, you get the warning because groff now warns about something that didn't work in the past, either.  mandoc(1) has also been warning about that for some time:

     $ echo '\\f[C]' | mandoc -T lint
    mandoc: <stdin>:1:1: WARNING: invalid escape sequence argument: \f[C]

I'm not quite sure why you get a warning about CB.  Then again, that's on the .ie line, and comparing strings with and without font escapes to find out anything about those font escapes is totally non-portable in the first place.  For example, mandoc won't even consider "\fRtext\fP" equal to "text".  So i don't think you should worry about that specific CB warning.

Regarding following groff(7) documentation - obviously, GNU troff documentation documents GNU features, and those are portable to varying degrees, some more, some less.  All the same, groff_man(7), in addition to documentating than man(7) language itself, also contains various bits of portability advice.  For example, groff_man(7) talks about single-letter \fB \fI \fR \fP but not about \f[] for a reason.  Also note that groff_man(7) does not even mention \f(CB, let alone \f[CB].  If you rely on groff(7) in addition to groff_man(7), it should not come as a surprise that your output will be GNU-specific and not portable.

The groff HTML output device produces output of atrocious quality.  That's due to technical limitations in the fundamental way roff works and very hard to improve.  In particular, grohtml(1) cannot produce "pre"-tags or any other semantic HTML.  The best ist can do it produce physical formatting tags like "B" and "I" tags.  If you try to tweak low-level details of your output to work better with grohtml(1), that's guaranteed to ruin the quality of your code, but won't result in good HTML output either way.  If you want good HTML output from manual pages, you really have to use mandoc(1) - for example, mandoc -Thtml produces "pre"-tags from .EX, leaving font selection to CSS (and browser defaults, which are usually reasonable).  Trying to manually tweak fonts in the manual pages source code in order to get good HTML output is completely hopeless.

Regarding .hy - just leave it out completely in all cases, no matter whether some "hyphenate" variable is set in your pandoc input or not.  Maybe in your pandoc input language, it makes sense to give users a choice whether they want automatic hyphenation or not.  But in man(7) code, any attempt to translate that choice will not be portable, most likely have no effect whatsoever, or possibly even cause trouble with some formatters.  Not every feature can reasonably be translated from one language to another.

The reason why you did not use .EX probably is (just guessing!) that twenty years ago, it was not particularly portable.  Few people used AT&T Ninth Edition Unix which invented it, so around 1995-2000, it was mostly available via esr@'s man-ext package and in GNU troff.  But nowadays, it is relatively widely supported - certainly less fragile than trying to manually manipulate fonts, in particular C fonts.

Defining .EX in individual manual pages was what esr@ recommended twenty years ago.  I never considered that particularly sustainable advice.  Back than, you could perhaps argue that it helped some formatters some people used back then, but it always was a terrible kludge at best.  Today, formatters that might profit in any way are extremely rare, but you risk trouble with modern formatters that include good implementations of .EX.  Redefining something that is already part of the language risks clashes, and even worse, bundled implementations are almost never maintained, get outdated when the formatters are improved, so you end up with worse output on the most common formatters if your own bad implementation overrides the good implementation in the formatter.

CW ("constant width") is a historical name for CR that was widely used before people started also using CB and CI.  If all you want is *one* C font, than \(CW could possibly be minimally more portable than \(CR, but i don't really know whether any formatters still exist that understand \(CW but not \(CR.  If you use \(CB or \(CI, than using \(CW makes no sense because it is extremely unlikely that any formatter understands \(CB but not \(CR.

Yes, the perl manual pages contain a huge preamble generated by the pod2man(1).  According to what i said, it should not be there.  However, that's the only instance of such a low-level roff preamble i have ever seen that causes relatively little trouble in practice.  I'm unsure why that is.  Probably a combination of that particular code being extremely stable - the pod2man(1) maintenance team almost never tinkers with it, certainly not in ways causing new compatibility issues - and Russ Allbery commanding exceptional roff skills.  Certainly not everything in that preamble works on all formatters, but somehow, it seems very carefully crafted such that even if some parts of it don't work somewhere, the fallout is relatively harmless and the page still mostly readable.  I have often seem other teams attempt similar feats, but none ever managed to. Certainly not the DocBook team, certainly not pandoc, certainly not rst2man, and i think there are several others the names of which i don't recall right now...

**Comment by ischwarze** [comment]
> I remembered why we use the `\f[CR]` form instead of `\f(CR`. We sometimes need three letters, e.g. for text that is bold, italic, and monospace we use `\f[CBI]`. This seems to work -- although the monospace/non-monospace distinction isn't visible in the terminal, `groff -Thtml -man` yields `<tt><i><b>`...

I wouldn't be surprised if GNU troff is the only formatter supporting a CBI font.  Regarding portability, that's significantly worse than even \f[CB].  For example, in mandoc(1), \f[CBI] is the same as \fR:

     $ echo '\\f[CBI]' | mandoc -T lint
    mandoc: <stdin>:1:1: WARNING: invalid escape sequence argument: \f[CBI]

Besides, for which semantic purpose would you want to use a font that is CW, bold and italic at the same time?  Off the top of my head, i can't think of any reasonable use case.  Probably, the reason why mandoc(1) does not support it is that i have never seen it used in practice, whereas CB, CI, CR (and CW) do occasionally occur in real-world manual pages.
Not every feature that can be constructed by generalizing some physical formatting rules actually makes sense for practical purposes...

**Comment by g-branden-robinson** [comment]
> Perhaps there are ways to improve pandoc's man output, and we're happy to hear them. But this doesn't explain why this warning is suddenly popping up after this particular groff release. I'd like to understand that.

Hi jgm,

I replied at some length at https://savannah.gnu.org/bugs/index.php?64594 .

**Comment by jgm** [comment]
Thank you both for the detailed explanations and advice!

I would very much like to use .EX/.EE, but when I try it on my system (macos), it doesn't seem to give me the formatting I want.  It doesn't give me a blank line between it and surrounding content, or indentation, or (I think) a monospace font. (That's a bit hard to tell just from the terminal, but I tested with `-Thtml` which does seem to make the distinction.)  I wonder what the default definition of these macros is?  I tried redefining them but the definition I provided was simply ignored (maybe because you can't redefine built-in macros?).  I can define a macro with a new name, and that works.  Am I missing something?

> Besides, for which semantic purpose would you want to use a font that is CW, bold and italic at the same time? 

I'm sure you can get by very well without this in man pages, but pandoc is charged with converting things, and these things might include bold italicized monospace content.  So, I'm faced with the question what to do if the content I'm converting has all three properties.  I can produce non-portable `\f[CBI]` or I can simply ignore one of the features and produce something more portable. I'm not sure what's best here.

(Also, I should mention that I share some of the font handling code between the man and ms writers, in Text.Pandoc.Writers.Roff.  Certainly in ms we want to support CBI.)

**Comment by jgm** [comment]
As for V, it's still kind of nice to allow users to change the rendering of inline code by modifying something in the template, so I like the idea of this "font alias" if there's a way to make it work portably.

The suggestion
```
.\" Automatically generated by Pandoc IN AN IMAGINED FUTURE
.\"
.\" Remap Courier family to bold styles on terminals for
.\" visibility inline.
.if \n(.g .if n \{\
. do ftr CR B
. do ftr CI BI
. do ftr CB B
. do ftr CBI BI
.\}
```
does not give us quite the same flexibility, because it will also affect code blocks (not just inline code).  The current behavior boldfaces inline code but not code blocks -- aesthetically, bolding whole code blocks is pretty heavy and it's not necessary for distinguishing them from regular text, because they're indented and set off.

**Comment by g-branden-robinson** [comment]
Hi John,

I hope I can be of further assistance!  Let's find out...

> I would very much like to use .EX/.EE, but when I try it on my system (macos), it doesn't seem to give me the formatting I want. It doesn't give me a blank line between it and surrounding content, or indentation,

These are deliberate.  Ninth Edition Unix `EX`/`EE` didn't work that way, so ours doesn't, and sometimes you don't want vertical space or increased indentation.  You can compose what you need with the existing macros.

For spacing, use `P` (or `PP`, or `LP`) macros.

`RS` and `RE` are for relative insets.  They _do_ indent but they can be counterintuitive to use in one common application: setting a code example "within" an indented paragraph.  _groff_man_(7) in _groff_ 1.22.4 speaks to this issue a little bit (".RS doesn’t indent relative to my indented paragraph") and the _groff_man_style_(7) page in _groff_ 1.23.0 at much greater length, with examples ("Horizontal and vertical spacing").

Long story short (I hope): keep track of whether your previous paragraph used `TP` or `IP` (or not).  If it did, indent _twice_, then undo the indentation once after the end of the code block, then a second time at the end of the paragraph.

```
$ nroff -k -man <<EOF
.TH foo 1 2023-08-25 "groff test suite"
.SH Description
Foobar.
.IP
Blah blah blah.
You can fribulate the gonkulator like this.
.RS
.RS
.P
.EX
x[⍋x←6?40]
.EE
.RE
.
.P
Wasn't that great?
.RE
.P
Bazqux.
```

I apologize for the weirdness of it; it's compatible with Doug McIlroy's design of the _man_ package in 1979 (probably 1978, actually) for Seventh Edition Unix.  There is another approach you might like (or be able to transform to) better discussed in the _groff_man_style_(7) page that would have you using `RS` more frequently but also more symmetrically.

> or (I think) a monospace font. (That's a bit hard to tell just from the terminal, but I tested with `-Thtml` which does seem to make the distinction.)

Yeah, on the terminal _everything_ is monospaced, unless you hate your eyeballs.  ;-)

> I wonder what the default definition of these macros is?

You can find _groff_'s in [its _an-ext.tmac_ file](https://git.savannah.gnu.org/cgit/groff.git/tree/tmac/an-ext.tmac?h=1.23.0#n160).  It has some extra complexity involving register tests to (1) make it easy to run our automated test suite on it and (2) accept a proposal from Ingo that the `EE` macro be forgiving of user error.

> I tried redefining them but the definition I provided was simply ignored (maybe because you can't redefine built-in macros?). I can define a macro with a new name, and that works. Am I missing something?

You _can_ redefine them (except for `TH`, to which you can only append), but you have do so *after* calling `TH` or the _andoc.tmac_ macro file, which is a recommended best practice for everyday man page viewing, will clobber them.

_groff_man_style_(7) says:

          Except for .SB, definitions of macros described above as
          extensions are contained in this file; in some cases, they are
          simpler versions of definitions appearing in an.tmac, and are
          ignored if the formatter is GNU troff.  They are written to be
          compatible with AT&T troff and permissively licensed—not
          copylefted.  To reduce the risk of name space collisions,
          string and register names begin only with “m”.  We encourage
          man page authors who are concerned about portability to legacy
          Unix systems to copy these definitions into their pages, and
          maintainers of troff implementations or work‐alike systems
          that format man pages to re‐use them.

          The definitions for these macros are read after a page calls
          .TH, so they will replace any macros of the same names
          preceding it in your file.  If you use your own
          implementations of these macros, they must be defined after
          .TH is called to have any effect.  Furthermore, it is wise to
          define such page‐local macros (if at all) after the “Name”
          section to accommodate timid makewhatis or mandb
          implementations that may give up their scan for indexing
          material early.

> > Besides, for which semantic purpose would you want to use a font that is CW, bold and italic at the same time?
> 
> I'm sure you can get by very well without this in man pages, but pandoc is charged with converting things, and these things might include bold italicized monospace content. So, I'm faced with the question what to do if the content I'm converting has all three properties. I can produce non-portable `\f[CBI]` or I can simply ignore one of the features and produce something more portable. I'm not sure what's best here.

I think you can go ahead with the `CBI` font for non-man-page purposes.  Getting that combination to port to any non-_groff_-compatible implementation is going to be a tough roe to how for more reasons than just the "long" 3-character name.

> (Also, I should mention that I share some of the font handling code between the man and ms writers, in Text.Pandoc.Writers.Roff. Certainly in ms we want to support CBI.)

Yes indeed.  Device-independent _troff_ was a handful of years too early for the PostScript revolution, with its standardized families and styles, to impact its design.

Regards,
Branden

**Comment by g-branden-robinson** [comment]
> As for V, it's still kind of nice to allow users to change the rendering of inline code by modifying something in the template, so I like the idea of this "font alias" if there's a way to make it work portably.

The question that we have to address is: _how_ portable do you seek to be?

AT&T _troff_ didn't have any concept of document-defined fonts.  The font repertoire was a property of specific output devices (driver programs), and it had no facility for querying that repertoire or even reporting what the currently selected font was by name.  I think it was the Python Docutils maintainer who said recently that portability to the aforementioned trio: _groff_, Heirloom Doctools _troff_, and _mandoc_) was a comfortable horizon for him.  If you want to reach Plan 9 and Solaris _troff_s, or Documenter's Workbench 3.3 _troff_, more work will be cut out for you.  Maybe I can think of some tricks--but I fear they will look ugly, confusing, and unmotivated in the output.  ('Course, you can always write _roff_ comments to accompany the cleverness.)

Let me know how ambitious you want to be and I'll offer the best advice I can.

> The suggestion
> 
> ```
> .\" Automatically generated by Pandoc IN AN IMAGINED FUTURE
> .\"
> .\" Remap Courier family to bold styles on terminals for
> .\" visibility inline.
> .if \n(.g .if n \{\
> . do ftr CR B
> . do ftr CI BI
> . do ftr CB B
> . do ftr CBI BI
> .\}
> ```
> 
> does not give us quite the same flexibility, because it will also affect code blocks (not just inline code).

That's true.  I wince to suggest it, but I suppose you could stuff the above into a macro, write another to unwind it, and then call them in inverted order by appending to the existing `EX` and `EE` macros.  Details available on request.

> The current behavior boldfaces inline code but not code blocks -- aesthetically, bolding whole code blocks is pretty heavy and it's not necessary for distinguishing them from regular text, because they're indented and set off.

I agree.  It would make for eye strain, or at least give typographically sensitive people the vapors.

Regards,
Branden

**Comment by jgm** [comment]
Thanks very much for all of that; it really clears up a lot of my questions!  Am I understanding correctly that, if I just want to target the trio groff / mandoc / heirloom doctools troff, then defining a custom font `V` for inline verbatim is still okay?  That seems cleaner than the unwinding-macro approach you sketch above.

**Comment by g-branden-robinson** [comment]
> For terminal output, mandoc(1) discards the font family "C" and maps CB -> B, CI -> I, CR -> R. For HTML output, mandoc generates "pre"-tags from .EX, so the font depends on whatever CSS you are using, or on your browser defaults.

That's what _grohtml_ does, and I am not sure of the wisdom of that choice; for things that *aren't* man pages, changing the semantics of input line breaks (meaning: in the HTML document) seems like a terrible idea.

> If you are producing man(7) output, i think it's better to emit \f(BI, which will work on most modern formatters,

Yes.  I resort to it myself in _groff man_ and in a very few cases in our man pages (the only example I can think of is in _grotty_(1), to illustrate that face's availability with that driver).  It's not portable to Seventh Edition Unix or Unix System III.  But those are 40+ year old systems.  The PostScript revolution I mentioned above _did_ have an impact, so

The exception is formatting for TeX DVI; Knuth's Computer Modern faces had constant-width upright and italic forms, but not heavy (bold) variants thereof.  [We have bespoke logic in _groff_'s _an.tmac_ to cope with this](https://git.savannah.gnu.org/cgit/groff.git/tree/tmac/an.tmac?h=1.23.0#n1016), since it's the only output driver thus afflicted.  So far, no one using alternative fonts with _grodvi_(1) has complained that we're cramping their style.

Heck, if someone is using _grodvi_ *at all*, I'd like to hear from them.

> rather than emitting \f[CBI], which is equivalent to \fR on some widely used formatters

I trust you mean that it produces equivalent output, because the font selection can't be honored.

> and likely to cause warnings on top of that.

And thus do we get squarely back on topic. ;-)

> I'm not sure what people use ms(7) for nowadays, and which software they use for that. Your argument that you want to support \f[CBI] in ms(7) output may be fair enough: i guess that most people using ms(7) are likely using groff, where that works. My first idea of a user group where \f[CBI] might cause trouble even in ms(7) output is Plan 9 users.

I expect _ms_ document authors on Plan 9 use its _troff_, since _groff_'s _ms_ implementation is hopelessly entangled with GNU _troff_ extensions.  When updating [Larry Kollar's _ms.ms_ document](https://git.savannah.gnu.org/cgit/groff.git/tree/doc/ms.ms?h=1.23.0), I was careful to document all extensions in the macro language itself.  John, you might be interested in that document as well.

> There may be other examples, for example commercial UNIX systems like Solaris, HP-UX, or AIX.

Interestingly all of these have come up on the _groff_ list in the last few months.

We know that Solaris dropped its _troff_ for _groff_ in Solaris 11, which was released...over a decade ago now?  Solaris 10 is in hospice care; its date of execution has been postponed to January 2025--I think by the personal command of Larry Ellison specifically to spite my plans for designating a portable dialect of _roff_.

>shakes fist impotently<

I don't know if HP-UX still supports its Unix System V _troff_, but I can say that they got _groff_ 1.23.0 ported *really fast*.  Like, within a week.  I once could say I had friends at HP, but I think they're all retired now.  The more likely explanation is that they actually care about it, maybe because they use it.

Mike Fulton of IBM has been in touch with us, too, and I don't remember if he said they still had their System V _troff_, too--I was too gobsmacked by the fact that we could get rid of CCSID ("code page") 1047 support.

> Either way, using one feature in one output language doesn't imply that using the same feature in another output language is necessarily a good idea. I have a hard time thinking of any users who might profit from having \f[CBI] in manual pages, but i can easily think of lots of users who will be hurt by that.

It does seem like an unusual case.  If one follows my recommendations in _groff_man_style_(7), one would need to have an I/O example that was parameterized in user input.  Typically, man page examples are not that demanding of the reader's metacognition.

John, please rein me in at any time--I know I have a tendency to ramble.

**Comment by ischwarze** [comment]
> Thanks very much for all of that; it really clears up a lot of my questions! Am I understanding correctly that, if I just want to target the trio groff / mandoc / heirloom doctools troff, then defining a custom font `V` for inline verbatim is still okay?

No, you misunderstand: mandoc(1) does not support .ftr at all:
https://man.openbsd.org/roff.7#ftr  says:

    ftr newname [oldname]
        Translate font name. This is a groff extension and currently ignored.

Consequently, with mandoc, \fV is the same as \fR and also causes a warning message.

The mdoc(7) macro package provides the .Ql macro exactly for this purpose: https://man.openbsd.org/mdoc.7#Ql
In terminal output, .Ql encloses in single quotes.  In typeset (e.g. PDF) output, it uses a CW font and additionally encloses in single quotes if the argument is very short because the reader might then overlook the font change.  In HTML output (of course, mandoc(1) only, as groff doesn't provide a HTML output device good enough for real-world use), .Ql produces an element (code class="Li").  The "code"-tag provides reasonable (typical CW) formatting by default, and the "class"-attribute allows additional customization using CSS.

But the older man(7) language does not provide any similar functionality, not even if you are willing to aggressively use all GNU extensions.  Consequently, the best solution i can think of would look something like this:

    .PP
    This paragraph contains
    \(oq\f(CRinline code\fP\(cq
    in the middle.
    .PP

I expect that to be quite portable, even beyond the big three.
Obviously, mandoc cannot produce a "code"-tag from that, but that's a limitation of the man(7) language and not mandoc(1)'s fault.

> That seems cleaner than the unwinding-macro approach you sketch above.

Indeed, defining your own macros in a manual page sets you up for a trip on the highway to hell (pod2man being the singular exception that confirms the rule rather than casting doubt on it, as discussed), and defining a custom macro to wrap standard ones sounds even worse.  Even Branden, who usually tends be bolder and less timid with respect to compatibility questions than i am, was visibly shaking when reluctantly considering whether he should really provide such advice.  :-o

> (EDIT: Of course, another alternative would be for pandoc just to hardcode `CB` for inline verbatim code; the only disadvantage this has is that this decision couldn't be changed by modifying the template.)

I think enclosing in single quotes is less intrusive and less confusing than switching to CB, and will also feel familiar to people used to pages written in mdoc(7).

**Comment by g-branden-robinson** [comment]
> The mdoc(7) macro package provides the .Ql macro exactly for this purpose: https://man.openbsd.org/mdoc.7#Ql In terminal output, .Ql encloses in single quotes. In typeset (e.g. PDF) output, it uses a CW font and additionally encloses in single quotes if the argument is very short because the reader might then overlook the font change. In HTML output (of course, mandoc(1) only, as groff doesn't provide a HTML output device good enough for real-world use),

I'd love to argue here, but I can't.  The line of attack I have in mind is to [give _tbl_ direct HTML output support](https://savannah.gnu.org/bugs/?60052), use GNU _eqn_'s long-standing MathML output mode, and [add an SVG output mode to GNU _pic_](https://savannah.gnu.org/bugs/?62890).  If I understand aright, these would eliminate all of the reasons for the _pre-grohtml_ preprocessor.  That, in turn, would make `groff -Thtml` run faster and, most importantly of all, make the output driver *way* easier to debug.  It seems like every damn time I have attacked a _grohtml_ problem, the problem has arisen first in _pre-grohtml_ running `troff -Tps` first, and unfortunately that preprocessor is diligent about destroying as much evidence at the crime scene as it can.  For a long time it even lied about `troff`'s exit status.

This is a long-term project. 

> .Ql produces an element (code class="Li"). The "code"-tag provides reasonable (typical CW) formatting by default, and the "class"-attribute allows additional customization using CSS.
> 
> But the older man(7) language does not provide any similar functionality, not even if you are willing to aggressively use all GNU extensions. Consequently, the best solution i can think of would look something like this:
> 
> ```
> .PP
> This paragraph contains
> \(oq\f(CRinline code\fP\(cq
> in the middle.
> .PP
> ```
> 
> I expect that to be quite portable, even beyond the big three.

There is the problem of the `oq` and `cq` special character identifiers not being portable beyond that horizon, which in turn is the fault of AT&T _troff_ for deciding, as with font identifiers, that no portability was required for such things.

This one is a more superable problem (with string definitions in the _man_ document, as Thomas Dickey does, or by trivial edits to font description files in _troff_ implementations), however.

> Obviously, mandoc cannot produce a "code"-tag from that, but that's a limitation of the man(7) language and not mandoc(1)'s fault.

I'd be remiss if I didn't point out [my ambition to add a quotation macro to _man_(7)](
https://lists.gnu.org/archive/html/groff/2022-12/msg00078.html).

> Indeed, defining your own macros in a manual page sets you up for a trip on the highway to hell (pod2man being the singular exception that confirms the rule rather than casting doubt on it, as discussed), and defining a custom macro to wrap standard ones sounds even worse. Even Branden, who usually tends be bolder and less timid with respect to compatibility questions than i am, was visibly shaking when reluctantly considering whether he should really provide such advice. :-o

:-P

> I think enclosing in single quotes is less intrusive and less confusing than switching to CB, and will also feel familiar to people used to pages written in mdoc(7).

Double quotes will feel more familiar to North Americans.  ;-)

In any case, you want to be quoting multi-word inline literals, particularly in case formatting gets stripped, as happens when people forget to run _mandoc_(1)'s output through _ul_(1), or paste man page contents into emails.

I would also add that I find inline family changes a bit uncomfortable to read.  Worse than bold?  I'm not sure.

**Comment by jgm** [comment]
> I think enclosing in single quotes is less intrusive and less confusing than switching to CB, and will also feel familiar to people used to pages written in mdoc(7).

I'm not sure I like this as a general solution, because

1) the inline code you're writing might contain `'` characters and then it could be very confusing -- though it's unlikely that it would contain curly quotes
2) authors might manually include quotes, e.g. markdown `` '`foo`' ``, and then we'll get them doubled.

**Comment by jgm** [comment]
Looks like the best solution might be using `\f(CB` or `\f[CB]` for inline code. The drawback is that users wouldn't be able to change that with a change to the template.

**Comment by ischwarze** [comment]
>> I think enclosing in single quotes is less intrusive and less confusing than switching to CB, and will also feel familiar to people used to pages written in mdoc(7).

> I'm not sure I like this as a general solution, because
>     1. the inline code you're writing might contain `'` characters and then it could be very confusing -- though it's unlikely that it would contain curly quotes
>     2. authors might manually include quotes, e.g. markdown `` '`foo`' ``, and then we'll get them doubled.

Well, you are writing a translation tool, so the tool can parse the content and decide accordingly.
For example, if the inline code in question has already been enclosed in any kind of quotes by the document author, your tool can skip writing the \(oq\(cq.  Or if the inline code contains single quotes, your tool could issue \(lq\(rq instead of the normal \(oq\(cq.  I'm not saying that must be done, but *if* you worry about such corner cases, that's one way out, and you can adapt the amount of effort you put into that according to how much you worry about potential ugliness.  The main point to remember here is that it's fine if your tool makes such conditional decisions and then emits characters that fit the situation - but that you should *not* attempt to code conditionals by abusing low-level roff(7) code, which doesn't belong in manual page source code.

Of course, going for \f(CB for inline code is not out of the question either.  I have occasionally seen printed books use bold face for sample code.  Then again, manual pages usually do *not* use bold face for such purposes, so it might perhaps confuse some readers, and besides, it's also slightly confusing if inline code samples end up using a different font compared to displayed code samples - and displayed code samples should almost certainly use .EX without any manual font fiddling.

**Comment by jgm** [comment]
I've just push a couple changes that implement some of the suggestions made here.
The sample above now becomes
```
.PP
Paragraph with \f[CR]inline code\f[R]
.IP
.EX
Code block line 1
Code block line 2
Code block line 3
.EE
```

**Comment by hickford** [comment]
@jgm @ischwarze @g-branden-robinson thank you for your thorough collaboration and prompt fix!

I regenerated with my man page

**Comment by ischwarze** [comment]
> I regenerated with my man page, fixing the warnings [hickford/git-credential-oauth@99abc35](https://github.com/hickford/git-credential-oauth/commit/99abc3550e7cc468c186d84e96126bda4a6cef02)

Indeed, the man(7) code generated by Pandoc 3.1.7 is massively better regarding style, reliability, and portability than what you got from Pandoc 3.1.2 in the past.  Really glad that so much progress was made here, this will probably save other Pandoc users quite some grief as well.
