### ISSUE TITLE
citeproc replaces 'and' with semicolon in publisher field

### ISSUE THREAD

**Issue by bbolker** [jgm/pandoc#9051]
When the word 'and' occurs in a publisher field in a bibliography, citeproc seems (??) to convert it to a semicolon. Specifically, running `pandoc test2.md --citeproc` for a bib entry that has "Chapman and Hall/CRC" in the publisher field outputs an entry with "Chapman; Hall/CRC".  This is with pandoc 3.1.7.  This is with the default CSL, it seems to also happen with a version of `apa.csl` I have lying around ...

I searched for other issues etc. referring to this but failed to find any.

Here's `test2.md`:

```
---
title: "STATS 720 bibliography"
bibliography: "test2.bib"
nocite: '@*'
---

hello world
```

and here's `test2.bib`:

```
@book{chambersStatistical1991,
	title = {Statistical {Models} in {S}},
	publisher = {Chapman and Hall/CRC},
	editor = {Chambers, J. M. and Hastie, T. J.},
	year = {1991}
}
```

And the full output:

```
<p>hello world</p>
<div id="refs" class="references csl-bib-body hanging-indent"
role="list">
<div id="ref-chambersStatistical1991" class="csl-entry" role="listitem">
Chambers, J. M., and T. J. Hastie, eds. 1991. <em>Statistical
<span>Models</span> in <span>S</span></em>. Chapman; Hall/CRC.
</div>
</div>
```

**Comment by jgm** [comment]
The `and` in a bibtex `author` field is just used to concatenate authors; howe multiple authors are rendered is up to the style.

It looks like our parser is treating `and` in the `publisher` field the same way. (You could defeat this by putting the whole publisher name in an extra layer of `{...}`.)

This might be a bug if it doesn't accord with the way bibtex works.

**Comment by jgm** [comment]
Code has
```hs
    pubfields <- mapM (\f -> Just `fmap`
                         (if variant == Bibtex || f == "howpublished"
                          then getField f
                          else getLiteralList' f)
                        <|> return Nothing)
```
Here, `getLiteralList'` will split the item on "and" and add semicolons.  So that explains why this is happening. Interestingly, this looks intentional: we explicitly do this only for biblatex, not for bibtex.  I'm not sure why, but it would be worth testing this with latex + bibtex and then biblatex to see if there is actually a difference in the treatment of the `publisher` field.

**Comment by bbolker** [comment]
Actually, I now see that this is a `biblatex` vs `bibtex` thing.  From [the biblatex manual](https://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf) section 2.3.4

> All of these fields [institution, organization, publisher, etc.] may contain a list of items separated by the keyword ‘and’. If they contain a literal ‘and’, it must be wrapped in braces.

What I hadn't realized but see looking [here](https://quarto.org/docs/authoring/footnotes-and-citations.html) is that a bibliographic database file with the `.bib` extension is automatically interpreted as biblatex, while BibTeX is reserved for `.bibtex` extensions ...  so what was happening is that I was switching over to biblatex without realizing it.

**Comment by jgm** [comment]
I see we have some test cases with multiple publishers.
In those cases the expectation was that we'd get an array of multiple publishers when converting to CSL.
The problem is that `and` isn't a reliable way to separate multiple publishers in bibtex, because `and` is a common word *in* publisher names.
Perhaps @adunning could help us here.

**Comment by jgm** [comment]
Ah, good to have that worked out.
