### ISSUE TITLE
Section numbers do not render to docx/odt TOC

### ISSUE THREAD

**Issue by volkerjaenisch** [jgm/pandoc#9244]
Dear Pandoc People, you are making a really good job!

Maybe a beginners error.

Given the markdown

test.md:

```
# top

## top-1

### top -3
```

and the command line

`pandoc -f markdown -t docx test.md -o test.docx --number-sections --toc -s`

The result opens in Libre-Office as:

![image](https://github.com/jgm/pandoc/assets/2539336/19d7765c-38d2-4d86-82cf-e20a0a4bebfc)

This is independent of the output format docx/dot used.

Am I doing something stupid/wrong?

Any help appreciated

Volker

System:
 * Debian Bookworm
 * PanDoc 3.1.9-1 installed via debian package download.

**Comment by jgm** [comment]
The toc is implemented in docx via a "field" that generates the table of contents in Word when the document is opened.  The XML for this is

```xml
<w:fldChar w:fldCharType="begin" w:dirty="true" /><w:instrText xml:space="preserve">TOC \o &quot;1-3&quot; \h \z \u</w:instrText><w:fldChar w:fldCharType="separate" /><w:fldChar w:fldCharType="end" />
```
(This is necessary because only with Word's layout do we have the page numbers for the sections.)  Apparently Libre Office doesn't process this field.  There's nothing we can do on the pandoc side.
