### ISSUE TITLE
man pages are missing from hackage distributed `pandoc-cli` tarball

### ISSUE THREAD

**Issue by jonassmedegaard** [jgm/pandoc#9245]
man directory is located at the root of the Github project, but belongs to the pandoc-cli hackage distribution - where it is not included.

**Comment by jgm** [comment]
I've moved the man pages to pandoc-cli.
If it would help you, I could create a new release of pandoc-cli with these included.

**Comment by jgm** [comment]
Hm.  If the man pages are in pandoc-cli, then I think maybe I do need to synchronize pandoc-cli with pandoc in the way I described elsewhere. The man pages describe a particular version of pandoc and will only make sense if the executable is built against that particular version.

**Comment by jgm** [comment]
Alternatively we could move the man pages back to pandoc...odd as that is.

**Comment by jonassmedegaard** [comment]
For Debian redistribution specifically, I have worked around this issue by having the Debian source package which corresponds with upstream `pandoc-cli` project use Github source as its source.
There is no need to do any particular upstream setup to help the Debian use-case - this issue was raised for the more general logic of "the project to build an executable binary seems to be the sensible project to also carry a man page for that same executable binary", but it is arguably sensible for a library to provide assets for supporting CLI tools.

And as for issueing a release, even if the Debian use-case were affected, we could not directly benefit from a new release, because we maintain only a single version of each Haskell library and they are all kept compatible, which means it is only rarely possible to update to newest release of Pandoc.

**Comment by jgm** [comment]
Understood. Well, assuming I stick with this plan, going forward you'd be able to simplify things and use official release tarballs rather than GitHub source (once you caught up to whatever the next release after 3.1.9 will be).

In any case, the plan has motivations independent of packaging.  I agree with you that it makes sense to have the man pages with pandoc-cli, but that makes it attractive to pin the pandoc version. Pinning the version is also important if we want to make it easy to install a particular pandoc version via `cabal install` or `stack install`.
