### ISSUE TITLE
Pdf to md

### ISSUE THREAD

**Issue by johnfelipe** [jgm/pandoc#9351]
Is important have this flow
Pdf to markdown
Pls put asap

**Comment by alerque** [comment]
There are lots of tools out there for this, each with their own tradoffs. PDF is not a document format it is a display format and it not suited to conversion to other formats. Some tools do try to recreate some of the layout, others work at extracting the text string, others focus on OCR aspects (since PDFs frequently have rasterized content) but none of them are or even will be a really good reliable conversion. All of them are some combination of lossy / messy. It is possible to stay relatively true to the visual presentation by converting to another presentation-oriented format or make guesses about how those elements assemble into a text string, but there little to no structural data do go on.

As such Pandoc is not well suited to playing in this space. There is simply no reasonable way to recover structured markup as represented by the Pandoc AST or most of the formats understood by Pandoc from PDFs. You'll want to evaluate what you are trying to accomplish and what tooling works "best" for your inputs and output goals.

(Also your request comes off as pretty entitled. When you post a feature request on an open source project: "it is important that you do this huge thing nobody else has accomplished and do it soon and for free" is not the right foot to start on.)

**Comment by tarleb** [comment]
See also issue #8682, among others.

**Comment by johnfelipe** [comment]
Sorry for comment with little details
https://products.aspose.app/words/es/conversion/pdf-to-md

That is online till I use, and is good formatting in MD format, but when pdf is huge, 15 or 20 MB not working then I want to try something locally

If you have another suggestion or may be in your app, add pdf option like input, not matter size....

Sorry again
Best regards
