### ISSUE TITLE
chunkedhtml: header shift

### ISSUE THREAD

**Issue by iagobaapellaniz** [jgm/pandoc#9398]
Let's say we have the following document structure
```markdown
---
title: Book
---

# 1st chapter

### A sub-section
```

Clearly html and chunkedhtml should produce similar results. 
In one case (html writer) we have 
```html
<h1 id="st-chapter">1st chapter</h1>
<h3 id="a-sub-section">A sub-section</h3>
```
and in the other (chunkedhtml writer)
```html
<h1 data-number="1" id="st-chapter">1st chapter</h1>
<h2 data-number="1.1" id="a-sub-section">A sub-section</h2>
```
Note the `h2` and `h3`. I consider this a bug since the author loses control on the level of the header compared with other witters.

For completeness, I also show the result with the LaTex writer which keeps the relative level differences
```latex
\section{1st chapter}\label{st-chapter}

\subsubsection{A sub-section}\label{a-sub-section}
```

**Pandoc version**
v1.23.1, MacOS

**Comment by jgm** [comment]
Why, in a hierarchical document, would you want gaps between header levels? That will lead to strange results with, e.g., section numbering.

This behavior is due to `makeSections`, which documents:

``` hs
-- If the baseLevel parameter is Just n, Header levels are                      
-- adjusted to be gapless starting at level n.                                  
makeSections :: Bool -> Maybe Int -> [Block] -> [Block]
```

We currently have this as a parameter in `splitIntoChunks` -- so that if you pass in `Nothing`, it will preserve header level, and if you pass in `Just n`, it will make them gapless starting at n.

When we call `splitIntoChunks` in `writeChunkedHTML`, we set this parameter to `Just 1`, which is why we get this behavior. Changing that to `Nothing` would preserve the author's header levels.

I'm not really sure what is best here; it would be useful to get comments from more people.
