### ISSUE TITLE
svg self-contained fix in #9206 is insufficient

### ISSUE THREAD

**Issue by cscheid** [jgm/pandoc#9420]
The SVG ID replacements in https://github.com/jgm/pandoc/commit/fc3d202e3f758cc11e1853720e6bfa9860f0dc16 are insufficient in the presence of clipping paths and other SVG features that use the IDs inside attribute values. Consider the following:

### index.md

```
![](./bad-svg.svg)
```

### bad-svg.svg

```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="504pt" height="360pt" viewBox="0 0 504 360" version="1.1">
<defs>
<clipPath id="clip1-c3ce354c">
  <path/>
</clipPath>
</defs>
<g clip-path="url(#clip1-c3ce354c)" clip-rule="nonzero"></g>
</svg>
```

## Repro

```
$ pandoc --embed-resources index.md
<p><svg id="svg_869cc2c64ecd3ae75656" width="504pt" height="360pt" viewBox="0 0 504 360">
<defs>
<clipPath id="svg_869cc2c64ecd3ae75656_clip1-c3ce354c">
  <path />
</clipPath>
</defs>
<g clip-path="url(#clip1-c3ce354c)" clip-rule="nonzero"></g>
</svg></p>
$ pandoc --version
pandoc 3.1.11
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/cscheid/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

The clipping path references the wrong ID now. (This was reported to Quarto users in https://github.com/quarto-dev/quarto-cli/issues/8619)

**Comment by jgm** [comment]
If I understand correctly, we just need to improve `addIdPrefix` a bit, matching on
`clip-path` with `url(#XXX)` and replacing `XXX` with `SVGID_XXX`.
That should be a fairly easy change.

**Comment by PeterSommerlad** [comment]
It seems this fix was insufficient to support gradients in SVG. While clipping now works, Gradient areas are shown black in Safari denoting a problem.  I'll attache a small example and experiments that I did. to demonstrate the missing things

* A markdown file with tikz image using the filter diagram.lua `Test.md`
* the output produced from pandoc as html using `pandoc -s -t html --embed-resources --standalone -L diagram.lua -o Test.html Test.md `
* The intermediate pdf produced by diagram.lua that I hacked to keep it around: `TestImage.pdf`
* The SVG file produced by `inkscape --export-plain-svg --export-filename=./TesDirectInkscape.svg ./TestImage.pdf`
* And a html file, where I copied the SVG file of the previous step into the above `Test.html` where one sees that the browser now renders both correctly, so it is definitely an issue with some ids not transformed correctly by pandoc: `TestBothPandocAndInkscapeSVGRendercorrectlyTogehter.html`

It took me about a week to find the culprit (it worked with earlier versions somehow) and the clipping was fixed by above changes but they were insufficient for gradient shadings.

* [Test.md](https://github.com/jgm/pandoc/files/14308565/Test.md)
* [Test.html.txt](https://github.com/jgm/pandoc/files/14308580/Test.html.txt)
* [TestImage.pdf](https://github.com/jgm/pandoc/files/14308564/TestImage.pdf)
* TestDirectInkscapeConversion ![TestDirectInkscape](https://github.com/jgm/pandoc/assets/1725845/ca599372-4f17-46d4-a39d-4ded1387a2e1)
* [TestBothPandocAndInkscapeSVGRendercorrectlyTogehter.html.txt](https://github.com/jgm/pandoc/files/14308586/TestBothPandocAndInkscapeSVGRendercorrectlyTogehter.html.txt)

**Comment by jgm** [comment]
@PeterSommerlad please submit a separate issue for this.

**Comment by PeterSommerlad** [comment]
already did as #9467
