### ISSUE TITLE
Latex: `header-includes:` works via `--metadata-file` but not via `--metadata`

### ISSUE THREAD

**Issue by camoz** [jgm/pandoc#9474]
## Input files

`input.md`:

```
hello world
```

`meta.yaml`:

```
header-includes: \renewcommand*{\familydefault}{\sfdefault}
```

`defaults.yaml`:

```
metadata:
  header-includes: \renewcommand*{\familydefault}{\sfdefault}
```

## Works

`pandoc --metadata-file meta.yaml -o output.pdf input.md` produces a PDF with sans serif font, as expected.

## Does not work

- `pandoc -d defaults.yaml -o output.pdf input.md`
- `pandoc -M 'header-includes: \renewcommand*{\familydefault}{\sfdefault}' -o output.pdf input.md`
- ``pandoc -M 'header-includes: `\renewcommand*{\familydefault}{\sfdefault}`{=latex}' -o output.pdf input.md``

They all fail with:

```
Error producing PDF.
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.43 \textbackslash
```

## Additional info

- If I convert directly to latex, the output is always `hello world`
- Putting the `header-includes` directly in the markdown file (YAML block) works as expected.
- I found a few similar issues but none of them seem to be exactly this issue. Sorry if I missed something, I'm quite new to pandoc.
- **OS**: Archlinux
- **Pandoc versions:** 3.1.12.1 and 3.1.6.2 (both behave the same)

**Comment by jgm** [comment]
This is as documented.

See the manual for `--metadata-file`:

> (If the input format is Markdown or a Markdown variant, then the same variant will be used to parse the metadata file; if it is a non-Markdown format, pandoc’s default Markdown extensions will be used.)

Vs `--metadata`:

>  Values will be parsed as YAML boolean or string values


The other relevant fact is that pandoc's markdown will parse things like `\renewcommand` as raw LaTeX rather than literal strigs.

What this means is that when you just use `-M`, you'll get a literal string, which will be escaped in LaTeX output; when you use `--metadata-file`, the `\renewcommand` will be parsed as a raw LaTeX element, which will be passed through unescaped.

To understand this better, you can experiment with `-t native`.

**Comment by camoz** [comment]
Very late, but still I want to thank you for the explanation, that helped!
