### ISSUE TITLE
Include nginx and shell  or sh (link to bash) to supported highlight languages

### ISSUE THREAD

**Issue by anutator** [jgm/pandoc#9544]
Markdown correctly highlight nginx web server code blocks (nginx) , but when I try to export it to .epub format there is no code syntax.
Besides there are several variants of bash — sh or shell,  in Markdown they a treated as bash. Please add additional languages.

**Comment by jgm** [comment]
I'm sorry, I don't really understand the issue clearly.

`nginx` is not a supported syntax for pandoc's highlighting, so I'm not sure why you say "Markdown correctly highlights" it.  Perhaps you mean some other program than pandoc?

We support `bash`, `zsh`, `tcsh`.  It is possible to add others, but we derive them from KDE syntax definitions so they'd need to be defined there.

Highlighting in pandoc is done by jgm/skylighting, so that's where you'd need to make a request for specific additional syntaxes.

**Comment by jgm** [comment]
It is also possible to use the pandoc option `--syntax-definition=nginx.xml` with KDE's `nginx.xml` to get highlighting for nginx, even without changes to skylighting.
You'll need to get nginx.xml from KDE's repository ; links can be found in the README for skylighting, linked aboe.
