### ISSUE TITLE
Lists are destructured when converting from Markdown to Docx

### ISSUE THREAD

**Issue by anadon** [jgm/pandoc#9547]
When converting from Markdown to Docx using version 3.1.11 On Ubuntu 23.10 by invoking `pandoc programming-as-literature.md -o programming-as-literature.docx` the resulting document does not contain bulleted lists which were present in the original document.

![image](https://github.com/jgm/pandoc/assets/3113477/1d53b514-51ca-4a50-9aed-b3ce89a2798c)
![image](https://github.com/jgm/pandoc/assets/3113477/292d7fdd-09aa-4130-9605-54646d77581f)
[programming-as-literature.md](https://github.com/jgm/pandoc/files/14502353/programming-as-literature.md)
[programming-as-literature.docx](https://github.com/jgm/pandoc/files/14502354/programming-as-literature.docx)

I have searched the issues, and the closest items look like #7280 #6663 and #4544 but these look like more complex issues.

**Comment by anadon** [comment]
Here's what I think the docx should look like.
[programming-as-literature-hand-corrected-formatting.docx](https://github.com/jgm/pandoc/files/14502624/programming-as-literature-hand-corrected-formatting.docx)

**Comment by jgm** [comment]
You can use `pandoc -t native` to see how pandoc is parsing this. You'll see that the list is not parsed as a list. Why not?  Well, pandoc's markdown requires a blank line before a list, to avoid false positives on lists (e.g. when a number followed by a period gets wrapped to the beginning of a line -- there was actually a test case like this in the original Markdown.pl test suite).

This requirement used to be common (following original Markdown.pl), but now that commonmark has allowed omitting the space, it is less common. See [babelmark](https://babelmark.github.io/?text=hi%0A*+there%0A).

Anyway, the solution for you is to use `-f commonmark` or `-f gfm` or `-f commonmark_x` instead of the default `-f markdown`.
