### ISSUE TITLE
Wrong list style with nested lists when converting to docx

### ISSUE THREAD

**Issue by logicsalad** [jgm/pandoc#9969]
There seems to be a bug in the newest pandoc version 3.2.1.
When I convert a nested list from markdown to docx I get wrong list styles in the output file.
When using the previous pandoc version 3.2 the output is correct.

Input file `nested_lists.md`:
```
1.  This is a numbered item
    -   This is a bullet subitem
    -   This is a bullet subitem
    -   This is a bullet subitem
2.  This is a numbered item
    a)  This is a letter subitem
    b)  This is a letter subitem
3.  This is a numbered item
4.  This is a numbered item
```
Command line:
```
pandoc -o nested_lists.docx nested_lists.md
```

Output `nested_lists.docx` opened in Word 2016:
![pandoc_numbered_lists_docx](https://github.com/jgm/pandoc/assets/59561160/e879b22c-ebe7-4e13-abc8-ff93386296fd)

**Comment by khalid-hussain** [comment]
I just faced the same problem today with "loose" lists. I think it's only the `docx` writer since the `html` output is fine.

Markdown I tested:

```
44. First para of first item.

    Second para of first item.

    1. First para of first sub item.

    2. Second para of first sub item.

45. First para of second item.
```

Commands used:

```
$ pandoc test.md -o test.docx
```

and:

```
$ pandoc test.md -o test.html -s
```

Docx output in Word 365:

![image](https://github.com/user-attachments/assets/55ad0de4-345e-4821-ab23-f49dd540dc71)

HTML output:

<img width="50%" height="50%" src="https://github.com/user-attachments/assets/eb8967c7-850d-41fe-b2fb-88b61089792c">

**Comment by logicsalad** [comment]
Solved in v.3.3. See also duplicate issue #9990 and #9994.
