### ISSUE TITLE
Issue with pandoc.Header

### ISSUE THREAD

**Issue by myfta** [jgm/pandoc#9983]
I have an issue with the Header constructor pandoc.Header. The Guide says its syntax is `Header (level, content[, attr])`

So I have created a Lua filte with the following content
```
function Strong (element)
  return pandoc.Header(1,element.content)
end
```
but this throws an error:
```
Error running filter strong_header.lua:
Inline, list of Inlines, or string expected, got Block
```

Conversely the pandoc.Emph works as expected with
```
function Strong (element)
  return pandoc.Emph(element.content)
end
```
Pandoc version 3.2.1 on Windows.

**Comment by tarleb** [comment]
Pandoc distinguishes between elements that can be part of a paragraph, and elements that make up the bigger structure of a document. The former are called *Inline* elements, and the latter *Block* elements. `Strong`is an Inline element, and `Header` is a Block, but Block elements cannot replace inline elements. So the error is correct.

You'll probably want to filter on `Para` elements and check if all of the paragraph content is strongly emphasized, because then you can replace the `Para` with a `Header`.

**Comment by myfta** [comment]
OK, so how do I replace HTML that includes both _Inline_ and _Block_ elements.

My case is I want to change
`<p><strong>...</strong></p>`
to
`<h1>...</h1>`

Thanks.

**Comment by jgm** [comment]
You'll need to match a Para whose children are exactly one Strong inline element, and replace it with a Header whose children are the contents of that Strong inline.

**Comment by myfta** [comment]
> You'll need to match a Para whose children are exactly one Strong inline element, and replace it with a Header whose children are the contents of that Strong inline.

Any clues as to how to achieve this?

Thanks
