### ISSUE TITLE
Typst Writer Cannot Create a Proper Horizontal Rule

### ISSUE THREAD

**Issue by thekief** [jgm/pandoc#9991]
I noticed that the Typst writer uses the following code to generate a horizontal line that spans across the page:

https://github.com/jgm/pandoc/blob/8613aa39e8b5b8282f30b9fd48b04ec2595ec8eb/src/Text/Pandoc/Writers/Typst.hs#L168-L169

This function does not exist in Typst to the best of my knowledge and led to issues while compiling a document. Instead the valid function to create a horizontal rule would be `#line(length: 100%)` according to the documentation [^1] .

[^1]: https://typst.app/docs/reference/visualize/line/

**Comment by jgm** [comment]
We use a custom function defined in the default typst template, since people may want different styles of horizontal rules. You can copy the definition from there. Note that our typst output presupposes several definitions from the default template, so if you use a custom template you should include them.  If you are not using `-s` or `--standalone`, no template is being used -- try just adding `-s`.
